from manim import *

# Band-layout whiteboard scene for the revision duo "Development, Resources
# and Sustainability Essentials" (grade 11, term 4). All seven subtopics:
# Part 1 Expert (1-4), Part 2 Simplifier (5-7). Band time apportioned to
# subtopics.json (255/255/260/250/195/195/195 of 1605 s). Exporter-safe
# primitives only; core-periphery and the erosion ladder are hand-built
# from Line/Arrow/Circle/Rectangle/Tex.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class DevelopmentResourcesSustainabilitySession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic full-screen while intro.md audio plays.
        self.wait(15)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): measuring development
        title = Tex("Development, Resources, Sustainability").scale(1.15).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex(r"Development $\neq$ growth: quality of lives,").scale(1.0).shift(UP * 1.3)
        b0_l2 = Tex(r"not just size of the economy").scale(1.0).shift(UP * 0.6)
        self.play(Write(b0_l1))
        self.play(Write(b0_l2))
        self.wait(2.5)
        b0_l3 = Tex(r"GDP: made inside; GNI: earned anywhere;").scale(0.95).shift(DOWN * 0.3)
        b0_l4 = Tex(r"take both PER CAPITA to compare").scale(0.95).shift(DOWN * 1.0)
        self.play(Write(b0_l3))
        self.play(Write(b0_l4))
        self.wait(2.5)
        b0_l5 = Tex(r"Gini: inequality 0 to 1 — SA among highest").scale(0.95).shift(DOWN * 1.9)
        self.play(Write(b0_l5))
        self.wait(2)
        b0_l6 = Tex(r"HDI: health $+$ knowledge $+$ living standard").scale(0.95).shift(DOWN * 2.7)
        self.play(Write(b0_l6))
        self.play(Create(SurroundingRectangle(b0_l6, color=GREEN)))
        self.wait(3)

        # --- Band 1 (subtopic_1): core-periphery and Rostow
        self.next_band(1)
        b1_title = Tex("Core--periphery and Rostow").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        core = Circle(radius=0.8, color=YELLOW).shift(band_shift(1) + UP * 0.6 + LEFT * 2.8)
        core_lab = Tex("CORE").scale(0.9).shift(band_shift(1) + UP * 0.6 + LEFT * 2.8)
        peri = Circle(radius=0.8, color=BLUE).shift(band_shift(1) + UP * 0.6 + RIGHT * 2.8)
        peri_lab = Tex("PERIPHERY").scale(0.7).shift(band_shift(1) + UP * 0.6 + RIGHT * 2.8)
        self.play(Create(core), Write(core_lab))
        self.play(Create(peri), Write(peri_lab))
        a_in = Arrow(band_shift(1) + UP * 0.9 + RIGHT * 1.9, band_shift(1) + UP * 0.9 + LEFT * 1.9, color=GREEN)
        a_in_lab = Tex("labour, raw materials").scale(0.8).shift(band_shift(1) + UP * 1.5)
        a_out = Arrow(band_shift(1) + UP * 0.3 + LEFT * 1.9, band_shift(1) + UP * 0.3 + RIGHT * 1.9, color=RED)
        a_out_lab = Tex("remittances").scale(0.8).shift(band_shift(1) + DOWN * 0.3)
        self.play(Create(a_in), Write(a_in_lab))
        self.play(Create(a_out), Write(a_out_lab))
        self.wait(2.5)
        b1_l1 = Tex(r"Gauteng core; former homelands periphery —").scale(0.9).shift(band_shift(1) + DOWN * 1.1)
        b1_l2 = Tex(r"the model scales: world, country, city").scale(0.9).shift(band_shift(1) + DOWN * 1.8)
        self.play(Write(b1_l1))
        self.play(Write(b1_l2))
        self.wait(2.5)
        b1_l3 = Tex(r"Rostow: 5 stages; criticise it — one Western").scale(0.9).shift(band_shift(1) + DOWN * 2.6)
        b1_l4 = Tex(r"staircase, ignores colonial history").scale(0.9).shift(band_shift(1) + DOWN * 3.3)
        self.play(Write(b1_l3))
        self.play(Write(b1_l4))
        self.wait(3)

        # --- Band 2 (subtopic_2): the trade rules
        self.next_band(2)
        b2_title = Tex("Trade: the rules of the game").scale(1.2).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(1.5)
        b2_l1 = Tex(r"Colonial pattern persists: primary out,").scale(0.95).shift(band_shift(2) + UP * 1.3)
        b2_l2 = Tex(r"manufactured in — the price trap").scale(0.95).shift(band_shift(2) + UP * 0.6)
        self.play(Write(b2_l1))
        self.play(Write(b2_l2))
        self.wait(2.5)
        b2_l3 = MathTex(r"\text{Terms of trade} = \frac{\text{export prices}}{\text{import prices}}").scale(0.86).shift(band_shift(2) + DOWN * 0.4)
        self.play(Write(b2_l3))
        self.wait(2.5)
        b2_l4 = Tex(r"Drifts against raw exporters — escape by").scale(0.95).shift(band_shift(2) + DOWN * 1.4)
        b2_l5 = Tex(r"BENEFICIATION: jewellery, not raw gold").scale(0.95).shift(band_shift(2) + DOWN * 2.1)
        self.play(Write(b2_l4))
        self.play(Write(b2_l5))
        self.play(Create(SurroundingRectangle(b2_l5, color=GREEN)))
        self.wait(2.5)
        b2_l6 = Tex(r"Free trade preached, farm subsidies practised;").scale(0.9).shift(band_shift(2) + DOWN * 3.0)
        b2_l7 = Tex(r"SA trades via BRICS and AfCFTA").scale(0.9).shift(band_shift(2) + DOWN * 3.7)
        self.play(Write(b2_l6))
        self.play(Write(b2_l7))
        self.wait(3)

        # --- Band 3 (subtopic_2): aid, argued both ways
        self.next_band(3)
        b3_title = Tex("Aid: argue it both ways").scale(1.2).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(1.5)
        b3_l1 = Tex(r"Types: humanitarian, development, technical,").scale(0.9).shift(band_shift(3) + UP * 1.3)
        b3_l2 = Tex(r"multilateral vs bilateral, tied (strings)").scale(0.9).shift(band_shift(3) + UP * 0.6)
        self.play(Write(b3_l1))
        self.play(Write(b3_l2))
        self.wait(2.5)
        b3_l3 = Tex(r"For: saves lives, builds clinics and dams,").scale(0.95).shift(band_shift(3) + DOWN * 0.3)
        b3_l4 = Tex(r"transfers skills, beat HIV at scale").scale(0.95).shift(band_shift(3) + DOWN * 1.0)
        self.play(Write(b3_l3))
        self.play(Write(b3_l4))
        self.wait(2.5)
        b3_l5 = Tex(r"Against: dependency, corruption leaks,").scale(0.95).shift(band_shift(3) + DOWN * 1.9)
        b3_l6 = Tex(r"tied aid serves the donor, debt traps").scale(0.95).shift(band_shift(3) + DOWN * 2.6)
        self.play(Write(b3_l5))
        self.play(Write(b3_l6))
        self.wait(2.5)
        b3_l7 = Tex(r"Fair trade and capacity beat charity").scale(1.0).shift(band_shift(3) + DOWN * 3.5)
        self.play(Write(b3_l7))
        self.play(Create(SurroundingRectangle(b3_l7, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): conventional energy
        self.next_band(4)
        b4_title = Tex("Powering the country: conventional").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(1.5)
        b4_l1 = Tex(r"Over $\tfrac{4}{5}$ coal, stations on the seams").scale(1.0).shift(band_shift(4) + UP * 1.3)
        self.play(Write(b4_l1))
        self.wait(2)
        b4_l2 = Tex(r"coal $\to$ steam $\to$ turbine $\to$ generator").scale(1.0).shift(band_shift(4) + UP * 0.5)
        self.play(Write(b4_l2))
        self.play(Create(SurroundingRectangle(b4_l2, color=GREEN)))
        self.wait(2.5)
        b4_l3 = Tex(r"Case: cheap, local, baseload, jobs.").scale(0.95).shift(band_shift(4) + DOWN * 0.4)
        b4_l4 = Tex(r"Charge sheet: CO$_2$, Highveld air, water,").scale(0.95).shift(band_shift(4) + DOWN * 1.1)
        b4_l5 = Tex(r"scars, acid mine drainage").scale(0.95).shift(band_shift(4) + DOWN * 1.8)
        self.play(Write(b4_l3))
        self.wait(2)
        self.play(Write(b4_l4))
        self.play(Write(b4_l5))
        self.wait(2.5)
        b4_l6 = Tex(r"Koeberg low-carbon but costly, century waste;").scale(0.9).shift(band_shift(4) + DOWN * 2.6)
        b4_l7 = Tex(r"hydro small; pumped storage $=$ giant battery").scale(0.9).shift(band_shift(4) + DOWN * 3.3)
        self.play(Write(b4_l6))
        self.play(Write(b4_l7))
        self.wait(3)

        # --- Band 5 (subtopic_3): non-conventional energy
        self.next_band(5)
        b5_title = Tex("The other lane: sun and wind").scale(1.2).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(1.5)
        b5_l1 = Tex(r"Northern Cape: world-class sun — PV farms,").scale(0.95).shift(band_shift(5) + UP * 1.3)
        b5_l2 = Tex(r"molten-salt mirrors generate after dark").scale(0.95).shift(band_shift(5) + UP * 0.6)
        self.play(Write(b5_l1))
        self.play(Write(b5_l2))
        self.wait(2.5)
        b5_l3 = Tex(r"Cape coasts: turbines, Jeffreys Bay north").scale(0.95).shift(band_shift(5) + DOWN * 0.3)
        self.play(Write(b5_l3))
        self.wait(2)
        b5_l4 = Tex(r"REIPPPP bidding drove prices below new coal").scale(0.95).shift(band_shift(5) + DOWN * 1.1)
        self.play(Write(b5_l4))
        self.play(Create(SurroundingRectangle(b5_l4, color=GREEN)))
        self.wait(2.5)
        b5_l5 = Tex(r"But intermittency: needs storage, backup,").scale(0.95).shift(band_shift(5) + DOWN * 2.0)
        b5_l6 = Tex(r"stronger grid — and a JUST TRANSITION").scale(0.95).shift(band_shift(5) + DOWN * 2.7)
        b5_l7 = Tex(r"for the coalfield communities").scale(0.95).shift(band_shift(5) + DOWN * 3.4)
        self.play(Write(b5_l5))
        self.play(Write(b5_l6))
        self.play(Write(b5_l7))
        self.wait(3)

        # --- Band 6 (subtopic_4): the erosion ladder
        self.next_band(6)
        b6_title = Tex("Soil: the erosion ladder").scale(1.2).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(1.5)
        b6_l1 = Tex(r"Centuries to form, one storm to lose —").scale(0.95).shift(band_shift(6) + UP * 1.3)
        b6_l2 = Tex(r"non-renewable on any human timescale").scale(0.95).shift(band_shift(6) + UP * 0.6)
        self.play(Write(b6_l1))
        self.play(Write(b6_l2))
        self.wait(2.5)
        b6_l3 = Tex(r"Only 12\% arable, 3\% high-potential").scale(0.95).shift(band_shift(6) + DOWN * 0.2)
        self.play(Write(b6_l3))
        self.wait(2)
        b6_l4 = Tex(r"bare land $\to$ splash $\to$ sheet $\to$ rill $\to$ donga").scale(0.95).shift(band_shift(6) + DOWN * 1.1)
        self.play(Write(b6_l4))
        self.play(Create(SurroundingRectangle(b6_l4, color=GREEN)))
        self.wait(2.5)
        b6_l5 = Tex(r"Remedies: cover the ground, plough the").scale(0.95).shift(band_shift(6) + DOWN * 2.0)
        b6_l6 = Tex(r"contours, terrace, rotate, fence to carrying").scale(0.95).shift(band_shift(6) + DOWN * 2.7)
        b6_l7 = Tex(r"capacity; heal dongas with gabions").scale(0.95).shift(band_shift(6) + DOWN * 3.4)
        self.play(Write(b6_l5))
        self.play(Write(b6_l6))
        self.play(Write(b6_l7))
        self.wait(3)

        # --- Band 7 (subtopic_4): sustainability and the circle
        self.next_band(7)
        b7_title = Tex("Sustainability binds the year").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(1.5)
        b7_l1 = Tex(r"Meet present needs without compromising").scale(0.95).shift(band_shift(7) + UP * 1.3)
        b7_l2 = Tex(r"future generations' ability to meet theirs").scale(0.95).shift(band_shift(7) + UP * 0.6)
        self.play(Write(b7_l1))
        self.play(Write(b7_l2))
        self.play(Create(SurroundingRectangle(VGroup(b7_l1, b7_l2), color=GREEN)))
        self.wait(3)
        b7_l3 = Tex(r"Government: policy, procurement, carbon tax").scale(0.9).shift(band_shift(7) + DOWN * 0.4)
        b7_l4 = Tex(r"Business: clean power, audits, honesty").scale(0.9).shift(band_shift(7) + DOWN * 1.1)
        b7_l5 = Tex(r"Individuals: the kWh never used").scale(0.9).shift(band_shift(7) + DOWN * 1.8)
        self.play(Write(b7_l3))
        self.wait(1.8)
        self.play(Write(b7_l4))
        self.wait(1.8)
        self.play(Write(b7_l5))
        self.wait(2)
        b7_l6 = Tex(r"The circle: development needs energy; coal spends").scale(0.85).shift(band_shift(7) + DOWN * 2.6)
        b7_l7 = Tex(r"climate; storms strip soil; lost soil starves all").scale(0.85).shift(band_shift(7) + DOWN * 3.3)
        self.play(Write(b7_l6))
        self.play(Write(b7_l7))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): the scoreboard and the rigged shop
        self.next_band(8)
        b8_title = Tex("The scoreboard and the rigged shop").scale(1.15).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = Tex(r"GDP is total marks — fix 1: per learner;").scale(0.95).shift(band_shift(8) + UP * 1.3)
        b8_l2 = Tex(r"fix 2: check the spread (Gini);").scale(0.95).shift(band_shift(8) + UP * 0.6)
        b8_l3 = Tex(r"fix 3: follow money into lives (HDI)").scale(0.95).shift(band_shift(8) + DOWN * 0.1)
        self.play(Write(b8_l1))
        self.wait(2)
        self.play(Write(b8_l2))
        self.wait(2)
        self.play(Write(b8_l3))
        self.play(Create(SurroundingRectangle(b8_l3, color=GREEN)))
        self.wait(2.5)
        b8_l4 = Tex(r"Rigged shop: sell raw, buy finished —").scale(0.95).shift(band_shift(8) + DOWN * 1.0)
        b8_l5 = Tex(r"your trolley of ore buys less each year").scale(0.95).shift(band_shift(8) + DOWN * 1.7)
        self.play(Write(b8_l4))
        self.play(Write(b8_l5))
        self.wait(2.5)
        b8_l6 = Tex(r"Escape: start MAKING — beneficiation").scale(0.95).shift(band_shift(8) + DOWN * 2.5)
        self.play(Write(b8_l6))
        self.wait(2)
        b8_l7 = Tex(r"Aid: bakeries beat bread; fair rules beat both").scale(0.9).shift(band_shift(8) + DOWN * 3.3)
        self.play(Write(b8_l7))
        self.wait(3)

        # --- Band 9 (subtopic_6): the braai fire and the free fuels
        self.next_band(9)
        b9_title = Tex("The braai fire and the two free fuels").scale(1.1).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex(r"Coal fire: cheap, local, steady all night —").scale(0.95).shift(band_shift(9) + UP * 1.3)
        b9_l2 = Tex(r"but smoke, thirst, acid leaks, big bills").scale(0.95).shift(band_shift(9) + UP * 0.6)
        self.play(Write(b9_l1))
        self.play(Write(b9_l2))
        self.wait(2.5)
        b9_l3 = Tex(r"Free fuels: Upington mirrors store heat in").scale(0.95).shift(band_shift(9) + DOWN * 0.3)
        b9_l4 = Tex(r"salt; Cape winds spin turbine forests").scale(0.95).shift(band_shift(9) + DOWN * 1.0)
        self.play(Write(b9_l3))
        self.play(Write(b9_l4))
        self.wait(2.5)
        b9_l5 = Tex(r"But the sun clocks off: keep something").scale(0.95).shift(band_shift(9) + DOWN * 1.8)
        b9_l6 = Tex(r"steady, build batteries — Ingula's dam").scale(0.95).shift(band_shift(9) + DOWN * 2.5)
        self.play(Write(b9_l5))
        self.play(Write(b9_l6))
        self.wait(2.5)
        b9_l7 = Tex(r"Carry the coal towns across: just transition").scale(0.95).shift(band_shift(9) + DOWN * 3.3)
        self.play(Write(b9_l7))
        self.play(Create(SurroundingRectangle(b9_l7, color=GREEN)))
        self.wait(3)

        # --- Band 10 (subtopic_7): living off the interest
        self.next_band(10)
        b10_title = Tex("Living off the interest").scale(1.2).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_title))
        self.wait(2)
        b10_l1 = Tex(r"Soil: deposited a teaspoon a year,").scale(0.95).shift(band_shift(10) + UP * 1.3)
        b10_l2 = Tex(r"withdrawn by the bucket in one storm").scale(0.95).shift(band_shift(10) + UP * 0.6)
        self.play(Write(b10_l1))
        self.play(Write(b10_l2))
        self.wait(2.5)
        b10_l3 = Tex(r"bare veld $\to$ splash $\to$ sheet $\to$ rills $\to$ donga;").scale(0.9).shift(band_shift(10) + DOWN * 0.3)
        b10_l4 = Tex(r"cover, contour, terrace, rest, gabions").scale(0.9).shift(band_shift(10) + DOWN * 1.0)
        self.play(Write(b10_l3))
        self.play(Write(b10_l4))
        self.wait(2.5)
        b10_l5 = Tex(r"Bank rule: live off interest, never capital —").scale(0.95).shift(band_shift(10) + DOWN * 1.9)
        b10_l6 = Tex(r"coal is capital burning; sun is pure interest").scale(0.95).shift(band_shift(10) + DOWN * 2.6)
        self.play(Write(b10_l5))
        self.play(Write(b10_l6))
        self.play(Create(SurroundingRectangle(b10_l6, color=GREEN)))
        self.wait(2.5)
        b10_l7 = Tex(r"Walk the circle of the year, join by join").scale(1.0).shift(band_shift(10) + DOWN * 3.4)
        self.play(Write(b10_l7))
        self.wait(4)
