from manim import *

# Band-layout whiteboard scene for "Conservation of Energy and Power"
# (Part 1 Expert subtopics 1-4, Part 2 Simplifier subtopics 5-7).
# Exporter-safe vocabulary only; write-only reveals; camera moves between
# bands. Subtopic durations 235/235/240/240/195/195/195 of 1535 s.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class ConservationEnergyPowerSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): conservative vs non-conservative ---
        title = Tex("Conservation of Energy and Power").scale(1.25).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex("Conservative: work independent of path").scale(1.05).shift(UP * 1.2)
        b0_l2 = Tex("(gravity — repays in full, any route)").scale(1.0).shift(UP * 0.4)
        self.play(Write(b0_l1))
        self.wait(2)
        self.play(Write(b0_l2))
        self.wait(2)
        b0_l3 = Tex("Non-conservative: path matters").scale(1.05).shift(DOWN * 0.5)
        b0_l4 = Tex("(friction charges per metre, no refunds)").scale(1.0).shift(DOWN * 1.3)
        self.play(Write(b0_l3))
        self.wait(2)
        self.play(Write(b0_l4))
        self.wait(2)
        b0_l5 = MathTex(r"E_{mech} = E_k + E_p").scale(1.15).shift(DOWN * 2.4)
        self.play(Write(b0_l5))
        self.play(Create(SurroundingRectangle(b0_l5, color=GREEN)))
        self.wait(3)

        # --- Band 1 (subtopic_1): the principle, ball dropped from 10 m ---
        self.next_band(1)
        b1_title = Tex("No friction: $E_{mech}$ stays constant").scale(1.15).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l0 = Tex("Ball dropped from 10 m, no air resistance").scale(1.0).shift(band_shift(1) + UP * 1.2)
        self.play(Write(b1_l0))
        self.wait(2)
        b1_l1 = MathTex(r"mgh = \tfrac{1}{2} m v^2").scale(1.1).shift(band_shift(1) + UP * 0.3)
        b1_l2 = Tex("The mass cancels — every mass falls alike").scale(1.0).shift(band_shift(1) + DOWN * 0.6)
        b1_l3 = MathTex(r"v^2 = 2 \times 9{,}8 \times 10 = 196").scale(1.05).shift(band_shift(1) + DOWN * 1.5)
        b1_l4 = MathTex(r"v = 14\ \text{m·s}^{-1}").scale(1.1).shift(band_shift(1) + DOWN * 2.5)
        self.play(Write(b1_l1))
        self.wait(2.5)
        self.play(Write(b1_l2))
        self.wait(2)
        self.play(Write(b1_l3))
        self.wait(2)
        self.play(Write(b1_l4))
        self.play(Create(SurroundingRectangle(b1_l4, color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): the bookkeeping identity ---
        self.next_band(2)
        b2_title = Tex("When friction joins the party").scale(1.2).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(1.5)
        b2_eq = MathTex(r"W_{nc} = \Delta E_k + \Delta E_p").scale(1.25).shift(band_shift(2) + UP * 1.1)
        self.play(Write(b2_eq))
        self.play(Create(SurroundingRectangle(b2_eq, color=GREEN)))
        self.wait(2.5)
        b2_l1 = Tex("1. Reference level: the lowest point").scale(1.0).shift(band_shift(2) + UP * 0.0)
        b2_l2 = Tex("2. Four energies: start and end, $E_k$, $E_p$").scale(1.0).shift(band_shift(2) + DOWN * 0.9)
        b2_l3 = Tex("3. Two changes, each final minus initial").scale(1.0).shift(band_shift(2) + DOWN * 1.8)
        b2_l4 = Tex("4. Sum: negative drained, positive pumped in").scale(1.0).shift(band_shift(2) + DOWN * 2.7)
        self.play(Write(b2_l1))
        self.wait(2)
        self.play(Write(b2_l2))
        self.wait(2)
        self.play(Write(b2_l3))
        self.wait(2)
        self.play(Write(b2_l4))
        self.wait(3)

        # --- Band 3 (subtopic_2): the slide, worked in full ---
        self.next_band(3)
        b3_title = Tex("Child, 30 kg, slide 3 m high, arrives at 6").scale(1.05).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(2)
        b3_l1 = MathTex(r"E_{p,i} = 30 \times 9{,}8 \times 3 = 882\ \text{J}").scale(1.0).shift(band_shift(3) + UP * 1.2)
        b3_l2 = MathTex(r"E_{k,f} = \tfrac{1}{2} \times 30 \times 36 = 540\ \text{J}").scale(1.0).shift(band_shift(3) + UP * 0.3)
        self.play(Write(b3_l1))
        self.wait(2.5)
        self.play(Write(b3_l2))
        self.wait(2.5)
        b3_l3 = MathTex(r"\Delta E_k = +540, \quad \Delta E_p = -882").scale(1.0).shift(band_shift(3) + DOWN * 0.6)
        b3_l4 = MathTex(r"W_{nc} = 540 - 882 = -342\ \text{J}").scale(1.05).shift(band_shift(3) + DOWN * 1.6)
        self.play(Write(b3_l3))
        self.wait(2.5)
        self.play(Write(b3_l4))
        self.play(Create(SurroundingRectangle(b3_l4, color=GREEN)))
        self.wait(2)
        b3_l5 = Tex("Friction drained 342 J as heat —").scale(1.0).shift(band_shift(3) + DOWN * 2.5)
        b3_l6 = Tex("frictionless would have given 7,7, not 6").scale(1.0).shift(band_shift(3) + DOWN * 3.3)
        self.play(Write(b3_l5))
        self.play(Write(b3_l6))
        self.wait(3)

        # --- Band 4 (subtopic_3): ramp solved to the friction force ---
        self.next_band(4)
        b4_title = Tex("Box, 2 kg, ramp 4 m long, top at 2,5 m").scale(1.05).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(2)
        b4_l1 = MathTex(r"E_{p,i} = 2 \times 9{,}8 \times 2{,}5 = 49\ \text{J}").scale(1.0).shift(band_shift(4) + UP * 1.2)
        b4_l2 = MathTex(r"E_{k,f} = \tfrac{1}{2} \times 2 \times 25 = 25\ \text{J}").scale(1.0).shift(band_shift(4) + UP * 0.3)
        b4_l3 = MathTex(r"W_{nc} = 25 - 49 = -24\ \text{J}").scale(1.05).shift(band_shift(4) + DOWN * 0.6)
        self.play(Write(b4_l1))
        self.wait(2.5)
        self.play(Write(b4_l2))
        self.wait(2.5)
        self.play(Write(b4_l3))
        self.wait(2.5)
        b4_l4 = MathTex(r"-24 = -f \times 4 \;\Rightarrow\; f = 6\ \text{N}").scale(1.05).shift(band_shift(4) + DOWN * 1.6)
        self.play(Write(b4_l4))
        self.play(Create(SurroundingRectangle(b4_l4, color=GREEN)))
        self.wait(2)
        b4_rule = Tex("Friction: the 4 m PATH. Gravity: the height.").scale(1.0).shift(band_shift(4) + DOWN * 2.6)
        self.play(Write(b4_rule))
        self.wait(3)

        # --- Band 5 (subtopic_3): uphill motor + air resistance twist ---
        self.next_band(5)
        b5_title = Tex("Uphill, and the airborne twist").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(1.5)
        b5_l1 = Tex("Motor drags box up at constant speed:").scale(1.0).shift(band_shift(5) + UP * 1.2)
        b5_l2 = MathTex(r"\Delta E_k = 0, \;\; \Delta E_p = +49\ \text{J}").scale(1.0).shift(band_shift(5) + UP * 0.3)
        b5_l3 = MathTex(r"W_{motor} = 49 + 24 = 73\ \text{J}").scale(1.05).shift(band_shift(5) + DOWN * 0.7)
        self.play(Write(b5_l1))
        self.wait(2)
        self.play(Write(b5_l2))
        self.wait(2.5)
        self.play(Write(b5_l3))
        self.play(Create(SurroundingRectangle(b5_l3, color=GREEN)))
        self.wait(2.5)
        b5_l4 = Tex("Ball returns slower than it left:").scale(1.0).shift(band_shift(5) + DOWN * 1.7)
        b5_l5 = Tex("air resistance charged BOTH halves").scale(1.0).shift(band_shift(5) + DOWN * 2.6)
        self.play(Write(b5_l4))
        self.play(Write(b5_l5))
        self.wait(3)

        # --- Band 6 (subtopic_4): power — stairs and borehole ---
        self.next_band(6)
        b6_title = MathTex(r"P = \frac{W}{\Delta t} \;\; [\text{W} = \text{J·s}^{-1}]").scale(1.15).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(2)
        b6_l1 = Tex("Learner, 60 kg, stairs 3 m, in 5 s:").scale(1.0).shift(band_shift(6) + UP * 1.1)
        b6_l2 = MathTex(r"W = 60 \times 9{,}8 \times 3 = 1\,764\ \text{J}").scale(1.0).shift(band_shift(6) + UP * 0.2)
        b6_l3 = MathTex(r"P = \frac{1\,764}{5} = 352{,}8\ \text{W}").scale(1.05).shift(band_shift(6) + DOWN * 0.9)
        self.play(Write(b6_l1))
        self.wait(2)
        self.play(Write(b6_l2))
        self.wait(2.5)
        self.play(Write(b6_l3))
        self.play(Create(SurroundingRectangle(b6_l3, color=GREEN)))
        self.wait(2.5)
        b6_l4 = Tex("Borehole: 120 kg per minute from 30 m").scale(0.95).shift(band_shift(6) + DOWN * 1.9)
        b6_l5 = MathTex(r"P_{min} = \frac{35\,280}{60} = 588\ \text{W}").scale(1.0).shift(band_shift(6) + DOWN * 2.9)
        self.play(Write(b6_l4))
        self.wait(2)
        self.play(Write(b6_l5))
        self.play(Create(SurroundingRectangle(b6_l5, color=GREEN)))
        self.wait(3)

        # --- Band 7 (subtopic_4): P = Fv at constant speed ---
        self.next_band(7)
        b7_title = Tex("Cruising at constant speed").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(1.5)
        b7_eq = MathTex(r"P = F v").scale(1.25).shift(band_shift(7) + UP * 1.1)
        self.play(Write(b7_eq))
        self.wait(2)
        b7_l1 = Tex(r"Truck at 25 m$\cdot$s$^{-1}$ against 1 800 N:").scale(1.0).shift(band_shift(7) + UP * 0.1)
        b7_l2 = MathTex(r"P = 1\,800 \times 25 = 45\,000\ \text{W}").scale(1.05).shift(band_shift(7) + DOWN * 0.9)
        self.play(Write(b7_l1))
        self.wait(2.5)
        self.play(Write(b7_l2))
        self.play(Create(SurroundingRectangle(b7_l2, color=GREEN)))
        self.wait(2)
        b7_l3 = Tex("45 kW just to stand still against the air").scale(1.0).shift(band_shift(7) + DOWN * 1.9)
        self.play(Write(b7_l3))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): the energy toll road ---
        self.next_band(8)
        b8_title = Tex("The energy toll road").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = Tex("Height-money trades with speed-money").scale(1.05).shift(band_shift(8) + UP * 1.1)
        b8_l2 = Tex("Perfect pool: same total, forever").scale(1.05).shift(band_shift(8) + UP * 0.2)
        self.play(Write(b8_l1))
        self.wait(2.5)
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = Tex("Gravity: honest banker, repays in full").scale(1.0).shift(band_shift(8) + DOWN * 0.7)
        b8_l4 = Tex("Friction: toll collector, burns the money").scale(1.0).shift(band_shift(8) + DOWN * 1.6)
        self.play(Write(b8_l3))
        self.wait(2.5)
        self.play(Write(b8_l4))
        self.wait(2)
        b8_l5 = Tex("Ask of every force: banker or toll collector?").scale(1.0).shift(band_shift(8) + DOWN * 2.6)
        self.play(Write(b8_l5))
        self.play(Create(SurroundingRectangle(b8_l5, color=GREEN)))
        self.wait(3)

        # --- Band 9 (subtopic_6): friction's receipt ---
        self.next_band(9)
        b9_title = Tex("Friction's receipt").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex("Wallet in: 882 J. Wallet out: 540 J.").scale(1.05).shift(band_shift(9) + UP * 1.1)
        b9_l2 = Tex("Receipt: $-342$ J — the toll, now warmth").scale(1.05).shift(band_shift(9) + UP * 0.2)
        self.play(Write(b9_l1))
        self.wait(2.5)
        self.play(Write(b9_l2))
        self.play(Create(SurroundingRectangle(b9_l2, color=GREEN)))
        self.wait(2.5)
        b9_l3 = Tex("Negative: money left. Positive: paid in.").scale(1.0).shift(band_shift(9) + DOWN * 0.8)
        self.play(Write(b9_l3))
        self.wait(2.5)
        b9_l4 = Tex("Friction charges the PATH;").scale(1.0).shift(band_shift(9) + DOWN * 1.7)
        b9_l5 = Tex("gravity charges only the HEIGHT").scale(1.0).shift(band_shift(9) + DOWN * 2.5)
        self.play(Write(b9_l4))
        self.play(Write(b9_l5))
        self.wait(3)

        # --- Band 10 (subtopic_7): rich against fast ---
        self.next_band(10)
        b10_title = Tex("Power: rich against fast").scale(1.2).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_title))
        self.wait(2)
        b10_l1 = Tex("Same stairs, same work — Thabo in 3 s,").scale(1.0).shift(band_shift(10) + UP * 1.1)
        b10_l2 = Tex("Sipho in 30 s: ten times the power").scale(1.0).shift(band_shift(10) + UP * 0.2)
        self.play(Write(b10_l1))
        self.play(Write(b10_l2))
        self.wait(2.5)
        b10_l3 = Tex("Work: the size of the bill.").scale(1.05).shift(band_shift(10) + DOWN * 0.7)
        b10_l4 = Tex("Power: how quickly you pay it.").scale(1.05).shift(band_shift(10) + DOWN * 1.6)
        self.play(Write(b10_l3))
        self.wait(2)
        self.play(Write(b10_l4))
        self.play(Create(SurroundingRectangle(b10_l4, color=GREEN)))
        self.wait(2)
        b10_l5 = Tex("Watts are just joules in a hurry").scale(1.05).shift(band_shift(10) + DOWN * 2.6)
        self.play(Write(b10_l5))
        self.wait(4)
