from manim import *

# Band-layout whiteboard scene for the CAPS grade 12 accounting session duo
# "Corporate Governance and Ethics". One band per teaching beat; the camera
# moves down to fresh space and earlier work stays on the canvas. Only
# exporter-safe mobjects (Tex/MathTex/Line/Arrow/Dot/Circle/Rectangle/
# SurroundingRectangle/VGroup) and write-only reveals — no Transform, no
# FadeOut, no sub-part indexing on MathTex.
#
# Subtopic time shares (subtopics.json, total 1500 s):
# 230/235/235/225 expert, 190/195/190 simplifier.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class CorporateGovernanceAndEthicsSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): owners vs runners ---
        title = Tex("Corporate Governance and Ethics").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_head = Tex("Vusani Limited: who owns, who runs?").scale(1.1).shift(UP * 1.4)
        self.play(Write(b0_head))
        self.wait(2)
        mid0 = Line(UP * 0.9, DOWN * 2.6, stroke_width=3)
        self.play(Create(mid0))
        b0_sh = Tex("SHAREHOLDERS own").scale(1.0).shift(UP * 0.5 + LEFT * 3.2)
        b0_dh = Tex("DIRECTORS run").scale(1.0).shift(UP * 0.5 + RIGHT * 3.2)
        self.play(Write(b0_sh), Write(b0_dh))
        self.wait(2)
        b0_s1 = Tex("Vote at the AGM").scale(0.9).shift(DOWN * 0.3 + LEFT * 3.2)
        b0_d1 = Tex("Fiduciary duty: good faith").scale(0.9).shift(DOWN * 0.3 + RIGHT * 3.2)
        self.play(Write(b0_s1), Write(b0_d1))
        self.wait(2)
        b0_s2 = Tex("Elect directors, appoint auditor").scale(0.85).shift(DOWN * 1.1 + LEFT * 3.2)
        b0_d2 = Tex("Safeguard assets, fair statements").scale(0.85).shift(DOWN * 1.1 + RIGHT * 3.2)
        self.play(Write(b0_s2), Write(b0_d2))
        self.wait(2)
        b0_s3 = Tex("Dividends when declared").scale(0.85).shift(DOWN * 1.9 + LEFT * 3.2)
        b0_d3 = Tex("Declare interests, account to owners").scale(0.85).shift(DOWN * 1.9 + RIGHT * 3.2)
        self.play(Write(b0_s3), Write(b0_d3))
        self.wait(3)

        # --- Band 1 (subtopic_1): the board's structure ---
        self.next_band(1)
        b1_title = Tex("Inside the board").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l1 = Tex("Executive directors — work in the company daily").scale(1.0).shift(band_shift(1) + UP * 1.1)
        b1_l2 = Tex("Non-executive directors — outside oversight").scale(1.0).shift(band_shift(1) + UP * 0.3)
        b1_l3 = Tex("Independent non-executives — no other ties at all").scale(1.0).shift(band_shift(1) + DOWN * 0.5)
        self.play(Write(b1_l1))
        self.wait(2)
        self.play(Write(b1_l2))
        self.wait(2)
        self.play(Write(b1_l3))
        self.play(Create(SurroundingRectangle(b1_l3, color=GREEN)))
        self.wait(2.5)
        b1_bad = Tex("One person as chairperson AND chief executive").scale(0.95).shift(band_shift(1) + DOWN * 1.5)
        self.play(Write(b1_bad))
        self.play(Create(strike(b1_bad)))
        self.wait(2)
        b1_l4 = Tex("Chair runs the BOARD; CEO runs the COMPANY").scale(1.0).shift(band_shift(1) + DOWN * 2.4)
        self.play(Write(b1_l4))
        self.wait(3)

        # --- Band 2 (subtopic_2): the King Code's four demands ---
        self.next_band(2)
        b2_title = Tex("The King Code (King IV): four demands").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(1.5)
        b2_l0 = Tex("Not an Act — the JSE requires: apply and explain").scale(0.95).shift(band_shift(2) + UP * 1.3)
        self.play(Write(b2_l0))
        self.wait(2)
        b2_l1 = Tex("RESPONSIBILITY — take charge of assets and actions").scale(0.95).shift(band_shift(2) + UP * 0.4)
        b2_l2 = Tex("ACCOUNTABILITY — answer for every decision").scale(0.95).shift(band_shift(2) + DOWN * 0.4)
        b2_l3 = Tex("FAIRNESS — weigh ALL stakeholders").scale(0.95).shift(band_shift(2) + DOWN * 1.2)
        b2_l4 = Tex("TRANSPARENCY — report openly, good news and bad").scale(0.95).shift(band_shift(2) + DOWN * 2.0)
        self.play(Write(b2_l1))
        self.wait(2)
        self.play(Write(b2_l2))
        self.wait(2)
        self.play(Write(b2_l3))
        self.wait(2)
        self.play(Write(b2_l4))
        self.play(Create(SurroundingRectangle(VGroup(b2_l1, b2_l2, b2_l3, b2_l4), color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_2): committees turn words into structures ---
        self.next_band(3)
        b3_title = Tex("Words into structures").scale(1.2).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(1.5)
        b3_l1 = Tex("AUDIT COMMITTEE — independent non-executives:").scale(1.0).shift(band_shift(3) + UP * 1.2)
        b3_l2 = Tex("oversees reporting, hears internal audit,").scale(0.95).shift(band_shift(3) + UP * 0.4)
        b3_l3 = Tex("guards the external auditor's independence").scale(0.95).shift(band_shift(3) + DOWN * 0.3)
        self.play(Write(b3_l1))
        self.wait(2)
        self.play(Write(b3_l2))
        self.wait(2)
        self.play(Write(b3_l3))
        self.wait(2.5)
        b3_l4 = Tex("REMUNERATION COMMITTEE — directors do not set").scale(0.95).shift(band_shift(3) + DOWN * 1.2)
        b3_l5 = Tex("their own pay; pay disclosed in the annual report").scale(0.95).shift(band_shift(3) + DOWN * 2.0)
        self.play(Write(b3_l4))
        self.wait(2)
        self.play(Write(b3_l5))
        self.play(Create(SurroundingRectangle(b3_l5, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): the five ethics principles ---
        self.next_band(4)
        b4_title = Tex("The professional code of conduct").scale(1.2).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(1.5)
        b4_l1 = Tex("Integrity — straightforward and honest").scale(0.95).shift(band_shift(4) + UP * 1.2)
        b4_l2 = Tex("Objectivity — no bias, no conflict of interest").scale(0.95).shift(band_shift(4) + UP * 0.4)
        b4_l3 = Tex("Competence and due care — do the work properly").scale(0.95).shift(band_shift(4) + DOWN * 0.4)
        b4_l4 = Tex("Confidentiality — never shields illegality").scale(0.95).shift(band_shift(4) + DOWN * 1.2)
        b4_l5 = Tex("Professional behaviour — obey the law").scale(0.95).shift(band_shift(4) + DOWN * 2.0)
        self.play(Write(b4_l1))
        self.wait(2)
        self.play(Write(b4_l2))
        self.wait(2)
        self.play(Write(b4_l3))
        self.wait(2)
        self.play(Write(b4_l4))
        self.wait(2)
        self.play(Write(b4_l5))
        self.wait(3)

        # --- Band 5 (subtopic_3): conflicts and share dealing ---
        self.next_band(5)
        b5_title = Tex("Conflicts, and the two share crimes").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(1.5)
        b5_bad = Tex("Steer the contract to the spouse, say nothing").scale(0.95).shift(band_shift(5) + UP * 1.2)
        self.play(Write(b5_bad))
        self.play(Create(strike(b5_bad)))
        self.wait(2)
        b5_l1 = Tex("Declare the interest, withdraw from the decision").scale(0.95).shift(band_shift(5) + UP * 0.4)
        self.play(Write(b5_l1))
        self.play(Create(SurroundingRectangle(b5_l1, color=GREEN)))
        self.wait(2.5)
        b5_l2 = Tex("INSIDER TRADING — trade on information").scale(0.95).shift(band_shift(5) + DOWN * 0.5)
        b5_l3 = Tex("the market lacks — illegal").scale(0.95).shift(band_shift(5) + DOWN * 1.2)
        self.play(Write(b5_l2))
        self.play(Write(b5_l3))
        self.wait(2.5)
        b5_l4 = Tex("MANIPULATION — false information or staged trades").scale(0.9).shift(band_shift(5) + DOWN * 2.0)
        b5_l5 = Tex("to move the price artificially — illegal").scale(0.9).shift(band_shift(5) + DOWN * 2.7)
        self.play(Write(b5_l4))
        self.play(Write(b5_l5))
        self.wait(3)

        # --- Band 6 (subtopic_4): three layers of checking ---
        self.next_band(6)
        b6_title = Tex("Three layers of checking").scale(1.2).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(1.5)
        b6_l1 = Tex("1. Internal CONTROL — daily, by management:").scale(0.95).shift(band_shift(6) + UP * 1.2)
        b6_l2 = Tex("divided duties, authorisation, documents, safeguards").scale(0.9).shift(band_shift(6) + UP * 0.5)
        self.play(Write(b6_l1))
        self.wait(2)
        self.play(Write(b6_l2))
        self.wait(2)
        b6_l3 = Tex("2. Internal AUDIT — all year, reports to the").scale(0.95).shift(band_shift(6) + DOWN * 0.3)
        b6_l4 = Tex("audit committee, so findings cannot be buried").scale(0.9).shift(band_shift(6) + DOWN * 1.0)
        self.play(Write(b6_l3))
        self.play(Write(b6_l4))
        self.wait(2.5)
        b6_l5 = Tex("3. INDEPENDENT audit — appointed by shareholders,").scale(0.9).shift(band_shift(6) + DOWN * 1.8)
        b6_l6 = Tex("opinion on fair presentation, value = independence").scale(0.9).shift(band_shift(6) + DOWN * 2.5)
        self.play(Write(b6_l5))
        self.play(Write(b6_l6))
        self.play(Create(SurroundingRectangle(b6_l6, color=GREEN)))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 7 (subtopic_5): the club and its committee ---
        self.next_band(7)
        b7_title = Tex("Phambili United: the club and its committee").scale(1.1).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(2)
        b7_l1 = Tex("200 members OWN the club (shareholders)").scale(1.0).shift(band_shift(7) + UP * 1.1)
        b7_l2 = Tex("5 elected committee members RUN it (directors)").scale(1.0).shift(band_shift(7) + UP * 0.3)
        self.play(Write(b7_l1))
        self.wait(2)
        self.play(Write(b7_l2))
        self.wait(2)
        b7_l3 = Tex("Members keep: votes, yearly report-back,").scale(0.95).shift(band_shift(7) + DOWN * 0.6)
        b7_l4 = Tex("hard questions, choosing the outside checker").scale(0.95).shift(band_shift(7) + DOWN * 1.3)
        self.play(Write(b7_l3))
        self.play(Write(b7_l4))
        self.wait(2.5)
        b7_l5 = Tex("The treasurer's rand is not the treasurer's").scale(1.0).shift(band_shift(7) + DOWN * 2.2)
        self.play(Write(b7_l5))
        self.play(Create(SurroundingRectangle(b7_l5, color=GREEN)))
        self.wait(3)

        # --- Band 8 (subtopic_6): house rules and the kit contract ---
        self.next_band(8)
        b8_title = Tex("House rules, and the kit contract").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = Tex("Responsibility: bank the gate money, fix the roof").scale(0.9).shift(band_shift(8) + UP * 1.2)
        b8_l2 = Tex("Accountability: nobody spends and answers to nobody").scale(0.9).shift(band_shift(8) + UP * 0.5)
        b8_l3 = Tex("Fairness: all 200 members count").scale(0.9).shift(band_shift(8) + DOWN * 0.2)
        b8_l4 = Tex("Transparency: bad months reported too").scale(0.9).shift(band_shift(8) + DOWN * 0.9)
        self.play(Write(b8_l1))
        self.wait(2)
        self.play(Write(b8_l2))
        self.wait(2)
        self.play(Write(b8_l3))
        self.wait(2)
        self.play(Write(b8_l4))
        self.wait(2)
        b8_bad = Tex("Kit from the brother's shop, no quotes").scale(0.95).shift(band_shift(8) + DOWN * 1.7)
        self.play(Write(b8_bad))
        self.play(Create(strike(b8_bad)))
        self.wait(2)
        b8_fix = Tex("Declare, step out, three quotes, minute it").scale(0.95).shift(band_shift(8) + DOWN * 2.5)
        self.play(Write(b8_fix))
        self.play(Create(SurroundingRectangle(b8_fix, color=GREEN)))
        self.wait(3)

        # --- Band 9 (subtopic_7): who checks the checkers ---
        self.next_band(9)
        b9_title = Tex("Who checks the checkers?").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex("Habits: two signatures; counter, recorder,").scale(0.95).shift(band_shift(9) + UP * 1.2)
        b9_l2 = Tex("banker are different people; receipts for everything").scale(0.9).shift(band_shift(9) + UP * 0.5)
        self.play(Write(b9_l1))
        self.play(Write(b9_l2))
        self.wait(2.5)
        b9_l3 = Tex("Naledi: inside, all year, reports past the treasurer").scale(0.95).shift(band_shift(9) + DOWN * 0.4)
        self.play(Write(b9_l3))
        self.wait(2.5)
        b9_l4 = Tex("Outside accountant: chosen by members, no ties,").scale(0.95).shift(band_shift(9) + DOWN * 1.2)
        b9_l5 = Tex("tells the MEMBERS whether the report shows the truth").scale(0.9).shift(band_shift(9) + DOWN * 1.9)
        self.play(Write(b9_l4))
        self.play(Write(b9_l5))
        self.wait(2.5)
        b9_l6 = Tex("Every scenario: problem, principle, remedy").scale(1.0).shift(band_shift(9) + DOWN * 2.7)
        self.play(Write(b9_l6))
        self.play(Create(SurroundingRectangle(b9_l6, color=GREEN)))
        self.wait(4)
