from manim import *

# Band-layout whiteboard scene for "Partnerships and Statements Essentials"
# (grade 11, term 4, revision). One band per teaching beat; the camera moves
# down and nothing is removed. Part 1 (Expert) = subtopics 1-4, Part 2
# (Simplifier) = subtopics 5-7 in fresh bands. Exporter-safe primitives only;
# write-only reveals. Subtopic durations 220/220/230/230/190/200/200 of
# 1490 s guide the apportioning.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class PartnershipsRevisionSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md plays.
        self.wait(14)

        # ===== Part 1 — Expert =====
        # --- Band 0 (subtopic_1): two accounts per partner ---
        title = Tex("Partnerships and Statements Essentials").scale(1.2).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex("Two accounts PER partner:").scale(1.1).shift(UP * 1.3)
        self.play(Write(b0_l1))
        self.wait(2)
        b0_l2 = Tex("CAPITAL: the long-term investment —").scale(1.05).shift(UP * 0.5)
        b0_l3 = Tex("Zola R200 000, Sipho R100 000; barely moves").scale(1.0).shift(DOWN * 0.3)
        self.play(Write(b0_l2))
        self.play(Write(b0_l3))
        self.wait(2.5)
        b0_l4 = Tex("CURRENT: the living account — profit share").scale(1.0).shift(DOWN * 1.2)
        b0_l5 = Tex("in, drawings out; credit $=$ business owes").scale(1.0).shift(DOWN * 2.0)
        self.play(Write(b0_l4))
        self.play(Write(b0_l5))
        self.wait(2.5)
        b0_l6 = Tex("The agreement is the constitution").scale(1.05).shift(DOWN * 2.9)
        self.play(Write(b0_l6))
        self.wait(3)

        # --- Band 1 (subtopic_1): appropriations are not expenses ---
        self.next_band(1)
        b1_t = Tex("The sharpest distinction in the topic").scale(1.1).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_t))
        self.wait(2)
        b1_trap = Tex("Partners' salaries $=$ business expenses?").scale(1.05).shift(band_shift(1) + UP * 1.2)
        self.play(Write(b1_trap))
        self.play(Create(strike(b1_trap)))
        self.wait(2)
        b1_l1 = Tex("They are APPROPRIATIONS —").scale(1.05).shift(band_shift(1) + UP * 0.2)
        b1_l2 = Tex("divisions of a profit already made").scale(1.05).shift(band_shift(1) + DOWN * 0.6)
        self.play(Write(b1_l1))
        self.play(Write(b1_l2))
        self.wait(2.5)
        b1_l3 = Tex("Income statement ends at net profit;").scale(1.05).shift(band_shift(1) + DOWN * 1.5)
        b1_l4 = Tex("only after that line does dividing begin").scale(1.05).shift(band_shift(1) + DOWN * 2.3)
        self.play(Write(b1_l3))
        self.play(Write(b1_l4))
        self.play(Create(SurroundingRectangle(b1_l4, color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): the appropriation account ---
        self.next_band(2)
        b2_t = Tex("Appropriation: empty R240 000 exactly").scale(1.1).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(2)
        b2_l1 = Tex("Salaries: Zola R96 000, Sipho R72 000").scale(1.0).shift(band_shift(2) + UP * 1.3)
        b2_l2 = Tex("Interest 10\\%: R20 000 and R10 000").scale(1.0).shift(band_shift(2) + UP * 0.6)
        b2_l3 = Tex("Bonus to Sipho: R12 000").scale(1.0).shift(band_shift(2) + DOWN * 0.1)
        self.play(Write(b2_l1))
        self.wait(2)
        self.play(Write(b2_l2))
        self.wait(2)
        self.play(Write(b2_l3))
        self.wait(2)
        b2_l4 = Tex("Remainder: 240 $-$ 168 $-$ 30 $-$ 12").scale(1.0).shift(band_shift(2) + DOWN * 0.9)
        b2_l5 = Tex("(thousands) $=$ R30 000: R15 000 each").scale(1.0).shift(band_shift(2) + DOWN * 1.7)
        self.play(Write(b2_l4))
        self.wait(2)
        self.play(Write(b2_l5))
        self.wait(2)
        b2_l6 = Tex("Zola R131 000 $+$ Sipho R109 000").scale(1.0).shift(band_shift(2) + DOWN * 2.5)
        b2_l7 = Tex("$=$ R240 000 — the account empties").scale(1.05).shift(band_shift(2) + DOWN * 3.3)
        self.play(Write(b2_l6))
        self.wait(2)
        self.play(Write(b2_l7))
        self.play(Create(SurroundingRectangle(b2_l7, color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_2): the current accounts close ---
        self.next_band(3)
        b3_t = Tex("The year completes in the current accounts").scale(1.05).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t))
        self.wait(2)
        b3_l1 = Tex("Zola: R4 000 cr $+$ R131 000").scale(1.05).shift(band_shift(3) + UP * 1.2)
        b3_l2 = Tex("$-$ drawings R110 000 $=$ R25 000 credit").scale(1.05).shift(band_shift(3) + UP * 0.4)
        self.play(Write(b3_l1))
        self.wait(2)
        self.play(Write(b3_l2))
        self.play(Create(SurroundingRectangle(b3_l2, color=GREEN)))
        self.wait(2.5)
        b3_l3 = Tex("Sipho: R6 000 DEBIT $+$ R109 000").scale(1.05).shift(band_shift(3) + DOWN * 0.6)
        b3_l4 = Tex("$-$ drawings R95 000 $=$ R8 000 credit").scale(1.05).shift(band_shift(3) + DOWN * 1.4)
        self.play(Write(b3_l3))
        self.wait(2)
        self.play(Write(b3_l4))
        self.play(Create(SurroundingRectangle(b3_l4, color=GREEN)))
        self.wait(2.5)
        b3_l5 = Tex("Read like a bank: the business owes both;").scale(1.0).shift(band_shift(3) + DOWN * 2.3)
        b3_l6 = Tex("nobody lived beyond their earnings").scale(1.0).shift(band_shift(3) + DOWN * 3.0)
        self.play(Write(b3_l5))
        self.play(Write(b3_l6))
        self.wait(3)

        # --- Band 4 (subtopic_3): statement of comprehensive income ---
        self.next_band(4)
        b4_t = Tex("Statement of Comprehensive Income").scale(1.1).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(2)
        b4_l1 = Tex("Sales R900 000 $-$ cost of sales R600 000").scale(1.0).shift(band_shift(4) + UP * 1.2)
        b4_l2 = Tex("$=$ Gross profit R300 000 (50\\% on cost)").scale(1.0).shift(band_shift(4) + UP * 0.4)
        self.play(Write(b4_l1))
        self.wait(2)
        self.play(Write(b4_l2))
        self.wait(2)
        b4_l3 = Tex("$+$ Other income (incl. profit on").scale(1.0).shift(band_shift(4) + DOWN * 0.5)
        b4_l4 = Tex("disposal R5 000); $-$ expenses R65 000").scale(1.0).shift(band_shift(4) + DOWN * 1.3)
        self.play(Write(b4_l3))
        self.play(Write(b4_l4))
        self.wait(2.5)
        b4_l5 = Tex("Net profit R240 000 — flows to").scale(1.05).shift(band_shift(4) + DOWN * 2.2)
        b4_l6 = Tex("appropriation, not to one capital account").scale(1.0).shift(band_shift(4) + DOWN * 3.0)
        self.play(Write(b4_l5))
        self.play(Create(SurroundingRectangle(b4_l5, color=GREEN)))
        self.play(Write(b4_l6))
        self.wait(3)

        # --- Band 5 (subtopic_3): the asset disposal, four steps ---
        self.next_band(5)
        b5_t = Tex("Asset disposal — four steps, always").scale(1.1).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_t))
        self.wait(2)
        b5_l1 = Tex("1. Cost out: Vehicles cr, Disposal dr R80 000").scale(0.95).shift(band_shift(5) + UP * 1.2)
        b5_l2 = Tex("2. Acc. depreciation R50 000 to Disposal").scale(0.95).shift(band_shift(5) + UP * 0.4)
        b5_l3 = Tex("carrying value now R30 000").scale(0.95).shift(band_shift(5) + DOWN * 0.3)
        self.play(Write(b5_l1))
        self.wait(2)
        self.play(Write(b5_l2))
        self.wait(2)
        self.play(Write(b5_l3))
        self.wait(2)
        b5_l4 = Tex("3. Proceeds R35 000 against Disposal").scale(0.95).shift(band_shift(5) + DOWN * 1.1)
        b5_l5 = Tex("4. Difference $=$ profit R5 000, income").scale(1.0).shift(band_shift(5) + DOWN * 2.0)
        self.play(Write(b5_l4))
        self.wait(2)
        self.play(Write(b5_l5))
        self.play(Create(SurroundingRectangle(b5_l5, color=GREEN)))
        self.wait(3)

        # --- Band 6 (subtopic_3): statement of financial position ---
        self.next_band(6)
        b6_t = Tex("Statement of Financial Position").scale(1.1).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_t))
        self.wait(2)
        b6_l1 = Tex("Non-current assets \\quad R335 000").scale(1.0).shift(band_shift(6) + UP * 1.2)
        b6_l2 = Tex("Current assets R168 000: stock 98,").scale(1.0).shift(band_shift(6) + UP * 0.4)
        b6_l3 = Tex("debtors 60, bank 10 (thousands)").scale(1.0).shift(band_shift(6) + DOWN * 0.3)
        b6_l4 = Tex("Total assets \\quad R503 000").scale(1.05).shift(band_shift(6) + DOWN * 1.1)
        self.play(Write(b6_l1))
        self.wait(2)
        self.play(Write(b6_l2))
        self.play(Write(b6_l3))
        self.wait(2)
        self.play(Write(b6_l4))
        self.wait(2)
        b6_l5 = Tex("Equity R333 000 $+$ loan R100 000").scale(1.0).shift(band_shift(6) + DOWN * 1.9)
        b6_l6 = Tex("$+$ current liabilities R70 000 $=$ R503 000").scale(1.0).shift(band_shift(6) + DOWN * 2.7)
        self.play(Write(b6_l5))
        self.wait(2)
        self.play(Write(b6_l6))
        self.play(Create(SurroundingRectangle(b6_l6, color=GREEN)))
        self.wait(3)

        # --- Band 7 (subtopic_4): profitability and the operating rhythm ---
        self.next_band(7)
        b7_t = Tex("Indicators: profitability and rhythm").scale(1.1).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(2)
        b7_l1 = Tex("Gross profit on sales: 300/900 $=$ 33,3\\%").scale(1.0).shift(band_shift(7) + UP * 1.2)
        b7_l2 = Tex("Net profit on sales: 240/900 $=$ 26,7\\%").scale(1.0).shift(band_shift(7) + UP * 0.4)
        self.play(Write(b7_l1))
        self.wait(2)
        self.play(Write(b7_l2))
        self.wait(2)
        b7_l3 = Tex("Stock turnover: 600 000 $\\div$ 100 000").scale(1.0).shift(band_shift(7) + DOWN * 0.5)
        b7_l4 = Tex("$=$ 6 times a year").scale(1.05).shift(band_shift(7) + DOWN * 1.3)
        self.play(Write(b7_l3))
        self.play(Write(b7_l4))
        self.wait(2.5)
        b7_l5 = Tex("Debtors: 60/360 $\\times$ 12 $=$ 2 months —").scale(1.0).shift(band_shift(7) + DOWN * 2.2)
        b7_l6 = Tex("slow against 30-day terms").scale(1.0).shift(band_shift(7) + DOWN * 3.0)
        self.play(Write(b7_l5))
        self.play(Write(b7_l6))
        self.wait(3)

        # --- Band 8 (subtopic_4): liquidity, gearing, return ---
        self.next_band(8)
        b8_t = Tex("Liquidity, gearing, return").scale(1.1).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_t))
        self.wait(2)
        b8_l1 = Tex("Current ratio 168:70 $=$ 2,4:1").scale(1.0).shift(band_shift(8) + UP * 1.2)
        b8_l2 = Tex("Acid test 70:70 $=$ 1:1 — sound").scale(1.0).shift(band_shift(8) + UP * 0.4)
        self.play(Write(b8_l1))
        self.wait(2)
        self.play(Write(b8_l2))
        self.wait(2)
        b8_l3 = Tex("Debt-equity 100:333 $=$ 0,3:1 —").scale(1.0).shift(band_shift(8) + DOWN * 0.5)
        b8_l4 = Tex("lightly geared, room to borrow").scale(1.0).shift(band_shift(8) + DOWN * 1.3)
        self.play(Write(b8_l3))
        self.play(Write(b8_l4))
        self.wait(2.5)
        b8_l5 = Tex("Return on avg equity: 240/320 $=$ 75\\%").scale(1.0).shift(band_shift(8) + DOWN * 2.2)
        b8_l6 = Tex("(partners' salaries sit inside that return)").scale(0.95).shift(band_shift(8) + DOWN * 3.0)
        self.play(Write(b8_l5))
        self.play(Create(SurroundingRectangle(b8_l5, color=GREEN)))
        self.play(Write(b8_l6))
        self.wait(3)

        # ===== Part 2 — Simplifier =====
        # --- Band 9 (subtopic_5): two friends, one till ---
        self.next_band(9)
        b9_t = Tex("Two friends, one till").scale(1.15).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(2)
        b9_l1 = Tex("``I put in more'' — ``I work harder''").scale(1.05).shift(band_shift(9) + UP * 1.2)
        b9_l2 = Tex("The agreement answers both BEFORE").scale(1.05).shift(band_shift(9) + UP * 0.4)
        b9_l3 = Tex("the shouting: salary, interest, ratio").scale(1.05).shift(band_shift(9) + DOWN * 0.4)
        self.play(Write(b9_l1))
        self.wait(2.5)
        self.play(Write(b9_l2))
        self.play(Write(b9_l3))
        self.wait(2.5)
        b9_l4 = Tex("Big pile (capital): stays planted").scale(1.0).shift(band_shift(9) + DOWN * 1.3)
        b9_l5 = Tex("Living pile (current): profit in, drawings out").scale(0.95).shift(band_shift(9) + DOWN * 2.1)
        self.play(Write(b9_l4))
        self.wait(2)
        self.play(Write(b9_l5))
        self.wait(2)
        b9_l6 = Tex("The paper remembers — nobody argues").scale(1.0).shift(band_shift(9) + DOWN * 2.9)
        self.play(Write(b9_l6))
        self.wait(3)

        # --- Band 10 (subtopic_6): slicing the profit pot ---
        self.next_band(10)
        b10_t = Tex("The pot holds R240 000").scale(1.15).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_t))
        self.wait(2)
        b10_l1 = Tex("Ladle 1 — wages for work: R96 000, R72 000").scale(0.95).shift(band_shift(10) + UP * 1.2)
        b10_l2 = Tex("Ladle 2 — thanks to money: R20 000, R10 000").scale(0.95).shift(band_shift(10) + UP * 0.4)
        b10_l3 = Tex("Ladle 3 — the promised bonus: R12 000").scale(0.95).shift(band_shift(10) + DOWN * 0.4)
        b10_l4 = Tex("Last ladle — R30 000 left: R15 000 each").scale(0.95).shift(band_shift(10) + DOWN * 1.2)
        self.play(Write(b10_l1))
        self.wait(2)
        self.play(Write(b10_l2))
        self.wait(2)
        self.play(Write(b10_l3))
        self.wait(2)
        self.play(Write(b10_l4))
        self.wait(2)
        b10_l5 = Tex("Plates: R131 000 $+$ R109 000 $=$ R240 000").scale(1.0).shift(band_shift(10) + DOWN * 2.0)
        self.play(Write(b10_l5))
        self.play(Create(SurroundingRectangle(b10_l5, color=GREEN)))
        self.wait(2)
        b10_trap = Tex("Partner salary $=$ staff wages?").scale(1.0).shift(band_shift(10) + DOWN * 2.8)
        self.play(Write(b10_trap))
        self.play(Create(strike(b10_trap)))
        b10_fix = Tex("Slices of profit — sharing comes AFTER").scale(0.95).shift(band_shift(10) + DOWN * 3.5)
        self.play(Write(b10_fix))
        self.wait(3)

        # --- Band 11 (subtopic_7): reading the scoreboard ---
        self.next_band(11)
        b11_t = Tex("Reading the scoreboard").scale(1.15).shift(band_shift(11) + UP * 2.2)
        self.play(Write(b11_t))
        self.wait(2)
        b11_l1 = Tex("Trading: a third of every sale is").scale(1.0).shift(band_shift(11) + UP * 1.2)
        b11_l2 = Tex("gross profit; shelves turn 6 times").scale(1.0).shift(band_shift(11) + UP * 0.5)
        self.play(Write(b11_l1))
        self.play(Write(b11_l2))
        self.wait(2.5)
        b11_l3 = Tex("But customers pay in 2 months —").scale(1.0).shift(band_shift(11) + DOWN * 0.3)
        b11_l4 = Tex("lending customers money for free").scale(1.0).shift(band_shift(11) + DOWN * 1.0)
        self.play(Write(b11_l3))
        self.play(Write(b11_l4))
        self.wait(2.5)
        b11_l5 = Tex("Creditor: R2,40 near money per R1 owed").scale(1.0).shift(band_shift(11) + DOWN * 1.8)
        b11_l6 = Tex("Bank: R1 borrowed per R3 owned").scale(1.0).shift(band_shift(11) + DOWN * 2.6)
        self.play(Write(b11_l5))
        self.wait(2)
        self.play(Write(b11_l6))
        self.wait(2)
        b11_l7 = Tex("Worth it? 75 back per 100 kept in").scale(1.0).shift(band_shift(11) + DOWN * 3.4)
        self.play(Write(b11_l7))
        self.play(Create(SurroundingRectangle(b11_l7, color=GREEN)))
        self.wait(4)
