from manim import *

# Band-layout whiteboard scene for "Map Scale and Distance" (grade 12,
# term 1 mapwork). All seven subtopics: Part 1 Expert (1-4), Part 2
# Simplifier (5-7). Band time apportioned to subtopics.json
# (230/220/210/260/200/180/190 of 1490 s). Exporter-safe primitives only;
# the worked conversion 8,6 cm on 1:50 000 -> 4,3 km is carried line by
# line with green-boxed answers and struck traps, per the script.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class MapScaleDistanceSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic full-screen while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): what 1:50 000 means
        title = Tex("Map Scale and Distance").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex(r"1:50 000 — ONE unit on paper is").scale(1.05).shift(UP * 1.2)
        b0_l2 = Tex(r"FIFTY THOUSAND on the ground").scale(1.05).shift(UP * 0.5)
        self.play(Write(b0_l1))
        self.play(Write(b0_l2))
        self.wait(2.5)
        b0_l3 = MathTex(r"1 \text{ cm} = 50\,000 \text{ cm} = 500 \text{ m} = 0,5 \text{ km}").scale(0.95).shift(DOWN * 0.5)
        self.play(Write(b0_l3))
        self.play(Create(SurroundingRectangle(b0_l3, color=GREEN)))
        self.wait(2.5)
        b0_l4 = Tex(r"Two centimetres: one kilometre —").scale(1.0).shift(DOWN * 1.6)
        b0_l5 = Tex(r"your ruler is measuring the landscape").scale(1.0).shift(DOWN * 2.3)
        self.play(Write(b0_l4))
        self.play(Write(b0_l5))
        self.wait(2.5)
        b0_l6 = Tex(r"The ratio has no units: any unit in,").scale(0.95).shift(DOWN * 3.1)
        b0_l7 = Tex(r"the same unit out").scale(0.95).shift(DOWN * 3.7)
        self.play(Write(b0_l6))
        self.play(Write(b0_l7))
        self.wait(3)

        # --- Band 1 (subtopic_1): three dialects, large vs small scale
        self.next_band(1)
        b1_title = Tex("Three dialects of one scale").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l1 = Tex(r"Words: ``1 cm represents 0,5 km''").scale(1.0).shift(band_shift(1) + UP * 1.2)
        b1_l2 = Tex(r"Ratio: 1:50 000 — the one we calculate with").scale(1.0).shift(band_shift(1) + UP * 0.4)
        self.play(Write(b1_l1))
        self.wait(2)
        self.play(Write(b1_l2))
        self.wait(2)
        # Linear scale bar: a divided bar with km labels.
        bar = Rectangle(width=4.8, height=0.35).shift(band_shift(1) + DOWN * 0.6)
        t1 = Line(band_shift(1) + DOWN * 0.42 + LEFT * 1.2, band_shift(1) + DOWN * 0.78 + LEFT * 1.2)
        t2 = Line(band_shift(1) + DOWN * 0.42 + RIGHT * 1.2, band_shift(1) + DOWN * 0.78 + RIGHT * 1.2)
        z_lab = Tex("0").scale(0.7).shift(band_shift(1) + DOWN * 1.15 + LEFT * 2.4)
        k_lab = Tex("1 km").scale(0.7).shift(band_shift(1) + DOWN * 1.15 + LEFT * 1.2)
        k2_lab = Tex("2 km").scale(0.7).shift(band_shift(1) + DOWN * 1.15 + RIGHT * 1.2)
        bar_lab = Tex("linear scale: step distances off, no sums").scale(0.85).shift(band_shift(1) + DOWN * 1.8)
        self.play(Create(bar), Create(t1), Create(t2))
        self.play(Write(z_lab), Write(k_lab), Write(k2_lab), Write(bar_lab))
        self.wait(2.5)
        b1_l3 = Tex(r"1:10 000 is the LARGER scale ($\tfrac{1}{10\,000} > \tfrac{1}{50\,000}$):").scale(0.86).shift(band_shift(1) + DOWN * 2.7)
        b1_l4 = Tex(r"smaller area, more detail — the orthophoto").scale(0.95).shift(band_shift(1) + DOWN * 3.4)
        self.play(Write(b1_l3))
        self.play(Write(b1_l4))
        self.wait(3)

        # --- Band 2 (subtopic_2): the straight-line calculation, in full
        self.next_band(2)
        b2_title = Tex(r"8,6 cm on 1:50 000 — real distance in km?").scale(1.05).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(2)
        b2_l1 = MathTex(r"\text{real} = \text{map distance} \times 50\,000").scale(1.05).shift(band_shift(2) + UP * 1.2)
        self.play(Write(b2_l1))
        self.wait(2)
        b2_l2 = MathTex(r"8,6 \times 50\,000 = 430\,000 \text{ cm}").scale(1.1).shift(band_shift(2) + UP * 0.3)
        self.play(Write(b2_l2))
        self.wait(2)
        b2_l3 = MathTex(r"430\,000 \div 100 = 4\,300 \text{ m}").scale(1.1).shift(band_shift(2) + DOWN * 0.6)
        self.play(Write(b2_l3))
        self.wait(2)
        b2_l4 = MathTex(r"4\,300 \div 1\,000 = 4,3 \text{ km}").scale(1.1).shift(band_shift(2) + DOWN * 1.5)
        self.play(Write(b2_l4))
        self.play(Create(SurroundingRectangle(b2_l4, color=GREEN)))
        self.wait(2.5)
        b2_l5 = Tex(r"Say the unit — a naked 4,3 forfeits a mark").scale(0.95).shift(band_shift(2) + DOWN * 2.5)
        self.play(Write(b2_l5))
        self.wait(2)
        b2_l6 = Tex(r"Ladder: $\div 100$ to metres, $\div 1\,000$ to km").scale(0.95).shift(band_shift(2) + DOWN * 3.3)
        self.play(Write(b2_l6))
        self.wait(3)

        # --- Band 3 (subtopic_2): the shortcut and measuring care
        self.next_band(3)
        b3_title = Tex("The shortcut, and the millimetre").scale(1.2).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(1.5)
        b3_l1 = Tex(r"On 1:50 000 only: cm $\times$ 0,5 $=$ km").scale(1.0).shift(band_shift(3) + UP * 1.2)
        b3_l2 = MathTex(r"8,6 \times 0,5 = 4,3 \quad \checkmark").scale(1.1).shift(band_shift(3) + UP * 0.3)
        self.play(Write(b3_l1))
        self.play(Write(b3_l2))
        self.wait(2.5)
        b3_l3 = Tex(r"Use it to VERIFY; show the full ladder —").scale(1.0).shift(band_shift(3) + DOWN * 0.6)
        b3_l4 = Tex(r"the memo pays for the steps").scale(1.0).shift(band_shift(3) + DOWN * 1.3)
        self.play(Write(b3_l3))
        self.play(Write(b3_l4))
        self.play(Create(SurroundingRectangle(b3_l4, color=GREEN)))
        self.wait(2.5)
        b3_l5 = Tex(r"Measure point-centre to point-centre,").scale(1.0).shift(band_shift(3) + DOWN * 2.2)
        b3_l6 = Tex(r"to the nearest mm: 1 mm off $=$ 50 m off").scale(1.0).shift(band_shift(3) + DOWN * 2.9)
        self.play(Write(b3_l5))
        self.play(Write(b3_l6))
        self.wait(3)

        # --- Band 4 (subtopic_3): curved routes and other scales
        self.next_band(4)
        b4_title = Tex("Curved routes, other scales, reverse").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(1.5)
        b4_l1 = Tex(r"Winding road: lay string along the bends,").scale(0.95).shift(band_shift(4) + UP * 1.3)
        b4_l2 = Tex(r"straighten it on the ruler — say 12,4 cm").scale(0.95).shift(band_shift(4) + UP * 0.6)
        self.play(Write(b4_l1))
        self.play(Write(b4_l2))
        self.wait(2.5)
        b4_l3 = MathTex(r"12,4 \times 50\,000 = 620\,000 \text{ cm} = 6,2 \text{ km}").scale(1.0).shift(band_shift(4) + DOWN * 0.3)
        self.play(Write(b4_l3))
        self.play(Create(SurroundingRectangle(b4_l3, color=GREEN)))
        self.wait(2.5)
        b4_l4 = Tex(r"Orthophoto 1:10 000:").scale(1.0).shift(band_shift(4) + DOWN * 1.3)
        b4_l5 = MathTex(r"8,6 \times 10\,000 = 86\,000 \text{ cm} = 0,86 \text{ km}").scale(1.0).shift(band_shift(4) + DOWN * 2.1)
        self.play(Write(b4_l4))
        self.play(Write(b4_l5))
        self.wait(2.5)
        b4_l6 = Tex(r"Reverse: $430\,000 \div 50\,000 = 8,6$ cm —").scale(0.95).shift(band_shift(4) + DOWN * 3.0)
        b4_l7 = Tex(r"multiply to ground, divide back to map").scale(0.95).shift(band_shift(4) + DOWN * 3.7)
        self.play(Write(b4_l6))
        self.play(Write(b4_l7))
        self.wait(3)

        # --- Band 5 (subtopic_4): the sense check
        self.next_band(5)
        b5_title = Tex("The hand-span sense check").scale(1.2).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(1.5)
        b5_l1 = Tex(r"A hand-span $\approx$ 10 cm $\approx$ 5 km on 1:50 000").scale(1.0).shift(band_shift(5) + UP * 1.2)
        self.play(Write(b5_l1))
        self.play(Create(SurroundingRectangle(b5_l1, color=GREEN)))
        self.wait(2.5)
        b5_l2 = Tex(r"8,6 cm $\to$ 4,3 km: a bit under a span,").scale(1.0).shift(band_shift(5) + UP * 0.2)
        b5_l3 = Tex(r"a bit under 5 km — it fits").scale(1.0).shift(band_shift(5) + DOWN * 0.5)
        self.play(Write(b5_l2))
        self.play(Write(b5_l3))
        self.wait(2.5)
        b5_l4 = Tex(r"43 km or 0,43 km from the same paper?").scale(1.0).shift(band_shift(5) + DOWN * 1.5)
        self.play(Write(b5_l4))
        self.play(Create(strike(b5_l4)))
        self.wait(2)
        b5_l5 = Tex(r"A slipped decimal — ask: could I walk").scale(1.0).shift(band_shift(5) + DOWN * 2.4)
        b5_l6 = Tex(r"this in an afternoon?").scale(1.0).shift(band_shift(5) + DOWN * 3.1)
        self.play(Write(b5_l5))
        self.play(Write(b5_l6))
        self.wait(3)

        # --- Band 6 (subtopic_4): the traps
        self.next_band(6)
        b6_title = Tex("Four traps, named").scale(1.2).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(1.5)
        b6_t1 = MathTex(r"\div 1\,000 \text{ on the cm} \to \text{m rung}").scale(1.0).shift(band_shift(6) + UP * 1.3)
        self.play(Write(b6_t1))
        self.play(Create(strike(b6_t1)))
        self.wait(2)
        b6_l1 = Tex(r"Recite: $\div 100$ to m, $\div 1\,000$ to km").scale(1.0).shift(band_shift(6) + UP * 0.4)
        self.play(Write(b6_l1))
        self.wait(2)
        b6_t2 = Tex(r"Wrong factor — the sheet quietly changed").scale(0.95).shift(band_shift(6) + DOWN * 0.5)
        self.play(Write(b6_t2))
        self.wait(2)
        b6_t3 = Tex(r"Rounding 8,6 to 9 cm first: 200 m error").scale(0.95).shift(band_shift(6) + DOWN * 1.3)
        self.play(Write(b6_t3))
        self.play(Create(strike(b6_t3)))
        self.wait(2)
        b6_t4 = Tex(r"4 300 ``metres'' when km were demanded").scale(0.95).shift(band_shift(6) + DOWN * 2.2)
        self.play(Write(b6_t4))
        self.wait(2)
        b6_l2 = Tex(r"This distance feeds gradient, cross-sections,").scale(0.9).shift(band_shift(6) + DOWN * 3.1)
        b6_l3 = Tex(r"area — ten of thirty mapwork marks").scale(0.9).shift(band_shift(6) + DOWN * 3.8)
        self.play(Write(b6_l2))
        self.play(Write(b6_l3))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 7 (subtopic_5): the shrunk district
        self.next_band(7)
        b7_title = Tex("The district, shrunk 50 000 times").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(2)
        b7_l1 = Tex(r"A map is the real place, squashed evenly;").scale(0.95).shift(band_shift(7) + UP * 1.3)
        b7_l2 = Tex(r"the printed number is the shrink factor").scale(0.95).shift(band_shift(7) + UP * 0.6)
        self.play(Write(b7_l1))
        self.play(Write(b7_l2))
        self.wait(2.5)
        b7_l3 = Tex(r"Un-shrink: multiply by 50 000").scale(1.05).shift(band_shift(7) + DOWN * 0.3)
        self.play(Write(b7_l3))
        self.play(Create(SurroundingRectangle(b7_l3, color=GREEN)))
        self.wait(2.5)
        b7_l4 = Tex(r"Cordial rule: 1-to-5 works in a cup or a").scale(0.95).shift(band_shift(7) + DOWN * 1.2)
        b7_l5 = Tex(r"bucket — the ratio never argues with your ruler").scale(0.9).shift(band_shift(7) + DOWN * 1.9)
        self.play(Write(b7_l4))
        self.play(Write(b7_l5))
        self.wait(2.5)
        b7_l6 = Tex(r"A 30 cm school ruler spans 15 km of SA").scale(0.95).shift(band_shift(7) + DOWN * 2.8)
        self.play(Write(b7_l6))
        self.wait(2)
        b7_l7 = Tex(r"Zoom: 1:10 000 is zoomed IN — big detail").scale(0.95).shift(band_shift(7) + DOWN * 3.6)
        self.play(Write(b7_l7))
        self.wait(3)

        # --- Band 8 (subtopic_6): multiply once, step down twice
        self.next_band(8)
        b8_title = Tex("Multiply once, then step down twice").scale(1.1).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = MathTex(r"8 \times 50\,000 = 400\,000; \;\; 0,6 \times 50\,000 = 30\,000").scale(0.95).shift(band_shift(8) + UP * 1.2)
        self.play(Write(b8_l1))
        self.wait(2)
        b8_l2 = MathTex(r"8,6 \times 50\,000 = 430\,000 \text{ cm}").scale(1.05).shift(band_shift(8) + UP * 0.3)
        self.play(Write(b8_l2))
        self.wait(2)
        b8_l3 = Tex(r"Cents to rand: $430\,000$ cm $= 4\,300$ m").scale(1.0).shift(band_shift(8) + DOWN * 0.6)
        self.play(Write(b8_l3))
        self.wait(2)
        b8_l4 = Tex(r"Rand to bundles: $4\,300$ m $= 4,3$ km").scale(1.0).shift(band_shift(8) + DOWN * 1.5)
        self.play(Write(b8_l4))
        self.play(Create(SurroundingRectangle(b8_l4, color=GREEN)))
        self.wait(2.5)
        b8_l5 = Tex(r"Write the word ``kilometres'' — the").scale(0.95).shift(band_shift(8) + DOWN * 2.4)
        b8_l6 = Tex(r"cheapest mark in the paper").scale(0.95).shift(band_shift(8) + DOWN * 3.1)
        self.play(Write(b8_l5))
        self.play(Write(b8_l6))
        self.wait(2)
        b8_l7 = Tex(r"Check: halve the cm — 8,6 $\to$ 4,3 $\checkmark$").scale(0.95).shift(band_shift(8) + DOWN * 3.8)
        self.play(Write(b8_l7))
        self.wait(3)

        # --- Band 9 (subtopic_7): shoelaces and zoomed sheets
        self.next_band(9)
        b9_title = Tex("Shoelaces and zoomed-in sheets").scale(1.15).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex(r"Bendy road: shoelace into every curve,").scale(0.95).shift(band_shift(9) + UP * 1.3)
        b9_l2 = Tex(r"pinch, straighten, read — 12,4 cm").scale(0.95).shift(band_shift(9) + UP * 0.6)
        self.play(Write(b9_l1))
        self.play(Write(b9_l2))
        self.wait(2.5)
        b9_l3 = MathTex(r"12,4 \times 50\,000 = 620\,000 \text{ cm} = 6,2 \text{ km}").scale(1.0).shift(band_shift(9) + DOWN * 0.3)
        self.play(Write(b9_l3))
        self.play(Create(SurroundingRectangle(b9_l3, color=GREEN)))
        self.wait(2.5)
        b9_l4 = Tex(r"Orthophoto: same 8,6 cm, only 0,86 km —").scale(0.95).shift(band_shift(9) + DOWN * 1.3)
        b9_l5 = Tex(r"glance at the printed scale first").scale(0.95).shift(band_shift(9) + DOWN * 2.0)
        self.play(Write(b9_l4))
        self.play(Write(b9_l5))
        self.wait(2.5)
        b9_l6 = Tex(r"Backwards: $4,3$ km $= 430\,000$ cm,").scale(0.95).shift(band_shift(9) + DOWN * 2.9)
        b9_l7 = MathTex(r"430\,000 \div 50\,000 = 8,6 \text{ cm}").scale(1.0).shift(band_shift(9) + DOWN * 3.7)
        self.play(Write(b9_l6))
        self.play(Write(b9_l7))
        self.wait(3)

        # --- Band 10 (subtopic_7): the closing checklist
        self.next_band(10)
        b10_title = Tex("The hand-span test, and the habits").scale(1.15).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_title))
        self.wait(2)
        b10_l1 = Tex(r"Hand-span $\approx$ 10 cm $\approx$ 5 km $\approx$ an hour's walk").scale(0.87).shift(band_shift(10) + UP * 1.2)
        self.play(Write(b10_l1))
        self.wait(2)
        b10_l2 = Tex(r"4,3 km: under a span, under an hour — fits;").scale(0.95).shift(band_shift(10) + UP * 0.4)
        b10_l3 = Tex(r"43 km would mean a runaway decimal").scale(0.95).shift(band_shift(10) + DOWN * 0.3)
        self.play(Write(b10_l2))
        self.play(Write(b10_l3))
        self.wait(2.5)
        b10_l4 = Tex(r"Measure to the mm; never round early;").scale(0.95).shift(band_shift(10) + DOWN * 1.2)
        b10_l5 = Tex(r"use the sheet's own scale; finish in the").scale(0.95).shift(band_shift(10) + DOWN * 1.9)
        b10_l6 = Tex(r"asked unit; hand-span every answer").scale(0.95).shift(band_shift(10) + DOWN * 2.6)
        self.play(Write(b10_l4))
        self.play(Write(b10_l5))
        self.play(Write(b10_l6))
        self.wait(2.5)
        b10_l7 = Tex(r"Gradient, cross-section, area all stand here").scale(0.95).shift(band_shift(10) + DOWN * 3.4)
        self.play(Write(b10_l7))
        self.play(Create(SurroundingRectangle(b10_l7, color=GREEN)))
        self.wait(4)
