from manim import *

# Band-layout whiteboard scene for the CAPS grade 12 accounting session duo
# "FIFO and Weighted Average". One band per teaching beat; the camera moves
# down to fresh space and earlier work stays on the canvas. Exporter-safe
# mobjects only; write-only reveals — no Transform/FadeOut/sub-part indexing.
#
# Subtopic time shares (subtopics.json, total 1530 s):
# 230/240/230/230 expert, 190/210/200 simplifier.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class FifoAndWeightedAverageSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): systems and the three methods ---
        title = Tex("FIFO and Weighted Average").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex(r"Perpetual: stock is a running account").scale(1.05).shift(UP * 1.3)
        b0_l2 = Tex(r"Periodic: opening $+$ purchases $-$ closing $=$ COS").scale(1.05).shift(UP * 0.5)
        self.play(Write(b0_l1))
        self.wait(2)
        self.play(Write(b0_l2))
        self.wait(2.5)
        b0_l3 = Tex("1. Specific identification — few, costly, traceable").scale(1.0).shift(DOWN * 0.5)
        b0_l4 = Tex("2. FIFO — oldest sold first, shelf holds newest costs").scale(1.0).shift(DOWN * 1.3)
        b0_l5 = Tex("3. Weighted average — one pooled cost per unit").scale(1.0).shift(DOWN * 2.1)
        self.play(Write(b0_l3))
        self.wait(2)
        self.play(Write(b0_l4))
        self.wait(2)
        self.play(Write(b0_l5))
        self.wait(2)
        b0_l6 = Tex("GAAP: historical cost, prudence, consistency").scale(1.0).shift(DOWN * 2.9)
        self.play(Write(b0_l6))
        self.wait(3)

        # --- Band 1 (subtopic_2): the Dlamini Stores stock story ---
        self.next_band(1)
        b1_title = Tex("Dlamini Stores: the year's stock story").scale(1.15).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l1 = Tex(r"Opening: 200 units @ R50 $=$ R10\,000").scale(1.05).shift(band_shift(1) + UP * 1.2)
        b1_l2 = Tex(r"May: 400 @ R55 $=$ R22\,000").scale(1.05).shift(band_shift(1) + UP * 0.4)
        b1_l3 = Tex(r"Aug: 300 @ R60 $=$ R18\,000").scale(1.05).shift(band_shift(1) + DOWN * 0.4)
        b1_l4 = Tex(r"Dec: 100 @ R62 $=$ R6\,200").scale(1.05).shift(band_shift(1) + DOWN * 1.2)
        self.play(Write(b1_l1))
        self.wait(2)
        self.play(Write(b1_l2))
        self.wait(1.5)
        self.play(Write(b1_l3))
        self.wait(1.5)
        self.play(Write(b1_l4))
        self.wait(2)
        b1_l5 = Tex(r"Available: 1\,000 units costing R56\,200").scale(1.05).shift(band_shift(1) + DOWN * 2.1)
        b1_l6 = Tex(r"Sold 750 @ R90 $=$ R67\,500; 250 remain").scale(1.05).shift(band_shift(1) + DOWN * 2.9)
        self.play(Write(b1_l5))
        self.play(Create(SurroundingRectangle(b1_l5, color=GREEN)))
        self.wait(2)
        self.play(Write(b1_l6))
        self.wait(3)

        # --- Band 2 (subtopic_2): FIFO worked to the rand ---
        self.next_band(2)
        b2_title = Tex("FIFO: value the 250 from the NEWEST back").scale(1.1).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(1.5)
        b2_wrong = Tex("Counting forward from opening stock").scale(1.0).shift(band_shift(2) + UP * 1.2)
        self.play(Write(b2_wrong))
        self.play(Create(strike(b2_wrong)))
        self.wait(2)
        b2_l1 = Tex(r"100 @ R62 (Dec) $=$ R6\,200").scale(1.05).shift(band_shift(2) + UP * 0.3)
        b2_l2 = Tex(r"150 @ R60 (Aug) $=$ R9\,000").scale(1.05).shift(band_shift(2) + DOWN * 0.5)
        b2_l3 = Tex(r"Closing stock $=$ R15\,200").scale(1.1).shift(band_shift(2) + DOWN * 1.3)
        self.play(Write(b2_l1))
        self.wait(2)
        self.play(Write(b2_l2))
        self.wait(2)
        self.play(Write(b2_l3))
        self.play(Create(SurroundingRectangle(b2_l3, color=GREEN)))
        self.wait(2)
        b2_l4 = Tex(r"COS: $56\,200 - 15\,200 = $ R41\,000").scale(1.05).shift(band_shift(2) + DOWN * 2.1)
        b2_l5 = Tex(r"Gross profit: $67\,500 - 41\,000 = $ R26\,500").scale(1.05).shift(band_shift(2) + DOWN * 2.9)
        self.play(Write(b2_l4))
        self.wait(2)
        self.play(Write(b2_l5))
        self.play(Create(SurroundingRectangle(b2_l5, color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_3): weighted average worked to the rand ---
        self.next_band(3)
        b3_title = Tex("Weighted average: pool everything").scale(1.15).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(1.5)
        b3_l1 = MathTex(r"\frac{R56\,200}{1\,000 \text{ units}} = R56{,}20 \text{ per unit}").scale(1.0).shift(band_shift(3) + UP * 1.0)
        self.play(Write(b3_l1))
        self.wait(2.5)
        b3_l2 = Tex(r"Closing stock: 250 @ R56,20 $=$ R14\,050").scale(1.05).shift(band_shift(3) + UP * 0.0)
        b3_l3 = Tex(r"Cost of sales: 750 @ R56,20 $=$ R42\,150").scale(1.05).shift(band_shift(3) + DOWN * 0.8)
        b3_l4 = Tex(r"Check: $14\,050 + 42\,150 = R56\,200$ — the pool").scale(1.0).shift(band_shift(3) + DOWN * 1.6)
        self.play(Write(b3_l2))
        self.wait(2)
        self.play(Write(b3_l3))
        self.wait(2)
        self.play(Write(b3_l4))
        self.wait(2)
        b3_l5 = Tex(r"Gross profit: $67\,500 - 42\,150 = $ R25\,350").scale(1.05).shift(band_shift(3) + DOWN * 2.5)
        self.play(Write(b3_l5))
        self.play(Create(SurroundingRectangle(b3_l5, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): the comparison and the two traps ---
        self.next_band(4)
        b4_title = Tex("Side by side: the R1\\,150 law").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(1.5)
        b4_l1 = Tex(r"Closing stock: R15\,200 vs R14\,050 $=$ R1\,150").scale(1.0).shift(band_shift(4) + UP * 1.1)
        b4_l2 = Tex(r"Gross profit: R26\,500 vs R25\,350 $=$ R1\,150").scale(1.0).shift(band_shift(4) + UP * 0.3)
        b4_l3 = Tex("Rands on the shelf are rands kept out of COS").scale(1.0).shift(band_shift(4) + DOWN * 0.5)
        self.play(Write(b4_l1))
        self.wait(2)
        self.play(Write(b4_l2))
        self.wait(2)
        self.play(Write(b4_l3))
        self.play(Create(SurroundingRectangle(b4_l3, color=GREEN)))
        self.wait(2.5)
        b4_wrong = Tex(r"Simple average of prices: $\frac{50+55+60+62}{4} = R56{,}75$").scale(0.95).shift(band_shift(4) + DOWN * 1.5)
        self.play(Write(b4_wrong))
        self.play(Create(strike(b4_wrong)))
        self.wait(2)
        b4_l4 = Tex("Weight by UNITS; carriage joins the cost pool").scale(1.0).shift(band_shift(4) + DOWN * 2.5)
        self.play(Write(b4_l4))
        self.wait(3)

        # --- Band 5 (subtopic_4): validation, controls, ethics ---
        self.next_band(5)
        b5_title = Tex("Validation, control, ethics").scale(1.2).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(1.5)
        b5_l1 = Tex(r"Books say 250; the count finds 235").scale(1.05).shift(band_shift(5) + UP * 1.2)
        b5_l2 = Tex(r"Deficit: 15 @ R56,20 $=$ R843 written off").scale(1.05).shift(band_shift(5) + UP * 0.4)
        self.play(Write(b5_l1))
        self.wait(2)
        self.play(Write(b5_l2))
        self.play(Create(SurroundingRectangle(b5_l2, color=GREEN)))
        self.wait(2.5)
        b5_l3 = Tex("Controls: divide duties; pre-numbered documents;").scale(0.95).shift(band_shift(5) + DOWN * 0.5)
        b5_l4 = Tex("locked storerooms; independent counts; review").scale(0.95).shift(band_shift(5) + DOWN * 1.2)
        self.play(Write(b5_l3))
        self.play(Write(b5_l4))
        self.wait(2.5)
        b5_l5 = Tex(r"Overstate stock $\rightarrow$ inflate profit; understate $\rightarrow$ cheat SARS").scale(0.9).shift(band_shift(5) + DOWN * 2.1)
        b5_l6 = Tex("Consistency is the GAAP answer to convenient switches").scale(0.9).shift(band_shift(5) + DOWN * 2.9)
        self.play(Write(b5_l5))
        self.wait(2.5)
        self.play(Write(b5_l6))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 6 (subtopic_5): the fridge that ate the profits ---
        self.next_band(6)
        b6_title = Tex("Zanele's fridge: three honest options").scale(1.15).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(2)
        b6_l1 = Tex(r"30 cans: some cost R10, some R12 — no name tags").scale(1.0).shift(band_shift(6) + UP * 1.1)
        self.play(Write(b6_l1))
        self.wait(2.5)
        b6_l2 = Tex("Know each item — works for dated ice cream tubs").scale(1.0).shift(band_shift(6) + UP * 0.2)
        b6_l3 = Tex("Oldest sells first — the fridge holds the newest").scale(1.0).shift(band_shift(6) + DOWN * 0.6)
        b6_l4 = Tex("Or call every can the average of the batch").scale(1.0).shift(band_shift(6) + DOWN * 1.4)
        self.play(Write(b6_l2))
        self.wait(2)
        self.play(Write(b6_l3))
        self.wait(2)
        self.play(Write(b6_l4))
        self.wait(2)
        b6_l5 = Tex("The fridge and the profit share one pot of rands").scale(1.0).shift(band_shift(6) + DOWN * 2.3)
        self.play(Write(b6_l5))
        self.play(Create(SurroundingRectangle(b6_l5, color=GREEN)))
        self.wait(3)

        # --- Band 7 (subtopic_6): two honest answers on 60 cans ---
        self.next_band(7)
        b7_title = Tex("Two honest answers, 60 cans").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(1.5)
        b7_l1 = Tex(r"40 @ R10 $+$ 20 @ R12 $=$ 60 cans, R640; sold 30 @ R15").scale(0.95).shift(band_shift(7) + UP * 1.2)
        self.play(Write(b7_l1))
        self.wait(2.5)
        b7_l2 = Tex(r"FIFO fridge: 20 @ R12 $+$ 10 @ R10 $=$ R340").scale(1.0).shift(band_shift(7) + UP * 0.3)
        b7_l3 = Tex(r"COS R300; profit $450 - 300 = $ R150").scale(1.0).shift(band_shift(7) + DOWN * 0.5)
        self.play(Write(b7_l2))
        self.wait(2)
        self.play(Write(b7_l3))
        self.play(Create(SurroundingRectangle(b7_l3, color=GREEN)))
        self.wait(2.5)
        b7_l4 = Tex(r"Average: $R640 \div 60 = R10{,}67$; fridge R320").scale(1.0).shift(band_shift(7) + DOWN * 1.4)
        b7_l5 = Tex(r"COS R320; profit $450 - 320 = $ R130").scale(1.0).shift(band_shift(7) + DOWN * 2.2)
        self.play(Write(b7_l4))
        self.wait(2)
        self.play(Write(b7_l5))
        self.play(Create(SurroundingRectangle(b7_l5, color=GREEN)))
        self.wait(2)
        b7_l6 = Tex(r"R20 apart — the same R20 sitting in the fridge").scale(1.0).shift(band_shift(7) + DOWN * 3.0)
        self.play(Write(b7_l6))
        self.wait(3)

        # --- Band 8 (subtopic_7): when the count and the book disagree ---
        self.next_band(8)
        b8_title = Tex("When the count and the book disagree").scale(1.15).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = Tex(r"Notebook: 30 cans. Count: 27. Three missing").scale(1.0).shift(band_shift(8) + UP * 1.2)
        b8_l2 = Tex(r"Deficit: 3 @ R10,67 $=$ R32 written off").scale(1.0).shift(band_shift(8) + UP * 0.4)
        self.play(Write(b8_l1))
        self.wait(2)
        self.play(Write(b8_l2))
        self.play(Create(SurroundingRectangle(b8_l2, color=GREEN)))
        self.wait(2)
        b8_l3 = Tex(r"3 cans a week $=$ 156 cans a year — a ghost's month").scale(0.95).shift(band_shift(8) + DOWN * 0.4)
        self.play(Write(b8_l3))
        self.wait(2.5)
        b8_l4 = Tex("Fences: split the jobs, keep the papers, lock up,").scale(0.95).shift(band_shift(8) + DOWN * 1.2)
        b8_l5 = Tex("surprise counts by someone else, read the trend").scale(0.95).shift(band_shift(8) + DOWN * 1.9)
        self.play(Write(b8_l4))
        self.play(Write(b8_l5))
        self.wait(2.5)
        b8_l6 = Tex("Puff the fridge up or squash it down — both are lies").scale(0.95).shift(band_shift(8) + DOWN * 2.8)
        self.play(Write(b8_l6))
        self.play(Create(SurroundingRectangle(b8_l6, color=GREEN)))
        self.wait(4)
