from manim import *

# Band-layout whiteboard scene (reference: quadratics-by-factorisation).
# One band per teaching beat, add-only lifecycle, camera moves down between
# bands. Covers all seven subtopics: Part 1 Expert (quadratic equations and
# the discriminant, the three function families, trig identities and general
# solutions, trig graphs and triangle rules) then Part 2 Simplifier (delta
# as the warning light, graphs as machines with dials, one circle and the
# final sweep). Band dwell proportional to subtopics.json
# (250/240/235/245/185/185/180 of 1520 s).

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class AlgebraFunctionsTrigRevisionSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic display while intro.md plays (~4-5% of scene).
        self.wait(16)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): the three weapons ---
        title = Tex("Algebra, Functions and Trig Essentials").scale(1.2).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = MathTex(r"x^2 - 5x + 6 = 0 \Rightarrow (x-2)(x-3) = 0").scale(1.05).shift(UP * 1.0)
        self.play(Write(b0_l1))
        self.wait(2)
        b0_l2 = MathTex(r"x = 2 \text{ or } x = 3 \quad \text{(factors visible)}").scale(1.05).shift(UP * 0.1)
        self.play(Write(b0_l2))
        self.wait(2)
        b0_l3 = MathTex(r"x^2 - 4x - 3 = 0: \; x = \frac{4 \pm \sqrt{28}}{2}").scale(1.05).shift(DOWN * 1.0)
        self.play(Write(b0_l3))
        self.wait(2.5)
        b0_l4 = MathTex(r"x = 2 \pm \sqrt{7} \quad \text{(formula never jams)}").scale(1.05).shift(DOWN * 2.1)
        self.play(Write(b0_l4))
        self.play(Create(SurroundingRectangle(b0_l4, color=GREEN)))
        self.wait(2.5)

        # --- Band 1 (subtopic_1): delta and the inequality ---
        self.next_band(1)
        b1_title = MathTex(r"\Delta = b^2 - 4ac \text{ runs the show}").scale(1.15).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l1 = Tex(r"$\Delta > 0$: two real; $\Delta = 0$: one; $\Delta < 0$: none").scale(1.0).shift(band_shift(1) + UP * 1.1)
        self.play(Write(b1_l1))
        self.wait(2.5)
        b1_l2 = Tex(r"Perfect square: rational; $28$: irrational").scale(1.0).shift(band_shift(1) + UP * 0.2)
        self.play(Write(b1_l2))
        self.wait(2.5)
        b1_l3 = MathTex(r"x^2 - x - 6 < 0: \;\; (x-3)(x+2) < 0").scale(1.05).shift(band_shift(1) + DOWN * 0.8)
        self.play(Write(b1_l3))
        self.wait(2)
        b1_l4 = MathTex(r"-2 < x < 3 \;\; (\text{below the axis BETWEEN roots})").scale(1.0).shift(band_shift(1) + DOWN * 1.7)
        self.play(Write(b1_l4))
        self.play(Create(SurroundingRectangle(b1_l4, color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_1): the surd equation's ghost ---
        self.next_band(2)
        b2_title = MathTex(r"\sqrt{x + 7} = x - 5").scale(1.2).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(1.5)
        b2_l1 = MathTex(r"x + 7 = x^2 - 10x + 25").scale(1.1).shift(band_shift(2) + UP * 1.1)
        self.play(Write(b2_l1))
        self.wait(2)
        b2_l2 = MathTex(r"x^2 - 11x + 18 = 0 \Rightarrow x = 9 \text{ or } x = 2").scale(1.05).shift(band_shift(2) + UP * 0.2)
        self.play(Write(b2_l2))
        self.wait(2)
        b2_l3 = MathTex(r"x = 9: \sqrt{16} = 4 = 9 - 5 \;\checkmark").scale(1.05).shift(band_shift(2) + DOWN * 0.8)
        self.play(Write(b2_l3))
        self.wait(2)
        b2_l4 = MathTex(r"x = 2: \sqrt{9} = 3 \neq -3").scale(1.05).shift(band_shift(2) + DOWN * 1.7)
        self.play(Write(b2_l4))
        self.play(Create(strike(b2_l4)))
        self.wait(2)
        b2_l5 = Tex("Squaring makes ghosts — the check is the method").scale(1.0).shift(band_shift(2) + DOWN * 2.7)
        self.play(Write(b2_l5))
        self.wait(2.5)

        # --- Band 3 (subtopic_2): the parabola's anatomy ---
        self.next_band(3)
        b3_title = MathTex(r"y = 2(x - 1)^2 - 8").scale(1.2).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(1.5)
        b3_l1 = MathTex(r"\text{Turning point } (1; -8) \text{ — sign flips on } p").scale(1.0).shift(band_shift(3) + UP * 1.1)
        self.play(Write(b3_l1))
        self.wait(2.5)
        b3_l2 = MathTex(r"y\text{-int: } x = 0 \Rightarrow 2(1) - 8 = -6").scale(1.05).shift(band_shift(3) + UP * 0.2)
        self.play(Write(b3_l2))
        self.wait(2)
        b3_l3 = MathTex(r"x\text{-int: } (x-1)^2 = 4 \Rightarrow x = 3 \text{ or } -1").scale(1.05).shift(band_shift(3) + DOWN * 0.7)
        self.play(Write(b3_l3))
        self.wait(2.5)
        b3_l4 = Tex("Four anchors, one parabola, full marks").scale(1.05).shift(band_shift(3) + DOWN * 1.7)
        self.play(Write(b3_l4))
        self.play(Create(SurroundingRectangle(b3_l4, color=GREEN)))
        self.wait(2.5)

        # --- Band 4 (subtopic_2): hyperbola, exponential, the grammar ---
        self.next_band(4)
        b4_title = Tex("Hyperbola and exponential: asymptotes first").scale(1.1).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(1.5)
        b4_l1 = MathTex(r"y = \frac{3}{x - 2} + 1: \;\; x = 2, \; y = 1").scale(1.05).shift(band_shift(4) + UP * 1.1)
        self.play(Write(b4_l1))
        self.wait(2.5)
        b4_l2 = Tex(r"Domain $x \neq 2$; range $y \neq 1$ — the fences").scale(1.0).shift(band_shift(4) + UP * 0.2)
        self.play(Write(b4_l2))
        self.wait(2.5)
        b4_l3 = MathTex(r"y = 2 \cdot 3^x + 1: \;\; \text{asymptote } y = 1, \; y > 1").scale(1.0).shift(band_shift(4) + DOWN * 0.8)
        self.play(Write(b4_l3))
        self.wait(2.5)
        b4_l4 = Tex(r"One grammar: $p$ slides (flipped), $q$ lifts, $a$ stretches").scale(0.95).shift(band_shift(4) + DOWN * 1.8)
        self.play(Write(b4_l4))
        self.play(Create(SurroundingRectangle(b4_l4, color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_3): identities and reduction ---
        self.next_band(5)
        b5_title = Tex("Two identities power everything").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(1.5)
        b5_l1 = MathTex(r"\tan x = \frac{\sin x}{\cos x}, \; \sin^2 x + \cos^2 x = 1").scale(1.05).shift(band_shift(5) + UP * 1.1)
        self.play(Write(b5_l1))
        self.play(Create(SurroundingRectangle(b5_l1, color=GREEN)))
        self.wait(2.5)
        b5_l2 = MathTex(r"\sin(180^\circ - x) = \sin x, \;\; \cos(180^\circ + x) = -\cos x").scale(0.95).shift(band_shift(5) + UP * 0.1)
        self.play(Write(b5_l2))
        self.wait(2.5)
        b5_l3 = MathTex(r"\sin(360^\circ - x) = -\sin x, \;\; \cos(-x) = \cos x").scale(0.95).shift(band_shift(5) + DOWN * 0.8)
        self.play(Write(b5_l3))
        self.wait(2.5)
        b5_l4 = MathTex(r"\sin 150^\circ: \text{ref } 30^\circ \Rightarrow \tfrac{1}{2}").scale(1.0).shift(band_shift(5) + DOWN * 1.8)
        self.play(Write(b5_l4))
        self.wait(2.5)

        # --- Band 6 (subtopic_3): general solutions ---
        self.next_band(6)
        b6_title = Tex("General solutions: the circle keeps spinning").scale(1.1).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(1.5)
        b6_l1 = MathTex(r"\sin x = \tfrac{1}{2}: \; x = 30^\circ \text{ or } 150^\circ").scale(1.05).shift(band_shift(6) + UP * 1.1)
        self.play(Write(b6_l1))
        self.wait(2)
        b6_l2 = MathTex(r"+ k \cdot 360^\circ \text{ — both families}").scale(1.05).shift(band_shift(6) + UP * 0.2)
        self.play(Write(b6_l2))
        self.play(Create(SurroundingRectangle(b6_l2, color=GREEN)))
        self.wait(2.5)
        b6_l3 = MathTex(r"\cos x = -\tfrac{1}{2}: \pm 120^\circ + k \cdot 360^\circ").scale(1.05).shift(band_shift(6) + DOWN * 0.8)
        self.play(Write(b6_l3))
        self.wait(2.5)
        b6_l4 = MathTex(r"\tan: \text{ one solution, every } 180^\circ").scale(1.05).shift(band_shift(6) + DOWN * 1.7)
        self.play(Write(b6_l4))
        self.wait(2)
        b6_l5 = Tex("Restricted interval? Let $k$ run, keep what lands inside").scale(0.95).shift(band_shift(6) + DOWN * 2.7)
        self.play(Write(b6_l5))
        self.wait(2.5)

        # --- Band 7 (subtopic_4): trig graphs and the sine rule ---
        self.next_band(7)
        b7_title = Tex("Waves with dials, then any triangle").scale(1.1).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(1.5)
        b7_l1 = MathTex(r"\sin 2x: \text{period } 180^\circ; \; \sin(x - 30^\circ): \text{late}").scale(0.95).shift(band_shift(7) + UP * 1.1)
        self.play(Write(b7_l1))
        self.wait(2.5)
        b7_l2 = MathTex(r"\text{Sine rule: } \frac{a}{\sin A} = \frac{b}{\sin B}").scale(1.0).shift(band_shift(7) + UP * 0.0)
        self.play(Write(b7_l2))
        self.wait(2.5)
        b7_l3 = MathTex(r"\frac{8 \sin 60^\circ}{\sin 40^\circ} \approx 10{,}78").scale(1.05).shift(band_shift(7) + DOWN * 1.1)
        self.play(Write(b7_l3))
        self.play(Create(SurroundingRectangle(b7_l3, color=GREEN)))
        self.wait(2.5)

        # --- Band 8 (subtopic_4): cosine rule, area rule, the museum ---
        self.next_band(8)
        b8_title = Tex("Cosine rule and area rule").scale(1.15).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(1.5)
        b8_l1 = MathTex(r"a^2 = 130 - 126\cos 50^\circ \Rightarrow a \approx 7").scale(0.95).shift(band_shift(8) + UP * 1.1)
        self.play(Write(b8_l1))
        self.wait(2.5)
        b8_l2 = MathTex(r"\text{Area} = \tfrac{1}{2}(7)(9)\sin 50^\circ \approx 24{,}13").scale(1.05).shift(band_shift(8) + UP * 0.1)
        self.play(Write(b8_l2))
        self.play(Create(SurroundingRectangle(b8_l2, color=GREEN)))
        self.wait(2.5)
        b8_l3 = Tex("Museum: ghost roots; $p$'s sign; the lost family;").scale(1.0).shift(band_shift(8) + DOWN * 1.0)
        self.play(Write(b8_l3))
        b8_l4 = Tex("the non-included angle — four marks lost yearly").scale(1.0).shift(band_shift(8) + DOWN * 1.9)
        self.play(Write(b8_l4))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 9 (subtopic_5): delta as the warning light ---
        self.next_band(9)
        b9_title = Tex("Delta as the warning light").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex("Green — two crossings; one dot — a kiss; red — floats clear").scale(0.95).shift(band_shift(9) + UP * 1.1)
        self.play(Write(b9_l1))
        self.wait(2.5)
        b9_l2 = Tex("One calculation answers nature-of-roots — no solving").scale(1.0).shift(band_shift(9) + UP * 0.2)
        self.play(Write(b9_l2))
        self.play(Create(SurroundingRectangle(b9_l2, color=GREEN)))
        self.wait(2.5)
        b9_l3 = Tex("Attachments: factorise / formula / complete the square").scale(1.0).shift(band_shift(9) + DOWN * 0.8)
        self.play(Write(b9_l3))
        self.wait(2)
        b9_l4 = Tex("Inequalities want a REGION — sketch and shade").scale(1.0).shift(band_shift(9) + DOWN * 1.7)
        self.play(Write(b9_l4))
        self.wait(2)
        b9_l5 = Tex("Surd jobs: reject every ghost in writing").scale(1.0).shift(band_shift(9) + DOWN * 2.6)
        self.play(Write(b9_l5))
        self.wait(2.5)

        # --- Band 10 (subtopic_6): machines with dials ---
        self.next_band(10)
        b10_title = Tex("Graphs as machines with dials").scale(1.2).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_title))
        self.wait(2)
        b10_l1 = Tex(r"Dial $a$: stretch and flip. Dial $q$: honest elevator").scale(1.0).shift(band_shift(10) + UP * 1.1)
        self.play(Write(b10_l1))
        self.wait(2.5)
        b10_l2 = Tex(r"Dial $p$: slider with the flipped label — $+p$ slides LEFT").scale(0.95).shift(band_shift(10) + UP * 0.2)
        self.play(Write(b10_l2))
        self.wait(2.5)
        b10_l3 = MathTex(r"2(x-1)^2 - 8: \text{ right 1, down 8} \Rightarrow (1; -8)").scale(1.0).shift(band_shift(10) + DOWN * 0.8)
        self.play(Write(b10_l3))
        self.play(Create(SurroundingRectangle(b10_l3, color=GREEN)))
        self.wait(2.5)
        b10_l4 = Tex("Hyperbola: dials move the CROSS; exponential: the floor").scale(0.95).shift(band_shift(10) + DOWN * 1.8)
        self.play(Write(b10_l4))
        self.wait(2)
        b10_l5 = Tex("Reading a graph: anchor first, dials second").scale(1.0).shift(band_shift(10) + DOWN * 2.7)
        self.play(Write(b10_l5))
        self.wait(2.5)

        # --- Band 11 (subtopic_7): one circle, and the final sweep ---
        self.next_band(11)
        b11_title = Tex("One circle, every triangle — final sweep").scale(1.15).shift(band_shift(11) + UP * 2.2)
        self.play(Write(b11_title))
        self.wait(2)
        b11_l1 = Tex("Sine is the height, cosine the shadow — CAST records signs").scale(0.9).shift(band_shift(11) + UP * 1.1)
        self.play(Write(b11_l1))
        self.wait(2.5)
        b11_l2 = Tex("General solutions: the circle refuses to stop spinning").scale(0.95).shift(band_shift(11) + UP * 0.2)
        self.play(Write(b11_l2))
        self.wait(2.5)
        b11_l3 = Tex("Matching pair: sine rule. Gripped angle or SSS: cosine").scale(0.95).shift(band_shift(11) + DOWN * 0.7)
        self.play(Write(b11_l3))
        self.wait(2.5)
        b11_l4 = Tex("Traps: ghosts, $p$'s sign, lost family, non-included angle").scale(0.9).shift(band_shift(11) + DOWN * 1.6)
        self.play(Write(b11_l4))
        self.play(Create(SurroundingRectangle(b11_l4, color=GREEN)))
        self.wait(2.5)
        b11_l5 = Tex("Substitute back, check with special angles — free proof").scale(0.9).shift(band_shift(11) + DOWN * 2.6)
        self.play(Write(b11_l5))
        self.wait(4)
