from manim import *

# BAND LAYOUT: sequential vertical bands, one frame-height each; the camera
# moves down between teaching steps and nothing is ever removed. Only
# exporter-supported mobjects (Tex/MathTex, Line/Arrow, Dot, Circle,
# Rectangle/SurroundingRectangle) with write-only reveals — no sub-part
# transforms. The floor plan and elevation are hand-built from Rectangles and
# Lines (no Arc: the door swing is shown as a straight leaf line).
#
# Mirrors script.md across the seven subtopics of the duo (Part 1 — Expert:
# subtopics 1-4; Part 2 — Simplifier: 5-7); band time proportional to
# subtopics.json.

BAND = config.frame_height


def band_shift(k):
    """World-space shift that places content in band k."""
    return DOWN * BAND * k


class ScaleFloorElevationPlansSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic full-screen while intro.md audio plays (~4-5%).
        self.wait(15)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): the number scale ---
        title = Tex("Scale, Floor Plans and Elevation Plans").scale(1.1).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        l01 = Tex("Number scale 1 : 50 — same units both sides").scale(1.0).shift(UP * 1.3)
        self.play(Write(l01))
        self.wait(2)
        l02 = MathTex(r"1:50: \; 1 \text{ cm} = 50 \text{ cm} = 0{,}5 \text{ m}").scale(1.05).shift(UP * 0.4)
        l03 = MathTex(r"1:100: \; 1 \text{ cm} = 100 \text{ cm} = 1 \text{ m}").scale(1.05).shift(DOWN * 0.5)
        l04 = MathTex(r"1:2\,000\,000: \; 1 \text{ cm} = 20 \text{ km}").scale(1.05).shift(DOWN * 1.4)
        self.play(Write(l02))
        self.wait(2)
        self.play(Write(l03))
        self.wait(2)
        self.play(Write(l04))
        self.wait(2)
        l05 = Tex("Bigger second number = smaller drawing").scale(1.0).shift(DOWN * 2.5)
        self.play(Write(l05))
        self.wait(3)

        # --- Band 1 (subtopic_1): the bar scale and the photocopier ---
        self.next_band(1)
        b1_t = Tex("The bar scale: a ruler printed on the plan").scale(1.05).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_t))
        self.wait(1.5)
        # Bar scale: 3 segments of 2 cm each, labelled 1 m apiece.
        bar = Rectangle(width=6.0, height=0.5).shift(band_shift(1) + UP * 1.0)
        d1 = Line(band_shift(1) + UP * 1.25 + LEFT * 1.0, band_shift(1) + UP * 0.75 + LEFT * 1.0)
        d2 = Line(band_shift(1) + UP * 1.25 + RIGHT * 1.0, band_shift(1) + UP * 0.75 + RIGHT * 1.0)
        self.play(Create(bar))
        self.play(Create(d1), Create(d2))
        m0 = MathTex("0").scale(0.8).shift(band_shift(1) + UP * 0.35 + LEFT * 3.0)
        m1 = MathTex(r"1\text{ m}").scale(0.8).shift(band_shift(1) + UP * 0.35 + LEFT * 1.0)
        m2 = MathTex(r"2\text{ m}").scale(0.8).shift(band_shift(1) + UP * 0.35 + RIGHT * 1.0)
        m3 = MathTex(r"3\text{ m}").scale(0.8).shift(band_shift(1) + UP * 0.35 + RIGHT * 3.0)
        self.play(Write(m0), Write(m1), Write(m2), Write(m3))
        self.wait(2)
        b1_l1 = Tex("Each 2 cm segment stands for 1 m — 1 : 50").scale(1.0).shift(band_shift(1) + DOWN * 0.6)
        self.play(Write(b1_l1))
        self.wait(2)
        b1_l2 = Tex("Photocopy at 80\\%: the ratio becomes a lie,").scale(1.0).shift(band_shift(1) + DOWN * 1.5)
        b1_l3 = Tex("but the bar shrinks with the page — still true").scale(1.0).shift(band_shift(1) + DOWN * 2.3)
        self.play(Write(b1_l2))
        self.wait(2)
        self.play(Write(b1_l3))
        self.play(Create(SurroundingRectangle(b1_l3, color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): ruler to reality and back ---
        self.next_band(2)
        b2_t = Tex("Plan to reality: multiply. Back: divide.").scale(1.1).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(1.5)
        b2_l1 = MathTex(r"8{,}4 \text{ cm} \times 50 = 420 \text{ cm} = 4{,}20 \text{ m}").scale(1.05).shift(band_shift(2) + UP * 1.1)
        self.play(Write(b2_l1))
        self.wait(2.5)
        b2_l2 = MathTex(r"6{,}0 \text{ cm} \times 50 = 300 \text{ cm} = 3{,}00 \text{ m}").scale(1.05).shift(band_shift(2) + UP * 0.2)
        self.play(Write(b2_l2))
        self.wait(2.5)
        b2_l3 = Tex("Stoep 5,5 m on a 1 : 100 plan:").scale(1.0).shift(band_shift(2) + DOWN * 0.8)
        b2_l4 = MathTex(r"5{,}5 \text{ m} = 550 \text{ cm}; \;\; 550 \div 100 = 5{,}5 \text{ cm}").scale(1.0).shift(band_shift(2) + DOWN * 1.7)
        self.play(Write(b2_l3))
        self.wait(2)
        self.play(Write(b2_l4))
        self.play(Create(SurroundingRectangle(b2_l4, color=GREEN)))
        b2_l5 = Tex("Convert units first, then apply the ratio").scale(0.95).shift(band_shift(2) + DOWN * 2.7)
        self.play(Write(b2_l5))
        self.wait(3)

        # --- Band 3 (subtopic_2): the quotation ---
        self.next_band(3)
        b3_t = Tex("Turning the room into a quotation").scale(1.1).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t))
        self.wait(1.5)
        b3_l1 = MathTex(r"\text{Carpet: } 4{,}20 \times 3{,}00 = 12{,}6 \text{ m}^2").scale(1.0).shift(band_shift(3) + UP * 1.2)
        b3_l2 = Tex("$12{,}6 \\times 189 =$ R2 381,40").scale(1.0).shift(band_shift(3) + UP * 0.4)
        self.play(Write(b3_l1))
        self.wait(2)
        self.play(Write(b3_l2))
        self.wait(2)
        b3_l3 = MathTex(r"\text{Skirting: } 2(4{,}20 + 3{,}00) - 0{,}9 = 13{,}5 \text{ m}").scale(0.95).shift(band_shift(3) + DOWN * 0.5)
        b3_l4 = Tex("$13{,}5 \\times$ R42,00 = R567,00").scale(1.0).shift(band_shift(3) + DOWN * 1.3)
        self.play(Write(b3_l3))
        self.wait(2.5)
        self.play(Write(b3_l4))
        self.wait(2)
        b3_l5 = MathTex(r"\text{Paving: } 11 \div 0{,}02 = 550; \; \times 1{,}05 \to 578").scale(0.95).shift(band_shift(3) + DOWN * 2.2)
        self.play(Write(b3_l5))
        self.play(Create(SurroundingRectangle(b3_l5, color=GREEN)))
        b3_l6 = Tex("Materials always round UP").scale(0.95).shift(band_shift(3) + DOWN * 3.1)
        self.play(Write(b3_l6))
        self.wait(3)

        # --- Band 4 (subtopic_3): reading a floor plan ---
        self.next_band(4)
        b4_t = Tex("The floor plan: roof lifted off").scale(1.1).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(1.5)
        # Room outline with a door gap on the bottom wall and window on top.
        c = band_shift(4) + DOWN * 0.8 + LEFT * 2.2
        w_top = Line(c + LEFT * 2.1 + UP * 1.5, c + RIGHT * 2.1 + UP * 1.5)
        w_left = Line(c + LEFT * 2.1 + UP * 1.5, c + LEFT * 2.1 + DOWN * 1.5)
        w_right = Line(c + RIGHT * 2.1 + UP * 1.5, c + RIGHT * 2.1 + DOWN * 1.5)
        w_bot1 = Line(c + LEFT * 2.1 + DOWN * 1.5, c + LEFT * 0.3 + DOWN * 1.5)
        w_bot2 = Line(c + RIGHT * 0.9 + DOWN * 1.5, c + RIGHT * 2.1 + DOWN * 1.5)
        self.play(Create(w_top), Create(w_left), Create(w_right))
        self.play(Create(w_bot1), Create(w_bot2))
        leaf = Line(c + LEFT * 0.3 + DOWN * 1.5, c + LEFT * 0.3 + DOWN * 0.3)
        self.play(Create(leaf))
        door_lab = Tex("door + swing").scale(0.7).shift(c + DOWN * 2.0 + RIGHT * 0.3)
        self.play(Write(door_lab))
        win = Line(c + LEFT * 0.6 + UP * 1.62, c + RIGHT * 0.6 + UP * 1.62)
        win2 = Line(c + LEFT * 0.6 + UP * 1.38, c + RIGHT * 0.6 + UP * 1.38)
        win_lab = Tex("window").scale(0.7).shift(c + UP * 2.0)
        self.play(Create(win), Create(win2), Write(win_lab))
        bed = Tex("BED").scale(0.8).shift(c)
        self.play(Write(bed))
        self.wait(2)
        b4_l1 = Tex("Dimensions in mm: 4 200 = 4,2 m").scale(0.95).shift(band_shift(4) + UP * 1.0 + RIGHT * 3.0)
        b4_l2 = Tex("Arc shows the door swing").scale(0.95).shift(band_shift(4) + UP * 0.1 + RIGHT * 3.0)
        b4_l3 = Tex("North arrow = sun and weather").scale(0.95).shift(band_shift(4) + DOWN * 0.8 + RIGHT * 3.0)
        self.play(Write(b4_l1))
        self.wait(2)
        self.play(Write(b4_l2))
        self.wait(2)
        self.play(Write(b4_l3))
        self.wait(2)
        b4_l4 = Tex("Analyse like a family: propose the fix").scale(0.95).shift(band_shift(4) + DOWN * 3.2)
        self.play(Write(b4_l4))
        self.wait(3)

        # --- Band 5 (subtopic_4): the elevation ---
        self.next_band(5)
        b5_t = Tex("The elevation: standing straight in front").scale(1.05).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_t))
        self.wait(1.5)
        e = band_shift(5) + DOWN * 1.0 + LEFT * 2.4
        wall = Rectangle(width=4.0, height=2.4).shift(e)
        self.play(Create(wall))
        roof = Line(e + LEFT * 2.0 + UP * 1.2, e + RIGHT * 2.0 + UP * 1.8)
        self.play(Create(roof))
        winr = Rectangle(width=1.2, height=1.2).shift(e + RIGHT * 0.9 + DOWN * 0.0 + UP * 0.3)
        self.play(Create(winr))
        h1 = Tex("wall 2,4 m").scale(0.75).shift(e + LEFT * 2.9 + UP * 0.0)
        h2 = Tex("sill 0,9 m").scale(0.75).shift(e + RIGHT * 0.9 + DOWN * 1.0)
        h3 = Tex("head at 2,1 m").scale(0.75).shift(e + RIGHT * 0.9 + UP * 1.25)
        self.play(Write(h1))
        self.wait(1.5)
        self.play(Write(h2), Write(h3))
        self.wait(2)
        b5_l1 = Tex("Named by the direction the wall FACES").scale(0.95).shift(band_shift(5) + UP * 1.1 + RIGHT * 2.6)
        self.play(Write(b5_l1))
        self.wait(2)
        b5_l2 = Tex("Elevation: heights, roof slope").scale(0.95).shift(band_shift(5) + UP * 0.2 + RIGHT * 2.9)
        b5_l3 = Tex("Floor plan: layout, areas").scale(0.95).shift(band_shift(5) + DOWN * 0.6 + RIGHT * 3.0)
        self.play(Write(b5_l2))
        self.play(Write(b5_l3))
        self.wait(3)

        # --- Band 6 (subtopic_4): combining the two drawings ---
        self.next_band(6)
        b6_t = Tex("Combine the drawings: wall area to paint").scale(1.05).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_t))
        self.wait(1.5)
        b6_l1 = MathTex(r"\text{Plan gives } 14{,}4 \text{ m; elevation gives } 2{,}4 \text{ m}").scale(0.95).shift(band_shift(6) + UP * 1.2)
        b6_l2 = MathTex(r"14{,}4 \times 2{,}4 = 34{,}56 \text{ m}^2").scale(1.05).shift(band_shift(6) + UP * 0.3)
        self.play(Write(b6_l1))
        self.wait(2.5)
        self.play(Write(b6_l2))
        self.wait(2)
        b6_l3 = MathTex(r"\text{Door: } 0{,}9 \times 2{,}1 = 1{,}89 \text{ m}^2").scale(1.0).shift(band_shift(6) + DOWN * 0.6)
        b6_l4 = MathTex(r"\text{Window: } 1{,}2 \times 1{,}2 = 1{,}44 \text{ m}^2").scale(1.0).shift(band_shift(6) + DOWN * 1.5)
        self.play(Write(b6_l3))
        self.wait(2)
        self.play(Write(b6_l4))
        self.wait(2)
        b6_l5 = MathTex(r"34{,}56 - 1{,}89 - 1{,}44 = 31{,}23 \text{ m}^2").scale(1.05).shift(band_shift(6) + DOWN * 2.4)
        self.play(Write(b6_l5))
        self.play(Create(SurroundingRectangle(b6_l5, color=GREEN)))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 7 (subtopic_5): the shrunk house ---
        self.next_band(7)
        b7_t = Tex("The shrunk house").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(2)
        b7_l1 = Tex("1 : 50 = fifty times smaller").scale(1.05).shift(band_shift(7) + UP * 1.2)
        self.play(Write(b7_l1))
        self.wait(2)
        b7_l2 = MathTex(r"\text{Page to reality: } 8{,}4 \times 50 = 420 \text{ cm}").scale(1.0).shift(band_shift(7) + UP * 0.3)
        self.play(Write(b7_l2))
        self.wait(2)
        b7_l3 = MathTex(r"\text{Reality to page: } 550 \div 100 = 5{,}5 \text{ cm}").scale(1.0).shift(band_shift(7) + DOWN * 0.6)
        self.play(Write(b7_l3))
        self.play(Create(SurroundingRectangle(b7_l3, color=GREEN)))
        self.wait(2.5)
        b7_l4 = Tex("The photocopier doesn't know ratios —").scale(1.0).shift(band_shift(7) + DOWN * 1.6)
        b7_l5 = Tex("the printed ruler shrinks too, so trust it").scale(1.0).shift(band_shift(7) + DOWN * 2.4)
        self.play(Write(b7_l4))
        self.play(Write(b7_l5))
        self.wait(3)

        # --- Band 8 (subtopic_6): bird's eye vs standing in front ---
        self.next_band(8)
        b8_t = Tex("Bird's eye and standing-in-front").scale(1.1).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_t))
        self.wait(2)
        b8_l1 = Tex("Floor plan: roof off, looking down —").scale(1.0).shift(band_shift(8) + UP * 1.2)
        b8_l2 = Tex("answers ``where is everything?''").scale(1.0).shift(band_shift(8) + UP * 0.4)
        self.play(Write(b8_l1))
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = Tex("Elevation: one wall, straight on —").scale(1.0).shift(band_shift(8) + DOWN * 0.5)
        b8_l4 = Tex("answers ``how high?''").scale(1.0).shift(band_shift(8) + DOWN * 1.3)
        self.play(Write(b8_l3))
        self.play(Write(b8_l4))
        self.wait(2.5)
        b8_l5 = Tex("4 200 on a plan means millimetres: 4,2 m").scale(0.95).shift(band_shift(8) + DOWN * 2.2)
        self.play(Write(b8_l5))
        self.play(Create(SurroundingRectangle(b8_l5, color=GREEN)))
        self.wait(3)

        # --- Band 9 (subtopic_7): the shopping list ---
        self.next_band(9)
        b9_t = Tex("Turning the plan into a shopping list").scale(1.05).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(2)
        b9_l1 = Tex("Floor: 12,6 m$^2$ carpet — R2 381,40").scale(1.0).shift(band_shift(9) + UP * 1.2)
        self.play(Write(b9_l1))
        self.wait(2)
        b9_l2 = Tex("Edge: 14,4 $-$ 0,9 = 13,5 m — R567,00").scale(1.0).shift(band_shift(9) + UP * 0.3)
        self.play(Write(b9_l2))
        self.wait(2)
        b9_l3 = Tex("Stoep: 550 blocks + 5\\% = 578 blocks").scale(1.0).shift(band_shift(9) + DOWN * 0.6)
        self.play(Write(b9_l3))
        self.wait(2)
        b9_l4 = Tex("Walls: 34,56 $-$ 1,89 $-$ 1,44 = 31,23 m$^2$").scale(1.0).shift(band_shift(9) + DOWN * 1.5)
        self.play(Write(b9_l4))
        self.play(Create(SurroundingRectangle(b9_l4, color=GREEN)))
        self.wait(2)
        b9_l5 = Tex("Two drawings shake hands on that number").scale(0.95).shift(band_shift(9) + DOWN * 2.4)
        self.play(Write(b9_l5))
        self.wait(4)
