from manim import *

# Band layout: one frame-height band per teaching beat; the camera moves down
# to fresh space and earlier work stays on the canvas. Only exporter-supported
# mobjects; every line of working is a single-string MathTex revealed with
# Write — no sub-part transforms.
#
# Mirrors script.md across all seven subtopics (Part 1 — Expert: 1-4;
# Part 2 — Simplifier: 5-7), band time roughly proportional to subtopics.json
# (230/240/230/250/185/185/180 of 1500 s).

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class SpheresPyramidsConesSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic display holds while intro.md audio plays.
        self.wait(15)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): the one-third family
        title = Tex("Spheres, Pyramids, Cones and Combined Solids").scale(1.1).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = MathTex(r"V = \tfrac{1}{3} \times \text{base area} \times h").scale(1.2).shift(UP * 0.9)
        self.play(Write(b0_l1))
        self.wait(2.5)
        b0_l2 = Tex(r"Three cone-pours fill the cylinder — exactly").scale(1.05).shift(DOWN * 0.2)
        self.play(Write(b0_l2))
        self.wait(2.5)
        b0_l3 = Tex(r"$h$ is the PERPENDICULAR height,").scale(1.05).shift(DOWN * 1.2)
        b0_l4 = Tex(r"apex straight down to the centre").scale(1.05).shift(DOWN * 2.0)
        self.play(Write(b0_l3))
        self.play(Write(b0_l4))
        self.wait(3)

        # --- Band 1 (subtopic_1): both volumes worked
        self.next_band(1)
        b1_t1 = Tex(r"Pyramid: base edge 10, height 12").scale(1.1).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_t1))
        self.wait(1.5)
        b1_l1 = MathTex(r"V = \tfrac{1}{3} \times 100 \times 12 = 400 \text{ cm}^3").scale(1.1).shift(band_shift(1) + UP * 1.2)
        self.play(Write(b1_l1))
        self.play(Create(SurroundingRectangle(b1_l1, color=GREEN)))
        self.wait(2.5)
        b1_t2 = Tex(r"Cone: radius 6, height 8").scale(1.1).shift(band_shift(1) + DOWN * 0.1)
        self.play(Write(b1_t2))
        self.wait(1.5)
        b1_l2 = MathTex(r"V = \tfrac{1}{3} \times 36\pi \times 8 = 96\pi").scale(1.1).shift(band_shift(1) + DOWN * 1.1)
        self.play(Write(b1_l2))
        self.wait(2)
        b1_l3 = MathTex(r"96\pi = 301{,}59 \text{ cm}^3").scale(1.1).shift(band_shift(1) + DOWN * 2.1)
        self.play(Write(b1_l3))
        self.play(Create(SurroundingRectangle(b1_l3, color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): slant height from Pythagoras
        self.next_band(2)
        b2_title = Tex("Slant height: Pythagoras builds it").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(1.5)
        vert = Line(DOWN * 1.2, UP * 0.8).shift(band_shift(2) + LEFT * 2.4)
        horiz = Line(LEFT * 2.4 + DOWN * 1.2, LEFT * 0.6 + DOWN * 1.2).shift(band_shift(2))
        hyp = Line(LEFT * 2.4 + UP * 0.8, LEFT * 0.6 + DOWN * 1.2).shift(band_shift(2))
        self.play(Create(vert))
        self.play(Create(horiz))
        self.play(Create(hyp))
        lbl_h = MathTex(r"h").scale(0.9).shift(band_shift(2) + LEFT * 2.8 + DOWN * 0.2)
        lbl_r = MathTex(r"r").scale(0.9).shift(band_shift(2) + LEFT * 1.5 + DOWN * 1.6)
        lbl_s = MathTex(r"s").scale(0.9).shift(band_shift(2) + LEFT * 1.1 + DOWN * 0.1)
        self.play(Write(lbl_h), Write(lbl_r), Write(lbl_s))
        self.wait(2)
        b2_l1 = MathTex(r"s^2 = h^2 + r^2").scale(1.1).shift(band_shift(2) + RIGHT * 2.0 + UP * 0.2)
        self.play(Write(b2_l1))
        self.wait(2)
        b2_l2 = MathTex(r"\text{Cone: } s^2 = 8^2 + 6^2 = 100,\; s = 10").scale(1.05).shift(band_shift(2) + DOWN * 2.0)
        self.play(Write(b2_l2))
        self.wait(2)
        b2_l3 = MathTex(r"\text{Pyramid: } s^2 = 12^2 + 5^2 = 169,\; s = 13").scale(1.05).shift(band_shift(2) + DOWN * 2.9)
        self.play(Write(b2_l3))
        self.wait(3)

        # --- Band 3 (subtopic_2): surface areas assemble
        self.next_band(3)
        b3_t1 = Tex(r"Cone surface: base + curved sector").scale(1.1).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t1))
        self.wait(1.5)
        b3_l1 = MathTex(r"A = \pi r^2 + \pi r s").scale(1.15).shift(band_shift(3) + UP * 1.2)
        self.play(Write(b3_l1))
        self.wait(2)
        b3_l2 = MathTex(r"A = 36\pi + 60\pi = 96\pi = 301{,}59 \text{ cm}^2").scale(1.05).shift(band_shift(3) + UP * 0.2)
        self.play(Write(b3_l2))
        self.play(Create(SurroundingRectangle(b3_l2, color=GREEN)))
        self.wait(2.5)
        b3_t2 = Tex(r"Pyramid: square base + 4 triangles").scale(1.1).shift(band_shift(3) + DOWN * 0.9)
        self.play(Write(b3_t2))
        self.wait(1.5)
        b3_l3 = MathTex(r"\text{Each face: } \tfrac{1}{2} \times 10 \times 13 = 65").scale(1.05).shift(band_shift(3) + DOWN * 1.8)
        self.play(Write(b3_l3))
        self.wait(2)
        b3_l4 = MathTex(r"A = 100 + 4 \times 65 = 360 \text{ cm}^2").scale(1.05).shift(band_shift(3) + DOWN * 2.7)
        self.play(Write(b3_l4))
        self.play(Create(SurroundingRectangle(b3_l4, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): the sphere — two formulas, one radius
        self.next_band(4)
        b4_title = Tex("The sphere: cubed fills, squared wraps").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(2)
        b4_l1 = MathTex(r"V = \tfrac{4}{3}\pi r^3 \qquad A = 4\pi r^2").scale(1.2).shift(band_shift(4) + UP * 1.1)
        self.play(Write(b4_l1))
        self.wait(2.5)
        b4_l2 = MathTex(r"r = 6: \; V = \tfrac{4}{3}\pi \times 216 = 288\pi").scale(1.1).shift(band_shift(4) + UP * 0.0)
        self.play(Write(b4_l2))
        self.wait(2)
        b4_l3 = MathTex(r"288\pi = 904{,}78 \text{ cm}^3").scale(1.1).shift(band_shift(4) + DOWN * 1.0)
        self.play(Write(b4_l3))
        self.wait(2)
        b4_l4 = MathTex(r"A = 4\pi \times 36 = 144\pi = 452{,}39 \text{ cm}^2").scale(1.05).shift(band_shift(4) + DOWN * 2.0)
        self.play(Write(b4_l4))
        self.play(Create(SurroundingRectangle(b4_l4, color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_3): the hemisphere trap
        self.next_band(5)
        b5_title = Tex("The hemisphere: surface does NOT halve").scale(1.1).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(2)
        b5_l1 = MathTex(r"V = \tfrac{1}{2} \times 288\pi = 144\pi \; \checkmark").scale(1.1).shift(band_shift(5) + UP * 1.1)
        self.play(Write(b5_l1))
        self.wait(2)
        b5_wrong = MathTex(r"A = \tfrac{1}{2} \times 144\pi = 72\pi").scale(1.1).shift(band_shift(5) + UP * 0.1)
        self.play(Write(b5_wrong))
        self.play(Create(strike(b5_wrong)))
        self.wait(2)
        b5_l2 = Tex(r"The cut exposes a new circle: $\pi r^2 = 36\pi$").scale(1.05).shift(band_shift(5) + DOWN * 0.9)
        self.play(Write(b5_l2))
        self.wait(2)
        b5_l3 = MathTex(r"A = 72\pi + 36\pi = 108\pi").scale(1.15).shift(band_shift(5) + DOWN * 1.9)
        self.play(Write(b5_l3))
        self.play(Create(SurroundingRectangle(b5_l3, color=GREEN)))
        b5_rule = Tex("Dome on a building? Rim attached — no circle").scale(0.95).shift(band_shift(5) + DOWN * 2.9)
        self.play(Write(b5_rule))
        self.wait(3)

        # --- Band 6 (subtopic_4): ice-cream volume — glued solids add
        self.next_band(6)
        b6_title = Tex("Ice-cream: cone + hemisphere, volume").scale(1.1).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(2)
        b6_l1 = MathTex(r"V_{\text{cone}} = 96\pi \qquad V_{\text{hemi}} = 144\pi").scale(1.1).shift(band_shift(6) + UP * 1.1)
        self.play(Write(b6_l1))
        self.wait(2.5)
        b6_l2 = MathTex(r"V = 96\pi + 144\pi = 240\pi").scale(1.15).shift(band_shift(6) + UP * 0.0)
        self.play(Write(b6_l2))
        self.wait(2)
        b6_l3 = MathTex(r"240\pi = 753{,}98 \text{ cm}^3").scale(1.1).shift(band_shift(6) + DOWN * 1.0)
        self.play(Write(b6_l3))
        self.play(Create(SurroundingRectangle(b6_l3, color=GREEN)))
        self.wait(2)
        b6_rule = Tex("Volume never cares about the join").scale(1.05).shift(band_shift(6) + DOWN * 2.1)
        self.play(Write(b6_rule))
        self.wait(3)

        # --- Band 7 (subtopic_4): surface area — the hidden-face rule
        self.next_band(7)
        b7_title = Tex("Surface: only the OUTSIDE counts").scale(1.1).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(2)
        b7_l1 = Tex(r"Buried at the join: cone base, hemi circle").scale(1.0).shift(band_shift(7) + UP * 1.1)
        self.play(Write(b7_l1))
        self.wait(2.5)
        b7_l2 = MathTex(r"\text{Cone curve: } \pi r s = \pi \times 6 \times 10 = 60\pi").scale(1.05).shift(band_shift(7) + UP * 0.1)
        self.play(Write(b7_l2))
        self.wait(2)
        b7_l3 = MathTex(r"\text{Hemi skin: } 72\pi").scale(1.05).shift(band_shift(7) + DOWN * 0.9)
        self.play(Write(b7_l3))
        self.wait(2)
        b7_l4 = MathTex(r"A = 60\pi + 72\pi = 132\pi = 414{,}69 \text{ cm}^2").scale(1.05).shift(band_shift(7) + DOWN * 1.9)
        self.play(Write(b7_l4))
        self.play(Create(SurroundingRectangle(b7_l4, color=GREEN)))
        b7_rule = Tex(r"Blind adding buries $72\pi$ of phantom area").scale(0.95).shift(band_shift(7) + DOWN * 2.9)
        self.play(Write(b7_rule))
        self.wait(3)

        # --- Band 8 (subtopic_4): the error museum
        self.next_band(8)
        b8_title = Tex("The error museum").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(1.5)
        b8_l1 = Tex(r"1. Slant height fed into a volume formula").scale(1.05).shift(band_shift(8) + UP * 1.1)
        self.play(Write(b8_l1))
        self.wait(2)
        b8_l2 = Tex(r"2. Buried faces counted in a combined solid").scale(1.05).shift(band_shift(8) + UP * 0.2)
        self.play(Write(b8_l2))
        self.wait(2)
        b8_l3 = Tex(r"3. The hemisphere's circle mishandled").scale(1.05).shift(band_shift(8) + DOWN * 0.7)
        self.play(Write(b8_l3))
        self.wait(2)
        b8_l4 = Tex(r"4. The one third dropped: three times too big").scale(1.05).shift(band_shift(8) + DOWN * 1.6)
        self.play(Write(b8_l4))
        self.wait(2)
        b8_l5 = Tex(r"Exact in $\pi$, round last, unit checked").scale(1.05).shift(band_shift(8) + DOWN * 2.6)
        self.play(Write(b8_l5))
        self.play(Create(SurroundingRectangle(b8_l5, color=GREEN)))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 9 (subtopic_5): a funnel, a tent and a soccer ball
        self.next_band(9)
        b9_title = Tex("A funnel, a tent and a soccer ball").scale(1.15).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex(r"Pointy solids: base $\times$ height, divided by 3").scale(1.05).shift(band_shift(9) + UP * 1.1)
        self.play(Write(b9_l1))
        self.wait(2.5)
        b9_l2 = MathTex(r"\text{Tent: } \tfrac{100 \times 12}{3} = 400").scale(1.05).shift(band_shift(9) + UP * 0.1)
        self.play(Write(b9_l2))
        self.wait(2.5)
        b9_l3 = MathTex(r"\text{Funnel: } \tfrac{36\pi \times 8}{3} = 96\pi").scale(1.05).shift(band_shift(9) + DOWN * 0.9)
        self.play(Write(b9_l3))
        self.wait(2.5)
        b9_l4 = Tex(r"Ball: $\tfrac{4}{3}\pi r^3$ fills, $4\pi r^2$ wraps").scale(1.05).shift(band_shift(9) + DOWN * 1.9)
        self.play(Write(b9_l4))
        self.wait(2)
        b9_rule = Tex("Cubed fills, squared wraps").scale(1.1).shift(band_shift(9) + DOWN * 2.9)
        self.play(Write(b9_rule))
        self.play(Create(SurroundingRectangle(b9_rule, color=GREEN)))
        self.wait(3)

        # --- Band 10 (subtopic_6): rondavel — how much air inside
        self.next_band(10)
        b10_title = Tex(r"Rondavel: walls $r=3$, $h=2$; roof $h=4$").scale(1.1).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_title))
        self.wait(2)
        b10_l1 = MathTex(r"\text{Walls: } \pi \times 9 \times 2 = 18\pi").scale(1.1).shift(band_shift(10) + UP * 1.1)
        self.play(Write(b10_l1))
        self.wait(2.5)
        b10_l2 = MathTex(r"\text{Roof: } \tfrac{1}{3} \times \pi \times 9 \times 4 = 12\pi").scale(1.1).shift(band_shift(10) + UP * 0.1)
        self.play(Write(b10_l2))
        self.wait(2.5)
        b10_l3 = MathTex(r"V = 18\pi + 12\pi = 30\pi \approx 94{,}25 \text{ m}^3").scale(1.05).shift(band_shift(10) + DOWN * 1.0)
        self.play(Write(b10_l3))
        self.play(Create(SurroundingRectangle(b10_l3, color=GREEN)))
        self.wait(3)

        # --- Band 11 (subtopic_6): rondavel — plaster and thatch
        self.next_band(11)
        b11_title = Tex("Plaster and thatch: walk the outside").scale(1.1).shift(band_shift(11) + UP * 2.2)
        self.play(Write(b11_title))
        self.wait(2)
        b11_l1 = MathTex(r"\text{Plaster: } 2\pi \times 3 \times 2 = 12\pi \approx 37{,}70").scale(1.05).shift(band_shift(11) + UP * 1.1)
        self.play(Write(b11_l1))
        self.wait(2.5)
        b11_l2 = MathTex(r"\text{Slant: } s^2 = 4^2 + 3^2 \Rightarrow s = 5").scale(1.05).shift(band_shift(11) + UP * 0.1)
        self.play(Write(b11_l2))
        self.wait(2.5)
        b11_l3 = MathTex(r"\text{Thatch: } \pi \times 3 \times 5 = 15\pi \approx 47{,}12").scale(1.05).shift(band_shift(11) + DOWN * 0.9)
        self.play(Write(b11_l3))
        self.play(Create(SurroundingRectangle(b11_l3, color=GREEN)))
        self.wait(2.5)
        b11_l4 = Tex("Ceiling circles buried; floor is the ground").scale(1.0).shift(band_shift(11) + DOWN * 2.0)
        self.play(Write(b11_l4))
        self.wait(3)

        # --- Band 12 (subtopic_7): the trap list
        self.next_band(12)
        b12_title = Tex("The trap list").scale(1.2).shift(band_shift(12) + UP * 2.2)
        self.play(Write(b12_title))
        self.wait(2)
        b12_l1 = Tex(r"1. Perpendicular $h$ for volume, slant $s$ for surface").scale(0.95).shift(band_shift(12) + UP * 1.1)
        self.play(Write(b12_l1))
        self.wait(2.5)
        b12_l2 = Tex(r"2. Hemisphere: half the skin PLUS $\pi r^2$").scale(1.0).shift(band_shift(12) + UP * 0.2)
        self.play(Write(b12_l2))
        self.wait(2.5)
        b12_l3 = Tex(r"3. Cross out both buried faces at a join").scale(1.0).shift(band_shift(12) + DOWN * 0.7)
        self.play(Write(b12_l3))
        self.wait(2.5)
        b12_l4 = Tex(r"4. No one third = three times too big").scale(1.0).shift(band_shift(12) + DOWN * 1.6)
        self.play(Write(b12_l4))
        self.wait(2)
        b12_ans = Tex(r"Pythagoras converts $h \leftrightarrow s$ any time").scale(1.0).shift(band_shift(12) + DOWN * 2.6)
        self.play(Write(b12_ans))
        self.play(Create(SurroundingRectangle(b12_ans, color=GREEN)))
        self.wait(4)
