from manim import *

# Band-layout whiteboard scene for "Solar, Wind and Renewable Energy"
# (grade 11, term 4). All seven subtopics: Part 1 Expert (1-4), Part 2
# Simplifier (5-7). Band time apportioned to subtopics.json
# (230/235/230/235/195/200/200 of 1525 s). Exporter-safe primitives only;
# the CSP mirror field and the wind turbine are hand-built from
# Line/Arrow/Dot/Circle/Tex, element by element.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class SolarWindRenewableEnergySession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic full-screen while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): the family and its two properties
        title = Tex("Solar, Wind and Renewable Energy").scale(1.25).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex(r"Non-conventional: solar, wind, biomass,").scale(1.0).shift(UP * 1.2)
        b0_l2 = Tex(r"biogas, geothermal, wave, small hydro").scale(1.0).shift(UP * 0.5)
        self.play(Write(b0_l1))
        self.play(Write(b0_l2))
        self.wait(2.5)
        b0_l3 = Tex(r"Property 1: the FUEL IS FREE —").scale(1.05).shift(DOWN * 0.5)
        b0_l4 = Tex(r"cost sits in the harvesting machine").scale(1.0).shift(DOWN * 1.2)
        self.play(Write(b0_l3))
        self.play(Write(b0_l4))
        self.wait(2.5)
        b0_l5 = Tex(r"Property 2: INTERMITTENT — sun sets,").scale(1.05).shift(DOWN * 2.1)
        b0_l6 = Tex(r"wind drops: needs storage, backup, mix").scale(1.0).shift(DOWN * 2.8)
        self.play(Write(b0_l5))
        self.play(Write(b0_l6))
        self.wait(3)

        # --- Band 1 (subtopic_1): the endowment and REIPPPP
        self.next_band(1)
        b1_title = Tex("Why South Africa is blessed").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l1 = Tex(r"Interior: over 2 500 sunshine hours/year").scale(1.0).shift(band_shift(1) + UP * 1.2)
        self.play(Write(b1_l1))
        self.wait(2)
        b1_l2 = Tex(r"Northern Cape: world-premium solar land").scale(1.0).shift(band_shift(1) + UP * 0.4)
        self.play(Write(b1_l2))
        self.wait(2)
        b1_l3 = Tex(r"Coasts: strong winds off two oceans").scale(1.0).shift(band_shift(1) + DOWN * 0.4)
        self.play(Write(b1_l3))
        self.wait(2)
        b1_l4 = Tex(r"Cloudy Germany leads solar — resource").scale(1.0).shift(band_shift(1) + DOWN * 1.2)
        b1_l5 = Tex(r"was never South Africa's problem").scale(1.0).shift(band_shift(1) + DOWN * 1.9)
        self.play(Write(b1_l4))
        self.play(Write(b1_l5))
        self.wait(2.5)
        b1_l6 = Tex(r"REIPPPP auctions: new sun and wind now").scale(1.0).shift(band_shift(1) + DOWN * 2.7)
        b1_l7 = Tex(r"cheaper per kWh than new coal").scale(1.05).shift(band_shift(1) + DOWN * 3.4)
        self.play(Write(b1_l6))
        self.play(Write(b1_l7))
        self.play(Create(SurroundingRectangle(b1_l7, color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): PV against CSP — the mirror field
        self.next_band(2)
        b2_title = Tex("Solar: PV against CSP").scale(1.2).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(1.5)
        b2_l1 = Tex(r"PV: sunlight $\Rightarrow$ electricity directly —").scale(1.0).shift(band_shift(2) + UP * 1.3)
        b2_l2 = Tex(r"no moving parts, peaks at noon, dies at dusk").scale(0.95).shift(band_shift(2) + UP * 0.6)
        self.play(Write(b2_l1))
        self.play(Write(b2_l2))
        self.wait(2.5)
        # CSP: mirrors on the ground focus beams onto a tower receiver.
        tower = Line(band_shift(2) + DOWN * 2.6, band_shift(2) + DOWN * 0.6)
        receiver = Circle(radius=0.22, color=YELLOW).shift(band_shift(2) + DOWN * 0.5)
        self.play(Create(tower), Create(receiver))
        m1 = Line(band_shift(2) + DOWN * 2.7 + LEFT * 3.2, band_shift(2) + DOWN * 2.5 + LEFT * 2.6)
        m2 = Line(band_shift(2) + DOWN * 2.8 + LEFT * 1.9, band_shift(2) + DOWN * 2.6 + LEFT * 1.3)
        m3 = Line(band_shift(2) + DOWN * 2.8 + RIGHT * 1.3, band_shift(2) + DOWN * 2.6 + RIGHT * 1.9)
        m4 = Line(band_shift(2) + DOWN * 2.7 + RIGHT * 2.6, band_shift(2) + DOWN * 2.5 + RIGHT * 3.2)
        self.play(Create(m1), Create(m2), Create(m3), Create(m4))
        r1 = Arrow(band_shift(2) + DOWN * 2.5 + LEFT * 2.9, band_shift(2) + DOWN * 0.7 + LEFT * 0.25, color=YELLOW, stroke_width=3)
        r2 = Arrow(band_shift(2) + DOWN * 2.5 + RIGHT * 2.9, band_shift(2) + DOWN * 0.7 + RIGHT * 0.25, color=YELLOW, stroke_width=3)
        mir_lab = Tex("heliostat mirrors").scale(0.8).shift(band_shift(2) + DOWN * 3.3)
        self.play(Create(r1), Create(r2), Write(mir_lab))
        self.wait(2)
        rec_lab = Tex(r"molten salt, hundreds of $^\circ$C").scale(0.85).shift(band_shift(2) + DOWN * 0.4 + RIGHT * 3.3)
        self.play(Write(rec_lab))
        self.wait(2)
        b2_l3 = Tex(r"Hot salt stores for hours: solar after sunset").scale(0.95).shift(band_shift(2) + UP * 0.05)
        self.play(Write(b2_l3))
        self.play(Create(SurroundingRectangle(b2_l3, color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_2): solar examples, SA and world
        self.next_band(3)
        b3_title = Tex("Solar examples to name").scale(1.2).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(1.5)
        b3_l1 = Tex(r"Northern Cape PV farms: Upington, De Aar").scale(1.0).shift(band_shift(3) + UP * 1.2)
        self.play(Write(b3_l1))
        self.wait(2)
        b3_l2 = Tex(r"CSP: Khi Solar One; KaXu and Xina troughs").scale(1.0).shift(band_shift(3) + UP * 0.4)
        self.play(Write(b3_l2))
        self.wait(2)
        b3_l3 = Tex(r"Redstone: 12 h molten-salt storage —").scale(1.0).shift(band_shift(3) + DOWN * 0.4)
        b3_l4 = Tex(r"built to serve the evening peak").scale(1.0).shift(band_shift(3) + DOWN * 1.1)
        self.play(Write(b3_l3))
        self.play(Write(b3_l4))
        self.play(Create(SurroundingRectangle(b3_l4, color=GREEN)))
        self.wait(2.5)
        b3_l5 = Tex(r"Rooftop PV boomed in load-shedding;").scale(1.0).shift(band_shift(3) + DOWN * 2.0)
        b3_l6 = Tex(r"solar water heaters: cheapest solar of all").scale(1.0).shift(band_shift(3) + DOWN * 2.7)
        self.play(Write(b3_l5))
        self.play(Write(b3_l6))
        self.wait(2)
        b3_l7 = Tex(r"World: China's deserts, Germany, Noor (Morocco)").scale(0.95).shift(band_shift(3) + DOWN * 3.4)
        self.play(Write(b3_l7))
        self.wait(3)

        # --- Band 4 (subtopic_3): the turbine and the cube law
        self.next_band(4)
        b4_title = Tex("Wind: the machine and the cube law").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(1.5)
        # Turbine: tower, hub dot, three straight blades.
        t_tower = Line(band_shift(4) + DOWN * 2.6 + LEFT * 3.6, band_shift(4) + DOWN * 0.2 + LEFT * 3.6)
        hub = Dot(band_shift(4) + DOWN * 0.2 + LEFT * 3.6)
        bl1 = Line(band_shift(4) + DOWN * 0.2 + LEFT * 3.6, band_shift(4) + UP * 1.1 + LEFT * 3.3)
        bl2 = Line(band_shift(4) + DOWN * 0.2 + LEFT * 3.6, band_shift(4) + DOWN * 0.7 + LEFT * 2.4)
        bl3 = Line(band_shift(4) + DOWN * 0.2 + LEFT * 3.6, band_shift(4) + DOWN * 0.7 + LEFT * 4.8)
        self.play(Create(t_tower), Create(hub))
        self.play(Create(bl1), Create(bl2), Create(bl3))
        t_lab = Tex(r"towers past 100 m;\\ huge blades").scale(0.85).shift(band_shift(4) + DOWN * 3.2 + LEFT * 3.6)
        self.play(Write(t_lab))
        self.wait(2)
        b4_l1 = Tex(r"air $\Rightarrow$ blades $\Rightarrow$ shaft $\Rightarrow$ generator").scale(1.0).shift(band_shift(4) + UP * 0.9 + RIGHT * 1.8)
        self.play(Write(b4_l1))
        self.wait(2)
        b4_l2 = MathTex(r"P \propto A \times v^3").scale(1.2).shift(band_shift(4) + DOWN * 0.1 + RIGHT * 1.8)
        self.play(Write(b4_l2))
        self.play(Create(SurroundingRectangle(b4_l2, color=GREEN)))
        self.wait(2)
        b4_l3 = Tex(r"Double the wind: eight times the power").scale(1.0).shift(band_shift(4) + DOWN * 1.1 + RIGHT * 1.8)
        self.play(Write(b4_l3))
        self.wait(2)
        b4_l4 = Tex(r"Siting is everything: coastal ridges,\\ plateaus, wind-funnel gaps").scale(0.95).shift(band_shift(4) + DOWN * 2.3 + RIGHT * 1.8)
        self.play(Write(b4_l4))
        self.wait(3)

        # --- Band 5 (subtopic_3): wind examples and the two-column check
        self.next_band(5)
        b5_title = Tex("Wind examples and the check").scale(1.2).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(1.5)
        b5_l1 = Tex(r"Eastern Cape leads: Jeffreys Bay,").scale(1.0).shift(band_shift(5) + UP * 1.2)
        b5_l2 = Tex(r"Cookhouse, Coega clusters").scale(1.0).shift(band_shift(5) + UP * 0.5)
        self.play(Write(b5_l1))
        self.play(Write(b5_l2))
        self.wait(2.5)
        b5_l3 = Tex(r"Western Cape: Caledon, Darling;").scale(1.0).shift(band_shift(5) + DOWN * 0.3)
        b5_l4 = Tex(r"turbines and sheep share the veld").scale(1.0).shift(band_shift(5) + DOWN * 1.0)
        self.play(Write(b5_l3))
        self.play(Write(b5_l4))
        self.wait(2.5)
        b5_l5 = Tex(r"World: Denmark $\approx$ half from wind;").scale(1.0).shift(band_shift(5) + DOWN * 1.8)
        b5_l6 = Tex(r"China's fleet; North Sea offshore").scale(1.0).shift(band_shift(5) + DOWN * 2.5)
        self.play(Write(b5_l5))
        self.play(Write(b5_l6))
        self.wait(2.5)
        b5_l7 = Tex(r"Clean, cheap, quick vs intermittent, noise, birds").scale(0.9).shift(band_shift(5) + DOWN * 3.2)
        self.play(Write(b5_l7))
        self.wait(3)

        # --- Band 6 (subtopic_4): economic effects, both columns
        self.next_band(6)
        b6_title = Tex("The future: economic effects").scale(1.2).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(1.5)
        b6_l1 = Tex(r"$+$ Cheapest new power restrains tariffs").scale(1.0).shift(band_shift(6) + UP * 1.2)
        b6_l2 = Tex(r"$+$ 100s of billions invested; rural jobs").scale(1.0).shift(band_shift(6) + UP * 0.4)
        b6_l3 = Tex(r"$+$ Community trusts; green industry ladder").scale(1.0).shift(band_shift(6) + DOWN * 0.4)
        self.play(Write(b6_l1))
        self.wait(2)
        self.play(Write(b6_l2))
        self.wait(2)
        self.play(Write(b6_l3))
        self.wait(2)
        b6_l4 = Tex(r"$-$ Coal employs $\approx$ 90 000 in Mpumalanga;").scale(1.0).shift(band_shift(6) + DOWN * 1.3)
        b6_l5 = Tex(r"renewables employ fewer, elsewhere").scale(1.0).shift(band_shift(6) + DOWN * 2.0)
        self.play(Write(b6_l4))
        self.play(Write(b6_l5))
        self.wait(2.5)
        b6_l6 = Tex(r"Hence the JUST TRANSITION: retraining,").scale(1.0).shift(band_shift(6) + DOWN * 2.8)
        b6_l7 = Tex(r"pensions, new industry for coal country").scale(1.0).shift(band_shift(6) + DOWN * 3.5)
        self.play(Write(b6_l6))
        self.play(Write(b6_l7))
        self.wait(3)

        # --- Band 7 (subtopic_4): environment, obstacles, conclusion
        self.next_band(7)
        b7_title = Tex("Environment and the three obstacles").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(1.5)
        b7_l1 = Tex(r"$+$ No CO$_2$, no smog, almost no water").scale(1.0).shift(band_shift(7) + UP * 1.3)
        b7_l2 = Tex(r"$-$ Land, birds and bats, panel disposal").scale(1.0).shift(band_shift(7) + UP * 0.6)
        self.play(Write(b7_l1))
        self.wait(2)
        self.play(Write(b7_l2))
        self.wait(2)
        b7_l3 = Tex(r"1. GRID: best sun/wind far from Gauteng;").scale(1.0).shift(band_shift(7) + DOWN * 0.3)
        b7_l4 = Tex(r"new lines are the binding constraint").scale(1.0).shift(band_shift(7) + DOWN * 1.0)
        self.play(Write(b7_l3))
        self.play(Write(b7_l4))
        self.wait(2)
        b7_l5 = Tex(r"2. INTERMITTENCY: managed by the mix").scale(1.0).shift(band_shift(7) + DOWN * 1.8)
        b7_l6 = Tex(r"3. POLICY CERTAINTY: auctions on schedule").scale(1.0).shift(band_shift(7) + DOWN * 2.5)
        self.play(Write(b7_l5))
        self.wait(2)
        self.play(Write(b7_l6))
        self.wait(2)
        b7_l7 = Tex(r"Resource is world-class; delivery decides speed").scale(0.95).shift(band_shift(7) + DOWN * 3.3)
        self.play(Write(b7_l7))
        self.play(Create(SurroundingRectangle(b7_l7, color=GREEN)))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): fuel that falls from the sky
        self.next_band(8)
        b8_title = Tex("Fuel that falls from the sky").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = Tex(r"A filling station with free petrol:").scale(1.05).shift(band_shift(8) + UP * 1.2)
        b8_l2 = Tex(r"pay for the pumps, the fuel just arrives").scale(1.0).shift(band_shift(8) + UP * 0.5)
        self.play(Write(b8_l1))
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = Tex(r"The catch: free fuel keeps its own hours").scale(1.0).shift(band_shift(8) + DOWN * 0.4)
        self.play(Write(b8_l3))
        self.wait(2)
        b8_l4 = Tex(r"Free but moody vs costly but steady").scale(1.1).shift(band_shift(8) + DOWN * 1.3)
        self.play(Write(b8_l4))
        self.play(Create(SurroundingRectangle(b8_l4, color=GREEN)))
        self.wait(2.5)
        b8_l5 = Tex(r"Our sky: 2 500$+$ sun hours; Germany leads").scale(0.95).shift(band_shift(8) + DOWN * 2.2)
        b8_l6 = Tex(r"solar with HALF our sunshine").scale(1.0).shift(band_shift(8) + DOWN * 2.9)
        self.play(Write(b8_l5))
        self.play(Write(b8_l6))
        self.wait(2)
        b8_l7 = Tex(r"REIPPPP: free fuel became cheap fuel too").scale(0.95).shift(band_shift(8) + DOWN * 3.6)
        self.play(Write(b8_l7))
        self.wait(3)

        # --- Band 9 (subtopic_6): sun traps and wind catchers
        self.next_band(9)
        b9_title = Tex("Sun traps and wind catchers").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex(r"PV panel: sun in, current out — no moving").scale(1.0).shift(band_shift(9) + UP * 1.2)
        b9_l2 = Tex(r"parts; rooftops, Upington, De Aar").scale(1.0).shift(band_shift(9) + UP * 0.5)
        self.play(Write(b9_l1))
        self.play(Write(b9_l2))
        self.wait(2.5)
        b9_l3 = Tex(r"CSP: magnifying-glass trick — mirrors cook").scale(1.0).shift(band_shift(9) + DOWN * 0.4)
        b9_l4 = Tex(r"salt; the thermos serves supper from lunch").scale(1.0).shift(band_shift(9) + DOWN * 1.1)
        self.play(Write(b9_l3))
        self.play(Write(b9_l4))
        self.wait(2.5)
        b9_l5 = Tex(r"Redstone: 12 hours of stored sun").scale(1.0).shift(band_shift(9) + DOWN * 1.9)
        self.play(Write(b9_l5))
        self.play(Create(SurroundingRectangle(b9_l5, color=GREEN)))
        self.wait(2)
        b9_l6 = Tex(r"Turbine: skyscraper pinwheel; double wind,").scale(0.95).shift(band_shift(9) + DOWN * 2.7)
        b9_l7 = Tex(r"EIGHT times power; Jeffreys Bay, Cookhouse").scale(0.95).shift(band_shift(9) + DOWN * 3.4)
        self.play(Write(b9_l6))
        self.play(Write(b9_l7))
        self.wait(3)

        # --- Band 10 (subtopic_7): the relay race and the baton
        self.next_band(10)
        b10_title = Tex("The relay race and the baton").scale(1.2).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_title))
        self.wait(2)
        b10_l1 = Tex(r"Coal: tired runner. Sun and wind: warmed up").scale(0.95).shift(band_shift(10) + UP * 1.3)
        self.play(Write(b10_l1))
        self.wait(2)
        b10_l2 = Tex(r"Fumble 1: the extension cord — full").scale(1.0).shift(band_shift(10) + UP * 0.5)
        b10_l3 = Tex(r"transmission lines, power far from Gauteng").scale(0.95).shift(band_shift(10) + DOWN * 0.2)
        self.play(Write(b10_l2))
        self.play(Write(b10_l3))
        self.wait(2.5)
        b10_l4 = Tex(r"Fumble 2: the night shift — salt, batteries,").scale(0.95).shift(band_shift(10) + DOWN * 1.0)
        b10_l5 = Tex(r"pumped storage; a MIX covers the clock").scale(0.95).shift(band_shift(10) + DOWN * 1.7)
        self.play(Write(b10_l4))
        self.play(Write(b10_l5))
        self.wait(2.5)
        b10_l6 = Tex(r"Fumble 3: coal towns — pass the baton justly").scale(0.95).shift(band_shift(10) + DOWN * 2.5)
        self.play(Write(b10_l6))
        self.wait(2)
        b10_l7 = Tex(r"Direction is settled; only speed is argued").scale(1.05).shift(band_shift(10) + DOWN * 3.3)
        self.play(Write(b10_l7))
        self.play(Create(SurroundingRectangle(b10_l7, color=GREEN)))
        self.wait(4)
