from manim import *

# Band-layout whiteboard scene for "The Photoelectric Effect and Atomic
# Spectra" (Part 1 — Expert subtopics 1-4, Part 2 — Simplifier subtopics 5-7).
# Exporter-safe mobjects only, write-only reveals, camera moves between bands.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


class PhotoelectricEffectSpectraSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): the effect and the threshold
        title = Tex("The Photoelectric Effect").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex("Electrons ejected from a metal by light").scale(1.05).shift(UP * 1.3)
        b0_l2 = Tex("of SUITABLE FREQUENCY").scale(1.05).shift(UP * 0.6)
        self.play(Write(b0_l1))
        self.play(Write(b0_l2))
        self.wait(2.5)
        b0_l3 = Tex(r"Threshold $f_0$: below it, NOTHING moves —").scale(1.05).shift(DOWN * 0.4)
        b0_l4 = Tex("no matter how bright, no matter how long").scale(1.05).shift(DOWN * 1.2)
        self.play(Write(b0_l3))
        self.play(Write(b0_l4))
        self.wait(2.5)
        b0_l5 = Tex("Above it: instant emission, even in dim light").scale(1.0).shift(DOWN * 2.3)
        self.play(Write(b0_l5))
        self.wait(3)

        # --- Band 1 (subtopic_1): photons and the work function
        self.next_band(1)
        b1_title = Tex("Einstein: light arrives in packets").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l1 = MathTex(r"E = hf").scale(1.3).shift(band_shift(1) + UP * 1.1)
        self.play(Write(b1_l1))
        self.play(Create(SurroundingRectangle(b1_l1, color=GREEN)))
        self.wait(2)
        b1_l2 = MathTex(r"h = 6{,}63 \times 10^{-34}\ \text{J}\cdot\text{s}").scale(1.05).shift(band_shift(1) + UP * 0.1)
        self.play(Write(b1_l2))
        self.wait(2)
        b1_l3 = Tex("One photon, one electron — all or nothing").scale(1.05).shift(band_shift(1) + DOWN * 0.8)
        self.play(Write(b1_l3))
        self.wait(2.5)
        b1_l4 = Tex(r"Work function $W_0$: the exit cost of the metal").scale(1.0).shift(band_shift(1) + DOWN * 1.7)
        self.play(Write(b1_l4))
        self.wait(2)
        b1_l5 = MathTex(r"W_0 = hf_0").scale(1.2).shift(band_shift(1) + DOWN * 2.7)
        self.play(Write(b1_l5))
        self.play(Create(SurroundingRectangle(b1_l5, color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): the photoelectric equation
        self.next_band(2)
        b2_title = Tex("The photoelectric equation").scale(1.2).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(1.5)
        b2_l1 = MathTex(r"E = W_0 + E_{k(max)}").scale(1.3).shift(band_shift(2) + UP * 1.0)
        self.play(Write(b2_l1))
        self.play(Create(SurroundingRectangle(b2_l1, color=GREEN)))
        self.wait(2.5)
        b2_l2 = MathTex(r"hf = hf_0 + \tfrac{1}{2}mv_{max}^2").scale(1.15).shift(band_shift(2) + DOWN * 0.2)
        self.play(Write(b2_l2))
        self.wait(2.5)
        b2_l3 = Tex("Photon pays the exit cost; the change").scale(1.05).shift(band_shift(2) + DOWN * 1.3)
        b2_l4 = Tex("becomes kinetic energy of the electron").scale(1.05).shift(band_shift(2) + DOWN * 2.1)
        self.play(Write(b2_l3))
        self.play(Write(b2_l4))
        self.wait(2)
        b2_l5 = Tex("MAX: surface electrons keep the most").scale(1.0).shift(band_shift(2) + DOWN * 3.0)
        self.play(Write(b2_l5))
        self.wait(3)

        # --- Band 3 (subtopic_2): full calculation on caesium
        self.next_band(3)
        b3_title = Tex(r"Caesium: $f = 6{,}0 \times 10^{14}$ Hz").scale(1.1).shift(band_shift(3) + UP * 2.4)
        b3_sub = MathTex(r"W_0 = 3{,}36 \times 10^{-19}\ \text{J}").scale(1.05).shift(band_shift(3) + UP * 1.6)
        self.play(Write(b3_title))
        self.play(Write(b3_sub))
        self.wait(2)
        b3_l1 = MathTex(r"E = hf = 6{,}63 \times 10^{-34} \times 6{,}0 \times 10^{14}").scale(1.0).shift(band_shift(3) + UP * 0.6)
        b3_l2 = MathTex(r"E = 3{,}978 \times 10^{-19}\ \text{J} > W_0").scale(1.05).shift(band_shift(3) + DOWN * 0.3)
        self.play(Write(b3_l1))
        self.wait(2.5)
        self.play(Write(b3_l2))
        self.wait(2)
        b3_l3 = Tex("Photon covers the exit cost: emission!").scale(1.0).shift(band_shift(3) + DOWN * 1.1)
        self.play(Write(b3_l3))
        self.wait(2)
        b3_l4 = MathTex(r"E_{k(max)} = (3{,}978 - 3{,}36) \times 10^{-19}").scale(1.0).shift(band_shift(3) + DOWN * 2.0)
        b3_l5 = MathTex(r"E_{k(max)} = 6{,}18 \times 10^{-20}\ \text{J}").scale(1.1).shift(band_shift(3) + DOWN * 2.9)
        self.play(Write(b3_l4))
        self.wait(2)
        self.play(Write(b3_l5))
        self.play(Create(SurroundingRectangle(b3_l5, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_2): threshold frequency and wavelength conversion
        self.next_band(4)
        b4_title = Tex("Two standard variations").scale(1.2).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(1.5)
        b4_l1 = MathTex(r"f_0 = \frac{W_0}{h} = \frac{3{,}36 \times 10^{-19}}{6{,}63 \times 10^{-34}}").scale(1.05).shift(band_shift(4) + UP * 1.0)
        b4_l2 = MathTex(r"f_0 = 5{,}07 \times 10^{14}\ \text{Hz}").scale(1.1).shift(band_shift(4) + DOWN * 0.1)
        self.play(Write(b4_l1))
        self.wait(2.5)
        self.play(Write(b4_l2))
        self.play(Create(SurroundingRectangle(b4_l2, color=GREEN)))
        self.wait(2.5)
        b4_l3 = Tex("Given wavelength? Convert first — 3 moves:").scale(1.05).shift(band_shift(4) + DOWN * 1.0)
        b4_l4a = MathTex(r"f = \frac{c}{\lambda} = \frac{3 \times 10^8}{5{,}0 \times 10^{-7}}").scale(1.0).shift(band_shift(4) + DOWN * 2.0)
        b4_l4b = MathTex(r"f = 6{,}0 \times 10^{14}\ \text{Hz}").scale(1.05).shift(band_shift(4) + DOWN * 3.0)
        self.play(Write(b4_l3))
        self.wait(2)
        self.play(Write(b4_l4a))
        self.wait(2)
        self.play(Write(b4_l4b))
        self.wait(3)

        # --- Band 5 (subtopic_3): the two dials — intensity and frequency
        self.next_band(5)
        b5_title = Tex("Intensity versus frequency").scale(1.2).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(1.5)
        b5_l1 = Tex(r"Intensity $\uparrow$: MORE photons per second").scale(1.05).shift(band_shift(5) + UP * 1.2)
        b5_l2 = Tex(r"more electrons/s, SAME $E_{k(max)}$").scale(1.05).shift(band_shift(5) + UP * 0.4)
        self.play(Write(b5_l1))
        self.wait(2)
        self.play(Write(b5_l2))
        self.wait(2.5)
        b5_l3 = Tex(r"Frequency $\uparrow$: BIGGER energy packets").scale(1.05).shift(band_shift(5) + DOWN * 0.6)
        b5_l4 = Tex(r"greater $E_{k(max)}$, NOT more electrons").scale(1.05).shift(band_shift(5) + DOWN * 1.4)
        self.play(Write(b5_l3))
        self.wait(2)
        self.play(Write(b5_l4))
        self.wait(2.5)
        b5_l5 = Tex("No electron can pool two photons").scale(1.05).shift(band_shift(5) + DOWN * 2.5)
        self.play(Write(b5_l5))
        self.play(Create(SurroundingRectangle(b5_l5, color=GREEN)))
        self.wait(3)

        # --- Band 6 (subtopic_3): the particle-nature argument
        self.next_band(6)
        b6_title = Tex("Why this proves particles").scale(1.2).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(1.5)
        b6_l1 = Tex("Waves predict: any frequency works if bright;").scale(1.0).shift(band_shift(6) + UP * 1.2)
        b6_l2 = Tex("dim light needs a waiting time").scale(1.0).shift(band_shift(6) + UP * 0.5)
        self.play(Write(b6_l1))
        self.play(Write(b6_l2))
        self.wait(2.5)
        b6_l3 = Tex("Observed: instant response, hard threshold,").scale(1.0).shift(band_shift(6) + DOWN * 0.5)
        b6_l4 = Tex(r"$E_k$ climbs with $f$ but ignores brightness").scale(1.0).shift(band_shift(6) + DOWN * 1.3)
        self.play(Write(b6_l3))
        self.wait(2)
        self.play(Write(b6_l4))
        self.wait(2.5)
        b6_l5 = Tex("Only indivisible packets explain all three").scale(1.05).shift(band_shift(6) + DOWN * 2.4)
        self.play(Write(b6_l5))
        self.play(Create(SurroundingRectangle(b6_l5, color=GREEN)))
        self.wait(3)

        # --- Band 7 (subtopic_4): atomic spectra — the ladder and the lines
        self.next_band(7)
        b7_title = Tex("Atomic spectra: rungs on a ladder").scale(1.15).shift(band_shift(7) + UP * 2.9)
        self.play(Write(b7_title))
        self.wait(1.5)
        # energy-level ladder with a downward jump emitting a photon
        lvl1 = Line(band_shift(7) + LEFT * 3.6 + DOWN * 0.5, band_shift(7) + LEFT * 1.2 + DOWN * 0.5)
        lvl2 = Line(band_shift(7) + LEFT * 3.6 + UP * 0.7, band_shift(7) + LEFT * 1.2 + UP * 0.7)
        lvl3 = Line(band_shift(7) + LEFT * 3.6 + UP * 1.6, band_shift(7) + LEFT * 1.2 + UP * 1.6)
        lab1 = MathTex(r"E_1").scale(0.9).shift(band_shift(7) + LEFT * 4.1 + DOWN * 0.5)
        lab2 = MathTex(r"E_2").scale(0.9).shift(band_shift(7) + LEFT * 4.1 + UP * 0.7)
        lab3 = MathTex(r"E_3").scale(0.9).shift(band_shift(7) + LEFT * 4.1 + UP * 1.6)
        self.play(Create(lvl1), Create(lvl2), Create(lvl3), Write(lab1), Write(lab2), Write(lab3))
        self.wait(1.5)
        jump = Arrow(band_shift(7) + LEFT * 2.4 + UP * 0.7, band_shift(7) + LEFT * 2.4 + DOWN * 0.5, buff=0, color=YELLOW)
        photon = Arrow(band_shift(7) + LEFT * 1.1 + UP * 0.1, band_shift(7) + RIGHT * 0.6 + UP * 0.1, buff=0, color=BLUE)
        ph_lab = Tex("photon out").scale(0.85).shift(band_shift(7) + RIGHT * 0.1 + UP * 0.7)
        self.play(Create(jump))
        self.play(Create(photon), Write(ph_lab))
        self.wait(2)
        b7_eq = MathTex(r"E = hf = E_2 - E_1").scale(1.15).shift(band_shift(7) + RIGHT * 2.7 + UP * 1.6)
        self.play(Write(b7_eq))
        self.play(Create(SurroundingRectangle(b7_eq, color=GREEN)))
        self.wait(2.5)
        b7_l1 = Tex("Emission: bright lines on black — one per jump").scale(1.0).shift(band_shift(7) + DOWN * 1.5)
        b7_l2 = Tex("Absorption: dark lines in the rainbow,").scale(1.0).shift(band_shift(7) + DOWN * 2.3)
        b7_l3 = Tex("same frequencies — every element's fingerprint").scale(1.0).shift(band_shift(7) + DOWN * 3.0)
        self.play(Write(b7_l1))
        self.wait(2)
        self.play(Write(b7_l2))
        self.play(Write(b7_l3))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): the bouncer at the metal's door
        self.next_band(8)
        b8_title = Tex("The bouncer at the metal's door").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = Tex(r"Exit fee $=$ work function, fixed per metal").scale(1.05).shift(band_shift(8) + UP * 1.2)
        self.play(Write(b8_l1))
        self.wait(2.5)
        b8_l2 = Tex("Photons are customers: blue rich, red poor").scale(1.05).shift(band_shift(8) + UP * 0.4)
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = Tex("No whip-rounds: one photon, one electron").scale(1.05).shift(band_shift(8) + DOWN * 0.5)
        self.play(Write(b8_l3))
        self.wait(2.5)
        b8_l4 = Tex("Cash covers the fee: walk out instantly,").scale(1.05).shift(band_shift(8) + DOWN * 1.4)
        b8_l5 = Tex("keep the change as speed").scale(1.05).shift(band_shift(8) + DOWN * 2.2)
        self.play(Write(b8_l4))
        self.play(Write(b8_l5))
        self.play(Create(SurroundingRectangle(b8_l5, color=GREEN)))
        self.wait(2.5)
        b8_l6 = Tex("A stadium of R5 notes never pays one R50 fee").scale(1.0).shift(band_shift(8) + DOWN * 3.1)
        self.play(Write(b8_l6))
        self.wait(3)

        # --- Band 9 (subtopic_6): ten soft throws never beat one hard throw
        self.next_band(9)
        b9_title = Tex("Ten soft throws never beat one hard one").scale(1.15).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex("Carnival bell: the machine RESETS each swing").scale(1.0).shift(band_shift(9) + UP * 1.2)
        self.play(Write(b9_l1))
        self.wait(2.5)
        b9_l2 = Tex(r"Swing hardness $=$ frequency (energy per photon)").scale(1.0).shift(band_shift(9) + UP * 0.4)
        b9_l3 = Tex(r"Swings per minute $=$ intensity (photons/s)").scale(1.0).shift(band_shift(9) + DOWN * 0.4)
        self.play(Write(b9_l2))
        self.wait(2)
        self.play(Write(b9_l3))
        self.wait(2.5)
        b9_l4 = Tex("Frequency dial: WHETHER and how fast").scale(1.05).shift(band_shift(9) + DOWN * 1.4)
        b9_l5 = Tex("Intensity dial: HOW MANY per second").scale(1.05).shift(band_shift(9) + DOWN * 2.2)
        self.play(Write(b9_l4))
        self.wait(2)
        self.play(Write(b9_l5))
        self.play(Create(SurroundingRectangle(VGroup(b9_l4, b9_l5), color=GREEN)))
        self.wait(3.5)

        # --- Band 10 (subtopic_7): every element signs its light
        self.next_band(10)
        b10_title = Tex("Every element signs its light").scale(1.2).shift(band_shift(10) + UP * 2.6)
        self.play(Write(b10_title))
        self.wait(2)
        # emission spectrum sketch: dark strip with sharp coloured lines
        strip = Rectangle(width=7.0, height=1.0).shift(band_shift(10) + UP * 1.5)
        sl1 = Line(band_shift(10) + LEFT * 2.6 + UP * 1.05, band_shift(10) + LEFT * 2.6 + UP * 1.95, color=RED, stroke_width=6)
        sl2 = Line(band_shift(10) + LEFT * 0.9 + UP * 1.05, band_shift(10) + LEFT * 0.9 + UP * 1.95, color=YELLOW, stroke_width=6)
        sl3 = Line(band_shift(10) + RIGHT * 0.6 + UP * 1.05, band_shift(10) + RIGHT * 0.6 + UP * 1.95, color=GREEN, stroke_width=6)
        sl4 = Line(band_shift(10) + RIGHT * 2.3 + UP * 1.05, band_shift(10) + RIGHT * 2.3 + UP * 1.95, color=BLUE, stroke_width=6)
        strip_lab = Tex("sharp lines, always the same places").scale(0.9).shift(band_shift(10) + UP * 0.6)
        self.play(Create(strip))
        self.play(Create(sl1), Create(sl2), Create(sl3), Create(sl4))
        self.play(Write(strip_lab))
        self.wait(2.5)
        b10_l1 = Tex("Fixed rungs, fixed drops, fixed colours").scale(1.05).shift(band_shift(10) + DOWN * 0.4)
        self.play(Write(b10_l1))
        self.play(Create(SurroundingRectangle(b10_l1, color=GREEN)))
        self.wait(2.5)
        b10_l2 = Tex("Cool gas steals the same colours: dark lines").scale(1.0).shift(band_shift(10) + DOWN * 1.4)
        self.play(Write(b10_l2))
        self.wait(2.5)
        b10_l3 = Tex("Helium was read in sunlight before Earth;").scale(1.0).shift(band_shift(10) + DOWN * 2.3)
        b10_l4 = Tex("slide the barcode red and the star recedes").scale(1.0).shift(band_shift(10) + DOWN * 3.0)
        self.play(Write(b10_l3))
        self.play(Write(b10_l4))
        self.wait(4)
