from manim import *

# Band-layout whiteboard scene for "What Economics Studies" (grade 10, term 1).
# One band per teaching beat; camera moves down, earlier work stays. Only
# exporter-safe mobjects (Tex/MathTex/Line/Arrow/Dot/Circle/Rectangle/
# SurroundingRectangle/VGroup); write-only reveals, no transforms.
#
# Subtopic shares (subtopics.json, total 1440 s):
# 220/220/220/210/190/190/190.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class WhatEconomicsStudiesSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic full-screen while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): the definition, needs and wants ---
        title = Tex("What Economics Studies").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        d1 = Tex(r"Social science: how people, firms and").scale(1.05).shift(UP * 1.0)
        d2 = Tex(r"the state use LIMITED resources to").scale(1.05).shift(UP * 0.2)
        d3 = Tex(r"satisfy UNLIMITED needs and wants").scale(1.05).shift(DOWN * 0.6)
        self.play(Write(d1))
        self.play(Write(d2))
        self.play(Write(d3))
        box0 = SurroundingRectangle(VGroup(d1, d2, d3), color=GREEN)
        self.play(Create(box0))
        self.wait(2.5)
        d4 = Tex(r"NEEDS: survival and dignity").scale(1.05).shift(DOWN * 1.8)
        d5 = Tex(r"WANTS: beyond necessity — unlimited").scale(1.05).shift(DOWN * 2.6)
        self.play(Write(d4))
        self.wait(2)
        self.play(Write(d5))
        self.wait(3)

        # --- Band 1 (subtopic_1): four factors, four rewards, three processes ---
        self.next_band(1)
        b1t = Tex("Factors of production and their rewards").scale(1.1).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1t))
        self.wait(1.5)
        f1 = Tex(r"Natural resources $\rightarrow$ rent").scale(1.05).shift(band_shift(1) + UP * 1.2)
        f2 = Tex(r"Labour $\rightarrow$ wages").scale(1.05).shift(band_shift(1) + UP * 0.4)
        f3 = Tex(r"Capital $\rightarrow$ interest").scale(1.05).shift(band_shift(1) + DOWN * 0.4)
        f4 = Tex(r"Entrepreneurship $\rightarrow$ profit").scale(1.05).shift(band_shift(1) + DOWN * 1.2)
        self.play(Write(f1))
        self.play(Write(f2))
        self.play(Write(f3))
        self.play(Write(f4))
        box1 = SurroundingRectangle(VGroup(f1, f2, f3, f4), color=GREEN)
        self.play(Create(box1))
        self.wait(2.5)
        p1 = Tex(r"Processes: production $\rightarrow$ exchange").scale(1.0).shift(band_shift(1) + DOWN * 2.2)
        p2 = Tex(r"$\rightarrow$ consumption (the end purpose)").scale(1.0).shift(band_shift(1) + DOWN * 2.9)
        self.play(Write(p1))
        self.play(Write(p2))
        self.wait(3)

        # --- Band 2 (subtopic_2): micro vs macro ---
        self.next_band(2)
        b2t = Tex("The great division of the subject").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2t))
        self.wait(1.5)
        b2a = Tex(r"MICRO: individual units close-up").scale(1.1).shift(band_shift(2) + UP * 1.1)
        b2b = Tex(r"one household, one firm, one market").scale(1.0).shift(band_shift(2) + UP * 0.3)
        self.play(Write(b2a))
        self.play(Write(b2b))
        self.wait(2.5)
        b2c = Tex(r"MACRO: the economy as a WHOLE").scale(1.1).shift(band_shift(2) + DOWN * 0.6)
        b2d = Tex(r"total production, inflation, jobs").scale(1.0).shift(band_shift(2) + DOWN * 1.4)
        self.play(Write(b2c))
        self.play(Write(b2d))
        self.wait(2.5)
        b2e = Tex(r"One shop's price: micro.").scale(1.05).shift(band_shift(2) + DOWN * 2.3)
        b2f = Tex(r"The general price level: macro.").scale(1.05).shift(band_shift(2) + DOWN * 3.0)
        self.play(Write(b2e))
        self.play(Write(b2f))
        self.wait(3)

        # --- Band 3 (subtopic_2): working branches, positive vs normative ---
        self.next_band(3)
        b3t = Tex("Working branches of economics").scale(1.15).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3t))
        self.wait(1.5)
        b3a = Tex(r"Theory, applied, economic history,").scale(1.05).shift(band_shift(3) + UP * 1.2)
        b3b = Tex(r"development economics — SA's own").scale(1.05).shift(band_shift(3) + UP * 0.4)
        self.play(Write(b3a))
        self.play(Write(b3b))
        self.wait(2.5)
        b3c = Tex(r"POSITIVE: what IS — testable").scale(1.05).shift(band_shift(3) + DOWN * 0.5)
        b3d = Tex(r"``unemployment is 32\%''").scale(1.0).shift(band_shift(3) + DOWN * 1.2)
        b3e = Tex(r"NORMATIVE: what OUGHT to be").scale(1.05).shift(band_shift(3) + DOWN * 2.0)
        b3f = Tex(r"``government should create jobs''").scale(1.0).shift(band_shift(3) + DOWN * 2.7)
        self.play(Write(b3c))
        self.play(Write(b3d))
        self.wait(2)
        self.play(Write(b3e))
        self.play(Write(b3f))
        self.wait(3)

        # --- Band 4 (subtopic_3): the scientific loop ---
        self.next_band(4)
        b4t = Tex("The method: the scientific loop").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4t))
        self.wait(1.5)
        s1 = Tex("1. Observation — watch the data").scale(1.05).shift(band_shift(4) + UP * 1.2)
        s2 = Tex("2. Hypothesis — propose a cause").scale(1.05).shift(band_shift(4) + UP * 0.4)
        s3 = Tex("3. Testing — against history, stats").scale(1.05).shift(band_shift(4) + DOWN * 0.4)
        s4 = Tex("4. Law — if it keeps surviving").scale(1.05).shift(band_shift(4) + DOWN * 1.2)
        self.play(Write(s1))
        self.wait(1.5)
        self.play(Write(s2))
        self.wait(1.5)
        self.play(Write(s3))
        self.wait(1.5)
        self.play(Write(s4))
        self.wait(2)
        cp = Tex(r"Guard clause: CETERIS PARIBUS —").scale(1.05).shift(band_shift(4) + DOWN * 2.2)
        cp2 = Tex(r"``all other things being equal''").scale(1.05).shift(band_shift(4) + DOWN * 2.9)
        self.play(Write(cp))
        self.play(Write(cp2))
        self.play(Create(SurroundingRectangle(VGroup(cp, cp2), color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_3): tools and honest limits ---
        self.next_band(5)
        b5t = Tex("Tools — and honest limits").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5t))
        self.wait(1.5)
        b5a = Tex(r"DATA: Stats SA, the Reserve Bank").scale(1.05).shift(band_shift(5) + UP * 1.1)
        b5b = Tex(r"INDICES: many numbers in one (CPI)").scale(1.05).shift(band_shift(5) + UP * 0.3)
        b5c = Tex(r"MODELS: useful simplifications; GRAPHS").scale(1.0).shift(band_shift(5) + DOWN * 0.5)
        self.play(Write(b5a))
        self.wait(1.5)
        self.play(Write(b5b))
        self.wait(1.5)
        self.play(Write(b5c))
        self.wait(2)
        b5w = Tex(r"``Economic laws are certainties''").scale(1.05).shift(band_shift(5) + DOWN * 1.5)
        self.play(Write(b5w))
        self.play(Create(strike(b5w)))
        self.wait(2)
        b5d = Tex(r"People react — laws are TENDENCIES").scale(1.05).shift(band_shift(5) + DOWN * 2.5)
        self.play(Write(b5d))
        self.play(Create(SurroundingRectangle(b5d, color=GREEN)))
        self.wait(3)

        # --- Band 6 (subtopic_4): economics among the sciences ---
        self.next_band(6)
        b6t = Tex("Economics among the sciences").scale(1.15).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6t))
        self.wait(1.5)
        b6a = Tex(r"A SOCIAL science: human behaviour,").scale(1.05).shift(band_shift(6) + UP * 1.1)
        b6b = Tex(r"but the most quantitative member").scale(1.05).shift(band_shift(6) + UP * 0.3)
        self.play(Write(b6a))
        self.play(Write(b6b))
        self.wait(2.5)
        b6c = Tex(r"Natural science: controlled labs,").scale(1.0).shift(band_shift(6) + DOWN * 0.6)
        b6d = Tex(r"exceptionless laws — water boils").scale(1.0).shift(band_shift(6) + DOWN * 1.3)
        self.play(Write(b6c))
        self.play(Write(b6d))
        self.wait(2)
        b6e = Tex(r"Economics: scientific METHOD on").scale(1.05).shift(band_shift(6) + DOWN * 2.2)
        b6f = Tex(r"subject matter with free will").scale(1.05).shift(band_shift(6) + DOWN * 2.9)
        self.play(Write(b6e))
        self.play(Write(b6f))
        self.play(Create(SurroundingRectangle(VGroup(b6e, b6f), color=GREEN)))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 7 (subtopic_5): the science of not enough ---
        self.next_band(7)
        b7t = Tex("The science of not enough").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7t))
        self.wait(2)
        b7a = Tex(r"Saturday, R50: airtime, chips, cap...").scale(1.05).shift(band_shift(7) + UP * 1.1)
        b7b = Tex(r"the queue of wants never ends").scale(1.05).shift(band_shift(7) + UP * 0.3)
        self.play(Write(b7a))
        self.play(Write(b7b))
        self.wait(2.5)
        b7c = Tex(r"Make $\rightarrow$ swap $\rightarrow$ use").scale(1.15).shift(band_shift(7) + DOWN * 0.7)
        b7d = Tex(r"production, exchange, consumption").scale(1.0).shift(band_shift(7) + DOWN * 1.5)
        self.play(Write(b7c))
        self.play(Write(b7d))
        self.play(Create(SurroundingRectangle(b7c, color=GREEN)))
        self.wait(2.5)
        b7e = Tex(r"Gogo's vetkoek: flour, hands, stove,").scale(1.0).shift(band_shift(7) + DOWN * 2.3)
        b7f = Tex(r"and the risk — rent, wage, interest, profit").scale(0.95).shift(band_shift(7) + DOWN * 3.0)
        self.play(Write(b7e))
        self.play(Write(b7f))
        self.wait(3)

        # --- Band 8 (subtopic_6): close-up lens, drone shot ---
        self.next_band(8)
        b8t = Tex("Close-up lens, drone shot").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8t))
        self.wait(2)
        b8a = Tex(r"Close-up: one shop, one price — micro").scale(1.05).shift(band_shift(8) + UP * 1.1)
        b8b = Tex(r"Drone: the whole country — macro").scale(1.05).shift(band_shift(8) + UP * 0.3)
        self.play(Write(b8a))
        self.wait(2)
        self.play(Write(b8b))
        self.wait(2)
        b8c = Tex(r"Test: can you point at it on your street?").scale(1.0).shift(band_shift(8) + DOWN * 0.6)
        self.play(Write(b8c))
        self.play(Create(SurroundingRectangle(b8c, color=GREEN)))
        self.wait(2)
        b8w = Tex(r"``Petrol is too expensive'' — a fact").scale(1.05).shift(band_shift(8) + DOWN * 1.6)
        self.play(Write(b8w))
        self.play(Create(strike(b8w)))
        self.wait(2)
        b8d = Tex(r"That's a WISH (normative); ``up 90c''").scale(1.0).shift(band_shift(8) + DOWN * 2.5)
        b8e = Tex(r"is a MEASUREMENT (positive)").scale(1.0).shift(band_shift(8) + DOWN * 3.1)
        self.play(Write(b8d))
        self.play(Write(b8e))
        self.wait(3)

        # --- Band 9 (subtopic_7): testing like a scientist ---
        self.next_band(9)
        b9t = Tex("Testing like a scientist").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9t))
        self.wait(2)
        b9a = Tex(r"Rainy morning, quiet rank: observe").scale(1.05).shift(band_shift(9) + UP * 1.1)
        b9b = Tex(r"guess $\rightarrow$ test $\rightarrow$ keep what survives").scale(1.05).shift(band_shift(9) + UP * 0.3)
        self.play(Write(b9a))
        self.play(Write(b9b))
        self.wait(2.5)
        b9c = Tex(r"Ceteris paribus: ``if nothing else").scale(1.05).shift(band_shift(9) + DOWN * 0.6)
        b9d = Tex(r"changes'' — one thread at a time").scale(1.05).shift(band_shift(9) + DOWN * 1.3)
        self.play(Write(b9c))
        self.play(Write(b9d))
        self.play(Create(SurroundingRectangle(VGroup(b9c, b9d), color=GREEN)))
        self.wait(2.5)
        b9e = Tex(r"Water never talks back — people do:").scale(1.0).shift(band_shift(9) + DOWN * 2.2)
        b9f = Tex(r"strong tendencies, humble forecasts").scale(1.0).shift(band_shift(9) + DOWN * 2.9)
        self.play(Write(b9e))
        self.play(Write(b9f))
        self.wait(4)
