from manim import *

# Band-layout whiteboard scene for the session duo "Globalisation and the
# North-South Divide" (Grade 11, Term 4). One band per teaching step; the
# camera moves down and nothing is removed. Exporter-safe mobjects only; the
# scorecard columns and the coffee value chain are hand-built from
# Rectangles, Arrows and Tex. Band time apportioned to subtopics.json
# (240/250/250/240/205/205/210 of 1600 s).

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class GlobalisationNorthSouthSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md audio plays.
        self.wait(15)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): definition + technology causes ---
        title = Tex("Globalisation and the North/South Divide").scale(1.15).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        g1 = Tex("Economies increasingly interconnected and interdependent").scale(0.9).shift(UP * 1.2)
        self.play(Write(g1))
        self.wait(2)
        g2 = Tex("Test: decisions on one continent move prices,").scale(0.9).shift(UP * 0.3)
        g2b = Tex("jobs and incomes on another — fast").scale(0.9).shift(DOWN * 0.5)
        self.play(Write(g2))
        self.play(Write(g2b))
        self.wait(2.5)
        g3 = Tex("Technology made it POSSIBLE: containers,").scale(0.9).shift(DOWN * 1.5)
        g3b = Tex("undersea cables, computing — the global value chain").scale(0.9).shift(DOWN * 2.3)
        self.play(Write(g3))
        self.play(Write(g3b))
        self.wait(3)

        # --- Band 1 (subtopic_1): policy causes ---
        self.next_band(1)
        b1_title = Tex("Policy made it PERMITTED").scale(1.15).shift(band_shift(1) + UP * 2.3)
        self.play(Write(b1_title))
        self.wait(1.5)
        p1 = Tex(r"Tariffs negotiated down $\to$ WTO in 1995").scale(0.95).shift(band_shift(1) + UP * 1.3)
        p2 = Tex("Exchange controls relaxed: finance at keystroke speed").scale(0.9).shift(band_shift(1) + UP * 0.4)
        self.play(Write(p1))
        self.wait(2)
        self.play(Write(p2))
        self.wait(2)
        p3 = Tex("China 1978, Soviet bloc 1989, South Africa 1994:").scale(0.9).shift(band_shift(1) + DOWN * 0.5)
        p3b = Tex("billions of workers and consumers joined").scale(0.9).shift(band_shift(1) + DOWN * 1.3)
        self.play(Write(p3))
        self.play(Write(p3b))
        self.wait(2.5)
        p4 = Tex("Containers, cables, computers: possible;").scale(0.9).shift(band_shift(1) + DOWN * 2.2)
        p4b = Tex("trade deals, free finance, reopened economies: allowed").scale(0.85).shift(band_shift(1) + DOWN * 3.0)
        self.play(Write(p4))
        self.play(Write(p4b))
        self.play(Create(SurroundingRectangle(VGroup(p4, p4b), color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): the gains column ---
        self.next_band(2)
        b2_title = Tex("The scorecard: gains column").scale(1.15).shift(band_shift(2) + UP * 2.3)
        self.play(Write(b2_title))
        self.wait(1.5)
        w1 = Tex("Specialisation: lower prices, wider choice on our shelves").scale(0.85).shift(band_shift(2) + UP * 1.4)
        w2 = Tex("FDI: world-scale motor industry, 100 000$+$ jobs").scale(0.9).shift(band_shift(2) + UP * 0.55)
        w3 = Tex("Technology spreads: vaccines, solar, mobile banking").scale(0.9).shift(band_shift(2) + DOWN * 0.3)
        w4 = Tex("Hundreds of millions exported their way out of poverty").scale(0.85).shift(band_shift(2) + DOWN * 1.15)
        for m in (w1, w2, w3, w4):
            self.play(Write(m))
            self.wait(2)
        self.play(Create(SurroundingRectangle(VGroup(w1, w4), color=GREEN, buff=0.25)))
        self.wait(3)

        # --- Band 3 (subtopic_2): the losses column + verdict ---
        self.next_band(3)
        b3_title = Tex("The losses column — and the verdict").scale(1.1).shift(band_shift(3) + UP * 2.3)
        self.play(Write(b3_title))
        self.wait(1.5)
        l1 = Tex("Cheap imports gutted textile towns: Newcastle's jobs").scale(0.85).shift(band_shift(3) + UP * 1.4)
        l2 = Tex("Contagion: 2008 US housing crash cost SA jobs in a year").scale(0.85).shift(band_shift(3) + UP * 0.55)
        l3 = Tex("Mobile capital shifts profits; workers lose bargaining").scale(0.85).shift(band_shift(3) + DOWN * 0.3)
        l4 = Tex("power — the race to the bottom; inequality widens").scale(0.85).shift(band_shift(3) + DOWN * 1.15)
        for m in (l1, l2, l3, l4):
            self.play(Write(m))
            self.wait(2)
        l5 = Tex("Verdict: raises total income, redistributes opportunity —").scale(0.8).shift(band_shift(3) + DOWN * 2.1)
        l5b = Tex("capture the gains, protect and re-skill the losers").scale(0.85).shift(band_shift(3) + DOWN * 2.9)
        self.play(Write(l5))
        self.play(Write(l5b))
        self.play(Create(SurroundingRectangle(l5b, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): the divide and its three mechanisms ---
        self.next_band(4)
        b4_title = Tex("The North/South divide: three mechanisms").scale(1.05).shift(band_shift(4) + UP * 2.3)
        self.play(Write(b4_title))
        self.wait(1.5)
        m1 = Tex("Economic shorthand, not geography — Australia is").scale(0.85).shift(band_shift(4) + UP * 1.4)
        m1b = Tex("southern on the map, Northern in the wallet").scale(0.85).shift(band_shift(4) + UP * 0.6)
        self.play(Write(m1))
        self.play(Write(m1b))
        self.wait(2.5)
        m2 = Tex("1. Terms of trade: selling raw, buying made — a treadmill").scale(0.85).shift(band_shift(4) + DOWN * 0.3)
        self.play(Write(m2))
        self.wait(2)
        m3 = Tex("2. Debt in foreign currency: repayments balloon,").scale(0.85).shift(band_shift(4) + DOWN * 1.15)
        m3b = Tex("schools and clinics squeezed to service bankers").scale(0.85).shift(band_shift(4) + DOWN * 1.95)
        self.play(Write(m3))
        self.play(Write(m3b))
        self.wait(2.5)
        m4 = Tex("3. Voice: IMF, World Bank, WTO rules tilted North").scale(0.85).shift(band_shift(4) + DOWN * 2.8)
        self.play(Write(m4))
        self.wait(3)

        # --- Band 5 (subtopic_3): the divide is moving ---
        self.next_band(5)
        b5_title = Tex("The divide is real — and moving").scale(1.15).shift(band_shift(5) + UP * 2.3)
        self.play(Write(b5_title))
        self.wait(1.5)
        v1 = Tex("Tariffs higher on processed goods than raw materials:").scale(0.85).shift(band_shift(5) + UP * 1.4)
        v1b = Tex("quietly discouraging Southern industrialisation").scale(0.85).shift(band_shift(5) + UP * 0.6)
        self.play(Write(v1))
        self.play(Write(v1b))
        self.wait(2.5)
        v2 = Tex("China, India, Brazil shifted the centre of gravity south").scale(0.85).shift(band_shift(5) + DOWN * 0.3)
        self.play(Write(v2))
        self.wait(2)
        v3 = Tex("BRICS (SA a member) presses for a louder Southern voice").scale(0.85).shift(band_shift(5) + DOWN * 1.15)
        self.play(Write(v3))
        self.wait(2)
        v4 = Tex("AfCFTA: grow the South's own internal market").scale(0.9).shift(band_shift(5) + DOWN * 2.0)
        self.play(Write(v4))
        self.play(Create(SurroundingRectangle(v4, color=GREEN)))
        self.wait(3)

        # --- Band 6 (subtopic_4): South Africa inside the global economy ---
        self.next_band(6)
        b6_title = Tex("South Africa inside the global economy").scale(1.1).shift(band_shift(6) + UP * 2.3)
        self.play(Write(b6_title))
        self.wait(1.5)
        s1 = Tex(r"Openness: exports $+$ imports well over half of GDP").scale(0.9).shift(band_shift(6) + UP * 1.4)
        self.play(Write(s1))
        self.wait(2)
        s2 = Tex("Petrol tracks world oil; maize tracks world grain;").scale(0.85).shift(band_shift(6) + UP * 0.55)
        s2b = Tex("when China sneezes, the platinum belt catches cold").scale(0.85).shift(band_shift(6) + DOWN * 0.25)
        self.play(Write(s2))
        self.play(Write(s2b))
        self.wait(2.5)
        s3 = Tex("Links: AfCFTA, preferential US/EU access, BRICS, WTO").scale(0.85).shift(band_shift(6) + DOWN * 1.1)
        self.play(Write(s3))
        self.wait(2.5)
        s4 = Tex("The divide in one country: Sandton finance up north,").scale(0.85).shift(band_shift(6) + DOWN * 2.0)
        s4b = Tex("raw-export dependence down south — in one trade account").scale(0.8).shift(band_shift(6) + DOWN * 2.8)
        self.play(Write(s4))
        self.play(Write(s4b))
        self.wait(3)

        # --- Band 7 (subtopic_4): the two-handed policy debate ---
        self.next_band(7)
        b7_title = Tex("The two-handed policy debate").scale(1.15).shift(band_shift(7) + UP * 2.3)
        self.play(Write(b7_title))
        self.wait(1.5)
        d1 = Tex("One hand: deeper integration — chase exports,").scale(0.9).shift(band_shift(7) + UP * 1.4)
        d1b = Tex("court investment, industrialise through AfCFTA").scale(0.9).shift(band_shift(7) + UP * 0.6)
        self.play(Write(d1))
        self.play(Write(d1b))
        self.wait(2.5)
        d2 = Tex("Other hand: strategic protection — tariffs and").scale(0.9).shift(band_shift(7) + DOWN * 0.3)
        d2b = Tex("local content for clothing and poultry, while rebuilding").scale(0.85).shift(band_shift(7) + DOWN * 1.1)
        self.play(Write(d2))
        self.play(Write(d2b))
        self.wait(2.5)
        d3 = Tex("Openness grows the pie but redistributes the slices:").scale(0.85).shift(band_shift(7) + DOWN * 2.0)
        d3b = Tex("pair integration with skills, infrastructure, safety nets").scale(0.85).shift(band_shift(7) + DOWN * 2.8)
        self.play(Write(d3))
        self.play(Write(d3b))
        self.play(Create(SurroundingRectangle(d3b, color=GREEN)))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): the world in your pocket ---
        self.next_band(8)
        b8_title = Tex("The world in your pocket").scale(1.2).shift(band_shift(8) + UP * 2.3)
        self.play(Write(b8_title))
        self.wait(2)
        k1 = Tex("Design America; chip Taiwan; screen Korea; cobalt DRC;").scale(0.8).shift(band_shift(8) + UP * 1.4)
        k1b = Tex("assembly China; updates via the Mtunzini cable").scale(0.85).shift(band_shift(8) + UP * 0.6)
        self.play(Write(k1))
        self.play(Write(k1b))
        self.wait(2.5)
        k2 = Tex("One phone, six countries minimum — carried daily").scale(0.9).shift(band_shift(8) + DOWN * 0.3)
        self.play(Write(k2))
        self.wait(2)
        k3 = Tex("Door one: containers made moving cheap; cables").scale(0.85).shift(band_shift(8) + DOWN * 1.2)
        k3b = Tex("made information instant — slice production like a loaf").scale(0.85).shift(band_shift(8) + DOWN * 2.0)
        self.play(Write(k3))
        self.play(Write(k3b))
        self.wait(2.5)
        k4 = Tex("Door two: tariffs down, WTO referee, China back in").scale(0.85).shift(band_shift(8) + DOWN * 2.9)
        self.play(Write(k4))
        self.wait(3)

        # --- Band 9 (subtopic_6): one shop now — winners and losers ---
        self.next_band(9)
        b9_title = Tex("One shop now: who won, who lost").scale(1.1).shift(band_shift(9) + UP * 2.3)
        self.play(Write(b9_title))
        self.wait(2)
        n1 = Tex("Gain: East London and Rosslyn build for the world —").scale(0.85).shift(band_shift(9) + UP * 1.4)
        n1b = Tex("100 000$+$ families eat from the motor industry").scale(0.85).shift(band_shift(9) + UP * 0.6)
        self.play(Write(n1))
        self.play(Write(n1b))
        self.wait(2.5)
        n2 = Tex("Loss: Newcastle's sewing machines went quiet —").scale(0.85).shift(band_shift(9) + DOWN * 0.3)
        n2b = Tex("cheaper shirts for the world, paid for by those streets").scale(0.85).shift(band_shift(9) + DOWN * 1.1)
        self.play(Write(n2))
        self.play(Write(n2b))
        self.wait(2.5)
        n3 = Tex("2008: one shop, one flu — connected means exposed").scale(0.85).shift(band_shift(9) + DOWN * 2.0)
        self.play(Write(n3))
        self.wait(2)
        n4 = Tex(r"``Is globalisation good or bad?''").scale(0.9).shift(band_shift(9) + DOWN * 2.9)
        self.play(Write(n4))
        self.play(Create(strike(n4)))
        self.wait(2)
        n5 = Tex("It grows the total and moves the shares").scale(0.9).shift(band_shift(9) + RIGHT * 3.3 + DOWN * 2.2)
        self.play(Write(n5))
        self.play(Create(SurroundingRectangle(n5, color=GREEN)))
        self.wait(3)

        # --- Band 10 (subtopic_7): top of the map, bottom of the map ---
        self.next_band(10)
        b10_title = Tex("Top of the map, bottom of the map").scale(1.1).shift(band_shift(10) + UP * 2.4)
        self.play(Write(b10_title))
        self.wait(2)
        south = Rectangle(width=4.4, height=1.1).shift(band_shift(10) + LEFT * 3.8 + UP * 1.2)
        south_lab = Tex("South: beans, cents").scale(0.75).move_to(south.get_center())
        north = Rectangle(width=4.4, height=1.1).shift(band_shift(10) + RIGHT * 3.8 + UP * 1.2)
        north_lab = Tex("North: roast, brand, R50").scale(0.75).move_to(north.get_center())
        arr = Arrow(south.get_right(), north.get_left(), buff=0.1)
        arr_lab = Tex("raw beans").scale(0.7).shift(band_shift(10) + UP * 1.75)
        self.play(Create(south), Write(south_lab))
        self.play(Create(arr), Write(arr_lab))
        self.play(Create(north), Write(north_lab))
        self.wait(2.5)
        c1 = Tex("The finishing is where the money lives").scale(0.95).shift(band_shift(10) + UP * 0.2)
        self.play(Write(c1))
        self.play(Create(SurroundingRectangle(c1, color=GREEN)))
        self.wait(2)
        c2 = Tex("Weights: dollar debt swells; rulebooks written up north").scale(0.85).shift(band_shift(10) + DOWN * 0.7)
        self.play(Write(c2))
        self.wait(2)
        c3 = Tex("The map moves: China and India pull the centre south;").scale(0.85).shift(band_shift(10) + DOWN * 1.6)
        c3b = Tex("BRICS demands voice; AfCFTA keeps the finishing here").scale(0.85).shift(band_shift(10) + DOWN * 2.4)
        self.play(Write(c3))
        self.play(Write(c3b))
        self.wait(2)
        c4 = Tex("Our future: learn to finish what we dig and grow").scale(0.9).shift(band_shift(10) + DOWN * 3.05)
        self.play(Write(c4))
        self.wait(4)
