from manim import *

# Band-layout whiteboard scene for the session duo "Scarcity, Choice and
# Opportunity Cost" (grade 10, term 1). One band per teaching beat; the camera
# moves down to fresh space and earlier work stays on the canvas. Only
# exporter-safe mobjects are used (Tex/MathTex/Line/Arrow/Dot/Circle/
# Rectangle/SurroundingRectangle/VGroup); reveals are write-only.
#
# Subtopic time shares (subtopics.json, total 1440 s):
# 210/220/220/220/190/190/190 -> bands are apportioned accordingly.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class ScarcityChoiceOpportunityCostSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): scarcity, the permanent condition ---
        title = Tex("Scarcity, Choice and Opportunity Cost").scale(1.25).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        d1 = Tex(r"SCARCITY: resources insufficient").scale(1.15).shift(UP * 1.0)
        d2 = Tex(r"to satisfy all wants").scale(1.15).shift(UP * 0.3)
        self.play(Write(d1))
        self.play(Write(d2))
        self.wait(2.5)
        d3 = Tex(r"Universal — rich and poor alike").scale(1.1).shift(DOWN * 0.7)
        d4 = Tex(r"Permanent — no growth abolishes it").scale(1.1).shift(DOWN * 1.5)
        self.play(Write(d3))
        self.wait(2)
        self.play(Write(d4))
        self.wait(2)
        d5 = Tex(r"Even money cannot buy unlimited time").scale(1.05).shift(DOWN * 2.5)
        self.play(Write(d5))
        self.wait(3)

        # --- Band 1 (subtopic_1): scarcity vs shortage; choice forced ---
        self.next_band(1)
        b1t = Tex("Scarcity is NOT a shortage").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1t))
        self.wait(1.5)
        b1w = Tex(r"``Scarcity = a shortage''").scale(1.1).shift(band_shift(1) + UP * 1.2)
        self.play(Write(b1w))
        self.play(Create(strike(b1w)))
        self.wait(2)
        b1a = Tex(r"Shortage: at the going price,").scale(1.05).shift(band_shift(1) + UP * 0.3)
        b1b = Tex(r"demand $>$ supply — temporary, fixable").scale(1.05).shift(band_shift(1) + DOWN * 0.5)
        self.play(Write(b1a))
        self.play(Write(b1b))
        self.wait(2.5)
        b1c = Tex(r"Scarcity forces CHOICE: rank wants").scale(1.1).shift(band_shift(1) + DOWN * 1.5)
        b1d = Tex(r"household, firm and state all rank").scale(1.05).shift(band_shift(1) + DOWN * 2.3)
        self.play(Write(b1c))
        self.wait(2)
        self.play(Write(b1d))
        box1 = SurroundingRectangle(VGroup(b1a, b1b), color=GREEN)
        self.play(Create(box1))
        self.wait(3)

        # --- Band 2 (subtopic_2): opportunity cost defined ---
        self.next_band(2)
        b2t = Tex("Opportunity Cost — the True Price").scale(1.2).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2t))
        self.wait(1.5)
        b2a = Tex(r"Value of the NEXT BEST alternative").scale(1.1).shift(band_shift(2) + UP * 1.1)
        b2b = Tex(r"sacrificed when a choice is made").scale(1.1).shift(band_shift(2) + UP * 0.3)
        self.play(Write(b2a))
        self.play(Write(b2b))
        self.wait(2.5)
        b2c = Tex(r"R120: calculator chosen").scale(1.1).shift(band_shift(2) + DOWN * 0.7)
        b2d = Tex(r"next best = data bundle").scale(1.1).shift(band_shift(2) + DOWN * 1.5)
        b2e = Tex(r"opportunity cost = ONE data bundle").scale(1.1).shift(band_shift(2) + DOWN * 2.4)
        self.play(Write(b2c))
        self.wait(2)
        self.play(Write(b2d))
        self.wait(2)
        self.play(Write(b2e))
        self.play(Create(SurroundingRectangle(b2e, color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_2): three levels + exam disciplines ---
        self.next_band(3)
        b3t = Tex("The concept at every level").scale(1.2).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3t))
        self.wait(1.5)
        b3a = Tex(r"Household: R150 shift vs studying").scale(1.05).shift(band_shift(3) + UP * 1.2)
        b3b = Tex(r"Business: R6 000 machine vs stock profit").scale(1.05).shift(band_shift(3) + UP * 0.4)
        b3c = Tex(r"State: stadium vs clinics and schools").scale(1.05).shift(band_shift(3) + DOWN * 0.4)
        self.play(Write(b3a))
        self.wait(2)
        self.play(Write(b3b))
        self.wait(2)
        self.play(Write(b3c))
        self.wait(2.5)
        b3w = Tex(r"``Opportunity cost $=$ R120''").scale(1.05).shift(band_shift(3) + DOWN * 1.4)
        self.play(Write(b3w))
        self.play(Create(strike(b3w)))
        self.wait(2)
        b3d = Tex(r"Express it in REAL terms, next best only").scale(1.05).shift(band_shift(3) + DOWN * 2.4)
        self.play(Write(b3d))
        self.play(Create(SurroundingRectangle(b3d, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): the three questions ---
        self.next_band(4)
        b4t = Tex("Three questions every economy answers").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4t))
        self.wait(1.5)
        b4a = Tex(r"1. WHAT to produce? — the basket").scale(1.1).shift(band_shift(4) + UP * 1.1)
        b4b = Tex(r"maize or flowers, taxis or tractors").scale(1.0).shift(band_shift(4) + UP * 0.3)
        self.play(Write(b4a))
        self.play(Write(b4b))
        self.wait(2.5)
        b4c = Tex(r"2. HOW? — labour- or capital-intensive").scale(1.1).shift(band_shift(4) + DOWN * 0.6)
        self.play(Write(b4c))
        self.wait(2.5)
        b4d = Tex(r"3. FOR WHOM? — who gets the output").scale(1.1).shift(band_shift(4) + DOWN * 1.5)
        b4e = Tex(r"the distribution question").scale(1.0).shift(band_shift(4) + DOWN * 2.3)
        self.play(Write(b4d))
        self.play(Write(b4e))
        self.wait(3)

        # --- Band 5 (subtopic_3): economic systems ---
        self.next_band(5)
        b5t = Tex("Who answers? Economic systems").scale(1.2).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5t))
        self.wait(1.5)
        b5a = Tex(r"MARKET: prices answer all three").scale(1.1).shift(band_shift(5) + UP * 1.1)
        b5b = Tex(r"PLANNED: the state sets targets").scale(1.1).shift(band_shift(5) + UP * 0.2)
        b5c = Tex(r"MIXED: markets + state corrections").scale(1.1).shift(band_shift(5) + DOWN * 0.7)
        self.play(Write(b5a))
        self.wait(2)
        self.play(Write(b5b))
        self.wait(2)
        self.play(Write(b5c))
        self.wait(2)
        b5d = Tex(r"South Africa is firmly MIXED").scale(1.1).shift(band_shift(5) + DOWN * 1.7)
        self.play(Write(b5d))
        self.play(Create(SurroundingRectangle(b5d, color=GREEN)))
        b5e = Tex(r"pure forms are textbook poles").scale(1.0).shift(band_shift(5) + DOWN * 2.7)
        self.play(Write(b5e))
        self.wait(3)

        # --- Band 6 (subtopic_4): promotion of rights ---
        self.next_band(6)
        b6t = Tex("Economic activity PROMOTES rights").scale(1.15).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6t))
        self.wait(1.5)
        b6a = Tex(r"Employment funds food, shelter,").scale(1.05).shift(band_shift(6) + UP * 1.1)
        b6b = Tex(r"education, healthcare — dignity").scale(1.05).shift(band_shift(6) + UP * 0.3)
        self.play(Write(b6a))
        self.play(Write(b6b))
        self.wait(2.5)
        b6c = Tex(r"Taxes fund schools, hospitals, grants").scale(1.05).shift(band_shift(6) + DOWN * 0.7)
        self.play(Write(b6c))
        self.wait(2)
        b6d = Tex(r"Growth widens what society affords").scale(1.05).shift(band_shift(6) + DOWN * 1.6)
        self.play(Write(b6d))
        self.wait(3)

        # --- Band 7 (subtopic_4): violation, externalities, sustainability ---
        self.next_band(7)
        b7t = Tex("...and can VIOLATE them").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7t))
        self.wait(1.5)
        b7a = Tex(r"Child labour, unsafe work, low wages").scale(1.05).shift(band_shift(7) + UP * 1.2)
        self.play(Write(b7a))
        self.wait(2)
        b7b = Tex(r"EXTERNALITY: a cost paid by third").scale(1.05).shift(band_shift(7) + UP * 0.3)
        b7c = Tex(r"parties that no price collected").scale(1.05).shift(band_shift(7) + DOWN * 0.5)
        self.play(Write(b7b))
        self.play(Write(b7c))
        self.wait(2.5)
        box7 = SurroundingRectangle(VGroup(b7b, b7c), color=GREEN)
        self.play(Create(box7))
        self.wait(1.5)
        b7d = Tex(r"SUSTAINABILITY: meet today's needs").scale(1.05).shift(band_shift(7) + DOWN * 1.5)
        b7e = Tex(r"without robbing tomorrow's").scale(1.05).shift(band_shift(7) + DOWN * 2.3)
        self.play(Write(b7d))
        self.play(Write(b7e))
        self.wait(2)
        b7f = Tex(r"Exam: argue BOTH sides, then remedies").scale(1.0).shift(band_shift(7) + DOWN * 3.0)
        self.play(Write(b7f))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): not a shortage, a forever thing ---
        self.next_band(8)
        b8t = Tex("Not a shortage — a forever thing").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8t))
        self.wait(2)
        b8a = Tex(r"Bread gone at the spaza by ten:").scale(1.05).shift(band_shift(8) + UP * 1.1)
        b8b = Tex(r"shortage — the van fixes it").scale(1.05).shift(band_shift(8) + UP * 0.3)
        self.play(Write(b8a))
        self.play(Write(b8b))
        self.wait(2.5)
        b8c = Tex(r"Wanting more than there is:").scale(1.05).shift(band_shift(8) + DOWN * 0.6)
        b8d = Tex(r"scarcity — nothing fixes it").scale(1.05).shift(band_shift(8) + DOWN * 1.4)
        self.play(Write(b8c))
        self.play(Write(b8d))
        self.wait(2.5)
        b8e = Tex(r"So life is RANKING: what comes FIRST?").scale(1.05).shift(band_shift(8) + DOWN * 2.4)
        self.play(Write(b8e))
        self.play(Create(SurroundingRectangle(b8e, color=GREEN)))
        self.wait(3)

        # --- Band 9 (subtopic_6): the price tag behind the price tag ---
        self.next_band(9)
        b9t = Tex("The price tag behind the price tag").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9t))
        self.wait(2)
        b9a = Tex(r"Printed tag: R120 for the calculator").scale(1.05).shift(band_shift(9) + UP * 1.1)
        b9b = Tex(r"Hidden tag: the data bundle forgone").scale(1.05).shift(band_shift(9) + UP * 0.3)
        self.play(Write(b9a))
        self.wait(2)
        self.play(Write(b9b))
        self.wait(2.5)
        b9w = Tex(r"``True cost $=$ the R120''").scale(1.05).shift(band_shift(9) + DOWN * 0.7)
        self.play(Write(b9w))
        self.play(Create(strike(b9w)))
        self.wait(2)
        b9c = Tex(r"Name the runner-up, in real things").scale(1.05).shift(band_shift(9) + DOWN * 1.7)
        self.play(Write(b9c))
        self.play(Create(SurroundingRectangle(b9c, color=GREEN)))
        self.wait(2)
        b9d = Tex(r"Even free things cost the afternoon").scale(1.0).shift(band_shift(9) + DOWN * 2.7)
        self.play(Write(b9d))
        self.wait(3)

        # --- Band 10 (subtopic_7): people and the planet in the ledger ---
        self.next_band(10)
        b10t = Tex("People and the planet in the ledger").scale(1.15).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10t))
        self.wait(2)
        # Two-column bookkeeper's ledger, hand-built from lines.
        rail = Line(band_shift(10) + UP * 1.4, band_shift(10) + DOWN * 1.4, stroke_width=4)
        bar = Line(band_shift(10) + UP * 1.4 + LEFT * 3.4,
                   band_shift(10) + UP * 1.4 + RIGHT * 3.4, stroke_width=4)
        self.play(Create(bar), Create(rail))
        h1 = Tex("Promotes").scale(1.05).shift(band_shift(10) + UP * 1.8 + LEFT * 1.9)
        h2 = Tex("Violates").scale(1.05).shift(band_shift(10) + UP * 1.8 + RIGHT * 1.9)
        self.play(Write(h1), Write(h2))
        self.wait(1.5)
        l1 = Tex("jobs, wages").scale(0.95).shift(band_shift(10) + UP * 0.8 + LEFT * 1.9)
        l2 = Tex("school fees, clinic").scale(0.95).shift(band_shift(10) + UP * 0.1 + LEFT * 1.9)
        l3 = Tex("taxes for services").scale(0.95).shift(band_shift(10) + DOWN * 0.6 + LEFT * 1.9)
        r1 = Tex("smoke the street breathes").scale(0.85).shift(band_shift(10) + UP * 0.8 + RIGHT * 1.9)
        r2 = Tex("waste in the river").scale(0.95).shift(band_shift(10) + UP * 0.1 + RIGHT * 1.9)
        r3 = Tex("unsafe, underpaid work").scale(0.9).shift(band_shift(10) + DOWN * 0.6 + RIGHT * 1.9)
        self.play(Write(l1))
        self.play(Write(l2))
        self.play(Write(l3))
        self.wait(2)
        self.play(Write(r1))
        self.play(Write(r2))
        self.play(Write(r3))
        self.wait(2.5)
        b10c = Tex(r"Weigh both columns, then name fixes:").scale(1.0).shift(band_shift(10) + DOWN * 2.1)
        b10d = Tex(r"rules, polluter pays, rights upheld").scale(1.0).shift(band_shift(10) + DOWN * 2.8)
        self.play(Write(b10c))
        self.play(Write(b10d))
        self.play(Create(SurroundingRectangle(b10d, color=GREEN)))
        self.wait(4)
