from manim import *

# Band-layout whiteboard scene for the Analysing Graphs and Making Decisions
# session duo. One band per teaching beat, camera-only transitions, add-only
# lifecycle. Exporter-supported mobjects only: axes are Arrows, the
# electricity line is a chain of Lines, bars are Rectangles, points are Dots.
# Band time apportioned to subtopics.json (210/230/230/260/180/185/185 of
# 1480 s).

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class AnalysingGraphsDecisionsSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): the electricity line graph, read ---
        title = Tex("Analysing Graphs, Making Decisions").scale(1.2).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        origin = DOWN * 2.6 + LEFT * 5.4
        x_ax = Arrow(origin, origin + RIGHT * 9.6, buff=0, stroke_width=4)
        y_ax = Arrow(origin, origin + UP * 4.6, buff=0, stroke_width=4)
        self.play(Create(x_ax), Create(y_ax))
        y_lab = Tex("units").scale(0.8).shift(origin + UP * 4.3 + RIGHT * 1.0)
        x_lab = Tex("month").scale(0.8).shift(origin + RIGHT * 8.9 + DOWN * 0.4)
        self.play(Write(y_lab), Write(x_lab))
        self.wait(1.5)
        # Feb 300 -> Jun 500 -> Jul 560 -> Oct 380 (heights scaled /150)
        p_feb = origin + RIGHT * 1.2 + UP * 2.0
        p_jun = origin + RIGHT * 4.4 + UP * 3.33
        p_jul = origin + RIGHT * 5.4 + UP * 3.73
        p_oct = origin + RIGHT * 8.0 + UP * 2.53
        seg1 = Line(p_feb, p_jun, color=YELLOW, stroke_width=5)
        seg2 = Line(p_jun, p_jul, color=YELLOW, stroke_width=5)
        seg3 = Line(p_jul, p_oct, color=YELLOW, stroke_width=5)
        d_feb = Dot(p_feb, color=RED)
        d_jul = Dot(p_jul, color=RED)
        self.play(Create(seg1), run_time=1.2)
        self.play(Create(seg2), Create(seg3), run_time=1.2)
        self.play(Create(d_feb), Create(d_jul))
        feb_lab = Tex("Feb: 300").scale(0.85).shift(p_feb + DOWN * 0.6 + RIGHT * 0.4)
        jul_lab = Tex("Jul: 560").scale(0.85).shift(p_jul + UP * 0.5)
        self.play(Write(feb_lab), Write(jul_lab))
        self.wait(2)
        read_rule = Tex("Month up to the point, across to the scale").scale(0.95).shift(UP * 1.6 + RIGHT * 0.2)
        self.play(Write(read_rule))
        self.wait(3)

        # --- Band 1 (subtopic_1): max, min, range, disciplines ---
        self.next_band(1)
        b1_t = Tex("Maximum, minimum, range").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_t))
        self.wait(1.5)
        b1_l1 = Tex("Maximum: July's 560 \\quad Minimum: Feb's 300").scale(1.0).shift(band_shift(1) + UP * 1.1)
        b1_l2 = MathTex(r"\text{Range} = 560 - 300 = 260 \text{ units}").scale(1.1).shift(band_shift(1) + UP * 0.1)
        self.play(Write(b1_l1))
        self.wait(2.5)
        self.play(Write(b1_l2))
        self.play(Create(SurroundingRectangle(b1_l2, color=GREEN)))
        self.wait(2.5)
        b1_l3 = Tex("A big range signals seasonal behaviour").scale(1.0).shift(band_shift(1) + DOWN * 0.9)
        self.play(Write(b1_l3))
        self.wait(2)
        b1_l4 = Tex("Read the axis SCALE first; quote units always").scale(1.0).shift(band_shift(1) + DOWN * 1.9)
        self.play(Write(b1_l4))
        self.wait(3)

        # --- Band 2 (subtopic_2): trends and percentage change ---
        self.next_band(2)
        b2_t = Tex("Trends and percentage change").scale(1.2).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(1.5)
        b2_l1 = Tex("Trend = direction + numbers: rises 300 to 560,").scale(0.95).shift(band_shift(2) + UP * 1.2)
        b2_l2 = Tex("peaks in July, then declines").scale(0.95).shift(band_shift(2) + UP * 0.5)
        self.play(Write(b2_l1))
        self.play(Write(b2_l2))
        self.wait(2.5)
        b2_wrong = MathTex(r"60 \div 560 \approx 10{,}7\% \text{ (new value!)}").scale(1.0).shift(band_shift(2) + DOWN * 0.5)
        self.play(Write(b2_wrong))
        self.play(Create(strike(b2_wrong)))
        self.wait(2)
        b2_l3 = MathTex(r"\frac{\text{change}}{\text{original}} \times 100 = \frac{60}{500} \times 100 = 12\%").scale(0.88).shift(band_shift(2) + DOWN * 1.7)
        self.play(Write(b2_l3))
        self.play(Create(SurroundingRectangle(b2_l3, color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_2): the water bars ---
        self.next_band(3)
        b3_t = Tex("Water: before and after the plumber").scale(1.15).shift(band_shift(3) + UP * 2.4)
        self.play(Write(b3_t))
        self.wait(1.5)
        base = band_shift(3) + DOWN * 2.4
        bar1 = Rectangle(width=1.6, height=3.4, color=BLUE).shift(base + LEFT * 3.6 + UP * 1.7)
        bar2 = Rectangle(width=1.6, height=2.3, color=TEAL).shift(base + LEFT * 1.2 + UP * 1.15)
        floor = Line(base + LEFT * 5.0, base + RIGHT * 0.4)
        self.play(Create(floor))
        self.play(Create(bar1))
        lab1 = Tex("28 kl").scale(0.9).shift(base + LEFT * 3.6 + UP * 3.8)
        self.play(Write(lab1))
        self.play(Create(bar2))
        lab2 = Tex("19 kl").scale(0.9).shift(base + LEFT * 1.2 + UP * 2.7)
        self.play(Write(lab2))
        self.wait(2)
        b3_l1 = MathTex(r"\text{Saving: } 28 - 19 = 9 \text{ kl}").scale(1.0).shift(band_shift(3) + RIGHT * 3.4 + UP * 0.6)
        b3_l2 = MathTex(r"\frac{9}{28} \times 100 \approx 32{,}1\%").scale(1.0).shift(band_shift(3) + RIGHT * 3.4 + DOWN * 0.6)
        self.play(Write(b3_l1))
        self.wait(2.5)
        self.play(Write(b3_l2))
        self.play(Create(SurroundingRectangle(b3_l2, color=GREEN)))
        self.wait(2)
        b3_l3 = Tex("One toilet, a third of the water").scale(0.95).shift(band_shift(3) + RIGHT * 3.4 + DOWN * 1.7)
        self.play(Write(b3_l3))
        self.wait(3)

        # --- Band 4 (subtopic_3): electricity into rand ---
        self.next_band(4)
        b4_t = Tex("From graph to rand: R2,50 per unit").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(1.5)
        b4_l1 = MathTex(r"\text{July: } 560 \times 2{,}50 = 1\;120 + 280 = \text{R}1\;400").scale(1.0).shift(band_shift(4) + UP * 1.1)
        b4_l2 = MathTex(r"\text{February: } 300 \times 2{,}50 = \text{R}750").scale(1.0).shift(band_shift(4) + UP * 0.2)
        self.play(Write(b4_l1))
        self.wait(2.5)
        self.play(Write(b4_l2))
        self.wait(2.5)
        b4_l3 = MathTex(r"\text{Seasonal swing: } 1\;400 - 750 = \text{R}650").scale(1.05).shift(band_shift(4) + DOWN * 0.8)
        self.play(Write(b4_l3))
        self.play(Create(SurroundingRectangle(b4_l3, color=GREEN)))
        self.wait(2)
        b4_l4 = Tex("The line graph is now a budgeting document").scale(0.95).shift(band_shift(4) + DOWN * 1.8)
        self.play(Write(b4_l4))
        self.wait(3)

        # --- Band 5 (subtopic_3): pricing the repair ---
        self.next_band(5)
        b5_t = Tex("Was the R650 plumber worth it?").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_t))
        self.wait(1.5)
        b5_l1 = MathTex(r"9 \text{ kl} \times \text{R}32 = \text{R}288 \text{ per month}").scale(1.05).shift(band_shift(5) + UP * 1.1)
        b5_l2 = MathTex(r"\text{Year: } 288 \times 12 = \text{R}3\;456").scale(1.05).shift(band_shift(5) + UP * 0.2)
        self.play(Write(b5_l1))
        self.wait(2.5)
        self.play(Write(b5_l2))
        self.wait(2.5)
        b5_l3 = MathTex(r"\text{2 months: } 576 < 650; \quad \text{3 months: } 864 > 650").scale(0.94).shift(band_shift(5) + DOWN * 0.8)
        self.play(Write(b5_l3))
        self.wait(2.5)
        b5_ans = Tex("The repair pays for itself in month three").scale(1.05).shift(band_shift(5) + DOWN * 1.8)
        self.play(Write(b5_ans))
        self.play(Create(SurroundingRectangle(b5_ans, color=GREEN)))
        self.wait(3)

        # --- Band 6 (subtopic_3): the pie chart, share times whole ---
        self.next_band(6)
        b6_t = Tex("The pie: R2 400 split four ways").scale(1.15).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_t))
        self.wait(1.5)
        b6_l1 = MathTex(r"\text{Electricity } 50\%: \; 0{,}50 \times 2\;400 = \text{R}1\;200").scale(1.0).shift(band_shift(6) + UP * 1.1)
        b6_l2 = MathTex(r"\text{Water } 25\%: \text{R}600 \quad \text{Refuse } 15\%: \text{R}360").scale(0.86).shift(band_shift(6) + UP * 0.2)
        b6_l3 = MathTex(r"\text{Sewerage } 10\%: \text{R}240").scale(1.0).shift(band_shift(6) + DOWN * 0.7)
        self.play(Write(b6_l1))
        self.wait(2.5)
        self.play(Write(b6_l2))
        self.wait(2.5)
        self.play(Write(b6_l3))
        self.wait(2)
        b6_l4 = MathTex(r"\text{Audit: } 1\;200 + 600 + 360 + 240 = 2\;400 \; \checkmark").scale(0.91).shift(band_shift(6) + DOWN * 1.7)
        self.play(Write(b6_l4))
        self.play(Create(SurroundingRectangle(b6_l4, color=GREEN)))
        self.wait(3)

        # --- Band 7 (subtopic_4): conclusions and predictions ---
        self.next_band(7)
        b7_t = Tex("Conclude only what the numbers show").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(1.5)
        b7_l1 = Tex("Supported: winter uses most — 560 vs 300").scale(1.0).shift(band_shift(7) + UP * 1.1)
        self.play(Write(b7_l1))
        self.wait(2)
        b7_wrong = Tex("Unsupported: the household WASTES power").scale(1.0).shift(band_shift(7) + UP * 0.2)
        self.play(Write(b7_wrong))
        self.play(Create(strike(b7_wrong)))
        self.wait(2.5)
        b7_l2 = Tex("Prediction = number + condition:").scale(1.0).shift(band_shift(7) + DOWN * 0.8)
        b7_l3 = Tex("likely near 560 again, IF habits stay the same").scale(1.0).shift(band_shift(7) + DOWN * 1.6)
        self.play(Write(b7_l2))
        self.play(Write(b7_l3))
        self.play(Create(SurroundingRectangle(b7_l3, color=GREEN)))
        self.wait(3)

        # --- Band 8 (subtopic_4): the axis that lies ---
        self.next_band(8)
        b8_t = Tex("The axis that lies").scale(1.2).shift(band_shift(8) + UP * 2.5)
        self.play(Write(b8_t))
        self.wait(1.5)
        base8 = band_shift(8) + DOWN * 2.3 + LEFT * 3.4
        axis_line = Line(base8 + LEFT * 1.4, base8 + RIGHT * 3.6)
        self.play(Create(axis_line))
        start_lab = Tex("axis starts at 250!").scale(0.85).shift(base8 + LEFT * 0.4 + DOWN * 0.6)
        self.play(Write(start_lab))
        barF = Rectangle(width=1.2, height=0.5, color=BLUE).shift(base8 + RIGHT * 0.6 + UP * 0.25)
        barJ = Rectangle(width=1.2, height=3.1, color=RED).shift(base8 + RIGHT * 2.6 + UP * 1.55)
        self.play(Create(barF))
        labF = Tex("Feb").scale(0.8).shift(base8 + RIGHT * 0.6 + UP * 1.0)
        self.play(Write(labF))
        self.play(Create(barJ))
        labJ = Tex("Jul").scale(0.8).shift(base8 + RIGHT * 2.6 + UP * 3.5)
        self.play(Write(labJ))
        self.wait(2)
        b8_l1 = Tex("Stump of 50 vs tower of 310:").scale(0.95).shift(band_shift(8) + RIGHT * 3.3 + UP * 0.8)
        b8_l2 = Tex("LOOKS six-fold; truth: 560 vs 300").scale(0.95).shift(band_shift(8) + RIGHT * 3.3 + DOWN * 0.0)
        b8_l3 = Tex("— less than double").scale(0.95).shift(band_shift(8) + RIGHT * 3.3 + DOWN * 0.8)
        self.play(Write(b8_l1))
        self.wait(2)
        self.play(Write(b8_l2))
        self.play(Write(b8_l3))
        self.wait(2)
        b8_rule = Tex("Trust no axis that does not start at 0").scale(1.0).shift(band_shift(8) + RIGHT * 2.9 + DOWN * 1.9)
        self.play(Write(b8_rule))
        self.play(Create(SurroundingRectangle(b8_rule, color=GREEN)))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 9 (subtopic_5): the graph is a story about your house ---
        self.next_band(9)
        b9_t = Tex("The graph is your house talking").scale(1.15).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(2)
        b9_l1 = Tex("The winter spike is the family's cold-months diary").scale(0.95).shift(band_shift(9) + UP * 1.1)
        self.play(Write(b9_l1))
        self.wait(2.5)
        b9_l2 = Tex("Finger exercise: month, up to the dot, left: 560").scale(0.95).shift(band_shift(9) + UP * 0.2)
        b9_l3 = MathTex(r"\text{The swing: } 560 - 300 = 260 \text{ units}").scale(1.0).shift(band_shift(9) + DOWN * 0.7)
        self.play(Write(b9_l2))
        self.wait(2.5)
        self.play(Write(b9_l3))
        self.wait(2.5)
        b9_l4 = Tex("The shorter water bar is the plumber's signature").scale(0.95).shift(band_shift(9) + DOWN * 1.7)
        b9_l5 = Tex("Name the story first, then the details fit").scale(0.95).shift(band_shift(9) + DOWN * 2.7)
        self.play(Write(b9_l4))
        self.wait(2)
        self.play(Write(b9_l5))
        self.play(Create(SurroundingRectangle(b9_l5, color=GREEN)))
        self.wait(3)

        # --- Band 10 (subtopic_6): numbers first, opinions second ---
        self.next_band(10)
        b10_t = Tex("Numbers first, opinions second").scale(1.2).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_t))
        self.wait(2)
        b10_l1 = MathTex(r"\text{Winter costs } 1\;400 - 750 = \text{R}650 \text{ more}").scale(1.0).shift(band_shift(10) + UP * 1.1)
        self.play(Write(b10_l1))
        self.wait(2.5)
        b10_l2 = Tex("Plumber: R288/month vs R650 once — a bargain").scale(0.95).shift(band_shift(10) + UP * 0.2)
        self.play(Write(b10_l2))
        self.wait(2.5)
        b10_l3 = Tex("Aim at big slices: 10\\% off electricity = R120;").scale(0.95).shift(band_shift(10) + DOWN * 0.7)
        b10_l4 = Tex("10\\% off refuse = only R36").scale(0.95).shift(band_shift(10) + DOWN * 1.4)
        self.play(Write(b10_l3))
        self.play(Write(b10_l4))
        self.wait(2.5)
        b10_ans = Tex("Read, multiply once, THEN judge").scale(1.05).shift(band_shift(10) + DOWN * 2.4)
        self.play(Write(b10_ans))
        self.play(Create(SurroundingRectangle(b10_ans, color=GREEN)))
        self.wait(3)

        # --- Band 11 (subtopic_7): when a picture exaggerates ---
        self.next_band(11)
        b11_t = Tex("When a picture exaggerates").scale(1.2).shift(band_shift(11) + UP * 2.2)
        self.play(Write(b11_t))
        self.wait(2)
        b11_l1 = Tex("The lie is the missing bottom of the picture —").scale(0.95).shift(band_shift(11) + UP * 1.1)
        b11_l2 = Tex("a passport photo cropped to the frown").scale(0.95).shift(band_shift(11) + UP * 0.4)
        self.play(Write(b11_l1))
        self.play(Write(b11_l2))
        self.wait(2.5)
        b11_l3 = Tex("Five-second defence: where does the axis start?").scale(0.95).shift(band_shift(11) + DOWN * 0.6)
        self.play(Write(b11_l3))
        self.wait(2.5)
        b11_l4 = Tex("Exam sentences: axis starts at 250, so only the").scale(0.9).shift(band_shift(11) + DOWN * 1.5)
        b11_l5 = Tex("differences show; truly 560 vs 300 — under double").scale(0.9).shift(band_shift(11) + DOWN * 2.2)
        self.play(Write(b11_l4))
        self.play(Write(b11_l5))
        self.play(Create(SurroundingRectangle(b11_l5, color=GREEN)))
        self.wait(4)
