from manim import *

# Band layout: one frame-height band per teaching beat; the camera moves down
# to fresh space and earlier work stays on the canvas. Only exporter-supported
# mobjects (Tex/MathTex/Line/Arrow/Dot/Circle/Rectangle); every line of working
# is a single-string MathTex revealed with Write — no sub-part transforms.
#
# Mirrors script.md across all seven subtopics of the duo (Part 1 — Expert:
# subtopics 1-4; Part 2 — Simplifier: subtopics 5-7), with band time roughly
# proportional to subtopics.json (160/170/170/190/160/170/150 of 1170 s).

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class Solving2DTrigProblemsSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic display holds while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): elevation and depression, from the horizontal
        title = Tex("2D Problems with Right-Angled Triangles").scale(1.2).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex(r"Elevation: horizontal first, then tilt UP").scale(1.1).shift(UP * 1.0)
        self.play(Write(b0_l1))
        self.wait(2.5)
        b0_l2 = Tex(r"Depression: horizontal first, then tilt DOWN").scale(1.1).shift(UP * 0.1)
        self.play(Write(b0_l2))
        self.wait(2.5)
        b0_wrong = Tex(r"Measured from the vertical cliff wall").scale(1.05).shift(DOWN * 1.0)
        self.play(Write(b0_wrong))
        self.play(Create(strike(b0_wrong)))
        self.wait(2)
        b0_rule = Tex(r"Depression hangs BELOW the horizontal").scale(1.1).shift(DOWN * 2.0)
        self.play(Write(b0_rule))
        self.wait(3)

        # --- Band 1 (subtopic_1): the alternate-angle bridge
        self.next_band(1)
        b1_title = Tex("The alternate-angle bridge").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        top_h = Line(LEFT * 0.6, RIGHT * 2.8).shift(band_shift(1) + UP * 1.1)
        ground = Line(LEFT * 3.0, RIGHT * 2.8).shift(band_shift(1) + DOWN * 0.9)
        sight = Line(RIGHT * 2.8 + UP * 1.1, LEFT * 3.0 + DOWN * 0.9).shift(band_shift(1))
        self.play(Create(top_h))
        self.play(Create(ground))
        self.wait(1)
        self.play(Create(sight))
        self.wait(1.5)
        lbl_top = Tex(r"depression").scale(0.9).shift(band_shift(1) + UP * 0.7 + RIGHT * 1.1)
        lbl_bot = Tex(r"elevation").scale(0.9).shift(band_shift(1) + DOWN * 0.5 + LEFT * 1.4)
        self.play(Write(lbl_top))
        self.play(Write(lbl_bot))
        self.wait(2)
        b1_l1 = Tex(r"Depression from top $=$ elevation from below").scale(1.05).shift(band_shift(1) + DOWN * 1.8)
        self.play(Write(b1_l1))
        self.wait(2)
        b1_l2 = Tex(r"Reason: alternate angles, parallel lines").scale(1.05).shift(band_shift(1) + DOWN * 2.7)
        self.play(Write(b1_l2))
        self.wait(3)

        # --- Band 2 (subtopic_2): flagpole sketch and labels
        self.next_band(2)
        b2_title = Tex(r"Flagpole: 40 m away, elevation $32^\circ$").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(2)
        pole = Line(RIGHT * 2.2 + DOWN * 1.6, RIGHT * 2.2 + UP * 1.0).shift(band_shift(2))
        base = Line(LEFT * 2.8 + DOWN * 1.6, RIGHT * 2.2 + DOWN * 1.6).shift(band_shift(2))
        sightline = Line(LEFT * 2.8 + DOWN * 1.6, RIGHT * 2.2 + UP * 1.0).shift(band_shift(2))
        corner = Square(side_length=0.3).shift(band_shift(2) + RIGHT * 2.05 + DOWN * 1.45)
        self.play(Create(pole))
        self.play(Create(base))
        self.play(Create(sightline))
        self.play(Create(corner))
        self.wait(1.5)
        lbl_h = MathTex(r"h").scale(1.1).shift(band_shift(2) + RIGHT * 2.6 + DOWN * 0.3)
        lbl_40 = Tex(r"40 m").scale(1.0).shift(band_shift(2) + DOWN * 2.1 + LEFT * 0.3)
        lbl_32 = MathTex(r"32^\circ").scale(1.0).shift(band_shift(2) + LEFT * 1.6 + DOWN * 1.25)
        self.play(Write(lbl_h))
        self.play(Write(lbl_40))
        self.play(Write(lbl_32))
        self.wait(2)
        b2_l1 = Tex(r"Have adjacent, want opposite: tangent").scale(1.05).shift(band_shift(2) + DOWN * 2.9)
        self.play(Write(b2_l1))
        self.wait(3)

        # --- Band 3 (subtopic_2): solve for the height
        self.next_band(3)
        b3_l1 = MathTex(r"\tan 32^\circ = \frac{h}{40}").scale(1.2).shift(band_shift(3) + UP * 1.8)
        self.play(Write(b3_l1))
        self.wait(2)
        b3_l2 = MathTex(r"h = 40 \times \tan 32^\circ").scale(1.15).shift(band_shift(3) + UP * 0.7)
        self.play(Write(b3_l2))
        self.wait(2)
        b3_l3 = MathTex(r"h = 40 \times 0{,}6249 = 24{,}99...").scale(1.15).shift(band_shift(3) + DOWN * 0.3)
        self.play(Write(b3_l3))
        self.wait(2)
        b3_l4 = MathTex(r"h = 25{,}0 \text{ m}").scale(1.2).shift(band_shift(3) + DOWN * 1.3)
        self.play(Write(b3_l4))
        self.play(Create(SurroundingRectangle(b3_l4, color=GREEN)))
        self.wait(2)
        b3_rule = Tex("Sketch — label from the angle — choose the ratio").scale(1.0).shift(band_shift(3) + DOWN * 2.5)
        self.play(Write(b3_rule))
        self.wait(3)

        # --- Band 4 (subtopic_3): finding an angle — the ladder
        self.next_band(4)
        b4_title = Tex(r"Ladder 5 m, foot 2 m out: find $\theta$").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(2)
        b4_l1 = Tex(r"Hypotenuse 5, adjacent 2: cosine").scale(1.1).shift(band_shift(4) + UP * 1.1)
        self.play(Write(b4_l1))
        self.wait(2)
        b4_l2 = MathTex(r"\cos\theta = \frac{2}{5} = 0{,}4").scale(1.15).shift(band_shift(4) + UP * 0.1)
        self.play(Write(b4_l2))
        self.wait(2)
        b4_l3 = MathTex(r"\theta = \cos^{-1}(0{,}4) = 66{,}42^\circ").scale(1.15).shift(band_shift(4) + DOWN * 1.0)
        self.play(Write(b4_l3))
        self.wait(2)
        b4_l4 = MathTex(r"\theta = 66{,}4^\circ").scale(1.15).shift(band_shift(4) + DOWN * 2.0)
        self.play(Write(b4_l4))
        self.play(Create(SurroundingRectangle(b4_l4, color=GREEN)))
        b4_rule = Tex("The inverse function climbs ratio $\\to$ angle").scale(1.0).shift(band_shift(4) + DOWN * 2.9)
        self.play(Write(b4_rule))
        self.wait(3)

        # --- Band 5 (subtopic_3): finding a distance — cliff and boat
        self.next_band(5)
        b5_title = Tex(r"Cliff 30 m, depression $25^\circ$: how far?").scale(1.1).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(2)
        b5_l1 = Tex(r"Elevation at the boat $= 25^\circ$ (alt.\ angles)").scale(1.05).shift(band_shift(5) + UP * 1.1)
        self.play(Write(b5_l1))
        self.wait(2)
        b5_l2 = MathTex(r"\tan 25^\circ = \frac{30}{d}").scale(1.15).shift(band_shift(5) + UP * 0.1)
        self.play(Write(b5_l2))
        self.wait(2)
        b5_l3 = MathTex(r"d = \frac{30}{\tan 25^\circ} = \frac{30}{0{,}4663}").scale(1.1).shift(band_shift(5) + DOWN * 1.1)
        self.play(Write(b5_l3))
        self.wait(2)
        b5_l4 = MathTex(r"d = 64{,}3 \text{ m}").scale(1.15).shift(band_shift(5) + DOWN * 2.1)
        self.play(Write(b5_l4))
        self.play(Create(SurroundingRectangle(b5_l4, color=GREEN)))
        b5_rule = Tex("Unknown at the bottom: divide, not multiply").scale(1.0).shift(band_shift(5) + DOWN * 2.9)
        self.play(Write(b5_rule))
        self.wait(3)

        # --- Band 6 (subtopic_4): two triangles, one height — setup
        self.next_band(6)
        b6_title = Tex(r"Tower: $38^\circ$ at A, walk 20 m, $50^\circ$ at B").scale(1.05).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(2)
        tower = Line(RIGHT * 2.4 + DOWN * 1.4, RIGHT * 2.4 + UP * 1.0).shift(band_shift(6))
        grnd = Line(LEFT * 3.2 + DOWN * 1.4, RIGHT * 2.4 + DOWN * 1.4).shift(band_shift(6))
        sa = Line(LEFT * 3.2 + DOWN * 1.4, RIGHT * 2.4 + UP * 1.0).shift(band_shift(6))
        sb = Line(LEFT * 1.0 + DOWN * 1.4, RIGHT * 2.4 + UP * 1.0).shift(band_shift(6))
        self.play(Create(tower))
        self.play(Create(grnd))
        self.play(Create(sa))
        self.play(Create(sb))
        self.wait(1)
        dot_a = Dot(LEFT * 3.2 + DOWN * 1.4).shift(band_shift(6))
        dot_b = Dot(LEFT * 1.0 + DOWN * 1.4).shift(band_shift(6))
        lbl_a = MathTex(r"A\; 38^\circ").scale(0.9).shift(band_shift(6) + LEFT * 3.0 + DOWN * 1.9)
        lbl_b = MathTex(r"B\; 50^\circ").scale(0.9).shift(band_shift(6) + LEFT * 0.8 + DOWN * 1.9)
        lbl_hh = MathTex(r"h").scale(1.0).shift(band_shift(6) + RIGHT * 2.8 + DOWN * 0.2)
        lbl_d = MathTex(r"d").scale(0.9).shift(band_shift(6) + RIGHT * 0.7 + DOWN * 1.1)
        self.play(FadeIn(dot_a), FadeIn(dot_b))
        self.play(Write(lbl_a), Write(lbl_b))
        self.play(Write(lbl_hh), Write(lbl_d))
        self.wait(2)
        b6_l1 = Tex(r"Both triangles SHARE the same height $h$").scale(1.05).shift(band_shift(6) + DOWN * 2.9)
        self.play(Write(b6_l1))
        self.wait(3)

        # --- Band 7 (subtopic_4): equate the two heights and solve
        self.next_band(7)
        b7_l1 = MathTex(r"h = d\tan 50^\circ \quad h = (d+20)\tan 38^\circ").scale(1.0).shift(band_shift(7) + UP * 2.1)
        self.play(Write(b7_l1))
        self.wait(2.5)
        b7_l2 = MathTex(r"d\tan 50^\circ = (d+20)\tan 38^\circ").scale(1.05).shift(band_shift(7) + UP * 1.1)
        self.play(Write(b7_l2))
        self.wait(2)
        b7_l3 = MathTex(r"d(\tan 50^\circ - \tan 38^\circ) = 20\tan 38^\circ").scale(1.0).shift(band_shift(7) + UP * 0.1)
        self.play(Write(b7_l3))
        self.wait(2)
        b7_l4 = MathTex(r"d = \frac{15{,}626}{0{,}4105} = 38{,}07 \text{ m}").scale(1.05).shift(band_shift(7) + DOWN * 1.0)
        self.play(Write(b7_l4))
        self.wait(2.5)
        b7_l5 = MathTex(r"h = 38{,}07 \times 1{,}1918 = 45{,}4 \text{ m}").scale(1.05).shift(band_shift(7) + DOWN * 2.0)
        self.play(Write(b7_l5))
        self.play(Create(SurroundingRectangle(b7_l5, color=GREEN)))
        self.wait(2)
        b7_l6 = Tex(r"Check via A: $58{,}07 \times 0{,}7813 = 45{,}4$").scale(0.95).shift(band_shift(7) + DOWN * 2.9)
        self.play(Write(b7_l6))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): everything starts level
        self.next_band(8)
        b8_title = Tex("Looking up, looking down — start level").scale(1.15).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = Tex(r"Elevation: how far UP from level").scale(1.1).shift(band_shift(8) + UP * 1.1)
        self.play(Write(b8_l1))
        self.wait(2.5)
        b8_l2 = Tex(r"Depression: how far DOWN from level").scale(1.1).shift(band_shift(8) + UP * 0.2)
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_wrong = Tex(r"Down from the wall of the building").scale(1.05).shift(band_shift(8) + DOWN * 0.8)
        self.play(Write(b8_wrong))
        self.play(Create(strike(b8_wrong)))
        self.wait(2)
        b8_l3 = Tex(r"You look down at the driver at the same").scale(1.0).shift(band_shift(8) + DOWN * 1.8)
        b8_l4 = Tex(r"angle the driver looks up at you").scale(1.0).shift(band_shift(8) + DOWN * 2.6)
        self.play(Write(b8_l3))
        self.play(Write(b8_l4))
        self.wait(3.5)

        # --- Band 9 (subtopic_6): the flagpole, one triangle at a time
        self.next_band(9)
        b9_title = Tex(r"The flagpole again: 40 m, $32^\circ$").scale(1.15).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex(r"Across from the angle: OPPOSITE (pole)").scale(1.05).shift(band_shift(9) + UP * 1.1)
        self.play(Write(b9_l1))
        self.wait(2)
        b9_l2 = Tex(r"Touching along the ground: ADJACENT, 40").scale(1.05).shift(band_shift(9) + UP * 0.2)
        self.play(Write(b9_l2))
        self.wait(2)
        b9_l3 = Tex(r"SOH CAH TOA: opp and adj live in TOA").scale(1.05).shift(band_shift(9) + DOWN * 0.7)
        self.play(Write(b9_l3))
        self.wait(2)
        b9_l4 = MathTex(r"h = 40\tan 32^\circ \approx 25 \text{ m}").scale(1.1).shift(band_shift(9) + DOWN * 1.7)
        self.play(Write(b9_l4))
        self.play(Create(SurroundingRectangle(b9_l4, color=GREEN)))
        b9_rule = Tex("About five storeys — the size sounds right").scale(1.0).shift(band_shift(9) + DOWN * 2.8)
        self.play(Write(b9_rule))
        self.wait(3)

        # --- Band 10 (subtopic_6): the kite — sine for balance
        self.next_band(10)
        b10_title = Tex(r"Kite: string 50 m, elevation $40^\circ$").scale(1.15).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_title))
        self.wait(2)
        b10_l1 = Tex(r"String = hypotenuse; want the opposite").scale(1.05).shift(band_shift(10) + UP * 1.1)
        self.play(Write(b10_l1))
        self.wait(2)
        b10_l2 = Tex(r"Opp and hyp live in SOH: sine").scale(1.05).shift(band_shift(10) + UP * 0.2)
        self.play(Write(b10_l2))
        self.wait(2)
        b10_l3 = MathTex(r"h = 50\sin 40^\circ = 50 \times 0{,}6428").scale(1.1).shift(band_shift(10) + DOWN * 0.8)
        self.play(Write(b10_l3))
        self.wait(2)
        b10_l4 = MathTex(r"h \approx 32{,}1 \text{ m}").scale(1.15).shift(band_shift(10) + DOWN * 1.8)
        self.play(Write(b10_l4))
        self.play(Create(SurroundingRectangle(b10_l4, color=GREEN)))
        self.wait(3)

        # --- Band 11 (subtopic_7): reading the story into a sketch
        self.next_band(11)
        b11_title = Tex("Reading the story into a sketch").scale(1.2).shift(band_shift(11) + UP * 2.2)
        self.play(Write(b11_title))
        self.wait(2)
        b11_l1 = Tex(r"1. Vertical meets horizontal: the $90^\circ$").scale(1.05).shift(band_shift(11) + UP * 1.1)
        self.play(Write(b11_l1))
        self.wait(2.5)
        b11_l2 = Tex(r"2. The angle sits with the OBSERVER").scale(1.05).shift(band_shift(11) + UP * 0.2)
        self.play(Write(b11_l2))
        self.wait(2.5)
        b11_l3 = Tex(r"3. Words to sides, then have-and-want").scale(1.05).shift(band_shift(11) + DOWN * 0.7)
        self.play(Write(b11_l3))
        self.wait(2.5)
        b11_l4 = Tex(r"4. Read the picture back: does it fit?").scale(1.05).shift(band_shift(11) + DOWN * 1.6)
        self.play(Write(b11_l4))
        self.wait(2)
        b11_ans = Tex(r"No flag flies higher than Table Mountain").scale(1.05).shift(band_shift(11) + DOWN * 2.6)
        self.play(Write(b11_ans))
        self.play(Create(SurroundingRectangle(b11_ans, color=GREEN)))
        self.wait(4)
