from manim import *

# Band-layout whiteboard scene for the Measurement, Maps and Probability
# Essentials revision session. One band per teaching beat; the camera moves
# down and earlier work stays on the canvas. Exporter-supported mobjects
# only; every working line is its own single-string Tex/MathTex revealed
# with Write. No transforms, no FadeOut.
#
# Subtopic time shares (subtopics.json, total 1145 s):
# 210/165/170/170/135/145/150 -> bands 0-1 / 2-3 / 4-5 / 6-7 / 8 / 9 / 10.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class MeasurementMapsProbabilityEssentialsSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic full-screen while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): ladders, perimeter and area
        title = Tex("Measurement, Maps and Probability").scale(1.25).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = MathTex(r"2{,}5 \text{ kg} = 2\;500 \text{ g}; \quad 750 \text{ m}\ell = 0{,}75 \ell").scale(1.0).shift(UP * 1.2)
        b0_l2 = MathTex(r"1 \text{ m}^3 = 1\;000 \text{ litres}").scale(1.1).shift(UP * 0.3)
        self.play(Write(b0_l1))
        self.wait(2.5)
        self.play(Write(b0_l2))
        self.play(Create(SurroundingRectangle(b0_l2, color=GREEN)))
        self.wait(2.5)
        b0_l3 = Tex("Garden 8 m by 5 m — three different questions:").scale(1.0).shift(DOWN * 0.7)
        b0_l4 = MathTex(r"\text{Perimeter: } 2 \times (8+5) = 26 \text{ m of fencing}").scale(1.0).shift(DOWN * 1.6)
        b0_l5 = MathTex(r"\text{Area: } 8 \times 5 = 40 \text{ m}^2 \text{ of ground}").scale(1.0).shift(DOWN * 2.5)
        self.play(Write(b0_l3))
        self.wait(2)
        self.play(Write(b0_l4))
        self.wait(2)
        self.play(Write(b0_l5))
        self.wait(3)

        # --- Band 1 (subtopic_1): the cylinder walked to litres
        self.next_band(1)
        b1_t = Tex("The tank: from formula to litres").scale(1.15).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_t))
        self.wait(1.5)
        b1_l1 = MathTex(r"V = 3{,}142 \times 0{,}7^2 \times 1{,}5").scale(1.1).shift(band_shift(1) + UP * 1.1)
        b1_l2 = MathTex(r"0{,}7^2 = 0{,}49; \;\; \times 3{,}142 = 1{,}539\;58").scale(1.0).shift(band_shift(1) + UP * 0.2)
        b1_l3 = MathTex(r"\times \; 1{,}5 = 2{,}309 \text{ m}^3").scale(1.05).shift(band_shift(1) + DOWN * 0.7)
        b1_l4 = MathTex(r"2{,}309 \times 1\;000 \approx 2\;309 \text{ litres}").scale(1.1).shift(band_shift(1) + DOWN * 1.7)
        self.play(Write(b1_l1))
        self.wait(2.5)
        self.play(Write(b1_l2))
        self.wait(2.5)
        self.play(Write(b1_l3))
        self.wait(2)
        self.play(Write(b1_l4))
        self.play(Create(SurroundingRectangle(b1_l4, color=GREEN)))
        self.wait(2.5)
        b1_l5 = Tex("Radius, never diameter; litres, not cubic metres").scale(1.0).shift(band_shift(1) + DOWN * 2.7)
        self.play(Write(b1_l5))
        self.wait(3)

        # --- Band 2 (subtopic_2): the scale chain to kilometres
        self.next_band(2)
        b2_t = Tex("Scale 1 : 50 000 — run the chain home").scale(1.1).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(1.5)
        b2_l1 = MathTex(r"7 \times 50\;000 = 350\;000 \text{ cm}").scale(1.1).shift(band_shift(2) + UP * 1.0)
        b2_l2 = MathTex(r"\div \; 100 = 3\;500 \text{ m}").scale(1.1).shift(band_shift(2) + UP * 0.1)
        b2_l3 = MathTex(r"\div \; 1\;000 = 3{,}5 \text{ km}").scale(1.15).shift(band_shift(2) + DOWN * 0.8)
        self.play(Write(b2_l1))
        self.wait(2.5)
        self.play(Write(b2_l2))
        self.wait(2)
        self.play(Write(b2_l3))
        self.play(Create(SurroundingRectangle(b2_l3, color=GREEN)))
        self.wait(2.5)
        b2_l4 = Tex("An answer left in centimetres is a method mark").scale(1.0).shift(band_shift(2) + DOWN * 1.8)
        b2_l5 = Tex("stranded short of its answer mark").scale(1.0).shift(band_shift(2) + DOWN * 2.5)
        self.play(Write(b2_l4))
        self.play(Write(b2_l5))
        self.wait(3)

        # --- Band 3 (subtopic_2): decimal hours and chart reading
        self.next_band(3)
        b3_t = Tex("Decimal hours convert through 60").scale(1.15).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t))
        self.wait(1.5)
        b3_l1 = MathTex(r"\text{Time} = 420 \div 100 = 4{,}2 \text{ hours}").scale(1.05).shift(band_shift(3) + UP * 1.1)
        b3_l2 = MathTex(r"4 \text{ h } 20 \text{ min}").scale(1.05).shift(band_shift(3) + UP * 0.2)
        self.play(Write(b3_l1))
        self.wait(2.5)
        self.play(Write(b3_l2))
        self.play(Create(strike(b3_l2)))
        self.wait(2)
        b3_l3 = MathTex(r"0{,}2 \times 60 = 12 \;\Rightarrow\; 4 \text{ h } 12 \text{ min}").scale(1.1).shift(band_shift(3) + DOWN * 0.8)
        self.play(Write(b3_l3))
        self.play(Create(SurroundingRectangle(b3_l3, color=GREEN)))
        self.wait(2.5)
        b3_l4 = Tex("Distance chart: row of one town, column of the").scale(1.0).shift(band_shift(3) + DOWN * 1.8)
        b3_l5 = Tex("other; steepest section = steepest graph, not highest").scale(0.95).shift(band_shift(3) + DOWN * 2.6)
        self.play(Write(b3_l4))
        self.play(Write(b3_l5))
        self.wait(3)

        # --- Band 4 (subtopic_3): the plan, converted and matched
        self.next_band(4)
        b4_t = Tex("Plans: every centimetre is a metre at 1 : 100").scale(1.05).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(1.5)
        b4_l1 = MathTex(r"62 \text{ mm} \times 100 = 6\;200 \text{ mm} = 6{,}2 \text{ m}").scale(1.05).shift(band_shift(4) + UP * 1.1)
        self.play(Write(b4_l1))
        self.play(Create(SurroundingRectangle(b4_l1, color=GREEN)))
        self.wait(2.5)
        b4_l2 = Tex("Sanity: rooms live between 2 m and 8 m").scale(1.0).shift(band_shift(4) + UP * 0.1)
        b4_l3 = Tex("Symbols: thick walls, door arc, thin windows, WC").scale(1.0).shift(band_shift(4) + DOWN * 0.8)
        b4_l4 = Tex("Heights belong to the ELEVATIONS — match them").scale(1.0).shift(band_shift(4) + DOWN * 1.7)
        b4_l5 = Tex("by counting openings, anchored to compass words").scale(1.0).shift(band_shift(4) + DOWN * 2.4)
        self.play(Write(b4_l2))
        self.wait(2)
        self.play(Write(b4_l3))
        self.wait(2)
        self.play(Write(b4_l4))
        self.play(Write(b4_l5))
        self.wait(3)

        # --- Band 5 (subtopic_3): models and packaging
        self.next_band(5)
        b5_t = Tex("Models shrink; areas shrink SQUARED").scale(1.1).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_t))
        self.wait(1.5)
        b5_l1 = MathTex(r"\text{Stage } 10 \times 6 \text{ m at } 1:50 \rightarrow 20 \times 12 \text{ cm}").scale(1.0).shift(band_shift(5) + UP * 1.1)
        b5_l2 = MathTex(r"\text{Model's top area: } \tfrac{1}{50^2} = \tfrac{1}{2\;500} \text{ of the real}").scale(1.0).shift(band_shift(5) + UP * 0.1)
        self.play(Write(b5_l1))
        self.wait(2.5)
        self.play(Write(b5_l2))
        self.play(Create(SurroundingRectangle(b5_l2, color=GREEN)))
        self.wait(2.5)
        b5_l3 = Tex("Packaging: count WHOLE boxes along each axis,").scale(1.0).shift(band_shift(5) + DOWN * 0.9)
        b5_l4 = Tex("then multiply — volume division is only a ceiling").scale(1.0).shift(band_shift(5) + DOWN * 1.6)
        self.play(Write(b5_l3))
        self.play(Write(b5_l4))
        self.wait(3)

        # --- Band 6 (subtopic_4): three dialects, and the two coins
        self.next_band(6)
        b6_t = Tex("Probability speaks three dialects").scale(1.15).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_t))
        self.wait(1.5)
        b6_l1 = MathTex(r"P(\text{six}) = \tfrac{1}{6} = 0{,}17 = 17\%").scale(1.1).shift(band_shift(6) + UP * 1.1)
        self.play(Write(b6_l1))
        self.wait(2.5)
        b6_l2 = Tex("Two coins — list ALL outcomes first:").scale(1.05).shift(band_shift(6) + UP * 0.1)
        b6_l3 = MathTex(r"HH, \; HT, \; TH, \; TT").scale(1.1).shift(band_shift(6) + DOWN * 0.8)
        b6_l4 = MathTex(r"P(\text{two heads}) = \tfrac{1}{4} = 0{,}25").scale(1.1).shift(band_shift(6) + DOWN * 1.8)
        self.play(Write(b6_l2))
        self.wait(2)
        self.play(Write(b6_l3))
        self.wait(2)
        self.play(Write(b6_l4))
        self.play(Create(SurroundingRectangle(b6_l4, color=GREEN)))
        self.wait(2)
        b6_l5 = Tex("The list is the method mark; the answer follows").scale(1.0).shift(band_shift(6) + DOWN * 2.8)
        self.play(Write(b6_l5))
        self.wait(3)

        # --- Band 7 (subtopic_4): the table and its denominators
        self.next_band(7)
        b7_t = Tex("Denominator discipline on the table").scale(1.1).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(1.5)
        b7_l1 = Tex("120 learners: 42 girls and 30 boys walk").scale(1.0).shift(band_shift(7) + UP * 1.1)
        b7_l2 = MathTex(r"P(\text{walks}) = \tfrac{72}{120} = 0{,}6").scale(1.05).shift(band_shift(7) + UP * 0.2)
        b7_l3 = MathTex(r"P(\text{boy who walks}) = \tfrac{30}{120} = 0{,}25").scale(1.05).shift(band_shift(7) + DOWN * 0.8)
        b7_l4 = MathTex(r"P(\text{a chosen BOY walks}) = \tfrac{30}{50} = 0{,}6").scale(1.05).shift(band_shift(7) + DOWN * 1.8)
        self.play(Write(b7_l1))
        self.wait(2)
        self.play(Write(b7_l2))
        self.wait(2)
        self.play(Write(b7_l3))
        self.wait(2)
        self.play(Write(b7_l4))
        self.play(Create(SurroundingRectangle(b7_l4, color=GREEN)))
        self.wait(2)
        b7_l5 = MathTex(r"\text{Complement: rain } 30\% \Rightarrow \text{dry } 70\%").scale(1.0).shift(band_shift(7) + DOWN * 2.8)
        self.play(Write(b7_l5))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): setting up the hall
        self.next_band(8)
        b8_t = Tex("Setting up the hall").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_t))
        self.wait(1.5)
        b8_l1 = MathTex(r"\text{Floor: } 15 \times 9 = 135 \text{ m}^2; \;\; 135 \div 9 = 15 \text{ tables}").scale(0.95).shift(band_shift(8) + UP * 1.1)
        b8_l2 = MathTex(r"15 \times 8 = 120 \text{ seats}").scale(1.05).shift(band_shift(8) + UP * 0.2)
        b8_l3 = MathTex(r"\text{Lights on the edge: } 2 \times (15+9) = 48 \text{ m}").scale(1.0).shift(band_shift(8) + DOWN * 0.7)
        self.play(Write(b8_l1))
        self.wait(2.5)
        self.play(Write(b8_l2))
        self.wait(2)
        self.play(Write(b8_l3))
        self.wait(2.5)
        b8_l4 = MathTex(r"\text{Urn: } 20\;000 \div 250 = 80 \text{ cups} < 120 \text{ guests}").scale(0.95).shift(band_shift(8) + DOWN * 1.7)
        b8_l5 = Tex("Two urns pour 160: enough, with 40 spare").scale(1.05).shift(band_shift(8) + DOWN * 2.7)
        self.play(Write(b8_l4))
        self.wait(2.5)
        self.play(Write(b8_l5))
        self.play(Create(SurroundingRectangle(b8_l5, color=GREEN)))
        self.wait(3)

        # --- Band 9 (subtopic_6): getting Gogo to the venue
        self.next_band(9)
        b9_t = Tex("Getting Gogo to the venue").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(1.5)
        b9_l1 = MathTex(r"\text{Drive: } 180 \div 90 = 2 \text{ h; stops add } 30 \text{ min}").scale(1.0).shift(band_shift(9) + UP * 1.1)
        b9_l2 = MathTex(r"09{:}30 - 2\text{ h} = 07{:}30; \; -30 \text{ min} = 07{:}00").scale(1.05).shift(band_shift(9) + UP * 0.1)
        self.play(Write(b9_l1))
        self.wait(2.5)
        self.play(Write(b9_l2))
        self.play(Create(SurroundingRectangle(b9_l2, color=GREEN)))
        self.wait(2.5)
        b9_l3 = MathTex(r"\text{Gravel: } 12 \times 50\;000 = 600\;000 \text{ cm} = 6 \text{ km}").scale(1.0).shift(band_shift(9) + DOWN * 0.9)
        b9_l4 = MathTex(r"6 \div 60 = 0{,}1 \text{ h} = 6 \text{ min}").scale(1.05).shift(band_shift(9) + DOWN * 1.8)
        b9_l5 = MathTex(r"\text{Petrol: } \tfrac{180}{100} \times 8 = 14{,}4 \ell; \; \times 23{,}50 = \text{R}338{,}40").scale(0.95).shift(band_shift(9) + DOWN * 2.8)
        self.play(Write(b9_l3))
        self.wait(2.5)
        self.play(Write(b9_l4))
        self.wait(2)
        self.play(Write(b9_l5))
        self.wait(3)

        # --- Band 10 (subtopic_7): will it rain on Saturday?
        self.next_band(10)
        b10_t = Tex("Will it rain on Saturday?").scale(1.2).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_t))
        self.wait(1.5)
        b10_l1 = MathTex(r"30\% = \tfrac{3}{10} = 0{,}3; \quad \text{dry} = 70\%").scale(1.05).shift(band_shift(10) + UP * 1.1)
        b10_l2 = Tex("NOT rain for 30\\% of the day — 3 days in 10 like this").scale(0.95).shift(band_shift(10) + UP * 0.2)
        self.play(Write(b10_l1))
        self.wait(2.5)
        self.play(Write(b10_l2))
        self.wait(2.5)
        b10_l3 = MathTex(r"\text{Family's 20 years: } \tfrac{4}{20} = 0{,}2 \text{ (experimental)}").scale(1.0).shift(band_shift(10) + DOWN * 0.8)
        self.play(Write(b10_l3))
        self.play(Create(SurroundingRectangle(b10_l3, color=GREEN)))
        self.wait(2.5)
        b10_l4 = Tex("The R850 gazebo: no single right answer —").scale(1.0).shift(band_shift(10) + DOWN * 1.8)
        b10_l5 = Tex("weigh the cost against being wrong, state the reason").scale(0.95).shift(band_shift(10) + DOWN * 2.6)
        self.play(Write(b10_l4))
        self.play(Write(b10_l5))
        self.wait(4)
