from manim import *

# Band layout: one frame-height band per teaching beat; the camera moves down
# to fresh space and earlier work stays on the canvas. Only exporter-supported
# mobjects; every line of working is a single-string MathTex revealed with
# Write — no sub-part transforms.
#
# Mirrors script.md across all seven subtopics (Part 1 — Expert: 1-4;
# Part 2 — Simplifier: 5-7), band time roughly proportional to subtopics.json
# (225/240/225/250/180/180/180 of 1480 s).

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class PrismsAndCylindersSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic display holds while intro.md audio plays.
        self.wait(15)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): one law — base area times height
        title = Tex("Volume and Surface Area: Prisms and Cylinders").scale(1.05).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = MathTex(r"V = \text{base area} \times \text{height}").scale(1.2).shift(UP * 0.9)
        self.play(Write(b0_l1))
        self.wait(2.5)
        b0_l2 = Tex(r"A stack of identical layers: floor $\times$ floors").scale(1.05).shift(DOWN * 0.1)
        self.play(Write(b0_l2))
        self.wait(2.5)
        b0_l3 = MathTex(r"\text{Juice box } 8 \times 5 \times 12: \; V = 40 \times 12").scale(1.05).shift(DOWN * 1.1)
        self.play(Write(b0_l3))
        self.wait(2)
        b0_l4 = MathTex(r"V = 480 \text{ cm}^3").scale(1.15).shift(DOWN * 2.1)
        self.play(Write(b0_l4))
        self.play(Create(SurroundingRectangle(b0_l4, color=GREEN)))
        self.wait(3)

        # --- Band 1 (subtopic_1): the can — exact first, decimal last
        self.next_band(1)
        b1_title = Tex(r"Can: radius 5, height 12").scale(1.15).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l1 = MathTex(r"\text{Base: } \pi r^2 = 25\pi").scale(1.1).shift(band_shift(1) + UP * 1.1)
        self.play(Write(b1_l1))
        self.wait(2)
        b1_l2 = MathTex(r"V = 25\pi \times 12 = 300\pi \text{ cm}^3").scale(1.1).shift(band_shift(1) + UP * 0.1)
        self.play(Write(b1_l2))
        self.wait(2)
        b1_l3 = MathTex(r"300\pi = 942{,}48 \text{ cm}^3").scale(1.1).shift(band_shift(1) + DOWN * 0.9)
        self.play(Write(b1_l3))
        self.play(Create(SurroundingRectangle(b1_l3, color=GREEN)))
        self.wait(2)
        b1_l4 = Tex("Exact form first — rounding early plants errors").scale(1.0).shift(band_shift(1) + DOWN * 1.9)
        self.play(Write(b1_l4))
        self.wait(2)
        b1_l5 = Tex("Height = direction the base was copied in").scale(1.0).shift(band_shift(1) + DOWN * 2.8)
        self.play(Write(b1_l5))
        self.wait(3)

        # --- Band 2 (subtopic_2): the box net — six faces, three pairs
        self.next_band(2)
        b2_title = Tex("Unfold the box: six faces, three pairs").scale(1.1).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(2)
        b2_l1 = MathTex(r"\text{Top/bottom: } 8 \times 5 = 40 \text{ each}").scale(1.05).shift(band_shift(2) + UP * 1.1)
        self.play(Write(b2_l1))
        self.wait(2)
        b2_l2 = MathTex(r"\text{Front/back: } 8 \times 12 = 96 \text{ each}").scale(1.05).shift(band_shift(2) + UP * 0.2)
        self.play(Write(b2_l2))
        self.wait(2)
        b2_l3 = MathTex(r"\text{Sides: } 5 \times 12 = 60 \text{ each}").scale(1.05).shift(band_shift(2) + DOWN * 0.7)
        self.play(Write(b2_l3))
        self.wait(2)
        b2_l4 = MathTex(r"A = 2(40 + 96 + 60) = 392 \text{ cm}^2").scale(1.1).shift(band_shift(2) + DOWN * 1.7)
        self.play(Write(b2_l4))
        self.play(Create(SurroundingRectangle(b2_l4, color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_2): the can net — the label is a rectangle
        self.next_band(3)
        b3_title = Tex("The can unfolds into three pieces").scale(1.1).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(2)
        b3_l1 = MathTex(r"\text{Two circles: } 25\pi + 25\pi = 50\pi").scale(1.05).shift(band_shift(3) + UP * 1.1)
        self.play(Write(b3_l1))
        self.wait(2)
        b3_l2 = Tex(r"The wall rolls flat: a rectangle").scale(1.05).shift(band_shift(3) + UP * 0.2)
        self.play(Write(b3_l2))
        self.wait(2)
        b3_l3 = MathTex(r"2\pi r \times h = 10\pi \times 12 = 120\pi").scale(1.05).shift(band_shift(3) + DOWN * 0.7)
        self.play(Write(b3_l3))
        self.wait(2)
        b3_l4 = MathTex(r"A = 50\pi + 120\pi = 170\pi = 534{,}07 \text{ cm}^2").scale(1.0).shift(band_shift(3) + DOWN * 1.7)
        self.play(Write(b3_l4))
        self.play(Create(SurroundingRectangle(b3_l4, color=GREEN)))
        self.wait(2)
        b3_l5 = Tex(r"The label peels off as a flat rectangle").scale(1.0).shift(band_shift(3) + DOWN * 2.7)
        self.play(Write(b3_l5))
        self.wait(3)

        # --- Band 4 (subtopic_3): triangular prism — volume
        self.next_band(4)
        b4_title = Tex(r"Triangular prism: legs 6, 8; hyp 10; length 15").scale(1.0).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(2)
        tri_a = Line(LEFT * 2.6 + DOWN * 1.0, LEFT * 0.8 + DOWN * 1.0).shift(band_shift(4))
        tri_b = Line(LEFT * 0.8 + DOWN * 1.0, LEFT * 0.8 + UP * 0.6).shift(band_shift(4))
        tri_c = Line(LEFT * 2.6 + DOWN * 1.0, LEFT * 0.8 + UP * 0.6).shift(band_shift(4))
        self.play(Create(tri_a), Create(tri_b))
        self.play(Create(tri_c))
        lbl6 = MathTex(r"8").scale(0.9).shift(band_shift(4) + LEFT * 1.7 + DOWN * 1.4)
        lbl8 = MathTex(r"6").scale(0.9).shift(band_shift(4) + LEFT * 0.4 + DOWN * 0.2)
        lbl10 = MathTex(r"10").scale(0.9).shift(band_shift(4) + LEFT * 2.2 + UP * 0.1)
        self.play(Write(lbl6), Write(lbl8), Write(lbl10))
        self.wait(2)
        b4_l1 = MathTex(r"\text{Base: } \tfrac{1}{2} \times 6 \times 8 = 24 \text{ cm}^2").scale(1.05).shift(band_shift(4) + RIGHT * 2.2 + UP * 0.0)
        self.play(Write(b4_l1))
        self.wait(2.5)
        b4_l2 = MathTex(r"V = 24 \times 15 = 360 \text{ cm}^3").scale(1.1).shift(band_shift(4) + DOWN * 2.2)
        self.play(Write(b4_l2))
        self.play(Create(SurroundingRectangle(b4_l2, color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_3): triangular prism — surface and traps
        self.next_band(5)
        b5_l1 = MathTex(r"\text{Two triangles: } 24 + 24 = 48").scale(1.05).shift(band_shift(5) + UP * 2.1)
        self.play(Write(b5_l1))
        self.wait(2)
        b5_l2 = MathTex(r"\text{Rectangles: perimeter} \times \text{length}").scale(1.05).shift(band_shift(5) + UP * 1.1)
        self.play(Write(b5_l2))
        self.wait(2)
        b5_l3 = MathTex(r"(6+8+10) \times 15 = 360").scale(1.05).shift(band_shift(5) + UP * 0.1)
        self.play(Write(b5_l3))
        self.wait(2)
        b5_l4 = MathTex(r"A = 48 + 360 = 408 \text{ cm}^2").scale(1.1).shift(band_shift(5) + DOWN * 0.9)
        self.play(Write(b5_l4))
        self.play(Create(SurroundingRectangle(b5_l4, color=GREEN)))
        self.wait(2)
        b5_wrong = MathTex(r"\text{Base area} = 6 \times 8 = 48").scale(1.0).shift(band_shift(5) + DOWN * 1.9)
        self.play(Write(b5_wrong))
        self.play(Create(strike(b5_wrong)))
        self.wait(1.5)
        b5_rule = Tex("The half is not optional; the hyp is not a height").scale(0.95).shift(band_shift(5) + DOWN * 2.8)
        self.play(Write(b5_rule))
        self.wait(3)

        # --- Band 6 (subtopic_4): capacity, mixed units, open solids
        self.next_band(6)
        b6_title = Tex("Housekeeping: units and capacity").scale(1.15).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(2)
        b6_l1 = MathTex(r"1000 \text{ cm}^3 = 1 \text{ litre}").scale(1.1).shift(band_shift(6) + UP * 1.1)
        self.play(Write(b6_l1))
        self.wait(2)
        b6_l2 = MathTex(r"480 \text{ cm}^3 = 0{,}48 \ell \qquad 942{,}48 \approx 0{,}94 \ell").scale(1.0).shift(band_shift(6) + UP * 0.2)
        self.play(Write(b6_l2))
        self.wait(2.5)
        b6_l3 = Tex(r"Mixed units? Convert BEFORE multiplying").scale(1.05).shift(band_shift(6) + DOWN * 0.7)
        self.play(Write(b6_l3))
        self.wait(2)
        b6_l4 = MathTex(r"\text{No lid: } 25\pi + 120\pi = 145\pi").scale(1.05).shift(band_shift(6) + DOWN * 1.6)
        self.play(Write(b6_l4))
        self.wait(2)
        b6_l5 = Tex(r"The story selects which faces exist").scale(1.05).shift(band_shift(6) + DOWN * 2.6)
        self.play(Write(b6_l5))
        self.wait(3)

        # --- Band 7 (subtopic_4): the error museum
        self.next_band(7)
        b7_title = Tex("The error museum").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(1.5)
        b7_l1 = Tex(r"1. Diameter used as radius: area $\times 4$ wrong").scale(1.0).shift(band_shift(7) + UP * 1.1)
        self.play(Write(b7_l1))
        self.wait(2.5)
        b7_l2 = Tex(r"2. Rounding $\pi$ early — carry the symbol").scale(1.0).shift(band_shift(7) + UP * 0.2)
        self.play(Write(b7_l2))
        self.wait(2.5)
        b7_l3 = Tex(r"3. Volume in cm$^2$, or area in cm$^3$").scale(1.0).shift(band_shift(7) + DOWN * 0.7)
        self.play(Write(b7_l3))
        self.wait(2.5)
        b7_l4 = Tex(r"4. The missing half in a triangular base").scale(1.0).shift(band_shift(7) + DOWN * 1.6)
        self.play(Write(b7_l4))
        self.wait(2)
        b7_l5 = Tex(r"Exact first, rounded second, unit checked").scale(1.05).shift(band_shift(7) + DOWN * 2.6)
        self.play(Write(b7_l5))
        self.play(Create(SurroundingRectangle(b7_l5, color=GREEN)))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): stacking identical floors
        self.next_band(8)
        b8_title = Tex("Stacking identical floors").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = Tex(r"A block of flats: one floor plan, 12 floors").scale(1.05).shift(band_shift(8) + UP * 1.1)
        self.play(Write(b8_l1))
        self.wait(2.5)
        b8_l2 = MathTex(r"\text{Box: } 40 \times 12 = 480 \text{ cm}^3").scale(1.05).shift(band_shift(8) + UP * 0.2)
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = MathTex(r"\text{Can: } 25\pi \times 12 = 300\pi = 942{,}48").scale(1.05).shift(band_shift(8) + DOWN * 0.7)
        self.play(Write(b8_l3))
        self.wait(2.5)
        b8_l4 = Tex(r"Find the floor, count the floors").scale(1.1).shift(band_shift(8) + DOWN * 1.7)
        self.play(Write(b8_l4))
        self.play(Create(SurroundingRectangle(b8_l4, color=GREEN)))
        self.wait(2)
        b8_l5 = Tex(r"The floor is the face that appears twice").scale(1.0).shift(band_shift(8) + DOWN * 2.7)
        self.play(Write(b8_l5))
        self.wait(3)

        # --- Band 9 (subtopic_6): wrapping, not filling
        self.next_band(9)
        b9_title = Tex("Wrapping, not filling").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex(r"Open the box flat: count six panels").scale(1.05).shift(band_shift(9) + UP * 1.1)
        self.play(Write(b9_l1))
        self.wait(2)
        b9_l2 = MathTex(r"2(40) + 2(96) + 2(60) = 392 \text{ cm}^2").scale(1.05).shift(band_shift(9) + UP * 0.2)
        self.play(Write(b9_l2))
        self.wait(2.5)
        b9_l3 = Tex(r"Peel the can's label: $10\pi \times 12 = 120\pi$").scale(1.05).shift(band_shift(9) + DOWN * 0.7)
        self.play(Write(b9_l3))
        self.wait(2.5)
        b9_l4 = MathTex(r"A = 120\pi + 50\pi = 170\pi = 534{,}07").scale(1.05).shift(band_shift(9) + DOWN * 1.7)
        self.play(Write(b9_l4))
        self.play(Create(SurroundingRectangle(b9_l4, color=GREEN)))
        self.wait(2)
        b9_l5 = Tex(r"Cubic fills; square wraps — check the unit").scale(1.0).shift(band_shift(9) + DOWN * 2.7)
        self.play(Write(b9_l5))
        self.wait(3)

        # --- Band 10 (subtopic_7): the five-step checklist
        self.next_band(10)
        b10_title = Tex("The five-step checklist").scale(1.2).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_title))
        self.wait(2)
        b10_l1 = Tex(r"1. Name the base — the face that repeats").scale(1.0).shift(band_shift(10) + UP * 1.2)
        self.play(Write(b10_l1))
        self.wait(2)
        b10_l2 = Tex(r"2. Base area (half for triangles, $r$ not $d$)").scale(1.0).shift(band_shift(10) + UP * 0.4)
        self.play(Write(b10_l2))
        self.wait(2)
        b10_l3 = Tex(r"3. Volume $=$ base area $\times$ height").scale(1.0).shift(band_shift(10) + DOWN * 0.4)
        self.play(Write(b10_l3))
        self.wait(2)
        b10_l4 = Tex(r"4. Net for surface — only faces the story allows").scale(1.0).shift(band_shift(10) + DOWN * 1.2)
        self.play(Write(b10_l4))
        self.wait(2)
        b10_l5 = Tex(r"5. Exact, then rounded, then the right unit").scale(1.0).shift(band_shift(10) + DOWN * 2.0)
        self.play(Write(b10_l5))
        self.play(Create(SurroundingRectangle(b10_l5, color=GREEN)))
        self.wait(2)
        b10_l6 = Tex(r"Box: 480 and 392. Can: $300\pi$ and $170\pi$").scale(0.95).shift(band_shift(10) + DOWN * 2.9)
        self.play(Write(b10_l6))
        self.wait(4)
