from manim import *

# Band-layout whiteboard scene for "The Doppler Effect"
# (Part 1 Expert subtopics 1-4, Part 2 Simplifier subtopics 5-7).
# Exporter-safe vocabulary only; the wavefront picture is hand-built from
# Circles and a Dot. Write-only reveals; camera moves between bands.
# Subtopic durations 235/240/240/235/190/195/195 of 1530 s.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class DopplerEffectSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): definition + wavefront picture ---
        title = Tex("The Doppler Effect").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_def = Tex("Change in DETECTED frequency, because").scale(1.0).shift(UP * 1.3)
        b0_def2 = Tex("source and listener move relative to the medium").scale(0.95).shift(UP * 0.6)
        self.play(Write(b0_def))
        self.play(Write(b0_def2))
        self.wait(3)
        # Moving source: successive crests emitted from positions further right,
        # so wavefronts bunch ahead (right) and stretch behind (left).
        c0 = DOWN * 1.6 + LEFT * 1.0
        w1 = Circle(radius=1.7, color=BLUE).move_to(c0 + LEFT * 1.0)
        w2 = Circle(radius=1.1, color=BLUE).move_to(c0 + LEFT * 0.45)
        w3 = Circle(radius=0.5, color=BLUE).move_to(c0)
        src = Dot(c0 + RIGHT * 0.25, color=YELLOW)
        self.play(Create(w1))
        self.play(Create(w2))
        self.play(Create(w3))
        self.play(FadeIn(src))
        arr = Arrow(c0 + RIGHT * 0.4, c0 + RIGHT * 1.6, buff=0, color=YELLOW)
        self.play(Create(arr))
        lab_ahead = Tex("bunched: higher $f$").scale(0.85).shift(c0 + RIGHT * 3.6 + UP * 0.6)
        lab_behind = Tex("stretched: lower $f$").scale(0.85).shift(c0 + LEFT * 3.9 + UP * 0.6)
        self.play(Write(lab_ahead))
        self.wait(1.5)
        self.play(Write(lab_behind))
        self.wait(3)

        # --- Band 1 (subtopic_1): what changes, what does not ---
        self.next_band(1)
        b1_title = Tex("What changes, what does not").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l1 = Tex(r"Speed of sound: fixed by the air ($\approx$ 340)").scale(1.0).shift(band_shift(1) + UP * 1.1)
        b1_l2 = Tex("Source frequency: never wavers").scale(1.0).shift(band_shift(1) + UP * 0.2)
        self.play(Write(b1_l1))
        self.wait(2)
        self.play(Write(b1_l2))
        self.wait(2)
        b1_wrong = Tex("Getting louder is the Doppler effect").scale(1.0).shift(band_shift(1) + DOWN * 0.8)
        self.play(Write(b1_wrong))
        self.play(Create(strike(b1_wrong)))
        self.wait(2)
        b1_l3 = Tex("Loudness $=$ amplitude and distance;").scale(1.0).shift(band_shift(1) + DOWN * 1.7)
        b1_l4 = Tex("PITCH $=$ frequency — only pitch is Doppler").scale(1.0).shift(band_shift(1) + DOWN * 2.6)
        self.play(Write(b1_l3))
        self.play(Write(b1_l4))
        self.play(Create(SurroundingRectangle(b1_l4, color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): the equation and its signs ---
        self.next_band(2)
        b2_eq = MathTex(r"f_L = \frac{v \pm v_L}{v \pm v_s} \, f_s").scale(1.3).shift(band_shift(2) + UP * 2.0)
        self.play(Write(b2_eq))
        self.play(Create(SurroundingRectangle(b2_eq, color=GREEN)))
        self.wait(3)
        b2_l1 = Tex("Listener lives in the NUMERATOR:").scale(1.0).shift(band_shift(2) + UP * 0.6)
        b2_l2 = Tex("toward source: add; away: subtract").scale(1.0).shift(band_shift(2) + DOWN * 0.2)
        self.play(Write(b2_l1))
        self.play(Write(b2_l2))
        self.wait(2.5)
        b2_l3 = Tex("Source lives in the DENOMINATOR:").scale(1.0).shift(band_shift(2) + DOWN * 1.1)
        b2_l4 = Tex("toward listener: subtract; away: add").scale(1.0).shift(band_shift(2) + DOWN * 1.9)
        self.play(Write(b2_l3))
        self.play(Write(b2_l4))
        self.wait(2.5)
        b2_rule = Tex("Approach raises $f$; recession lowers it").scale(1.0).shift(band_shift(2) + DOWN * 2.9)
        self.play(Write(b2_rule))
        self.play(Create(SurroundingRectangle(b2_rule, color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_2): the ambulance, both sides of the pass ---
        self.next_band(3)
        b3_title = Tex(r"Siren 900 Hz, source at 30 m$\cdot$s$^{-1}$").scale(1.1).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(2)
        b3_l1 = MathTex(r"f_L = \frac{340}{340 - 30} \times 900").scale(1.05).shift(band_shift(3) + UP * 1.0)
        b3_l2 = MathTex(r"f_L = \frac{340}{310} \times 900 = 987{,}10\ \text{Hz}").scale(1.05).shift(band_shift(3) + DOWN * 0.2)
        self.play(Write(b3_l1))
        self.wait(2.5)
        self.play(Write(b3_l2))
        self.play(Create(SurroundingRectangle(b3_l2, color=GREEN)))
        self.wait(2.5)
        b3_l3 = MathTex(r"\text{Receding: } \frac{340}{370} \times 900 = 827{,}03\ \text{Hz}").scale(1.0).shift(band_shift(3) + DOWN * 1.4)
        self.play(Write(b3_l3))
        self.play(Create(SurroundingRectangle(b3_l3, color=GREEN)))
        self.wait(2.5)
        b3_l4 = Tex("Pitch falls 987 to 827; siren held 900").scale(1.0).shift(band_shift(3) + DOWN * 2.5)
        self.play(Write(b3_l4))
        self.wait(3)

        # --- Band 4 (subtopic_3): moving listener + the reverse problem ---
        self.next_band(4)
        b4_title = Tex(r"Listener at 20 m$\cdot$s$^{-1}$, siren 500 Hz").scale(1.1).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(2)
        b4_l1 = MathTex(r"f_L = \frac{340 + 20}{340} \times 500 = 529{,}41\ \text{Hz}").scale(1.0).shift(band_shift(4) + UP * 1.1)
        b4_l2 = MathTex(r"\text{Away: } \frac{320}{340} \times 500 = 470{,}59\ \text{Hz}").scale(1.0).shift(band_shift(4) + UP * 0.1)
        self.play(Write(b4_l1))
        self.wait(2.5)
        self.play(Write(b4_l2))
        self.wait(2.5)
        b4_l3 = Tex("Reverse: 800 Hz hooter heard as 850 Hz").scale(1.0).shift(band_shift(4) + DOWN * 0.9)
        b4_l4 = Tex("Higher than source: APPROACHING (say it!)").scale(0.95).shift(band_shift(4) + DOWN * 1.7)
        self.play(Write(b4_l3))
        self.wait(2)
        self.play(Write(b4_l4))
        self.wait(2)
        b4_l5 = MathTex(r"340 - v_s = \frac{340 \times 800}{850} = 320").scale(1.0).shift(band_shift(4) + DOWN * 2.6)
        b4_l6 = MathTex(r"v_s = 20\ \text{m·s}^{-1}").scale(1.05).shift(band_shift(4) + DOWN * 3.5)
        self.play(Write(b4_l5))
        self.wait(2.5)
        self.play(Write(b4_l6))
        self.play(Create(SurroundingRectangle(b4_l6, color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_3): ultrasound in the clinic ---
        self.next_band(5)
        b5_title = Tex("Doppler in the clinic").scale(1.2).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(1.5)
        b5_l1 = Tex("Ultrasound: above 20 kHz, beyond hearing").scale(1.0).shift(band_shift(5) + UP * 1.1)
        b5_l2 = Tex("Reflects off moving blood cells —").scale(1.0).shift(band_shift(5) + UP * 0.2)
        b5_l3 = Tex("shift size measures blood-flow speed").scale(1.0).shift(band_shift(5) + DOWN * 0.7)
        self.play(Write(b5_l1))
        self.wait(2)
        self.play(Write(b5_l2))
        self.play(Write(b5_l3))
        self.wait(2.5)
        b5_l4 = Tex("Narrowed artery: blood speeds up — heard").scale(1.0).shift(band_shift(5) + DOWN * 1.6)
        b5_l5 = Tex("Foetal heartbeat: rhythmic shifts, no incision").scale(0.95).shift(band_shift(5) + DOWN * 2.5)
        self.play(Write(b5_l4))
        self.wait(2)
        self.play(Write(b5_l5))
        self.play(Create(SurroundingRectangle(b5_l5, color=GREEN)))
        self.wait(3)

        # --- Band 6 (subtopic_4): red shift and the expanding universe ---
        self.next_band(6)
        b6_title = Tex("Red shift: Doppler for light").scale(1.2).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(1.5)
        b6_l1 = Tex("Receding source: lower $f$ — toward the RED").scale(1.0).shift(band_shift(6) + UP * 1.1)
        b6_l2 = Tex("Each element's spectral lines: a fingerprint").scale(1.0).shift(band_shift(6) + UP * 0.2)
        b6_l3 = Tex("Galaxy light: the whole pattern slid redward").scale(1.0).shift(band_shift(6) + DOWN * 0.7)
        self.play(Write(b6_l1))
        self.wait(2.5)
        self.play(Write(b6_l2))
        self.wait(2.5)
        self.play(Write(b6_l3))
        self.wait(2.5)
        b6_l4 = Tex("Almost every galaxy: red-shifted;").scale(1.0).shift(band_shift(6) + DOWN * 1.6)
        b6_l5 = Tex("farther away, faster receding").scale(1.0).shift(band_shift(6) + DOWN * 2.4)
        self.play(Write(b6_l4))
        self.play(Write(b6_l5))
        self.wait(2.5)
        b6_l6 = Tex("Conclusion: the universe is EXPANDING").scale(1.05).shift(band_shift(6) + DOWN * 3.3)
        self.play(Write(b6_l6))
        self.play(Create(SurroundingRectangle(b6_l6, color=GREEN)))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 7 (subtopic_5): the siren that lies to you ---
        self.next_band(7)
        b7_title = Tex("The siren that lies to you").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(2)
        b7_l1 = Tex("To the paramedic: one steady note").scale(1.05).shift(band_shift(7) + UP * 1.1)
        b7_l2 = Tex("To you: high wail, then a sudden sag").scale(1.05).shift(band_shift(7) + UP * 0.2)
        self.play(Write(b7_l1))
        self.wait(2.5)
        self.play(Write(b7_l2))
        self.wait(2.5)
        b7_l3 = Tex("Crests launch from closer each time:").scale(1.0).shift(band_shift(7) + DOWN * 0.7)
        b7_l4 = Tex("bunched arrivals $=$ higher pitch").scale(1.0).shift(band_shift(7) + DOWN * 1.5)
        self.play(Write(b7_l3))
        self.play(Write(b7_l4))
        self.wait(2.5)
        b7_l5 = Tex("Motion re-spaces the waves — that is all").scale(1.0).shift(band_shift(7) + DOWN * 2.5)
        self.play(Write(b7_l5))
        self.play(Create(SurroundingRectangle(b7_l5, color=GREEN)))
        self.wait(3)

        # --- Band 8 (subtopic_6): taxis every ten minutes ---
        self.next_band(8)
        b8_title = Tex("Taxis leaving every ten minutes").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = Tex("Walk toward the rank: meet taxis sooner").scale(1.0).shift(band_shift(8) + UP * 1.1)
        b8_l2 = Tex("Walk away: they must chase you — fewer").scale(1.0).shift(band_shift(8) + UP * 0.2)
        self.play(Write(b8_l1))
        self.wait(2.5)
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = Tex("Rolling rank: each taxi starts from closer —").scale(1.0).shift(band_shift(8) + DOWN * 0.7)
        b8_l4 = Tex("gaps shrink for everyone downstream").scale(1.0).shift(band_shift(8) + DOWN * 1.5)
        self.play(Write(b8_l3))
        self.play(Write(b8_l4))
        self.wait(2.5)
        b8_l5 = Tex("Signs: pick whichever pushes approach UP").scale(1.0).shift(band_shift(8) + DOWN * 2.5)
        self.play(Write(b8_l5))
        self.play(Create(SurroundingRectangle(b8_l5, color=GREEN)))
        self.wait(3)

        # --- Band 9 (subtopic_7): maternity ward to the whole sky ---
        self.next_band(9)
        b9_title = Tex("From the maternity ward to the sky").scale(1.15).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex("Bounce a wave off a mover: the echo's").scale(1.0).shift(band_shift(9) + UP * 1.1)
        b9_l2 = Tex("shift betrays the speed — no touching").scale(1.0).shift(band_shift(9) + UP * 0.3)
        self.play(Write(b9_l1))
        self.play(Write(b9_l2))
        self.wait(2.5)
        b9_l3 = Tex("Blood through a squeeze, a beating heart").scale(1.0).shift(band_shift(9) + DOWN * 0.6)
        self.play(Write(b9_l3))
        self.wait(2.5)
        b9_l4 = Tex("Galaxies: fingerprints slid red — leaving;").scale(1.0).shift(band_shift(9) + DOWN * 1.5)
        b9_l5 = Tex("raisins drifting apart in rising bread").scale(1.0).shift(band_shift(9) + DOWN * 2.3)
        self.play(Write(b9_l4))
        self.wait(2)
        self.play(Write(b9_l5))
        self.wait(2)
        b9_l6 = Tex("One effect, three sizes").scale(1.05).shift(band_shift(9) + DOWN * 3.2)
        self.play(Write(b9_l6))
        self.play(Create(SurroundingRectangle(b9_l6, color=GREEN)))
        self.wait(4)
