from manim import *

# Band-layout whiteboard scene for the industrial-and-regional-development duo.
# Part 1 (Expert): subtopics 1-4; Part 2 (Simplifier): subtopics 5-7.
# Subtopic durations 230/235/245/245/190/195/190 of 1530 s — bands
# 0-1 / 2-3 / 4-5 / 6-7 / 8 / 9 / 10 apportioned to match.
# Diagrams hand-built from Arrow/Line/Rectangle/Tex primitives only.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class IndustrialRegionalDevelopmentSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic full-screen while intro.md audio plays.
        self.wait(14)

        # ===== Part 1 — Expert =====
        # --- Band 0 (subtopic_1): the value chain ---
        title = Tex("Industrial and Regional Development").scale(1.25).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        chain_y = UP * 0.9
        r1 = Rectangle(width=2.4, height=1.1).shift(LEFT * 5.0 + chain_y)
        t1 = Tex("iron ore").scale(0.95).shift(LEFT * 5.0 + chain_y)
        r2 = Rectangle(width=2.4, height=1.1).shift(LEFT * 1.7 + chain_y)
        t2 = Tex("steel").scale(0.95).shift(LEFT * 1.7 + chain_y)
        r3 = Rectangle(width=2.4, height=1.1).shift(RIGHT * 1.7 + chain_y)
        t3 = Tex("axle").scale(0.95).shift(RIGHT * 1.7 + chain_y)
        r4 = Rectangle(width=2.4, height=1.1).shift(RIGHT * 5.0 + chain_y)
        t4 = Tex("bakkie").scale(0.95).shift(RIGHT * 5.0 + chain_y)
        a1 = Arrow(LEFT * 3.8 + chain_y, LEFT * 2.9 + chain_y, buff=0, stroke_width=4)
        a2 = Arrow(LEFT * 0.5 + chain_y, RIGHT * 0.5 + chain_y, buff=0, stroke_width=4)
        a3 = Arrow(RIGHT * 2.9 + chain_y, RIGHT * 3.8 + chain_y, buff=0, stroke_width=4)
        self.play(Create(r1), Write(t1))
        self.play(Create(a1), Create(r2), Write(t2))
        self.play(Create(a2), Create(r3), Write(t3))
        self.play(Create(a3), Create(r4), Write(t4))
        self.wait(2)
        v1 = Tex("Each stage multiplies value — the maker keeps").scale(1.0).shift(DOWN * 0.4)
        v2 = Tex("the wages, profits and taxes it generates").scale(1.0).shift(DOWN * 1.1)
        self.play(Write(v1))
        self.play(Write(v2))
        self.wait(2.5)
        v3 = Tex("BENEFICIATION: process before export —").scale(1.05).shift(DOWN * 2.0)
        v4 = Tex("export the bakkie, not the ore").scale(1.05).shift(DOWN * 2.8)
        self.play(Write(v3))
        self.play(Write(v4))
        self.play(Create(SurroundingRectangle(v4, color=GREEN)))
        self.wait(3)

        # --- Band 1 (subtopic_1): four arguments and the caution ---
        self.next_band(1)
        b1_title = Tex("Why industrialise? Four arguments").scale(1.15).shift(band_shift(1) + UP * 2.4)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l1 = Tex("1. Value added stays home").scale(1.0).shift(band_shift(1) + UP * 1.5)
        b1_l2 = Tex("2. Employment: factories absorb semi-skilled labour").scale(1.0).shift(band_shift(1) + UP * 0.7)
        b1_l3 = Tex("3. Stability: diversify off the commodity roller-coaster").scale(0.95).shift(band_shift(1) + DOWN * 0.1)
        b1_l4 = Tex("4. Linkages: BACKWARD to suppliers,").scale(1.0).shift(band_shift(1) + DOWN * 0.9)
        b1_l5 = Tex("FORWARD to users — one plant, hundreds of firms").scale(1.0).shift(band_shift(1) + DOWN * 1.6)
        for m in (b1_l1, b1_l2, b1_l3, b1_l4, b1_l5):
            self.play(Write(m))
            self.wait(1.8)
        b1_l6 = Tex("Caution: is the industry becoming competitive,").scale(1.0).shift(band_shift(1) + DOWN * 2.5)
        b1_l7 = Tex("or merely comfortable?").scale(1.0).shift(band_shift(1) + DOWN * 3.1)
        self.play(Write(b1_l6))
        self.play(Write(b1_l7))
        self.play(Create(SurroundingRectangle(b1_l7, color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): the named strategies ---
        self.next_band(2)
        b2_title = Tex("South Africa's industrial strategies").scale(1.15).shift(band_shift(2) + UP * 2.4)
        self.play(Write(b2_title))
        self.wait(1.5)
        b2_l1 = Tex("NIPF 2007, rolled out through the IPAPs (dtic):").scale(1.0).shift(band_shift(2) + UP * 1.5)
        b2_l2 = Tex("priority sectors, targeted — not blanket — support").scale(1.0).shift(band_shift(2) + UP * 0.8)
        self.play(Write(b2_l1))
        self.play(Write(b2_l2))
        self.wait(2.5)
        b2_l3 = Tex("APDP: duty credits reward local production —").scale(1.0).shift(band_shift(2))
        b2_l4 = Tex("seven global carmakers assemble here").scale(1.0).shift(band_shift(2) + DOWN * 0.7)
        self.play(Write(b2_l3))
        self.play(Write(b2_l4))
        self.wait(2.5)
        b2_l5 = Tex("Clothing programme; Section 12I allowances").scale(1.0).shift(band_shift(2) + DOWN * 1.5)
        b2_l6 = Tex("Black Industrialists Scheme; IDC finance for").scale(1.0).shift(band_shift(2) + DOWN * 2.3)
        b2_l7 = Tex("projects banks find too slow or too risky").scale(1.0).shift(band_shift(2) + DOWN * 3.0)
        self.play(Write(b2_l5))
        self.wait(2)
        self.play(Write(b2_l6))
        self.play(Write(b2_l7))
        self.wait(3)

        # --- Band 3 (subtopic_2): localisation and the headwinds ---
        self.next_band(3)
        b3_title = Tex("The demand lever, and the headwinds").scale(1.15).shift(band_shift(3) + UP * 2.4)
        self.play(Write(b3_title))
        self.wait(1.5)
        b3_l1 = Tex("LOCALISATION: the state must buy local buses,").scale(1.0).shift(band_shift(3) + UP * 1.4)
        b3_l2 = Tex("rail stock, cables, uniforms — a guaranteed market").scale(1.0).shift(band_shift(3) + UP * 0.7)
        self.play(Write(b3_l1))
        self.play(Write(b3_l2))
        self.wait(2.5)
        b3_l3 = Tex("NDP goal: raise manufacturing's share of").scale(1.0).shift(band_shift(3) + DOWN * 0.2)
        b3_l4 = Tex("output and employment; grow small suppliers").scale(1.0).shift(band_shift(3) + DOWN * 0.9)
        self.play(Write(b3_l3))
        self.play(Write(b3_l4))
        self.wait(2.5)
        b3_l5 = Tex("Headwinds: expensive electricity, port and rail").scale(1.0).shift(band_shift(3) + DOWN * 1.8)
        b3_l6 = Tex("bottlenecks, skills shortages, Asian competition").scale(1.0).shift(band_shift(3) + DOWN * 2.5)
        self.play(Write(b3_l5))
        self.play(Write(b3_l6))
        self.wait(2)
        b3_l7 = Tex("A strategy on paper is not one in a load-shedding schedule").scale(0.9).shift(band_shift(3) + DOWN * 3.2)
        self.play(Write(b3_l7))
        self.play(Create(SurroundingRectangle(b3_l7, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): clustering, the homeland lesson, the corridor ---
        self.next_band(4)
        b4_title = Tex("Regional development: spreading the map").scale(1.15).shift(band_shift(4) + UP * 2.4)
        self.play(Write(b4_title))
        self.wait(1.5)
        b4_l1 = Tex("Industry clusters: Gauteng, 2\\% of the land,").scale(1.0).shift(band_shift(4) + UP * 1.4)
        b4_l2 = Tex("produces about a third of national output").scale(1.0).shift(band_shift(4) + UP * 0.7)
        self.play(Write(b4_l1))
        self.play(Write(b4_l2))
        self.wait(2.5)
        b4_l3 = Tex("Apartheid decentralisation: subsidies to homeland").scale(1.0).shift(band_shift(4) + DOWN * 0.2)
        b4_l4 = Tex("borders — factories died when subsidies stopped").scale(1.0).shift(band_shift(4) + DOWN * 0.9)
        self.play(Write(b4_l3))
        self.play(Write(b4_l4))
        self.play(Create(strike(b4_l4)))
        self.wait(2.5)
        b4_l5 = Tex("SDIs: invest along corridors with real potential —").scale(1.0).shift(band_shift(4) + DOWN * 1.8)
        b4_l6 = Tex("Maputo Corridor: N4, rail and border upgrades").scale(1.0).shift(band_shift(4) + DOWN * 2.5)
        b4_l7 = Tex("linking Gauteng's industry to Maputo's port").scale(1.0).shift(band_shift(4) + DOWN * 3.2)
        self.play(Write(b4_l5))
        self.play(Write(b4_l6))
        self.play(Write(b4_l7))
        self.wait(3)

        # --- Band 5 (subtopic_3): the SEZ toolkit ---
        self.next_band(5)
        b5_title = Tex("Special Economic Zones (SEZ Act, 2014)").scale(1.15).shift(band_shift(5) + UP * 2.4)
        self.play(Write(b5_title))
        self.wait(1.5)
        b5_l1 = Tex("Fenced zone at a port or airport, offering:").scale(1.0).shift(band_shift(5) + UP * 1.4)
        b5_l2 = Tex("15\\% corporate tax, building allowances,").scale(1.0).shift(band_shift(5) + UP * 0.7)
        b5_l3 = Tex("employment tax incentive, duty-free inputs").scale(1.0).shift(band_shift(5))
        self.play(Write(b5_l1))
        self.play(Write(b5_l2))
        self.play(Write(b5_l3))
        self.play(Create(SurroundingRectangle(b5_l2, color=GREEN)))
        self.wait(3)
        b5_l4 = Tex("Coega (Ngqura port, the largest); East London").scale(1.0).shift(band_shift(5) + DOWN * 1.0)
        b5_l5 = Tex("(vehicles); Richards Bay (metals); Dube TradePort").scale(1.0).shift(band_shift(5) + DOWN * 1.7)
        b5_l6 = Tex("(perishables); Saldanha (oil-and-gas); Tshwane (auto)").scale(0.95).shift(band_shift(5) + DOWN * 2.4)
        self.play(Write(b5_l4))
        self.wait(2)
        self.play(Write(b5_l5))
        self.wait(2)
        self.play(Write(b5_l6))
        self.wait(2)
        b5_l7 = Tex("Plus industrial parks and township programmes").scale(1.0).shift(band_shift(5) + DOWN * 3.1)
        self.play(Write(b5_l7))
        self.wait(3)

        # --- Band 6 (subtopic_4): best practice and results ---
        self.next_band(6)
        b6_title = Tex("Judging the strategies I").scale(1.15).shift(band_shift(6) + UP * 2.4)
        self.play(Write(b6_title))
        self.wait(1.5)
        b6_l1 = Tex("Best-practice recipe (Korea, Malaysia, Vietnam):").scale(1.0).shift(band_shift(6) + UP * 1.4)
        b6_l2 = Tex("tie support to EXPORTS, keep it TEMPORARY,").scale(1.0).shift(band_shift(6) + UP * 0.7)
        b6_l3 = Tex("invest in skills and infrastructure underneath").scale(1.0).shift(band_shift(6))
        self.play(Write(b6_l1))
        self.play(Write(b6_l2))
        self.play(Write(b6_l3))
        self.wait(2.5)
        b6_l4 = Tex("APDP passes the export test — scored highest").scale(1.0).shift(band_shift(6) + DOWN * 0.9)
        self.play(Write(b6_l4))
        self.wait(2)
        b6_l5 = Tex("Results: manufacturing's GDP share fell from").scale(1.0).shift(band_shift(6) + DOWN * 1.7)
        b6_l6 = Tex("over 19\\% toward 12–13\\% — deindustrialisation").scale(1.0).shift(band_shift(6) + DOWN * 2.4)
        self.play(Write(b6_l5))
        self.play(Write(b6_l6))
        self.play(Create(SurroundingRectangle(b6_l6, color=GREEN)))
        self.wait(2)
        b6_l7 = Tex("Coega, Dube: real tenants; other zones: empty sheds").scale(0.95).shift(band_shift(6) + DOWN * 3.2)
        self.play(Write(b6_l7))
        self.wait(3)

        # --- Band 7 (subtopic_4): constraints, cost, verdict ---
        self.next_band(7)
        b7_title = Tex("Judging the strategies II").scale(1.15).shift(band_shift(7) + UP * 2.4)
        self.play(Write(b7_title))
        self.wait(1.5)
        b7_l1 = Tex("Binding constraints: no incentive outweighs").scale(1.0).shift(band_shift(7) + UP * 1.4)
        b7_l2 = Tex("failing power, queuing ports, broken rail —").scale(1.0).shift(band_shift(7) + UP * 0.7)
        b7_l3 = Tex("fix network industries FIRST (top evaluation point)").scale(1.0).shift(band_shift(7))
        self.play(Write(b7_l1))
        self.play(Write(b7_l2))
        self.play(Write(b7_l3))
        self.play(Create(SurroundingRectangle(b7_l3, color=GREEN)))
        self.wait(3)
        b7_l4 = Tex("Cost and governance: rands per sustainable job;").scale(1.0).shift(band_shift(7) + DOWN * 1.0)
        b7_l5 = Tex("permanent subsidy repeats the homeland mistake").scale(1.0).shift(band_shift(7) + DOWN * 1.7)
        self.play(Write(b7_l4))
        self.play(Write(b7_l5))
        self.wait(2.5)
        b7_l6 = Tex("Investors price political risk like transport costs").scale(1.0).shift(band_shift(7) + DOWN * 2.6)
        self.play(Write(b7_l6))
        self.wait(3)

        # ===== Part 2 — Simplifier =====
        # --- Band 8 (subtopic_5): the bakkie and the bag of ore ---
        self.next_band(8)
        b8_title = Tex("The bakkie and the bag of ore").scale(1.2).shift(band_shift(8) + UP * 2.4)
        self.play(Write(b8_title))
        self.wait(2)
        o_rect = Rectangle(width=4.6, height=1.6).shift(band_shift(8) + LEFT * 3.4 + UP * 1.0)
        o_l1 = Tex("Bag of ore").scale(1.0).shift(band_shift(8) + LEFT * 3.4 + UP * 1.35)
        o_l2 = Tex("a few hundred rand").scale(0.9).shift(band_shift(8) + LEFT * 3.4 + UP * 0.7)
        self.play(Create(o_rect), Write(o_l1), Write(o_l2))
        self.wait(2)
        b_rect = Rectangle(width=4.6, height=1.6).shift(band_shift(8) + RIGHT * 3.4 + UP * 1.0)
        b_l1 = Tex("Bakkie").scale(1.0).shift(band_shift(8) + RIGHT * 3.4 + UP * 1.35)
        b_l2 = Tex("hundreds of thousands").scale(0.9).shift(band_shift(8) + RIGHT * 3.4 + UP * 0.7)
        self.play(Create(b_rect), Write(b_l1), Write(b_l2))
        self.wait(2)
        b8_l1 = Tex("Same iron — the maker keeps the wages of the").scale(1.0).shift(band_shift(8) + DOWN * 0.2)
        b8_l2 = Tex("steelworker, stitcher, painter, transporter").scale(1.0).shift(band_shift(8) + DOWN * 0.9)
        self.play(Write(b8_l1))
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = Tex("Hundreds of firms hang off one assembly line").scale(1.0).shift(band_shift(8) + DOWN * 1.8)
        self.play(Write(b8_l3))
        self.wait(2)
        b8_l4 = Tex("Help must have a finish line — support the child").scale(1.0).shift(band_shift(8) + DOWN * 2.6)
        b8_l5 = Tex("to grow up, not to stay a child").scale(1.0).shift(band_shift(8) + DOWN * 3.2)
        self.play(Write(b8_l4))
        self.play(Write(b8_l5))
        self.play(Create(SurroundingRectangle(b8_l5, color=GREEN)))
        self.wait(3)

        # --- Band 9 (subtopic_6): why the factory went to Coega ---
        self.next_band(9)
        b9_title = Tex("Why the factory went to Coega").scale(1.2).shift(band_shift(9) + UP * 2.4)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex("Factories go where factories already are —").scale(1.0).shift(band_shift(9) + UP * 1.5)
        b9_l2 = Tex("so the state builds the missing foundations").scale(1.0).shift(band_shift(9) + UP * 0.8)
        self.play(Write(b9_l1))
        self.play(Write(b9_l2))
        self.wait(2.5)
        b9_l3 = Tex("Coega deal: deep-water port, roads and power").scale(1.0).shift(band_shift(9))
        b9_l4 = Tex("ready, 15\\% tax, duty-free inputs for exporters").scale(1.0).shift(band_shift(9) + DOWN * 0.7)
        self.play(Write(b9_l3))
        self.play(Write(b9_l4))
        self.wait(2.5)
        b9_l5 = Tex("Corridor version: the N4 gave Mpumalanga's steel").scale(1.0).shift(band_shift(9) + DOWN * 1.5)
        b9_l6 = Tex("and fruit a shorter road to a ship").scale(1.0).shift(band_shift(9) + DOWN * 2.2)
        self.play(Write(b9_l5))
        self.play(Write(b9_l6))
        self.wait(2.5)
        b9_l7 = Tex("Pay a factory to ARRIVE anywhere;").scale(1.0).shift(band_shift(9) + DOWN * 3.0)
        b9_l8 = Tex("it STAYS only where business works").scale(1.0).shift(band_shift(9) + DOWN * 3.6)
        self.play(Write(b9_l7))
        self.play(Write(b9_l8))
        self.play(Create(SurroundingRectangle(b9_l8, color=GREEN)))
        self.wait(3)

        # --- Band 10 (subtopic_7): marking the government's homework ---
        self.next_band(10)
        b10_title = Tex("Marking the government's homework").scale(1.15).shift(band_shift(10) + UP * 2.6)
        self.play(Write(b10_title))
        self.wait(2)
        b10_l1 = Tex("1. State the test: exports, temporary, foundations").scale(1.0).shift(band_shift(10) + UP * 1.7)
        b10_l2 = Tex("2. Wins by name: car programme, Coega,").scale(1.0).shift(band_shift(10) + UP * 0.9)
        b10_l3 = Tex("Dube TradePort, the Maputo Corridor").scale(1.0).shift(band_shift(10) + UP * 0.2)
        b10_l4 = Tex("3. Failures by name: a fifth to an eighth of GDP,").scale(1.0).shift(band_shift(10) + DOWN * 0.6)
        b10_l5 = Tex("clothing jobs collapsed, empty-shed zones").scale(1.0).shift(band_shift(10) + DOWN * 1.3)
        b10_l6 = Tex("4. The bottleneck: power, rail, ports, skills").scale(1.0).shift(band_shift(10) + DOWN * 2.1)
        for m in (b10_l1, b10_l2, b10_l3, b10_l4, b10_l5, b10_l6):
            self.play(Write(m))
            self.wait(1.8)
        b10_l7 = Tex("Verdict: right direction — fix the constraints").scale(1.0).shift(band_shift(10) + DOWN * 2.9)
        b10_l8 = Tex("and the incentives can finally bite").scale(1.0).shift(band_shift(10) + DOWN * 3.5)
        self.play(Write(b10_l7))
        self.play(Write(b10_l8))
        self.play(Create(SurroundingRectangle(b10_l8, color=GREEN)))
        self.wait(4)
