from manim import *

# Band-layout whiteboard scene for "Unit Costs and Break-Even Analysis"
# (grade 11, term 3, cost accounting). One band per teaching beat; camera
# moves down, nothing is removed. Part 1 (Expert) = subtopics 1-4,
# Part 2 (Simplifier) = subtopics 5-7 in fresh bands. Exporter-safe
# primitives only; write-only reveals. Subtopic durations
# 225/225/240/235/195/195/205 of 1520 s guide the apportioning.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class BreakEvenAnalysisSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md plays.
        self.wait(14)

        # ===== Part 1 — Expert =====
        # --- Band 0 (subtopic_1): the budget, spoken in full ---
        title = Tex("Unit Costs and Break-Even Analysis").scale(1.2).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex("Plan: 24 000 pairs at R95 each").scale(1.1).shift(UP * 1.3)
        self.play(Write(b0_l1))
        self.wait(2)
        b0_l2 = Tex("Variable per pair: materials R23,").scale(1.05).shift(UP * 0.5)
        b0_l3 = Tex("labour R17, selling R8 $=$ R48").scale(1.05).shift(DOWN * 0.3)
        self.play(Write(b0_l2))
        self.play(Write(b0_l3))
        self.wait(2.5)
        b0_l4 = Tex("Fixed: overheads R400 000").scale(1.05).shift(DOWN * 1.2)
        b0_l5 = Tex("$+$ administration R258 000 $=$ R658 000").scale(1.05).shift(DOWN * 2.0)
        self.play(Write(b0_l4))
        self.play(Write(b0_l5))
        self.play(Create(SurroundingRectangle(b0_l5, color=GREEN)))
        b0_l6 = Tex("payable whether one pair is made or 30 000").scale(0.95).shift(DOWN * 2.9)
        self.play(Write(b0_l6))
        self.wait(3)

        # --- Band 1 (subtopic_1): each family from two angles ---
        self.next_band(1)
        b1_t = Tex("Watch each cost from two angles").scale(1.15).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_t))
        self.wait(2)
        b1_l1 = Tex("Variable: R48 PER UNIT, always").scale(1.05).shift(band_shift(1) + UP * 1.2)
        b1_l2 = Tex("in total: 10 000 pairs R480 000;").scale(1.0).shift(band_shift(1) + UP * 0.4)
        b1_l3 = Tex("24 000 pairs R1 152 000").scale(1.0).shift(band_shift(1) + DOWN * 0.3)
        self.play(Write(b1_l1))
        self.wait(2)
        self.play(Write(b1_l2))
        self.play(Write(b1_l3))
        self.wait(2.5)
        b1_l4 = Tex("Fixed: R658 000 IN TOTAL, always").scale(1.05).shift(band_shift(1) + DOWN * 1.2)
        b1_l5 = Tex("per unit: R65,80 at 10 000 pairs;").scale(1.0).shift(band_shift(1) + DOWN * 2.0)
        b1_l6 = Tex("R27,42 at 24 000 — volume spreads it").scale(1.0).shift(band_shift(1) + DOWN * 2.8)
        self.play(Write(b1_l4))
        self.wait(2)
        self.play(Write(b1_l5))
        self.play(Write(b1_l6))
        self.wait(3)

        # --- Band 2 (subtopic_2): contribution per unit ---
        self.next_band(2)
        b2_t = Tex("Contribution per unit").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(2)
        b2_l1 = Tex("Selling price per unit \\quad R95").scale(1.05).shift(band_shift(2) + UP * 1.2)
        b2_l2 = Tex("$-$ Variable cost per unit \\quad R48").scale(1.05).shift(band_shift(2) + UP * 0.4)
        b2_l3 = Tex("$=$ Contribution per unit \\quad R47").scale(1.1).shift(band_shift(2) + DOWN * 0.5)
        self.play(Write(b2_l1))
        self.wait(2)
        self.play(Write(b2_l2))
        self.wait(2)
        self.play(Write(b2_l3))
        self.play(Create(SurroundingRectangle(b2_l3, color=GREEN)))
        self.wait(2)
        b2_trap = Tex("Contribution $=$ profit?").scale(1.05).shift(band_shift(2) + DOWN * 1.5)
        self.play(Write(b2_trap))
        self.play(Create(strike(b2_trap)))
        b2_fix = Tex("It pays toward the R658 000 pile;").scale(1.0).shift(band_shift(2) + DOWN * 2.3)
        b2_fix2 = Tex("only after the pile is buried: profit").scale(1.0).shift(band_shift(2) + DOWN * 3.0)
        self.play(Write(b2_fix))
        self.play(Write(b2_fix2))
        self.wait(3)

        # --- Band 3 (subtopic_2): the four-line statement ---
        self.next_band(3)
        b3_t = Tex("The whole year in four lines").scale(1.15).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t))
        self.wait(2)
        b3_l1 = Tex("Sales: 24 000 $\\times$ R95 $=$ R2 280 000").scale(1.0).shift(band_shift(3) + UP * 1.2)
        b3_l2 = Tex("$-$ Variable: 24 000 $\\times$ R48 $=$ R1 152 000").scale(1.0).shift(band_shift(3) + UP * 0.4)
        b3_l3 = Tex("$=$ Contribution R1 128 000").scale(1.05).shift(band_shift(3) + DOWN * 0.5)
        b3_l4 = Tex("(check: 24 000 $\\times$ R47)").scale(0.95).shift(band_shift(3) + DOWN * 1.2)
        b3_l5 = Tex("$-$ Fixed costs R658 000").scale(1.05).shift(band_shift(3) + DOWN * 2.0)
        b3_l6 = Tex("$=$ Budgeted profit R470 000").scale(1.1).shift(band_shift(3) + DOWN * 2.9)
        self.play(Write(b3_l1))
        self.wait(2)
        self.play(Write(b3_l2))
        self.wait(2)
        self.play(Write(b3_l3))
        self.wait(1.5)
        self.play(Write(b3_l4))
        self.wait(1.5)
        self.play(Write(b3_l5))
        self.wait(1.5)
        self.play(Write(b3_l6))
        self.play(Create(SurroundingRectangle(b3_l6, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): the break-even point ---
        self.next_band(4)
        b4_t = Tex("Break-even: contribution buries fixed cost").scale(1.1).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(2)
        b4_f = MathTex(r"\text{BE units} = \frac{\text{total fixed costs}}{\text{contribution per unit}}").scale(1.05).shift(band_shift(4) + UP * 1.0)
        self.play(Write(b4_f))
        self.wait(2.5)
        b4_l1 = Tex("R658 000 $\\div$ R47 $=$ 14 000 pairs").scale(1.1).shift(band_shift(4) + DOWN * 0.2)
        self.play(Write(b4_l1))
        self.play(Create(SurroundingRectangle(b4_l1, color=GREEN)))
        self.wait(2.5)
        b4_l2 = Tex("Check: revenue 14 000 $\\times$ R95 $=$ R1 330 000").scale(0.95).shift(band_shift(4) + DOWN * 1.1)
        b4_l3 = Tex("variable R672 000; contribution R658 000").scale(0.95).shift(band_shift(4) + DOWN * 1.9)
        b4_l4 = Tex("$=$ fixed costs exactly: profit R0").scale(1.0).shift(band_shift(4) + DOWN * 2.7)
        self.play(Write(b4_l2))
        self.wait(2)
        self.play(Write(b4_l3))
        self.wait(2)
        self.play(Write(b4_l4))
        self.wait(2)
        b4_l5 = Tex("Break-even VALUE: R1 330 000").scale(1.0).shift(band_shift(4) + DOWN * 3.4)
        self.play(Write(b4_l5))
        self.wait(3)

        # --- Band 5 (subtopic_3): interpretation and the two disciplines ---
        self.next_band(5)
        b5_t = Tex("Interpret it, and round it UP").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_t))
        self.wait(2)
        b5_l1 = Tex("14 000 of 24 000 planned $=$ 58,3\\%").scale(1.05).shift(band_shift(5) + UP * 1.2)
        b5_l2 = Tex("well below plan: a healthy cushion").scale(1.0).shift(band_shift(5) + UP * 0.4)
        self.play(Write(b5_l1))
        self.wait(2)
        self.play(Write(b5_l2))
        self.wait(2)
        b5_trap = Tex("R658 000 $\\div$ R95 selling price?").scale(1.0).shift(band_shift(5) + DOWN * 0.5)
        self.play(Write(b5_trap))
        self.play(Create(strike(b5_trap)))
        b5_fix = Tex("Only CONTRIBUTION goes below the line").scale(1.0).shift(band_shift(5) + DOWN * 1.3)
        self.play(Write(b5_fix))
        self.wait(2)
        b5_l3 = Tex("R658 100 $\\div$ R47 $=$ 14 002,1").scale(1.0).shift(band_shift(5) + DOWN * 2.2)
        b5_l4 = Tex("14 002 still loses: break-even 14 003").scale(1.0).shift(band_shift(5) + DOWN * 3.0)
        self.play(Write(b5_l3))
        self.wait(2)
        self.play(Write(b5_l4))
        self.play(Create(SurroundingRectangle(b5_l4, color=GREEN)))
        self.wait(3)

        # --- Band 6 (subtopic_4): margin of safety ---
        self.next_band(6)
        b6_t = Tex("Margin of safety").scale(1.15).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_t))
        self.wait(2)
        b6_l1 = Tex("Planned 24 000 $-$ break-even 14 000").scale(1.05).shift(band_shift(6) + UP * 1.1)
        b6_l2 = Tex("$=$ 10 000 pairs $=$ 41,7\\% of plan").scale(1.05).shift(band_shift(6) + UP * 0.2)
        self.play(Write(b6_l1))
        self.wait(2)
        self.play(Write(b6_l2))
        self.play(Create(SurroundingRectangle(b6_l2, color=GREEN)))
        self.wait(2.5)
        b6_l3 = Tex("Sales can fall two fifths before loss").scale(1.0).shift(band_shift(6) + DOWN * 0.8)
        b6_l4 = Tex("A 5-10\\% margin reads as fragile:").scale(1.0).shift(band_shift(6) + DOWN * 1.6)
        b6_l5 = Tex("one bad season away from loss").scale(1.0).shift(band_shift(6) + DOWN * 2.4)
        self.play(Write(b6_l3))
        self.wait(2)
        self.play(Write(b6_l4))
        self.play(Write(b6_l5))
        self.wait(3)

        # --- Band 7 (subtopic_4): what-ifs on price and costs ---
        self.next_band(7)
        b7_t = Tex("What-if: the line moves").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(2)
        b7_l1 = Tex("Price R89: contribution R89 $-$ R48 $=$ R41").scale(1.0).shift(band_shift(7) + UP * 1.2)
        b7_l2 = Tex("R658 000 $\\div$ R41 $=$ 16 048,8 $\\Rightarrow$ 16 049").scale(1.0).shift(band_shift(7) + UP * 0.4)
        self.play(Write(b7_l1))
        self.wait(2)
        self.play(Write(b7_l2))
        self.wait(2.5)
        b7_l3 = Tex("Leather up R3: contribution R44").scale(1.0).shift(band_shift(7) + DOWN * 0.5)
        b7_l4 = Tex("R658 000 $\\div$ R44 $=$ 14 954,5 $\\Rightarrow$ 14 955").scale(1.0).shift(band_shift(7) + DOWN * 1.3)
        self.play(Write(b7_l3))
        self.wait(2)
        self.play(Write(b7_l4))
        self.wait(2.5)
        b7_l5 = Tex("Rent up R47 000: R705 000 $\\div$ R47").scale(1.0).shift(band_shift(7) + DOWN * 2.2)
        b7_l6 = Tex("$=$ 15 000 pairs exactly").scale(1.05).shift(band_shift(7) + DOWN * 3.0)
        self.play(Write(b7_l5))
        self.wait(2)
        self.play(Write(b7_l6))
        self.play(Create(SurroundingRectangle(b7_l6, color=GREEN)))
        self.wait(3)

        # ===== Part 2 — Simplifier =====
        # --- Band 8 (subtopic_5): the pile of stones ---
        self.next_band(8)
        b8_t = Tex("The pile of stones").scale(1.15).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_t))
        self.wait(2)
        b8_l1 = Tex("Saturday costs R658 before roll one:").scale(1.05).shift(band_shift(8) + UP * 1.2)
        b8_l2 = Tex("braai R400, gazebo and coolers R258").scale(1.0).shift(band_shift(8) + UP * 0.4)
        self.play(Write(b8_l1))
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = Tex("Each roll: R48 travels with it").scale(1.05).shift(band_shift(8) + DOWN * 0.5)
        b8_l4 = Tex("Sell at R95: R47 stays behind").scale(1.05).shift(band_shift(8) + DOWN * 1.3)
        self.play(Write(b8_l3))
        self.wait(2)
        self.play(Write(b8_l4))
        self.wait(2)
        b8_l5 = Tex("R47 $=$ one stone off the pile").scale(1.05).shift(band_shift(8) + DOWN * 2.2)
        self.play(Write(b8_l5))
        self.play(Create(SurroundingRectangle(b8_l5, color=GREEN)))
        b8_l6 = Tex("busier day $=$ cheaper braai per roll").scale(0.95).shift(band_shift(8) + DOWN * 3.0)
        self.play(Write(b8_l6))
        self.wait(3)

        # --- Band 9 (subtopic_6): roll number fourteen ---
        self.next_band(9)
        b9_t = Tex("Roll number fourteen").scale(1.15).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(2)
        b9_l1 = Tex("R658 $\\div$ R47 $=$ 14 rolls").scale(1.1).shift(band_shift(9) + UP * 1.2)
        b9_l2 = Tex("Roll 15 is the first one for YOU").scale(1.05).shift(band_shift(9) + UP * 0.4)
        self.play(Write(b9_l1))
        self.wait(2)
        self.play(Write(b9_l2))
        self.wait(2)
        b9_l3 = Tex("Factory adds zeros: R658 000 $\\div$ R47").scale(1.0).shift(band_shift(9) + DOWN * 0.5)
        b9_l4 = Tex("$=$ 14 000; 10 000 profit pairs $=$ R470 000").scale(1.0).shift(band_shift(9) + DOWN * 1.3)
        self.play(Write(b9_l3))
        self.wait(2)
        self.play(Write(b9_l4))
        self.wait(2)
        b9_trap = Tex("14,2 rolls? break even on roll 14?").scale(1.0).shift(band_shift(9) + DOWN * 2.2)
        self.play(Write(b9_trap))
        self.play(Create(strike(b9_trap)))
        b9_fix = Tex("Round UP: at 14 you are a stone short").scale(1.0).shift(band_shift(9) + DOWN * 3.0)
        self.play(Write(b9_fix))
        self.play(Create(SurroundingRectangle(b9_fix, color=GREEN)))
        self.wait(3)

        # --- Band 10 (subtopic_7): when the price of wors goes up ---
        self.next_band(10)
        b10_t = Tex("Ask what-if BEFORE Saturday").scale(1.15).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_t))
        self.wait(2)
        b10_l1 = Tex("Wors up R3: contribution R44,").scale(1.0).shift(band_shift(10) + UP * 1.2)
        b10_l2 = Tex("line moves to 15 rolls").scale(1.0).shift(band_shift(10) + UP * 0.5)
        self.play(Write(b10_l1))
        self.play(Write(b10_l2))
        self.wait(2.5)
        b10_l3 = Tex("Sell at R89: contribution R41,").scale(1.0).shift(band_shift(10) + DOWN * 0.3)
        b10_l4 = Tex("line jumps past 16 — a R6 cut bites R47").scale(1.0).shift(band_shift(10) + DOWN * 1.0)
        self.play(Write(b10_l3))
        self.play(Write(b10_l4))
        self.wait(2.5)
        b10_l5 = Tex("Braai up R47: pile R705, line at 15").scale(1.0).shift(band_shift(10) + DOWN * 1.8)
        self.play(Write(b10_l5))
        self.wait(2.5)
        b10_l6 = Tex("Factory echoes: 14 955, 16 049, 15 000").scale(1.0).shift(band_shift(10) + DOWN * 2.6)
        self.play(Write(b10_l6))
        self.play(Create(SurroundingRectangle(b10_l6, color=GREEN)))
        b10_l7 = Tex("The survival line is a headlight").scale(1.0).shift(band_shift(10) + DOWN * 3.4)
        self.play(Write(b10_l7))
        self.wait(4)
