from manim import *

# Band layout: one frame-tall bands down a long canvas; camera moves down,
# nothing is removed. Exporter-safe mobjects only (Tex/MathTex/Line/Arrow/
# Dot/Circle/Rectangle/VGroup); write-only reveals — no Transform/FadeOut.
#
# Mirrors script.md across the seven subtopics of the duo
# (Expert 1-4: bands 0-7; Simplifier 5-7: bands 8-10), scene time
# apportioned to subtopics.json (250/250/230/240/195/195/210 of 1570 s).

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class ImperfectMarketsSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic full-screen while intro.md plays (~4-5%).
        self.wait(15)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): monopoly and its barriers ---
        title = Tex("Monopoly, Oligopoly, Monopolistic Competition").scale(1.05).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        m1 = Tex(r"MONOPOLY: one seller, no close substitutes,").scale(1.0).shift(UP * 1.2)
        m2 = Tex(r"entry BLOCKED").scale(1.05).shift(UP * 0.5)
        self.play(Write(m1))
        self.play(Write(m2))
        self.wait(2.5)
        b1 = Tex(r"Barriers: patents and licences;").scale(1.0).shift(DOWN * 0.4)
        b2 = Tex(r"a key resource (De Beers); NATURAL").scale(1.0).shift(DOWN * 1.2)
        b3 = Tex(r"monopoly (the Eskom grid); scale").scale(1.0).shift(DOWN * 2.0)
        self.play(Write(b1))
        self.wait(1.5)
        self.play(Write(b2))
        self.wait(1.5)
        self.play(Write(b3))
        self.wait(2)
        pm = Tex(r"The monopolist IS the industry: a price MAKER").scale(0.95).shift(DOWN * 2.9)
        self.play(Write(pm))
        self.play(Create(SurroundingRectangle(pm, color=GREEN)))
        self.wait(3)

        # --- Band 1 (subtopic_1): MR below AR, and the diagram ---
        self.next_band(1)
        b1_title = Tex(r"Why MR runs below AR: 10 at R20, or 11 at R19").scale(1.0).shift(band_shift(1) + UP * 2.9)
        self.play(Write(b1_title))
        self.wait(1.5)
        ar1 = MathTex(r"MR = 19 - 10 \times 1 = R9, \text{ not } R19").scale(1.0).shift(band_shift(1) + UP * 2.1 + RIGHT * 2.2)
        self.play(Write(ar1))
        self.wait(2.5)
        o = band_shift(1) + DOWN * 2.9 + LEFT * 5.6
        y_ax = Arrow(o, o + UP * 4.7, buff=0, stroke_width=3)
        x_ax = Arrow(o, o + RIGHT * 7.2, buff=0, stroke_width=3)
        p_lab = Tex("P").scale(0.8).shift(o + UP * 4.7 + LEFT * 0.35)
        q_lab = Tex("Q").scale(0.8).shift(o + RIGHT * 7.2 + DOWN * 0.35)
        self.play(Create(y_ax), Create(x_ax), Write(p_lab), Write(q_lab))
        dd = Line(o + RIGHT * 0.4 + UP * 4.2, o + RIGHT * 6.0 + UP * 0.8, color=BLUE)
        dd_lab = Tex("D $=$ AR", color=BLUE).scale(0.8).shift(o + RIGHT * 6.7 + UP * 1.1)
        self.play(Create(dd), Write(dd_lab))
        self.wait(1.5)
        mr = Line(o + RIGHT * 0.4 + UP * 4.2, o + RIGHT * 3.6 + UP * 0.4, color=ORANGE)
        mr_lab = Tex("MR", color=ORANGE).scale(0.8).shift(o + RIGHT * 3.9 + UP * 0.15)
        self.play(Create(mr), Write(mr_lab))
        self.wait(1.5)
        mc = VGroup(Line(o + RIGHT * 0.8 + UP * 1.6, o + RIGHT * 1.6 + UP * 0.9, color=GREEN),
                    Line(o + RIGHT * 1.6 + UP * 0.9, o + RIGHT * 4.6 + UP * 3.9, color=GREEN))
        mc_lab = Tex("MC", color=GREEN).scale(0.8).shift(o + RIGHT * 5.0 + UP * 4.1)
        self.play(Create(mc), Write(mc_lab))
        self.wait(1.5)
        eq = Dot(o + RIGHT * 2.46 + UP * 1.76, color=YELLOW)
        eq_lab = Tex("MR $=$ MC").scale(0.7).shift(o + RIGHT * 3.6 + UP * 1.9)
        self.play(Create(eq), Write(eq_lab))
        up_line = DashedLine(o + RIGHT * 2.46 + UP * 1.76, o + RIGHT * 2.46 + UP * 2.95, color=GREY)
        pdot = Dot(o + RIGHT * 2.46 + UP * 2.95, color=YELLOW)
        pm_lab = MathTex(r"P_m").scale(0.75).shift(o + RIGHT * 1.9 + UP * 3.3)
        self.play(Create(up_line), Create(pdot), Write(pm_lab))
        self.wait(2)
        wrongp = Tex(r"Price read off MR").scale(0.85).shift(o + RIGHT * 8.6 + UP * 3.9)
        self.play(Write(wrongp))
        self.play(Create(strike(wrongp)))
        rightp = Tex(r"Price from D, above $Q_m$").scale(0.85).shift(o + RIGHT * 8.6 + UP * 3.1)
        self.play(Write(rightp))
        self.wait(2)
        verdict = Tex(r"$P > MC$, smaller Q, profit persists").scale(0.85).shift(o + RIGHT * 8.6 + UP * 2.1)
        self.play(Write(verdict))
        self.play(Create(SurroundingRectangle(verdict, color=GREEN)))
        self.wait(2.5)

        # --- Band 2 (subtopic_2): oligopoly and the kink ---
        self.next_band(2)
        b2_title = Tex("Oligopoly: the few, and the kink").scale(1.15).shift(band_shift(2) + UP * 2.9)
        self.play(Write(b2_title))
        self.wait(1.5)
        f1 = Tex(r"Few large, mutually dependent sellers —").scale(0.9).shift(band_shift(2) + UP * 2.1 + RIGHT * 2.6)
        f2 = Tex(r"each watches its rivals, not just the market").scale(0.85).shift(band_shift(2) + UP * 1.5 + RIGHT * 2.6)
        self.play(Write(f1))
        self.play(Write(f2))
        self.wait(2)
        o2 = band_shift(2) + DOWN * 2.9 + LEFT * 5.6
        y2 = Arrow(o2, o2 + UP * 4.6, buff=0, stroke_width=3)
        x2 = Arrow(o2, o2 + RIGHT * 6.2, buff=0, stroke_width=3)
        p2 = Tex("P").scale(0.8).shift(o2 + UP * 4.6 + LEFT * 0.35)
        q2 = Tex("Q").scale(0.8).shift(o2 + RIGHT * 6.2 + DOWN * 0.35)
        self.play(Create(y2), Create(x2), Write(p2), Write(q2))
        upper = Line(o2 + RIGHT * 0.6 + UP * 3.5, o2 + RIGHT * 3.0 + UP * 2.6, color=BLUE)
        lower = Line(o2 + RIGHT * 3.0 + UP * 2.6, o2 + RIGHT * 4.6 + UP * 0.4, color=BLUE)
        self.play(Create(upper))
        el_lab = Tex("raise: rivals sit still — elastic").scale(0.75).shift(o2 + RIGHT * 3.4 + UP * 3.9)
        self.play(Write(el_lab))
        self.wait(2)
        self.play(Create(lower))
        in_lab = Tex("cut: rivals match — inelastic").scale(0.75).shift(o2 + RIGHT * 6.6 + UP * 1.6)
        self.play(Write(in_lab))
        self.wait(2)
        kink = Dot(o2 + RIGHT * 3.0 + UP * 2.6, color=YELLOW)
        kink_lab = Tex("ruling price").scale(0.75).shift(o2 + RIGHT * 1.7 + UP * 2.3)
        self.play(Create(kink), Write(kink_lab))
        self.wait(2)
        sticky = Tex(r"Up loses alone; down gains nothing:").scale(0.85).shift(band_shift(2) + DOWN * 1.7 + RIGHT * 3.3)
        sticky2 = Tex(r"prices are STICKY").scale(0.9).shift(band_shift(2) + DOWN * 2.4 + RIGHT * 3.3)
        self.play(Write(sticky))
        self.play(Write(sticky2))
        self.play(Create(SurroundingRectangle(sticky2, color=GREEN)))
        self.wait(2.5)

        # --- Band 3 (subtopic_2): non-price war and collusion ---
        self.next_band(3)
        b3_title = Tex("Everything but the price — or a handshake").scale(1.1).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(1.5)
        np1 = Tex(r"Non-price weapons: branding, adverts,").scale(1.0).shift(band_shift(3) + UP * 1.2)
        np2 = Tex(r"loyalty cards, features, sponsorships").scale(1.0).shift(band_shift(3) + UP * 0.5)
        self.play(Write(np1))
        self.play(Write(np2))
        self.wait(2.5)
        col = Tex(r"CARTEL: the few price as one monopolist —").scale(0.95).shift(band_shift(3) + DOWN * 0.4)
        col2 = Tex(r"SA's bread and construction cases").scale(0.95).shift(band_shift(3) + DOWN * 1.1)
        self.play(Write(col))
        self.play(Write(col2))
        self.wait(2.5)
        tac = Tex(r"Tacit: price leadership, no word spoken").scale(0.95).shift(band_shift(3) + DOWN * 1.9)
        self.play(Write(tac))
        self.wait(2)
        inst = Tex(r"Cartels self-destruct: each member").scale(0.95).shift(band_shift(3) + DOWN * 2.7)
        inst2 = Tex(r"profits by secretly shading the price").scale(0.95).shift(band_shift(3) + DOWN * 3.4)
        self.play(Write(inst))
        self.play(Write(inst2))
        self.play(Create(SurroundingRectangle(inst2, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): monopolistic competition ---
        self.next_band(4)
        b4_title = Tex("Monopolistic competition: slightly special").scale(1.1).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(1.5)
        mc1 = Tex(r"MANY sellers, FREE entry, differentiated:").scale(0.95).shift(band_shift(4) + UP * 1.2)
        mc2 = Tex(r"salons, takeaways, guesthouses, labels").scale(0.95).shift(band_shift(4) + UP * 0.5)
        self.play(Write(mc1))
        self.play(Write(mc2))
        self.wait(2.5)
        mc3 = Tex(r"Loyalty tilts demand: gently sloping —").scale(0.95).shift(band_shift(4) + DOWN * 0.4)
        mc4 = Tex(r"close substitutes wait next door").scale(0.95).shift(band_shift(4) + DOWN * 1.1)
        self.play(Write(mc3))
        self.play(Write(mc4))
        self.wait(2.5)
        mc5 = Tex(r"Short run: MR $=$ MC, price off D,").scale(0.95).shift(band_shift(4) + DOWN * 2.0)
        mc6 = Tex(r"economic profit possible — for now").scale(0.95).shift(band_shift(4) + DOWN * 2.7)
        self.play(Write(mc5))
        self.play(Write(mc6))
        self.wait(3)

        # --- Band 5 (subtopic_3): entry until tangency ---
        self.next_band(5)
        b5_title = Tex("Entry slices until D touches AC").scale(1.1).shift(band_shift(5) + UP * 2.9)
        self.play(Write(b5_title))
        self.wait(1.5)
        o5 = band_shift(5) + DOWN * 2.9 + LEFT * 5.6
        y5 = Arrow(o5, o5 + UP * 4.6, buff=0, stroke_width=3)
        x5 = Arrow(o5, o5 + RIGHT * 6.6, buff=0, stroke_width=3)
        p5 = Tex("P").scale(0.8).shift(o5 + UP * 4.6 + LEFT * 0.35)
        q5 = Tex("Q").scale(0.8).shift(o5 + RIGHT * 6.6 + DOWN * 0.35)
        self.play(Create(y5), Create(x5), Write(p5), Write(q5))
        ac = VGroup(Line(o5 + RIGHT * 1.0 + UP * 3.4, o5 + RIGHT * 2.9 + UP * 1.5, color=GREEN),
                    Line(o5 + RIGHT * 2.9 + UP * 1.5, o5 + RIGHT * 5.4 + UP * 3.1, color=GREEN))
        ac_lab = Tex("AC", color=GREEN).scale(0.8).shift(o5 + RIGHT * 5.8 + UP * 3.3)
        self.play(Create(ac), Write(ac_lab))
        self.wait(1.5)
        d_old = Line(o5 + RIGHT * 1.6 + UP * 4.4, o5 + RIGHT * 5.8 + UP * 0.8, color=BLUE)
        d_old_lab = MathTex(r"D_1", color=BLUE).scale(0.8).shift(o5 + RIGHT * 6.2 + UP * 0.6)
        self.play(Create(d_old), Write(d_old_lab))
        self.wait(1.5)
        shiftar = Arrow(o5 + RIGHT * 4.2 + UP * 2.6, o5 + RIGHT * 3.0 + UP * 2.6, buff=0, color=YELLOW)
        d_new = Line(o5 + RIGHT * 0.6 + UP * 3.8, o5 + RIGHT * 4.4 + UP * 0.4, color=ORANGE)
        d_new_lab = MathTex(r"D_2", color=ORANGE).scale(0.8).shift(o5 + RIGHT * 4.8 + UP * 0.25)
        self.play(Create(shiftar))
        self.play(Create(d_new), Write(d_new_lab))
        self.wait(1.5)
        tang = Dot(o5 + RIGHT * 2.1 + UP * 2.45, color=YELLOW)
        tang_lab = Tex("tangency: P $=$ AC").scale(0.75).shift(o5 + RIGHT * 0.9 + UP * 1.7)
        self.play(Create(tang), Write(tang_lab))
        self.wait(2)
        n1 = Tex(r"Normal profit only — entry ate the rest").scale(0.85).shift(o5 + RIGHT * 9.3 + UP * 3.9)
        self.play(Write(n1))
        self.play(Create(SurroundingRectangle(n1, color=GREEN)))
        self.wait(2)
        n2 = Tex(r"Left of AC's minimum:").scale(0.85).shift(o5 + RIGHT * 9.3 + UP * 2.9)
        n3 = Tex(r"EXCESS CAPACITY, $P > MC$").scale(0.85).shift(o5 + RIGHT * 9.3 + UP * 2.2)
        self.play(Write(n2))
        self.play(Write(n3))
        self.wait(2)
        n4 = Tex(r"The compensation: VARIETY").scale(0.85).shift(o5 + RIGHT * 9.3 + UP * 1.2)
        self.play(Write(n4))
        self.wait(2.5)

        # --- Band 6 (subtopic_4): the comparison table ---
        self.next_band(6)
        b6_title = Tex("Four structures, five tests").scale(1.15).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(1.5)
        hdr = Tex(r"PC $\;|\;$ Mon.\ comp.\ $\;|\;$ Oligopoly $\;|\;$ Monopoly").scale(0.9).shift(band_shift(6) + UP * 1.3)
        self.play(Write(hdr))
        self.wait(2)
        t1 = Tex(r"Sellers: very many / many / few / one").scale(0.9).shift(band_shift(6) + UP * 0.5)
        t2 = Tex(r"Product: same / varied / either / unique").scale(0.9).shift(band_shift(6) + DOWN * 0.2)
        t3 = Tex(r"Entry: free / free / difficult / blocked").scale(0.9).shift(band_shift(6) + DOWN * 0.9)
        t4 = Tex(r"Price power: none / slight / careful / full").scale(0.9).shift(band_shift(6) + DOWN * 1.6)
        t5 = Tex(r"Demand: flat / gentle / kinked / market curve").scale(0.9).shift(band_shift(6) + DOWN * 2.3)
        self.play(Write(t1))
        self.wait(1.5)
        self.play(Write(t2))
        self.wait(1.5)
        self.play(Write(t3))
        self.wait(1.5)
        self.play(Write(t4))
        self.wait(1.5)
        self.play(Write(t5))
        self.wait(1.5)
        t6 = Tex(r"Long-run profit: normal / normal / possible / persists").scale(0.85).shift(band_shift(6) + DOWN * 3.0)
        self.play(Write(t6))
        self.play(Create(SurroundingRectangle(t6, color=GREEN)))
        self.wait(3)

        # --- Band 7 (subtopic_4): the two dials ---
        self.next_band(7)
        b7_title = Tex("One machine, two dials").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(1.5)
        d71 = Tex(r"WHERE to produce: always MR $=$ MC").scale(1.0).shift(band_shift(7) + UP * 1.2)
        d72 = Tex(r"WHAT price: off the firm's demand curve").scale(1.0).shift(band_shift(7) + UP * 0.4)
        d73 = Tex(r"WHAT profit: compare price with AC").scale(1.0).shift(band_shift(7) + DOWN * 0.4)
        self.play(Write(d71))
        self.wait(2)
        self.play(Write(d72))
        self.wait(2)
        self.play(Write(d73))
        self.wait(2)
        dial = Tex(r"Dials: SLOPE of demand, EASE of entry").scale(1.0).shift(band_shift(7) + DOWN * 1.4)
        self.play(Write(dial))
        self.play(Create(SurroundingRectangle(dial, color=GREEN)))
        self.wait(2)
        qual = Tex(r"Monopoly's qualification: natural scale").scale(0.95).shift(band_shift(7) + DOWN * 2.3)
        qual2 = Tex(r"wants regulation, not break-up").scale(0.95).shift(band_shift(7) + DOWN * 3.0)
        self.play(Write(qual))
        self.play(Write(qual2))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): the only bridge in town ---
        self.next_band(8)
        b8_title = Tex("The only bridge in town").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        br1 = Tex(r"No next table: raise the toll, most pay —").scale(0.95).shift(band_shift(8) + UP * 1.2)
        br2 = Tex(r"a price MAKER, constrained only by the slope").scale(0.9).shift(band_shift(8) + UP * 0.5)
        self.play(Write(br1))
        self.play(Write(br2))
        self.wait(2.5)
        br3 = Tex(r"Cut R20 to R19 for one more crosser:").scale(0.95).shift(band_shift(8) + DOWN * 0.4)
        br4 = Tex(r"EVERYONE pays R19 — the discount eats the gain").scale(0.9).shift(band_shift(8) + DOWN * 1.1)
        self.play(Write(br3))
        self.play(Write(br4))
        self.wait(2.5)
        br5 = Tex(r"That invisible cost is why MR $<$ price").scale(0.95).shift(band_shift(8) + DOWN * 2.0)
        self.play(Write(br5))
        self.play(Create(SurroundingRectangle(br5, color=GREEN)))
        self.wait(2.5)
        br6 = Tex(r"One bridge can be cheapest: natural monopoly —").scale(0.9).shift(band_shift(8) + DOWN * 2.9)
        br7 = Tex(r"put a regulator at the tollgate").scale(0.95).shift(band_shift(8) + DOWN * 3.5)
        self.play(Write(br6))
        self.play(Write(br7))
        self.wait(3)

        # --- Band 9 (subtopic_6): three petrol stations ---
        self.next_band(9)
        b9_title = Tex("Three petrol stations, one staring contest").scale(1.1).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        pe1 = Tex(r"Raise 10c: rivals sit still, pumps empty").scale(0.95).shift(band_shift(9) + UP * 1.2)
        pe2 = Tex(r"Cut 10c: rivals match, everyone poorer").scale(0.95).shift(band_shift(9) + UP * 0.4)
        self.play(Write(pe1))
        self.wait(2.5)
        self.play(Write(pe2))
        self.wait(2.5)
        pe3 = Tex(r"So the price stands still for months —").scale(0.95).shift(band_shift(9) + DOWN * 0.5)
        pe4 = Tex(r"the kink, drawn in real life").scale(0.95).shift(band_shift(9) + DOWN * 1.2)
        self.play(Write(pe3))
        self.play(Write(pe4))
        self.play(Create(SurroundingRectangle(pe4, color=GREEN)))
        self.wait(2.5)
        pe5 = Tex(r"War moves to forecourts, cards, coffee").scale(0.95).shift(band_shift(9) + DOWN * 2.1)
        self.play(Write(pe5))
        self.wait(2)
        pe6 = Tex(r"The dinner-table deal: cheating breaks it,").scale(0.9).shift(band_shift(9) + DOWN * 2.9)
        pe7 = Tex(r"and the Competition Commission raids it").scale(0.9).shift(band_shift(9) + DOWN * 3.5)
        self.play(Write(pe6))
        self.play(Write(pe7))
        self.wait(3)

        # --- Band 10 (subtopic_7): a street full of salons ---
        self.next_band(10)
        b10_title = Tex("A street full of salons").scale(1.2).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_title))
        self.wait(2)
        sa1 = Tex(r"Each owns a tiny bridge: R20 of loyalty,").scale(0.95).shift(band_shift(10) + UP * 1.2)
        sa2 = Tex(r"but ten substitutes wait within 200 m").scale(0.95).shift(band_shift(10) + UP * 0.5)
        self.play(Write(sa1))
        self.play(Write(sa2))
        self.wait(2.5)
        sa3 = Tex(r"Fat margins $\Rightarrow$ two new salons in months:").scale(0.9).shift(band_shift(10) + DOWN * 0.4)
        sa4 = Tex(r"curves creep left until profit is normal").scale(0.95).shift(band_shift(10) + DOWN * 1.1)
        self.play(Write(sa3))
        self.play(Write(sa4))
        self.wait(2.5)
        sa5 = Tex(r"The idle chair $=$ excess capacity,").scale(0.95).shift(band_shift(10) + DOWN * 1.9)
        sa6 = Tex(r"the price of variety").scale(0.95).shift(band_shift(10) + DOWN * 2.6)
        self.play(Write(sa5))
        self.play(Write(sa6))
        self.play(Create(SurroundingRectangle(sa6, color=GREEN)))
        self.wait(2.5)
        zoo = Tex(r"Tables, bridge, stations, salons — four structures").scale(0.85).shift(band_shift(10) + DOWN * 3.4)
        self.play(Write(zoo))
        self.wait(4)
