from manim import *

# Band-layout whiteboard scene for "National Accounts Aggregates"
# (Part 1 — Expert subtopics 1-4, Part 2 — Simplifier subtopics 5-7).
# Every worked calculation from the script appears line by line in MathTex.
# Exporter-safe primitives only; add-only lifecycle.
# Subtopic durations: 210/240/240/250/180/180/180 of 1480 s.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class NationalAccountsAggregatesSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        self.wait(14)

        # ===================== Part 1 — Expert =====================
        # --- Band 0 (subtopic_1): three routes to one total ---
        title = Tex("National Accounts Aggregates").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0a = Tex("Produced $=$ sold $=$ spent $=$ earned").scale(1.1).shift(UP * 1.2)
        self.play(Write(b0a))
        self.play(Create(SurroundingRectangle(b0a, color=GREEN)))
        self.wait(2)
        b0b = Tex("Production method: sum of VALUE ADDED").scale(1.0).shift(UP * 0.1)
        b0c = Tex("Expenditure method: spending on FINAL goods").scale(1.0).shift(DOWN * 0.7)
        b0d = Tex("Income method: factor incomes summed").scale(1.0).shift(DOWN * 1.5)
        self.play(Write(b0b))
        self.wait(2)
        self.play(Write(b0c))
        self.wait(2)
        self.play(Write(b0d))
        self.wait(2)
        b0e = Tex("Three routes, one GDP — difference $=$ residual").scale(1.0).shift(DOWN * 2.5)
        self.play(Write(b0e))
        self.wait(3)

        # --- Band 1 (subtopic_1): the three distinctions ---
        self.next_band(1)
        b1t = Tex("Three distinctions to state precisely").scale(1.15).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1t))
        self.wait(2)
        b1a = Tex("Final vs intermediate: flour to a bakery is").scale(1.0).shift(band_shift(1) + UP * 1.1)
        b1a2 = Tex("intermediate; to a household, final — use decides").scale(1.0).shift(band_shift(1) + UP * 0.4)
        self.play(Write(b1a))
        self.play(Write(b1a2))
        self.wait(2.5)
        b1b = Tex("Gross vs net: net subtracts consumption of").scale(1.0).shift(band_shift(1) + DOWN * 0.5)
        b1b2 = Tex("fixed capital — only net shows capacity growth").scale(1.0).shift(band_shift(1) + DOWN * 1.2)
        self.play(Write(b1b))
        self.play(Write(b1b2))
        self.wait(2.5)
        b1c = Tex("Domestic: inside the borders, whoever owns;").scale(1.0).shift(band_shift(1) + DOWN * 2.1)
        b1c2 = Tex("national: earned by residents, wherever").scale(1.0).shift(band_shift(1) + DOWN * 2.8)
        self.play(Write(b1c))
        self.play(Write(b1c2))
        self.play(Create(SurroundingRectangle(VGroup(b1c, b1c2), color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): household consumption C ---
        self.next_band(2)
        b2t = Tex("C: household consumption — the largest slice").scale(1.1).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2t))
        self.wait(2)
        b2a = Tex("About three-fifths of domestic expenditure").scale(1.0).shift(band_shift(2) + UP * 1.2)
        self.play(Write(b2a))
        self.wait(2)
        b2b = Tex("Durable (3+ yrs): vehicles, furniture, fridges").scale(0.95).shift(band_shift(2) + UP * 0.4)
        b2c = Tex("Semi-durable: clothing, footwear, tyres").scale(0.95).shift(band_shift(2) + DOWN * 0.3)
        b2d = Tex("Non-durable: food, fuel, medicine, electricity").scale(0.95).shift(band_shift(2) + DOWN * 1.0)
        b2e = Tex("Services: rent, transport, education, insurance").scale(0.95).shift(band_shift(2) + DOWN * 1.7)
        for m in (b2b, b2c, b2d, b2e):
            self.play(Write(m))
            self.wait(1.5)
        b2f = Tex("Durables are postponable — first to fall in a downturn").scale(0.9).shift(band_shift(2) + DOWN * 2.7)
        self.play(Write(b2f))
        self.play(Create(SurroundingRectangle(b2f, color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_2): G and its two exclusions ---
        self.next_band(3)
        b3t = Tex("G: government consumption — two exclusions").scale(1.1).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3t))
        self.wait(2)
        b3a = Tex("In G: salaries of teachers, nurses, police;").scale(1.0).shift(band_shift(3) + UP * 1.1)
        b3a2 = Tex("stationery, fuel, medicines, electricity").scale(1.0).shift(band_shift(3) + UP * 0.4)
        self.play(Write(b3a))
        self.play(Write(b3a2))
        self.wait(2.5)
        b3w1 = Tex("Social grants belong in G").scale(1.0).shift(band_shift(3) + DOWN * 0.5)
        self.play(Write(b3w1))
        self.play(Create(strike(b3w1)))
        b3r1 = Tex("Transfers buy nothing — counted in C when spent").scale(0.95).shift(band_shift(3) + DOWN * 1.3)
        self.play(Write(b3r1))
        self.wait(2.5)
        b3w2 = Tex("A new school building belongs in G").scale(1.0).shift(band_shift(3) + DOWN * 2.1)
        self.play(Write(b3w2))
        self.play(Create(strike(b3w2)))
        b3r2 = Tex("Capital spending is investment — it goes in I").scale(0.95).shift(band_shift(3) + DOWN * 2.9)
        self.play(Write(b3r2))
        self.play(Create(SurroundingRectangle(b3r2, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): gross fixed capital formation ---
        self.next_band(4)
        b4t = Tex("I: gross fixed capital formation").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4t))
        self.wait(2)
        b4a = Tex("Fixed assets used in production for over a year").scale(1.0).shift(band_shift(4) + UP * 1.2)
        self.play(Write(b4a))
        self.wait(2)
        b4b = Tex("Buildings, roads, rail, dams, ports, power;").scale(0.95).shift(band_shift(4) + UP * 0.4)
        b4b2 = Tex("machinery, transport, ICT, orchards, livestock").scale(0.95).shift(band_shift(4) + DOWN * 0.3)
        self.play(Write(b4b))
        self.play(Write(b4b2))
        self.wait(2.5)
        b4c = Tex("Second-hand factory: NOT capital formation —").scale(0.95).shift(band_shift(4) + DOWN * 1.2)
        b4c2 = Tex("no new asset; only ownership moved").scale(0.95).shift(band_shift(4) + DOWN * 1.9)
        self.play(Write(b4c))
        self.play(Write(b4c2))
        self.wait(2)
        b4d = Tex("Investors: private firms, public corporations, govt").scale(0.9).shift(band_shift(4) + DOWN * 2.8)
        self.play(Write(b4d))
        self.wait(3)

        # --- Band 5 (subtopic_3): net investment, and the target ---
        self.next_band(5)
        b5t = Tex("Gross to net, in rand billions").scale(1.2).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5t))
        self.wait(2)
        b5l1 = MathTex(r"\text{Gross I} = \text{R900 bn}, \; \text{depr.} = \text{R560 bn}").scale(0.95).shift(band_shift(5) + UP * 1.1)
        self.play(Write(b5l1))
        self.wait(2)
        b5l2 = MathTex(r"\text{Net I} = 900 - 560 = \text{R}340\,\text{bn}").scale(1.1).shift(band_shift(5) + UP * 0.2)
        self.play(Write(b5l2))
        self.play(Create(SurroundingRectangle(b5l2, color=GREEN)))
        self.wait(2.5)
        b5a = Tex("Only R340 bn adds capacity; the rest replaces wear").scale(0.95).shift(band_shift(5) + DOWN * 0.8)
        self.play(Write(b5a))
        self.wait(2)
        b5l3 = MathTex(r"\frac{900}{6\,300} = 14{,}3\% \quad \text{vs NDP target} \approx 30\%").scale(0.86).shift(band_shift(5) + DOWN * 1.8)
        self.play(Write(b5l3))
        self.wait(2)
        b5b = Tex("Gross below depreciation $=$ eating your capital").scale(0.95).shift(band_shift(5) + DOWN * 2.8)
        self.play(Write(b5b))
        self.wait(3)

        # --- Band 6 (subtopic_4): GNE and GDP ---
        self.next_band(6)
        b6t = Tex("GNE, then GDP (rand billions)").scale(1.2).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6t))
        self.wait(2)
        b6l1 = MathTex(r"GNE = C + G + I + \Delta\text{inventories}").scale(1.05).shift(band_shift(6) + UP * 1.2)
        self.play(Write(b6l1))
        self.wait(2)
        b6l2 = MathTex(r"= 3\,900 + 1\,400 + 900 + 50 = 6\,250").scale(1.05).shift(band_shift(6) + UP * 0.3)
        self.play(Write(b6l2))
        self.play(Create(SurroundingRectangle(b6l2, color=GREEN)))
        self.wait(2.5)
        b6l3 = MathTex(r"GDP = GNE + X - M").scale(1.05).shift(band_shift(6) + DOWN * 0.7)
        self.play(Write(b6l3))
        self.wait(2)
        b6l4 = MathTex(r"= 6\,250 + 1\,900 - 1\,850 = 6\,300").scale(1.05).shift(band_shift(6) + DOWN * 1.6)
        self.play(Write(b6l4))
        self.play(Create(SurroundingRectangle(b6l4, color=GREEN)))
        self.wait(2)
        b6a = Tex("Spend more than you produce: a trade deficit").scale(0.95).shift(band_shift(6) + DOWN * 2.6)
        self.play(Write(b6a))
        self.wait(3)

        # --- Band 7 (subtopic_4): GVA and GNI ---
        self.next_band(7)
        b7t = Tex("GVA and GNI close the chain").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7t))
        self.wait(2)
        b7l1 = MathTex(r"GDP = GVA + \text{taxes on products} - \text{subsidies}").scale(0.95).shift(band_shift(7) + UP * 1.2)
        self.play(Write(b7l1))
        self.wait(2)
        b7l2 = MathTex(r"5\,640 + 700 - 40 = 6\,300").scale(1.05).shift(band_shift(7) + UP * 0.3)
        self.play(Write(b7l2))
        self.wait(2.5)
        b7l3 = MathTex(r"GNI = GDP + \text{income received} - \text{income paid}").scale(0.95).shift(band_shift(7) + DOWN * 0.7)
        self.play(Write(b7l3))
        self.wait(2)
        b7l4 = MathTex(r"= 6\,300 + 90 - 240 = 6\,150").scale(1.05).shift(band_shift(7) + DOWN * 1.6)
        self.play(Write(b7l4))
        self.play(Create(SurroundingRectangle(b7l4, color=GREEN)))
        self.wait(2)
        b7a = Tex("GNI $<$ GDP: dividends flow to owners abroad").scale(0.95).shift(band_shift(7) + DOWN * 2.6)
        self.play(Write(b7a))
        self.wait(3)

        # ===================== Part 2 — Simplifier =====================
        # --- Band 8 (subtopic_5): the country's till slip ---
        self.next_band(8)
        b8t = Tex("The country's till slip").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8t))
        self.wait(2)
        b8a = Tex("Biggest pile: households — C, three rand in five").scale(1.0).shift(band_shift(8) + UP * 1.2)
        self.play(Write(b8a))
        self.wait(2)
        b8b = Tex("Fridge: durable $\\cdot$ shoes: semi $\\cdot$ bread: non-durable").scale(0.9).shift(band_shift(8) + UP * 0.4)
        b8b2 = Tex("taxi ride: service — nothing left behind").scale(0.95).shift(band_shift(8) + DOWN * 0.3)
        self.play(Write(b8b))
        self.play(Write(b8b2))
        self.wait(2.5)
        b8c = Tex("G: the nurse's pay, the chalk, the van's fuel").scale(1.0).shift(band_shift(8) + DOWN * 1.1)
        self.play(Write(b8c))
        self.wait(2)
        b8w = Tex("The neighbour's grant sits in G").scale(1.0).shift(band_shift(8) + DOWN * 2.0)
        self.play(Write(b8w))
        self.play(Create(strike(b8w)))
        b8r = Tex("It is counted in C when the household spends it").scale(0.95).shift(band_shift(8) + DOWN * 2.9)
        self.play(Write(b8r))
        self.play(Create(SurroundingRectangle(b8r, color=GREEN)))
        self.wait(3)

        # --- Band 9 (subtopic_6): spending that builds tomorrow ---
        self.next_band(9)
        b9t = Tex("Spending that builds tomorrow").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9t))
        self.wait(2)
        b9a = Tex("Stock and paint get sold; the R400 000 bakkie").scale(1.0).shift(band_shift(9) + UP * 1.1)
        b9a2 = Tex("still works next year — that is capital").scale(1.0).shift(band_shift(9) + UP * 0.4)
        self.play(Write(b9a))
        self.play(Write(b9a2))
        self.wait(2.5)
        b9l1 = MathTex(r"400\,000 - 150\,000 \text{ wear} = 250\,000 \text{ net}").scale(1.0).shift(band_shift(9) + DOWN * 0.5)
        self.play(Write(b9l1))
        self.wait(2)
        b9l2 = MathTex(r"\text{Country: } 900 - 560 = \text{R}340\,\text{bn new capacity}").scale(0.93).shift(band_shift(9) + DOWN * 1.4)
        self.play(Write(b9l2))
        self.play(Create(SurroundingRectangle(b9l2, color=GREEN)))
        self.wait(2)
        b9b = Tex("Second-hand bakkie: keys moved, no new asset").scale(0.95).shift(band_shift(9) + DOWN * 2.3)
        self.play(Write(b9b))
        self.wait(2)
        b9c = Tex("The only pile that makes NEXT year bigger").scale(1.0).shift(band_shift(9) + DOWN * 3.1)
        self.play(Write(b9c))
        self.wait(3)

        # --- Band 10 (subtopic_7): three totals, one country ---
        self.next_band(10)
        b10t = Tex("Three totals, one country").scale(1.2).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10t))
        self.wait(2)
        b10l1 = MathTex(r"\text{GNE: } 3\,900 + 1\,400 + 900 + 50 = 6\,250").scale(0.95).shift(band_shift(10) + UP * 1.2)
        self.play(Write(b10l1))
        self.wait(2)
        b10l2 = MathTex(r"\text{GDP: } 6\,250 + 1\,900 - 1\,850 = 6\,300").scale(0.95).shift(band_shift(10) + UP * 0.4)
        self.play(Write(b10l2))
        self.wait(2)
        b10l3 = MathTex(r"\text{GVA: } 5\,640 + 700 - 40 = 6\,300").scale(0.95).shift(band_shift(10) + DOWN * 0.4)
        self.play(Write(b10l3))
        self.wait(2)
        b10l4 = MathTex(r"\text{GNI: } 6\,300 + 90 - 240 = 6\,150").scale(0.95).shift(band_shift(10) + DOWN * 1.2)
        self.play(Write(b10l4))
        self.play(Create(SurroundingRectangle(b10l4, color=GREEN)))
        self.wait(2)
        b10a = Tex("Spent $\\cdot$ produced $\\cdot$ before tax $\\cdot$ kept").scale(1.0).shift(band_shift(10) + DOWN * 2.2)
        self.play(Write(b10a))
        self.wait(2)
        b10b = Tex("The R150 bn gap: the price of foreign shareholders").scale(0.95).shift(band_shift(10) + DOWN * 3.0)
        self.play(Write(b10b))
        self.wait(4)
