from manim import *

# Band-layout whiteboard scene for the organic reactions session duo.
# Covers all seven subtopics (Part 1 Expert: 1-4, Part 2 Simplifier: 5-7),
# band time proportional to subtopics.json (235/240/240/235/190/195/195 of
# 1530 s). Add-only lifecycle; exporter-safe mobjects only.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class OrganicReactionsSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        self.wait(14)

        # ===== Part 1 — Expert =====
        # --- Band 0 (subtopic_1): combustion ---
        title = Tex("Combustion: The Fuel Family at Work").scale(1.2).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_e1 = MathTex(r"CH_4 + 2O_2 \rightarrow CO_2 + 2H_2O").scale(1.1).shift(UP * 1.0)
        self.play(Write(b0_e1))
        self.wait(2)
        b0_l1 = Tex("Balance C first, then H, count O last").scale(1.0).shift(UP * 0.1)
        self.play(Write(b0_l1))
        self.wait(2)
        b0_e2 = MathTex(r"C_3H_8 + 5O_2 \rightarrow 3CO_2 + 4H_2O").scale(1.1).shift(DOWN * 0.9)
        self.play(Write(b0_e2))
        self.play(Create(SurroundingRectangle(b0_e2, color=GREEN)))
        self.wait(2.5)
        b0_l2 = Tex("EXCESS oxygen: complete combustion —").scale(1.0).shift(DOWN * 2.0)
        b0_l3 = Tex(r"only $CO_2$ and $H_2O$, plus the heat").scale(1.0).shift(DOWN * 2.8)
        self.play(Write(b0_l2))
        self.wait(1.5)
        self.play(Write(b0_l3))
        self.wait(3)

        # --- Band 1 (subtopic_1): esterification ---
        self.next_band(1)
        b1_t = Tex("Esterification: the perfume reaction").scale(1.15).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_t))
        self.wait(2)
        b1_l1 = Tex(r"acid + alcohol $\rightarrow$ ester + water").scale(1.1).shift(band_shift(1) + UP * 1.2)
        self.play(Write(b1_l1))
        self.wait(2)
        b1_l2 = Tex(r"conc. $H_2SO_4$ catalyst, gentle heat").scale(1.0).shift(band_shift(1) + UP * 0.4)
        self.play(Write(b1_l2))
        self.wait(2)
        b1_l3 = Tex("ethanoic acid + ethanol").scale(1.0).shift(band_shift(1) + DOWN * 0.5)
        b1_l4 = Tex(r"$\rightarrow$ ethyl ethanoate + $H_2O$").scale(1.05).shift(band_shift(1) + DOWN * 1.3)
        self.play(Write(b1_l3))
        self.wait(1.5)
        self.play(Write(b1_l4))
        self.play(Create(SurroundingRectangle(b1_l4, color=GREEN)))
        self.wait(2.5)
        b1_l5 = Tex("Alcohol gives -yl, acid gives -oate:").scale(1.0).shift(band_shift(1) + DOWN * 2.3)
        b1_l6 = Tex("methanol + butanoic acid = methyl butanoate").scale(0.95).shift(band_shift(1) + DOWN * 3.1)
        self.play(Write(b1_l5))
        self.wait(1.5)
        self.play(Write(b1_l6))
        self.wait(3)

        # --- Band 2 (subtopic_2): addition — hydrogen and halogens ---
        self.next_band(2)
        b2_t = Tex("Addition: opening the double bond").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(2)
        b2_l1 = Tex("Alkene + partner: two molecules become one").scale(0.95).shift(band_shift(2) + UP * 1.2)
        self.play(Write(b2_l1))
        self.wait(2)
        b2_l2 = Tex(r"Hydrogenation (Pt/Pd/Ni): ethene $\rightarrow$ ethane").scale(0.95).shift(band_shift(2) + UP * 0.3)
        b2_l3 = Tex("— oils harden into margarine").scale(0.95).shift(band_shift(2) + DOWN * 0.4)
        self.play(Write(b2_l2))
        self.wait(2)
        self.play(Write(b2_l3))
        self.wait(2)
        b2_l4 = Tex(r"Halogenation: ethene + $Br_2 \rightarrow$ 1,2-dibromoethane").scale(0.9).shift(band_shift(2) + DOWN * 1.3)
        self.play(Write(b2_l4))
        self.wait(2)
        b2_l5 = Tex("Bromine fades FAST = the unsaturation test").scale(0.95).shift(band_shift(2) + DOWN * 2.2)
        self.play(Write(b2_l5))
        self.play(Create(SurroundingRectangle(b2_l5, color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_2): the richness rule ---
        self.next_band(3)
        b3_t = Tex("Propene + HBr: which carbon gets what?").scale(1.1).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t))
        self.wait(2)
        b3_l1 = Tex("H joins the double-bond carbon that").scale(1.0).shift(band_shift(3) + UP * 1.2)
        b3_l2 = Tex("ALREADY holds more hydrogens").scale(1.0).shift(band_shift(3) + UP * 0.4)
        self.play(Write(b3_l1))
        self.wait(1.5)
        self.play(Write(b3_l2))
        self.wait(2)
        b3_l3 = Tex("C1 has two H, C2 has one: H joins C1,").scale(0.95).shift(band_shift(3) + DOWN * 0.5)
        b3_l4 = Tex("Br settles on C2: 2-bromopropane (major)").scale(0.95).shift(band_shift(3) + DOWN * 1.3)
        self.play(Write(b3_l3))
        self.wait(2)
        self.play(Write(b3_l4))
        self.play(Create(SurroundingRectangle(b3_l4, color=GREEN)))
        self.wait(2.5)
        b3_l5 = Tex("Hydration (dilute acid): propene mainly").scale(0.95).shift(band_shift(3) + DOWN * 2.3)
        b3_l6 = Tex("gives propan-2-ol — the rich get richer").scale(0.95).shift(band_shift(3) + DOWN * 3.0)
        self.play(Write(b3_l5))
        self.wait(1.5)
        self.play(Write(b3_l6))
        self.wait(3)

        # --- Band 4 (subtopic_3): elimination — dehydrohalogenation ---
        self.next_band(4)
        b4_t = Tex("Elimination: creating the double bond").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(2)
        b4_l1 = Tex("2-bromobutane + NaOH, but HOT,").scale(1.0).shift(band_shift(4) + UP * 1.2)
        b4_l2 = Tex("CONCENTRATED, in ETHANOL").scale(1.0).shift(band_shift(4) + UP * 0.4)
        self.play(Write(b4_l1))
        self.wait(1.5)
        self.play(Write(b4_l2))
        self.wait(2)
        b4_l3 = Tex("Br leaves C2; H leaves the neighbour").scale(0.95).shift(band_shift(4) + DOWN * 0.5)
        b4_l4 = Tex("with FEWER hydrogens — C3, not C1").scale(0.95).shift(band_shift(4) + DOWN * 1.3)
        self.play(Write(b4_l3))
        self.wait(2)
        self.play(Write(b4_l4))
        self.wait(2)
        b4_l5 = Tex("Major product: but-2-ene (more stable)").scale(1.0).shift(band_shift(4) + DOWN * 2.3)
        self.play(Write(b4_l5))
        self.play(Create(SurroundingRectangle(b4_l5, color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_3): dehydration and cracking ---
        self.next_band(5)
        b5_l1 = Tex("Dehydration: alcohol ejects water,").scale(1.0).shift(band_shift(5) + UP * 2.2)
        b5_l2 = Tex(r"excess conc. $H_2SO_4$, heated:").scale(1.0).shift(band_shift(5) + UP * 1.4)
        b5_l3 = Tex(r"ethanol $\rightarrow$ ethene + $H_2O$").scale(1.05).shift(band_shift(5) + UP * 0.5)
        self.play(Write(b5_l1))
        self.wait(1.5)
        self.play(Write(b5_l2))
        self.wait(1.5)
        self.play(Write(b5_l3))
        self.wait(2)
        b5_l4 = Tex("Cracking: long alkane, high T and p,").scale(1.0).shift(band_shift(5) + DOWN * 0.5)
        b5_l5 = Tex("gives shorter alkane + alkene").scale(1.0).shift(band_shift(5) + DOWN * 1.3)
        self.play(Write(b5_l4))
        self.wait(1.5)
        self.play(Write(b5_l5))
        self.wait(2)
        b5_l6 = Tex("Elimination's signature: ONE reactant,").scale(0.95).shift(band_shift(5) + DOWN * 2.2)
        b5_l7 = Tex("a double bond appears, harsh conditions").scale(0.95).shift(band_shift(5) + DOWN * 2.9)
        self.play(Write(b5_l6))
        self.wait(1.5)
        self.play(Write(b5_l7))
        self.wait(3)

        # --- Band 6 (subtopic_4): substitution ---
        self.next_band(6)
        b6_t = Tex("Substitution: the straight swap").scale(1.15).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_t))
        self.wait(2)
        b6_l1 = MathTex(r"CH_4 + Br_2 \xrightarrow{\text{light}} CH_3Br + HBr").scale(1.0).shift(band_shift(6) + UP * 1.2)
        self.play(Write(b6_l1))
        self.wait(2)
        b6_l2 = Tex("Both products count — the H leaves as HBr").scale(0.95).shift(band_shift(6) + UP * 0.3)
        self.play(Write(b6_l2))
        self.wait(2)
        b6_l3 = Tex("No light, no reaction: alkanes fade bromine").scale(0.95).shift(band_shift(6) + DOWN * 0.6)
        b6_l4 = Tex("slowly, in sunlight only — alkenes instantly").scale(0.95).shift(band_shift(6) + DOWN * 1.4)
        self.play(Write(b6_l3))
        self.wait(1.5)
        self.play(Write(b6_l4))
        self.wait(2)
        b6_l5 = Tex("Hydrolysis: 2-bromopropane + dilute NaOH").scale(0.95).shift(band_shift(6) + DOWN * 2.3)
        b6_l6 = Tex(r"$\rightarrow$ propan-2-ol — swap in place").scale(0.95).shift(band_shift(6) + DOWN * 3.1)
        self.play(Write(b6_l5))
        self.wait(1.5)
        self.play(Write(b6_l6))
        self.wait(3)

        # --- Band 7 (subtopic_4): the condition contrast ---
        self.next_band(7)
        b7_t = Tex("Same reagent, two fates").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(2)
        b7_l1 = Tex("2-bromobutane + NaOH:").scale(1.05).shift(band_shift(7) + UP * 1.2)
        self.play(Write(b7_l1))
        self.wait(1.5)
        b7_l2 = Tex("DILUTE, aqueous, warm: SUBSTITUTION").scale(1.0).shift(band_shift(7) + UP * 0.3)
        b7_l3 = Tex("— the alcohol forms").scale(1.0).shift(band_shift(7) + DOWN * 0.4)
        self.play(Write(b7_l2))
        self.wait(1.5)
        self.play(Write(b7_l3))
        self.wait(2)
        b7_l4 = Tex("CONCENTRATED, ethanolic, hot: ELIMINATION").scale(0.95).shift(band_shift(7) + DOWN * 1.3)
        b7_l5 = Tex("— the alkene forms").scale(1.0).shift(band_shift(7) + DOWN * 2.0)
        self.play(Write(b7_l4))
        self.wait(1.5)
        self.play(Write(b7_l5))
        self.wait(2)
        b7_l6 = Tex("Conditions are the verdict — learn the passwords").scale(0.9).shift(band_shift(7) + DOWN * 2.9)
        self.play(Write(b7_l6))
        self.play(Create(SurroundingRectangle(b7_l6, color=GREEN)))
        self.wait(3)

        # ===== Part 2 — Simplifier =====
        # --- Band 8 (subtopic_5): burning money, bottling fruit ---
        self.next_band(8)
        b8_t = Tex("Burning money and bottling fruit").scale(1.15).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_t))
        self.wait(2)
        b8_l1 = Tex("Combustion dismantles the skeleton entirely:").scale(0.95).shift(band_shift(8) + UP * 1.2)
        b8_l2 = Tex(r"every alkane burns to $CO_2$ + $H_2O$ + energy").scale(0.95).shift(band_shift(8) + UP * 0.4)
        self.play(Write(b8_l1))
        self.wait(2)
        self.play(Write(b8_l2))
        self.wait(2)
        b8_l3 = Tex("Count C, then H, oxygen adjusts last").scale(0.95).shift(band_shift(8) + DOWN * 0.5)
        self.play(Write(b8_l3))
        self.wait(2)
        b8_l4 = Tex("Esterification is matchmaking: acid + alcohol,").scale(0.95).shift(band_shift(8) + DOWN * 1.4)
        b8_l5 = Tex(r"conc. $H_2SO_4$, water as the confetti").scale(0.95).shift(band_shift(8) + DOWN * 2.2)
        self.play(Write(b8_l4))
        self.wait(1.5)
        self.play(Write(b8_l5))
        self.wait(2)
        b8_l6 = Tex("Pear drops and banana smells are esters").scale(0.95).shift(band_shift(8) + DOWN * 3.1)
        self.play(Write(b8_l6))
        self.wait(3)

        # --- Band 9 (subtopic_6): the molecule with open hands ---
        self.next_band(9)
        b9_t = Tex("The molecule with open hands").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(2)
        b9_l1 = Tex("Alkane: every hand gripped — inert").scale(1.0).shift(band_shift(9) + UP * 1.2)
        b9_l2 = Tex("Alkene: one spare hand per carbon — grabby").scale(0.95).shift(band_shift(9) + UP * 0.4)
        self.play(Write(b9_l1))
        self.wait(2)
        self.play(Write(b9_l2))
        self.wait(2)
        b9_l3 = Tex("Hydrogen + nickel: oil becomes margarine").scale(0.95).shift(band_shift(9) + DOWN * 0.5)
        b9_l4 = Tex("Bromine decolourised instantly: alkene!").scale(0.95).shift(band_shift(9) + DOWN * 1.3)
        self.play(Write(b9_l3))
        self.wait(2)
        self.play(Write(b9_l4))
        self.wait(2)
        b9_l5 = Tex("HBr must choose: the new H joins the carbon").scale(0.95).shift(band_shift(9) + DOWN * 2.2)
        b9_l6 = Tex("already richer in H — 2-bromopropane wins").scale(0.95).shift(band_shift(9) + DOWN * 2.9)
        self.play(Write(b9_l5))
        self.wait(1.5)
        self.play(Write(b9_l6))
        self.play(Create(SurroundingRectangle(b9_l6, color=GREEN)))
        self.wait(3)

        # --- Band 10 (subtopic_7): the dance floor rules ---
        self.next_band(10)
        b10_t = Tex("The dance floor rules").scale(1.2).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_t))
        self.wait(2)
        b10_l1 = Tex("Molecules do not choose the reaction —").scale(1.0).shift(band_shift(10) + UP * 1.2)
        b10_l2 = Tex("the CONDITIONS choose for them").scale(1.0).shift(band_shift(10) + UP * 0.4)
        self.play(Write(b10_l1))
        self.wait(1.5)
        self.play(Write(b10_l2))
        self.wait(2)
        b10_l3 = Tex("Dilute, watery, warm: the polite swap").scale(0.95).shift(band_shift(10) + DOWN * 0.5)
        b10_l4 = Tex("Concentrated, ethanolic, hot: the ejection").scale(0.95).shift(band_shift(10) + DOWN * 1.3)
        self.play(Write(b10_l3))
        self.wait(1.5)
        self.play(Write(b10_l4))
        self.wait(2)
        b10_l5 = Tex("Light on an alkane: substitution begins;").scale(0.95).shift(band_shift(10) + DOWN * 2.2)
        b10_l6 = Tex("no light, no reaction — read conditions FIRST").scale(0.95).shift(band_shift(10) + DOWN * 2.9)
        self.play(Write(b10_l5))
        self.wait(1.5)
        self.play(Write(b10_l6))
        self.play(Create(SurroundingRectangle(b10_l6, color=GREEN)))
        self.wait(4)
