from manim import *

# Band-layout whiteboard scene for the CAPS Grade 10 Term 4 revision duo
# "Year-End and Controls Essentials". One band per teaching beat; the camera
# moves down to fresh space and nothing is ever removed. Exporter-safe
# primitives only (Tex/MathTex/Line/SurroundingRectangle/VGroup); every line
# of working is its own single-string Tex/MathTex revealed with Write.
# Subtopic time shares (subtopics.json): 220/220/220/220/180/190/190 of 1440 s.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class YearEndAndControlsEssentialsSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): adjustments — the two depreciations ---
        title = Tex("Year-End and Controls Essentials").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex("Adjustments: matching — this year's").scale(1.1).shift(UP * 1.2)
        b0_l2 = Tex("income and expenses, no more, no less").scale(1.1).shift(UP * 0.5)
        self.play(Write(b0_l1))
        self.play(Write(b0_l2))
        self.wait(2)
        b0_l3 = Tex(r"Vehicle: R40 000 $\times$ 20\% = R8 000").scale(1.1).shift(DOWN * 0.5)
        self.play(Write(b0_l3))
        self.wait(2)
        b0_l4 = Tex(r"Equipment: 10\% $\times$ (10 000 $-$ 1 000)").scale(1.1).shift(DOWN * 1.3)
        b0_l5 = Tex(r"= 10\% $\times$ R9 000 = R900").scale(1.1).shift(DOWN * 2.1)
        self.play(Write(b0_l4))
        self.wait(2)
        self.play(Write(b0_l5))
        self.wait(1.5)
        b0_l6 = Tex("Total depreciation: R8 900").scale(1.1).shift(DOWN * 2.9)
        self.play(Write(b0_l6))
        self.play(Create(SurroundingRectangle(b0_l6, color=GREEN)))
        self.wait(3)

        # --- Band 1 (subtopic_1): the three timing repairs ---
        self.next_band(1)
        b1_title = Tex("The timing repairs").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l1 = Tex(r"Accrued expense: W\&E 2 400 + 400 = R2 800").scale(1.05).shift(band_shift(1) + UP * 1.1)
        b1_l2 = Tex("R400 unpaid = current liability").scale(1.05).shift(band_shift(1) + UP * 0.3)
        self.play(Write(b1_l1))
        self.wait(2)
        self.play(Write(b1_l2))
        self.wait(2)
        b1_l3 = Tex(r"Prepaid expense: insurance 1 800 $-$ 300 = R1 500").scale(1.0).shift(band_shift(1) + DOWN * 0.6)
        b1_l4 = Tex("R300 paid ahead = current asset").scale(1.05).shift(band_shift(1) + DOWN * 1.4)
        self.play(Write(b1_l3))
        self.wait(2)
        self.play(Write(b1_l4))
        self.wait(2)
        b1_l5 = Tex("Accrued income: rent 5 500 + 500 = R6 000").scale(1.05).shift(band_shift(1) + DOWN * 2.2)
        b1_l6 = Tex("R500 outstanding = current asset").scale(1.05).shift(band_shift(1) + DOWN * 3.0)
        self.play(Write(b1_l5))
        self.wait(2)
        self.play(Write(b1_l6))
        self.wait(3)

        # --- Band 2 (subtopic_2): trading account and profit and loss ---
        self.next_band(2)
        b2_title = Tex("Final accounts: Trading, then Profit and Loss").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(1.5)
        b2_l1 = Tex(r"Sales 120 000 $-$ Cost of sales 80 000").scale(1.1).shift(band_shift(2) + UP * 1.1)
        b2_l2 = Tex(r"Gross profit R40 000 \; (80 000 $\times$ 1,5)").scale(1.1).shift(band_shift(2) + UP * 0.3)
        self.play(Write(b2_l1))
        self.wait(2)
        self.play(Write(b2_l2))
        self.wait(2)
        b2_l3 = Tex("+ Rent income 6 000").scale(1.1).shift(band_shift(2) + DOWN * 0.5)
        self.play(Write(b2_l3))
        self.wait(1.5)
        b2_l4 = Tex(r"$-$ Expenses 31 200: wages 18 000,").scale(1.05).shift(band_shift(2) + DOWN * 1.3)
        b2_l5 = Tex(r"W\&E 2 800, insurance 1 500, depr 8 900").scale(1.05).shift(band_shift(2) + DOWN * 2.1)
        self.play(Write(b2_l4))
        self.play(Write(b2_l5))
        self.wait(2.5)
        b2_l6 = Tex(r"Net profit = 40 000 + 6 000 $-$ 31 200 = R14 800").scale(1.05).shift(band_shift(2) + DOWN * 2.9)
        self.play(Write(b2_l6))
        self.play(Create(SurroundingRectangle(b2_l6, color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_2): statement of financial position balances ---
        self.next_band(3)
        b3_title = Tex("Statement of Financial Position").scale(1.15).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(1.5)
        b3_l1 = Tex("Non-current assets (carrying value) 70 300").scale(1.05).shift(band_shift(3) + UP * 1.2)
        self.play(Write(b3_l1))
        self.wait(2)
        b3_l2 = Tex("Current assets 15 400: stock 8 000,").scale(1.0).shift(band_shift(3) + UP * 0.4)
        b3_l3 = Tex("debtors 4 500, bank 2 100, 300 + 500").scale(1.0).shift(band_shift(3) + DOWN * 0.3)
        self.play(Write(b3_l2))
        self.play(Write(b3_l3))
        self.wait(2)
        b3_line = Line(band_shift(3) + DOWN * 0.75 + LEFT * 3.2,
                       band_shift(3) + DOWN * 0.75 + RIGHT * 3.2, stroke_width=3)
        b3_l4 = Tex("Total assets R85 700").scale(1.1).shift(band_shift(3) + DOWN * 1.2)
        self.play(Create(b3_line))
        self.play(Write(b3_l4))
        self.wait(2)
        b3_l5 = Tex(r"Equity: 70 000 + 14 800 $-$ 6 800 = 78 000").scale(1.0).shift(band_shift(3) + DOWN * 2.0)
        b3_l6 = Tex("+ Current liabilities 7 700 = R85 700").scale(1.05).shift(band_shift(3) + DOWN * 2.8)
        self.play(Write(b3_l5))
        self.wait(2)
        self.play(Write(b3_l6))
        self.play(Create(SurroundingRectangle(b3_l6, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): profitability gauges ---
        self.next_band(4)
        b4_title = Tex("The gauges: profitability").scale(1.2).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(1.5)
        b4_l1 = MathTex(r"\text{GP on cost: } \frac{40\,000}{80\,000} = 50\%").scale(1.1).shift(band_shift(4) + UP * 0.9)
        self.play(Write(b4_l1))
        self.wait(2)
        b4_l2 = Tex("= the mark-up policy: no stock leaked").scale(1.0).shift(band_shift(4) + UP * 0.0)
        self.play(Write(b4_l2))
        self.wait(2)
        b4_l3 = MathTex(r"\text{GP on sales: } \frac{40\,000}{120\,000} = 33{,}3\%").scale(1.1).shift(band_shift(4) + DOWN * 1.0)
        self.play(Write(b4_l3))
        self.wait(2)
        b4_l4 = MathTex(r"\text{NP on sales: } \frac{14\,800}{120\,000} = 12{,}3\%").scale(1.1).shift(band_shift(4) + DOWN * 2.2)
        self.play(Write(b4_l4))
        self.play(Create(SurroundingRectangle(b4_l4, color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_3): liquidity, solvency, return ---
        self.next_band(5)
        b5_title = Tex("Liquidity, solvency, return").scale(1.2).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(1.5)
        b5_l1 = Tex("Current ratio: 15 400 : 7 700 = 2 : 1").scale(1.1).shift(band_shift(5) + UP * 1.1)
        self.play(Write(b5_l1))
        self.wait(2)
        b5_l2 = Tex("Acid test: 7 400 : 7 700 = 0,96 : 1").scale(1.1).shift(band_shift(5) + UP * 0.3)
        self.play(Write(b5_l2))
        self.wait(2)
        b5_l3 = Tex("Solvency: 85 700 vs 7 700 — 11 times over").scale(1.05).shift(band_shift(5) + DOWN * 0.5)
        self.play(Write(b5_l3))
        self.wait(2)
        b5_l4 = MathTex(r"\text{ROE: } \frac{14\,800}{74\,000} = 20\%").scale(1.1).shift(band_shift(5) + DOWN * 1.5)
        self.play(Write(b5_l4))
        self.play(Create(SurroundingRectangle(b5_l4, color=GREEN)))
        self.wait(2)
        b5_l5 = Tex("Comment = figure, comparison, judgement").scale(1.05).shift(band_shift(5) + DOWN * 2.7)
        self.play(Write(b5_l5))
        self.wait(3)

        # --- Band 6 (subtopic_4): guards and rules ---
        self.next_band(6)
        b6_title = Tex("Guards: control, ethics, GAAP").scale(1.2).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(1.5)
        b6_l1 = Tex("Control: divide duties, documents,").scale(1.05).shift(band_shift(6) + UP * 1.1)
        b6_l2 = Tex("authorisation, safeguards, checks").scale(1.05).shift(band_shift(6) + UP * 0.3)
        self.play(Write(b6_l1))
        self.play(Write(b6_l2))
        self.wait(2.5)
        b6_l3 = Tex("Ethics: integrity, objectivity,").scale(1.05).shift(band_shift(6) + DOWN * 0.5)
        b6_l4 = Tex("confidentiality, competence").scale(1.05).shift(band_shift(6) + DOWN * 1.3)
        self.play(Write(b6_l3))
        self.play(Write(b6_l4))
        self.wait(2.5)
        b6_l5 = Tex("GAAP: cost, prudence, matching,").scale(1.05).shift(band_shift(6) + DOWN * 2.1)
        b6_l6 = Tex("going concern, entity, materiality").scale(1.05).shift(band_shift(6) + DOWN * 2.9)
        self.play(Write(b6_l5))
        self.play(Write(b6_l6))
        self.wait(3)

        # --- Band 7 (subtopic_4): unit cost and the budget ---
        self.next_band(7)
        b7_title = Tex("Cost of one unit, and the budget").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(1.5)
        b7_l1 = Tex("Materials 6 000 + Labour 4 000 = prime 10 000").scale(1.0).shift(band_shift(7) + UP * 1.1)
        self.play(Write(b7_l1))
        self.wait(2)
        b7_l2 = Tex("+ Overheads 2 000 = total R12 000").scale(1.05).shift(band_shift(7) + UP * 0.3)
        self.play(Write(b7_l2))
        self.wait(2)
        b7_l3 = MathTex(r"\frac{12\,000}{1\,000} = R12 \text{ each; sell R15} \Rightarrow R3").scale(0.89).shift(band_shift(7) + DOWN * 0.7)
        self.play(Write(b7_l3))
        self.play(Create(SurroundingRectangle(b7_l3, color=GREEN)))
        self.wait(2.5)
        b7_l4 = Tex(r"Budget: receipts 9 000 $-$ payments 7 500").scale(1.0).shift(band_shift(7) + DOWN * 1.7)
        b7_l5 = Tex("surplus 1 500 + opening 1 000 = R2 500").scale(1.0).shift(band_shift(7) + DOWN * 2.5)
        self.play(Write(b7_l4))
        self.wait(2)
        self.play(Write(b7_l5))
        self.play(Create(SurroundingRectangle(b7_l5, color=GREEN)))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): tidying the room before the photo ---
        self.next_band(8)
        b8_title = Tex("Tidying the room before the photo").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = Tex("Bakkie wearing out: R8 900 of honesty").scale(1.05).shift(band_shift(8) + UP * 1.1)
        self.play(Write(b8_l1))
        self.wait(2.5)
        b8_l2 = Tex("February's electricity: pull in R400").scale(1.05).shift(band_shift(8) + UP * 0.3)
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = Tex("Insurance paid ahead: push out R300").scale(1.05).shift(band_shift(8) + DOWN * 0.5)
        self.play(Write(b8_l3))
        self.wait(2.5)
        b8_l4 = Tex("Rent earned, not received: pull in R500").scale(1.05).shift(band_shift(8) + DOWN * 1.3)
        self.play(Write(b8_l4))
        self.wait(2.5)
        b8_l5 = Tex("Skip depreciation: shop looks richer").scale(1.05).shift(band_shift(8) + DOWN * 2.2)
        self.play(Write(b8_l5))
        self.play(Create(strike(b8_l5)))
        self.wait(2)
        b8_l6 = Tex("The photo must show the TRUE year").scale(1.05).shift(band_shift(8) + DOWN * 3.0)
        self.play(Write(b8_l6))
        self.wait(3)

        # --- Band 9 (subtopic_6): report card and health check ---
        self.next_band(9)
        b9_title = Tex("The report card and the health check").scale(1.15).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex("Top floor: buy 80, sell 120 — R40 000").scale(1.05).shift(band_shift(9) + UP * 1.1)
        self.play(Write(b9_l1))
        self.wait(2.5)
        b9_l2 = Tex("Middle floor: + tenant's rent R6 000").scale(1.05).shift(band_shift(9) + UP * 0.3)
        self.play(Write(b9_l2))
        self.wait(2.5)
        b9_l3 = Tex(r"Bottom floor: $-$ R31 200 to stay open").scale(1.05).shift(band_shift(9) + DOWN * 0.5)
        self.play(Write(b9_l3))
        self.wait(2.5)
        b9_l4 = Tex("The year's true mark: R14 800").scale(1.1).shift(band_shift(9) + DOWN * 1.4)
        self.play(Write(b9_l4))
        self.play(Create(SurroundingRectangle(b9_l4, color=GREEN)))
        self.wait(2.5)
        b9_l5 = Tex("Health: 2 : 1 ready; 0,96 without stock;").scale(1.0).shift(band_shift(9) + DOWN * 2.3)
        b9_l6 = Tex("debts covered 11 times; R20 per R100 earned").scale(1.0).shift(band_shift(9) + DOWN * 3.0)
        self.play(Write(b9_l5))
        self.wait(2)
        self.play(Write(b9_l6))
        self.wait(3)

        # --- Band 10 (subtopic_7): locks and the vetkoek ---
        self.next_band(10)
        b10_title = Tex("Locks on the doors, one vetkoek costed").scale(1.15).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_title))
        self.wait(2)
        b10_l1 = Tex("One hand end to end = an invitation").scale(1.05).shift(band_shift(10) + UP * 1.1)
        self.play(Write(b10_l1))
        self.play(Create(strike(b10_l1)))
        self.wait(2)
        b10_l2 = Tex("Split the jobs, slip every movement,").scale(1.05).shift(band_shift(10) + UP * 0.2)
        b10_l3 = Tex("second nod, count by a non-seller").scale(1.05).shift(band_shift(10) + DOWN * 0.6)
        self.play(Write(b10_l2))
        self.play(Write(b10_l3))
        self.wait(2.5)
        b10_l4 = Tex("Vetkoek: 6 000 + 4 000 + 2 000 = 12 000").scale(1.0).shift(band_shift(10) + DOWN * 1.4)
        self.play(Write(b10_l4))
        self.wait(2.5)
        b10_l5 = Tex(r"12 000 $\div$ 1 000 = R12; sell R15 = R3 home").scale(1.0).shift(band_shift(10) + DOWN * 2.2)
        self.play(Write(b10_l5))
        self.play(Create(SurroundingRectangle(b10_l5, color=GREEN)))
        self.wait(2.5)
        b10_l6 = Tex("Write the month first: purse ends R2 500").scale(1.0).shift(band_shift(10) + DOWN * 3.0)
        self.play(Write(b10_l6))
        self.wait(4)
