from manim import *

# Band-layout whiteboard scene for "Economic Redress and Democratisation"
# (Part 1 — Expert subtopics 1-4, Part 2 — Simplifier subtopics 5-7).
# Exporter-safe primitives only; add-only lifecycle.
# Subtopic durations: 220/240/220/230/190/200/190 of 1490 s.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class EconomicRedressDemocratisationSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        self.wait(14)

        # ===================== Part 1 — Expert =====================
        # --- Band 0 (subtopic_1): the marginalised groups ---
        title = Tex("Economic Redress and Democratisation").scale(1.25).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0a = Tex("Marginalised: pushed to the edge of economic life").scale(1.05).shift(UP * 1.2)
        b0a2 = Tex("— by legislation, not by chance").scale(1.05).shift(UP * 0.5)
        self.play(Write(b0a))
        self.play(Write(b0a2))
        self.wait(2)
        b0b = Tex("Black South Africans $\\cdot$ women $\\cdot$ rural communities").scale(0.91).shift(DOWN * 0.4)
        b0c = Tex("people with disabilities $\\cdot$ youth").scale(1.0).shift(DOWN * 1.1)
        self.play(Write(b0b))
        self.wait(2)
        self.play(Write(b0c))
        self.wait(2)
        b0d = Tex("Redress: deliberate correction of past injustice").scale(1.05).shift(DOWN * 2.1)
        self.play(Write(b0d))
        self.play(Create(SurroundingRectangle(b0d, color=GREEN)))
        self.wait(3)

        # --- Band 1 (subtopic_1): mechanisms and compounding ---
        self.next_band(1)
        b1t = Tex("Name the MECHANISM of exclusion").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1t))
        self.wait(2)
        b1a = Tex("Land dispossessed by law; unequal education;").scale(1.0).shift(band_shift(1) + UP * 1.1)
        b1a2 = Tex("low-wage migrant labour channels").scale(1.0).shift(band_shift(1) + UP * 0.4)
        self.play(Write(b1a))
        self.play(Write(b1a2))
        self.wait(2)
        b1b = Tex("Women: barred from property, credit, occupations;").scale(0.95).shift(band_shift(1) + DOWN * 0.4)
        b1b2 = Tex("unpaid care work constrains participation").scale(0.95).shift(band_shift(1) + DOWN * 1.1)
        self.play(Write(b1b))
        self.play(Write(b1b2))
        self.wait(2)
        b1c = Tex("Rural areas starved of infrastructure; youth inherit").scale(0.95).shift(band_shift(1) + DOWN * 1.9)
        self.play(Write(b1c))
        self.wait(2)
        b1d = Tex("Overlaps COMPOUND: one multiplied exclusion").scale(1.05).shift(band_shift(1) + DOWN * 2.8)
        self.play(Write(b1d))
        self.play(Create(SurroundingRectangle(b1d, color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): natural resources — land reform ---
        self.next_band(2)
        b2t = Tex("Redress via factors: natural resources (land)").scale(1.1).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2t))
        self.wait(2)
        r2a = Rectangle(width=3.6, height=1.0).shift(band_shift(2) + UP * 0.9 + LEFT * 4.6)
        t2a = Tex("Restitution").scale(0.9).move_to(r2a.get_center())
        d2a = Tex("return or compensate post-1913 dispossession").scale(0.9).shift(band_shift(2) + UP * 0.9 + RIGHT * 2.2)
        self.play(Create(r2a), Write(t2a))
        self.play(Write(d2a))
        self.wait(2)
        r2b = Rectangle(width=3.6, height=1.0).shift(band_shift(2) + DOWN * 0.3 + LEFT * 4.6)
        t2b = Tex("Redistribution").scale(0.9).move_to(r2b.get_center())
        d2b = Tex("transfer land to those denied access").scale(0.9).shift(band_shift(2) + DOWN * 0.3 + RIGHT * 2.0)
        self.play(Create(r2b), Write(t2b))
        self.play(Write(d2b))
        self.wait(2)
        r2c = Rectangle(width=3.6, height=1.0).shift(band_shift(2) + DOWN * 1.5 + LEFT * 4.6)
        t2c = Tex("Tenure reform").scale(0.9).move_to(r2c.get_center())
        d2c = Tex("secure legally insecure occupation").scale(0.9).shift(band_shift(2) + DOWN * 1.5 + RIGHT * 1.9)
        self.play(Create(r2c), Write(t2c))
        self.play(Write(d2c))
        self.wait(2)
        b2e = Tex("Title deed needs finance, training, market access").scale(1.0).shift(band_shift(2) + DOWN * 2.7)
        self.play(Write(b2e))
        self.play(Create(SurroundingRectangle(b2e, color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_2): labour, capital, entrepreneurship ---
        self.next_band(3)
        b3t = Tex("Labour, capital, entrepreneurship").scale(1.2).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3t))
        self.wait(2)
        b3a = Tex("Labour: employment equity to management level;").scale(1.0).shift(band_shift(3) + UP * 1.1)
        b3a2 = Tex("skills levies, learnerships, apprenticeships").scale(1.0).shift(band_shift(3) + UP * 0.4)
        self.play(Write(b3a))
        self.play(Write(b3a2))
        self.wait(2.5)
        b3b = Tex("Capital: B-BBEE ownership, procurement;").scale(1.0).shift(band_shift(3) + DOWN * 0.5)
        b3b2 = Tex("development finance for the credit-excluded").scale(1.0).shift(band_shift(3) + DOWN * 1.2)
        self.play(Write(b3b))
        self.play(Write(b3b2))
        self.wait(2.5)
        b3c = Tex("Entrepreneurship: incubation, set-asides, support").scale(1.0).shift(band_shift(3) + DOWN * 2.0)
        self.play(Write(b3c))
        self.wait(2)
        b3d = Tex("Ask: denied what? instrument? support needed?").scale(1.0).shift(band_shift(3) + DOWN * 2.9)
        self.play(Write(b3d))
        self.play(Create(SurroundingRectangle(b3d, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): democratising decisions — the channels ---
        self.next_band(4)
        b4t = Tex("Democratising economic decisions").scale(1.2).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4t))
        self.wait(2)
        b4a = Tex("Labour law: workers become PARTIES to decisions").scale(1.0).shift(band_shift(4) + UP * 1.1)
        self.play(Write(b4a))
        self.wait(2)
        b4b = Tex("Public hearings: parliamentary submissions,").scale(1.0).shift(band_shift(4) + UP * 0.3)
        b4b2 = Tex("municipal IDPs, regulators' hearings").scale(1.0).shift(band_shift(4) + DOWN * 0.4)
        self.play(Write(b4b))
        self.play(Write(b4b2))
        self.wait(2)
        b4c = Tex("Self-regulating bodies: practitioners set standards").scale(0.95).shift(band_shift(4) + DOWN * 1.3)
        self.play(Write(b4c))
        self.wait(2)
        b4d = Tex("Those affected get a channel into the decision").scale(1.05).shift(band_shift(4) + DOWN * 2.3)
        self.play(Write(b4d))
        self.play(Create(SurroundingRectangle(b4d, color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_3): NEDLAC — four chairs at one table ---
        self.next_band(5)
        b5t = Tex("NEDLAC: four constituencies, one table").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5t))
        self.wait(2)
        table = Rectangle(width=3.6, height=1.2).shift(band_shift(5) + DOWN * 0.2)
        t_tab = Tex("NEDLAC").scale(0.9).move_to(table.get_center())
        self.play(Create(table), Write(t_tab))
        self.wait(1.5)
        c1 = Tex("Government").scale(0.85).shift(band_shift(5) + UP * 1.2 + LEFT * 4.2)
        c2 = Tex("Business").scale(0.85).shift(band_shift(5) + UP * 1.2 + RIGHT * 4.2)
        c3 = Tex("Labour").scale(0.85).shift(band_shift(5) + DOWN * 1.7 + LEFT * 4.2)
        c4 = Tex("Community").scale(0.85).shift(band_shift(5) + DOWN * 1.7 + RIGHT * 4.2)
        a1 = Arrow(c1.get_right(), table.get_corner(UL), buff=0.15)
        a2 = Arrow(c2.get_left(), table.get_corner(UR), buff=0.15)
        a3 = Arrow(c3.get_right(), table.get_corner(DL), buff=0.15)
        a4 = Arrow(c4.get_left(), table.get_corner(DR), buff=0.15)
        self.play(Write(c1), Create(a1))
        self.play(Write(c2), Create(a2))
        self.play(Write(c3), Create(a3))
        self.play(Write(c4), Create(a4))
        self.wait(2)
        b5a = Tex("Policy negotiated BEFORE Parliament — consensus").scale(0.95).shift(band_shift(5) + DOWN * 2.6)
        self.play(Write(b5a))
        self.wait(2)
        b5b = Tex("Limit: slow; weakly organised voices under-heard").scale(0.9).shift(band_shift(5) + DOWN * 3.3)
        self.play(Write(b5b))
        self.wait(3)

        # --- Band 6 (subtopic_4): macro-economic aims and their tension ---
        self.next_band(6)
        b6t = Tex("Macro-economic aims — and their tension").scale(1.15).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6t))
        self.wait(2)
        b6a = Tex("Growth $\\cdot$ employment $\\cdot$ equitable distribution").scale(1.0).shift(band_shift(6) + UP * 1.1)
        b6b = Tex("stability $\\cdot$ external balance").scale(1.0).shift(band_shift(6) + UP * 0.4)
        self.play(Write(b6a))
        self.play(Write(b6b))
        self.wait(2.5)
        b6c = Tex("Redistribution needs revenue, revenue needs growth;").scale(0.95).shift(band_shift(6) + DOWN * 0.5)
        b6d = Tex("stability constrains borrowing for social spending").scale(0.95).shift(band_shift(6) + DOWN * 1.2)
        self.play(Write(b6c))
        self.play(Write(b6d))
        self.wait(2.5)
        b6e = Tex("Policy is the balancing of aims that pull apart").scale(1.05).shift(band_shift(6) + DOWN * 2.2)
        self.play(Write(b6e))
        self.play(Create(SurroundingRectangle(b6e, color=GREEN)))
        self.wait(3)

        # --- Band 7 (subtopic_4): judging redress on both ledgers ---
        self.next_band(7)
        b7t = Tex("Judge redress on BOTH ledgers").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7t))
        self.wait(2)
        b7a = Tex("Achievements: services, housing, grants expanded;").scale(0.95).shift(band_shift(7) + UP * 1.1)
        b7a2 = Tex("Black middle class; law and institutions built").scale(0.95).shift(band_shift(7) + UP * 0.4)
        self.play(Write(b7a))
        self.play(Write(b7a2))
        self.wait(2.5)
        b7b = Tex("Shortfalls: unemployment high; severe inequality;").scale(0.95).shift(band_shift(7) + DOWN * 0.5)
        b7b2 = Tex("land reform slow; benefits sometimes narrow").scale(0.95).shift(band_shift(7) + DOWN * 1.2)
        self.play(Write(b7b))
        self.play(Write(b7b2))
        self.wait(2.5)
        b7c = Tex("State both, name mechanisms, not slogans").scale(1.05).shift(band_shift(7) + DOWN * 2.2)
        self.play(Write(b7c))
        self.play(Create(SurroundingRectangle(b7c, color=GREEN)))
        self.wait(3)

        # ===================== Part 2 — Simplifier =====================
        # --- Band 8 (subtopic_5): starting the race at different lines ---
        self.next_band(8)
        b8t = Tex("Starting the race at different lines").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8t))
        self.wait(2)
        b8a = Tex("Same exam, different starting lines —").scale(1.05).shift(band_shift(8) + UP * 1.1)
        b8a2 = Tex("drawn by law: land, address, school, job").scale(1.05).shift(band_shift(8) + UP * 0.4)
        self.play(Write(b8a))
        self.play(Write(b8a2))
        self.wait(2.5)
        b8wrong = Tex("Repealing the laws restored equality").scale(1.05).shift(band_shift(8) + DOWN * 0.5)
        self.play(Write(b8wrong))
        self.play(Create(strike(b8wrong)))
        self.wait(2)
        b8b = Tex("Disadvantage is inherited: assets, education,").scale(1.0).shift(band_shift(8) + DOWN * 1.4)
        b8b2 = Tex("networks, address").scale(1.0).shift(band_shift(8) + DOWN * 2.1)
        self.play(Write(b8b))
        self.play(Write(b8b2))
        self.wait(2)
        b8c = Tex("Equal law $\\neq$ equal economy — redress closes the gap").scale(0.95).shift(band_shift(8) + DOWN * 3.0)
        self.play(Write(b8c))
        self.play(Create(SurroundingRectangle(b8c, color=GREEN)))
        self.wait(3)

        # --- Band 9 (subtopic_6): four things to build a livelihood ---
        self.next_band(9)
        b9t = Tex("Four things you need to build a livelihood").scale(1.15).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9t))
        self.wait(2)
        b9a = Tex("LAND: back, or access, or secure — plus support;").scale(1.0).shift(band_shift(9) + UP * 1.1)
        b9a2 = Tex("land alone is a field, not a farm").scale(1.0).shift(band_shift(9) + UP * 0.4)
        self.play(Write(b9a))
        self.play(Write(b9a2))
        self.wait(2.5)
        b9b = Tex("SKILLS AND WORK: equity to management; training").scale(0.95).shift(band_shift(9) + DOWN * 0.4)
        self.play(Write(b9b))
        self.wait(2)
        b9c = Tex("MONEY: ownership, procurement, credit access").scale(0.95).shift(band_shift(9) + DOWN * 1.2)
        self.play(Write(b9c))
        self.wait(2)
        b9d = Tex("THE CHANCE TO BUILD: incubators, set-asides").scale(0.95).shift(band_shift(9) + DOWN * 2.0)
        self.play(Write(b9d))
        self.wait(2)
        b9e = Tex("Test: a THING handed over, or a LIVELIHOOD built?").scale(1.0).shift(band_shift(9) + DOWN * 2.9)
        self.play(Write(b9e))
        self.play(Create(SurroundingRectangle(b9e, color=GREEN)))
        self.wait(3)

        # --- Band 10 (subtopic_7): who sits at the table ---
        self.next_band(10)
        b10t = Tex("Who sits at the table").scale(1.2).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10t))
        self.wait(2)
        b10a = Tex("Unions opposite management; hearings for the public;").scale(0.95).shift(band_shift(10) + UP * 1.1)
        b10a2 = Tex("professions policing their own standards").scale(0.95).shift(band_shift(10) + UP * 0.4)
        self.play(Write(b10a))
        self.play(Write(b10a2))
        self.wait(2.5)
        b10b = Tex("NEDLAC's four chairs: government, business,").scale(1.0).shift(band_shift(10) + DOWN * 0.5)
        b10b2 = Tex("labour, community — laws argued before Parliament").scale(1.0).shift(band_shift(10) + DOWN * 1.2)
        self.play(Write(b10b))
        self.play(Write(b10b2))
        self.wait(2.5)
        b10c = Tex("Judge with both columns: real gains, real shortfalls").scale(0.95).shift(band_shift(10) + DOWN * 2.1)
        self.play(Write(b10c))
        self.wait(2)
        b10d = Tex("Say both, with the mechanisms attached").scale(1.05).shift(band_shift(10) + DOWN * 3.0)
        self.play(Write(b10d))
        self.play(Create(SurroundingRectangle(b10d, color=GREEN)))
        self.wait(4)
