from manim import *

# Band-layout whiteboard scene for the urban-settlements duo
# (urbanisation, hierarchy and land-use zones). Exporter-safe primitives
# only (Tex/MathTex/Line/Arrow/Dot/Circle/Rectangle/VGroup); add-only
# lifecycle; camera moves down one frame-height per band. The hierarchy
# pyramid and the cross-city zone strip are hand-built Rectangle diagrams
# labelled as they grow, in script order.
#
# Subtopic shares (subtopics.json, total 1660 s):
# 225/215/260/280 expert, 210/230/240 simplifier. Part 1 gets bands 0-8
# (subtopic_4 carries three bands for its 280 s), Part 2 gets fresh
# bands 9-11.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class UrbanisationLandUseSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md plays.
        self.wait(15)

        # ===== Part 1 — Expert =====
        # --- Band 0 (subtopic_1): the birth of towns ---
        title = Tex("From First Villages to an Urban World").scale(1.25).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        r1 = MathTex(r"\text{surplus} + \text{specialisation} + \text{exchange} = \text{a town}").scale(1.0).shift(UP * 1.0)
        self.play(Write(r1))
        self.play(Create(SurroundingRectangle(r1, color=GREEN)))
        self.wait(2.5)
        r2 = Tex(r"Extra food frees traders, craftsmen, rulers").scale(1.0).shift(DOWN * 0.2)
        self.play(Write(r2))
        self.wait(2)
        r3 = Tex(r"First cities: irrigated river valleys —").scale(1.0).shift(DOWN * 1.1)
        r3b = Tex(r"Nile, Tigris-Euphrates, Indus").scale(1.0).shift(DOWN * 1.9)
        self.play(Write(r3))
        self.play(Write(r3b))
        self.wait(2.5)
        r4 = Tex(r"Defensible, well-watered crossing points").scale(0.95).shift(DOWN * 2.8)
        self.play(Write(r4))
        self.wait(3)

        # --- Band 1 (subtopic_1): the industrial gradient + level vs rate ---
        self.next_band(1)
        b1_t = Tex("Factories tipped the world urban").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_t))
        self.wait(1.5)
        f1 = Tex(r"Industrial revolution: factories concentrate").scale(1.0).shift(band_shift(1) + UP * 1.2)
        f1b = Tex(r"work in towns — towns explode").scale(1.0).shift(band_shift(1) + UP * 0.4)
        self.play(Write(f1))
        self.play(Write(f1b))
        self.wait(2.5)
        f2 = Tex(r"Early 2000s: over half of humanity urban").scale(1.0).shift(band_shift(1) + DOWN * 0.5)
        self.play(Write(f2))
        self.wait(2)
        f3 = Tex(r"Developed: HIGH level, slow rate").scale(1.0).shift(band_shift(1) + DOWN * 1.4)
        f4 = Tex(r"Developing: lower level, FAST rate").scale(1.0).shift(band_shift(1) + DOWN * 2.2)
        self.play(Write(f3))
        self.wait(2)
        self.play(Write(f4))
        self.play(Create(SurroundingRectangle(f4, color=GREEN)))
        self.wait(2)
        f5 = Tex(r"SA: about two thirds urban, Gauteng the magnet").scale(0.95).shift(band_shift(1) + DOWN * 3.1)
        self.play(Write(f5))
        self.wait(3)

        # --- Band 2 (subtopic_2): urbanisation vs growth, rate vs level ---
        self.next_band(2)
        b2_t = Tex("Vocabulary: the near-twins, part 1").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(1.5)
        v1 = Tex(r"Urbanisation: rising PERCENTAGE urban").scale(1.0).shift(band_shift(2) + UP * 1.2)
        v2 = Tex(r"Urban growth: rising NUMBER of people").scale(1.0).shift(band_shift(2) + UP * 0.4)
        self.play(Write(v1))
        self.wait(2)
        self.play(Write(v2))
        self.wait(2)
        v3 = Tex(r"Same pace in town and country: growth,").scale(0.95).shift(band_shift(2) + DOWN * 0.5)
        v3b = Tex(r"yes — urbanisation, no").scale(0.95).shift(band_shift(2) + DOWN * 1.3)
        self.play(Write(v3))
        self.play(Write(v3b))
        self.wait(2.5)
        v4 = Tex(r"Rate = the SPEED of the rise;").scale(1.0).shift(band_shift(2) + DOWN * 2.2)
        v4b = Tex(r"level = the snapshot percentage").scale(1.0).shift(band_shift(2) + DOWN * 3.0)
        self.play(Write(v4))
        self.play(Write(v4b))
        self.play(Create(SurroundingRectangle(v4b, color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_2): expansion, sprawl, counter-urbanisation ---
        self.next_band(3)
        b3_t = Tex("Vocabulary: the near-twins, part 2").scale(1.15).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t))
        self.wait(1.5)
        x1 = Tex(r"Urban expansion: built-up area spreads outward").scale(0.95).shift(band_shift(3) + UP * 1.2)
        x2 = Tex(r"Urban sprawl: LOW-density, poorly planned").scale(0.95).shift(band_shift(3) + UP * 0.4)
        x2b = Tex(r"spread leapfrogging along highways").scale(0.95).shift(band_shift(3) + DOWN * 0.4)
        self.play(Write(x1))
        self.wait(2)
        self.play(Write(x2))
        self.play(Write(x2b))
        self.wait(2.5)
        x3 = Tex(r"All sprawl is expansion; not all expansion").scale(0.95).shift(band_shift(3) + DOWN * 1.3)
        x3b = Tex(r"is sprawl").scale(0.95).shift(band_shift(3) + DOWN * 2.1)
        self.play(Write(x3))
        self.play(Write(x3b))
        self.play(Create(SurroundingRectangle(x3b, color=GREEN)))
        self.wait(2.5)
        x4 = Tex(r"Counter-urbanisation: city $\rightarrow$ small town,").scale(0.95).shift(band_shift(3) + DOWN * 2.8)
        x4b = Tex(r"chasing quality of life (Cape coastal towns)").scale(0.95).shift(band_shift(3) + DOWN * 3.4)
        self.play(Write(x4))
        self.play(Write(x4b))
        self.wait(3)

        # --- Band 4 (subtopic_3): site vs situation — the great pair ---
        self.next_band(4)
        b4_t = Tex("Site, situation, and which one won").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(1.5)
        s1 = Tex(r"Cape Town: good SITE — sheltered ground,").scale(1.0).shift(band_shift(4) + UP * 1.2)
        s1b = Tex(r"fresh water, a natural bay").scale(1.0).shift(band_shift(4) + UP * 0.4)
        self.play(Write(s1))
        self.play(Write(s1b))
        self.wait(2.5)
        s2 = Tex(r"Johannesburg: poor site — no harbour,").scale(1.0).shift(band_shift(4) + DOWN * 0.5)
        s2b = Tex(r"no river — but SITUATION on the gold").scale(1.0).shift(band_shift(4) + DOWN * 1.3)
        self.play(Write(s2))
        self.play(Write(s2b))
        self.wait(2.5)
        s3 = Tex(r"Answer site first, then situation —").scale(1.0).shift(band_shift(4) + DOWN * 2.2)
        s3b = Tex(r"and say which one dominated").scale(1.0).shift(band_shift(4) + DOWN * 3.0)
        self.play(Write(s3))
        self.play(Write(s3b))
        self.play(Create(SurroundingRectangle(s3b, color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_3): functional classification ---
        self.next_band(5)
        b5_t = Tex("Towns sorted by the work they do").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_t))
        self.wait(1.5)
        c1 = Tex(r"Central place: serves its sphere of influence").scale(0.95).shift(band_shift(5) + UP * 1.2)
        c2 = Tex(r"Break-of-bulk: cargo changes transport (Durban)").scale(0.95).shift(band_shift(5) + UP * 0.4)
        c3 = Tex(r"Junction: routes meet (De Aar)").scale(0.95).shift(band_shift(5) + DOWN * 0.4)
        c4 = Tex(r"Gateway: border door (Musina); gap town:").scale(0.95).shift(band_shift(5) + DOWN * 1.2)
        c4b = Tex(r"mountain pass (Worcester, Ceres)").scale(0.95).shift(band_shift(5) + DOWN * 2.0)
        self.play(Write(c1))
        self.wait(2)
        self.play(Write(c2))
        self.wait(2)
        self.play(Write(c3))
        self.wait(2)
        self.play(Write(c4))
        self.play(Write(c4b))
        self.wait(2.5)
        c5 = Tex(r"Specialised: Rustenburg mines, Sasolburg fuel,").scale(0.95).shift(band_shift(5) + DOWN * 2.8)
        c5b = Tex(r"Clarens tourism, Makhanda teaches, Pretoria governs").scale(0.9).shift(band_shift(5) + DOWN * 3.5)
        self.play(Write(c5))
        self.play(Write(c5b))
        self.wait(3)

        # --- Band 6 (subtopic_4): the urban hierarchy see-saw ---
        self.next_band(6)
        b6_t = Tex("The urban hierarchy: many small, few big").scale(1.1).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_t))
        self.wait(1.5)
        # Pyramid of rectangles
        base = Rectangle(width=6.4, height=0.8, color=GREY).shift(band_shift(6) + DOWN * 1.6)
        base_lab = Tex(r"many villages: low-order services").scale(0.85).shift(band_shift(6) + DOWN * 1.6)
        mid = Rectangle(width=4.0, height=0.8, color=GREY).shift(band_shift(6) + DOWN * 0.7)
        mid_lab = Tex(r"regional towns: hospitals").scale(0.85).shift(band_shift(6) + DOWN * 0.7)
        top = Rectangle(width=1.8, height=0.8, color=YELLOW).shift(band_shift(6) + UP * 0.2)
        top_lab = Tex(r"metros").scale(0.85).shift(band_shift(6) + UP * 0.2)
        self.play(Create(base), Write(base_lab))
        self.play(Create(mid), Write(mid_lab))
        self.play(Create(top), Write(top_lab))
        self.wait(2)
        h1 = Tex(r"Higher order $\Rightarrow$ larger sphere of influence").scale(0.95).shift(band_shift(6) + DOWN * 2.6)
        h1b = Tex(r"needed $\Rightarrow$ fewer places can offer it").scale(0.95).shift(band_shift(6) + DOWN * 3.3)
        self.play(Write(h1))
        self.play(Write(h1b))
        self.play(Create(SurroundingRectangle(h1b, color=GREEN)))
        self.wait(3)

        # --- Band 7 (subtopic_4): CBD and transition zone ---
        self.next_band(7)
        b7_t = Tex("Walking out: CBD, then transition").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(1.5)
        z1 = Tex(r"CBD: dearest land $\Rightarrow$ tallest buildings —").scale(0.95).shift(band_shift(7) + UP * 1.2)
        z1b = Tex(r"offices, banks, department stores packed in").scale(0.95).shift(band_shift(7) + UP * 0.4)
        self.play(Write(z1))
        self.play(Write(z1b))
        self.wait(2.5)
        z2 = Tex(r"All transport converges; congested by day,").scale(0.95).shift(band_shift(7) + DOWN * 0.5)
        z2b = Tex(r"empty at night — few can live there").scale(0.95).shift(band_shift(7) + DOWN * 1.3)
        self.play(Write(z2))
        self.play(Write(z2b))
        self.wait(2.5)
        z3 = Tex(r"Transition zone: the city's construction site —").scale(0.95).shift(band_shift(7) + DOWN * 2.1)
        z3b = Tex(r"flats in old houses, light industry, decay").scale(0.95).shift(band_shift(7) + DOWN * 2.8)
        z3c = Tex(r"and gentrification side by side").scale(0.95).shift(band_shift(7) + DOWN * 3.4)
        self.play(Write(z3))
        self.play(Write(z3b))
        self.play(Write(z3c))
        self.wait(3)

        # --- Band 8 (subtopic_4): residential gradient, industry, nodes ---
        self.next_band(8)
        b8_t = Tex("Residential zones, industry, nodes").scale(1.15).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_t))
        self.wait(1.5)
        y1 = Tex(r"Model: income rises outward — but apartheid").scale(0.95).shift(band_shift(8) + UP * 1.2)
        y1b = Tex(r"pushed townships to the far edge, behind").scale(0.95).shift(band_shift(8) + UP * 0.4)
        y1c = Tex(r"buffer strips, railways and industry").scale(0.95).shift(band_shift(8) + DOWN * 0.4)
        self.play(Write(y1))
        self.play(Write(y1b))
        self.play(Write(y1c))
        self.wait(2.5)
        y2 = Tex(r"So the poorest carry the longest commutes").scale(0.95).shift(band_shift(8) + DOWN * 1.3)
        self.play(Write(y2))
        self.play(Create(SurroundingRectangle(y2, color=GREEN)))
        self.wait(2)
        y3 = Tex(r"Heavy industry: flat land on rail/harbours;").scale(0.95).shift(band_shift(8) + DOWN * 2.1)
        y3b = Tex(r"light industry near main roads and airports").scale(0.95).shift(band_shift(8) + DOWN * 2.8)
        self.play(Write(y3))
        self.play(Write(y3b))
        self.wait(2.5)
        y4 = Tex(r"Nodes like Sandton pull CBD functions outward").scale(0.9).shift(band_shift(8) + DOWN * 3.4)
        self.play(Write(y4))
        self.wait(3)

        # ===== Part 2 — Simplifier =====
        # --- Band 9 (subtopic_5): why cities exist ---
        self.next_band(9)
        b9_t = Tex("Why cities exist, and why everyone moves").scale(1.1).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(2)
        p1 = Tex(r"Extra food + split-up jobs + a market").scale(1.0).shift(band_shift(9) + UP * 1.2)
        p1b = Tex(r"= a town (first ones: the Nile valley)").scale(1.0).shift(band_shift(9) + UP * 0.4)
        self.play(Write(p1))
        self.play(Write(p1b))
        self.play(Create(SurroundingRectangle(p1b, color=GREEN)))
        self.wait(2.5)
        p2 = Tex(r"Factories are gathering machines: thousands").scale(0.95).shift(band_shift(9) + DOWN * 0.5)
        p2b = Tex(r"of workers pulled to one gate").scale(0.95).shift(band_shift(9) + DOWN * 1.3)
        self.play(Write(p2))
        self.play(Write(p2b))
        self.wait(2.5)
        p3 = Tex(r"Rich countries: car parked at the top (level").scale(0.95).shift(band_shift(9) + DOWN * 2.2)
        p3b = Tex(r"high, rate slow); developing: still climbing").scale(0.95).shift(band_shift(9) + DOWN * 3.0)
        self.play(Write(p3))
        self.play(Write(p3b))
        self.wait(3)

        # --- Band 10 (subtopic_6): the ladder of shops ---
        self.next_band(10)
        b10_t = Tex("The ladder of shops and the jobs towns do").scale(1.05).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_t))
        self.wait(2)
        q1 = Tex(r"Bread: the spaza. Shoes: town. Wedding outfit:").scale(0.95).shift(band_shift(10) + UP * 1.2)
        q1b = Tex(r"the big city. Heart transplant: one place").scale(0.95).shift(band_shift(10) + UP * 0.4)
        self.play(Write(q1))
        self.play(Write(q1b))
        self.wait(2.5)
        q2 = Tex(r"More special the thing, further you travel,").scale(0.95).shift(band_shift(10) + DOWN * 0.5)
        q2b = Tex(r"fewer places offer it — the see-saw").scale(0.95).shift(band_shift(10) + DOWN * 1.3)
        self.play(Write(q2))
        self.play(Write(q2b))
        self.play(Create(SurroundingRectangle(q2b, color=GREEN)))
        self.wait(2.5)
        q3 = Tex(r"Durban handles, De Aar joins, Musina guards,").scale(0.95).shift(band_shift(10) + DOWN * 2.2)
        q3b = Tex(r"Worcester sits in the mountain doorway").scale(0.95).shift(band_shift(10) + DOWN * 3.0)
        self.play(Write(q3))
        self.play(Write(q3b))
        self.wait(2)
        q4 = Tex(r"Joburg forgave its site for the gold").scale(0.95).shift(band_shift(10) + DOWN * 3.6)
        self.play(Write(q4))
        self.wait(3)

        # --- Band 11 (subtopic_7): a taxi ride across the zones ---
        self.next_band(11)
        b11_t = Tex("A taxi ride across the zones").scale(1.2).shift(band_shift(11) + UP * 2.2)
        self.play(Write(b11_t))
        self.wait(2)
        t1 = Tex(r"CBD: tug-of-war over land — dearest ground,").scale(0.95).shift(band_shift(11) + UP * 1.4)
        t1b = Tex(r"so stack thirty floors of rent on top of it").scale(0.95).shift(band_shift(11) + UP * 0.7)
        self.play(Write(t1))
        self.play(Write(t1b))
        self.wait(2.5)
        t2 = Tex(r"Next ring: half building site, half waiting").scale(0.95).shift(band_shift(11) + UP * 0.0)
        t2b = Tex(r"room — the transition zone").scale(0.95).shift(band_shift(11) + DOWN * 0.7)
        self.play(Write(t2))
        self.play(Write(t2b))
        self.wait(2.5)
        t3 = Tex(r"Then homes — apartheid rearranged the seats:").scale(0.95).shift(band_shift(11) + DOWN * 1.5)
        t3b = Tex(r"townships at the far edge, longest fares").scale(0.95).shift(band_shift(11) + DOWN * 2.2)
        self.play(Write(t3))
        self.play(Write(t3b))
        self.wait(2.5)
        t4 = Tex(r"Factory belts on the rail; and the mall that ate").scale(0.9).shift(band_shift(11) + DOWN * 2.9)
        t5 = Tex(r"the CBD's lunch: Sandton, Gateway, Century City").scale(0.9).shift(band_shift(11) + DOWN * 3.5)
        self.play(Write(t4))
        self.wait(2)
        self.play(Write(t5))
        self.play(Create(SurroundingRectangle(t5, color=GREEN)))
        self.wait(4)
