from manim import *

# Band-layout whiteboard scene for "Chemistry Paper Practice Run" — seven
# question walks through a Paper 2 (this duo's script runs all seven
# subtopics as expert question walks; each gets its own fresh bands).
# Exporter-safe mobjects only, write-only reveals, camera moves between bands.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class ChemistryPaperPracticeSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        self.wait(14)

        # --- Band 0 (subtopic_1): Q1 — naming
        title = Tex("Chemistry Paper Practice Run").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex("Q1: 4-C chain, OH on C1, methyl on C2").scale(1.05).shift(UP * 1.2)
        self.play(Write(b0_l1))
        self.wait(2)
        b0_l2 = Tex("Longest chain with the functional group,").scale(1.0).shift(UP * 0.4)
        b0_l3 = Tex("lowest number to the group, branches named").scale(1.0).shift(DOWN * 0.3)
        self.play(Write(b0_l2))
        self.play(Write(b0_l3))
        self.wait(2.5)
        b0_l4 = Tex("2-methylbutan-1-ol").scale(1.25).shift(DOWN * 1.4)
        self.play(Write(b0_l4))
        self.play(Create(SurroundingRectangle(b0_l4, color=GREEN)))
        self.wait(2)
        b0_l5 = Tex("Audit: number the other way, OH lands on C4").scale(1.0).shift(DOWN * 2.5)
        self.play(Write(b0_l5))
        self.wait(3)

        # --- Band 1 (subtopic_1): series, isomer, definition
        self.next_band(1)
        b1_title = Tex("Series and isomers").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l1 = Tex("Homologous series: alcohols —").scale(1.05).shift(band_shift(1) + UP * 1.2)
        b1_l2 = Tex(r"one general formula, members differ by CH$_2$").scale(1.0).shift(band_shift(1) + UP * 0.4)
        self.play(Write(b1_l1))
        self.play(Write(b1_l2))
        self.wait(2.5)
        b1_l3 = Tex(r"Chain isomer of butane (C$_4$H$_{10}$):").scale(1.05).shift(band_shift(1) + DOWN * 0.5)
        b1_l4 = Tex("2-methylpropane").scale(1.15).shift(band_shift(1) + DOWN * 1.3)
        self.play(Write(b1_l3))
        self.play(Write(b1_l4))
        self.play(Create(SurroundingRectangle(b1_l4, color=GREEN)))
        self.wait(2.5)
        b1_l5 = Tex("Structural isomers: SAME molecular formula,").scale(1.0).shift(band_shift(1) + DOWN * 2.2)
        b1_l6 = Tex("DIFFERENT structural formula — both halves").scale(1.0).shift(band_shift(1) + DOWN * 2.9)
        self.play(Write(b1_l5))
        self.play(Write(b1_l6))
        self.wait(3)

        # --- Band 2 (subtopic_2): the reaction scheme
        self.next_band(2)
        b2_title = Tex("Q2: propene $+$ HBr $\\rightarrow$ X $\\rightarrow$ Y").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(2)
        b2_l1 = Tex("Step 1: addition (hydrohalogenation)").scale(1.05).shift(band_shift(2) + UP * 1.2)
        b2_l2 = Tex("Step 2: elimination (dehydrohalogenation)").scale(1.05).shift(band_shift(2) + UP * 0.4)
        self.play(Write(b2_l1))
        self.wait(2)
        self.play(Write(b2_l2))
        self.wait(2.5)
        b2_l3 = Tex("H adds to the C already richer in H,").scale(1.0).shift(band_shift(2) + DOWN * 0.5)
        b2_l4 = Tex("so Br lands on the middle carbon:").scale(1.0).shift(band_shift(2) + DOWN * 1.2)
        b2_l5 = Tex("X $=$ 2-bromopropane (major)").scale(1.1).shift(band_shift(2) + DOWN * 2.0)
        self.play(Write(b2_l3))
        self.play(Write(b2_l4))
        self.wait(2)
        self.play(Write(b2_l5))
        self.play(Create(SurroundingRectangle(b2_l5, color=GREEN)))
        self.wait(2)
        b2_l6 = Tex("Y $=$ propene — the round trip is the audit").scale(1.0).shift(band_shift(2) + DOWN * 2.9)
        self.play(Write(b2_l6))
        self.wait(3)

        # --- Band 3 (subtopic_2): conditions choose the product
        self.next_band(3)
        b3_title = Tex("Conditions choose the product").scale(1.2).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(1.5)
        b3_l1 = Tex("Addition of HBr: no light, no catalyst").scale(1.05).shift(band_shift(3) + UP * 1.1)
        self.play(Write(b3_l1))
        self.wait(2)
        b3_l2 = Tex("Elimination: CONCENTRATED strong base,").scale(1.05).shift(band_shift(3) + UP * 0.3)
        b3_l3 = Tex("in ethanol, with heat").scale(1.05).shift(band_shift(3) + DOWN * 0.4)
        self.play(Write(b3_l2))
        self.play(Write(b3_l3))
        self.wait(2.5)
        b3_l4 = Tex("Dilute aqueous base instead: substitution —").scale(1.0).shift(band_shift(3) + DOWN * 1.4)
        b3_l5 = Tex("Br swapped for OH gives propan-2-ol").scale(1.05).shift(band_shift(3) + DOWN * 2.2)
        self.play(Write(b3_l4))
        self.play(Write(b3_l5))
        self.play(Create(SurroundingRectangle(b3_l5, color=GREEN)))
        self.wait(3.5)

        # --- Band 4 (subtopic_3): stoichiometry and percentage purity
        self.next_band(4)
        b4_title = Tex(r"Q3: 2,5 g impure CaCO$_3$, gas 0,448 dm$^3$").scale(1.05).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(2)
        b4_l1 = MathTex(r"n(CO_2) = \frac{0{,}448}{22{,}4} = 0{,}02\ \text{mol}").scale(1.05).shift(band_shift(4) + UP * 1.1)
        self.play(Write(b4_l1))
        self.wait(2.5)
        b4_l2 = Tex(r"Ratio 1:1 from the equation, so").scale(1.0).shift(band_shift(4) + UP * 0.2)
        b4_l3 = MathTex(r"n(CaCO_3) = 0{,}02\ \text{mol}").scale(1.05).shift(band_shift(4) + DOWN * 0.6)
        self.play(Write(b4_l2))
        self.play(Write(b4_l3))
        self.wait(2)
        b4_l4 = MathTex(r"m = 0{,}02 \times 100 = 2\ \text{g}").scale(1.05).shift(band_shift(4) + DOWN * 1.5)
        self.play(Write(b4_l4))
        self.wait(2)
        b4_l5 = MathTex(r"\text{Purity} = \frac{2}{2{,}5} \times 100 = 80\%").scale(1.1).shift(band_shift(4) + DOWN * 2.5)
        self.play(Write(b4_l5))
        self.play(Create(SurroundingRectangle(b4_l5, color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_4): rate and the collision story
        self.next_band(5)
        b5_title = Tex(r"Q4: 0,06 mol H$_2$ in 30 s").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(2)
        b5_l1 = MathTex(r"\text{rate} = \frac{0{,}06}{30} = 0{,}002\ \text{mol}\cdot\text{s}^{-1}").scale(1.0).shift(band_shift(5) + UP * 1.1)
        self.play(Write(b5_l1))
        self.play(Create(SurroundingRectangle(b5_l1, color=GREEN)))
        self.wait(2.5)
        b5_l2 = Tex("Granules, same mass: surface area DOWN").scale(1.0).shift(band_shift(5) + UP * 0.0)
        b5_l3 = Tex("effective collisions per second DOWN").scale(1.0).shift(band_shift(5) + DOWN * 0.8)
        b5_l4 = Tex("rate DOWN — one mark per link").scale(1.0).shift(band_shift(5) + DOWN * 1.6)
        self.play(Write(b5_l2))
        self.wait(2)
        self.play(Write(b5_l3))
        self.wait(2)
        self.play(Write(b5_l4))
        self.wait(2)
        b5_l5 = Tex(r"Total H$_2$ unchanged: slower, not less").scale(1.0).shift(band_shift(5) + DOWN * 2.6)
        self.play(Write(b5_l5))
        self.wait(3)

        # --- Band 6 (subtopic_4): catalyst on the PE diagram
        self.next_band(6)
        b6_title = Tex("Catalyst: only the hump drops").scale(1.15).shift(band_shift(6) + UP * 2.8)
        self.play(Write(b6_title))
        self.wait(1.5)
        ax_y = Arrow(band_shift(6) + LEFT * 4.0 + DOWN * 2.0, band_shift(6) + LEFT * 4.0 + UP * 2.0, buff=0)
        ax_x = Arrow(band_shift(6) + LEFT * 4.0 + DOWN * 2.0, band_shift(6) + RIGHT * 3.6 + DOWN * 2.0, buff=0)
        y_lab = Tex("PE").scale(0.85).shift(band_shift(6) + LEFT * 4.5 + UP * 1.7)
        x_lab = Tex("progress").scale(0.85).shift(band_shift(6) + RIGHT * 2.9 + DOWN * 2.4)
        self.play(Create(ax_y), Create(ax_x), Write(y_lab), Write(x_lab))
        self.wait(1.5)
        # uncatalysed path: reactant shelf, high hump, product shelf
        p1 = Line(band_shift(6) + LEFT * 4.0 + DOWN * 0.6, band_shift(6) + LEFT * 2.6 + DOWN * 0.6)
        p2 = Line(band_shift(6) + LEFT * 2.6 + DOWN * 0.6, band_shift(6) + LEFT * 0.8 + UP * 1.5)
        p3 = Line(band_shift(6) + LEFT * 0.8 + UP * 1.5, band_shift(6) + RIGHT * 1.0 + DOWN * 1.3)
        p4 = Line(band_shift(6) + RIGHT * 1.0 + DOWN * 1.3, band_shift(6) + RIGHT * 3.0 + DOWN * 1.3)
        self.play(Create(p1), Create(p2))
        self.play(Create(p3), Create(p4))
        self.wait(1.5)
        # catalysed hump, lower
        c2 = DashedLine(band_shift(6) + LEFT * 2.6 + DOWN * 0.6, band_shift(6) + LEFT * 0.8 + UP * 0.5, color=YELLOW)
        c3 = DashedLine(band_shift(6) + LEFT * 0.8 + UP * 0.5, band_shift(6) + RIGHT * 1.0 + DOWN * 1.3, color=YELLOW)
        cat_lab = Tex("catalysed").scale(0.85).shift(band_shift(6) + RIGHT * 1.8 + UP * 0.5)
        self.play(Create(c2), Create(c3), Write(cat_lab))
        self.wait(2)
        b6_l1 = Tex(r"Reactants, products, $\Delta H$: untouched").scale(1.0).shift(band_shift(6) + DOWN * 2.9)
        self.play(Write(b6_l1))
        self.play(Create(SurroundingRectangle(b6_l1, color=GREEN)))
        self.wait(3)

        # --- Band 7 (subtopic_5): the RICE table
        self.next_band(7)
        b7_title = Tex(r"Q5: 2SO$_2$ + O$_2 \rightleftharpoons$ 2SO$_3$ in 2 dm$^3$").scale(1.05).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(2)
        b7_h = MathTex(r"\quad\ \ SO_2 \quad\ \ O_2 \quad\ \ SO_3").scale(1.0).shift(band_shift(7) + UP * 1.2)
        self.play(Write(b7_h))
        self.wait(1.5)
        b7_r1 = MathTex(r"\text{I:}\ \ 0{,}4 \quad\ 0{,}3 \quad\ 0").scale(1.0).shift(band_shift(7) + UP * 0.4)
        b7_r2 = MathTex(r"\text{C:}\ -0{,}2 \ \ -0{,}1 \ \ +0{,}2").scale(1.0).shift(band_shift(7) + DOWN * 0.4)
        b7_r3 = MathTex(r"\text{E:}\ \ 0{,}2 \quad\ 0{,}2 \quad\ 0{,}2").scale(1.0).shift(band_shift(7) + DOWN * 1.2)
        self.play(Write(b7_r1))
        self.wait(2)
        self.play(Write(b7_r2))
        self.wait(2.5)
        self.play(Write(b7_r3))
        self.play(Create(SurroundingRectangle(b7_r3, color=GREEN)))
        self.wait(2)
        b7_l1 = Tex(r"Change anchored on SO$_3$: ratios 2:2 and 2:1").scale(1.0).shift(band_shift(7) + DOWN * 2.2)
        self.play(Write(b7_l1))
        self.wait(3)

        # --- Band 8 (subtopic_5): concentrations, then Kc
        self.next_band(8)
        b8_title = Tex("Divide by the volume FIRST").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(1.5)
        b8_l1 = MathTex(r"[\text{each}] = \frac{0{,}2}{2} = 0{,}1\ \text{mol}\cdot\text{dm}^{-3}").scale(1.05).shift(band_shift(8) + UP * 1.1)
        self.play(Write(b8_l1))
        self.wait(2.5)
        b8_l2 = Tex("Moles poured straight into $K_c$ score nothing").scale(1.0).shift(band_shift(8) + UP * 0.2)
        self.play(Write(b8_l2))
        self.wait(2)
        b8_l3 = MathTex(r"K_c = \frac{[SO_3]^2}{[SO_2]^2[O_2]}").scale(1.1).shift(band_shift(8) + DOWN * 0.9)
        self.play(Write(b8_l3))
        self.wait(2.5)
        b8_l4 = MathTex(r"K_c = \frac{(0{,}1)^2}{(0{,}1)^2(0{,}1)} = \frac{0{,}01}{0{,}001} = 10").scale(1.05).shift(band_shift(8) + DOWN * 2.2)
        self.play(Write(b8_l4))
        self.play(Create(SurroundingRectangle(b8_l4, color=GREEN)))
        self.wait(2)
        b8_l5 = Tex(r"No units on $K_c$; 10 leans toward products").scale(1.0).shift(band_shift(8) + DOWN * 3.1)
        self.play(Write(b8_l5))
        self.wait(3)

        # --- Band 9 (subtopic_6): the titration
        self.next_band(9)
        b9_title = Tex(r"Q6: 25 cm$^3$ of 0,1 M oxalic acid, 20 cm$^3$ NaOH").scale(1.0).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = MathTex(r"n_{acid} = 0{,}1 \times 0{,}025 = 0{,}0025\ \text{mol}").scale(1.05).shift(band_shift(9) + UP * 1.1)
        self.play(Write(b9_l1))
        self.wait(2.5)
        b9_l2 = Tex(r"Volumes in dm$^3$ — the quiet trap").scale(1.0).shift(band_shift(9) + UP * 0.2)
        self.play(Write(b9_l2))
        self.wait(2)
        b9_l3 = MathTex(r"\text{Ratio } 1:2 \Rightarrow n_{NaOH} = 0{,}005\ \text{mol}").scale(1.05).shift(band_shift(9) + DOWN * 0.7)
        self.play(Write(b9_l3))
        self.wait(2.5)
        b9_l4 = MathTex(r"c = \frac{0{,}005}{0{,}020} = 0{,}25\ \text{mol}\cdot\text{dm}^{-3}").scale(1.05).shift(band_shift(9) + DOWN * 1.8)
        self.play(Write(b9_l4))
        self.play(Create(SurroundingRectangle(b9_l4, color=GREEN)))
        self.wait(3)

        # --- Band 10 (subtopic_6): pH and hydrolysis
        self.next_band(10)
        b10_title = Tex("pH, and why the salt sits above 7").scale(1.15).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_title))
        self.wait(1.5)
        b10_l1 = MathTex(r"[H_3O^+] = 0{,}001 = 10^{-3}").scale(1.05).shift(band_shift(10) + UP * 1.2)
        b10_l2 = MathTex(r"pH = -\log[H_3O^+] = -\log 10^{-3} = 3").scale(1.05).shift(band_shift(10) + UP * 0.2)
        self.play(Write(b10_l1))
        self.wait(2)
        self.play(Write(b10_l2))
        self.play(Create(SurroundingRectangle(b10_l2, color=GREEN)))
        self.wait(2.5)
        b10_l3 = Tex("Sodium oxalate: weak acid $+$ strong base salt").scale(1.0).shift(band_shift(10) + DOWN * 0.9)
        b10_l4 = Tex(r"Oxalate takes protons, frees OH$^-$: pH $> 7$").scale(1.0).shift(band_shift(10) + DOWN * 1.7)
        b10_l5 = Tex("hence phenolphthalein was the right choice").scale(1.0).shift(band_shift(10) + DOWN * 2.5)
        self.play(Write(b10_l3))
        self.wait(2)
        self.play(Write(b10_l4))
        self.wait(2)
        self.play(Write(b10_l5))
        self.wait(3)

        # --- Band 11 (subtopic_7): the galvanic cell — anode and emf
        self.next_band(11)
        b11_title = Tex(r"Q7: Zn ($-$0,76 V) with Ag ($+$0,80 V)").scale(1.1).shift(band_shift(11) + UP * 2.2)
        self.play(Write(b11_title))
        self.wait(2)
        b11_l1 = Tex("Anode: Zn — lower reduction potential,").scale(1.0).shift(band_shift(11) + UP * 1.2)
        b11_l2 = Tex("stronger reducing agent, so it oxidises").scale(1.0).shift(band_shift(11) + UP * 0.5)
        self.play(Write(b11_l1))
        self.play(Write(b11_l2))
        self.wait(2.5)
        b11_l3 = MathTex(r"\text{Anode: } Zn \rightarrow Zn^{2+} + 2e^-").scale(1.05).shift(band_shift(11) + DOWN * 0.5)
        b11_l4 = MathTex(r"\text{Cathode: } Ag^+ + e^- \rightarrow Ag").scale(1.05).shift(band_shift(11) + DOWN * 1.4)
        self.play(Write(b11_l3))
        self.wait(2)
        self.play(Write(b11_l4))
        self.wait(2)
        b11_wrong = MathTex(r"E_{cell} = 0{,}80 - 0{,}76 = 0{,}04\ \text{V}").scale(1.0).shift(band_shift(11) + DOWN * 2.3)
        self.play(Write(b11_wrong))
        self.play(Create(strike(b11_wrong)))
        self.wait(2)
        b11_l5 = MathTex(r"E_{cell} = 0{,}80 - (-0{,}76) = 1{,}56\ \text{V}").scale(1.05).shift(band_shift(11) + DOWN * 3.1)
        self.play(Write(b11_l5))
        self.play(Create(SurroundingRectangle(b11_l5, color=GREEN)))
        self.wait(3)

        # --- Band 12 (subtopic_7): overall reaction and the salt bridge
        self.next_band(12)
        b12_title = Tex("Balance the electrons, close the run").scale(1.15).shift(band_shift(12) + UP * 2.2)
        self.play(Write(b12_title))
        self.wait(1.5)
        b12_l1 = Tex("Silver half-reaction doubles:").scale(1.0).shift(band_shift(12) + UP * 1.2)
        b12_l2 = MathTex(r"Zn + 2Ag^+ \rightarrow Zn^{2+} + 2Ag").scale(1.1).shift(band_shift(12) + UP * 0.3)
        self.play(Write(b12_l1))
        self.play(Write(b12_l2))
        self.play(Create(SurroundingRectangle(b12_l2, color=GREEN)))
        self.wait(2.5)
        b12_l3 = Tex(r"Positive emf $=$ spontaneous $=$ galvanic").scale(1.0).shift(band_shift(12) + DOWN * 0.8)
        self.play(Write(b12_l3))
        self.wait(2)
        b12_l4 = Tex("Salt bridge: ions migrate, circuit completes,").scale(1.0).shift(band_shift(12) + DOWN * 1.7)
        b12_l5 = Tex("both solutions stay electrically neutral").scale(1.0).shift(band_shift(12) + DOWN * 2.4)
        self.play(Write(b12_l4))
        self.play(Write(b12_l5))
        self.wait(2)
        b12_l6 = Tex("Oxidation at the anode, reduction at the cathode").scale(1.0).shift(band_shift(12) + DOWN * 3.1)
        self.play(Write(b12_l6))
        self.wait(4)
