from manim import *

# Band-layout whiteboard scene for equations-of-motion (Part 1 Expert
# subtopics 1-4, Part 2 Simplifier subtopics 5-7). Exporter-safe mobjects
# only; add-only lifecycle; the 10-to-25 m/s over 300 m car problem worked
# line by line with the script's exact numbers and units.
# Time apportioned to subtopics.json (220/230/230/260/170/180/170 of 1460 s).

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class EquationsOfMotionSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): the cast of five ---
        title = Tex("Equations of Motion").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        a1 = Tex("$v_i$: initial velocity; $v_f$: final velocity").scale(1.0).shift(UP * 1.0)
        self.play(Write(a1))
        self.wait(2)
        a2 = Tex("$a$: acceleration (m·s$^{-2}$)").scale(1.0).shift(UP * 0.2)
        self.play(Write(a2))
        self.wait(2)
        a3 = Tex("$\\Delta t$: time; $\\Delta x$: displacement").scale(1.0).shift(DOWN * 0.6)
        self.play(Write(a3))
        self.wait(2)
        a4 = Tex("Licence word: UNIFORM acceleration").scale(1.05).shift(DOWN * 1.6)
        self.play(Write(a4))
        self.play(Create(SurroundingRectangle(a4, color=GREEN)))
        self.wait(2)
        a5 = Tex("No uniform $a$, no equations of motion").scale(0.95).shift(DOWN * 2.6)
        self.play(Write(a5))
        self.wait(3)

        # --- Band 1 (subtopic_1): the four equations, each missing one ---
        self.next_band(1)
        b1_t = Tex("Four equations, each missing one").scale(1.15).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_t))
        self.wait(1.5)
        b1_1 = MathTex(r"v_f = v_i + a\Delta t \; \text{(no } \Delta x)").scale(1.0).shift(band_shift(1) + UP * 1.35)
        self.play(Write(b1_1))
        self.wait(2)
        b1_2 = MathTex(r"\Delta x = v_i\Delta t + \tfrac{1}{2}a\Delta t^2").scale(1.0).shift(band_shift(1) + UP * 0.55)
        b1_2n = Tex("(no $v_f$)").scale(0.85).shift(band_shift(1) + DOWN * 0.15)
        self.play(Write(b1_2))
        self.play(Write(b1_2n))
        self.wait(2)
        b1_3 = MathTex(r"v_f^2 = v_i^2 + 2a\Delta x \; \text{(no } \Delta t)").scale(1.0).shift(band_shift(1) + DOWN * 0.95)
        self.play(Write(b1_3))
        self.wait(2)
        b1_4 = MathTex(r"\Delta x = \tfrac{v_i + v_f}{2}\Delta t \; \text{(no } a)").scale(1.0).shift(band_shift(1) + DOWN * 1.75)
        self.play(Write(b1_4))
        self.wait(2)
        b1_5 = Tex("Find the ABSENT quantity; exclude it").scale(1.0).shift(band_shift(1) + DOWN * 2.75)
        self.play(Write(b1_5))
        self.play(Create(SurroundingRectangle(b1_5, color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): the data audit and the choice ---
        self.next_band(2)
        b2_t = Tex("10 to 25 m·s$^{-1}$ over 300 m: find $a$").scale(1.1).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(1.5)
        b2_1 = MathTex(r"v_i = 10, \;\; v_f = 25, \;\; \Delta x = 300").scale(1.05).shift(band_shift(2) + UP * 1.1)
        self.play(Write(b2_1))
        self.wait(2)
        b2_2 = Tex("Wanted: $a$; \\; absent: $\\Delta t$").scale(1.05).shift(band_shift(2) + UP * 0.1)
        self.play(Write(b2_2))
        self.wait(2)
        b2_3 = Tex("So: the equation with no time in it").scale(1.0).shift(band_shift(2) + DOWN * 0.9)
        self.play(Write(b2_3))
        self.wait(2)
        b2_4 = MathTex(r"v_f^2 = v_i^2 + 2a\Delta x").scale(1.15).shift(band_shift(2) + DOWN * 1.9)
        self.play(Write(b2_4))
        self.play(Create(SurroundingRectangle(b2_4, color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_2): substitute and solve ---
        self.next_band(3)
        b3_t = Tex("Substitute and solve").scale(1.2).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t))
        self.wait(1.5)
        b3_1 = MathTex(r"25^2 = 10^2 + 2a(300)").scale(1.1).shift(band_shift(3) + UP * 1.1)
        self.play(Write(b3_1))
        self.wait(2)
        b3_2 = MathTex(r"625 = 100 + 600a").scale(1.1).shift(band_shift(3) + UP * 0.1)
        self.play(Write(b3_2))
        self.wait(2)
        b3_3 = MathTex(r"525 = 600a").scale(1.1).shift(band_shift(3) + DOWN * 0.9)
        self.play(Write(b3_3))
        self.wait(2)
        b3_4 = MathTex(r"a = \frac{525}{600} = 0{,}875\ \text{m·s}^{-2}").scale(1.1).shift(band_shift(3) + DOWN * 1.9)
        self.play(Write(b3_4))
        self.play(Create(SurroundingRectangle(b3_4, color=GREEN)))
        self.wait(2.5)
        b3_5 = Tex("Direction of motion; size believable").scale(0.95).shift(band_shift(3) + DOWN * 2.9)
        self.play(Write(b3_5))
        self.wait(3)

        # --- Band 4 (subtopic_3): the time, road one ---
        self.next_band(4)
        b4_t = Tex("Finding the time: road one").scale(1.2).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(1.5)
        b4_1 = MathTex(r"v_f = v_i + a\Delta t").scale(1.1).shift(band_shift(4) + UP * 1.1)
        self.play(Write(b4_1))
        self.wait(2)
        b4_2 = MathTex(r"25 = 10 + 0{,}875\,\Delta t").scale(1.1).shift(band_shift(4) + UP * 0.1)
        self.play(Write(b4_2))
        self.wait(2)
        b4_3 = MathTex(r"15 = 0{,}875\,\Delta t").scale(1.1).shift(band_shift(4) + DOWN * 0.9)
        self.play(Write(b4_3))
        self.wait(2)
        b4_4 = MathTex(r"\Delta t = \frac{15}{0{,}875} = 17{,}14\ \text{s}").scale(1.1).shift(band_shift(4) + DOWN * 1.9)
        self.play(Write(b4_4))
        self.play(Create(SurroundingRectangle(b4_4, color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_3): road two, the check ---
        self.next_band(5)
        b5_t = Tex("Road two: the independent check").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_t))
        self.wait(1.5)
        b5_1 = MathTex(r"\Delta x = \tfrac{v_i + v_f}{2}\Delta t \; \text{(no } a)").scale(1.0).shift(band_shift(5) + UP * 1.1)
        self.play(Write(b5_1))
        self.wait(2)
        b5_2 = MathTex(r"\text{average} = \frac{10 + 25}{2} = 17{,}5\ \text{m·s}^{-1}").scale(1.0).shift(band_shift(5) + UP * 0.1)
        self.play(Write(b5_2))
        self.wait(2.5)
        b5_3 = MathTex(r"300 = 17{,}5\,\Delta t").scale(1.05).shift(band_shift(5) + DOWN * 0.9)
        self.play(Write(b5_3))
        self.wait(2)
        b5_3b = MathTex(r"\Delta t = 17{,}14\ \text{s} \; \checkmark").scale(1.05).shift(band_shift(5) + DOWN * 1.8)
        self.play(Write(b5_3b))
        self.play(Create(SurroundingRectangle(b5_3b, color=GREEN)))
        self.wait(2.5)
        b5_4 = Tex("Two roads agreeing: the strongest check").scale(1.0).shift(band_shift(5) + DOWN * 2.8)
        self.play(Write(b5_4))
        self.wait(3)

        # --- Band 6 (subtopic_4): the five-step method ---
        self.next_band(6)
        b6_t = Tex("The method, five steps").scale(1.2).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_t))
        self.wait(1.5)
        b6_1 = Tex("1. Confirm UNIFORM acceleration").scale(1.0).shift(band_shift(6) + UP * 1.1)
        b6_2 = Tex("2. List given, wanted, absent — convert units").scale(0.95).shift(band_shift(6) + UP * 0.3)
        b6_3 = Tex("3. Choose by the absent quantity").scale(1.0).shift(band_shift(6) + DOWN * 0.5)
        b6_4 = Tex("4. Substitute with units; state direction").scale(0.95).shift(band_shift(6) + DOWN * 1.3)
        b6_5 = Tex("5. Sense-check; verify by a second road").scale(0.95).shift(band_shift(6) + DOWN * 2.1)
        for m in (b6_1, b6_2, b6_3, b6_4, b6_5):
            self.play(Write(m))
            self.wait(1.7)
        self.wait(2)

        # --- Band 7 (subtopic_4): the traps ---
        self.next_band(7)
        b7_t = Tex("The classic traps").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(1.5)
        b7_trap = MathTex(r"90\ \text{km/h enters as } 90\ \text{m·s}^{-1}").scale(1.0).shift(band_shift(7) + UP * 1.1)
        self.play(Write(b7_trap))
        self.play(Create(strike(b7_trap)))
        self.wait(2)
        b7_1 = MathTex(r"\frac{90}{3{,}6} = 25\ \text{m·s}^{-1} \; \text{at the data stage}").scale(0.95).shift(band_shift(7) + UP * 0.1)
        self.play(Write(b7_1))
        self.play(Create(SurroundingRectangle(b7_1, color=GREEN)))
        self.wait(2.5)
        b7_2 = Tex("$v_f^2$ means 625, not 25 — square at once").scale(0.95).shift(band_shift(7) + DOWN * 0.9)
        self.play(Write(b7_2))
        self.wait(2)
        b7_3 = Tex("Braking: $a$ is negative — keep the sign").scale(0.95).shift(band_shift(7) + DOWN * 1.8)
        self.play(Write(b7_3))
        self.wait(2)
        b7_4 = Tex("Choose by absence, not by memory").scale(0.95).shift(band_shift(7) + DOWN * 2.7)
        self.play(Write(b7_4))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): five facts about any trip ---
        self.next_band(8)
        b8_t = Tex("Five facts about any trip").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_t))
        self.wait(2)
        b8_1 = Tex("Speed at the start; speed at the end").scale(1.0).shift(band_shift(8) + UP * 1.1)
        self.play(Write(b8_1))
        self.wait(2)
        b8_2 = Tex("How quickly speed grows; how long; how far").scale(0.95).shift(band_shift(8) + UP * 0.2)
        self.play(Write(b8_2))
        self.wait(2)
        b8_3 = Tex("Permission slip: the word UNIFORM").scale(1.0).shift(band_shift(8) + DOWN * 0.7)
        self.play(Write(b8_3))
        self.play(Create(SurroundingRectangle(b8_3, color=GREEN)))
        self.wait(2)
        b8_4 = Tex("Each equation is missing exactly one fact").scale(0.95).shift(band_shift(8) + DOWN * 1.7)
        self.play(Write(b8_4))
        self.wait(2)
        b8_5 = Tex("(stop-start traffic does not qualify)").scale(0.9).shift(band_shift(8) + DOWN * 2.6)
        self.play(Write(b8_5))
        self.wait(3)

        # --- Band 9 (subtopic_6): the one fact you don't need ---
        self.next_band(9)
        b9_t = Tex("Hunt the fact nobody mentioned").scale(1.15).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(2)
        b9_1 = Tex("Given 10, 25, 300 m; wanted $a$; no TIME").scale(0.95).shift(band_shift(9) + UP * 1.1)
        self.play(Write(b9_1))
        self.wait(2)
        b9_2 = MathTex(r"625 = 100 + 600a").scale(1.05).shift(band_shift(9) + UP * 0.1)
        self.play(Write(b9_2))
        self.wait(2)
        b9_3 = MathTex(r"a = \frac{525}{600} = 0{,}875\ \text{m·s}^{-2}").scale(1.05).shift(band_shift(9) + DOWN * 0.9)
        self.play(Write(b9_3))
        self.play(Create(SurroundingRectangle(b9_3, color=GREEN)))
        self.wait(2.5)
        b9_4 = Tex("Meaning: almost 1 m/s of extra speed").scale(0.95).shift(band_shift(9) + DOWN * 1.9)
        b9_5 = Tex("each second — an ordinary pull-away").scale(0.95).shift(band_shift(9) + DOWN * 2.7)
        self.play(Write(b9_4))
        self.play(Write(b9_5))
        self.wait(3)

        # --- Band 10 (subtopic_7): checking the fare two ways ---
        self.next_band(10)
        b10_t = Tex("Checking the fare two ways").scale(1.2).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_t))
        self.wait(2)
        b10_1 = MathTex(r"\text{Road 1: } \Delta t = \frac{15}{0{,}875} = 17{,}14\ \text{s}").scale(1.0).shift(band_shift(10) + UP * 1.1)
        self.play(Write(b10_1))
        self.wait(2.5)
        b10_2 = MathTex(r"\text{Road 2: } \frac{300}{17{,}5} = 17{,}14\ \text{s} \; \checkmark").scale(1.0).shift(band_shift(10) + UP * 0.1)
        self.play(Write(b10_2))
        self.play(Create(SurroundingRectangle(b10_2, color=GREEN)))
        self.wait(2.5)
        b10_3 = Tex("Count your change twice — two counts").scale(0.95).shift(band_shift(10) + DOWN * 0.9)
        b10_4 = Tex("that agree beat one made confidently").scale(0.95).shift(band_shift(10) + DOWN * 1.7)
        self.play(Write(b10_3))
        self.play(Write(b10_4))
        self.wait(2.5)
        b10_5 = Tex("Units at the door; braking wears a minus").scale(0.95).shift(band_shift(10) + DOWN * 2.7)
        self.play(Write(b10_5))
        self.wait(4)
