from manim import *

# Band-layout whiteboard scene for the session duo "Physical Properties and
# Intermolecular Forces" (Part 1 Expert subtopics 1-4, Part 2 Simplifier
# subtopics 5-7). Exporter-safe vocabulary only: Tex/MathTex/Line/Arrow/Dot/
# Circle/Rectangle/SurroundingRectangle/VGroup, write-only reveals, camera
# moves between bands. Subtopic durations 235/235/235/240/190/195/195 of
# 1525 s drive the proportional dwell times.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class IntermolecularForcesSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): inter vs intra, the anchor distinction ---
        title = Tex("Intermolecular Forces").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex("Inside a molecule: covalent bonds (strong)").scale(1.1).shift(UP * 1.1)
        b0_l2 = Tex("Between molecules: weaker attractions").scale(1.1).shift(UP * 0.2)
        self.play(Write(b0_l1))
        self.wait(2)
        self.play(Write(b0_l2))
        self.wait(2)
        b0_wrong = Tex("Boiling breaks the covalent bonds").scale(1.1).shift(DOWN * 1.0)
        self.play(Write(b0_wrong))
        self.play(Create(strike(b0_wrong)))
        self.wait(2)
        b0_l3 = Tex("Boiling breaks only the forces BETWEEN").scale(1.1).shift(DOWN * 2.0)
        self.play(Write(b0_l3))
        self.play(Create(SurroundingRectangle(b0_l3, color=GREEN)))
        self.wait(3)

        # --- Band 1 (subtopic_1): the three forces, weakest to strongest ---
        self.next_band(1)
        b1_title = Tex("Three forces, weakest to strongest").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l1 = Tex("1. London: ALL molecules; grows with size").scale(1.05).shift(band_shift(1) + UP * 1.1)
        b1_l2 = Tex("2. Dipole-dipole: polar molecules (C=O)").scale(1.05).shift(band_shift(1) + UP * 0.2)
        b1_l3 = Tex("3. Hydrogen bond: H on N, O or F").scale(1.05).shift(band_shift(1) + DOWN * 0.7)
        self.play(Write(b1_l1))
        self.wait(2.5)
        self.play(Write(b1_l2))
        self.wait(2.5)
        self.play(Write(b1_l3))
        self.wait(2.5)
        b1_l4 = Tex("Acids H-bond twice: molecules pair up").scale(1.05).shift(band_shift(1) + DOWN * 1.6)
        self.play(Write(b1_l4))
        self.wait(2)
        b1_rank = Tex(r"alkane $<$ aldehyde/ketone $<$ alcohol $<$ acid").scale(1.0).shift(band_shift(1) + DOWN * 2.6)
        self.play(Write(b1_rank))
        self.play(Create(SurroundingRectangle(b1_rank, color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): lever 1 — chain length ---
        self.next_band(2)
        b2_title = Tex("Lever 1: chain length").scale(1.2).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(1.5)
        b2_l1 = MathTex(r"\text{methane: } -161{,}5\ ^\circ\text{C}").scale(1.1).shift(band_shift(2) + UP * 1.1)
        b2_l2 = MathTex(r"\text{butane: } -0{,}5\ ^\circ\text{C}").scale(1.1).shift(band_shift(2) + UP * 0.3)
        b2_l3 = MathTex(r"\text{pentane: } 36{,}1 \quad \text{octane: } 126").scale(1.1).shift(band_shift(2) + DOWN * 0.5)
        self.play(Write(b2_l1))
        self.wait(2)
        self.play(Write(b2_l2))
        self.wait(2)
        self.play(Write(b2_l3))
        self.wait(2)
        b2_l4 = Tex("Longer chain: more electrons, more surface").scale(1.05).shift(band_shift(2) + DOWN * 1.5)
        b2_l5 = Tex("Stronger London forces: higher boiling point").scale(1.05).shift(band_shift(2) + DOWN * 2.5)
        self.play(Write(b2_l4))
        self.wait(2)
        self.play(Write(b2_l5))
        self.play(Create(SurroundingRectangle(b2_l5, color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_2): lever 2 — branching, with contact diagram ---
        self.next_band(3)
        b3_title = Tex(r"Lever 2: branching ($C_5H_{12}$ isomers)").scale(1.15).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(1.5)
        b3_l1 = MathTex(r"\text{pentane: } 36{,}1\ ^\circ\text{C}").scale(1.05).shift(band_shift(3) + UP * 1.2)
        b3_l2 = MathTex(r"\text{2-methylbutane: } 27{,}8\ ^\circ\text{C}").scale(1.05).shift(band_shift(3) + UP * 0.4)
        b3_l3 = MathTex(r"\text{2,2-dimethylpropane: } 9{,}5\ ^\circ\text{C}").scale(1.05).shift(band_shift(3) + DOWN * 0.4)
        self.play(Write(b3_l1))
        self.wait(1.5)
        self.play(Write(b3_l2))
        self.wait(1.5)
        self.play(Write(b3_l3))
        self.wait(2)
        # Contact diagram: straight chains touch along their length,
        # branched spheres touch at a point.
        chain_a = Line(LEFT * 5.5, LEFT * 2.5).shift(band_shift(3) + DOWN * 1.3)
        chain_b = Line(LEFT * 5.5, LEFT * 2.5).shift(band_shift(3) + DOWN * 1.6)
        self.play(Create(chain_a), Create(chain_b))
        lab_a = Tex("full-length contact").scale(0.9).shift(band_shift(3) + DOWN * 2.2 + LEFT * 4.0)
        self.play(Write(lab_a))
        self.wait(1.5)
        ball_a = Circle(radius=0.45, color=WHITE).shift(band_shift(3) + DOWN * 1.45 + RIGHT * 2.5)
        ball_b = Circle(radius=0.45, color=WHITE).shift(band_shift(3) + DOWN * 1.45 + RIGHT * 3.4)
        touch = Dot(band_shift(3) + DOWN * 1.45 + RIGHT * 2.95, color=YELLOW)
        self.play(Create(ball_a), Create(ball_b))
        self.play(FadeIn(touch))
        lab_b = Tex("spheres touch at a point").scale(0.9).shift(band_shift(3) + DOWN * 2.2 + RIGHT * 3.2)
        self.play(Write(lab_b))
        self.wait(2)
        b3_rule = Tex("More branching: less contact, lower b.p.").scale(1.05).shift(band_shift(3) + DOWN * 3.0)
        self.play(Write(b3_rule))
        self.play(Create(SurroundingRectangle(b3_rule, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): lever 3 — functional group at equal mass ---
        self.next_band(4)
        b4_title = Tex("Lever 3: functional group (equal mass)").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(1.5)
        b4_l1 = MathTex(r"\text{butane (58): } -0{,}5\ ^\circ\text{C}").scale(1.05).shift(band_shift(4) + UP * 1.1)
        b4_l1b = Tex("London only").scale(0.95).shift(band_shift(4) + UP * 0.45 + RIGHT * 3.5)
        self.play(Write(b4_l1))
        self.play(Write(b4_l1b))
        self.wait(2)
        b4_l2 = MathTex(r"\text{propanal (58): } 48{,}8\ ^\circ\text{C}").scale(1.05).shift(band_shift(4) + DOWN * 0.2)
        b4_l2b = Tex("+ dipole-dipole").scale(0.95).shift(band_shift(4) + DOWN * 0.85 + RIGHT * 3.5)
        self.play(Write(b4_l2))
        self.play(Write(b4_l2b))
        self.wait(2)
        b4_l3 = MathTex(r"\text{propan-1-ol (60): } 97{,}2\ ^\circ\text{C}").scale(1.05).shift(band_shift(4) + DOWN * 1.5)
        b4_l3b = Tex("+ hydrogen bonds").scale(0.95).shift(band_shift(4) + DOWN * 2.15 + RIGHT * 3.3)
        self.play(Write(b4_l3))
        self.play(Write(b4_l3b))
        self.wait(2)
        b4_l4 = MathTex(r"\text{propanoic acid (74): } 141\ ^\circ\text{C}").scale(1.05).shift(band_shift(4) + DOWN * 2.9)
        self.play(Write(b4_l4))
        self.play(Create(SurroundingRectangle(b4_l4, color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_3): solubility + fair comparisons ---
        self.next_band(5)
        b5_title = Tex("Solubility, and fair comparisons").scale(1.2).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(1.5)
        b5_l1 = Tex("Water is a hydrogen-bonding liquid").scale(1.05).shift(band_shift(5) + UP * 1.1)
        b5_l2 = Tex("Short alcohols, acids H-bond: dissolve").scale(1.05).shift(band_shift(5) + UP * 0.2)
        b5_l3 = Tex("Alkanes offer only London: do not mix").scale(1.05).shift(band_shift(5) + DOWN * 0.7)
        self.play(Write(b5_l1))
        self.wait(2)
        self.play(Write(b5_l2))
        self.wait(2)
        self.play(Write(b5_l3))
        self.wait(2)
        b5_wrong = Tex("Compare propan-1-ol with octane").scale(1.05).shift(band_shift(5) + DOWN * 1.7)
        self.play(Write(b5_wrong))
        self.play(Create(strike(b5_wrong)))
        self.wait(2)
        b5_rule = Tex("Change ONE lever; hold the rest constant").scale(1.05).shift(band_shift(5) + DOWN * 2.7)
        self.play(Write(b5_rule))
        self.play(Create(SurroundingRectangle(b5_rule, color=GREEN)))
        self.wait(3)

        # --- Band 6 (subtopic_4): vapour pressure, the inverted readout ---
        self.next_band(6)
        b6_title = Tex("Vapour pressure").scale(1.2).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(1.5)
        b6_l1 = Tex("Pressure of vapour in equilibrium").scale(1.05).shift(band_shift(6) + UP * 1.2)
        b6_l2 = Tex("with its liquid, in a closed container").scale(1.05).shift(band_shift(6) + UP * 0.4)
        self.play(Write(b6_l1))
        self.play(Write(b6_l2))
        self.wait(2.5)
        b6_l3 = Tex("Boils when vapour pressure $=$ atmospheric").scale(1.05).shift(band_shift(6) + DOWN * 0.5)
        self.play(Write(b6_l3))
        self.wait(2)
        b6_l4 = Tex("Strong forces: LOW v.p., HIGH b.p.").scale(1.05).shift(band_shift(6) + DOWN * 1.4)
        b6_l5 = Tex("Weak forces: HIGH v.p., LOW b.p. (volatile)").scale(1.05).shift(band_shift(6) + DOWN * 2.3)
        self.play(Write(b6_l4))
        self.wait(2)
        self.play(Write(b6_l5))
        self.play(Create(SurroundingRectangle(b6_l5, color=GREEN)))
        self.wait(3)

        # --- Band 7 (subtopic_4): the four-step answer scheme ---
        self.next_band(7)
        b7_title = Tex("The four-step answer").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(1.5)
        b7_l1 = Tex("1. Identify the structural difference").scale(1.05).shift(band_shift(7) + UP * 1.1)
        b7_l2 = Tex("2. Name the forces in each compound").scale(1.05).shift(band_shift(7) + UP * 0.2)
        b7_l3 = Tex("3. Compare their strengths, and say why").scale(1.05).shift(band_shift(7) + DOWN * 0.7)
        b7_l4 = Tex("4. Stronger forces need more ENERGY").scale(1.05).shift(band_shift(7) + DOWN * 1.6)
        self.play(Write(b7_l1))
        self.wait(2.5)
        self.play(Write(b7_l2))
        self.wait(2.5)
        self.play(Write(b7_l3))
        self.wait(2.5)
        self.play(Write(b7_l4))
        self.play(Create(SurroundingRectangle(b7_l4, color=GREEN)))
        self.wait(2)
        b7_l5 = Tex("Four sentences, four marks, in that order").scale(1.0).shift(band_shift(7) + DOWN * 2.6)
        self.play(Write(b7_l5))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): molecules are wearing velcro ---
        self.next_band(8)
        b8_title = Tex("Molecules are wearing velcro").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = Tex("Long strips grip along their whole length").scale(1.05).shift(band_shift(8) + UP * 1.1)
        self.play(Write(b8_l1))
        self.wait(2)
        b8_l2 = MathTex(r"\text{methane } -161{,}5 \;\rightarrow\; \text{octane } 126").scale(1.0).shift(band_shift(8) + UP * 0.2)
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = Tex("Crumple the strip into a ball: tiny patch").scale(1.05).shift(band_shift(8) + DOWN * 0.7)
        b8_l4 = MathTex(r"36{,}1 \;\rightarrow\; 27{,}8 \;\rightarrow\; 9{,}5\ ^\circ\text{C}").scale(1.05).shift(band_shift(8) + DOWN * 1.6)
        self.play(Write(b8_l3))
        self.wait(2)
        self.play(Write(b8_l4))
        self.wait(2)
        b8_rule = Tex("The reason behind both: CONTACT").scale(1.1).shift(band_shift(8) + DOWN * 2.6)
        self.play(Write(b8_rule))
        self.play(Create(SurroundingRectangle(b8_rule, color=GREEN)))
        self.wait(3)

        # --- Band 9 (subtopic_6): some molecules also carry magnets ---
        self.next_band(9)
        b9_title = Tex("Some molecules also carry magnets").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex("C=O: weak fridge magnets (dipole-dipole)").scale(1.05).shift(band_shift(9) + UP * 1.1)
        b9_l2 = Tex("O--H: handshakes (hydrogen bonds)").scale(1.05).shift(band_shift(9) + UP * 0.2)
        self.play(Write(b9_l1))
        self.wait(2.5)
        self.play(Write(b9_l2))
        self.wait(2.5)
        b9_l3 = MathTex(r"-0{,}5 \;<\; 48{,}8 \;<\; 97{,}2 \;<\; 141\ ^\circ\text{C}").scale(1.05).shift(band_shift(9) + DOWN * 0.8)
        self.play(Write(b9_l3))
        self.wait(2.5)
        b9_l4 = Tex("Acids hold hands in pairs: two H-bonds").scale(1.05).shift(band_shift(9) + DOWN * 1.7)
        self.play(Write(b9_l4))
        self.wait(2)
        b9_rank = Tex("alkane, aldehyde/ketone, alcohol, acid").scale(1.0).shift(band_shift(9) + DOWN * 2.7)
        self.play(Write(b9_rank))
        self.play(Create(SurroundingRectangle(b9_rank, color=GREEN)))
        self.wait(3)

        # --- Band 10 (subtopic_7): why nail polish remover disappears ---
        self.next_band(10)
        b10_title = Tex("Why nail polish remover disappears").scale(1.15).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_title))
        self.wait(2)
        b10_l1 = Tex("Weak grip: many escape the surface").scale(1.05).shift(band_shift(10) + UP * 1.1)
        b10_l2 = Tex("High vapour pressure: volatile").scale(1.05).shift(band_shift(10) + UP * 0.2)
        self.play(Write(b10_l1))
        self.wait(2)
        self.play(Write(b10_l2))
        self.wait(2)
        b10_l3 = Tex("Strong grip: few escape, low v.p.").scale(1.05).shift(band_shift(10) + DOWN * 0.7)
        self.play(Write(b10_l3))
        self.wait(2)
        b10_wrong = Tex("High b.p. AND high v.p. together").scale(1.05).shift(band_shift(10) + DOWN * 1.6)
        self.play(Write(b10_wrong))
        self.play(Create(strike(b10_wrong)))
        self.wait(2)
        b10_rule = Tex("Same ladder, two readouts facing apart").scale(1.05).shift(band_shift(10) + DOWN * 2.6)
        self.play(Write(b10_rule))
        self.play(Create(SurroundingRectangle(b10_rule, color=GREEN)))
        self.wait(4)
