from manim import *

# Band-layout whiteboard scene for "Momentum, Impulse and Collisions"
# (Part 1 Expert subtopics 1-4, Part 2 Simplifier subtopics 5-7).
# Exporter-safe vocabulary only; write-only reveals; camera moves between
# bands. Subtopic durations 225/235/220/240/185/185/190 of 1480 s.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class MomentumImpulseCollisionsSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): definition + first calculation ---
        title = Tex("Momentum, Impulse and Collisions").scale(1.25).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_def = Tex("Momentum $=$ mass $\\times$ velocity (a VECTOR)").scale(1.05).shift(UP * 1.2)
        b0_f = MathTex(r"p = mv \;\; [\text{kg·m·s}^{-1}]").scale(1.15).shift(UP * 0.3)
        self.play(Write(b0_def))
        self.wait(2)
        self.play(Write(b0_f))
        self.wait(2)
        b0_l1 = Tex(r"1 200 kg bakkie at 20 m$\cdot$s$^{-1}$ east:").scale(1.05).shift(DOWN * 0.7)
        b0_l2 = MathTex(r"p = 1\,200 \times 20").scale(1.1).shift(DOWN * 1.6)
        b0_l3 = MathTex(r"p = 24\,000\ \text{kg·m·s}^{-1}\ \text{east}").scale(1.1).shift(DOWN * 2.5)
        self.play(Write(b0_l1))
        self.wait(2)
        self.play(Write(b0_l2))
        self.wait(2)
        self.play(Write(b0_l3))
        self.play(Create(SurroundingRectangle(b0_l3, color=GREEN)))
        self.wait(3)

        # --- Band 1 (subtopic_1): vector change of momentum + N2 in p-form ---
        self.next_band(1)
        b1_title = Tex("Ball rebounds off a wall (signs at work)").scale(1.1).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l0 = Tex("Toward the wall $= +$; 0,5 kg; in 10, out 8").scale(1.0).shift(band_shift(1) + UP * 1.3)
        self.play(Write(b1_l0))
        self.wait(2)
        b1_wrong = MathTex(r"\Delta p = 0{,}5 \times (10 - 8) = 1").scale(1.05).shift(band_shift(1) + UP * 0.4)
        self.play(Write(b1_wrong))
        self.play(Create(strike(b1_wrong)))
        self.wait(2)
        b1_l1 = MathTex(r"p_i = 0{,}5 \times (+10) = 5").scale(1.1).shift(band_shift(1) + DOWN * 0.5)
        b1_l2 = MathTex(r"p_f = 0{,}5 \times (-8) = -4").scale(1.1).shift(band_shift(1) + DOWN * 1.3)
        b1_l3 = MathTex(r"\Delta p = -4 - 5 = -9\ \text{kg·m·s}^{-1}").scale(1.1).shift(band_shift(1) + DOWN * 2.1)
        self.play(Write(b1_l1))
        self.wait(2)
        self.play(Write(b1_l2))
        self.wait(2)
        self.play(Write(b1_l3))
        self.play(Create(SurroundingRectangle(b1_l3, color=GREEN)))
        self.wait(2)
        b1_law = MathTex(r"F_{net} = \frac{\Delta p}{\Delta t}").scale(1.15).shift(band_shift(1) + DOWN * 3.0)
        self.play(Write(b1_law))
        self.wait(3)

        # --- Band 2 (subtopic_2): impulse-momentum theorem, cricket ball ---
        self.next_band(2)
        b2_title = Tex("Impulse: the cricket ball").scale(1.2).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(1.5)
        b2_thm = MathTex(r"F_{net}\,\Delta t = m\,\Delta v").scale(1.15).shift(band_shift(2) + UP * 1.2)
        self.play(Write(b2_thm))
        self.wait(2)
        b2_l0 = Tex("Toward bowler $= +$: in $-30$, out $+40$").scale(1.0).shift(band_shift(2) + UP * 0.3)
        self.play(Write(b2_l0))
        self.wait(2)
        b2_l1 = MathTex(r"0{,}16 \times 40 - 0{,}16 \times (-30)").scale(1.05).shift(band_shift(2) + DOWN * 0.6)
        b2_l2 = MathTex(r"= 6{,}4 + 4{,}8 = 11{,}2\ \text{N} \cdot \text{s}").scale(1.1).shift(band_shift(2) + DOWN * 1.5)
        self.play(Write(b2_l1))
        self.wait(2.5)
        self.play(Write(b2_l2))
        self.play(Create(SurroundingRectangle(b2_l2, color=GREEN)))
        self.wait(2)
        b2_l3 = MathTex(r"F_{net} = \frac{11{,}2}{0{,}01} = 1\,120\ \text{N}").scale(1.1).shift(band_shift(2) + DOWN * 2.7)
        self.play(Write(b2_l3))
        self.wait(3)

        # --- Band 3 (subtopic_2): the force-time trade and safety devices ---
        self.next_band(3)
        b3_title = Tex("Trade force for time").scale(1.2).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(1.5)
        b3_l1 = Tex(r"Same $\Delta p$, more time, smaller force").scale(1.1).shift(band_shift(3) + UP * 1.1)
        self.play(Write(b3_l1))
        self.wait(2.5)
        b3_l2 = Tex("Airbag, crumple zone, arrestor bed,").scale(1.05).shift(band_shift(3) + UP * 0.2)
        b3_l3 = Tex("hands back, knees bent: all buy time").scale(1.05).shift(band_shift(3) + DOWN * 0.7)
        self.play(Write(b3_l2))
        self.wait(2)
        self.play(Write(b3_l3))
        self.wait(2)
        b3_wrong = Tex("``The airbag is soft''").scale(1.05).shift(band_shift(3) + DOWN * 1.7)
        self.play(Write(b3_wrong))
        self.play(Create(strike(b3_wrong)))
        self.wait(2)
        b3_rule = Tex(r"Say: $\Delta p$ constant, $\Delta t$ up, $F$ down").scale(1.05).shift(band_shift(3) + DOWN * 2.7)
        self.play(Write(b3_rule))
        self.play(Create(SurroundingRectangle(b3_rule, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): conservation of momentum, rifle recoil ---
        self.next_band(4)
        b4_title = Tex("Conservation of linear momentum").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(1.5)
        b4_l0 = Tex("Isolated system: total $p$ stays constant").scale(1.05).shift(band_shift(4) + UP * 1.2)
        self.play(Write(b4_l0))
        self.wait(2.5)
        b4_l1 = Tex(r"Rifle 4 kg at rest fires 0,02 kg at 400 m$\cdot$s$^{-1}$").scale(0.95).shift(band_shift(4) + UP * 0.3)
        self.play(Write(b4_l1))
        self.wait(2)
        b4_l2 = MathTex(r"0 = 0{,}02 \times 400 + 4 \times v").scale(1.1).shift(band_shift(4) + DOWN * 0.6)
        b4_l3 = MathTex(r"4v = -8").scale(1.1).shift(band_shift(4) + DOWN * 1.5)
        b4_l4 = MathTex(r"v = -2\ \text{m} \cdot \text{s}^{-1}\ \text{(recoil)}").scale(1.1).shift(band_shift(4) + DOWN * 2.4)
        self.play(Write(b4_l2))
        self.wait(2.5)
        self.play(Write(b4_l3))
        self.wait(2)
        self.play(Write(b4_l4))
        self.play(Create(SurroundingRectangle(b4_l4, color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_4): coupling trolleys + kinetic energy audit ---
        self.next_band(5)
        b5_title = Tex("Trolleys couple: elastic or inelastic?").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(1.5)
        b5_l1 = MathTex(r"p_{before} = 2 \times 3 + 1 \times 0 = 6").scale(1.05).shift(band_shift(5) + UP * 1.2)
        b5_l2 = MathTex(r"3v = 6 \;\Rightarrow\; v = 2\ \text{m·s}^{-1}").scale(1.05).shift(band_shift(5) + UP * 0.3)
        self.play(Write(b5_l1))
        self.wait(2.5)
        self.play(Write(b5_l2))
        self.play(Create(SurroundingRectangle(b5_l2, color=GREEN)))
        self.wait(2.5)
        b5_l3 = MathTex(r"E_{k,before} = \tfrac{1}{2} \times 2 \times 3^2 = 9\ \text{J}").scale(1.05).shift(band_shift(5) + DOWN * 0.8)
        b5_l4 = MathTex(r"E_{k,after} = \tfrac{1}{2} \times 3 \times 2^2 = 6\ \text{J}").scale(1.05).shift(band_shift(5) + DOWN * 1.7)
        self.play(Write(b5_l3))
        self.wait(2.5)
        self.play(Write(b5_l4))
        self.wait(2)
        b5_l5 = Tex("$E_k$ dropped: INELASTIC ($p$ still conserved)").scale(1.0).shift(band_shift(5) + DOWN * 2.7)
        self.play(Write(b5_l5))
        self.play(Create(SurroundingRectangle(b5_l5, color=GREEN)))
        self.wait(3)

        # --- Band 6 (subtopic_4): road-scale collision ---
        self.next_band(6)
        b6_title = Tex("Car 1 000 kg at 15 hits bakkie 1 500 kg").scale(1.1).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(2)
        b6_l1 = MathTex(r"p_{before} = 1\,000 \times 15 = 15\,000").scale(1.05).shift(band_shift(6) + UP * 1.1)
        b6_l2 = MathTex(r"v = \frac{15\,000}{2\,500} = 6\ \text{m} \cdot \text{s}^{-1}").scale(1.05).shift(band_shift(6) + UP * 0.0)
        self.play(Write(b6_l1))
        self.wait(2.5)
        self.play(Write(b6_l2))
        self.play(Create(SurroundingRectangle(b6_l2, color=GREEN)))
        self.wait(2.5)
        b6_l3 = MathTex(r"E_k: 112\,500\ \text{J} \;\rightarrow\; 45\,000\ \text{J}").scale(1.05).shift(band_shift(6) + DOWN * 1.2)
        self.play(Write(b6_l3))
        self.wait(2)
        b6_l4 = Tex("Inelastic — by calculation, not guesswork").scale(1.05).shift(band_shift(6) + DOWN * 2.2)
        self.play(Write(b6_l4))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 7 (subtopic_5): moving oomph ---
        self.next_band(7)
        b7_title = Tex("Moving oomph: mass AND speed count").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(2)
        b7_l1 = Tex("Coal truck: huge mass. Pellet: huge speed.").scale(1.05).shift(band_shift(7) + UP * 1.1)
        b7_l2 = MathTex(r"p = mv \quad \text{(oomph with a direction)}").scale(1.1).shift(band_shift(7) + UP * 0.2)
        self.play(Write(b7_l1))
        self.wait(2.5)
        self.play(Write(b7_l2))
        self.wait(2.5)
        b7_l3 = Tex(r"Bounce: $+10$ to $-8$ beats $10$ to $0$").scale(1.05).shift(band_shift(7) + DOWN * 0.8)
        self.play(Write(b7_l3))
        self.wait(2.5)
        b7_l4 = Tex("Signs track which way the oomph points").scale(1.05).shift(band_shift(7) + DOWN * 1.8)
        self.play(Write(b7_l4))
        self.play(Create(SurroundingRectangle(b7_l4, color=GREEN)))
        self.wait(3)

        # --- Band 8 (subtopic_6): the egg and the duvet ---
        self.next_band(8)
        b8_title = Tex("The egg and the duvet").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = Tex("Wall: change crammed into a millisecond").scale(1.05).shift(band_shift(8) + UP * 1.1)
        b8_l2 = Tex("Duvet: same change over half a second").scale(1.05).shift(band_shift(8) + UP * 0.2)
        self.play(Write(b8_l1))
        self.wait(2.5)
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = Tex("More time, less force — egg survives").scale(1.05).shift(band_shift(8) + DOWN * 0.7)
        self.play(Write(b8_l3))
        self.wait(2)
        b8_l4 = Tex(r"1. $\Delta p$ fixed \; 2. $\Delta t$ up \; 3. $F$ down").scale(1.05).shift(band_shift(8) + DOWN * 1.7)
        self.play(Write(b8_l4))
        self.play(Create(SurroundingRectangle(b8_l4, color=GREEN)))
        self.wait(2)
        b8_l5 = Tex("Airbag $=$ a duvet for your face").scale(1.05).shift(band_shift(8) + DOWN * 2.7)
        self.play(Write(b8_l5))
        self.wait(3)

        # --- Band 9 (subtopic_7): trolleys that crash and stick ---
        self.next_band(9)
        b9_title = Tex("Trolleys that crash and stick").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex("6 units of oomph shared by 3 mass units").scale(1.05).shift(band_shift(9) + UP * 1.1)
        b9_l2 = MathTex(r"v = \frac{6}{3} = 2").scale(1.1).shift(band_shift(9) + UP * 0.0)
        self.play(Write(b9_l1))
        self.wait(2.5)
        self.play(Write(b9_l2))
        self.play(Create(SurroundingRectangle(b9_l2, color=GREEN)))
        self.wait(2.5)
        b9_l3 = Tex("Inside pushes are equal and opposite:").scale(1.05).shift(band_shift(9) + DOWN * 1.1)
        b9_l4 = Tex("momentum only changes pockets").scale(1.05).shift(band_shift(9) + DOWN * 2.0)
        self.play(Write(b9_l3))
        self.wait(2)
        self.play(Write(b9_l4))
        self.wait(2)
        b9_l5 = Tex("Sticking $=$ inelastic: some $E_k$ leaks away").scale(1.0).shift(band_shift(9) + DOWN * 2.9)
        self.play(Write(b9_l5))
        self.play(Create(SurroundingRectangle(b9_l5, color=GREEN)))
        self.wait(4)
