from manim import *

# Band-layout whiteboard scene for "High-Pressure Cells and Travelling
# Disturbances" (grade 12, term 1, subtropical anticyclones). All seven
# subtopics: Part 1 Expert (1-4), Part 2 Simplifier (5-7). Band time
# apportioned to subtopics.json (235/255/255/245/195/205/210 of 1600 s).
# Exporter-safe primitives only; the three-highs map and the inversion-lid
# cross-section are hand-built from Line/Arrow/Circle/Rectangle/Tex.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class SubtropicalAnticyclonesSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic full-screen while intro.md audio plays.
        self.wait(15)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): the three highs on the map
        title = Tex("Subtropical Anticyclones").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex(r"SA sits at $\approx 30^\circ$S: the sinking belt").scale(1.0).shift(UP * 1.4)
        self.play(Write(b0_l1))
        self.wait(2)
        # Sketch map: SA block with the three highs around/on it.
        sa = Rectangle(width=2.6, height=1.6).shift(DOWN * 0.4)
        sa_lab = Tex("SA").scale(0.9).shift(DOWN * 0.4)
        self.play(Create(sa), Write(sa_lab))
        h1 = Circle(radius=0.55, color=YELLOW).shift(DOWN * 0.4 + LEFT * 4.2)
        h1_lab = Tex(r"H\\ S Atlantic").scale(0.7).shift(DOWN * 0.4 + LEFT * 4.2)
        self.play(Create(h1), Write(h1_lab))
        self.wait(1.5)
        h2 = Circle(radius=0.55, color=YELLOW).shift(DOWN * 0.4 + RIGHT * 4.2)
        h2_lab = Tex(r"H\\ S Indian").scale(0.7).shift(DOWN * 0.4 + RIGHT * 4.2)
        self.play(Create(h2), Write(h2_lab))
        self.wait(1.5)
        h3 = Circle(radius=0.45, color=ORANGE).shift(DOWN * 0.35)
        h3_lab = Tex("Kalahari H").scale(0.65).shift(UP * 0.45)
        self.play(Create(h3), Write(h3_lab))
        self.wait(2)
        b0_l2 = Tex(r"Anticlockwise around a HIGH down here —").scale(1.0).shift(DOWN * 2.0)
        b0_l3 = Tex(r"clockwise around a low").scale(1.0).shift(DOWN * 2.7)
        self.play(Write(b0_l2))
        self.play(Write(b0_l3))
        self.play(Create(SurroundingRectangle(b0_l2, color=GREEN)))
        self.wait(3)

        # --- Band 1 (subtopic_1): character of the three cells
        self.next_band(1)
        b1_title = Tex("Sinking air stamps the weather").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l1 = Tex(r"Subsiding air warms, dissolves cloud:").scale(1.0).shift(band_shift(1) + UP * 1.2)
        b1_l2 = Tex(r"stable, clear, dry — 60\%$+$ of SA semi-arid").scale(0.95).shift(band_shift(1) + UP * 0.5)
        self.play(Write(b1_l1))
        self.play(Write(b1_l2))
        self.wait(2.5)
        b1_l3 = Tex(r"S Atlantic High: cool air up the west coast,").scale(0.95).shift(band_shift(1) + DOWN * 0.4)
        b1_l4 = Tex(r"Benguela upwelling — fog, Namib aridity").scale(0.95).shift(band_shift(1) + DOWN * 1.1)
        self.play(Write(b1_l3))
        self.play(Write(b1_l4))
        self.wait(2.5)
        b1_l5 = Tex(r"S Indian High: warm moist air onto the").scale(0.95).shift(band_shift(1) + DOWN * 2.0)
        b1_l6 = Tex(r"east coast — KZN's humid summers").scale(0.95).shift(band_shift(1) + DOWN * 2.7)
        self.play(Write(b1_l5))
        self.play(Write(b1_l6))
        self.wait(2.5)
        b1_l7 = Tex(r"Kalahari High: seasonal — strong low lid in").scale(0.9).shift(band_shift(1) + DOWN * 3.5)
        b1_l8 = Tex(r"winter, weak and lifted in summer").scale(0.9).shift(band_shift(1) + DOWN * 4.1)
        b1_l8.shift(UP * 0.05)
        self.play(Write(b1_l7))
        self.play(Write(b1_l8))
        self.wait(3)

        # --- Band 2 (subtopic_2): the inversion lid, winter vs summer
        self.next_band(2)
        b2_title = Tex("Mechanism 1: the inversion lid").scale(1.2).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(1.5)
        # Escarpment cross-section: sea level left, step up to plateau right.
        sea = Line(band_shift(2) + DOWN * 2.4 + LEFT * 5.6, band_shift(2) + DOWN * 2.4 + LEFT * 2.6)
        step = Line(band_shift(2) + DOWN * 2.4 + LEFT * 2.6, band_shift(2) + DOWN * 0.9 + LEFT * 1.6)
        plateau = Line(band_shift(2) + DOWN * 0.9 + LEFT * 1.6, band_shift(2) + DOWN * 0.9 + RIGHT * 5.6)
        esc_lab = Tex("escarpment").scale(0.75).shift(band_shift(2) + DOWN * 2.0 + LEFT * 1.0)
        plat_lab = Tex("plateau").scale(0.75).shift(band_shift(2) + DOWN * 1.3 + RIGHT * 4.6)
        self.play(Create(sea), Create(step), Create(plateau))
        self.play(Write(esc_lab), Write(plat_lab))
        self.wait(2)
        winter_lid = Line(band_shift(2) + DOWN * 1.5 + LEFT * 5.6, band_shift(2) + DOWN * 1.5 + LEFT * 2.2, color=BLUE)
        winter_lab = Tex(r"winter lid below step:\\ interior dry").scale(0.85).shift(band_shift(2) + DOWN * 3.2 + LEFT * 2.6)
        self.play(Create(winter_lid), Write(winter_lab))
        self.wait(2.5)
        summer_lid = Line(band_shift(2) + UP * 0.6 + LEFT * 5.6, band_shift(2) + UP * 0.6 + RIGHT * 5.6, color=RED)
        summer_lab = Tex(r"summer lid: lifts high — moist air floods\\ in, afternoon thunderstorms").scale(0.8).shift(band_shift(2) + UP * 1.4 + RIGHT * 1.6)
        self.play(Create(summer_lid), Write(summer_lab))
        self.wait(2.5)
        b2_l1 = Tex(r"One moving lid: dry Joburg winters,\\ stormy Joburg summers").scale(0.85).shift(band_shift(2) + DOWN * 3.3 + RIGHT * 3.3)
        self.play(Write(b2_l1))
        self.wait(3)

        # --- Band 3 (subtopic_2): shift, currents, ridging
        self.next_band(3)
        b3_title = Tex("Shift, currents and ridging").scale(1.2).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(1.5)
        b3_l1 = Tex(r"Belt migrates with the sun: north in winter").scale(0.95).shift(band_shift(3) + UP * 1.3)
        b3_l2 = Tex(r"(fronts rain on the Cape), south in summer").scale(0.95).shift(band_shift(3) + UP * 0.6)
        self.play(Write(b3_l1))
        self.play(Write(b3_l2))
        self.wait(2.5)
        b3_l3 = Tex(r"Cold Benguela west: fog, desert shore;").scale(0.95).shift(band_shift(3) + DOWN * 0.3)
        b3_l4 = Tex(r"warm Agulhas east: humid, green coast").scale(0.95).shift(band_shift(3) + DOWN * 1.0)
        self.play(Write(b3_l3))
        self.play(Write(b3_l4))
        self.wait(2.5)
        b3_l5 = Tex(r"Ridging: Atlantic High hooks a tongue").scale(0.95).shift(band_shift(3) + DOWN * 1.9)
        b3_l6 = Tex(r"behind each front — onshore air, rain").scale(0.95).shift(band_shift(3) + DOWN * 2.6)
        b3_l7 = Tex(r"for the south coast in ALL seasons").scale(0.95).shift(band_shift(3) + DOWN * 3.3)
        self.play(Write(b3_l5))
        self.play(Write(b3_l6))
        self.play(Write(b3_l7))
        self.play(Create(SurroundingRectangle(b3_l7, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): the moisture front
        self.next_band(4)
        b4_title = Tex("Travelling disturbance 1: moisture front").scale(1.1).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(1.5)
        b4_l1 = Tex(r"Summer interior: moist tropical air (NE)").scale(0.95).shift(band_shift(4) + UP * 1.2)
        b4_l2 = Tex(r"meets dry hot western air — the dry line").scale(0.95).shift(band_shift(4) + UP * 0.5)
        self.play(Write(b4_l1))
        self.play(Write(b4_l2))
        self.wait(2.5)
        # The front as a NW-SE line with storm dots along it.
        mf = Line(band_shift(4) + UP * 0.0 + LEFT * 3.8, band_shift(4) + DOWN * 1.8 + RIGHT * 2.8, color=PURPLE)
        self.play(Create(mf))
        d1 = Dot(band_shift(4) + DOWN * 0.35 + LEFT * 2.6, color=YELLOW)
        d2 = Dot(band_shift(4) + DOWN * 0.9 + LEFT * 0.6, color=YELLOW)
        d3 = Dot(band_shift(4) + DOWN * 1.45 + RIGHT * 1.4, color=YELLOW)
        mf_lab = Tex(r"line thunderstorms,\\ 100s of km").scale(0.8).shift(band_shift(4) + DOWN * 0.6 + RIGHT * 3.6)
        self.play(Create(d1), Create(d2), Create(d3), Write(mf_lab))
        self.wait(2.5)
        b4_l3 = Tex(r"Highveld afternoons: downpours, lightning,").scale(0.95).shift(band_shift(4) + DOWN * 2.5)
        b4_l4 = Tex(r"hail, flash floods — SAWS warnings, hail").scale(0.95).shift(band_shift(4) + DOWN * 3.2)
        b4_l5 = Tex(r"nets, storm-water maintenance").scale(0.95).shift(band_shift(4) + DOWN * 3.9)
        b4_l5.shift(UP * 0.05)
        self.play(Write(b4_l3))
        self.play(Write(b4_l4))
        self.play(Write(b4_l5))
        self.wait(3)

        # --- Band 5 (subtopic_3): coastal low and berg wind
        self.next_band(5)
        b5_title = Tex("Coastal low and berg wind").scale(1.2).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(1.5)
        b5_l1 = Tex(r"Coastal low: shallow cell under the").scale(0.95).shift(band_shift(5) + UP * 1.3)
        b5_l2 = Tex(r"escarpment, sliding west coast $\to$ KZN").scale(0.95).shift(band_shift(5) + UP * 0.6)
        self.play(Write(b5_l1))
        self.play(Write(b5_l2))
        self.wait(2.5)
        b5_l3 = Tex(r"Ahead: hot dry offshore air. Behind: cool").scale(0.95).shift(band_shift(5) + DOWN * 0.3)
        b5_l4 = Tex(r"onshore air — 10 $^\circ$C drop in an hour").scale(0.95).shift(band_shift(5) + DOWN * 1.0)
        self.play(Write(b5_l3))
        self.play(Write(b5_l4))
        self.wait(2.5)
        b5_l5 = Tex(r"Berg wind: plateau air falls 1 km$+$ off the").scale(0.95).shift(band_shift(5) + DOWN * 1.9)
        b5_l6 = MathTex(r"\text{escarpment warming: } 1\,^\circ\text{C per } 100 \text{ m}").scale(0.85).shift(band_shift(5) + DOWN * 2.6)
        self.play(Write(b5_l5))
        self.play(Write(b5_l6))
        self.play(Create(SurroundingRectangle(b5_l6, color=GREEN)))
        self.wait(2.5)
        b5_l7 = Tex(r"Hot, dry, gusty: 30 $^\circ$C$+$ July days, peak fire").scale(0.9).shift(band_shift(5) + DOWN * 3.4)
        b5_l8 = Tex(r"danger — Knysna 2017; fire bans, firebreaks").scale(0.9).shift(band_shift(5) + DOWN * 4.05)
        b5_l8.shift(UP * 0.15)
        self.play(Write(b5_l7))
        self.play(Write(b5_l8))
        self.wait(3)

        # --- Band 6 (subtopic_4): the chart drill — highs and season
        self.next_band(6)
        b6_title = Tex("Chart drill: highs and season").scale(1.2).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(1.5)
        b6_l1 = Tex(r"Closed isobars round H: Atlantic west,").scale(0.95).shift(band_shift(6) + UP * 1.3)
        b6_l2 = Tex(r"Indian east, Kalahari inland (winter);").scale(0.95).shift(band_shift(6) + UP * 0.6)
        b6_l3 = Tex(r"centres 1020 hPa$+$, winter interior 1030$+$").scale(0.95).shift(band_shift(6) + DOWN * 0.1)
        self.play(Write(b6_l1))
        self.play(Write(b6_l2))
        self.play(Write(b6_l3))
        self.wait(3)
        b6_l4 = Tex(r"Season at a glance: interior H $+$ fronts far").scale(0.95).shift(band_shift(6) + DOWN * 1.0)
        b6_l5 = Tex(r"south $=$ winter; heat low $+$ storms $=$ summer").scale(0.95).shift(band_shift(6) + DOWN * 1.7)
        self.play(Write(b6_l4))
        self.play(Write(b6_l5))
        self.play(Create(SurroundingRectangle(b6_l5, color=GREEN)))
        self.wait(2.5)
        b6_l6 = Tex(r"Confirm with dew points: moist teens in").scale(0.95).shift(band_shift(6) + DOWN * 2.6)
        b6_l7 = Tex(r"summer, dry single digits in winter").scale(0.95).shift(band_shift(6) + DOWN * 3.3)
        self.play(Write(b6_l6))
        self.play(Write(b6_l7))
        self.wait(3)

        # --- Band 7 (subtopic_4): signatures and prediction
        self.next_band(7)
        b7_title = Tex("Signatures and prediction").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(1.5)
        b7_l1 = Tex(r"Ridging: isobars bulge east round the south").scale(0.95).shift(band_shift(7) + UP * 1.3)
        b7_l2 = Tex(r"coast — onshore SW winds, cool, drizzle").scale(0.95).shift(band_shift(7) + UP * 0.6)
        self.play(Write(b7_l1))
        self.play(Write(b7_l2))
        self.wait(2.5)
        b7_l3 = Tex(r"Coastal low: tight cell on the coast ahead").scale(0.95).shift(band_shift(7) + DOWN * 0.3)
        b7_l4 = Tex(r"of a front; offshore ahead, onshore behind").scale(0.95).shift(band_shift(7) + DOWN * 1.0)
        self.play(Write(b7_l3))
        self.play(Write(b7_l4))
        self.wait(2.5)
        b7_l5 = Tex(r"Moisture front: interior trough, moist NE").scale(0.95).shift(band_shift(7) + DOWN * 1.9)
        b7_l6 = Tex(r"side; satellite shows the diagonal Cb line").scale(0.95).shift(band_shift(7) + DOWN * 2.6)
        self.play(Write(b7_l5))
        self.play(Write(b7_l6))
        self.wait(2.5)
        b7_l7 = Tex(r"Predict west $\to$ east, and always give the").scale(0.95).shift(band_shift(7) + DOWN * 3.4)
        b7_l8 = Tex(r"MECHANISM — marks attach to mechanism").scale(0.95).shift(band_shift(7) + DOWN * 4.05)
        b7_l8.shift(UP * 0.1)
        self.play(Write(b7_l7))
        self.play(Write(b7_l8))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): three guards around the country
        self.next_band(8)
        b8_title = Tex("Three guards around the country").scale(1.15).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = Tex(r"Sinking air is the destroyer of weather:").scale(0.95).shift(band_shift(8) + UP * 1.3)
        b8_l2 = Tex(r"it warms as it squashes and eats cloud").scale(0.95).shift(band_shift(8) + UP * 0.6)
        self.play(Write(b8_l1))
        self.play(Write(b8_l2))
        self.play(Create(SurroundingRectangle(b8_l2, color=GREEN)))
        self.wait(2.5)
        b8_l3 = Tex(r"West guard: cold sea, fog, the Namib;").scale(0.95).shift(band_shift(8) + DOWN * 0.3)
        b8_l4 = Tex(r"east guard: warm wet-towel Durban air;").scale(0.95).shift(band_shift(8) + DOWN * 1.0)
        b8_l5 = Tex(r"inside guard (Kalahari): the moody one").scale(0.95).shift(band_shift(8) + DOWN * 1.7)
        self.play(Write(b8_l3))
        self.wait(2)
        self.play(Write(b8_l4))
        self.wait(2)
        self.play(Write(b8_l5))
        self.wait(2)
        b8_l6 = Tex(r"Highs go AGAINST the clock down here —").scale(0.95).shift(band_shift(8) + DOWN * 2.6)
        b8_l7 = Tex(r"say it three times").scale(0.95).shift(band_shift(8) + DOWN * 3.3)
        self.play(Write(b8_l6))
        self.play(Write(b8_l7))
        self.wait(3)

        # --- Band 9 (subtopic_6): the pot lid over Johannesburg
        self.next_band(9)
        b9_title = Tex("The pot lid over Johannesburg").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex(r"Pot $=$ plateau; lid $=$ inversion layer").scale(1.0).shift(band_shift(9) + UP * 1.3)
        self.play(Write(b9_l1))
        self.play(Create(SurroundingRectangle(b9_l1, color=GREEN)))
        self.wait(2.5)
        b9_l2 = Tex(r"Winter: lid pressed below the escarpment —").scale(0.95).shift(band_shift(9) + UP * 0.4)
        b9_l3 = Tex(r"moist air can't climb the step; frosty,").scale(0.95).shift(band_shift(9) + DOWN * 0.3)
        b9_l4 = Tex(r"cloudless, brown haze trapped under the lid").scale(0.95).shift(band_shift(9) + DOWN * 1.0)
        self.play(Write(b9_l2))
        self.play(Write(b9_l3))
        self.play(Write(b9_l4))
        self.wait(3)
        b9_l5 = Tex(r"Summer: lid lifts, moist air pours in —").scale(0.95).shift(band_shift(9) + DOWN * 1.9)
        b9_l6 = Tex(r"the four-o'clock Highveld storm; storms").scale(0.95).shift(band_shift(9) + DOWN * 2.6)
        b9_l7 = Tex(r"parade along the moisture front").scale(0.95).shift(band_shift(9) + DOWN * 3.3)
        self.play(Write(b9_l5))
        self.play(Write(b9_l6))
        self.play(Write(b9_l7))
        self.wait(2.5)
        b9_l8 = Tex(r"Guards slide north in winter: Cape rain").scale(0.95).shift(band_shift(9) + DOWN * 4.0)
        b9_l8.shift(UP * 0.1)
        self.play(Write(b9_l8))
        self.wait(3)

        # --- Band 10 (subtopic_7): the hairdryer and the cool change
        self.next_band(10)
        b10_title = Tex("The hairdryer and the cool change").scale(1.15).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_title))
        self.wait(2)
        b10_l1 = Tex(r"Berg wind: plateau air spills off the edge,").scale(0.95).shift(band_shift(10) + UP * 1.3)
        b10_l2 = MathTex(r"+1\,^\circ\text{C per } 100 \text{ m} \to 10\,^\circ\text{C hotter}").scale(0.9).shift(band_shift(10) + UP * 0.5)
        self.play(Write(b10_l1))
        self.play(Write(b10_l2))
        self.play(Create(SurroundingRectangle(b10_l2, color=GREEN)))
        self.wait(3)
        b10_l3 = Tex(r"34 $^\circ$C in July on the coast; the fire wind —").scale(0.9).shift(band_shift(10) + DOWN * 0.5)
        b10_l4 = Tex(r"Knysna 2017: fire bans, standby crews").scale(0.9).shift(band_shift(10) + DOWN * 1.2)
        self.play(Write(b10_l3))
        self.play(Write(b10_l4))
        self.wait(2.5)
        b10_l5 = Tex(r"Coastal low: a bead on a string ahead of").scale(0.95).shift(band_shift(10) + DOWN * 2.1)
        b10_l6 = Tex(r"the front — hairdryer ahead, cool change").scale(0.95).shift(band_shift(10) + DOWN * 2.8)
        b10_l7 = Tex(r"behind: sweating at breakfast, jersey by supper").scale(0.9).shift(band_shift(10) + DOWN * 3.5)
        self.play(Write(b10_l5))
        self.play(Write(b10_l6))
        self.play(Write(b10_l7))
        self.wait(2.5)
        b10_l8 = Tex(r"One chain: guards, lid, hairdryer, bead").scale(1.0).shift(band_shift(10) + DOWN * 4.2)
        b10_l8.shift(UP * 0.35)
        self.play(Write(b10_l8))
        self.play(Create(SurroundingRectangle(b10_l8, color=GREEN)))
        self.wait(4)
