import os

def get_file_content(filepath):
    try:
        with open(filepath, 'r') as f:
            return f.read()
    except Exception as e:
        return f"Error reading file: {e}"

def generate_structure_with_contents(startpath, exclude_dirs=None):
    if exclude_dirs is None:
        exclude_dirs = {'.git', '__pycache__', 'node_modules'}

    output = []
    for root, dirs, files in os.walk(startpath):
        dirs[:] = [d for d in dirs if d not in exclude_dirs]
        dirs.sort()

        rel_root = os.path.relpath(root, startpath)
        if rel_root == '.':
            rel_root = os.path.basename(startpath)

        level = rel_root.count(os.sep)

        # Folder Header
        output.append(f"{'#' * (level + 2)} Folder: `{rel_root}/`")
        output.append(f"> Description: Content for {rel_root}")
        output.append("")

        for f in sorted(files):
            filepath = os.path.join(root, f)
            rel_filepath = os.path.relpath(filepath, startpath)

            output.append(f"{'#' * (level + 3)} File: `{rel_filepath}`")
            output.append("```markdown")
            output.append(get_file_content(filepath))
            output.append("```")
            output.append("")

    return "\n".join(output)

def generate_tree(startpath, exclude_dirs=None):
    if exclude_dirs is None:
        exclude_dirs = {'.git', '__pycache__'}

    tree = []
    for root, dirs, files in os.walk(startpath):
        dirs[:] = [d for d in dirs if d not in exclude_dirs]
        level = root.replace(startpath, '').count(os.sep)
        indent = '  ' * level
        tree.append(f'{indent}{os.path.basename(root)}/')
        subindent = '  ' * (level + 1)
        for f in sorted(files):
            tree.append(f'{subindent}{f}')
    return '\n'.join(tree)

def update_structure_books():
    content = """# RokctAI Book Factory — Books Structure
> Content lives in `books/`

## Hierarchy
```
"""
    content += generate_tree('books')
    content += """
```

## Status Progression
`idea_generated` → `pending_approval` → `concept_expanding` → `concept_generated` → `pending_concept_approval` → `rules_generating` → `rules_generated` → `pending_rules_approval` → `writing` → `evaluating` → `draft_ready` → `pending_acceptance` → `publishing` → `published`
"""
    with open('STRUCTURE_BOOKS.md', 'w') as f:
        f.write(content)

def update_structure_bible():
    content = """# RokctAI Book Factory — Bible Series Structure
> Content lives in `bible/`

This file is automatically generated and contains the full content of all files in the `bible/` directory.

"""
    content += generate_structure_with_contents('bible')

    content += """
---
## Metarules
Located in `.rokct/types/series_episode/metarules/`:
- `world_rules.md`: Governing truth (Master Thread)
- `episode_rules.md`: Required 6-section structure
- `impact_metrics.md`: Evaluation criteria (Textual Integrity, The Punch, Thread Alignment)
- `audit_rules.md`: Verification chain and standards
"""
    with open('STRUCTURE_BIBLE.md', 'w') as f:
        f.write(content)

def update_structure_main():
    content = """# Repository Map — RokctAI Book Factory

This repository contains two parallel content streams managed by the same agent infrastructure.

## 1. Books Stream (`books/`)
Automated publishing factory for poetry, fiction, and children's books.
- **Rules:** `.rokct/types/{poetry|fiction|children|short_story}/`
- **Output:** `books/published/`
- **See:** [STRUCTURE_BOOKS.md](STRUCTURE_BOOKS.md)

## 2. Bible Series Stream (`bible/`)
Long-form research series exploring the hidden architecture of scripture.
- **Rules:** `.rokct/types/series_episode/`
- **Output:** `bible/{series_name}/`
- **See:** [STRUCTURE_BIBLE.md](STRUCTURE_BIBLE.md)

---

## Shared Infrastructure

### .rokct/
- **agent/**: Prompts, jobs, ledger, and guardrails.
- **skills/**: Ported skills from RokctAI/opportunities.
- **templates/**: Shared document stubs.

### .github/workflows/
Pipeline levels 0-6 managing the automated creation and publishing loop.

---

## Documentation
- [PLANNING.md](PLANNING.md): Core vision and technical specification.
- [README.md](README.md): Project overview and setup.
"""
    with open('STRUCTURE.md', 'w') as f:
        f.write(content)

if __name__ == "__main__":
    update_structure_books()
    update_structure_bible()
    update_structure_main()
    print("✅ Structure files updated successfully with full Bible contents.")
