import os

def get_file_content(filepath):
    try:
        with open(filepath, 'r') as f:
            return f.read()
    except Exception as e:
        return f"Error reading file: {e}"

def generate_structure_with_contents(startpath, exclude_dirs=None, exclude_files=None):
    if exclude_dirs is None:
        exclude_dirs = {'.git', '__pycache__', 'node_modules', 'published'}
    if exclude_files is None:
        exclude_files = {'.gitkeep', 'transitions.log', 'errors.log'}

    output = []
    for root, dirs, files in os.walk(startpath):
        dirs[:] = [d for d in dirs if d not in exclude_dirs]
        dirs.sort()

        rel_root = os.path.relpath(root, startpath)
        if rel_root == '.':
            rel_root = os.path.basename(os.path.abspath(startpath))

        level = rel_root.count(os.sep)

        # Folder Header
        output.append(f"{'#' * (level + 2)} Folder: `{rel_root}/`")
        output.append(f"> Description: Content for {rel_root}")
        output.append("")

        for f in sorted(files):
            if f in exclude_files:
                continue
            filepath = os.path.join(root, f)
            rel_filepath = os.path.relpath(filepath, startpath)

            output.append(f"{'#' * (level + 3)} File: `{rel_filepath}`")
            output.append("```markdown")
            output.append(get_file_content(filepath))
            output.append("```")
            output.append("")

    return "\n".join(output)

def update_structure_books():
    print("Generating STRUCTURE_BOOKS.md...")
    header = """# RokctAI Book Factory — Books Structure
> Content lives in `books/`

This file is automatically generated and contains the full content of templates and drafts for the Books Stream.

"""
    body = generate_structure_with_contents('books')
    footer = """
## Status Progression
`idea_generated` → `pending_approval` → `concept_expanding` → `concept_generated` → `pending_concept_approval` → `rules_generating` → `rules_generated` → `pending_rules_approval` → `writing` → `evaluating` → `draft_ready` → `pending_acceptance` → `publishing` → `published`
"""
    with open('STRUCTURE_BOOKS.md', 'w') as f:
        f.write(header + body + footer)

def update_structure_bible():
    print("Generating STRUCTURE_BIBLE.md...")
    header = """# RokctAI Book Factory — Bible Series Structure
> Content lives in `bible/`

This file is automatically generated and contains the full content of all files in the Bible Series Stream, including its governing metarules.

"""
    body = generate_structure_with_contents('bible')

    metarules_path = '.rokct/types/bible.series/metarules/'
    metarules_content = ""
    if os.path.exists(metarules_path):
        metarules_content = "\n---\n## Metarules (Full Content)\n"
        metarules_content += f"> Location: `{metarules_path}`\n\n"
        for f in sorted(os.listdir(metarules_path)):
            if f.endswith('.md'):
                metarules_content += f"### Metarule: `{f}`\n"
                metarules_content += "```markdown\n"
                metarules_content += get_file_content(os.path.join(metarules_path, f))
                metarules_content += "```\n\n"

    with open('STRUCTURE_BIBLE.md', 'w') as f:
        f.write(header + body + metarules_content)

def update_structure_film():
    print("Generating STRUCTURE_FILM.md...")
    header = """# RokctAI Book Factory — Film Series Structure
> Content lives in `film/`

This file is automatically generated and contains the full content of all files in the Film Series Stream, including its governing metarules.

"""
    body = generate_structure_with_contents('film')

    metarules_path = '.rokct/types/film.documentary/metarules/'
    metarules_content = ""
    if os.path.exists(metarules_path):
        metarules_content = "\n---\n## Metarules (Full Content)\n"
        metarules_content += f"> Location: `{metarules_path}`\n\n"
        for f in sorted(os.listdir(metarules_path)):
            if f.endswith('.md'):
                metarules_content += f"### Metarule: `{f}`\n"
                metarules_content += "```markdown\n"
                metarules_content += get_file_content(os.path.join(metarules_path, f))
                metarules_content += "```\n\n"

    with open('STRUCTURE_FILM.md', 'w') as f:
        f.write(header + body + metarules_content)


def update_structure_main():
    print("Generating STRUCTURE.md...")
    content = """# Repository Map — RokctAI Book Factory

This repository contains three parallel content streams managed by the same agent infrastructure.

## 1. Books Stream (`books/`)
Automated publishing factory for poetry, fiction, and children's books.
- **Rules:** `.rokct/types/{book.poetry|book.fiction|book.children|book.short_story}/`
- **Output:** `books/published/`
- **See:** [STRUCTURE_BOOKS.md](STRUCTURE_BOOKS.md)

## 2. Bible Series Stream (`bible/`)
Long-form research series exploring the hidden architecture of scripture.
- **Rules:** `.rokct/types/bible.series/`
- **Output:** `bible/{series_name}/`
- **See:** [STRUCTURE_BIBLE.md](STRUCTURE_BIBLE.md)

## 3. Film Stream (`film/`)
Documentary and scripting content output.
- **Rules:** `.rokct/types/film.documentary/`
- **Output:** `film/{project_name}/`
- **See:** [STRUCTURE_FILM.md](STRUCTURE_FILM.md)

---

## Shared Infrastructure (Highlights)

### .rokct/
- **agent/**: Prompts, jobs, ledger, and guardrails.
- **skills/**: Ported skills from RokctAI/opportunities.
- **templates/**: Shared document stubs.

### .github/workflows/
Pipeline levels 0-6 managing the automated creation and publishing loop.

---

## Documentation
- [PLANNING.md](PLANNING.md): Core vision and technical specification.
- [README.md](README.md): Project overview and setup.
"""
    with open('STRUCTURE.md', 'w') as f:
        f.write(content)

if __name__ == "__main__":
    update_structure_books()
    update_structure_bible()
    update_structure_film()
    update_structure_main()
    print("✅ Structure files updated with full file content transparency.")
