from manim import *

# Band-layout whiteboard scene for the Molecular Shapes and Polarity duo.
# Part 1 — Expert: subtopics 1-4; Part 2 — Simplifier: subtopics 5-7.
# Band dwell proportional to subtopics.json (250/240/230/240/185/185/195
# of 1525 s). Exporter-safe mobjects only (energy curve and molecular
# sketches from Lines/Arrows/Dots/Tex); add-only lifecycle; camera bands.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class MolecularShapesPolaritySession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic display while intro.md plays (~4-5% of scene).
        self.wait(14)

        # ===== Part 1 — Expert =====
        # --- Band 0 (subtopic_1): why atoms bond — the energy valley ---
        title = Tex("Molecular Shapes and Polarity").scale(1.2).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex("Bonding LOWERS energy — a valley, not a rule").scale(0.95).shift(UP * 1.5)
        self.play(Write(b0_l1))
        self.wait(2)
        axx = Arrow(LEFT * 4.6 + DOWN * 1.0, RIGHT * 0.6 + DOWN * 1.0, buff=0)
        axy = Arrow(LEFT * 4.6 + DOWN * 2.6, LEFT * 4.6 + UP * 0.8, buff=0)
        lx = Tex("separation").scale(0.7).shift(RIGHT * 0.4 + DOWN * 1.4)
        ly = Tex("energy").scale(0.7).shift(LEFT * 4.4 + UP * 1.05)
        curve = VGroup(
            Line(LEFT * 4.3 + UP * 0.6, LEFT * 3.9 + DOWN * 1.2, color=YELLOW),
            Line(LEFT * 3.9 + DOWN * 1.2, LEFT * 3.3 + DOWN * 2.2, color=YELLOW),
            Line(LEFT * 3.3 + DOWN * 2.2, LEFT * 2.6 + DOWN * 1.9, color=YELLOW),
            Line(LEFT * 2.6 + DOWN * 1.9, LEFT * 1.4 + DOWN * 1.3, color=YELLOW),
            Line(LEFT * 1.4 + DOWN * 1.3, RIGHT * 0.3 + DOWN * 1.05, color=YELLOW),
        )
        self.play(Create(axx), Create(axy), Write(lx), Write(ly))
        self.play(Create(curve))
        vmin = Dot(LEFT * 3.3 + DOWN * 2.2, color=GREEN)
        lmin = Tex("74 pm: bond length").scale(0.75).shift(LEFT * 1.0 + DOWN * 2.5)
        self.play(FadeIn(vmin), Write(lmin))
        self.wait(2.5)
        b0_l2 = Tex("Valley depth $=$ bond energy").scale(0.9).shift(RIGHT * 3.6 + DOWN * 0.2)
        self.play(Write(b0_l2))
        self.wait(2)
        b0_l3 = Tex("Helium: full shell, no valley, no bond").scale(0.9).shift(RIGHT * 3.2 + DOWN * 1.2)
        self.play(Write(b0_l3))
        self.wait(2.5)

        # --- Band 1 (subtopic_1): Lewis diagrams ---
        self.next_band(1)
        b1_title = Tex("Lewis diagrams: dots for valence electrons").scale(1.05).shift(band_shift(1) + UP * 2.3)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l1 = Tex(r"H$_2$O: two bonding pairs, two lone pairs on O").scale(0.95).shift(band_shift(1) + UP * 1.3)
        self.play(Write(b1_l1))
        self.wait(2)
        b1_l2 = Tex(r"NH$_3$: three bonds, one lone pair").scale(0.95).shift(band_shift(1) + UP * 0.4)
        self.play(Write(b1_l2))
        self.wait(2)
        b1_l3 = Tex(r"CH$_4$: four bonds, no lone pairs").scale(0.95).shift(band_shift(1) + DOWN * 0.5)
        self.play(Write(b1_l3))
        self.wait(2)
        b1_l4 = Tex(r"N$_2$: a TRIPLE bond; O$_2$: a double").scale(0.95).shift(band_shift(1) + DOWN * 1.4)
        self.play(Write(b1_l4))
        self.wait(2)
        b1_l5 = Tex(r"Dative: one atom gives BOTH electrons —").scale(0.95).shift(band_shift(1) + DOWN * 2.3)
        b1_l6 = Tex(r"H$_3$O$^+$ and NH$_4^+$").scale(0.95).shift(band_shift(1) + DOWN * 3.0)
        self.play(Write(b1_l5))
        self.play(Write(b1_l6))
        self.wait(2.5)

        # --- Band 2 (subtopic_2): VSEPR shapes ---
        self.next_band(2)
        b2_title = Tex("Pairs repel — spread as far as possible").scale(1.05).shift(band_shift(2) + UP * 2.3)
        self.play(Write(b2_title))
        self.wait(1.5)
        b2_l1 = Tex(r"2 groups: LINEAR, 180$^\circ$ (CO$_2$)").scale(0.95).shift(band_shift(2) + UP * 1.3)
        self.play(Write(b2_l1))
        self.wait(2)
        lin = VGroup(Dot(LEFT * 1.2 + UP * 0.6), Dot(UP * 0.6), Dot(RIGHT * 1.2 + UP * 0.6),
                     Line(LEFT * 1.2 + UP * 0.6, RIGHT * 1.2 + UP * 0.6))
        lin.shift(band_shift(2))
        self.play(Create(lin))
        self.wait(1.5)
        b2_l2 = Tex(r"3 groups: TRIGONAL PLANAR, 120$^\circ$ (BF$_3$)").scale(0.95).shift(band_shift(2) + DOWN * 0.3)
        self.play(Write(b2_l2))
        self.wait(2)
        b2_l3 = Tex(r"4 groups: TETRAHEDRAL, 109,5$^\circ$ (CH$_4$)").scale(0.95).shift(band_shift(2) + DOWN * 1.2)
        self.play(Write(b2_l3))
        self.wait(2)
        b2_l4 = Tex("The flat cross on paper is a lie —").scale(0.95).shift(band_shift(2) + DOWN * 2.1)
        b2_l5 = Tex("methane is a three-legged stool").scale(0.95).shift(band_shift(2) + DOWN * 2.8)
        self.play(Write(b2_l4))
        self.play(Write(b2_l5))
        self.wait(2.5)

        # --- Band 3 (subtopic_2): lone pairs and shrinking angles ---
        self.next_band(3)
        b3_title = Tex("Lone pairs: invisible, but they shove").scale(1.1).shift(band_shift(3) + UP * 2.3)
        self.play(Write(b3_title))
        self.wait(1.5)
        b3_l1 = Tex(r"NH$_3$: 4 pairs, 1 lone $\Rightarrow$ TRIGONAL PYRAMID").scale(0.95).shift(band_shift(3) + UP * 1.3)
        self.play(Write(b3_l1))
        self.wait(2.5)
        b3_l2 = Tex(r"H$_2$O: 4 pairs, 2 lone $\Rightarrow$ ANGULAR (bent)").scale(0.95).shift(band_shift(3) + UP * 0.4)
        self.play(Write(b3_l2))
        self.wait(2.5)
        b3_l3 = Tex("Lone pairs repel harder, squeezing angles:").scale(0.95).shift(band_shift(3) + DOWN * 0.6)
        self.play(Write(b3_l3))
        self.wait(2)
        b3_l4 = MathTex(r"109{,}5^\circ \to 107^\circ \to 104{,}5^\circ").scale(1.1).shift(band_shift(3) + DOWN * 1.6)
        lab34 = Tex(r"CH$_4$, NH$_3$, H$_2$O").scale(0.85).shift(band_shift(3) + DOWN * 2.3)
        self.play(Write(b3_l4))
        self.play(Write(lab34))
        self.play(Create(SurroundingRectangle(b3_l4, color=GREEN)))
        self.wait(2.5)
        b3_l5 = Tex("Name the shape by the ATOMS alone").scale(0.95).shift(band_shift(3) + DOWN * 3.1)
        self.play(Write(b3_l5))
        self.wait(2.5)

        # --- Band 4 (subtopic_3): electronegativity ---
        self.next_band(4)
        b4_title = Tex("Electronegativity: pull on the shared pair").scale(1.05).shift(band_shift(4) + UP * 2.3)
        self.play(Write(b4_title))
        self.wait(1.5)
        b4_l1 = Tex(r"F 4,0 \; O 3,5 \; N, Cl 3,0 \; C 2,5 \; H 2,1 \; Na 0,9").scale(0.9).shift(band_shift(4) + UP * 1.3)
        self.play(Write(b4_l1))
        self.wait(2.5)
        b4_l2 = MathTex(r"\Delta EN = 0: \text{ non-polar covalent}").scale(1.0).shift(band_shift(4) + UP * 0.3)
        self.play(Write(b4_l2))
        self.wait(2)
        b4_l3 = MathTex(r"\text{HCl: } 3{,}0 - 2{,}1 = 0{,}9 \text{ — polar}").scale(1.0).shift(band_shift(4) + DOWN * 0.7)
        self.play(Write(b4_l3))
        self.wait(2)
        b4_l4 = MathTex(r"\text{NaCl: } 3{,}0 - 0{,}9 = 2{,}1 \text{ — ionic}").scale(1.0).shift(band_shift(4) + DOWN * 1.7)
        self.play(Write(b4_l4))
        self.wait(2)
        b4_l5 = Tex(r"$\delta-$ on the stronger puller, $\delta+$ opposite").scale(0.95).shift(band_shift(4) + DOWN * 2.7)
        self.play(Write(b4_l5))
        self.wait(2.5)

        # --- Band 5 (subtopic_3): the sliding scale ---
        self.next_band(5)
        b5_title = Tex("One smooth slide, no cliff").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(1.5)
        rail = Arrow(LEFT * 4.5 + UP * 0.9, RIGHT * 4.5 + UP * 0.9, buff=0, color=YELLOW).shift(band_shift(5))
        t0 = Tex("perfect sharing").scale(0.8).shift(band_shift(5) + LEFT * 3.4 + UP * 1.6)
        t1 = Tex("unfair sharing").scale(0.8).shift(band_shift(5) + UP * 1.6)
        t2 = Tex("outright transfer").scale(0.8).shift(band_shift(5) + RIGHT * 3.3 + UP * 1.6)
        self.play(Create(rail))
        self.play(Write(t0), Write(t1), Write(t2))
        self.wait(2)
        u0 = MathTex(r"\Delta EN = 0").scale(0.8).shift(band_shift(5) + LEFT * 3.4 + UP * 0.3)
        u1 = MathTex(r"0{,}9 \;\; 1{,}4").scale(0.8).shift(band_shift(5) + UP * 0.3)
        u2 = MathTex(r"\approx 2 \text{ and up}").scale(0.8).shift(band_shift(5) + RIGHT * 3.3 + UP * 0.3)
        self.play(Write(u0), Write(u1), Write(u2))
        self.wait(2.5)
        b5_l1 = Tex(r"H$_2$ fair; H$_2$O strongly polar (1,4); NaCl ionic").scale(0.95).shift(band_shift(5) + DOWN * 1.0)
        self.play(Write(b5_l1))
        self.wait(2.5)
        b5_l2 = Tex(r"$\Delta EN$ is the position marker on the slide").scale(0.95).shift(band_shift(5) + DOWN * 2.0)
        self.play(Write(b5_l2))
        self.play(Create(SurroundingRectangle(b5_l2, color=GREEN)))
        self.wait(2.5)

        # --- Band 6 (subtopic_4): polar bonds vs polar molecules ---
        self.next_band(6)
        b6_title = Tex("Shape casts the deciding vote").scale(1.1).shift(band_shift(6) + UP * 2.4)
        self.play(Write(b6_title))
        self.wait(1.5)
        co2 = Tex("O $=$ C $=$ O").scale(1.0).shift(band_shift(6) + LEFT * 2.8 + UP * 1.3)
        aL = Arrow(LEFT * 2.8 + UP * 0.7, LEFT * 4.0 + UP * 0.7, buff=0, color=YELLOW).shift(band_shift(6))
        aR = Arrow(LEFT * 2.8 + UP * 0.7, LEFT * 1.6 + UP * 0.7, buff=0, color=YELLOW).shift(band_shift(6))
        lco2 = Tex("cancel: non-polar").scale(0.8).shift(band_shift(6) + LEFT * 2.8 + UP * 0.0)
        self.play(Write(co2))
        self.play(Create(aL), Create(aR), Write(lco2))
        self.wait(2.5)
        oD = Dot(band_shift(6) + RIGHT * 2.8 + UP * 1.5)
        lo = Tex("O").scale(0.85).shift(band_shift(6) + RIGHT * 2.8 + UP * 1.9)
        h1 = Dot(band_shift(6) + RIGHT * 1.9 + UP * 0.6)
        h2 = Dot(band_shift(6) + RIGHT * 3.7 + UP * 0.6)
        lh1 = Tex("H").scale(0.85).shift(band_shift(6) + RIGHT * 1.5 + UP * 0.5)
        lh2 = Tex("H").scale(0.85).shift(band_shift(6) + RIGHT * 4.1 + UP * 0.5)
        e1 = Line(RIGHT * 1.9 + UP * 0.6, RIGHT * 2.8 + UP * 1.5).shift(band_shift(6))
        e2 = Line(RIGHT * 3.7 + UP * 0.6, RIGHT * 2.8 + UP * 1.5).shift(band_shift(6))
        lw = Tex("add up: POLAR").scale(0.8).shift(band_shift(6) + RIGHT * 2.8 + DOWN * 0.1)
        self.play(FadeIn(oD), Write(lo), FadeIn(h1), Write(lh1), FadeIn(h2), Write(lh2))
        self.play(Create(e1), Create(e2), Write(lw))
        self.wait(2.5)
        b6_l1 = Tex("Polar only if polar bonds AND").scale(0.95).shift(band_shift(6) + DOWN * 1.3)
        b6_l2 = Tex("the shape does not cancel them").scale(0.95).shift(band_shift(6) + DOWN * 2.0)
        self.play(Write(b6_l1))
        self.play(Write(b6_l2))
        self.play(Create(SurroundingRectangle(VGroup(b6_l1, b6_l2), color=GREEN)))
        self.wait(2.5)
        b6_l3 = Tex(r"Symmetric cancels: CO$_2$, BF$_3$, CH$_4$").scale(0.9).shift(band_shift(6) + DOWN * 3.0)
        self.play(Write(b6_l3))
        self.wait(2.5)

        # --- Band 7 (subtopic_4): bond length and bond energy ---
        self.next_band(7)
        b7_title = Tex("Shorter bonds are stronger bonds").scale(1.1).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(1.5)
        b7_l1 = Tex("Bond length: nuclei distance at the minimum").scale(0.95).shift(band_shift(7) + UP * 1.2)
        self.play(Write(b7_l1))
        self.wait(2)
        b7_l2 = Tex("Bond energy: what it costs to break it").scale(0.95).shift(band_shift(7) + UP * 0.3)
        self.play(Write(b7_l2))
        self.wait(2)
        b7_l3 = Tex(r"C$-$C, C$=$C, C$\equiv$C: shorter and stronger").scale(0.95).shift(band_shift(7) + DOWN * 0.7)
        self.play(Write(b7_l3))
        self.wait(2.5)
        b7_l4 = Tex(r"N$\equiv$N: why the atmosphere is unreactive").scale(0.95).shift(band_shift(7) + DOWN * 1.7)
        self.play(Write(b7_l4))
        self.wait(2)
        b7_l5 = Tex("Bigger atoms: longer, weaker bonds").scale(0.95).shift(band_shift(7) + DOWN * 2.7)
        self.play(Write(b7_l5))
        self.wait(2.5)

        # ===== Part 2 — Simplifier =====
        # --- Band 8 (subtopic_5): why atoms hold hands ---
        self.next_band(8)
        b8_title = Tex("Why atoms hold hands").scale(1.2).shift(band_shift(8) + UP * 2.3)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = Tex("Bonding happens when it PAYS — in energy").scale(0.95).shift(band_shift(8) + UP * 1.3)
        self.play(Write(b8_l1))
        self.wait(2.5)
        b8_l2 = Tex("Two hydrogens share, feel full, roll into").scale(0.95).shift(band_shift(8) + UP * 0.4)
        b8_l3 = Tex("an energy valley and settle there").scale(0.95).shift(band_shift(8) + DOWN * 0.3)
        self.play(Write(b8_l2))
        self.play(Write(b8_l3))
        self.wait(2.5)
        b8_l4 = Tex("Helium is already full: no valley, drifts on").scale(0.95).shift(band_shift(8) + DOWN * 1.3)
        self.play(Write(b8_l4))
        self.play(Create(SurroundingRectangle(b8_l4, color=GREEN)))
        self.wait(2.5)
        b8_l5 = Tex("Nitrogen grips with a triple handshake —").scale(0.95).shift(band_shift(8) + DOWN * 2.3)
        b8_l6 = Tex("almost impossible to separate").scale(0.95).shift(band_shift(8) + DOWN * 3.0)
        self.play(Write(b8_l5))
        self.play(Write(b8_l6))
        self.wait(3)

        # --- Band 9 (subtopic_6): balloons tied at the centre ---
        self.next_band(9)
        b9_title = Tex("Balloons tied at the centre").scale(1.2).shift(band_shift(9) + UP * 2.3)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex("Balloons shove each other as far apart as possible").scale(0.9).shift(band_shift(9) + UP * 1.3)
        self.play(Write(b9_l1))
        self.wait(2.5)
        b9_l2 = Tex("2: straight line. 3: flat triangle. 4: tetrahedron").scale(0.9).shift(band_shift(9) + UP * 0.4)
        self.play(Write(b9_l2))
        self.wait(2.5)
        b9_l3 = Tex("Lone pairs are INVISIBLE balloons —").scale(0.95).shift(band_shift(9) + DOWN * 0.6)
        b9_l4 = Tex("you name only what you can see").scale(0.95).shift(band_shift(9) + DOWN * 1.3)
        self.play(Write(b9_l3))
        self.play(Write(b9_l4))
        self.wait(2.5)
        b9_l5 = MathTex(r"109{,}5^\circ \to 107^\circ \to 104{,}5^\circ").scale(1.0).shift(band_shift(9) + DOWN * 2.3)
        self.play(Write(b9_l5))
        self.play(Create(SurroundingRectangle(b9_l5, color=GREEN)))
        self.wait(3)

        # --- Band 10 (subtopic_7): fair and unfair tug-of-war ---
        self.next_band(10)
        b10_title = Tex("Fair and unfair tug-of-war").scale(1.2).shift(band_shift(10) + UP * 2.3)
        self.play(Write(b10_title))
        self.wait(2)
        b10_l1 = Tex("Twins pull equally: fair game, non-polar").scale(0.95).shift(band_shift(10) + UP * 1.3)
        self.play(Write(b10_l1))
        self.wait(2.5)
        b10_l2 = Tex(r"Cl 3,0 vs H 2,1: unfair — $\delta-$ at chlorine").scale(0.95).shift(band_shift(10) + UP * 0.4)
        self.play(Write(b10_l2))
        self.wait(2.5)
        b10_l3 = Tex("Adult vs toddler (gap 2,1): chlorine TAKES —").scale(0.95).shift(band_shift(10) + DOWN * 0.6)
        b10_l4 = Tex("ions form, the bond is ionic").scale(0.95).shift(band_shift(10) + DOWN * 1.3)
        self.play(Write(b10_l3))
        self.play(Write(b10_l4))
        self.wait(2.5)
        b10_l5 = Tex(r"CO$_2$: straight line, pulls cancel — non-polar").scale(0.95).shift(band_shift(10) + DOWN * 2.2)
        self.play(Write(b10_l5))
        self.wait(2)
        b10_l6 = Tex("Water is bent: pulls add — POLAR,").scale(0.95).shift(band_shift(10) + DOWN * 3.0)
        self.play(Write(b10_l6))
        self.wait(4)
