from manim import *

# Band-layout whiteboard scene for "Describing Motion" (Part 1 — Expert:
# subtopics 1-4; Part 2 — Simplifier: subtopics 5-7). Exporter-safe mobjects
# only, add-only lifecycle, camera moves down one band per teaching beat.
# Band time apportioned to subtopics.json (225/230/235/255/180/175/175 of
# 1475 s).

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class DescribingMotionSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic full-screen while intro.md audio plays (~4-5%).
        self.wait(14)

        # ===== Part 1 — Expert =====
        # --- Band 0 (subtopic_1): frame of reference and position ---
        title = Tex("Describing Motion").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        d1 = Tex("Position: location relative to a reference point").scale(1.05).shift(UP * 0.9)
        self.play(Write(d1))
        self.wait(2.5)
        d2 = Tex("Frame $=$ reference point $+$ positive direction").scale(1.05).shift(DOWN * 0.1)
        self.play(Write(d2))
        self.wait(2.5)
        d3 = Tex("Declare it: let the start be 0, east positive").scale(1.05).shift(DOWN * 1.1)
        self.play(Write(d3))
        self.wait(2)
        d4 = Tex("Never change frames midway").scale(1.05).shift(DOWN * 2.2)
        self.play(Write(d4))
        self.wait(3)

        # --- Band 1 (subtopic_1): the walk on a number line ---
        self.next_band(1)
        b1t = Tex("40 m east, then 30 m west").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1t))
        self.wait(1.5)
        base = band_shift(1) + DOWN * 0.6
        nline = Line(base + LEFT * 4.5, base + RIGHT * 4.5, stroke_width=4)
        self.play(Create(nline))
        t0 = Line(base + LEFT * 3.0 + DOWN * 0.15, base + LEFT * 3.0 + UP * 0.15, stroke_width=4)
        t10 = Line(base + LEFT * 1.5 + DOWN * 0.15, base + LEFT * 1.5 + UP * 0.15, stroke_width=4)
        t40 = Line(base + RIGHT * 3.0 + DOWN * 0.15, base + RIGHT * 3.0 + UP * 0.15, stroke_width=4)
        n0 = MathTex(r"0").scale(0.9).move_to(base + LEFT * 3.0 + DOWN * 0.55)
        n10 = MathTex(r"+10").scale(0.9).move_to(base + LEFT * 1.5 + DOWN * 0.55)
        n40 = MathTex(r"+40").scale(0.9).move_to(base + RIGHT * 3.0 + DOWN * 0.55)
        self.play(Create(t0), Create(t10), Create(t40))
        self.play(Write(n0), Write(n10), Write(n40))
        self.wait(2)
        leg1 = Arrow(base + LEFT * 3.0 + UP * 1.2, base + RIGHT * 3.0 + UP * 1.2, buff=0, color=YELLOW)
        l1lab = Tex("40 m east").scale(0.95).move_to(base + UP * 1.7)
        self.play(Create(leg1), Write(l1lab))
        self.wait(2)
        leg2 = Arrow(base + RIGHT * 3.0 + UP * 0.6, base + LEFT * 1.5 + UP * 0.6, buff=0, color=ORANGE)
        l2lab = Tex("30 m west").scale(0.95).move_to(base + RIGHT * 0.75 + UP * 0.25)
        self.play(Create(leg2), Write(l2lab))
        self.wait(2)
        fin = Tex(r"Final position: $+10$ m (10 m east)").scale(1.1).shift(band_shift(1) + DOWN * 2.3)
        self.play(Write(fin))
        self.play(Create(SurroundingRectangle(fin, color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): distance vs displacement, worked ---
        self.next_band(2)
        b2t = Tex("Distance versus displacement").scale(1.2).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2t))
        self.wait(2)
        b2a = Tex("Distance: ground covered — scalar").scale(1.05).shift(band_shift(2) + UP * 1.1)
        self.play(Write(b2a))
        self.wait(2)
        b2b = MathTex(r"D = 40 + 30 = 70 \text{ m}").scale(1.15).shift(band_shift(2) + UP * 0.2)
        self.play(Write(b2b))
        self.play(Create(SurroundingRectangle(b2b, color=GREEN)))
        self.wait(2.5)
        b2c = Tex("Displacement: change in position — vector").scale(1.05).shift(band_shift(2) + DOWN * 0.9)
        self.play(Write(b2c))
        self.wait(2)
        b2d = MathTex(r"\Delta x = 10 - 0 = 10 \text{ m east}").scale(1.15).shift(band_shift(2) + DOWN * 1.8)
        self.play(Write(b2d))
        self.play(Create(SurroundingRectangle(b2d, color=GREEN)))
        self.wait(2)
        b2e = Tex("70 m of walking, net change 10 m").scale(1.0).shift(band_shift(2) + DOWN * 2.9)
        self.play(Write(b2e))
        self.wait(3)

        # --- Band 3 (subtopic_2): the lap extreme ---
        self.next_band(3)
        b3t = Tex("One lap of a 400 m track").scale(1.2).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3t))
        self.wait(2)
        b3a = MathTex(r"D = 400 \text{ m}").scale(1.15).shift(band_shift(3) + UP * 1.0)
        self.play(Write(b3a))
        self.wait(2)
        b3b = MathTex(r"\Delta x = 0 \quad \text{(start = finish)}").scale(1.15).shift(band_shift(3) + UP * 0.0)
        self.play(Write(b3b))
        self.play(Create(SurroundingRectangle(b3b, color=GREEN)))
        self.wait(2.5)
        b3c = Tex("Real effort, zero displacement").scale(1.05).shift(band_shift(3) + DOWN * 1.1)
        self.play(Write(b3c))
        self.wait(2)
        b3d = Tex("They agree only if direction never changes").scale(1.05).shift(band_shift(3) + DOWN * 2.1)
        self.play(Write(b3d))
        self.wait(3)

        # --- Band 4 (subtopic_3): average speed and average velocity ---
        self.next_band(4)
        b4t = Tex("Average speed vs average velocity").scale(1.2).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4t))
        self.wait(2)
        b4a = MathTex(r"\text{speed} = \frac{D}{t} = \frac{70}{50} = 1{,}4 \text{ m/s}").scale(1.1).shift(band_shift(4) + UP * 0.9)
        self.play(Write(b4a))
        self.play(Create(SurroundingRectangle(b4a, color=GREEN)))
        self.wait(3)
        b4b = MathTex(r"v = \frac{10}{50} = 0{,}2 \text{ m/s east}").scale(1.1).shift(band_shift(4) + DOWN * 0.7)
        self.play(Write(b4b))
        self.play(Create(SurroundingRectangle(b4b, color=GREEN)))
        self.wait(3)
        b4c = Tex("Seven times smaller — the legs cancelled").scale(1.05).shift(band_shift(4) + DOWN * 1.9)
        self.play(Write(b4c))
        self.wait(2)
        b4d = Tex("Read the question's noun first").scale(1.05).shift(band_shift(4) + DOWN * 2.9)
        self.play(Write(b4d))
        self.wait(3)

        # --- Band 5 (subtopic_3): the lap in 80 s ---
        self.next_band(5)
        b5t = Tex("The lap, timed: 400 m in 80 s").scale(1.2).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5t))
        self.wait(2)
        b5a = MathTex(r"\text{speed} = \frac{400}{80} = 5 \text{ m/s}").scale(1.15).shift(band_shift(5) + UP * 0.9)
        self.play(Write(b5a))
        self.wait(2.5)
        b5b = MathTex(r"v = \frac{0}{80} = 0 \text{ m/s}").scale(1.15).shift(band_shift(5) + DOWN * 0.5)
        self.play(Write(b5b))
        self.play(Create(SurroundingRectangle(b5b, color=GREEN)))
        self.wait(2.5)
        b5c = Tex("Speed keeps the effort; velocity the outcome").scale(1.05).shift(band_shift(5) + DOWN * 1.8)
        self.play(Write(b5c))
        self.wait(3)

        # --- Band 6 (subtopic_4): the four-step method ---
        self.next_band(6)
        b6t = Tex("The method, four steps").scale(1.2).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6t))
        self.wait(2)
        b6a = Tex("1. Declare the frame, in writing").scale(1.05).shift(band_shift(6) + UP * 1.1)
        self.play(Write(b6a))
        self.wait(2)
        b6b = Tex("2. Track positions as signed numbers").scale(1.05).shift(band_shift(6) + UP * 0.2)
        self.play(Write(b6b))
        self.wait(2)
        b6c = Tex("3. Distance: path; displacement: endpoints").scale(1.05).shift(band_shift(6) + DOWN * 0.7)
        self.play(Write(b6c))
        self.wait(2)
        b6d = Tex("4. Divide by TOTAL time; attach direction").scale(1.05).shift(band_shift(6) + DOWN * 1.6)
        self.play(Write(b6d))
        self.wait(3)

        # --- Band 7 (subtopic_4): the traps ---
        self.next_band(7)
        b7t = Tex("The classic traps").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7t))
        self.wait(2)
        b7a = MathTex(r"\Delta x = 40 + 30 = 70 \text{ m}").scale(1.1).shift(band_shift(7) + UP * 1.1)
        self.play(Write(b7a))
        self.play(Create(strike(b7a)))
        self.wait(2)
        b7b = MathTex(r"\Delta x = 40 - 30 = 10 \text{ m east}").scale(1.1).shift(band_shift(7) + UP * 0.1)
        self.play(Write(b7b))
        self.play(Create(SurroundingRectangle(b7b, color=GREEN)))
        self.wait(2.5)
        b7c = Tex(r"$0{,}2$ m/s alone is half an answer").scale(1.05).shift(band_shift(7) + DOWN * 1.0)
        self.play(Write(b7c))
        self.wait(2)
        b7d = Tex("Vector answers carry a direction").scale(1.05).shift(band_shift(7) + DOWN * 1.9)
        self.play(Write(b7d))
        self.wait(2)
        b7e = Tex("Total time includes the rest stops").scale(1.05).shift(band_shift(7) + DOWN * 2.9)
        self.play(Write(b7e))
        self.wait(3)

        # ===== Part 2 — Simplifier =====
        # --- Band 8 (subtopic_5): where are you, relative to what ---
        self.next_band(8)
        b8t = Tex("Where are you, relative to what?").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8t))
        self.wait(2)
        b8a = Tex("Every location has a `from': the taxi rank").scale(1.05).shift(band_shift(8) + UP * 1.1)
        self.play(Write(b8a))
        self.wait(2.5)
        b8b = Tex("Rank $= 0$; shop $+2$; school $-1$").scale(1.05).shift(band_shift(8) + UP * 0.2)
        self.play(Write(b8b))
        self.wait(2.5)
        b8c = Tex("Minus is not punishment — just the other way").scale(1.0).shift(band_shift(8) + DOWN * 0.8)
        self.play(Write(b8c))
        self.wait(2.5)
        b8d = Tex(r"Walker: $0 \to +40 \to +10$").scale(1.1).shift(band_shift(8) + DOWN * 1.8)
        self.play(Write(b8d))
        self.play(Create(SurroundingRectangle(b8d, color=GREEN)))
        self.wait(3)

        # --- Band 9 (subtopic_6): the odometer and the pigeon ---
        self.next_band(9)
        b9t = Tex("The odometer and the pigeon").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9t))
        self.wait(2)
        b9a = Tex("Odometer counts every metre: distance").scale(1.05).shift(band_shift(9) + UP * 1.1)
        self.play(Write(b9a))
        self.wait(2)
        b9b = MathTex(r"\text{Odometer: } 70 \text{ m}").scale(1.1).shift(band_shift(9) + UP * 0.2)
        self.play(Write(b9b))
        self.wait(2)
        b9c = Tex("Pigeon flies straight home: displacement").scale(1.05).shift(band_shift(9) + DOWN * 0.7)
        self.play(Write(b9c))
        self.wait(2)
        b9d = MathTex(r"\text{Pigeon: } 10 \text{ m east}").scale(1.1).shift(band_shift(9) + DOWN * 1.6)
        self.play(Write(b9d))
        self.play(Create(SurroundingRectangle(b9d, color=GREEN)))
        self.wait(2)
        b9e = Tex("Full lap: odometer 400 m, pigeon stays put").scale(1.0).shift(band_shift(9) + DOWN * 2.7)
        self.play(Write(b9e))
        self.wait(3)

        # --- Band 10 (subtopic_7): two speedometers for one walk ---
        self.next_band(10)
        b10t = Tex("Two speedometers for one walk").scale(1.2).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10t))
        self.wait(2)
        b10a = MathTex(r"\text{Odometer over time: } \frac{70}{50} = 1{,}4 \text{ m/s}").scale(1.05).shift(band_shift(10) + UP * 1.0)
        self.play(Write(b10a))
        self.wait(2.5)
        b10b = MathTex(r"\text{Pigeon over time: } \frac{10}{50} = 0{,}2 \text{ m/s east}").scale(1.05).shift(band_shift(10) + DOWN * 0.4)
        self.play(Write(b10b))
        self.play(Create(SurroundingRectangle(b10b, color=GREEN)))
        self.wait(3)
        b10c = Tex("Read the noun like a price tag").scale(1.05).shift(band_shift(10) + DOWN * 1.7)
        self.play(Write(b10c))
        self.wait(2)
        b10d = Tex("Divide by the whole time, tea breaks included").scale(1.0).shift(band_shift(10) + DOWN * 2.7)
        self.play(Write(b10d))
        self.wait(4)
