from manim import *

# Band-layout whiteboard scene for Body Measurements, BMI and Medicine Dosage.
# One band per teaching beat; the camera moves down and earlier work stays on
# the canvas. Exporter-supported mobjects only; every working line is its own
# single-string Tex/MathTex revealed with Write. No transforms, no FadeOut.
#
# Subtopic time shares (subtopics.json, total 1470 s):
# 215/215/225/230/195/195/195 -> bands 0-1 / 2-3 / 4-5 / 6-7 / 8 / 9 / 10.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class BodyMeasurementsBmiDosageSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic full-screen while intro.md audio plays.
        self.wait(15)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): the two instruments and the unit discipline
        title = Tex("Body Measurements, BMI and Dosage").scale(1.25).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex("Mass: scale, in kilograms (zeroed, shoes off)").scale(1.05).shift(UP * 1.2)
        b0_l2 = Tex("Height: stadiometer, in METRES").scale(1.05).shift(UP * 0.3)
        self.play(Write(b0_l1))
        self.wait(2)
        self.play(Write(b0_l2))
        self.wait(2)
        b0_l3 = MathTex(r"168 \text{ cm} \div 100 = 1{,}68 \text{ m}").scale(1.15).shift(DOWN * 0.7)
        self.play(Write(b0_l3))
        self.play(Create(SurroundingRectangle(b0_l3, color=GREEN)))
        self.wait(2.5)
        b0_l4 = Tex("Convert BEFORE any formula sees the number").scale(1.05).shift(DOWN * 1.7)
        b0_l5 = Tex("Bongani: 82 kg and 1,68 m").scale(1.1).shift(DOWN * 2.6)
        self.play(Write(b0_l4))
        self.wait(2)
        self.play(Write(b0_l5))
        self.wait(3)

        # --- Band 1 (subtopic_1): babies, precision and reading between marks
        self.next_band(1)
        b1_t = Tex("Precision chosen to fit the purpose").scale(1.15).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_t))
        self.wait(1.5)
        b1_l1 = Tex("Adult mass: nearest 0,5 kg is fine").scale(1.05).shift(band_shift(1) + UP * 1.1)
        b1_l2 = Tex("Baby mass: nearest 0,1 kg — a newborn is 3 kg").scale(1.05).shift(band_shift(1) + UP * 0.2)
        b1_l3 = Tex("Head circumference tracks brain growth").scale(1.05).shift(band_shift(1) + DOWN * 0.7)
        self.play(Write(b1_l1))
        self.wait(2)
        self.play(Write(b1_l2))
        self.wait(2.5)
        self.play(Write(b1_l3))
        self.wait(2)
        b1_l4 = Tex("Needle halfway between 82 and 83?").scale(1.05).shift(band_shift(1) + DOWN * 1.7)
        b1_l5 = MathTex(r"\text{Read between the marks: } 82{,}5 \text{ kg}").scale(1.1).shift(band_shift(1) + DOWN * 2.7)
        self.play(Write(b1_l4))
        self.wait(2)
        self.play(Write(b1_l5))
        self.play(Create(SurroundingRectangle(b1_l5, color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): the BMI formula, worked in full
        self.next_band(2)
        b2_t = Tex("BMI: one screening number").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(1.5)
        b2_l1 = MathTex(r"BMI = \frac{\text{mass (kg)}}{\text{height (m)}^2}").scale(1.15).shift(band_shift(2) + UP * 1.0)
        self.play(Write(b2_l1))
        self.wait(2.5)
        b2_l2 = MathTex(r"\text{Height squared first: } 1{,}68 \times 1{,}68 = 2{,}8224").scale(1.0).shift(band_shift(2) + DOWN * 0.1)
        b2_l3 = MathTex(r"82 \div 2{,}8224 = 29{,}1").scale(1.15).shift(band_shift(2) + DOWN * 1.1)
        self.play(Write(b2_l2))
        self.wait(2.5)
        self.play(Write(b2_l3))
        self.play(Create(SurroundingRectangle(b2_l3, color=GREEN)))
        self.wait(2.5)
        b2_l4 = Tex("Formula is supplied — marks are for substitution,").scale(1.0).shift(band_shift(2) + DOWN * 2.1)
        b2_l5 = Tex("calculation and the interpretation sentence").scale(1.0).shift(band_shift(2) + DOWN * 2.8)
        self.play(Write(b2_l4))
        self.play(Write(b2_l5))
        self.wait(3)

        # --- Band 3 (subtopic_2): categories, the cm trap, the limits of BMI
        self.next_band(3)
        b3_t = Tex("Name the number, the category, the context").scale(1.1).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t))
        self.wait(1.5)
        b3_l1 = Tex("Below 18,5 underweight; 18,5--24,9 healthy").scale(1.05).shift(band_shift(3) + UP * 1.2)
        b3_l2 = Tex("25--29,9 overweight; 30 and up obese").scale(1.05).shift(band_shift(3) + UP * 0.4)
        self.play(Write(b3_l1))
        self.wait(2)
        self.play(Write(b3_l2))
        self.wait(2)
        b3_l3 = Tex("29,1 is overweight, near its upper edge").scale(1.05).shift(band_shift(3) + DOWN * 0.5)
        self.play(Write(b3_l3))
        self.play(Create(SurroundingRectangle(b3_l3, color=GREEN)))
        self.wait(2.5)
        b3_l4 = MathTex(r"82 \div 168^2 = 0{,}003 \;\text{ (no human number)}").scale(1.0).shift(band_shift(3) + DOWN * 1.5)
        self.play(Write(b3_l4))
        self.play(Create(strike(b3_l4)))
        self.wait(2)
        b3_l5 = Tex("Adult BMIs live between about 15 and 45").scale(1.0).shift(band_shift(3) + DOWN * 2.4)
        b3_l6 = Tex("Screening tool: it cannot see muscle or age").scale(1.0).shift(band_shift(3) + DOWN * 3.1)
        self.play(Write(b3_l5))
        self.wait(2)
        self.play(Write(b3_l6))
        self.wait(3)

        # --- Band 4 (subtopic_3): the growth chart, drawn
        self.next_band(4)
        b4_t = Tex("Growth charts: percentile curves").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(1.5)
        origin = band_shift(4) + LEFT * 4.6 + DOWN * 2.4
        ax_x = Arrow(origin, origin + RIGHT * 7.6, buff=0)
        ax_y = Arrow(origin, origin + UP * 4.0, buff=0)
        self.play(Create(ax_x), Create(ax_y))
        x_lab = Tex("age (months)").scale(1.0).shift(origin + RIGHT * 6.2 + DOWN * 0.5)
        y_lab = Tex("mass (kg)").scale(1.0).shift(origin + UP * 4.0 + RIGHT * 1.3)
        self.play(Write(x_lab), Write(y_lab))
        self.wait(1.5)
        # three percentile curves as two-segment polylines
        c85 = VGroup(Line(origin + UP * 1.4, origin + RIGHT * 3.5 + UP * 2.7),
                     Line(origin + RIGHT * 3.5 + UP * 2.7, origin + RIGHT * 7.0 + UP * 3.5))
        c50 = VGroup(Line(origin + UP * 1.0, origin + RIGHT * 3.5 + UP * 2.1),
                     Line(origin + RIGHT * 3.5 + UP * 2.1, origin + RIGHT * 7.0 + UP * 2.7))
        c15 = VGroup(Line(origin + UP * 0.6, origin + RIGHT * 3.5 + UP * 1.5),
                     Line(origin + RIGHT * 3.5 + UP * 1.5, origin + RIGHT * 7.0 + UP * 1.9))
        lab85 = Tex("85th").scale(0.9).shift(origin + RIGHT * 7.3 + UP * 3.5)
        lab50 = Tex("50th").scale(0.9).shift(origin + RIGHT * 7.3 + UP * 2.7)
        lab15 = Tex("15th").scale(0.9).shift(origin + RIGHT * 7.3 + UP * 1.9)
        self.play(Create(c85), Write(lab85))
        self.play(Create(c50), Write(lab50))
        self.play(Create(c15), Write(lab15))
        self.wait(2)
        pt = Dot(origin + RIGHT * 3.5 + UP * 2.1, color=RED)
        pt_lab = Tex("6 months, 7,3 kg: on the 50th").scale(1.0).shift(band_shift(4) + RIGHT * 0.4 + UP * 1.3)
        self.play(FadeIn(pt))
        self.play(Write(pt_lab))
        self.wait(3)

        # --- Band 5 (subtopic_3): reading both ways, and the journey
        self.next_band(5)
        b5_t = Tex("A percentile is a place in a line of 100").scale(1.1).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_t))
        self.wait(1.5)
        b5_l1 = Tex("50th: dead centre — half of peers weigh less").scale(1.05).shift(band_shift(5) + UP * 1.1)
        b5_l2 = Tex("85th at 6 months reads off about 8,4 kg").scale(1.05).shift(band_shift(5) + UP * 0.2)
        b5_l3 = Tex("Between the 15th and 50th: roughly the 30th").scale(1.05).shift(band_shift(5) + DOWN * 0.7)
        self.play(Write(b5_l1))
        self.wait(2)
        self.play(Write(b5_l2))
        self.wait(2)
        self.play(Write(b5_l3))
        self.wait(2)
        b5_l4 = Tex("Healthy growth tracks ALONG one curve").scale(1.05).shift(band_shift(5) + DOWN * 1.6)
        b5_l5 = Tex("Falling 50th to 15th: refer — read the film,").scale(1.05).shift(band_shift(5) + DOWN * 2.5)
        b5_l6 = Tex("not the photograph").scale(1.05).shift(band_shift(5) + DOWN * 3.2)
        self.play(Write(b5_l4))
        self.wait(2)
        self.play(Write(b5_l5))
        self.play(Write(b5_l6))
        self.wait(3)

        # --- Band 6 (subtopic_4): dose from rate, syrup from concentration
        self.next_band(6)
        b6_t = Tex("Dosage: milligrams per kilogram").scale(1.15).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_t))
        self.wait(1.5)
        b6_l1 = Tex("Girl of 18 kg; rate 15 mg per kg per dose").scale(1.05).shift(band_shift(6) + UP * 1.2)
        b6_l2 = MathTex(r"\text{Dose: } 15 \times 18 = 270 \text{ mg}").scale(1.1).shift(band_shift(6) + UP * 0.3)
        self.play(Write(b6_l1))
        self.wait(2)
        self.play(Write(b6_l2))
        self.wait(2.5)
        b6_l3 = Tex("Label: 120 mg per 5 ml of syrup").scale(1.05).shift(band_shift(6) + DOWN * 0.6)
        b6_l4 = MathTex(r"120 \div 5 = 24 \text{ mg per ml}").scale(1.1).shift(band_shift(6) + DOWN * 1.5)
        b6_l5 = MathTex(r"270 \div 24 = 11{,}25 \text{ ml}").scale(1.15).shift(band_shift(6) + DOWN * 2.5)
        self.play(Write(b6_l3))
        self.wait(2)
        self.play(Write(b6_l4))
        self.wait(2)
        self.play(Write(b6_l5))
        self.play(Create(SurroundingRectangle(b6_l5, color=GREEN)))
        self.wait(3)

        # --- Band 7 (subtopic_4): the day's total and the bottle's life
        self.next_band(7)
        b7_t = Tex("The bottle's life: round DOWN").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(1.5)
        b7_l1 = MathTex(r"\text{Per day: } 11{,}25 \times 3 = 33{,}75 \text{ ml}").scale(1.05).shift(band_shift(7) + UP * 1.1)
        b7_l2 = MathTex(r"\text{100 ml bottle: } 100 \div 11{,}25 = 8{,}88").scale(1.05).shift(band_shift(7) + UP * 0.2)
        b7_l3 = MathTex(r"= 8 \text{ full doses (dose nine falls short)}").scale(1.05).shift(band_shift(7) + DOWN * 0.8)
        self.play(Write(b7_l1))
        self.wait(2.5)
        self.play(Write(b7_l2))
        self.wait(2.5)
        self.play(Write(b7_l3))
        self.play(Create(SurroundingRectangle(b7_l3, color=GREEN)))
        self.wait(2.5)
        b7_l4 = Tex("Two full days, plus two doses of the third").scale(1.05).shift(band_shift(7) + DOWN * 1.8)
        b7_l5 = Tex("Medicine rounding errs toward LESS — never double").scale(1.0).shift(band_shift(7) + DOWN * 2.8)
        self.play(Write(b7_l4))
        self.wait(2)
        self.play(Write(b7_l5))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): the number on the clinic wall
        self.next_band(8)
        b8_t = Tex("Know what a human number sounds like").scale(1.15).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_t))
        self.wait(1.5)
        b8_l1 = MathTex(r"\text{Wall says 168 — slide the comma: } 1{,}68 \text{ m}").scale(1.0).shift(band_shift(8) + UP * 1.1)
        b8_l2 = MathTex(r"\text{Metres: } 82 \div 2{,}82 = 29{,}1 \;\text{ (a body)}").scale(1.05).shift(band_shift(8) + UP * 0.2)
        b8_l3 = MathTex(r"\text{Centimetres: } 82 \div 28\;224 = 0{,}003 \;\text{ (a paperclip)}").scale(0.92).shift(band_shift(8) + DOWN * 0.8)
        self.play(Write(b8_l1))
        self.wait(2.5)
        self.play(Write(b8_l2))
        self.play(Create(SurroundingRectangle(b8_l2, color=GREEN)))
        self.wait(2.5)
        self.play(Write(b8_l3))
        self.play(Create(strike(b8_l3)))
        self.wait(2.5)
        b8_l4 = Tex("Human BMIs: roughly 15 to 45 — else check units").scale(1.05).shift(band_shift(8) + DOWN * 1.8)
        b8_l5 = Tex("Needle halfway between 82 and 83: 82,5 kg").scale(1.05).shift(band_shift(8) + DOWN * 2.7)
        self.play(Write(b8_l4))
        self.wait(2)
        self.play(Write(b8_l5))
        self.wait(3)

        # --- Band 9 (subtopic_6): reading the curves
        self.next_band(9)
        b9_t = Tex("One hundred babies in a line").scale(1.15).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(1.5)
        b9_l1 = Tex("Percentile = her position in the line").scale(1.05).shift(band_shift(9) + UP * 1.1)
        b9_l2 = Tex("50th: dead centre; 85th: heavier than 85").scale(1.05).shift(band_shift(9) + UP * 0.2)
        b9_l3 = Tex("Age along, weight up: the dot kisses the 50th").scale(1.05).shift(band_shift(9) + DOWN * 0.7)
        self.play(Write(b9_l1))
        self.wait(2.5)
        self.play(Write(b9_l2))
        self.wait(2.5)
        self.play(Write(b9_l3))
        self.wait(2)
        b9_l4 = Tex("The 15th staying on the 15th is thriving").scale(1.05).shift(band_shift(9) + DOWN * 1.6)
        b9_l5 = Tex("Crossing lanes downward is the alarm: refer").scale(1.05).shift(band_shift(9) + DOWN * 2.5)
        self.play(Write(b9_l4))
        self.wait(2.5)
        self.play(Write(b9_l5))
        self.play(Create(SurroundingRectangle(b9_l5, color=GREEN)))
        self.wait(3)

        # --- Band 10 (subtopic_7): the medicine spoon
        self.next_band(10)
        b10_t = Tex("The medicine spoon: two steps, one life").scale(1.15).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_t))
        self.wait(1.5)
        b10_l1 = MathTex(r"\text{Medicine: } 15 \times 18 = 270 \text{ mg}").scale(1.05).shift(band_shift(10) + UP * 1.1)
        b10_l2 = MathTex(r"\text{Strength: } 120 \text{ mg in } 5 \text{ ml} = 24 \text{ mg per ml}").scale(0.91).shift(band_shift(10) + UP * 0.2)
        b10_l3 = MathTex(r"\text{Syrup: } 270 \div 24 = 11{,}25 \text{ ml (syringe!)}").scale(1.0).shift(band_shift(10) + DOWN * 0.8)
        self.play(Write(b10_l1))
        self.wait(2.5)
        self.play(Write(b10_l2))
        self.wait(2.5)
        self.play(Write(b10_l3))
        self.wait(2.5)
        b10_l4 = MathTex(r"100 \div 11{,}25 = 8{,}88 \;\Rightarrow\; 8 \text{ doses (DOWN)}").scale(0.96).shift(band_shift(10) + DOWN * 1.8)
        self.play(Write(b10_l4))
        self.play(Create(SurroundingRectangle(b10_l4, color=GREEN)))
        self.wait(2.5)
        b10_l5 = Tex("Paint rounds up; medicine rounds down").scale(1.05).shift(band_shift(10) + DOWN * 2.8)
        self.play(Write(b10_l5))
        self.wait(4)
