from manim import *

# Band-layout whiteboard scene for "Magnetic Declination and Area
# Calculation" (grade 12, term 1 mapwork). All seven subtopics: Part 1
# Expert (1-4), Part 2 Simplifier (5-7). Band time apportioned to
# subtopics.json (225/235/235/230/195/190/180 of 1490 s). Exporter-safe
# primitives only; both NSC calculations are worked line by line with the
# script's exact numbers, green-boxed answers and struck traps.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class MagneticDeclinationAreaSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic full-screen while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): two norths and the angle between them
        title = Tex("Magnetic Declination and Area").scale(1.25).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        # Two norths from one point: true north up, magnetic north west of it.
        origin = Dot(DOWN * 1.6)
        tn = Arrow(DOWN * 1.6, UP * 1.0, color=BLUE)
        tn_lab = Tex("true north").scale(0.9).shift(UP * 1.4 + RIGHT * 0.1)
        self.play(Create(origin), Create(tn), Write(tn_lab))
        self.wait(1.5)
        mn = Arrow(DOWN * 1.6, UP * 0.8 + LEFT * 1.5, color=RED)
        mn_lab = Tex("magnetic north").scale(0.9).shift(UP * 1.25 + LEFT * 2.3)
        self.play(Create(mn), Write(mn_lab))
        self.wait(1.5)
        dec_lab = Tex(r"declination:\\ the angle between").scale(0.85).shift(LEFT * 3.4 + DOWN * 0.6)
        self.play(Write(dec_lab))
        self.wait(2)
        b0_l1 = Tex(r"In SA the needle points WEST of true north").scale(0.95).shift(RIGHT * 2.1 + DOWN * 0.6)
        self.play(Write(b0_l1))
        self.wait(2)
        b0_l2 = Tex(r"The magnetic pole drifts — the angle").scale(0.95).shift(DOWN * 2.4)
        b0_l3 = Tex(r"grows a little every year").scale(0.95).shift(DOWN * 3.1)
        self.play(Write(b0_l2))
        self.play(Write(b0_l3))
        self.wait(3)

        # --- Band 1 (subtopic_1): the margin note and the bearing rule
        self.next_band(1)
        b1_title = Tex("The margin note and the rule").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l1 = Tex(r"Sheet margin gives three facts:").scale(1.0).shift(band_shift(1) + UP * 1.2)
        b1_l2 = Tex(r"declination in a stated year, mean annual").scale(0.95).shift(band_shift(1) + UP * 0.5)
        b1_l3 = Tex(r"change, and its direction (westward)").scale(0.95).shift(band_shift(1) + DOWN * 0.2)
        self.play(Write(b1_l1))
        self.play(Write(b1_l2))
        self.play(Write(b1_l3))
        self.wait(3)
        b1_l4 = Tex(r"Magnetic bearing $=$ true bearing $+$").scale(1.0).shift(band_shift(1) + DOWN * 1.2)
        b1_l5 = Tex(r"declination (when declination is west)").scale(1.0).shift(band_shift(1) + DOWN * 1.9)
        self.play(Write(b1_l4))
        self.play(Write(b1_l5))
        self.play(Create(SurroundingRectangle(b1_l5, color=GREEN)))
        self.wait(2.5)
        b1_l6 = MathTex(r"60' = 1^\circ \quad \text{(minutes of arc, not time)}").scale(1.05).shift(band_shift(1) + DOWN * 2.9)
        self.play(Write(b1_l6))
        self.wait(3)

        # --- Band 2 (subtopic_2): the declination calculation, in full
        self.next_band(2)
        b2_title = Tex(r"Given: $18^\circ 19'$ W in 2014, change $5'$/yr W").scale(1.05).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(2)
        b2_q = Tex(r"Calculate the declination for 2025").scale(1.0).shift(band_shift(2) + UP * 1.4)
        self.play(Write(b2_q))
        self.wait(2)
        b2_l1 = MathTex(r"2025 - 2014 = 11 \text{ years}").scale(1.1).shift(band_shift(2) + UP * 0.5)
        self.play(Write(b2_l1))
        self.wait(2)
        b2_l2 = MathTex(r"11 \times 5' = 55' \text{ westward}").scale(1.1).shift(band_shift(2) + DOWN * 0.4)
        self.play(Write(b2_l2))
        self.wait(2)
        b2_l3 = MathTex(r"18^\circ 19' + 55' = 18^\circ 74'").scale(1.1).shift(band_shift(2) + DOWN * 1.3)
        self.play(Write(b2_l3))
        self.wait(2)
        b2_l4 = MathTex(r"74' = 1^\circ 14' \;\Rightarrow\; 19^\circ 14'").scale(1.1).shift(band_shift(2) + DOWN * 2.2)
        self.play(Write(b2_l4))
        self.wait(2)
        b2_l5 = Tex(r"$= 19^\circ 14'$ west of true north").scale(1.1).shift(band_shift(2) + DOWN * 3.1)
        self.play(Write(b2_l5))
        self.play(Create(SurroundingRectangle(b2_l5, color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_2): add or subtract
        self.next_band(3)
        b3_title = Tex("Add or subtract? Read the note").scale(1.2).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(1.5)
        b3_l1 = Tex(r"Westerly declination, westward change:").scale(1.0).shift(band_shift(3) + UP * 1.2)
        b3_l2 = Tex(r"the angle GROWS — add (the SA standard)").scale(1.0).shift(band_shift(3) + UP * 0.4)
        self.play(Write(b3_l1))
        self.play(Write(b3_l2))
        self.play(Create(SurroundingRectangle(b3_l2, color=GREEN)))
        self.wait(2.5)
        b3_l3 = Tex(r"Eastward change: the needle swings back —").scale(1.0).shift(band_shift(3) + DOWN * 0.6)
        b3_l4 = Tex(r"the angle shrinks: subtract").scale(1.0).shift(band_shift(3) + DOWN * 1.4)
        self.play(Write(b3_l3))
        self.play(Write(b3_l4))
        self.wait(2.5)
        b3_l5 = Tex(r"Never assume the direction — read it,").scale(1.0).shift(band_shift(3) + DOWN * 2.4)
        b3_l6 = Tex(r"every time").scale(1.0).shift(band_shift(3) + DOWN * 3.1)
        self.play(Write(b3_l5))
        self.play(Write(b3_l6))
        self.wait(3)

        # --- Band 4 (subtopic_3): area on the orthophoto, in full
        self.next_band(4)
        b4_title = Tex(r"Area: orthophoto, scale 1:10 000").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(2)
        b4_wrong = Tex(r"$3,5 \times 1,8$ in cm, convert later").scale(1.0).shift(band_shift(4) + UP * 1.3)
        self.play(Write(b4_wrong))
        self.play(Create(strike(b4_wrong)))
        self.wait(2)
        b4_rule = Tex(r"Convert EACH side first, then multiply").scale(1.0).shift(band_shift(4) + UP * 0.5)
        self.play(Write(b4_rule))
        self.wait(2)
        b4_l1 = MathTex(r"3,5 \text{ cm} \to 35\,000 \text{ cm} = 350 \text{ m}").scale(1.05).shift(band_shift(4) + DOWN * 0.4)
        self.play(Write(b4_l1))
        self.wait(2)
        b4_l2 = MathTex(r"1,8 \text{ cm} \to 18\,000 \text{ cm} = 180 \text{ m}").scale(1.05).shift(band_shift(4) + DOWN * 1.3)
        self.play(Write(b4_l2))
        self.wait(2)
        b4_l3 = MathTex(r"350 \times 180 = 63\,000").scale(1.1).shift(band_shift(4) + DOWN * 2.2)
        self.play(Write(b4_l3))
        self.wait(2)
        b4_l4 = Tex(r"Area $= 63\,000$ m$^2$").scale(1.1).shift(band_shift(4) + DOWN * 3.1)
        self.play(Write(b4_l4))
        self.play(Create(SurroundingRectangle(b4_l4, color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_3): topographic sheet and units
        self.next_band(5)
        b5_title = Tex(r"Topographic sheet: 1:50 000").scale(1.2).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(1.5)
        b5_l1 = Tex(r"Every centimetre is half a kilometre").scale(1.0).shift(band_shift(5) + UP * 1.3)
        self.play(Write(b5_l1))
        self.wait(2)
        b5_l2 = MathTex(r"4 \text{ cm} \to 2 \text{ km}, \quad 3 \text{ cm} \to 1,5 \text{ km}").scale(1.05).shift(band_shift(5) + UP * 0.4)
        self.play(Write(b5_l2))
        self.wait(2)
        b5_l3 = MathTex(r"2 \times 1,5 = 3").scale(1.1).shift(band_shift(5) + DOWN * 0.5)
        self.play(Write(b5_l3))
        self.wait(1.5)
        b5_l4 = Tex(r"Area $= 3$ km$^2$").scale(1.1).shift(band_shift(5) + DOWN * 1.3)
        self.play(Write(b5_l4))
        self.play(Create(SurroundingRectangle(b5_l4, color=GREEN)))
        self.wait(2.5)
        b5_l5 = Tex(r"m$^2$ for small orthophoto features;").scale(1.0).shift(band_shift(5) + DOWN * 2.2)
        b5_l6 = Tex(r"km$^2$ for big country — land on the unit").scale(1.0).shift(band_shift(5) + DOWN * 2.9)
        b5_l7 = Tex(r"the question names").scale(1.0).shift(band_shift(5) + DOWN * 3.6)
        self.play(Write(b5_l5))
        self.play(Write(b5_l6))
        self.play(Write(b5_l7))
        self.wait(3)

        # --- Band 6 (subtopic_4): the traps, named and struck
        self.next_band(6)
        b6_title = Tex("The traps, named").scale(1.2).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(1.5)
        b6_t1 = MathTex(r"18^\circ 74' \text{ left standing}").scale(1.0).shift(band_shift(6) + UP * 1.3)
        self.play(Write(b6_t1))
        self.play(Create(strike(b6_t1)))
        self.wait(2)
        b6_l1 = Tex(r"$60'$ or more must carry into degrees").scale(1.0).shift(band_shift(6) + UP * 0.5)
        self.play(Write(b6_l1))
        self.wait(2)
        b6_t2 = Tex(r"Answer without ``west of true north''").scale(1.0).shift(band_shift(6) + DOWN * 0.4)
        self.play(Write(b6_t2))
        self.play(Create(strike(b6_t2)))
        self.wait(2)
        b6_t3 = Tex(r"Wrong year gap — count from the margin year").scale(0.95).shift(band_shift(6) + DOWN * 1.3)
        self.play(Write(b6_t3))
        self.wait(2)
        b6_t4 = Tex(r"cm $\times$ cm then convert: the dead end").scale(1.0).shift(band_shift(6) + DOWN * 2.2)
        self.play(Write(b6_t4))
        self.play(Create(strike(b6_t4)))
        self.wait(2)
        b6_l2 = Tex(r"Both sides off the SAME sheet; match the unit").scale(0.95).shift(band_shift(6) + DOWN * 3.1)
        self.play(Write(b6_l2))
        self.wait(3)

        # --- Band 7 (subtopic_4): the answer line and the bigger machine
        self.next_band(7)
        b7_title = Tex("Set out every line").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(1.5)
        b7_l1 = Tex(r"Given values $\to$ operation $\to$ answer with").scale(1.0).shift(band_shift(7) + UP * 1.2)
        b7_l2 = Tex(r"unit — and direction for declination").scale(1.0).shift(band_shift(7) + UP * 0.5)
        self.play(Write(b7_l1))
        self.play(Write(b7_l2))
        self.play(Create(SurroundingRectangle(b7_l2, color=GREEN)))
        self.wait(2.5)
        b7_l3 = Tex(r"Declination feeds every compass bearing;").scale(1.0).shift(band_shift(7) + DOWN * 0.5)
        b7_l4 = Tex(r"area feeds land-use and settlement questions").scale(0.95).shift(band_shift(7) + DOWN * 1.2)
        self.play(Write(b7_l3))
        self.play(Write(b7_l4))
        self.wait(2.5)
        b7_l5 = Tex(r"All three mapwork calculations are one").scale(1.0).shift(band_shift(7) + DOWN * 2.1)
        b7_l6 = Tex(r"discipline: map distance $\to$ ground truth").scale(1.0).shift(band_shift(7) + DOWN * 2.8)
        self.play(Write(b7_l5))
        self.play(Write(b7_l6))
        self.wait(3.5)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): the compass that tells a small lie
        self.next_band(8)
        b8_title = Tex("The compass that tells a small lie").scale(1.15).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = Tex(r"Map: true north. Needle: its own north,").scale(0.95).shift(band_shift(8) + UP * 1.3)
        b8_l2 = Tex(r"off to the west — a wedge of angle between").scale(0.95).shift(band_shift(8) + UP * 0.6)
        self.play(Write(b8_l1))
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = Tex(r"The wedge is the size of the lie — and it").scale(0.95).shift(band_shift(8) + DOWN * 0.3)
        b8_l4 = Tex(r"widens a few minutes every year").scale(0.95).shift(band_shift(8) + DOWN * 1.0)
        self.play(Write(b8_l3))
        self.play(Write(b8_l4))
        self.wait(2.5)
        b8_l5 = Tex(r"Translation sentence: magnetic bearing $=$").scale(0.95).shift(band_shift(8) + DOWN * 1.9)
        b8_l6 = Tex(r"true bearing $+$ the wedge (west)").scale(0.95).shift(band_shift(8) + DOWN * 2.6)
        self.play(Write(b8_l5))
        self.play(Write(b8_l6))
        self.play(Create(SurroundingRectangle(b8_l6, color=GREEN)))
        self.wait(2.5)
        b8_l7 = Tex(r"Your job: today's size of the lie").scale(1.0).shift(band_shift(8) + DOWN * 3.4)
        self.play(Write(b8_l7))
        self.wait(3)

        # --- Band 9 (subtopic_6): minutes like a clock
        self.next_band(9)
        b9_title = Tex("Minutes that are not time").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex(r"Sixty make one whole — clock rule").scale(1.0).shift(band_shift(9) + UP * 1.3)
        self.play(Write(b9_l1))
        self.wait(2)
        b9_l2 = MathTex(r"2025 - 2014 = 11").scale(1.05).shift(band_shift(9) + UP * 0.5)
        b9_l3 = MathTex(r"11 \times 5' = 55'").scale(1.05).shift(band_shift(9) + DOWN * 0.3)
        b9_l4 = MathTex(r"19' + 55' = 74'").scale(1.05).shift(band_shift(9) + DOWN * 1.1)
        self.play(Write(b9_l2))
        self.wait(1.8)
        self.play(Write(b9_l3))
        self.wait(1.8)
        self.play(Write(b9_l4))
        self.wait(1.8)
        b9_l5 = Tex(r"74 past 6 is 14 past 7: roll sixty over").scale(0.95).shift(band_shift(9) + DOWN * 1.9)
        self.play(Write(b9_l5))
        self.wait(2)
        b9_l6 = MathTex(r"18^\circ 74' \to 19^\circ 14' \text{ W of true north}").scale(1.05).shift(band_shift(9) + DOWN * 2.8)
        self.play(Write(b9_l6))
        self.play(Create(SurroundingRectangle(b9_l6, color=GREEN)))
        self.wait(2)
        b9_l7 = Tex(r"Westward drift: add. Eastward: subtract").scale(0.95).shift(band_shift(9) + DOWN * 3.6)
        self.play(Write(b9_l7))
        self.wait(3)

        # --- Band 10 (subtopic_7): the rugby field sense check
        self.next_band(10)
        b10_title = Tex("The rugby field in your answer book").scale(1.1).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_title))
        self.wait(2)
        b10_l1 = Tex(r"Tiling a floor: un-shrink each side first").scale(0.95).shift(band_shift(10) + UP * 1.3)
        self.play(Write(b10_l1))
        self.wait(2)
        b10_l2 = MathTex(r"3,5 \text{ cm} \to 350 \text{ m}; \quad 1,8 \text{ cm} \to 180 \text{ m}").scale(1.0).shift(band_shift(10) + UP * 0.4)
        self.play(Write(b10_l2))
        self.wait(2)
        b10_l3 = MathTex(r"350 \times 180 = 63\,000 \text{ m}^2").scale(1.05).shift(band_shift(10) + DOWN * 0.5)
        self.play(Write(b10_l3))
        self.play(Create(SurroundingRectangle(b10_l3, color=GREEN)))
        self.wait(2.5)
        b10_l4 = MathTex(r"\text{Rugby field} \approx 100 \times 70 = 7\,000 \text{ m}^2").scale(1.0).shift(band_shift(10) + DOWN * 1.5)
        b10_l5 = Tex(r"Our block $=$ nine rugby fields — sensible").scale(0.95).shift(band_shift(10) + DOWN * 2.3)
        self.play(Write(b10_l4))
        self.play(Write(b10_l5))
        self.wait(2.5)
        b10_l6 = Tex(r"Paper cm $\times$ paper cm first").scale(0.95).shift(band_shift(10) + DOWN * 3.1)
        self.play(Write(b10_l6))
        self.play(Create(strike(b10_l6)))
        self.wait(1.5)
        b10_l7 = Tex(r"Convert, convert, multiply — in that order").scale(0.95).shift(band_shift(10) + DOWN * 3.8)
        self.play(Write(b10_l7))
        self.wait(4)
