# Copyright (c) 2026 ROKCT INTELLIGENCE (PTY) LTD
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from manim import *

# Band-layout whiteboard scene for "Production Cost Statement and Break-Even"
# (grade 12, term 2, cost accounting). One band per teaching beat; the camera
# moves down and nothing is removed. Part 1 (Expert) = subtopics 1-4, Part 2
# (Simplifier) = subtopics 5-7 in fresh bands. Exporter-safe primitives only;
# write-only reveals. Subtopic durations 230/250/230/250/190/205/215 of
# 1570 s guide the apportioning.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class ProductionCostBreakEvenSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md plays.
        self.wait(14)

        # ===== Part 1 — Expert =====
        # --- Band 0 (subtopic_1): the three factory cost families ---
        title = Tex("Production Cost Statement and Break-Even").scale(1.1).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex("Direct materials: leather, steel, milk").scale(1.0).shift(UP * 1.2)
        b0_l2 = Tex("Direct labour: the hands that build it").scale(1.0).shift(UP * 0.5)
        self.play(Write(b0_l1))
        self.wait(2)
        self.play(Write(b0_l2))
        self.wait(2)
        b0_l3 = Tex("Together: PRIME COST").scale(1.05).shift(DOWN * 0.3)
        self.play(Write(b0_l3))
        self.play(Create(SurroundingRectangle(b0_l3, color=GREEN)))
        self.wait(2)
        b0_l4 = Tex("$+$ Factory overheads: rent, electricity,").scale(1.0).shift(DOWN * 1.1)
        b0_l5 = Tex("machine depreciation, indirect labour").scale(1.0).shift(DOWN * 1.8)
        self.play(Write(b0_l4))
        self.play(Write(b0_l5))
        self.wait(2)
        b0_trap = Tex("Showroom rent $=$ factory overhead?").scale(0.95).shift(DOWN * 2.6)
        self.play(Write(b0_trap))
        self.play(Create(strike(b0_trap)))
        b0_fix = Tex("Selling cost — the word FACTORY matters").scale(0.95).shift(DOWN * 3.3)
        self.play(Write(b0_fix))
        self.wait(3)

        # --- Band 1 (subtopic_1): three stocks, not one ---
        self.next_band(1)
        b1_t = Tex("Three stocks, not one").scale(1.15).shift(band_shift(1) + UP * 2.3)
        self.play(Write(b1_t))
        self.wait(2)
        grid = Rectangle(width=11.0, height=2.6).shift(band_shift(1) + UP * 0.5)
        v1 = Line(grid.get_top() + LEFT * 1.85, grid.get_bottom() + LEFT * 1.85)
        v2 = Line(grid.get_top() + RIGHT * 1.85, grid.get_bottom() + RIGHT * 1.85)
        self.play(Create(grid), Create(v1), Create(v2))
        c1 = Tex("Raw\\\\materials").scale(0.9).shift(band_shift(1) + UP * 1.1 + LEFT * 3.7)
        c2 = Tex("Work-in-\\\\progress").scale(0.9).shift(band_shift(1) + UP * 1.1)
        c3 = Tex("Finished\\\\goods").scale(0.9).shift(band_shift(1) + UP * 1.1 + RIGHT * 3.7)
        self.play(Write(c1), Write(c2), Write(c3))
        self.wait(2)
        d1 = Tex("waiting in\\\\the storeroom").scale(0.8).shift(band_shift(1) + DOWN * 0.2 + LEFT * 3.7)
        d2 = Tex("started, not\\\\finished").scale(0.8).shift(band_shift(1) + DOWN * 0.2)
        d3 = Tex("ready for\\\\sale").scale(0.8).shift(band_shift(1) + DOWN * 0.2 + RIGHT * 3.7)
        self.play(Write(d1))
        self.play(Write(d2))
        self.play(Write(d3))
        self.wait(2.5)
        b1_l1 = Tex("Beyond the factory: administration cost").scale(1.0).shift(band_shift(1) + DOWN * 1.6)
        b1_l2 = Tex("and selling and distribution cost").scale(1.0).shift(band_shift(1) + DOWN * 2.3)
        self.play(Write(b1_l1))
        self.play(Write(b1_l2))
        self.wait(3)

        # --- Band 2 (subtopic_2): the direct materials note ---
        self.next_band(2)
        b2_t = Tex("Khanya Footwear: materials USED").scale(1.1).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(2)
        b2_l1 = Tex("Opening raw materials \\quad R60 000").scale(1.0).shift(band_shift(2) + UP * 1.2)
        b2_l2 = Tex("$+$ Purchases \\quad R560 000").scale(1.0).shift(band_shift(2) + UP * 0.4)
        b2_l3 = Tex("$+$ Carriage on purchases \\quad R25 000").scale(1.0).shift(band_shift(2) + DOWN * 0.4)
        b2_l4 = Tex("$=$ Available \\quad R645 000").scale(1.0).shift(band_shift(2) + DOWN * 1.2)
        b2_l5 = Tex("$-$ Closing stock \\quad R95 000").scale(1.0).shift(band_shift(2) + DOWN * 2.0)
        b2_l6 = Tex("Direct material cost: R550 000").scale(1.05).shift(band_shift(2) + DOWN * 2.9)
        self.play(Write(b2_l1))
        self.wait(1.5)
        self.play(Write(b2_l2))
        self.wait(1.5)
        self.play(Write(b2_l3))
        self.wait(1.5)
        self.play(Write(b2_l4))
        self.wait(1.5)
        self.play(Write(b2_l5))
        self.wait(1.5)
        self.play(Write(b2_l6))
        self.play(Create(SurroundingRectangle(b2_l6, color=GREEN)))
        b2_l7 = Tex("buying is not using — the storeroom stays out").scale(0.9).shift(band_shift(2) + DOWN * 3.6)
        self.play(Write(b2_l7))
        self.wait(3)

        # --- Band 3 (subtopic_2): down to cost of production ---
        self.next_band(3)
        b3_t = Tex("The production cost statement").scale(1.1).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t))
        self.wait(2)
        b3_l1 = Tex("$+$ Direct labour R350 000:").scale(1.0).shift(band_shift(3) + UP * 1.2)
        b3_l2 = Tex("PRIME COST R900 000").scale(1.05).shift(band_shift(3) + UP * 0.4)
        self.play(Write(b3_l1))
        self.play(Write(b3_l2))
        self.wait(2)
        b3_l3 = Tex("$+$ Factory overheads R390 000:").scale(1.0).shift(band_shift(3) + DOWN * 0.4)
        b3_l4 = Tex("total manufacturing cost R1 290 000").scale(1.0).shift(band_shift(3) + DOWN * 1.2)
        self.play(Write(b3_l3))
        self.play(Write(b3_l4))
        self.wait(2.5)
        b3_l5 = Tex("$+$ opening WIP R40 000 $-$ closing R80 000").scale(0.95).shift(band_shift(3) + DOWN * 2.0)
        b3_l6 = Tex("Cost of production: R1 250 000").scale(1.05).shift(band_shift(3) + DOWN * 2.8)
        self.play(Write(b3_l5))
        self.wait(2)
        self.play(Write(b3_l6))
        self.play(Create(SurroundingRectangle(b3_l6, color=GREEN)))
        b3_l7 = Tex("50 000 pairs: unit cost R25").scale(1.0).shift(band_shift(3) + DOWN * 3.6)
        self.play(Write(b3_l7))
        self.wait(3)

        # --- Band 4 (subtopic_3): finished goods to gross profit ---
        self.next_band(4)
        b4_t = Tex("Factory floor to income statement").scale(1.1).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(2)
        b4_l1 = Tex("Finished goods: R100 000 $+$ R1 250 000").scale(1.0).shift(band_shift(4) + UP * 1.2)
        b4_l2 = Tex("$=$ R1 350 000 $-$ closing R150 000").scale(1.0).shift(band_shift(4) + UP * 0.4)
        b4_l3 = Tex("Cost of sales R1 200 000 (48 000 sold)").scale(1.0).shift(band_shift(4) + DOWN * 0.4)
        self.play(Write(b4_l1))
        self.wait(2)
        self.play(Write(b4_l2))
        self.wait(2)
        self.play(Write(b4_l3))
        self.wait(2)
        b4_l4 = Tex("Sales: 48 000 $\\times$ R35 $=$ R1 680 000").scale(1.0).shift(band_shift(4) + DOWN * 1.3)
        b4_l5 = Tex("Gross profit R480 000").scale(1.05).shift(band_shift(4) + DOWN * 2.1)
        self.play(Write(b4_l4))
        self.wait(2)
        self.play(Write(b4_l5))
        self.play(Create(SurroundingRectangle(b4_l5, color=GREEN)))
        b4_l6 = Tex("check: 480/1 200 $=$ 40\\% on cost — policy").scale(0.95).shift(band_shift(4) + DOWN * 2.9)
        self.play(Write(b4_l6))
        self.wait(3)

        # --- Band 5 (subtopic_3): operating costs and the address game ---
        self.next_band(5)
        b5_t = Tex("Every expense has one address").scale(1.1).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_t))
        self.wait(2)
        b5_l1 = Tex("Administration R150 000;").scale(1.0).shift(band_shift(5) + UP * 1.2)
        b5_l2 = Tex("selling and distribution R138 000").scale(1.0).shift(band_shift(5) + UP * 0.4)
        b5_l3 = Tex("Net profit: 480 $-$ 150 $-$ 138 $=$ R192 000").scale(1.0).shift(band_shift(5) + DOWN * 0.5)
        self.play(Write(b5_l1))
        self.play(Write(b5_l2))
        self.wait(2)
        self.play(Write(b5_l3))
        self.play(Create(SurroundingRectangle(b5_l3, color=GREEN)))
        self.wait(2.5)
        b5_l4 = Tex("Depreciation splits by USE: machinery to").scale(0.95).shift(band_shift(5) + DOWN * 1.4)
        b5_l5 = Tex("factory, office computers to admin,").scale(0.95).shift(band_shift(5) + DOWN * 2.1)
        b5_l6 = Tex("delivery vehicles to selling").scale(0.95).shift(band_shift(5) + DOWN * 2.8)
        self.play(Write(b5_l4))
        self.play(Write(b5_l5))
        self.play(Write(b5_l6))
        self.wait(3)

        # --- Band 6 (subtopic_4): break-even, the drill case ---
        self.next_band(6)
        b6_t = Tex("Break-even: sort by BEHAVIOUR").scale(1.1).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_t))
        self.wait(2)
        b6_l1 = Tex("Price R35; variable R23 a unit;").scale(1.0).shift(band_shift(6) + UP * 1.2)
        b6_l2 = Tex("fixed costs R540 000 a year").scale(1.0).shift(band_shift(6) + UP * 0.4)
        self.play(Write(b6_l1))
        self.play(Write(b6_l2))
        self.wait(2)
        b6_l3 = Tex("Contribution: R35 $-$ R23 $=$ R12").scale(1.05).shift(band_shift(6) + DOWN * 0.5)
        self.play(Write(b6_l3))
        self.wait(2)
        b6_l4 = Tex("R540 000 $\\div$ R12 $=$ 45 000 units").scale(1.1).shift(band_shift(6) + DOWN * 1.4)
        self.play(Write(b6_l4))
        self.play(Create(SurroundingRectangle(b6_l4, color=GREEN)))
        self.wait(2)
        b6_l5 = Tex("Sold 48 000: a 3 000-unit cushion —").scale(1.0).shift(band_shift(6) + DOWN * 2.3)
        b6_l6 = Tex("state it; the interpretation asks for it").scale(1.0).shift(band_shift(6) + DOWN * 3.0)
        self.play(Write(b6_l5))
        self.play(Write(b6_l6))
        self.wait(3)

        # --- Band 7 (subtopic_4): the levers, and factory ethics ---
        self.next_band(7)
        b7_t = Tex("The levers, and the ethics").scale(1.1).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(2)
        b7_l1 = Tex("Price up: contribution widens, line falls").scale(0.95).shift(band_shift(7) + UP * 1.2)
        b7_l2 = Tex("Materials dearer: line climbs;").scale(0.95).shift(band_shift(7) + UP * 0.5)
        b7_l3 = Tex("new machine: the fixed pile grows").scale(0.95).shift(band_shift(7) + DOWN * 0.2)
        self.play(Write(b7_l1))
        self.wait(2)
        self.play(Write(b7_l2))
        self.play(Write(b7_l3))
        self.wait(2.5)
        b7_l4 = Tex("Ethics: no expired or substandard goods;").scale(0.95).shift(band_shift(7) + DOWN * 1.1)
        b7_l5 = Tex("honest sourcing; price fixing is illegal").scale(0.95).shift(band_shift(7) + DOWN * 1.8)
        self.play(Write(b7_l4))
        self.play(Write(b7_l5))
        self.wait(2.5)
        b7_l6 = Tex("Controls: requisitions, clock cards,").scale(0.95).shift(band_shift(7) + DOWN * 2.6)
        b7_l7 = Tex("independent production counts, waste watched").scale(0.9).shift(band_shift(7) + DOWN * 3.3)
        self.play(Write(b7_l6))
        self.play(Write(b7_l7))
        self.wait(3)

        # ===== Part 2 — Simplifier =====
        # --- Band 8 (subtopic_5): Ma Zondi's vetkoek stand ---
        self.next_band(8)
        b8_t = Tex("Ma Zondi's vetkoek stand").scale(1.1).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_t))
        self.wait(2)
        b8_l1 = Tex("Flour, yeast, oil, mince: direct materials").scale(0.95).shift(band_shift(8) + UP * 1.2)
        b8_l2 = Tex("Bongani shaping dough: direct labour").scale(0.95).shift(band_shift(8) + UP * 0.5)
        b8_l3 = Tex("Gas, stall fee, deep oil: overheads —").scale(0.95).shift(band_shift(8) + DOWN * 0.2)
        b8_l4 = Tex("real, spread over all, pinned to none").scale(0.95).shift(band_shift(8) + DOWN * 0.9)
        self.play(Write(b8_l1))
        self.wait(2)
        self.play(Write(b8_l2))
        self.wait(2)
        self.play(Write(b8_l3))
        self.play(Write(b8_l4))
        self.wait(2.5)
        b8_l5 = Tex("Crate $=$ raw materials; tray of dough").scale(0.95).shift(band_shift(8) + DOWN * 1.8)
        b8_l6 = Tex("$=$ work-in-progress; warmer $=$ finished").scale(0.95).shift(band_shift(8) + DOWN * 2.5)
        self.play(Write(b8_l5))
        self.play(Write(b8_l6))
        self.wait(2.5)
        b8_l7 = Tex("Stand makes; office runs; selling moves").scale(0.95).shift(band_shift(8) + DOWN * 3.3)
        self.play(Write(b8_l7))
        self.wait(3)

        # --- Band 9 (subtopic_6): what one vetkoek costs ---
        self.next_band(9)
        b9_t = Tex("What does ONE vetkoek cost?").scale(1.1).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(2)
        b9_l1 = Tex("Ingredients USED R7 300 (bought R8 500;").scale(0.95).shift(band_shift(9) + UP * 1.2)
        b9_l2 = Tex("R1 200 still in the pantry stays out)").scale(0.95).shift(band_shift(9) + UP * 0.5)
        self.play(Write(b9_l1))
        self.play(Write(b9_l2))
        self.wait(2.5)
        b9_l3 = Tex("$+$ wages R4 200 $+$ overheads R3 200").scale(0.95).shift(band_shift(9) + DOWN * 0.3)
        b9_l4 = Tex("$=$ stand total R14 700").scale(1.0).shift(band_shift(9) + DOWN * 1.0)
        self.play(Write(b9_l3))
        self.wait(2)
        self.play(Write(b9_l4))
        self.wait(2)
        b9_l5 = Tex("Dough trays: $+$R300 old $-$R600 new").scale(0.95).shift(band_shift(9) + DOWN * 1.8)
        b9_l6 = Tex("$=$ finished production R14 400").scale(1.0).shift(band_shift(9) + DOWN * 2.5)
        self.play(Write(b9_l5))
        self.wait(2)
        self.play(Write(b9_l6))
        self.wait(2)
        b9_l7 = Tex("R14 400 $\\div$ 1 200 $=$ R12 a vetkoek").scale(1.05).shift(band_shift(9) + DOWN * 3.3)
        self.play(Write(b9_l7))
        self.play(Create(SurroundingRectangle(b9_l7, color=GREEN)))
        self.wait(3)

        # --- Band 10 (subtopic_7): break-even at the stand ---
        self.next_band(10)
        b10_t = Tex("How many before she smiles?").scale(1.1).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_t))
        self.wait(2)
        b10_l1 = Tex("Each vetkoek: sells R18, eats R10 —").scale(1.0).shift(band_shift(10) + UP * 1.2)
        b10_l2 = Tex("contributes R8; the fee pile is R4 800").scale(1.0).shift(band_shift(10) + UP * 0.4)
        self.play(Write(b10_l1))
        self.play(Write(b10_l2))
        self.wait(2.5)
        b10_l3 = Tex("R4 800 $\\div$ R8 $=$ 600 vetkoek").scale(1.1).shift(band_shift(10) + DOWN * 0.5)
        self.play(Write(b10_l3))
        self.play(Create(SurroundingRectangle(b10_l3, color=GREEN)))
        self.wait(2)
        b10_l4 = Tex("Proof: 600 $\\times$ R18 $=$ R10 800 in;").scale(1.0).shift(band_shift(10) + DOWN * 1.4)
        b10_l5 = Tex("ingredients R6 000 $+$ fee R4 800 out").scale(1.0).shift(band_shift(10) + DOWN * 2.2)
        b10_l6 = Tex("$=$ zero — the smile starts at 601").scale(1.0).shift(band_shift(10) + DOWN * 3.0)
        self.play(Write(b10_l4))
        self.wait(2)
        self.play(Write(b10_l5))
        self.wait(2)
        self.play(Write(b10_l6))
        self.wait(3)

        # --- Band 11 (subtopic_7): her levers, and her ethics ---
        self.next_band(11)
        b11_t = Tex("Move the levers, keep the ethics").scale(1.1).shift(band_shift(11) + UP * 2.2)
        self.play(Write(b11_t))
        self.wait(2)
        b11_l1 = Tex("Mince up, eats R12: line jumps to 800").scale(1.0).shift(band_shift(11) + UP * 1.2)
        b11_l2 = Tex("Price R20: contribution R10, line at 480").scale(1.0).shift(band_shift(11) + UP * 0.4)
        b11_l3 = Tex("Second stand: R4 800 more in fees —").scale(1.0).shift(band_shift(11) + DOWN * 0.4)
        b11_l4 = Tex("break-even doubles before growth pays").scale(1.0).shift(band_shift(11) + DOWN * 1.1)
        self.play(Write(b11_l1))
        self.wait(2)
        self.play(Write(b11_l2))
        self.wait(2)
        self.play(Write(b11_l3))
        self.play(Write(b11_l4))
        self.wait(2.5)
        b11_l5 = Tex("No day-old sold as fresh; no price deals").scale(0.95).shift(band_shift(11) + DOWN * 2.0)
        b11_l6 = Tex("with the seller two tables down; bags").scale(0.95).shift(band_shift(11) + DOWN * 2.7)
        b11_l7 = Tex("counted against batches — stand-sized controls").scale(0.95).shift(band_shift(11) + DOWN * 3.4)
        self.play(Write(b11_l5))
        self.play(Write(b11_l6))
        self.play(Write(b11_l7))
        self.wait(4)
