from manim import *

# Band-layout whiteboard scene for Conversions, Volume and Surface Area.
# One band per teaching beat; camera moves down, earlier work stays on the
# canvas. Exporter-supported mobjects only; every working line is its own
# single-string Tex/MathTex revealed with Write. No transforms, no FadeOut.
#
# Subtopic time shares (subtopics.json, total 1470 s):
# 215/215/225/230/195/195/195 -> bands 0-1 / 2-3 / 4-5 / 6-7 / 8 / 9 / 10.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class ConversionsVolumeSurfaceAreaSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic full-screen while intro.md audio plays.
        self.wait(15)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): the metric family and the imperial table
        title = Tex("Conversions, Volume and Surface Area").scale(1.25).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex("Metric moves in tens: shift the comma").scale(1.1).shift(UP * 1.2)
        b0_l2 = MathTex(r"2\;500 \text{ g} = 2{,}5 \text{ kg} \qquad 0{,}75 \text{ m} = 75 \text{ cm}").scale(0.92).shift(UP * 0.3)
        self.play(Write(b0_l1))
        self.wait(2)
        self.play(Write(b0_l2))
        self.wait(2.5)
        b0_l3 = Tex("Imperial needs a supplied factor table:").scale(1.05).shift(DOWN * 0.6)
        b0_l4 = MathTex(r"1 \text{ inch} = 2{,}54 \text{ cm}; \quad 1 \text{ kg} = 2{,}205 \text{ lb}").scale(0.95).shift(DOWN * 1.5)
        b0_l5 = MathTex(r"1 \text{ mile} = 1{,}609 \text{ km}; \quad 1 \text{ gal} = 3{,}785 \ell").scale(0.98).shift(DOWN * 2.4)
        self.play(Write(b0_l3))
        self.wait(2)
        self.play(Write(b0_l4))
        self.wait(2)
        self.play(Write(b0_l5))
        self.wait(3)

        # --- Band 1 (subtopic_1): the recipe and the oven dial
        self.next_band(1)
        b1_t = Tex("From the named unit multiply; to it divide").scale(1.1).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_t))
        self.wait(1.5)
        b1_l1 = MathTex(r"\text{2 lb flour: } 2 \div 2{,}205 = 0{,}907 \text{ kg} \approx 907 \text{ g}").scale(0.89).shift(band_shift(1) + UP * 1.1)
        self.play(Write(b1_l1))
        self.play(Create(SurroundingRectangle(b1_l1, color=GREEN)))
        self.wait(2.5)
        b1_l2 = Tex("Temperature is a FORMULA, not a factor:").scale(1.05).shift(band_shift(1) + UP * 0.1)
        b1_l3 = MathTex(r"F = 1{,}8 \times C + 32").scale(1.1).shift(band_shift(1) + DOWN * 0.8)
        b1_l4 = MathTex(r"350 - 32 = 318; \quad 318 \div 1{,}8 = 176{,}7\,^\circ\text{C}").scale(1.0).shift(band_shift(1) + DOWN * 1.7)
        b1_l5 = Tex(r"Set the dial to 180 °C — the nearest setting").scale(1.05).shift(band_shift(1) + DOWN * 2.6)
        self.play(Write(b1_l2))
        self.wait(2)
        self.play(Write(b1_l3))
        self.wait(2)
        self.play(Write(b1_l4))
        self.wait(2.5)
        self.play(Write(b1_l5))
        self.play(Create(SurroundingRectangle(b1_l5, color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): the cylinder tank, worked in full
        self.next_band(2)
        b2_t = Tex("Volume of the tank: a cylinder").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(1.5)
        b2_l1 = MathTex(r"V = \pi \times r^2 \times h, \quad \pi = 3{,}142").scale(1.1).shift(band_shift(2) + UP * 1.2)
        b2_l2 = MathTex(r"r = 0{,}9 \text{ m}: \quad 0{,}9 \times 0{,}9 = 0{,}81").scale(1.05).shift(band_shift(2) + UP * 0.3)
        b2_l3 = MathTex(r"0{,}81 \times 1{,}8 = 1{,}458").scale(1.05).shift(band_shift(2) + DOWN * 0.6)
        b2_l4 = MathTex(r"3{,}142 \times 1{,}458 = 4{,}581 \text{ m}^3").scale(1.05).shift(band_shift(2) + DOWN * 1.5)
        b2_l5 = MathTex(r"4{,}581 \times 1\;000 = 4\;581 \text{ litres}").scale(1.1).shift(band_shift(2) + DOWN * 2.5)
        self.play(Write(b2_l1))
        self.wait(2.5)
        self.play(Write(b2_l2))
        self.wait(2)
        self.play(Write(b2_l3))
        self.wait(2)
        self.play(Write(b2_l4))
        self.wait(2)
        self.play(Write(b2_l5))
        self.play(Create(SurroundingRectangle(b2_l5, color=GREEN)))
        self.wait(2)
        b2_l6 = Tex("Brochure promised 4 500: the promise checks out").scale(1.0).shift(band_shift(2) + DOWN * 3.2)
        self.play(Write(b2_l6))
        self.wait(3)

        # --- Band 3 (subtopic_2): the freezer, and the radius trap
        self.next_band(3)
        b3_t = Tex("The freezer: a rectangular prism").scale(1.15).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t))
        self.wait(1.5)
        b3_l1 = MathTex(r"V = l \times w \times h").scale(1.1).shift(band_shift(3) + UP * 1.2)
        b3_l2 = MathTex(r"1{,}2 \times 0{,}8 \times 0{,}9 = 0{,}864 \text{ m}^3 = 864 \text{ litres}").scale(1.0).shift(band_shift(3) + UP * 0.3)
        self.play(Write(b3_l1))
        self.wait(2)
        self.play(Write(b3_l2))
        self.play(Create(SurroundingRectangle(b3_l2, color=GREEN)))
        self.wait(2.5)
        b3_l3 = MathTex(r"\text{Tank 1,8 m wide: } r = 1{,}8 \text{ (quadruples } V\text{)}").scale(1.0).shift(band_shift(3) + DOWN * 0.7)
        self.play(Write(b3_l3))
        self.play(Create(strike(b3_l3)))
        self.wait(2)
        b3_l4 = MathTex(r"\text{Radius is HALF the diameter: } r = 0{,}9 \text{ m}").scale(1.05).shift(band_shift(3) + DOWN * 1.7)
        b3_l5 = Tex("Match the units BEFORE substituting").scale(1.05).shift(band_shift(3) + DOWN * 2.6)
        self.play(Write(b3_l4))
        self.wait(2)
        self.play(Write(b3_l5))
        self.wait(3)

        # --- Band 4 (subtopic_3): surface area of the tank
        self.next_band(4)
        b4_t = Tex("Surface area: curved wall plus the top").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(1.5)
        b4_l1 = Tex("The wall unrolls into a rectangle:").scale(1.05).shift(band_shift(4) + UP * 1.2)
        b4_l2 = MathTex(r"2 \times 3{,}142 \times 0{,}9 = 5{,}656 \text{ (circumference)}").scale(1.0).shift(band_shift(4) + UP * 0.3)
        b4_l3 = MathTex(r"5{,}656 \times 1{,}8 = 10{,}180 \text{ m}^2").scale(1.05).shift(band_shift(4) + DOWN * 0.6)
        b4_l4 = MathTex(r"\text{Top circle: } 3{,}142 \times 0{,}81 = 2{,}545 \text{ m}^2").scale(1.05).shift(band_shift(4) + DOWN * 1.5)
        b4_l5 = MathTex(r"10{,}180 + 2{,}545 = 12{,}73 \text{ m}^2").scale(1.1).shift(band_shift(4) + DOWN * 2.5)
        self.play(Write(b4_l1))
        self.wait(2)
        self.play(Write(b4_l2))
        self.wait(2.5)
        self.play(Write(b4_l3))
        self.wait(2)
        self.play(Write(b4_l4))
        self.wait(2)
        self.play(Write(b4_l5))
        self.play(Create(SurroundingRectangle(b4_l5, color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_3): the paint decision — buying rounds UP
        self.next_band(5)
        b5_t = Tex("The buying decision: round UP").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_t))
        self.wait(1.5)
        b5_l1 = Tex(r"One litre covers 9 m$^2$").scale(1.05).shift(band_shift(5) + UP * 1.1)
        b5_l2 = MathTex(r"12{,}73 \div 9 = 1{,}41 \text{ litres}").scale(1.1).shift(band_shift(5) + UP * 0.2)
        b5_l3 = Tex("Buy 2 litres — the shop sells whole tins").scale(1.1).shift(band_shift(5) + DOWN * 0.8)
        self.play(Write(b5_l1))
        self.wait(2)
        self.play(Write(b5_l2))
        self.wait(2)
        self.play(Write(b5_l3))
        self.play(Create(SurroundingRectangle(b5_l3, color=GREEN)))
        self.wait(2.5)
        b5_l4 = Tex("Rounding down leaves a third of the tank bare").scale(1.05).shift(band_shift(5) + DOWN * 1.8)
        b5_l5 = Tex("Read WHICH faces count: the base gets none").scale(1.05).shift(band_shift(5) + DOWN * 2.7)
        self.play(Write(b5_l4))
        self.wait(2)
        self.play(Write(b5_l5))
        self.wait(3)

        # --- Band 6 (subtopic_4): speed and filling time
        self.next_band(6)
        b6_t = Tex("Rates: the unit says what to divide").scale(1.15).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_t))
        self.wait(1.5)
        b6_l1 = MathTex(r"\text{Speed: } 420 \div 4{,}5 = 93{,}33 \text{ km/h}").scale(1.05).shift(band_shift(6) + UP * 1.1)
        self.play(Write(b6_l1))
        self.wait(2.5)
        b6_l2 = Tex("Filling at 12 litres per minute:").scale(1.05).shift(band_shift(6) + UP * 0.2)
        b6_l3 = MathTex(r"4\;581 \div 12 = 381{,}75 \text{ min}").scale(1.05).shift(band_shift(6) + DOWN * 0.7)
        b6_l4 = MathTex(r"381{,}75 \text{ min} = 6 \text{ h } 22 \text{ min}").scale(1.05).shift(band_shift(6) + DOWN * 1.6)
        b6_l5 = Tex("Tap open 08:00: full a little after 14:20").scale(1.05).shift(band_shift(6) + DOWN * 2.6)
        self.play(Write(b6_l2))
        self.wait(2)
        self.play(Write(b6_l3))
        self.wait(2)
        self.play(Write(b6_l4))
        self.wait(2)
        self.play(Write(b6_l5))
        self.play(Create(SurroundingRectangle(b6_l5, color=GREEN)))
        self.wait(3)

        # --- Band 7 (subtopic_4): cost rates and the better buy
        self.next_band(7)
        b7_t = Tex("Value for money: rands per kilogram").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(1.5)
        b7_l1 = MathTex(r"\text{5 kg bag: } 89{,}99 \div 5 = \text{R}18{,}00 \text{ per kg}").scale(1.0).shift(band_shift(7) + UP * 1.1)
        b7_l2 = MathTex(r"\text{10 kg bag: } 169{,}99 \div 10 = \text{R}17{,}00 \text{ per kg}").scale(1.0).shift(band_shift(7) + UP * 0.2)
        b7_l3 = Tex("Bigger bag saves R1 on every kilogram").scale(1.05).shift(band_shift(7) + DOWN * 0.8)
        self.play(Write(b7_l1))
        self.wait(2.5)
        self.play(Write(b7_l2))
        self.wait(2.5)
        self.play(Write(b7_l3))
        self.play(Create(SurroundingRectangle(b7_l3, color=GREEN)))
        self.wait(2.5)
        b7_l4 = Tex("...but only if all 10 kg get used in time").scale(1.05).shift(band_shift(7) + DOWN * 1.8)
        b7_l5 = Tex("The paper awards calculation AND judgement").scale(1.05).shift(band_shift(7) + DOWN * 2.7)
        self.play(Write(b7_l4))
        self.wait(2)
        self.play(Write(b7_l5))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): changing units without fear
        self.next_band(8)
        b8_t = Tex("Should the number grow or shrink?").scale(1.15).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_t))
        self.wait(1.5)
        b8_l1 = Tex("Down to smaller units, the number grows:").scale(1.05).shift(band_shift(8) + UP * 1.2)
        b8_l2 = MathTex(r"2{,}5 \text{ kg} \rightarrow 2\;500 \text{ g}; \quad 75 \text{ cm} \rightarrow 0{,}75 \text{ m}").scale(0.91).shift(band_shift(8) + UP * 0.3)
        self.play(Write(b8_l1))
        self.wait(2)
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = MathTex(r"\text{2 lb} \times 2{,}205 = 4{,}41 \text{ kg — moved the wrong way}").scale(0.95).shift(band_shift(8) + DOWN * 0.6)
        self.play(Write(b8_l3))
        self.play(Create(strike(b8_l3)))
        self.wait(2)
        b8_l4 = MathTex(r"2 \div 2{,}205 = 0{,}907 \text{ kg} \approx 907 \text{ g}").scale(1.05).shift(band_shift(8) + DOWN * 1.6)
        self.play(Write(b8_l4))
        self.play(Create(SurroundingRectangle(b8_l4, color=GREEN)))
        self.wait(2.5)
        b8_l5 = MathTex(r"\text{Oven: } 350 \rightarrow 318 \rightarrow 177 \rightarrow \text{dial } 180\,^\circ\text{C}").scale(0.95).shift(band_shift(8) + DOWN * 2.6)
        self.play(Write(b8_l5))
        self.wait(3)

        # --- Band 9 (subtopic_6): filling the tank, litre-boxes
        self.next_band(9)
        b9_t = Tex("Volume counts litre-boxes inside a shape").scale(1.1).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(1.5)
        b9_l1 = MathTex(r"1 \text{ m}^3 = 1\;000 \text{ litres}").scale(1.1).shift(band_shift(9) + UP * 1.2)
        b9_l2 = Tex("1,8 m across, so radius is HALF: 0,9").scale(1.05).shift(band_shift(9) + UP * 0.3)
        b9_l3 = MathTex(r"\text{Floor: } 3{,}142 \times 0{,}81 = 2{,}545 \text{ m}^2").scale(1.05).shift(band_shift(9) + DOWN * 0.6)
        b9_l4 = MathTex(r"2{,}545 \times 1{,}8 = 4{,}581 \text{ m}^3 = 4\;581 \ell").scale(1.05).shift(band_shift(9) + DOWN * 1.6)
        self.play(Write(b9_l1))
        self.wait(2.5)
        self.play(Write(b9_l2))
        self.wait(2)
        self.play(Write(b9_l3))
        self.wait(2)
        self.play(Write(b9_l4))
        self.play(Create(SurroundingRectangle(b9_l4, color=GREEN)))
        self.wait(2.5)
        b9_l5 = MathTex(r"\text{Freezer box: } 1{,}2 \times 0{,}8 \times 0{,}9 = 864 \ell").scale(1.0).shift(band_shift(9) + DOWN * 2.6)
        self.play(Write(b9_l5))
        self.wait(3)

        # --- Band 10 (subtopic_7): covering the outside
        self.next_band(10)
        b10_t = Tex("Peel the label, list the faces").scale(1.15).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_t))
        self.wait(1.5)
        b10_l1 = MathTex(r"\text{Peeled wall: } 5{,}66 \times 1{,}8 \approx 10{,}18 \text{ m}^2").scale(1.05).shift(band_shift(10) + UP * 1.1)
        b10_l2 = MathTex(r"\text{Lid circle: } 3{,}142 \times 0{,}81 \approx 2{,}55 \text{ m}^2").scale(1.05).shift(band_shift(10) + UP * 0.2)
        b10_l3 = MathTex(r"\text{To paint: } 10{,}18 + 2{,}55 = 12{,}73 \text{ m}^2").scale(1.05).shift(band_shift(10) + DOWN * 0.8)
        self.play(Write(b10_l1))
        self.wait(2.5)
        self.play(Write(b10_l2))
        self.wait(2)
        self.play(Write(b10_l3))
        self.wait(2.5)
        b10_l4 = MathTex(r"12{,}73 \div 9 = 1{,}41 \;\Rightarrow\; \text{buy 2 litres}").scale(1.05).shift(band_shift(10) + DOWN * 1.8)
        self.play(Write(b10_l4))
        self.play(Create(SurroundingRectangle(b10_l4, color=GREEN)))
        self.wait(2.5)
        b10_l5 = Tex("Shopping always rounds up; no bottom, no lidless").scale(1.0).shift(band_shift(10) + DOWN * 2.8)
        self.play(Write(b10_l5))
        self.wait(4)
