from manim import *

# Band-layout whiteboard scene for the Finance and Data Essentials revision
# session. One band per teaching beat; the camera moves down and earlier work
# stays on the canvas. Exporter-supported mobjects only; every working line
# is its own single-string Tex/MathTex revealed with Write. No transforms,
# no FadeOut.
#
# Subtopic time shares (subtopics.json, total 1135 s):
# 235/175/170/155/130/130/140 -> bands 0-1 / 2-4 / 5-6 / 7 / 8 / 9 / 10.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class FinanceDataEssentialsSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic full-screen while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): the rising block tariff
        title = Tex("Finance and Data Essentials").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex("Block tariff: 420 units never pay one rate").scale(1.05).shift(UP * 1.2)
        b0_l2 = MathTex(r"\text{First 350: } 350 \times 2{,}00 = \text{R}700{,}00").scale(1.05).shift(UP * 0.3)
        b0_l3 = MathTex(r"\text{Next 70: } 70 \times 2{,}50 = \text{R}175{,}00").scale(1.05).shift(DOWN * 0.6)
        b0_l4 = MathTex(r"\text{Subtotal R}875{,}00; \;\; \times 1{,}15 = \text{R}1\;006{,}25").scale(1.05).shift(DOWN * 1.5)
        self.play(Write(b0_l1))
        self.wait(2)
        self.play(Write(b0_l2))
        self.wait(2)
        self.play(Write(b0_l3))
        self.wait(2)
        self.play(Write(b0_l4))
        self.play(Create(SurroundingRectangle(b0_l4, color=GREEN)))
        self.wait(2.5)
        b0_l5 = MathTex(r"420 \times 2{,}50 \text{ — all at the top rate}").scale(1.0).shift(DOWN * 2.6)
        self.play(Write(b0_l5))
        self.play(Create(strike(b0_l5)))
        self.wait(3)

        # --- Band 1 (subtopic_1): simple vs compound, and inflation
        self.next_band(1)
        b1_t = Tex("Simple stands still; compound snowballs").scale(1.1).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_t))
        self.wait(1.5)
        b1_l1 = MathTex(r"\text{Simple: } 5\;000 \times 0{,}06 = \text{R}300 \text{ each year}").scale(1.0).shift(band_shift(1) + UP * 1.2)
        b1_l2 = MathTex(r"3 \times 300 = \text{R}900 \;\Rightarrow\; \text{R}5\;900{,}00").scale(1.0).shift(band_shift(1) + UP * 0.3)
        b1_l3 = MathTex(r"\text{Compound: } 5\;000 \times 1{,}06^3 = \text{R}5\;955{,}08").scale(1.0).shift(band_shift(1) + DOWN * 0.6)
        b1_l4 = MathTex(r"\text{Gap R}55{,}08 = \text{interest earned on interest}").scale(1.0).shift(band_shift(1) + DOWN * 1.5)
        self.play(Write(b1_l1))
        self.wait(2)
        self.play(Write(b1_l2))
        self.wait(2)
        self.play(Write(b1_l3))
        self.wait(2)
        self.play(Write(b1_l4))
        self.play(Create(SurroundingRectangle(b1_l4, color=GREEN)))
        self.wait(2.5)
        b1_l5 = MathTex(r"\text{Inflation: } 120 \times 1{,}05^2 = \text{R}132{,}30 \text{ (not 132)}").scale(0.96).shift(band_shift(1) + DOWN * 2.6)
        self.play(Write(b1_l5))
        self.wait(3)

        # --- Band 2 (subtopic_2): VAT, both directions
        self.next_band(2)
        b2_t = Tex("VAT runs both directions").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(1.5)
        b2_l1 = MathTex(r"\text{Forward: } 250 \times 0{,}15 = \text{R}37{,}50 \Rightarrow \text{R}287{,}50").scale(0.85).shift(band_shift(2) + UP * 1.1)
        self.play(Write(b2_l1))
        self.wait(2.5)
        b2_l2 = MathTex(r"\text{Backward: } 287{,}50 \div 1{,}15 = \text{R}250{,}00").scale(1.05).shift(band_shift(2) + UP * 0.1)
        self.play(Write(b2_l2))
        self.play(Create(SurroundingRectangle(b2_l2, color=GREEN)))
        self.wait(2.5)
        b2_l3 = MathTex(r"287{,}50 \times 0{,}15 \text{ then subtract}").scale(1.0).shift(band_shift(2) + DOWN * 0.9)
        self.play(Write(b2_l3))
        self.play(Create(strike(b2_l3)))
        self.wait(2)
        b2_l4 = Tex("The 15\\% was charged on the SMALLER amount —").scale(1.0).shift(band_shift(2) + DOWN * 1.9)
        b2_l5 = Tex("only division unwinds it").scale(1.0).shift(band_shift(2) + DOWN * 2.6)
        self.play(Write(b2_l4))
        self.play(Write(b2_l5))
        self.wait(3)

        # --- Band 3 (subtopic_2): the income tax chain
        self.next_band(3)
        b3_t = Tex("Income tax: bracket plus rebate").scale(1.15).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t))
        self.wait(1.5)
        b3_l1 = MathTex(r"310\;000 - 237\;100 = \text{R}72\;900").scale(1.0).shift(band_shift(3) + UP * 1.2)
        b3_l2 = MathTex(r"72\;900 \times 0{,}26 = \text{R}18\;954{,}00").scale(1.0).shift(band_shift(3) + UP * 0.3)
        b3_l3 = MathTex(r"18\;954 + 42\;678 = \text{R}61\;632{,}00").scale(1.0).shift(band_shift(3) + DOWN * 0.6)
        b3_l4 = MathTex(r"\text{Rebate: } 61\;632 - 17\;235 = \text{R}44\;397{,}00").scale(1.0).shift(band_shift(3) + DOWN * 1.5)
        b3_l5 = MathTex(r"\div \; 12 = \text{R}3\;699{,}75 \text{ per month}").scale(1.05).shift(band_shift(3) + DOWN * 2.5)
        self.play(Write(b3_l1))
        self.wait(2)
        self.play(Write(b3_l2))
        self.wait(2)
        self.play(Write(b3_l3))
        self.wait(2)
        self.play(Write(b3_l4))
        self.wait(2)
        self.play(Write(b3_l5))
        self.play(Create(SurroundingRectangle(b3_l5, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_2): exchange rates with the fee
        self.next_band(4)
        b4_t = Tex("Exchange rates: check the direction first").scale(1.1).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(1.5)
        b4_l1 = MathTex(r"\text{R}18{,}50 \text{ per dollar: } 120 \times 18{,}50 = \text{R}2\;220{,}00").scale(0.96).shift(band_shift(4) + UP * 1.1)
        b4_l2 = MathTex(r"\text{2\% fee: } 2\;220 \times 1{,}02 = \text{R}2\;264{,}40").scale(1.05).shift(band_shift(4) + UP * 0.1)
        self.play(Write(b4_l1))
        self.wait(2.5)
        self.play(Write(b4_l2))
        self.play(Create(SurroundingRectangle(b4_l2, color=GREEN)))
        self.wait(2.5)
        b4_l3 = Tex("Dollars to rands multiply; rands to dollars divide").scale(1.0).shift(band_shift(4) + DOWN * 0.9)
        self.play(Write(b4_l3))
        self.wait(3)

        # --- Band 5 (subtopic_3): mean, median, range on eleven marks
        self.next_band(5)
        b5_t = Tex("Eleven marks, three honest summaries").scale(1.1).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_t))
        self.wait(1.5)
        b5_l1 = MathTex(r"34, 41, 45, 52, 55, 58, 61, 66, 72, 78, 85").scale(0.95).shift(band_shift(5) + UP * 1.2)
        b5_l2 = MathTex(r"\text{Mean: } 647 \div 11 = 58{,}8").scale(1.05).shift(band_shift(5) + UP * 0.3)
        b5_l3 = MathTex(r"\text{Median: position } \tfrac{11+1}{2} = 6 \;\Rightarrow\; 58").scale(0.99).shift(band_shift(5) + DOWN * 0.7)
        b5_l4 = MathTex(r"\text{Range: } 85 - 34 = 51").scale(1.05).shift(band_shift(5) + DOWN * 1.7)
        self.play(Write(b5_l1))
        self.wait(2.5)
        self.play(Write(b5_l2))
        self.wait(2)
        self.play(Write(b5_l3))
        self.wait(2.5)
        self.play(Write(b5_l4))
        self.play(Create(SurroundingRectangle(b5_l4, color=GREEN)))
        self.wait(3)

        # --- Band 6 (subtopic_3): quartiles and the honest average
        self.next_band(6)
        b6_t = Tex("Quartiles cut the queue into quarters").scale(1.1).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_t))
        self.wait(1.5)
        b6_l1 = MathTex(r"Q_1 = 45 \text{ (position 3)}; \quad Q_3 = 72 \text{ (position 9)}").scale(0.95).shift(band_shift(6) + UP * 1.1)
        b6_l2 = MathTex(r"IQR = 72 - 45 = 27").scale(1.1).shift(band_shift(6) + UP * 0.1)
        self.play(Write(b6_l1))
        self.wait(2.5)
        self.play(Write(b6_l2))
        self.play(Create(SurroundingRectangle(b6_l2, color=GREEN)))
        self.wait(2.5)
        b6_l3 = Tex("Outliers drag the mean; the median holds still —").scale(1.0).shift(band_shift(6) + DOWN * 0.9)
        b6_l4 = Tex("say WHY, not just which").scale(1.05).shift(band_shift(6) + DOWN * 1.6)
        b6_l5 = Tex("75th percentile: heavier than 75 of 100 peers").scale(1.0).shift(band_shift(6) + DOWN * 2.6)
        self.play(Write(b6_l3))
        self.play(Write(b6_l4))
        self.wait(2.5)
        self.play(Write(b6_l5))
        self.wait(3)

        # --- Band 7 (subtopic_4): choosing graphs and catching lies
        self.next_band(7)
        b7_t = Tex("Choose the graph; catch the lie").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(1.5)
        b7_l1 = Tex("Bar: categories; pie: shares; line: time;").scale(1.0).shift(band_shift(7) + UP * 1.2)
        b7_l2 = Tex("histogram: grouped; box plot: five numbers").scale(1.0).shift(band_shift(7) + UP * 0.5)
        self.play(Write(b7_l1))
        self.play(Write(b7_l2))
        self.wait(2.5)
        b7_l3 = Tex("Same median 58, narrower box: A is more").scale(1.0).shift(band_shift(7) + DOWN * 0.4)
        b7_l4 = Tex("consistent — the comparison needs BOTH halves").scale(1.0).shift(band_shift(7) + DOWN * 1.1)
        self.play(Write(b7_l3))
        self.play(Write(b7_l4))
        self.wait(2.5)
        b7_l5 = Tex("Traps: axis starting at 45; tilted 3-D pie;").scale(1.0).shift(band_shift(7) + DOWN * 2.0)
        b7_l6 = Tex("biased sample. Critique: flaw, impression, fix").scale(1.0).shift(band_shift(7) + DOWN * 2.7)
        self.play(Write(b7_l5))
        self.wait(2)
        self.play(Write(b7_l6))
        self.play(Create(SurroundingRectangle(b7_l6, color=GREEN)))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): the tuck shop till
        self.next_band(8)
        b8_t = Tex("The tuck shop till").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_t))
        self.wait(1.5)
        b8_l1 = MathTex(r"\text{Buy R}6{,}50, \text{ sell R}10{,}00: \text{ profit R}3{,}50").scale(1.0).shift(band_shift(8) + UP * 1.1)
        b8_l2 = MathTex(r"\text{Mark-up: } \tfrac{3{,}50}{6{,}50} \times 100 = 53{,}8\%").scale(1.05).shift(band_shift(8) + UP * 0.1)
        self.play(Write(b8_l1))
        self.wait(2.5)
        self.play(Write(b8_l2))
        self.play(Create(SurroundingRectangle(b8_l2, color=GREEN)))
        self.wait(2.5)
        b8_l3 = Tex("Not 35\\% — the base is what SHE paid").scale(1.05).shift(band_shift(8) + DOWN * 0.9)
        b8_l4 = MathTex(r"\text{Excluding: } 250 \times 1{,}15 = \text{R}287{,}50").scale(1.0).shift(band_shift(8) + DOWN * 1.8)
        b8_l5 = MathTex(r"\text{Total shown: } 287{,}50 \div 1{,}15 = \text{R}250{,}00").scale(1.0).shift(band_shift(8) + DOWN * 2.7)
        self.play(Write(b8_l3))
        self.wait(2)
        self.play(Write(b8_l4))
        self.wait(2)
        self.play(Write(b8_l5))
        self.wait(3)

        # --- Band 9 (subtopic_6): stokvel rands and bank interest
        self.next_band(9)
        b9_t = Tex("Stokvel rands and bank interest").scale(1.15).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(1.5)
        b9_l1 = MathTex(r"\text{Stokvel: } 12 \times 200 = \text{R}2\;400 \text{ — safe, no growth}").scale(0.91).shift(band_shift(9) + UP * 1.1)
        b9_l2 = MathTex(r"\text{Simple 6\%: } \text{R}300 + \text{R}300 \Rightarrow \text{R}5\;600{,}00").scale(0.82).shift(band_shift(9) + UP * 0.2)
        b9_l3 = MathTex(r"\text{Compound: } 5\;000 \rightarrow 5\;300 \rightarrow \text{R}5\;618{,}00").scale(1.0).shift(band_shift(9) + DOWN * 0.8)
        self.play(Write(b9_l1))
        self.wait(2.5)
        self.play(Write(b9_l2))
        self.wait(2.5)
        self.play(Write(b9_l3))
        self.play(Create(SurroundingRectangle(b9_l3, color=GREEN)))
        self.wait(2.5)
        b9_l4 = Tex("The extra R18 is year two's interest on interest").scale(1.0).shift(band_shift(9) + DOWN * 1.8)
        b9_l5 = MathTex(r"\text{Inflation runs against her: } 120 \rightarrow \text{R}132{,}30").scale(1.0).shift(band_shift(9) + DOWN * 2.7)
        self.play(Write(b9_l4))
        self.wait(2)
        self.play(Write(b9_l5))
        self.wait(3)

        # --- Band 10 (subtopic_7): marks on the fridge door
        self.next_band(10)
        b10_t = Tex("Marks on the fridge door").scale(1.2).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_t))
        self.wait(1.5)
        b10_l1 = MathTex(r"24, 58, 62, 65, 71: \;\text{mean } 280 \div 5 = 56{,}0").scale(1.0).shift(band_shift(10) + UP * 1.1)
        b10_l2 = MathTex(r"\text{Median: third of five} = 62").scale(1.05).shift(band_shift(10) + UP * 0.2)
        self.play(Write(b10_l1))
        self.wait(2.5)
        self.play(Write(b10_l2))
        self.wait(2)
        b10_l3 = MathTex(r"\text{Drop the flu 24: mean of the rest} = 64{,}0").scale(1.0).shift(band_shift(10) + DOWN * 0.8)
        b10_l4 = Tex("One outlier pulled the mean eight points;").scale(1.0).shift(band_shift(10) + DOWN * 1.7)
        b10_l5 = Tex("the median never flinched").scale(1.0).shift(band_shift(10) + DOWN * 2.4)
        self.play(Write(b10_l3))
        self.wait(2.5)
        self.play(Write(b10_l4))
        self.play(Write(b10_l5))
        self.play(Create(SurroundingRectangle(b10_l5, color=GREEN)))
        self.wait(2.5)
        b10_l6 = Tex("Poster axis starts at R45 000: thumb test it").scale(1.0).shift(band_shift(10) + DOWN * 3.1)
        self.play(Write(b10_l6))
        self.wait(4)
