# Copyright (c) 2026 RokctAI
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from manim import *

# Band-layout whiteboard scene for the session duo "Manufacturing Costs and
# Ledger Accounts" (grade 11, term 3, cost accounting). One band per teaching
# beat; the camera moves down to fresh space and nothing is ever removed.
# Part 1 (Expert) covers subtopics 1-4, Part 2 (Simplifier) re-teaches as
# subtopics 5-7 in fresh bands. Exporter-safe primitives only
# (Tex/MathTex/Line/Arrow/Dot/Circle/Rectangle/SurroundingRectangle/VGroup);
# write-only reveals, no Transform/FadeOut. Subtopic durations
# 225/230/245/225/195/195/200 of 1515 s guide the time apportioning.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class ManufacturingCostsSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md plays.
        self.wait(14)

        # ===== Part 1 — Expert =====
        # --- Band 0 (subtopic_1): sorting costs by traceability ---
        title = Tex("Manufacturing Costs and Ledger Accounts").scale(1.2).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex("Sort every cost twice:").scale(1.1).shift(UP * 1.3)
        b0_l2 = Tex("by traceability and by behaviour").scale(1.1).shift(UP * 0.6)
        self.play(Write(b0_l1))
        self.play(Write(b0_l2))
        self.wait(2)
        b0_l3 = Tex(r"Direct materials $+$ Direct labour").scale(1.1).shift(DOWN * 0.4)
        b0_l4 = Tex(r"$=$ PRIME COST").scale(1.15).shift(DOWN * 1.2)
        self.play(Write(b0_l3))
        self.wait(2)
        self.play(Write(b0_l4))
        self.play(Create(SurroundingRectangle(b0_l4, color=GREEN)))
        self.wait(2)
        b0_l5 = Tex(r"$+$ Factory overheads (indirect)").scale(1.1).shift(DOWN * 2.1)
        b0_l6 = Tex(r"$=$ Total cost of production").scale(1.1).shift(DOWN * 2.9)
        self.play(Write(b0_l5))
        self.wait(2)
        self.play(Write(b0_l6))
        self.wait(3)

        # --- Band 1 (subtopic_1): period costs and cost behaviour ---
        self.next_band(1)
        b1_t = Tex("Period costs stay OUT of production").scale(1.15).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_t))
        self.wait(2)
        b1_l1 = Tex("Administration: office, bookkeeper").scale(1.05).shift(band_shift(1) + UP * 1.2)
        b1_l2 = Tex("Selling: advertising, delivery diesel").scale(1.05).shift(band_shift(1) + UP * 0.4)
        self.play(Write(b1_l1))
        self.wait(2)
        self.play(Write(b1_l2))
        self.wait(2)
        b1_l3 = Tex("Behaviour: VARIABLE moves with output").scale(1.05).shift(band_shift(1) + DOWN * 0.6)
        b1_l4 = Tex("FIXED ignores output: rent, foreman").scale(1.05).shift(band_shift(1) + DOWN * 1.4)
        self.play(Write(b1_l3))
        self.wait(2)
        self.play(Write(b1_l4))
        self.wait(2)
        b1_trap = Tex("Sales commission $=$ production cost?").scale(1.0).shift(band_shift(1) + DOWN * 2.3)
        self.play(Write(b1_trap))
        self.play(Create(strike(b1_trap)))
        b1_fix = Tex("Variable, but a SELLING cost").scale(1.05).shift(band_shift(1) + DOWN * 3.0)
        self.play(Write(b1_fix))
        self.wait(3)

        # --- Band 2 (subtopic_2): three stock accounts, drawn as a table ---
        self.next_band(2)
        b2_t = Tex("Three stock accounts, not one").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(2)
        grid = Rectangle(width=11.0, height=3.0).shift(band_shift(2) + UP * 0.2)
        v1 = Line(grid.get_top() + LEFT * 1.85, grid.get_bottom() + LEFT * 1.85)
        v2 = Line(grid.get_top() + RIGHT * 1.85, grid.get_bottom() + RIGHT * 1.85)
        h1 = Line(grid.get_left() + UP * 0.5, grid.get_right() + UP * 0.5)
        self.play(Create(grid), Create(v1), Create(v2), Create(h1))
        c1 = Tex("Raw materials").scale(0.95).shift(band_shift(2) + UP * 1.2 + LEFT * 3.7)
        c2 = Tex("Work-in-progress").scale(0.95).shift(band_shift(2) + UP * 1.2)
        c3 = Tex("Finished goods").scale(0.95).shift(band_shift(2) + UP * 1.2 + RIGHT * 3.7)
        self.play(Write(c1), Write(c2), Write(c3))
        self.wait(2)
        d1 = Tex("leather, soles,\\\\thread").scale(0.8).shift(band_shift(2) + UP * 0.0 + LEFT * 3.7)
        d2 = Tex("half-made pairs,\\\\value mid-process").scale(0.8).shift(band_shift(2) + UP * 0.0)
        d3 = Tex("completed pairs\\\\awaiting sale").scale(0.8).shift(band_shift(2) + UP * 0.0 + RIGHT * 3.7)
        self.play(Write(d1))
        self.play(Write(d2))
        self.play(Write(d3))
        self.wait(2)
        b2_l1 = Tex("Plus consumable stores: oil, needles").scale(1.0).shift(band_shift(2) + DOWN * 1.8)
        b2_l2 = Tex("used up, flow to overheads").scale(1.0).shift(band_shift(2) + DOWN * 2.5)
        self.play(Write(b2_l1))
        self.play(Write(b2_l2))
        self.wait(3)

        # --- Band 3 (subtopic_2): raw materials issued — the first key figure ---
        self.next_band(3)
        b3_t = Tex("Raw materials: what was ISSUED?").scale(1.15).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t))
        self.wait(2)
        b3_l1 = Tex("Opening balance \\quad R84 000").scale(1.05).shift(band_shift(3) + UP * 1.2)
        b3_l2 = Tex("$+$ Purchases \\quad R516 000").scale(1.05).shift(band_shift(3) + UP * 0.4)
        b3_l3 = Tex("$+$ Carriage on purchases \\quad R14 000").scale(1.05).shift(band_shift(3) + DOWN * 0.4)
        b3_l4 = Tex("$=$ Available \\quad R614 000").scale(1.05).shift(band_shift(3) + DOWN * 1.2)
        b3_l5 = Tex("$-$ Closing stock \\quad R76 000").scale(1.05).shift(band_shift(3) + DOWN * 2.0)
        b3_l6 = Tex("Issued to production: R538 000").scale(1.1).shift(band_shift(3) + DOWN * 2.9)
        self.play(Write(b3_l1))
        self.wait(1.5)
        self.play(Write(b3_l2))
        self.wait(1.5)
        self.play(Write(b3_l3))
        self.wait(1.5)
        self.play(Write(b3_l4))
        self.wait(1.5)
        self.play(Write(b3_l5))
        self.wait(1.5)
        self.play(Write(b3_l6))
        self.play(Create(SurroundingRectangle(b3_l6, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): cost accounts carry prime cost ---
        self.next_band(4)
        b4_t = Tex("The cost accounts fill up").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(2)
        b4_l1 = Tex("Direct materials cost \\quad R538 000").scale(1.05).shift(band_shift(4) + UP * 1.1)
        self.play(Write(b4_l1))
        self.wait(2)
        b4_l2 = Tex("Direct labour: wages R376 000").scale(1.05).shift(band_shift(4) + UP * 0.3)
        b4_l3 = Tex("$+$ employer contributions R26 000").scale(1.05).shift(band_shift(4) + DOWN * 0.5)
        b4_l4 = Tex("Direct labour cost \\quad R402 000").scale(1.05).shift(band_shift(4) + DOWN * 1.3)
        self.play(Write(b4_l2))
        self.wait(1.5)
        self.play(Write(b4_l3))
        self.wait(1.5)
        self.play(Write(b4_l4))
        self.wait(2)
        b4_l5 = Tex("Prime cost: R538 000 $+$ R402 000").scale(1.05).shift(band_shift(4) + DOWN * 2.2)
        b4_l6 = Tex("$=$ R940 000").scale(1.1).shift(band_shift(4) + DOWN * 3.0)
        self.play(Write(b4_l5))
        self.wait(1.5)
        self.play(Write(b4_l6))
        self.play(Create(SurroundingRectangle(b4_l6, color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_3): factory overheads, each named ---
        self.next_band(5)
        b5_t = Tex("Factory overhead cost account").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_t))
        self.wait(2)
        b5_l1 = Tex("Indirect materials \\quad R38 000").scale(1.0).shift(band_shift(5) + UP * 1.3)
        b5_l2 = Tex("Foreman's salary \\quad R132 000").scale(1.0).shift(band_shift(5) + UP * 0.6)
        b5_l3 = Tex("Factory rent \\quad R96 000").scale(1.0).shift(band_shift(5) + DOWN * 0.1)
        b5_l4 = Tex("Electricity and water \\quad R54 000").scale(1.0).shift(band_shift(5) + DOWN * 0.8)
        b5_l5 = Tex("Depreciation R60 000; insurance R20 000").scale(1.0).shift(band_shift(5) + DOWN * 1.5)
        self.play(Write(b5_l1))
        self.wait(1.2)
        self.play(Write(b5_l2))
        self.wait(1.2)
        self.play(Write(b5_l3))
        self.wait(1.2)
        self.play(Write(b5_l4))
        self.wait(1.2)
        self.play(Write(b5_l5))
        self.wait(1.5)
        b5_l6 = Tex("Total factory overheads: R400 000").scale(1.1).shift(band_shift(5) + DOWN * 2.5)
        self.play(Write(b5_l6))
        self.play(Create(SurroundingRectangle(b5_l6, color=GREEN)))
        self.wait(3)

        # --- Band 6 (subtopic_3): work-in-progress T-account ---
        self.next_band(6)
        b6_t = Tex("Work-in-progress").scale(1.15).shift(band_shift(6) + UP * 2.4)
        self.play(Write(b6_t))
        rail_h = Line(LEFT * 5.2, RIGHT * 5.2).shift(band_shift(6) + UP * 1.9)
        rail_v = Line(UP * 1.9, DOWN * 1.6).shift(band_shift(6))
        self.play(Create(rail_h), Create(rail_v))
        self.wait(2)
        b6_d1 = Tex("Balance b/d \\quad R46 000").scale(0.9).shift(band_shift(6) + UP * 1.3 + LEFT * 2.9)
        b6_d2 = Tex("Prime cost \\quad R940 000").scale(0.9).shift(band_shift(6) + UP * 0.6 + LEFT * 2.9)
        b6_d3 = Tex("Overheads \\quad R400 000").scale(0.9).shift(band_shift(6) + DOWN * 0.1 + LEFT * 2.9)
        self.play(Write(b6_d1))
        self.wait(1.5)
        self.play(Write(b6_d2))
        self.wait(1.5)
        self.play(Write(b6_d3))
        self.wait(2)
        b6_c1 = Tex("Finished goods \\quad R1 320 000").scale(0.9).shift(band_shift(6) + UP * 1.3 + RIGHT * 2.9)
        b6_c2 = Tex("Balance c/d \\quad R66 000").scale(0.9).shift(band_shift(6) + UP * 0.6 + RIGHT * 2.9)
        self.play(Write(b6_c1))
        self.wait(1.5)
        self.play(Write(b6_c2))
        self.wait(1.5)
        tot_l = Tex("R1 386 000").scale(0.9).shift(band_shift(6) + DOWN * 1.1 + LEFT * 2.9)
        tot_r = Tex("R1 386 000").scale(0.9).shift(band_shift(6) + DOWN * 1.1 + RIGHT * 2.9)
        tline_l = Line(LEFT * 4.6, LEFT * 1.2).shift(band_shift(6) + DOWN * 0.7)
        tline_r = Line(RIGHT * 1.2, RIGHT * 4.6).shift(band_shift(6) + DOWN * 0.7)
        self.play(Create(tline_l), Create(tline_r))
        self.play(Write(tot_l), Write(tot_r))
        self.wait(2)
        b6_l1 = Tex("Cost of production R1 320 000;").scale(1.0).shift(band_shift(6) + DOWN * 2.2)
        b6_l2 = Tex("24 000 pairs $\\Rightarrow$ R55 per pair").scale(1.05).shift(band_shift(6) + DOWN * 3.0)
        self.play(Write(b6_l1))
        self.wait(1.5)
        self.play(Write(b6_l2))
        self.play(Create(SurroundingRectangle(b6_l2, color=GREEN)))
        self.wait(3)

        # --- Band 7 (subtopic_3): finished goods to gross profit ---
        self.next_band(7)
        b7_t = Tex("Finished goods close the chain").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(2)
        b7_l1 = Tex("Opening R90 000 $+$ R1 320 000").scale(1.05).shift(band_shift(7) + UP * 1.2)
        b7_l2 = Tex("$=$ Available R1 410 000").scale(1.05).shift(band_shift(7) + UP * 0.4)
        b7_l3 = Tex("$-$ Closing R110 000").scale(1.05).shift(band_shift(7) + DOWN * 0.4)
        b7_l4 = Tex("Cost of sales R1 300 000").scale(1.05).shift(band_shift(7) + DOWN * 1.2)
        self.play(Write(b7_l1))
        self.wait(1.5)
        self.play(Write(b7_l2))
        self.wait(1.5)
        self.play(Write(b7_l3))
        self.wait(1.5)
        self.play(Write(b7_l4))
        self.wait(2)
        b7_l5 = Tex("Sales R1 950 000 $-$ R1 300 000").scale(1.05).shift(band_shift(7) + DOWN * 2.1)
        b7_l6 = Tex("Gross profit R650 000 (50\\% on cost)").scale(1.05).shift(band_shift(7) + DOWN * 2.9)
        self.play(Write(b7_l5))
        self.wait(1.5)
        self.play(Write(b7_l6))
        self.play(Create(SurroundingRectangle(b7_l6, color=GREEN)))
        self.wait(3)

        # --- Band 8 (subtopic_4): ethics and internal control ---
        self.next_band(8)
        b8_t = Tex("Controls follow the flow").scale(1.15).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_t))
        self.wait(2)
        b8_l1 = Tex("Materials: lock the store,").scale(1.0).shift(band_shift(8) + UP * 1.2)
        b8_l2 = Tex("issue only against signed requisitions").scale(1.0).shift(band_shift(8) + UP * 0.5)
        self.play(Write(b8_l1))
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = Tex("Labour: clock cards; overtime").scale(1.0).shift(band_shift(8) + DOWN * 0.4)
        b8_l4 = Tex("approved BEFORE it happens").scale(1.0).shift(band_shift(8) + DOWN * 1.1)
        self.play(Write(b8_l3))
        self.play(Write(b8_l4))
        self.wait(2.5)
        b8_l5 = Tex("Overheads: budgets compared monthly").scale(1.0).shift(band_shift(8) + DOWN * 2.0)
        self.play(Write(b8_l5))
        self.wait(2.5)
        b8_l6 = Tex("Ethics: dumped waste is a cost SHIFTED,").scale(1.0).shift(band_shift(8) + DOWN * 2.8)
        b8_l7 = Tex("not saved — honest costing tells the truth").scale(1.0).shift(band_shift(8) + DOWN * 3.5)
        self.play(Write(b8_l6))
        self.play(Write(b8_l7))
        self.wait(3.5)

        # ===== Part 2 — Simplifier =====
        # --- Band 9 (subtopic_5): the vetkoek stand sorts its costs ---
        self.next_band(9)
        b9_t = Tex("The vetkoek stand: sort the costs").scale(1.15).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(2)
        b9_l1 = Tex("Flour, oil, mince: DIRECT materials").scale(1.05).shift(band_shift(9) + UP * 1.2)
        b9_l2 = Tex("Cousin frying for a fee: DIRECT labour").scale(1.05).shift(band_shift(9) + UP * 0.4)
        b9_l3 = Tex("Together: PRIME COST").scale(1.05).shift(band_shift(9) + DOWN * 0.4)
        self.play(Write(b9_l1))
        self.wait(2)
        self.play(Write(b9_l2))
        self.wait(2)
        self.play(Write(b9_l3))
        self.wait(2)
        b9_l4 = Tex("Gas, gazebo hire, fryer wear: OVERHEADS").scale(1.0).shift(band_shift(9) + DOWN * 1.3)
        self.play(Write(b9_l4))
        self.wait(2)
        b9_trap = Tex("Flyers inside the vetkoek cost?").scale(1.0).shift(band_shift(9) + DOWN * 2.1)
        self.play(Write(b9_trap))
        self.play(Create(strike(b9_trap)))
        b9_fix = Tex("Selling cost — cost of the DAY").scale(1.0).shift(band_shift(9) + DOWN * 2.9)
        self.play(Write(b9_fix))
        self.wait(3)

        # --- Band 10 (subtopic_6): three tables, and the used figure ---
        self.next_band(10)
        b10_t = Tex("Sacks, half-done, warmer").scale(1.15).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_t))
        self.wait(2)
        b10_l1 = Tex("Was there $+$ arrived $-$ still there").scale(1.05).shift(band_shift(10) + UP * 1.2)
        b10_l2 = Tex("$=$ what moved on").scale(1.05).shift(band_shift(10) + UP * 0.4)
        self.play(Write(b10_l1))
        self.play(Write(b10_l2))
        self.wait(2.5)
        b10_l3 = Tex("R84 000 $+$ R516 000 $+$ R14 000").scale(1.05).shift(band_shift(10) + DOWN * 0.5)
        b10_l4 = Tex("$-$ R76 000 $=$ R538 000 USED").scale(1.05).shift(band_shift(10) + DOWN * 1.3)
        self.play(Write(b10_l3))
        self.wait(2)
        self.play(Write(b10_l4))
        self.play(Create(SurroundingRectangle(b10_l4, color=GREEN)))
        self.wait(2)
        b10_trap = Tex("Purchases $=$ materials cost?").scale(1.0).shift(band_shift(10) + DOWN * 2.2)
        self.play(Write(b10_trap))
        self.play(Create(strike(b10_trap)))
        b10_fix = Tex("Only the ISSUED materials count").scale(1.0).shift(band_shift(10) + DOWN * 3.0)
        self.play(Write(b10_fix))
        self.wait(3)

        # --- Band 11 (subtopic_7): one rand walks the whole path ---
        self.next_band(11)
        b11_t = Tex("One pair, followed all the way").scale(1.15).shift(band_shift(11) + UP * 2.2)
        self.play(Write(b11_t))
        self.wait(2)
        b11_l1 = Tex("Materials R538 000 $+$ labour R402 000").scale(1.0).shift(band_shift(11) + UP * 1.2)
        b11_l2 = Tex("$=$ prime cost R940 000").scale(1.05).shift(band_shift(11) + UP * 0.4)
        b11_l3 = Tex("$+$ overheads R400 000 $=$ R1 340 000").scale(1.0).shift(band_shift(11) + DOWN * 0.4)
        self.play(Write(b11_l1))
        self.wait(2)
        self.play(Write(b11_l2))
        self.wait(2)
        self.play(Write(b11_l3))
        self.wait(2)
        b11_l4 = Tex("R46 000 $+$ R1 340 000 $-$ R66 000").scale(1.0).shift(band_shift(11) + DOWN * 1.3)
        b11_l5 = Tex("$=$ R1 320 000 finished").scale(1.05).shift(band_shift(11) + DOWN * 2.1)
        self.play(Write(b11_l4))
        self.wait(2)
        self.play(Write(b11_l5))
        self.wait(2)
        b11_l6 = Tex("R1 320 000 $\\div$ 24 000 $=$ R55 a pair").scale(1.05).shift(band_shift(11) + DOWN * 3.0)
        self.play(Write(b11_l6))
        self.play(Create(SurroundingRectangle(b11_l6, color=GREEN)))
        self.wait(3)

        # --- Band 12 (subtopic_7): the store leg and the closed chain ---
        self.next_band(12)
        b12_t = Tex("Last leg: the store").scale(1.15).shift(band_shift(12) + UP * 2.2)
        self.play(Write(b12_t))
        self.wait(2)
        b12_l1 = Tex("Price at R80: R25 per pair covers").scale(1.05).shift(band_shift(12) + UP * 1.2)
        b12_l2 = Tex("office, deliveries and profit").scale(1.05).shift(band_shift(12) + UP * 0.4)
        self.play(Write(b12_l1))
        self.play(Write(b12_l2))
        self.wait(2.5)
        b12_l3 = Tex("R90 000 $+$ R1 320 000 $-$ R110 000").scale(1.0).shift(band_shift(12) + DOWN * 0.5)
        b12_l4 = Tex("$=$ cost of sales R1 300 000").scale(1.05).shift(band_shift(12) + DOWN * 1.3)
        self.play(Write(b12_l3))
        self.wait(2)
        self.play(Write(b12_l4))
        self.wait(2)
        b12_l5 = Tex("Sales R1 950 000: gross profit R650 000").scale(1.0).shift(band_shift(12) + DOWN * 2.2)
        self.play(Write(b12_l5))
        self.play(Create(SurroundingRectangle(b12_l5, color=GREEN)))
        b12_l6 = Tex("Sacks $\\rightarrow$ floor $\\rightarrow$ store $\\rightarrow$ customer").scale(1.0).shift(band_shift(12) + DOWN * 3.0)
        self.play(Write(b12_l6))
        self.wait(4)
