from manim import *

# Band-layout whiteboard scene for "Generators, Motors and Alternating Current"
# (Part 1 — Expert subtopics 1-4, Part 2 — Simplifier subtopics 5-7).
# Exporter-safe mobjects only, write-only reveals, camera moves between bands.
# Band dwell time follows subtopics.json (235/240/240/235/190/195/195 of 1530).

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


class GeneratorsMotorsACSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): induction and the generator principle
        title = Tex("Generators, Motors and AC").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex("Generator: mechanical $\\rightarrow$ electrical").scale(1.1).shift(UP * 1.2)
        self.play(Write(b0_l1))
        self.wait(2)
        b0_l2 = Tex("Electromagnetic induction:").scale(1.1).shift(UP * 0.3)
        b0_l3 = Tex("changing flux through a coil induces an emf").scale(1.05).shift(DOWN * 0.5)
        self.play(Write(b0_l2))
        self.play(Write(b0_l3))
        self.wait(2.5)
        b0_l4 = Tex("Spin the coil: flux rises and falls,").scale(1.05).shift(DOWN * 1.5)
        b0_l5 = Tex("emf reverses every half turn — AC out").scale(1.05).shift(DOWN * 2.3)
        self.play(Write(b0_l4))
        self.play(Write(b0_l5))
        self.wait(3)

        # --- Band 1 (subtopic_1): build the AC generator; rings decide AC or DC
        self.next_band(1)
        b1_title = Tex("Build the AC generator").scale(1.2).shift(band_shift(1) + UP * 2.9)
        self.play(Write(b1_title))
        self.wait(1.5)
        # magnet poles
        poleN = Rectangle(width=0.8, height=2.2).shift(band_shift(1) + LEFT * 3.0 + UP * 1.2)
        poleS = Rectangle(width=0.8, height=2.2).shift(band_shift(1) + RIGHT * 3.0 + UP * 1.2)
        labN = Tex("N").scale(1.0).shift(band_shift(1) + LEFT * 3.0 + UP * 1.2)
        labS = Tex("S").scale(1.0).shift(band_shift(1) + RIGHT * 3.0 + UP * 1.2)
        self.play(Create(poleN), Write(labN), Create(poleS), Write(labS))
        self.wait(1.5)
        # armature coil between the poles
        coil = Rectangle(width=2.6, height=1.4).shift(band_shift(1) + UP * 1.2)
        coil_lab = Tex("coil (armature)").scale(0.85).shift(band_shift(1) + UP * 2.4)
        self.play(Create(coil), Write(coil_lab))
        self.wait(1.5)
        # shaft down to two slip rings and brushes
        shaft = Line(band_shift(1) + UP * 0.5, band_shift(1) + DOWN * 0.4)
        ring1 = Circle(radius=0.22).shift(band_shift(1) + LEFT * 0.35 + DOWN * 0.75)
        ring2 = Circle(radius=0.22).shift(band_shift(1) + RIGHT * 0.35 + DOWN * 0.75)
        rings_lab = Tex("slip rings").scale(0.85).shift(band_shift(1) + LEFT * 2.4 + DOWN * 0.75)
        br1 = Rectangle(width=0.28, height=0.28).shift(band_shift(1) + LEFT * 0.35 + DOWN * 1.25)
        br2 = Rectangle(width=0.28, height=0.28).shift(band_shift(1) + RIGHT * 0.35 + DOWN * 1.25)
        br_lab = Tex("brushes").scale(0.85).shift(band_shift(1) + RIGHT * 2.3 + DOWN * 1.25)
        self.play(Create(shaft), Create(ring1), Create(ring2), Write(rings_lab))
        self.play(Create(br1), Create(br2), Write(br_lab))
        self.wait(2)
        b1_l1 = Tex("Slip rings: emf reverses each half turn — AC").scale(1.0).shift(band_shift(1) + DOWN * 2.0)
        self.play(Write(b1_l1))
        self.wait(2)
        b1_l2 = Tex("Split-ring commutator swaps on cue — DC").scale(1.0).shift(band_shift(1) + DOWN * 2.9)
        self.play(Write(b1_l2))
        self.play(Create(SurroundingRectangle(b1_l2, color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): the motor effect, forces on the coil
        self.next_band(2)
        b2_title = Tex("Motors and the motor effect").scale(1.2).shift(band_shift(2) + UP * 2.9)
        self.play(Write(b2_title))
        self.wait(1.5)
        b2_l1 = Tex("Current-carrying conductor in a field").scale(1.05).shift(band_shift(2) + UP * 2.1)
        b2_l2 = Tex("experiences a force").scale(1.05).shift(band_shift(2) + UP * 1.4)
        self.play(Write(b2_l1))
        self.play(Write(b2_l2))
        self.wait(2)
        # coil seen face-on, opposite forces on the two sides
        mcoil = Rectangle(width=3.0, height=1.2).shift(band_shift(2) + DOWN * 0.1)
        fL = Arrow(band_shift(2) + LEFT * 1.5 + DOWN * 0.1, band_shift(2) + LEFT * 1.5 + UP * 1.3, buff=0, color=YELLOW)
        fR = Arrow(band_shift(2) + RIGHT * 1.5 + DOWN * 0.1, band_shift(2) + RIGHT * 1.5 + DOWN * 1.5, buff=0, color=YELLOW)
        fL_lab = MathTex(r"F").scale(0.9).shift(band_shift(2) + LEFT * 2.0 + UP * 0.9)
        fR_lab = MathTex(r"F").scale(0.9).shift(band_shift(2) + RIGHT * 2.0 + DOWN * 1.1)
        self.play(Create(mcoil))
        self.play(Create(fL), Write(fL_lab))
        self.play(Create(fR), Write(fR_lab))
        self.wait(2)
        b2_l3 = Tex("Opposite currents, opposite forces: it turns").scale(1.0).shift(band_shift(2) + DOWN * 2.1)
        self.play(Write(b2_l3))
        self.wait(2)
        b2_l4 = Tex("Commutator flips current each half turn").scale(1.0).shift(band_shift(2) + DOWN * 2.9)
        self.play(Write(b2_l4))
        self.wait(3)

        # --- Band 3 (subtopic_2): one device, two energy directions
        self.next_band(3)
        b3_title = Tex("Same device, opposite directions").scale(1.2).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(1.5)
        b3_l1 = Tex("Turn the coil by hand $\\rightarrow$ electricity out").scale(1.05).shift(band_shift(3) + UP * 1.1)
        b3_l2 = Tex("GENERATOR").scale(1.1).shift(band_shift(3) + UP * 0.3)
        self.play(Write(b3_l1))
        self.play(Write(b3_l2))
        self.wait(2)
        b3_l3 = Tex("Feed electrical energy in $\\rightarrow$ rotation out").scale(1.05).shift(band_shift(3) + DOWN * 0.7)
        b3_l4 = Tex("MOTOR").scale(1.1).shift(band_shift(3) + DOWN * 1.5)
        self.play(Write(b3_l3))
        self.play(Write(b3_l4))
        self.play(Create(SurroundingRectangle(VGroup(b3_l1, b3_l2, b3_l3, b3_l4), color=GREEN)))
        self.wait(2.5)
        b3_l5 = Tex("Fans, drills, pumps, EVs: coils in fields").scale(1.0).shift(band_shift(3) + DOWN * 2.7)
        self.play(Write(b3_l5))
        self.wait(3)

        # --- Band 4 (subtopic_3): why the grid chose AC
        self.next_band(4)
        b4_title = Tex("Why the grid chose AC").scale(1.2).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(1.5)
        b4_l1 = Tex("Transformers change AC voltage easily").scale(1.05).shift(band_shift(4) + UP * 1.2)
        self.play(Write(b4_l1))
        self.wait(2)
        b4_l2 = MathTex(r"P_{loss} = I^2R").scale(1.25).shift(band_shift(4) + UP * 0.2)
        self.play(Write(b4_l2))
        self.play(Create(SurroundingRectangle(b4_l2, color=GREEN)))
        self.wait(2.5)
        b4_l3 = Tex("Same power at high V $\\Rightarrow$ small $I$").scale(1.05).shift(band_shift(4) + DOWN * 0.9)
        b4_l4 = Tex("small $I$ squared $=$ tiny heat loss").scale(1.05).shift(band_shift(4) + DOWN * 1.7)
        self.play(Write(b4_l3))
        self.wait(2)
        self.play(Write(b4_l4))
        self.wait(2)
        b4_l5 = Tex("Step up for the journey, down to 220 V").scale(1.05).shift(band_shift(4) + DOWN * 2.7)
        self.play(Write(b4_l5))
        self.wait(3)

        # --- Band 5 (subtopic_3): the AC wave against the DC line
        self.next_band(5)
        b5_title = Tex("The AC signal: 50 cycles per second").scale(1.15).shift(band_shift(5) + UP * 2.8)
        self.play(Write(b5_title))
        self.wait(1.5)
        ax_x = Arrow(band_shift(5) + LEFT * 4.2, band_shift(5) + RIGHT * 4.2, buff=0)
        ax_y = Arrow(band_shift(5) + LEFT * 4.0 + DOWN * 2.0, band_shift(5) + LEFT * 4.0 + UP * 2.2, buff=0)
        x_lab = Tex("t").scale(0.9).shift(band_shift(5) + RIGHT * 4.5 + DOWN * 0.4)
        y_lab = Tex("V").scale(0.9).shift(band_shift(5) + LEFT * 4.5 + UP * 1.9)
        self.play(Create(ax_x), Create(ax_y), Write(x_lab), Write(y_lab))
        self.wait(1.5)
        # one AC cycle as a 6-segment polyline
        wave = VGroup(
            Line(band_shift(5) + LEFT * 4.0, band_shift(5) + LEFT * 3.0 + UP * 1.4),
            Line(band_shift(5) + LEFT * 3.0 + UP * 1.4, band_shift(5) + LEFT * 2.0 + UP * 1.4),
            Line(band_shift(5) + LEFT * 2.0 + UP * 1.4, band_shift(5) + LEFT * 0.0),
            Line(band_shift(5) + LEFT * 0.0, band_shift(5) + RIGHT * 1.0 + DOWN * 1.4),
            Line(band_shift(5) + RIGHT * 1.0 + DOWN * 1.4, band_shift(5) + RIGHT * 2.0 + DOWN * 1.4),
            Line(band_shift(5) + RIGHT * 2.0 + DOWN * 1.4, band_shift(5) + RIGHT * 4.0),
        ).set_color(BLUE)
        self.play(Create(wave), run_time=2)
        vmax_lab = MathTex(r"+V_{max}").scale(0.9).shift(band_shift(5) + LEFT * 2.5 + UP * 2.0)
        vmin_lab = MathTex(r"-V_{max}").scale(0.9).shift(band_shift(5) + RIGHT * 1.5 + DOWN * 2.0)
        self.play(Write(vmax_lab), Write(vmin_lab))
        self.wait(2)
        dc = DashedLine(band_shift(5) + LEFT * 4.0 + UP * 0.8, band_shift(5) + RIGHT * 4.0 + UP * 0.8, color=YELLOW)
        dc_lab = Tex("DC: flat line").scale(0.9).shift(band_shift(5) + RIGHT * 2.6 + UP * 1.3)
        self.play(Create(dc), Write(dc_lab))
        self.wait(2)
        b5_l1 = Tex("Crossing zero $=$ current changing direction").scale(1.0).shift(band_shift(5) + DOWN * 2.9)
        self.play(Write(b5_l1))
        self.wait(3)

        # --- Band 6 (subtopic_4): rms — the DC-equivalent value
        self.next_band(6)
        b6_title = Tex("RMS: the honest measure of AC").scale(1.2).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(1.5)
        b6_l1 = Tex("Plain average of the wave $= 0$, yet kettles boil").scale(1.0).shift(band_shift(6) + UP * 1.4)
        self.play(Write(b6_l1))
        self.wait(2)
        b6_l2 = Tex("Heating tracks $I^2$ — positive both ways").scale(1.05).shift(band_shift(6) + UP * 0.7)
        self.play(Write(b6_l2))
        self.wait(2)
        b6_l3a = MathTex(r"I_{rms} = \frac{I_{max}}{\sqrt{2}}").scale(1.1).shift(band_shift(6) + DOWN * 0.2)
        b6_l3b = MathTex(r"V_{rms} = \frac{V_{max}}{\sqrt{2}}").scale(1.1).shift(band_shift(6) + DOWN * 1.1)
        self.play(Write(b6_l3a))
        self.wait(1.5)
        self.play(Write(b6_l3b))
        self.play(Create(SurroundingRectangle(VGroup(b6_l3a, b6_l3b), color=GREEN)))
        self.wait(2.5)
        b6_l4 = MathTex(r"V_{max} = 220 \times \sqrt{2} = 311{,}13\ \text{V}").scale(1.05).shift(band_shift(6) + DOWN * 2.1)
        self.play(Write(b6_l4))
        self.wait(2)
        b6_l5 = Tex("220 V on the wall is an rms value").scale(1.05).shift(band_shift(6) + DOWN * 3.0)
        self.play(Write(b6_l5))
        self.wait(3)

        # --- Band 7 (subtopic_4): worked example — 44 ohm heater on the mains
        self.next_band(7)
        b7_title = Tex(r"Heater: $R = 44\ \Omega$ on 220 V mains").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(2)
        b7_l1 = MathTex(r"I_{rms} = \frac{220}{44} = 5\ \text{A}").scale(1.1).shift(band_shift(7) + UP * 1.1)
        b7_l2 = MathTex(r"P_{avg} = V_{rms}I_{rms} = 220 \times 5").scale(1.1).shift(band_shift(7) + UP * 0.1)
        b7_l3 = MathTex(r"P_{avg} = 1100\ \text{W}").scale(1.15).shift(band_shift(7) + DOWN * 0.9)
        self.play(Write(b7_l1))
        self.wait(2.5)
        self.play(Write(b7_l2))
        self.wait(2)
        self.play(Write(b7_l3))
        self.play(Create(SurroundingRectangle(b7_l3, color=GREEN)))
        self.wait(2.5)
        b7_l4 = MathTex(r"I_{max} = 5\sqrt{2} = 7{,}07\ \text{A}").scale(1.05).shift(band_shift(7) + DOWN * 1.9)
        self.play(Write(b7_l4))
        self.wait(2)
        b7_l5 = Tex(r"Peak power $= 2200$ W $= 2 \times$ average").scale(1.05).shift(band_shift(7) + DOWN * 2.8)
        self.play(Write(b7_l5))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): the dynamo on the bicycle wheel
        self.next_band(8)
        b8_title = Tex("The dynamo on the bicycle wheel").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        # wheel + dynamo + lamp sketch
        wheel = Circle(radius=1.0).shift(band_shift(8) + LEFT * 3.0 + UP * 0.4)
        dyn = Rectangle(width=0.6, height=0.9).shift(band_shift(8) + LEFT * 1.6 + UP * 0.4)
        dyn_lab = Tex("magnet + coil").scale(0.8).shift(band_shift(8) + LEFT * 1.6 + UP * 1.4)
        wire_a = Line(band_shift(8) + LEFT * 1.3 + UP * 0.4, band_shift(8) + RIGHT * 1.4 + UP * 0.4)
        lamp = Circle(radius=0.35).shift(band_shift(8) + RIGHT * 1.8 + UP * 0.4)
        lamp_lab = Tex("lamp").scale(0.8).shift(band_shift(8) + RIGHT * 1.8 + UP * 1.2)
        self.play(Create(wheel), Create(dyn), Write(dyn_lab))
        self.play(Create(wire_a), Create(lamp), Write(lamp_lab))
        self.wait(2)
        b8_l1 = Tex("CHANGE is what pays: still magnet, no volts").scale(1.0).shift(band_shift(8) + DOWN * 0.8)
        self.play(Write(b8_l1))
        self.wait(2.5)
        b8_l2 = Tex("Pedal faster, glow brighter; stop, it dies").scale(1.0).shift(band_shift(8) + DOWN * 1.7)
        self.play(Write(b8_l2))
        self.wait(2)
        b8_l3 = Tex("Eskom: the same dynamo with a giant rider").scale(1.0).shift(band_shift(8) + DOWN * 2.6)
        self.play(Write(b8_l3))
        self.play(Create(SurroundingRectangle(b8_l3, color=GREEN)))
        self.wait(3)

        # --- Band 9 (subtopic_6): one machine, two personalities
        self.next_band(9)
        b9_title = Tex("One machine, two personalities").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex("Spin the shaft $\\rightarrow$ current out").scale(1.05).shift(band_shift(9) + UP * 1.2)
        b9_l2 = Tex("Feed current in $\\rightarrow$ the shaft spins").scale(1.05).shift(band_shift(9) + UP * 0.4)
        self.play(Write(b9_l1))
        self.wait(2)
        self.play(Write(b9_l2))
        self.wait(2.5)
        b9_l3 = Tex("Split ring swaps current every half turn:").scale(1.0).shift(band_shift(9) + DOWN * 0.6)
        b9_l4 = Tex("swap timed right, spin forever").scale(1.0).shift(band_shift(9) + DOWN * 1.4)
        self.play(Write(b9_l3))
        self.play(Write(b9_l4))
        self.wait(2.5)
        b9_l5 = Tex("EV: driving $=$ motor; braking $=$ generator").scale(1.0).shift(band_shift(9) + DOWN * 2.5)
        self.play(Write(b9_l5))
        self.play(Create(SurroundingRectangle(b9_l5, color=GREEN)))
        self.wait(3)

        # --- Band 10 (subtopic_7): what 220 volts actually means
        self.next_band(10)
        b10_title = Tex("What 220 volts actually means").scale(1.2).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_title))
        self.wait(2)
        b10_l1 = Tex(r"The wall swings $+311$ to $-311$ V, 50$\times$/s").scale(1.0).shift(band_shift(10) + UP * 1.2)
        self.play(Write(b10_l1))
        self.wait(2.5)
        b10_l2 = Tex("Heat works both strokes — like sandpaper").scale(1.0).shift(band_shift(10) + UP * 0.4)
        self.play(Write(b10_l2))
        self.wait(2.5)
        b10_l3 = MathTex(r"\frac{311}{1{,}414} = 220\ \text{V (rms)}").scale(1.1).shift(band_shift(10) + DOWN * 0.6)
        self.play(Write(b10_l3))
        self.play(Create(SurroundingRectangle(b10_l3, color=GREEN)))
        self.wait(2.5)
        b10_l4 = MathTex(r"\text{Kettle: } I = \frac{2200}{220} = 10\ \text{A (rms)}").scale(1.05).shift(band_shift(10) + DOWN * 1.8)
        self.play(Write(b10_l4))
        self.wait(2)
        b10_l5 = Tex("Peaks near 14 A; the bill runs on rms").scale(1.0).shift(band_shift(10) + DOWN * 2.8)
        self.play(Write(b10_l5))
        self.wait(4)
