from manim import *

# Band-layout whiteboard scene for "Value, Utility and Market Structures"
# (grade 10, term 2). One band per teaching beat; camera moves down, earlier
# work stays. Exporter-safe mobjects only; write-only reveals.
#
# Subtopic shares (subtopics.json, total 1450 s):
# 220/230/220/210/190/190/190.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class ValueUtilityMarketStructuresSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic full-screen while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): utility is subjective ---
        title = Tex("Value, Utility and Market Structures").scale(1.2).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        d1 = Tex(r"UTILITY: the satisfaction a consumer").scale(1.05).shift(UP * 1.1)
        d2 = Tex(r"derives from a good or service").scale(1.05).shift(UP * 0.4)
        self.play(Write(d1))
        self.play(Write(d2))
        self.wait(2.5)
        d3 = Tex(r"SUBJECTIVE — it lives in the user:").scale(1.05).shift(DOWN * 0.5)
        d4 = Tex(r"an umbrella in a storm vs a clear day").scale(1.0).shift(DOWN * 1.2)
        self.play(Write(d3))
        self.play(Write(d4))
        self.wait(2.5)
        d5 = Tex(r"That variation is why trade exists").scale(1.05).shift(DOWN * 2.2)
        self.play(Write(d5))
        self.play(Create(SurroundingRectangle(d5, color=GREEN)))
        self.wait(3)

        # --- Band 1 (subtopic_1): the two values, the paradox ---
        self.next_band(1)
        b1t = Tex("Water and diamonds").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1t))
        self.wait(1.5)
        b1a = Tex(r"Value in USE: usefulness to the owner").scale(1.0).shift(band_shift(1) + UP * 1.2)
        b1b = Tex(r"Value in EXCHANGE: what it fetches").scale(1.0).shift(band_shift(1) + UP * 0.5)
        self.play(Write(b1a))
        self.play(Write(b1b))
        self.wait(2.5)
        b1w = Tex(r"``Exchange value $=$ total usefulness''").scale(1.0).shift(band_shift(1) + DOWN * 0.4)
        self.play(Write(b1w))
        self.play(Create(strike(b1w)))
        self.wait(2)
        b1c = Tex(r"It is governed by SCARCITY relative to").scale(1.0).shift(band_shift(1) + DOWN * 1.3)
        b1d = Tex(r"wants, and the utility of the NEXT unit").scale(1.0).shift(band_shift(1) + DOWN * 2.0)
        self.play(Write(b1c))
        self.play(Write(b1d))
        self.wait(2)
        b1e = Tex(r"Plenty cheapens; scarcity dearens").scale(1.05).shift(band_shift(1) + DOWN * 2.9)
        self.play(Write(b1e))
        self.play(Create(SurroundingRectangle(b1e, color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): the perfect market ---
        self.next_band(2)
        b2t = Tex("The perfect market — the benchmark").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2t))
        self.wait(1.5)
        b2a = Tex(r"1. Many buyers and sellers").scale(1.0).shift(band_shift(2) + UP * 1.2)
        b2b = Tex(r"2. Homogeneous product").scale(1.0).shift(band_shift(2) + UP * 0.5)
        b2c = Tex(r"3. Perfect knowledge").scale(1.0).shift(band_shift(2) + DOWN * 0.2)
        b2d = Tex(r"4. Free entry and exit").scale(1.0).shift(band_shift(2) + DOWN * 0.9)
        self.play(Write(b2a))
        self.play(Write(b2b))
        self.play(Write(b2c))
        self.play(Write(b2d))
        box2 = SurroundingRectangle(VGroup(b2a, b2b, b2c, b2d), color=GREEN)
        self.play(Create(box2))
        self.wait(2.5)
        b2e = Tex(r"Everyone a PRICE TAKER — fresh produce").scale(0.95).shift(band_shift(2) + DOWN * 1.9)
        b2f = Tex(r"and share markets come closest").scale(0.95).shift(band_shift(2) + DOWN * 2.6)
        self.play(Write(b2e))
        self.play(Write(b2f))
        self.wait(3)

        # --- Band 3 (subtopic_2): imperfect structures ---
        self.next_band(3)
        b3t = Tex("Imperfect markets").scale(1.2).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3t))
        self.wait(1.5)
        b3a = Tex(r"MONOPOLY: one seller — patented pill,").scale(0.95).shift(band_shift(3) + UP * 1.2)
        b3b = Tex(r"sole water utility — a price MAKER").scale(0.95).shift(band_shift(3) + UP * 0.5)
        self.play(Write(b3a))
        self.play(Write(b3b))
        self.wait(2)
        b3c = Tex(r"OLIGOPOLY: a few large — banks,").scale(0.95).shift(band_shift(3) + DOWN * 0.3)
        b3d = Tex(r"networks, fuel — watching each other").scale(0.95).shift(band_shift(3) + DOWN * 1.0)
        self.play(Write(b3c))
        self.play(Write(b3d))
        self.wait(2)
        b3e = Tex(r"MONOPOLISTIC COMPETITION: many,").scale(0.95).shift(band_shift(3) + DOWN * 1.8)
        b3f = Tex(r"differentiated — salons, restaurants").scale(0.95).shift(band_shift(3) + DOWN * 2.5)
        self.play(Write(b3e))
        self.play(Write(b3f))
        self.wait(2)
        b3g = Tex(r"Test: how many? how similar? how free?").scale(0.95).shift(band_shift(3) + DOWN * 3.2)
        self.play(Write(b3g))
        self.play(Create(SurroundingRectangle(b3g, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): world markets, electronic effects ---
        self.next_band(4)
        b4t = Tex("World markets go electronic").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4t))
        self.wait(1.5)
        b4a = Tex(r"Platinum priced globally, not in").scale(1.0).shift(band_shift(4) + UP * 1.2)
        b4b = Tex(r"Rustenburg; the rand a world verdict").scale(1.0).shift(band_shift(4) + UP * 0.5)
        self.play(Write(b4a))
        self.play(Write(b4b))
        self.wait(2.5)
        b4c = Tex(r"Electronics: WIDENED markets,").scale(0.95).shift(band_shift(4) + DOWN * 0.4)
        b4d = Tex(r"ACCELERATED trading, brightened").scale(0.95).shift(band_shift(4) + DOWN * 1.1)
        b4e = Tex(r"KNOWLEDGE, lowered ENTRY, NEW forms").scale(0.95).shift(band_shift(4) + DOWN * 1.8)
        self.play(Write(b4c))
        self.play(Write(b4d))
        self.play(Write(b4e))
        self.wait(2.5)
        b4f = Tex(r"The farmer checks the market price").scale(0.95).shift(band_shift(4) + DOWN * 2.7)
        b4g = Tex(r"before the middleman's offer").scale(0.95).shift(band_shift(4) + DOWN * 3.4)
        self.play(Write(b4f))
        self.play(Write(b4g))
        self.wait(3)

        # --- Band 5 (subtopic_3): balancing the account ---
        self.next_band(5)
        b5t = Tex("Balance the account").scale(1.2).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5t))
        self.wait(1.5)
        b5a = Tex(r"Power concentrates in platform owners").scale(1.0).shift(band_shift(5) + UP * 1.1)
        b5b = Tex(r"Small sellers face world competition").scale(1.0).shift(band_shift(5) + UP * 0.3)
        b5c = Tex(r"The digital divide: data as a new").scale(1.0).shift(band_shift(5) + DOWN * 0.5)
        b5d = Tex(r"barrier to entry").scale(1.0).shift(band_shift(5) + DOWN * 1.2)
        self.play(Write(b5a))
        self.wait(2)
        self.play(Write(b5b))
        self.wait(2)
        self.play(Write(b5c))
        self.play(Write(b5d))
        self.wait(2)
        b5e = Tex(r"Wider, faster, better informed —").scale(1.05).shift(band_shift(5) + DOWN * 2.1)
        b5f = Tex(r"not automatically fairer").scale(1.05).shift(band_shift(5) + DOWN * 2.8)
        self.play(Write(b5e))
        self.play(Write(b5f))
        self.play(Create(SurroundingRectangle(b5f, color=GREEN)))
        self.wait(3)

        # --- Band 6 (subtopic_4): the five functions of markets ---
        self.next_band(6)
        b6t = Tex("What markets DO — five functions").scale(1.15).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6t))
        self.wait(1.5)
        b6a = Tex(r"1. PRICE FORMATION at the crossing").scale(0.95).shift(band_shift(6) + UP * 1.2)
        b6b = Tex(r"2. ALLOCATION — prices steer resources").scale(0.95).shift(band_shift(6) + UP * 0.5)
        b6c = Tex(r"3. INFORMATION — one-number messages").scale(0.95).shift(band_shift(6) + DOWN * 0.2)
        b6d = Tex(r"4. RATIONING — rising price decides who").scale(0.95).shift(band_shift(6) + DOWN * 0.9)
        b6e = Tex(r"5. LINKING buyers and sellers worldwide").scale(0.95).shift(band_shift(6) + DOWN * 1.6)
        for m in (b6a, b6b, b6c, b6d, b6e):
            self.play(Write(m))
            self.wait(1.2)
        b6f = Tex(r"Markets form prices; prices then").scale(1.0).shift(band_shift(6) + DOWN * 2.5)
        b6g = Tex(r"allocate, inform, ration and connect").scale(1.0).shift(band_shift(6) + DOWN * 3.2)
        self.play(Write(b6f))
        self.play(Write(b6g))
        self.play(Create(SurroundingRectangle(VGroup(b6f, b6g), color=GREEN)))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 7 (subtopic_5): the stadium bottle ---
        self.next_band(7)
        b7t = Tex("Why water costs R25 at the stadium").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7t))
        self.wait(2)
        b7a = Tex(r"R7 at the shop, R25 inside the gates —").scale(1.0).shift(band_shift(7) + UP * 1.2)
        b7b = Tex(r"the water didn't change; YOU did").scale(1.0).shift(band_shift(7) + UP * 0.5)
        self.play(Write(b7a))
        self.play(Write(b7b))
        self.wait(2.5)
        b7c = Tex(r"Usefulness-worth: water wins by a mile").scale(1.0).shift(band_shift(7) + DOWN * 0.4)
        b7d = Tex(r"Trading-worth runs on SCARCITY:").scale(1.0).shift(band_shift(7) + DOWN * 1.1)
        b7e = Tex(r"plenty makes cheap, scarce makes dear").scale(1.0).shift(band_shift(7) + DOWN * 1.8)
        self.play(Write(b7c))
        self.play(Write(b7d))
        self.play(Write(b7e))
        self.play(Create(SurroundingRectangle(b7e, color=GREEN)))
        self.wait(2.5)
        b7f = Tex(r"Lock the gates: water IS scarce inside —").scale(0.95).shift(band_shift(7) + DOWN * 2.7)
        b7g = Tex(r"and its price triples").scale(0.95).shift(band_shift(7) + DOWN * 3.4)
        self.play(Write(b7f))
        self.play(Write(b7g))
        self.wait(3)

        # --- Band 8 (subtopic_6): the potato market and the phone shops ---
        self.next_band(8)
        b8t = Tex("The potato market and the phone shops").scale(1.1).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8t))
        self.wait(2)
        b8a = Tex(r"Fifty farmers, identical sacks, visible").scale(1.0).shift(band_shift(8) + UP * 1.2)
        b8b = Tex(r"prices, free entry: ONE going price —").scale(1.0).shift(band_shift(8) + UP * 0.5)
        b8c = Tex(r"everyone takes it (perfect market)").scale(1.0).shift(band_shift(8) + DOWN * 0.2)
        self.play(Write(b8a))
        self.play(Write(b8b))
        self.play(Write(b8c))
        self.wait(2.5)
        b8d = Tex(r"Three networks: oligopoly.").scale(1.0).shift(band_shift(8) + DOWN * 1.1)
        b8e = Tex(r"One patented pill: monopoly — maker.").scale(1.0).shift(band_shift(8) + DOWN * 1.8)
        b8f = Tex(r"Salons, each different: monopolistic").scale(1.0).shift(band_shift(8) + DOWN * 2.5)
        b8g = Tex(r"competition").scale(1.0).shift(band_shift(8) + DOWN * 3.2)
        self.play(Write(b8d))
        self.wait(1.5)
        self.play(Write(b8e))
        self.wait(1.5)
        self.play(Write(b8f))
        self.play(Write(b8g))
        self.wait(3)

        # --- Band 9 (subtopic_7): the market in your pocket ---
        self.next_band(9)
        b9t = Tex("The market in your pocket").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9t))
        self.wait(2)
        b9a = Tex(r"The farmer negotiates from knowledge;").scale(1.0).shift(band_shift(9) + UP * 1.2)
        b9b = Tex(r"the seamstress sells with no shopfront").scale(1.0).shift(band_shift(9) + UP * 0.5)
        self.play(Write(b9a))
        self.play(Write(b9b))
        self.wait(2.5)
        b9c = Tex(r"But: owned platforms at the gates,").scale(1.0).shift(band_shift(9) + DOWN * 0.4)
        b9d = Tex(r"world rivals, and data as a locked gate").scale(1.0).shift(band_shift(9) + DOWN * 1.1)
        self.play(Write(b9c))
        self.play(Write(b9d))
        self.wait(2.5)
        b9e = Tex(r"Old or electronic, same five jobs:").scale(1.0).shift(band_shift(9) + DOWN * 2.0)
        b9f = Tex(r"markets make prices; prices do the rest").scale(1.0).shift(band_shift(9) + DOWN * 2.7)
        self.play(Write(b9e))
        self.play(Write(b9f))
        self.play(Create(SurroundingRectangle(b9f, color=GREEN)))
        self.wait(4)
