from manim import *

# Band-layout whiteboard scene for "GDP and GNI" (grade 10, term 1).
# One band per teaching beat; camera moves down, earlier work stays.
# Exporter-safe mobjects only; write-only reveals; the bread value chain is
# built from labelled Rectangles and Arrows.
#
# Subtopic shares (subtopics.json, total 1440 s):
# 210/220/220/220/190/190/190.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class GdpAndGniSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic full-screen while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): three gauges on one pipe ---
        title = Tex("Measuring the Economy: GDP and GNI").scale(1.2).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        d1 = Tex(r"Three gauges on one pipe:").scale(1.1).shift(UP * 1.1)
        self.play(Write(d1))
        self.wait(1.5)
        g1 = Tex(r"PRODUCTION $\rightarrow$ INCOME $\rightarrow$ SPENDING").scale(1.1).shift(UP * 0.2)
        self.play(Write(g1))
        self.wait(2)
        d2 = Tex(r"production creates income, income funds").scale(0.95).shift(DOWN * 0.7)
        d3 = Tex(r"spending, spending buys production").scale(0.95).shift(DOWN * 1.4)
        self.play(Write(d2))
        self.play(Write(d3))
        self.wait(2.5)
        d4 = Tex(r"One total, three routes — Stats SA").scale(1.0).shift(DOWN * 2.4)
        d5 = Tex(r"compiles the headline: GDP").scale(1.0).shift(DOWN * 3.1)
        self.play(Write(d4))
        self.play(Write(d5))
        self.wait(3)

        # --- Band 1 (subtopic_1): the GDP definition, phrase by phrase ---
        self.next_band(1)
        b1t = Tex("GDP — every phrase works").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1t))
        self.wait(1.5)
        b1a = Tex(r"Total MARKET VALUE of all FINAL goods").scale(1.0).shift(band_shift(1) + UP * 1.2)
        b1b = Tex(r"and services produced WITHIN a").scale(1.0).shift(band_shift(1) + UP * 0.5)
        b1c = Tex(r"country's borders in a GIVEN PERIOD").scale(1.0).shift(band_shift(1) + DOWN * 0.2)
        self.play(Write(b1a))
        self.play(Write(b1b))
        self.play(Write(b1c))
        box1 = SurroundingRectangle(VGroup(b1a, b1b, b1c), color=GREEN)
        self.play(Create(box1))
        self.wait(2.5)
        b1d = Tex(r"market value: prices add unlike things").scale(0.95).shift(band_shift(1) + DOWN * 1.2)
        b1e = Tex(r"final: sold to the end user").scale(0.95).shift(band_shift(1) + DOWN * 1.9)
        b1f = Tex(r"within borders: geography, not passport").scale(0.95).shift(band_shift(1) + DOWN * 2.6)
        b1g = Tex(r"period: a flow per year, not a stockpile").scale(0.95).shift(band_shift(1) + DOWN * 3.3)
        self.play(Write(b1d))
        self.play(Write(b1e))
        self.play(Write(b1f))
        self.play(Write(b1g))
        self.wait(3)

        # --- Band 2 (subtopic_2): the bread chain, no double counting ---
        self.next_band(2)
        b2t = Tex("Final goods only — follow the bread").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2t))
        self.wait(1.5)
        # Value chain: three labelled boxes with arrows.
        w_box = Rectangle(width=2.9, height=1.0).shift(band_shift(2) + LEFT * 4.0 + UP * 0.9)
        w_lab = Tex("wheat R4").scale(0.85).move_to(w_box)
        f_box = Rectangle(width=2.9, height=1.0).shift(band_shift(2) + UP * 0.9)
        f_lab = Tex("flour R7").scale(0.85).move_to(f_box)
        l_box = Rectangle(width=2.9, height=1.0).shift(band_shift(2) + RIGHT * 4.0 + UP * 0.9)
        l_lab = Tex("loaf R18").scale(0.85).move_to(l_box)
        a1 = Arrow(w_box.get_right(), f_box.get_left(), buff=0.1, stroke_width=4)
        a2 = Arrow(f_box.get_right(), l_box.get_left(), buff=0.1, stroke_width=4)
        self.play(Create(w_box), Write(w_lab))
        self.play(Create(a1), Create(f_box), Write(f_lab))
        self.play(Create(a2), Create(l_box), Write(l_lab))
        self.wait(2)
        b2w = MathTex(r"4 + 7 + 18 = \text{R}29").scale(1.1).shift(band_shift(2) + DOWN * 0.3)
        self.play(Write(b2w))
        self.play(Create(strike(b2w)))
        self.wait(2)
        b2a = Tex(r"Wheat and flour are INTERMEDIATE —").scale(1.0).shift(band_shift(2) + DOWN * 1.2)
        b2b = Tex(r"already inside the loaf's price").scale(1.0).shift(band_shift(2) + DOWN * 1.9)
        self.play(Write(b2a))
        self.play(Write(b2b))
        self.wait(2)
        b2c = MathTex(r"\text{Value added: } 4 + 3 + 11 = \text{R}18").scale(1.05).shift(band_shift(2) + DOWN * 2.8)
        self.play(Write(b2c))
        self.play(Create(SurroundingRectangle(b2c, color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_2): the border rule and the excluded list ---
        self.next_band(3)
        b3t = Tex("The border rule — and the excluded").scale(1.15).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3t))
        self.wait(1.5)
        b3a = Tex(r"Foreign-owned mine on SA soil:").scale(1.0).shift(band_shift(3) + UP * 1.2)
        b3b = Tex(r"counts in SA GDP — produced here").scale(1.0).shift(band_shift(3) + UP * 0.5)
        self.play(Write(b3a))
        self.play(Write(b3b))
        self.wait(2)
        b3c = Tex(r"SA engineer in Dubai: Dubai's GDP").scale(1.0).shift(band_shift(3) + DOWN * 0.3)
        self.play(Write(b3c))
        self.wait(2)
        b3d = Tex(r"Excluded: second-hand sales (dealer's").scale(0.95).shift(band_shift(3) + DOWN * 1.2)
        b3e = Tex(r"fee counts), share trades, social grants,").scale(0.95).shift(band_shift(3) + DOWN * 1.9)
        b3f = Tex(r"unpaid and informal work").scale(0.95).shift(band_shift(3) + DOWN * 2.6)
        self.play(Write(b3d))
        self.play(Write(b3e))
        self.play(Write(b3f))
        self.wait(2)
        b3g = Tex(r"Nothing NEW made $\Rightarrow$ not counted").scale(1.0).shift(band_shift(3) + DOWN * 3.3)
        self.play(Write(b3g))
        self.play(Create(SurroundingRectangle(b3g, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): GNI and the bridge ---
        self.next_band(4)
        b4t = Tex("GNI — following the factors home").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4t))
        self.wait(1.5)
        b4a = Tex(r"GDP asks WHERE it was produced;").scale(1.05).shift(band_shift(4) + UP * 1.2)
        b4b = Tex(r"GNI asks WHO earned the income").scale(1.05).shift(band_shift(4) + UP * 0.5)
        self.play(Write(b4a))
        self.play(Write(b4b))
        self.wait(2.5)
        b4c = Tex(r"GNI $=$ GDP $-$ factor income paid abroad").scale(1.0).shift(band_shift(4) + DOWN * 0.4)
        b4d = Tex(r"$+$ factor income received from abroad").scale(1.0).shift(band_shift(4) + DOWN * 1.1)
        self.play(Write(b4c))
        self.play(Write(b4d))
        box4 = SurroundingRectangle(VGroup(b4c, b4d), color=GREEN)
        self.play(Create(box4))
        self.wait(2.5)
        b4e = Tex(r"SA: foreign-owned mines $\Rightarrow$ GNI $<$ GDP").scale(0.95).shift(band_shift(4) + DOWN * 2.1)
        b4f = Tex(r"Lesotho: wages remitted home $\Rightarrow$ GNI $>$ GDP").scale(0.95).shift(band_shift(4) + DOWN * 2.8)
        self.play(Write(b4e))
        self.wait(2)
        self.play(Write(b4f))
        self.wait(3)

        # --- Band 5 (subtopic_4): per capita and the limits ---
        self.next_band(5)
        b5t = Tex("Per capita — and the honest limits").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5t))
        self.wait(1.5)
        b5a = MathTex(r"\text{GDP per capita} = \frac{\text{GDP}}{\text{population}}").scale(1.05).shift(band_shift(5) + UP * 1.0)
        self.play(Write(b5a))
        self.play(Create(SurroundingRectangle(b5a, color=GREEN)))
        self.wait(2.5)
        b5b = Tex(r"GDP does NOT measure:").scale(1.05).shift(band_shift(5) + DOWN * 0.1)
        b5c = Tex(r"1. distribution — averages hide the split").scale(0.95).shift(band_shift(5) + DOWN * 0.9)
        b5d = Tex(r"2. unpaid and informal work").scale(0.95).shift(band_shift(5) + DOWN * 1.6)
        b5e = Tex(r"3. well-being — health, safety, leisure").scale(0.95).shift(band_shift(5) + DOWN * 2.3)
        b5f = Tex(r"4. the environment — timber, not the forest").scale(0.95).shift(band_shift(5) + DOWN * 3.0)
        self.play(Write(b5b))
        self.play(Write(b5c))
        self.play(Write(b5d))
        self.play(Write(b5e))
        self.play(Write(b5f))
        self.wait(3.5)

        # ============ Part 2 — Simplifier ============
        # --- Band 6 (subtopic_5): counting everything the street made ---
        self.next_band(6)
        b6t = Tex("Counting everything the street made").scale(1.15).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6t))
        self.wait(2)
        b6a = Tex(r"Spaza sales, braids, repairs, vetkoek —").scale(1.0).shift(band_shift(6) + UP * 1.2)
        b6b = Tex(r"the street's GDP in rands").scale(1.0).shift(band_shift(6) + UP * 0.5)
        self.play(Write(b6a))
        self.play(Write(b6b))
        self.wait(2)
        b6w = Tex(r"Parts R300 $+$ repair R900 $=$ R1 200").scale(1.0).shift(band_shift(6) + DOWN * 0.4)
        self.play(Write(b6w))
        self.play(Create(strike(b6w)))
        self.wait(2)
        b6c = Tex(r"The parts are inside the R900:").scale(1.0).shift(band_shift(6) + DOWN * 1.3)
        b6d = Tex(r"mechanic ADDED R600 of skill").scale(1.0).shift(band_shift(6) + DOWN * 2.0)
        self.play(Write(b6c))
        self.play(Write(b6d))
        self.play(Create(SurroundingRectangle(b6d, color=GREEN)))
        self.wait(2)
        b6e = Tex(r"Old bakkie resold, granny's grant:").scale(0.95).shift(band_shift(6) + DOWN * 2.8)
        b6f = Tex(r"money moved, nothing new made").scale(0.95).shift(band_shift(6) + DOWN * 3.4)
        self.play(Write(b6e))
        self.play(Write(b6f))
        self.wait(3)

        # --- Band 7 (subtopic_6): the where-rule and the who-rule ---
        self.next_band(7)
        b7t = Tex("The where-rule and the who-rule").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7t))
        self.wait(2)
        b7a = Tex(r"WHERE (GDP): made on this street —").scale(1.0).shift(band_shift(7) + UP * 1.2)
        b7b = Tex(r"the outsider's shop counts here").scale(1.0).shift(band_shift(7) + UP * 0.5)
        self.play(Write(b7a))
        self.play(Write(b7b))
        self.wait(2)
        b7c = Tex(r"WHO (GNI): what our people earn —").scale(1.0).shift(band_shift(7) + DOWN * 0.3)
        b7d = Tex(r"the daughter in Sandton counts now").scale(1.0).shift(band_shift(7) + DOWN * 1.0)
        self.play(Write(b7c))
        self.play(Write(b7d))
        self.wait(2.5)
        b7e = Tex(r"Outsiders own the big shops: machine").scale(0.95).shift(band_shift(7) + DOWN * 1.9)
        b7f = Tex(r"here, keeping elsewhere — SA's shape").scale(0.95).shift(band_shift(7) + DOWN * 2.6)
        self.play(Write(b7e))
        self.play(Write(b7f))
        self.wait(2)
        b7g = Tex(r"The GAP between the two is the story").scale(1.0).shift(band_shift(7) + DOWN * 3.3)
        self.play(Write(b7g))
        self.play(Create(SurroundingRectangle(b7g, color=GREEN)))
        self.wait(3)

        # --- Band 8 (subtopic_7): what the big number can't see ---
        self.next_band(8)
        b8t = Tex("What the big number can't see").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8t))
        self.wait(2)
        b8a = Tex(r"1. WHO got it — totals aren't sharing").scale(1.0).shift(band_shift(8) + UP * 1.2)
        b8b = Tex(r"2. Work with no till — gogo's childcare").scale(1.0).shift(band_shift(8) + UP * 0.5)
        b8c = Tex(r"3. How life FEELS — more sold, worse lived").scale(1.0).shift(band_shift(8) + DOWN * 0.2)
        b8d = Tex(r"4. What got used up — the tree's absence").scale(1.0).shift(band_shift(8) + DOWN * 0.9)
        self.play(Write(b8a))
        self.wait(1.5)
        self.play(Write(b8b))
        self.wait(1.5)
        self.play(Write(b8c))
        self.wait(1.5)
        self.play(Write(b8d))
        self.wait(2)
        b8e = Tex(r"A speedometer, not a report card:").scale(1.05).shift(band_shift(8) + DOWN * 1.9)
        b8f = Tex(r"how fast — never how well, or for whom").scale(1.05).shift(band_shift(8) + DOWN * 2.6)
        self.play(Write(b8e))
        self.play(Write(b8f))
        self.play(Create(SurroundingRectangle(VGroup(b8e, b8f), color=GREEN)))
        self.wait(4)
