from manim import *

# Band-layout whiteboard scene for kinetic-energy (Part 1 Expert subtopics
# 1-4, Part 2 Simplifier subtopics 5-7). Exporter-safe mobjects only;
# add-only lifecycle; the 1000 kg car problem worked line by line with the
# script's exact numbers and units.
# Time apportioned to subtopics.json (225/235/240/245/180/175/175 of 1475 s).

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class KineticEnergySession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): energy carried by motion ---
        title = Tex("Kinetic Energy").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        a1 = Tex("Energy an object carries because it MOVES").scale(1.0).shift(UP * 1.0)
        self.play(Write(a1))
        self.wait(2)
        a2 = MathTex(r"E_k = \tfrac{1}{2} m v^2").scale(1.3).shift(UP * 0.0)
        self.play(Write(a2))
        self.play(Create(SurroundingRectangle(a2, color=GREEN)))
        self.wait(2.5)
        a3 = Tex("Mass dial: plain — double $m$, double $E_k$").scale(0.95).shift(DOWN * 1.0)
        self.play(Write(a3))
        self.wait(2)
        a4 = Tex("Speed dial: SQUARED — double $v$, four times").scale(0.95).shift(DOWN * 1.8)
        self.play(Write(a4))
        self.wait(2)
        a5 = Tex("Scalar, never negative: squaring erases sign").scale(0.95).shift(DOWN * 2.7)
        self.play(Write(a5))
        self.wait(3)

        # --- Band 1 (subtopic_2): a tonne at twenty ---
        self.next_band(1)
        b1_t = Tex("A tonne at twenty").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_t))
        self.wait(1.5)
        b1_1 = MathTex(r"m = 1000\ \text{kg}, \; v = 20\ \text{m·s}^{-1}\ (72\ \text{km/h})").scale(0.9).shift(band_shift(1) + UP * 1.2)
        self.play(Write(b1_1))
        self.wait(2)
        b1_2 = MathTex(r"v^2 = 20^2 = 400 \; \text{(square first!)}").scale(1.05).shift(band_shift(1) + UP * 0.2)
        self.play(Write(b1_2))
        self.wait(2)
        b1_3 = MathTex(r"\tfrac{1}{2} \times 1000 = 500").scale(1.05).shift(band_shift(1) + DOWN * 0.8)
        self.play(Write(b1_3))
        self.wait(2)
        b1_4 = MathTex(r"E_k = 500 \times 400 = 200\,000\ \text{J}").scale(1.1).shift(band_shift(1) + DOWN * 1.8)
        self.play(Write(b1_4))
        self.play(Create(SurroundingRectangle(b1_4, color=GREEN)))
        self.wait(2.5)
        b1_5 = Tex("= a 2 kg brick raised 10 km high").scale(0.95).shift(band_shift(1) + DOWN * 2.8)
        self.play(Write(b1_5))
        self.wait(3)

        # --- Band 2 (subtopic_2): the forgotten square ---
        self.next_band(2)
        b2_t = Tex("The commonest error, killed").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(1.5)
        b2_trap = MathTex(r"E_k = \tfrac{1}{2} \times 1000 \times 20 = 10\,000\ \text{J}").scale(1.0).shift(band_shift(2) + UP * 1.1)
        self.play(Write(b2_trap))
        self.play(Create(strike(b2_trap)))
        self.wait(2)
        b2_1 = Tex("Twenty times too small — the square forgot").scale(0.95).shift(band_shift(2) + UP * 0.2)
        self.play(Write(b2_1))
        self.wait(2)
        b2_2 = Tex("Defence: $v^2 = 400$ as its OWN line first").scale(1.0).shift(band_shift(2) + DOWN * 0.7)
        self.play(Write(b2_2))
        self.play(Create(SurroundingRectangle(b2_2, color=GREEN)))
        self.wait(2)
        b2_3 = MathTex(r"\text{Units: kg·m}^2\text{·s}^{-2} = \text{J} \; \checkmark").scale(1.0).shift(band_shift(2) + DOWN * 1.7)
        self.play(Write(b2_3))
        self.wait(2)
        b2_4 = MathTex(r"\text{km/h} \div 3{,}6 \to \text{m·s}^{-1} \; \text{BEFORE squaring}").scale(0.9).shift(band_shift(2) + DOWN * 2.6)
        self.play(Write(b2_4))
        self.wait(3)

        # --- Band 3 (subtopic_3): doubling the speed ---
        self.next_band(3)
        b3_t = Tex("The driver doubles the speed").scale(1.2).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t))
        self.wait(1.5)
        b3_1 = MathTex(r"v = 40\ \text{m·s}^{-1} \; (144\ \text{km/h})").scale(1.0).shift(band_shift(3) + UP * 1.1)
        self.play(Write(b3_1))
        self.wait(2)
        b3_2 = MathTex(r"v^2 = 40^2 = 1600").scale(1.05).shift(band_shift(3) + UP * 0.1)
        self.play(Write(b3_2))
        self.wait(2)
        b3_3 = MathTex(r"E_k = 500 \times 1600 = 800\,000\ \text{J}").scale(1.05).shift(band_shift(3) + DOWN * 0.9)
        self.play(Write(b3_3))
        self.play(Create(SurroundingRectangle(b3_3, color=GREEN)))
        self.wait(2.5)
        b3_4 = MathTex(r"\frac{800\,000}{200\,000} = 4: \; \text{double speed, FOUR}\times").scale(0.95).shift(band_shift(3) + DOWN * 1.9)
        self.play(Write(b3_4))
        self.wait(2)
        b3_5 = Tex("Triple the speed: nine times ($3^2$)").scale(1.0).shift(band_shift(3) + DOWN * 2.8)
        self.play(Write(b3_5))
        self.wait(3)

        # --- Band 4 (subtopic_3): the road consequences ---
        self.next_band(4)
        b4_t = Tex("The square on the road").scale(1.2).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(1.5)
        b4_1 = Tex("4$\\times$ energy: about 4$\\times$ braking distance").scale(1.0).shift(band_shift(4) + UP * 1.1)
        self.play(Write(b4_1))
        self.wait(2)
        b4_2 = Tex("Crash at 80 = four crashes at 40 at once").scale(1.0).shift(band_shift(4) + UP * 0.2)
        self.play(Write(b4_2))
        self.wait(2)
        b4_3 = MathTex(r"60: 139\,000\ \text{J}; \; 100: 386\,000\ \text{J}").scale(0.95).shift(band_shift(4) + DOWN * 0.8)
        self.play(Write(b4_3))
        self.wait(2)
        b4_4 = MathTex(r"120: 556\,000\ \text{J} \; \text{(km/h speeds)}").scale(0.95).shift(band_shift(4) + DOWN * 1.7)
        self.play(Write(b4_4))
        self.wait(2)
        b4_5 = Tex("Last 20 km/h cost more than the first 60").scale(0.95).shift(band_shift(4) + DOWN * 2.6)
        self.play(Write(b4_5))
        self.play(Create(SurroundingRectangle(b4_5, color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_4): the four-step method ---
        self.next_band(5)
        b5_t = Tex("The method, four steps").scale(1.2).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_t))
        self.wait(1.5)
        b5_1 = Tex("1. List $m$, $v$ — convert as you list").scale(1.0).shift(band_shift(5) + UP * 1.1)
        b5_2 = Tex("2. Square $v$ as its own written line").scale(1.0).shift(band_shift(5) + UP * 0.3)
        b5_3 = Tex("3. Assemble $\\tfrac{1}{2} m v^2$, carry units").scale(1.0).shift(band_shift(5) + DOWN * 0.5)
        b5_4 = Tex("4. Sense-check: positive, no direction").scale(1.0).shift(band_shift(5) + DOWN * 1.3)
        for m in (b5_1, b5_2, b5_3, b5_4):
            self.play(Write(m))
            self.wait(1.8)
        b5_5 = Tex("Scale: hundreds for balls, $10^5$ for cars").scale(0.95).shift(band_shift(5) + DOWN * 2.3)
        self.play(Write(b5_5))
        self.wait(3)

        # --- Band 6 (subtopic_4): the remaining traps ---
        self.next_band(6)
        b6_t = Tex("The classic traps").scale(1.2).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_t))
        self.wait(1.5)
        b6_trap = MathTex(r"72^2 \; \text{(squared in km/h!)}").scale(1.0).shift(band_shift(6) + UP * 1.1)
        self.play(Write(b6_trap))
        self.play(Create(strike(b6_trap)))
        self.wait(2)
        b6_1 = Tex("Convert first: wrong unit squares the error").scale(0.95).shift(band_shift(6) + UP * 0.2)
        self.play(Write(b6_1))
        self.wait(2)
        b6_2 = Tex("Never drop the half: it doubles every answer").scale(0.95).shift(band_shift(6) + DOWN * 0.7)
        self.play(Write(b6_2))
        self.wait(2)
        b6_3 = Tex("Negative direction still gives positive $E_k$").scale(0.95).shift(band_shift(6) + DOWN * 1.6)
        self.play(Write(b6_3))
        self.wait(2)
        b6_4 = Tex("Compare energies by squares, never speeds").scale(0.95).shift(band_shift(6) + DOWN * 2.5)
        self.play(Write(b6_4))
        self.play(Create(SurroundingRectangle(b6_4, color=GREEN)))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 7 (subtopic_5): the moving wallet ---
        self.next_band(7)
        b7_t = Tex("The moving wallet").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(2)
        b7_1 = Tex("Motion = carrying cash; stopping = spending").scale(0.95).shift(band_shift(7) + UP * 1.1)
        self.play(Write(b7_1))
        self.wait(2)
        b7_2 = Tex("Soft hands spend gently; a wall spends instantly").scale(0.9).shift(band_shift(7) + UP * 0.2)
        self.play(Write(b7_2))
        self.wait(2)
        b7_3 = Tex("Mass dial: full taxi = double the empty one").scale(0.95).shift(band_shift(7) + DOWN * 0.7)
        self.play(Write(b7_3))
        self.wait(2)
        b7_4 = Tex("Speed dial multiplies by ITSELF: 2$\\times$ = 4$\\times$").scale(0.95).shift(band_shift(7) + DOWN * 1.6)
        self.play(Write(b7_4))
        self.play(Create(SurroundingRectangle(b7_4, color=GREEN)))
        self.wait(2)
        b7_5 = Tex("No direction; standing still = empty wallet").scale(0.95).shift(band_shift(7) + DOWN * 2.5)
        self.play(Write(b7_5))
        self.wait(3)

        # --- Band 8 (subtopic_6): counting the taxi's cash ---
        self.next_band(8)
        b8_t = Tex("Counting the taxi's cash").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_t))
        self.wait(2)
        b8_1 = MathTex(r"20^2 = 400 \; \text{(square first, own line)}").scale(1.0).shift(band_shift(8) + UP * 1.1)
        self.play(Write(b8_1))
        self.wait(2.5)
        b8_2 = MathTex(r"\tfrac{1}{2} \times 1000 = 500").scale(1.0).shift(band_shift(8) + UP * 0.1)
        self.play(Write(b8_2))
        self.wait(2)
        b8_3 = MathTex(r"500 \times 400 = 200\,000\ \text{J}").scale(1.05).shift(band_shift(8) + DOWN * 0.9)
        self.play(Write(b8_3))
        self.play(Create(SurroundingRectangle(b8_3, color=GREEN)))
        self.wait(2.5)
        b8_4 = Tex("Brakes swallow it all as heat, every stop").scale(0.95).shift(band_shift(8) + DOWN * 1.9)
        self.play(Write(b8_4))
        self.wait(2)
        b8_5 = Tex("Forget the square: 10 000 J, 20$\\times$ too thin").scale(0.95).shift(band_shift(8) + DOWN * 2.8)
        self.play(Write(b8_5))
        self.wait(3)

        # --- Band 9 (subtopic_7): the quadratic surcharge ---
        self.next_band(9)
        b9_t = Tex("The quadratic surcharge").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(2)
        b9_1 = MathTex(r"40^2 = 1600: \; 500 \times 1600 = 800\,000\ \text{J}").scale(0.95).shift(band_shift(9) + UP * 1.1)
        self.play(Write(b9_1))
        self.play(Create(SurroundingRectangle(b9_1, color=GREEN)))
        self.wait(2.5)
        b9_2 = Tex("Double the pace, four times the fortune").scale(1.0).shift(band_shift(9) + UP * 0.1)
        self.play(Write(b9_2))
        self.wait(2)
        b9_3 = Tex("100 to 120 adds more than 0 to 60").scale(1.0).shift(band_shift(9) + DOWN * 0.8)
        self.play(Write(b9_3))
        self.wait(2)
        b9_4 = Tex("Safe gap at 60 is a factor short at 120").scale(1.0).shift(band_shift(9) + DOWN * 1.7)
        self.play(Write(b9_4))
        self.wait(2)
        b9_5 = Tex("Speed limits are the square, wearing law").scale(1.0).shift(band_shift(9) + DOWN * 2.6)
        self.play(Write(b9_5))
        self.wait(4)
