from manim import *

# Band-layout whiteboard scene for the Interest Without Formulae session duo.
# One band per teaching beat, camera moves down between bands, add-only
# lifecycle. Exporter-supported mobjects only; every working line is a
# single-string Tex/MathTex revealed with Write. Band time apportioned to
# subtopics.json (200/230/230/260/180/190/190 of 1480 s).

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class InterestWithoutFormulaeSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): a percentage is not money ---
        title = Tex("Interest Without Formulae").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex("Rate: a percentage per time period — a speed").scale(1.05).shift(UP * 1.1)
        b0_l2 = Tex("Interest: the actual rand amount produced").scale(1.05).shift(UP * 0.2)
        self.play(Write(b0_l1))
        self.wait(2.5)
        self.play(Write(b0_l2))
        self.wait(2.5)
        b0_l3 = MathTex(r"8\% \text{ of R3 000} = 0{,}08 \times 3\;000 = \text{R}240").scale(1.1).shift(DOWN * 0.8)
        self.play(Write(b0_l3))
        self.wait(2.5)
        b0_l4 = Tex("Rate: 8\\% \\quad Interest: R240").scale(1.1).shift(DOWN * 1.8)
        self.play(Write(b0_l4))
        self.play(Create(SurroundingRectangle(b0_l4, color=GREEN)))
        b0_l5 = Tex("Rate acts on PRINCIPAL to produce interest").scale(1.0).shift(DOWN * 2.8)
        self.play(Write(b0_l5))
        self.wait(3)

        # --- Band 1 (subtopic_1): direction of the money ---
        self.next_band(1)
        b1_t = Tex("Who pays whom?").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_t))
        self.wait(1.5)
        b1_l1 = Tex("Saver: the bank uses YOUR money").scale(1.1).shift(band_shift(1) + UP * 1.1)
        b1_l2 = Tex("So the bank PAYS you interest — a gain").scale(1.1).shift(band_shift(1) + UP * 0.2)
        self.play(Write(b1_l1))
        self.wait(2)
        self.play(Write(b1_l2))
        self.wait(2.5)
        b1_l3 = Tex("Borrower: you use the BANK'S money").scale(1.1).shift(band_shift(1) + DOWN * 0.8)
        b1_l4 = Tex("So YOU pay the interest — a cost").scale(1.1).shift(band_shift(1) + DOWN * 1.7)
        self.play(Write(b1_l3))
        self.wait(2)
        self.play(Write(b1_l4))
        self.play(Create(SurroundingRectangle(b1_l4, color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): year one, step by step ---
        self.next_band(2)
        b2_t = Tex("Thabo saves R3 000 at 8\\% per year").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(1.5)
        b2_l1 = MathTex(r"10\% \text{ of } 3\;000 = 300").scale(1.1).shift(band_shift(2) + UP * 1.1)
        b2_l2 = MathTex(r"1\% = 30, \quad 8\% = 8 \times 30 = \text{R}240").scale(1.1).shift(band_shift(2) + UP * 0.2)
        self.play(Write(b2_l1))
        self.wait(2)
        self.play(Write(b2_l2))
        self.wait(2.5)
        b2_l3 = MathTex(r"\text{Year 1 balance: } 3\;000 + 240 = \text{R}3\;240").scale(1.1).shift(band_shift(2) + DOWN * 0.8)
        self.play(Write(b2_l3))
        self.play(Create(SurroundingRectangle(b2_l3, color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_2): year two grows from the NEW balance ---
        self.next_band(3)
        b3_t = Tex("Year 2: 8\\% of the NEW balance").scale(1.15).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t))
        self.wait(1.5)
        b3_l1 = MathTex(r"1\% \text{ of } 3\;240 = 32{,}40").scale(1.1).shift(band_shift(3) + UP * 1.1)
        b3_l2 = MathTex(r"8 \times 32{,}40 = \text{R}259{,}20").scale(1.1).shift(band_shift(3) + UP * 0.2)
        b3_l3 = MathTex(r"3\;240 + 259{,}20 = \text{R}3\;499{,}20").scale(1.1).shift(band_shift(3) + DOWN * 0.7)
        self.play(Write(b3_l1))
        self.wait(2)
        self.play(Write(b3_l2))
        self.wait(2)
        self.play(Write(b3_l3))
        self.play(Create(SurroundingRectangle(b3_l3, color=GREEN)))
        self.wait(2.5)
        b3_l4 = Tex("R259,20 beats R240: interest on interest").scale(1.05).shift(band_shift(3) + DOWN * 1.7)
        b3_l5 = Tex("Withdraw each year: R480 vs R499,20 left in").scale(1.0).shift(band_shift(3) + DOWN * 2.7)
        self.play(Write(b3_l4))
        self.wait(2.5)
        self.play(Write(b3_l5))
        self.wait(3)

        # --- Band 4 (subtopic_3): the bank loan ---
        self.next_band(4)
        b4_t = Tex("Sipho borrows R3 000 at 20\\% per year").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(1.5)
        b4_l1 = MathTex(r"\text{Interest: } 0{,}20 \times 3\;000 = \text{R}600").scale(1.1).shift(band_shift(4) + UP * 1.1)
        b4_l2 = MathTex(r"\text{Repay: } 3\;000 + 600 = \text{R}3\;600").scale(1.1).shift(band_shift(4) + UP * 0.1)
        self.play(Write(b4_l1))
        self.wait(2.5)
        self.play(Write(b4_l2))
        self.play(Create(SurroundingRectangle(b4_l2, color=GREEN)))
        self.wait(2.5)
        b4_l3 = Tex("Percentage of principal, added on — that is all").scale(1.0).shift(band_shift(4) + DOWN * 1.0)
        self.play(Write(b4_l3))
        self.wait(3)

        # --- Band 5 (subtopic_3): the mashonisa trap ---
        self.next_band(5)
        b5_t = Tex("The mashonisa: 30\\% PER MONTH").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_t))
        self.wait(1.5)
        b5_l1 = MathTex(r"\text{Per month: } 0{,}30 \times 3\;000 = \text{R}900").scale(1.1).shift(band_shift(5) + UP * 1.1)
        b5_l2 = MathTex(r"\text{3 months: } 3 \times 900 = \text{R}2\;700").scale(1.1).shift(band_shift(5) + UP * 0.2)
        b5_l3 = Tex("...and the R3 000 principal is STILL owed").scale(1.05).shift(band_shift(5) + DOWN * 0.7)
        self.play(Write(b5_l1))
        self.wait(2.5)
        self.play(Write(b5_l2))
        self.wait(2.5)
        self.play(Write(b5_l3))
        self.wait(2.5)
        b5_l4 = MathTex(r"30\% \times 12 = 360\% \text{ per year vs } 20\%").scale(1.05).shift(band_shift(5) + DOWN * 1.7)
        self.play(Write(b5_l4))
        self.wait(2)
        b5_rule = Tex("A rate means nothing without its time period").scale(1.05).shift(band_shift(5) + DOWN * 2.7)
        self.play(Write(b5_rule))
        self.play(Create(SurroundingRectangle(b5_rule, color=GREEN)))
        self.wait(3)

        # --- Band 6 (subtopic_4): running it backwards — find the rate ---
        self.next_band(6)
        b6_t = Tex("Backwards: R450 interest on R3 000 — the rate?").scale(1.1).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_t))
        self.wait(1.5)
        b6_wrong = MathTex(r"450 \div 3\;450 \approx 13\% \text{ (repayment!)}").scale(1.05).shift(band_shift(6) + UP * 1.1)
        self.play(Write(b6_wrong))
        self.play(Create(strike(b6_wrong)))
        self.wait(2)
        b6_l1 = MathTex(r"\text{Rate} = \frac{\text{interest}}{\text{principal}} \times 100").scale(1.1).shift(band_shift(6) + UP * 0.0)
        b6_l2 = MathTex(r"450 \div 3\;000 = 0{,}15").scale(1.1).shift(band_shift(6) + DOWN * 1.0)
        b6_l3 = MathTex(r"0{,}15 \times 100 = 15\% \text{ per year}").scale(1.1).shift(band_shift(6) + DOWN * 1.9)
        self.play(Write(b6_l1))
        self.wait(2.5)
        self.play(Write(b6_l2))
        self.wait(2)
        self.play(Write(b6_l3))
        self.play(Create(SurroundingRectangle(b6_l3, color=GREEN)))
        b6_rule = Tex("Divide by the PRINCIPAL, never the repayment").scale(1.0).shift(band_shift(6) + DOWN * 2.9)
        self.play(Write(b6_rule))
        self.wait(3)

        # --- Band 7 (subtopic_4): the full method ---
        self.next_band(7)
        b7_t = Tex("Method for any interest question").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(1.5)
        b7_l1 = Tex("1. Principal, rate, period — per year or month?").scale(1.0).shift(band_shift(7) + UP * 1.1)
        b7_l2 = Tex("2. Direction: earned by saver or paid by borrower?").scale(1.0).shift(band_shift(7) + UP * 0.2)
        b7_l3 = Tex("3. One period's interest = \\% of CURRENT balance").scale(1.0).shift(band_shift(7) + DOWN * 0.7)
        b7_l4 = Tex("4. Move one period at a time — does it stay in?").scale(1.0).shift(band_shift(7) + DOWN * 1.6)
        b7_l5 = Tex("5. Answer what was asked: interest, balance, rate").scale(1.0).shift(band_shift(7) + DOWN * 2.5)
        self.play(Write(b7_l1))
        self.wait(2)
        self.play(Write(b7_l2))
        self.wait(2)
        self.play(Write(b7_l3))
        self.wait(2)
        self.play(Write(b7_l4))
        self.wait(2)
        self.play(Write(b7_l5))
        self.play(Create(SurroundingRectangle(b7_l3, color=GREEN)))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): renting money ---
        self.next_band(8)
        b8_t = Tex("Interest is rent on money").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_t))
        self.wait(2)
        b8_l1 = Tex("Borrow R3 000: rent is 20\\% = R600").scale(1.05).shift(band_shift(8) + UP * 1.1)
        b8_l2 = MathTex(r"\text{Return } 3\;000 + 600 = \text{R}3\;600").scale(1.05).shift(band_shift(8) + UP * 0.2)
        self.play(Write(b8_l1))
        self.wait(2.5)
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = Tex("Save R3 000: the bank rents YOUR money — R240").scale(1.0).shift(band_shift(8) + DOWN * 0.8)
        self.play(Write(b8_l3))
        self.wait(2.5)
        b8_l4 = Tex("Rate = the price tag (\\%) \\quad Interest = the rent (R)").scale(1.0).shift(band_shift(8) + DOWN * 1.8)
        self.play(Write(b8_l4))
        self.play(Create(SurroundingRectangle(b8_l4, color=GREEN)))
        self.wait(3)

        # --- Band 9 (subtopic_6): the snowball ---
        self.next_band(9)
        b9_t = Tex("The snowball in the savings account").scale(1.15).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(2)
        b9_l1 = MathTex(r"\text{Year 1: } +\text{R}240 \Rightarrow \text{R}3\;240").scale(1.05).shift(band_shift(9) + UP * 1.1)
        b9_l2 = MathTex(r"\text{Year 2: } 8\% \text{ of } 3\;240 = \text{R}259{,}20").scale(1.05).shift(band_shift(9) + UP * 0.2)
        b9_l3 = MathTex(r"\text{Ball now: } \text{R}3\;499{,}20").scale(1.05).shift(band_shift(9) + DOWN * 0.7)
        self.play(Write(b9_l1))
        self.wait(2.5)
        self.play(Write(b9_l2))
        self.wait(2.5)
        self.play(Write(b9_l3))
        self.play(Create(SurroundingRectangle(b9_l3, color=GREEN)))
        self.wait(2.5)
        b9_l4 = Tex("Spending it each year: R480 vs R499,20").scale(1.0).shift(band_shift(9) + DOWN * 1.7)
        b9_l5 = Tex("Measure the ball as it is NOW, not at the start").scale(1.0).shift(band_shift(9) + DOWN * 2.7)
        self.play(Write(b9_l4))
        self.wait(2.5)
        self.play(Write(b9_l5))
        self.wait(3)

        # --- Band 10 (subtopic_7): which loan hurts less ---
        self.next_band(10)
        b10_t = Tex("Which loan hurts less?").scale(1.2).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_t))
        self.wait(2)
        b10_l1 = Tex("Bank: 20\\% PER YEAR \\quad Mashonisa: 30\\% PER MONTH").scale(0.88).shift(band_shift(10) + UP * 1.1)
        self.play(Write(b10_l1))
        self.wait(2.5)
        b10_l2 = Tex("Bank's rent for a YEAR: R600").scale(1.05).shift(band_shift(10) + UP * 0.2)
        b10_l3 = Tex("Mashonisa's rent for ONE MONTH: R900").scale(1.05).shift(band_shift(10) + DOWN * 0.7)
        self.play(Write(b10_l2))
        self.wait(2)
        self.play(Write(b10_l3))
        self.wait(2.5)
        b10_l4 = MathTex(r"\text{3 months: R}2\;700 \text{ paid, R}3\;000 \text{ still owed}").scale(0.95).shift(band_shift(10) + DOWN * 1.7)
        self.play(Write(b10_l4))
        self.wait(2.5)
        b10_ans = Tex("Same period first: 360\\% vs 20\\% per year").scale(1.0).shift(band_shift(10) + DOWN * 2.7)
        self.play(Write(b10_ans))
        self.play(Create(SurroundingRectangle(b10_ans, color=GREEN)))
        self.wait(4)
