from manim import *

# Band-layout whiteboard scene for the Paper 1 Practice Run session (Finance
# and Data Handling, 150 marks, walked question by question). One band per
# teaching beat; the camera moves down and earlier work stays on the canvas.
# Exporter-supported mobjects only; every working line is its own
# single-string Tex/MathTex revealed with Write. No transforms, no FadeOut.
#
# Subtopic time shares (subtopics.json, total 900 s):
# 150/105/110/120/135/160/120 -> bands 0-1 / 2 / 3 / 4-5 / 6-7 / 8-9 / 10.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class Paper1PracticeRunSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic full-screen while intro.md audio plays.
        self.wait(13)

        # --- Band 0 (subtopic_1): the architecture of Paper 1
        title = Tex("Paper 1 Practice Run: 150 Marks").scale(1.25).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex("Q1: about 30 marks, Level 1 ONLY").scale(1.05).shift(UP * 1.2)
        b0_l2 = Tex("Q2 Finance; Q3 Data Handling").scale(1.05).shift(UP * 0.4)
        b0_l3 = Tex("Q4--5 integrate the two families").scale(1.05).shift(DOWN * 0.4)
        b0_l4 = Tex("Probability's 7 marks hide anywhere").scale(1.05).shift(DOWN * 1.2)
        self.play(Write(b0_l1))
        self.wait(2)
        self.play(Write(b0_l2))
        self.wait(2)
        self.play(Write(b0_l3))
        self.wait(2)
        self.play(Write(b0_l4))
        self.wait(2)
        b0_l5 = MathTex(r"\text{Taxonomy: } 30\% + 30\% + 20\% + 20\%").scale(1.05).shift(DOWN * 2.2)
        self.play(Write(b0_l5))
        self.wait(3)

        # --- Band 1 (subtopic_1): the mark allocation is the instruction
        self.next_band(1)
        b1_t = Tex("Read the mark allocation as an instruction").scale(1.1).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_t))
        self.wait(1.5)
        b1_l1 = Tex("2 marks: one method mark, one answer mark").scale(1.05).shift(band_shift(1) + UP * 1.1)
        b1_l2 = Tex("3 marks: a hidden middle step (a conversion)").scale(1.05).shift(band_shift(1) + UP * 0.2)
        b1_l3 = Tex("5 marks and up: a staged journey — each stage pays").scale(1.0).shift(band_shift(1) + DOWN * 0.7)
        self.play(Write(b1_l1))
        self.wait(2)
        self.play(Write(b1_l2))
        self.wait(2)
        self.play(Write(b1_l3))
        self.wait(2)
        b1_l4 = Tex("Consistent accuracy: wrong numbers carried").scale(1.05).shift(band_shift(1) + DOWN * 1.7)
        b1_l5 = Tex("forward correctly KEEP paying — never stop").scale(1.05).shift(band_shift(1) + DOWN * 2.4)
        self.play(Write(b1_l4))
        self.play(Write(b1_l5))
        self.play(Create(SurroundingRectangle(VGroup(b1_l4, b1_l5), color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): Question 1 warm-ups, four specimens
        self.next_band(2)
        b2_t = Tex("Question 1: the confidence deposit").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(1.5)
        b2_l1 = MathTex(r"\text{VAT: } 240 \times 0{,}15 = \text{R}36{,}00; \;\text{total R}276{,}00").scale(1.0).shift(band_shift(2) + UP * 1.1)
        b2_l2 = MathTex(r"\text{Net pay: } 15\;800 - 3\;240 = \text{R}12\;560{,}00").scale(1.0).shift(band_shift(2) + UP * 0.2)
        b2_l3 = MathTex(r"\text{Mode of } 12, 15, 15, 18, 21: \;\; 15").scale(1.05).shift(band_shift(2) + DOWN * 0.8)
        b2_l4 = MathTex(r"P(\text{six}) = \tfrac{1}{6}").scale(1.1).shift(band_shift(2) + DOWN * 1.8)
        self.play(Write(b2_l1))
        self.wait(2.5)
        self.play(Write(b2_l2))
        self.wait(2)
        self.play(Write(b2_l3))
        self.wait(2)
        self.play(Write(b2_l4))
        self.wait(2)
        b2_l5 = Tex("Show the one line even for two marks").scale(1.05).shift(band_shift(2) + DOWN * 2.8)
        self.play(Write(b2_l5))
        self.wait(3)

        # --- Band 3 (subtopic_3): the municipal water bill, six marks
        self.next_band(3)
        b3_t = Tex("Q2.1 The water bill: a staircase, not a switch").scale(1.05).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t))
        self.wait(1.5)
        b3_l1 = MathTex(r"\text{First 6 k}\ell \text{ free: R}0{,}00").scale(1.0).shift(band_shift(3) + UP * 1.2)
        b3_l2 = MathTex(r"\text{7 to 15: } 9 \times 18 = \text{R}162{,}00").scale(1.0).shift(band_shift(3) + UP * 0.4)
        b3_l3 = MathTex(r"\text{16 to 22: } 7 \times 26 = \text{R}182{,}00").scale(1.0).shift(band_shift(3) + DOWN * 0.4)
        b3_l4 = MathTex(r"162 + 182 = \text{R}344{,}00").scale(1.0).shift(band_shift(3) + DOWN * 1.2)
        b3_l5 = MathTex(r"\text{VAT: } 344 \times 1{,}15 = \text{R}395{,}60").scale(1.05).shift(band_shift(3) + DOWN * 2.0)
        self.play(Write(b3_l1))
        self.wait(2)
        self.play(Write(b3_l2))
        self.wait(2)
        self.play(Write(b3_l3))
        self.wait(2)
        self.play(Write(b3_l4))
        self.wait(1.5)
        self.play(Write(b3_l5))
        self.play(Create(SurroundingRectangle(b3_l5, color=GREEN)))
        self.wait(2)
        b3_l6 = MathTex(r"22 \times 26 \; \text{ — all at the top rate: never}").scale(0.95).shift(band_shift(3) + DOWN * 2.9)
        self.play(Write(b3_l6))
        self.play(Create(strike(b3_l6)))
        self.wait(3)

        # --- Band 4 (subtopic_4): compound interest year by year
        self.next_band(4)
        b4_t = Tex("Q2.2 Compound interest: show the compounding").scale(1.0).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(1.5)
        b4_l1 = Tex(r"R12 000 at 8,5\% a year, three years").scale(1.05).shift(band_shift(4) + UP * 1.2)
        b4_l2 = MathTex(r"\text{Year 1: } 12\;000 \times 1{,}085 = \text{R}13\;020{,}00").scale(1.0).shift(band_shift(4) + UP * 0.3)
        b4_l3 = MathTex(r"\text{Year 2: } 13\;020 \times 1{,}085 = \text{R}14\;126{,}70").scale(1.0).shift(band_shift(4) + DOWN * 0.6)
        b4_l4 = MathTex(r"\text{Year 3: } 14\;126{,}70 \times 1{,}085 = \text{R}15\;327{,}47").scale(1.0).shift(band_shift(4) + DOWN * 1.5)
        self.play(Write(b4_l1))
        self.wait(2)
        self.play(Write(b4_l2))
        self.wait(2)
        self.play(Write(b4_l3))
        self.wait(2)
        self.play(Write(b4_l4))
        self.play(Create(SurroundingRectangle(b4_l4, color=GREEN)))
        self.wait(2.5)
        b4_l5 = Tex("Each year's interest lands on the NEW balance").scale(1.0).shift(band_shift(4) + DOWN * 2.6)
        self.play(Write(b4_l5))
        self.wait(3)

        # --- Band 5 (subtopic_4): interest earned, and compound vs simple
        self.next_band(5)
        b5_t = Tex("The follow-ups the paper loves").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_t))
        self.wait(1.5)
        b5_l1 = MathTex(r"\text{Interest: } 15\;327{,}47 - 12\;000 = \text{R}3\;327{,}47").scale(1.0).shift(band_shift(5) + UP * 1.1)
        b5_l2 = MathTex(r"\text{Simple: } 12\;000 \times 0{,}085 = \text{R}1\;020 \text{ per year}").scale(1.0).shift(band_shift(5) + UP * 0.2)
        b5_l3 = MathTex(r"3 \times 1\;020 = \text{R}3\;060{,}00").scale(1.05).shift(band_shift(5) + DOWN * 0.7)
        b5_l4 = MathTex(r"\text{Compound wins by R}267{,}47").scale(1.05).shift(band_shift(5) + DOWN * 1.6)
        self.play(Write(b5_l1))
        self.wait(2.5)
        self.play(Write(b5_l2))
        self.wait(2)
        self.play(Write(b5_l3))
        self.wait(2)
        self.play(Write(b5_l4))
        self.play(Create(SurroundingRectangle(b5_l4, color=GREEN)))
        self.wait(2)
        b5_l5 = Tex("...because later interest grows on interest —").scale(1.0).shift(band_shift(5) + DOWN * 2.5)
        b5_l6 = Tex("the explanation mark needs that clause").scale(1.0).shift(band_shift(5) + DOWN * 3.2)
        self.play(Write(b5_l5))
        self.play(Write(b5_l6))
        self.wait(3)

        # --- Band 6 (subtopic_5): summarising the test marks
        self.next_band(6)
        b6_t = Tex("Q3 Data: twelve learners' percentages").scale(1.1).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_t))
        self.wait(1.5)
        b6_l1 = MathTex(r"38, 42, 47, 51, 54, 56, 60, 63, 67, 71, 76, 83").scale(0.95).shift(band_shift(6) + UP * 1.2)
        b6_l2 = MathTex(r"\text{Range: } 83 - 38 = 45").scale(1.05).shift(band_shift(6) + UP * 0.3)
        b6_l3 = MathTex(r"\text{Mean: } 708 \div 12 = 59{,}0").scale(1.05).shift(band_shift(6) + DOWN * 0.6)
        b6_l4 = MathTex(r"\text{Median (even count): } \tfrac{56 + 60}{2} = 58{,}0").scale(1.05).shift(band_shift(6) + DOWN * 1.6)
        self.play(Write(b6_l1))
        self.wait(2.5)
        self.play(Write(b6_l2))
        self.wait(2)
        self.play(Write(b6_l3))
        self.wait(2)
        self.play(Write(b6_l4))
        self.play(Create(SurroundingRectangle(b6_l4, color=GREEN)))
        self.wait(2)
        b6_l5 = Tex("Picking one middle value forfeits the marks").scale(1.0).shift(band_shift(6) + DOWN * 2.6)
        self.play(Write(b6_l5))
        self.wait(3)

        # --- Band 7 (subtopic_5): quartiles, IQR and the honest comment
        self.next_band(7)
        b7_t = Tex("Quartiles and the reasoning rand").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(1.5)
        b7_l1 = MathTex(r"Q_1 = \tfrac{47 + 51}{2} = 49{,}0 \qquad Q_3 = \tfrac{67 + 71}{2} = 69{,}0").scale(1.0).shift(band_shift(7) + UP * 1.1)
        b7_l2 = MathTex(r"IQR = 69 - 49 = 20").scale(1.1).shift(band_shift(7) + UP * 0.1)
        self.play(Write(b7_l1))
        self.wait(2.5)
        self.play(Write(b7_l2))
        self.play(Create(SurroundingRectangle(b7_l2, color=GREEN)))
        self.wait(2.5)
        b7_l3 = Tex("Comment WITH calculations:").scale(1.05).shift(band_shift(7) + DOWN * 0.9)
        b7_l4 = Tex("mean 59 and median 58 agree — no outlier pull —").scale(1.0).shift(band_shift(7) + DOWN * 1.7)
        b7_l5 = Tex("but a quarter of the class scored below 49").scale(1.0).shift(band_shift(7) + DOWN * 2.5)
        self.play(Write(b7_l3))
        self.wait(1.5)
        self.play(Write(b7_l4))
        self.wait(2)
        self.play(Write(b7_l5))
        self.wait(3)

        # --- Band 8 (subtopic_6): integrated question — chance and budget
        self.next_band(8)
        b8_t = Tex("Q4 Integrated: data, money, chance").scale(1.1).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_t))
        self.wait(1.5)
        b8_l1 = MathTex(r"P(\text{below } 50) = \tfrac{3}{12} = \tfrac{1}{4} = 0{,}25").scale(1.05).shift(band_shift(8) + UP * 1.1)
        self.play(Write(b8_l1))
        self.wait(2.5)
        b8_l2 = MathTex(r"\text{Costs: } 200 \times 6{,}50 = \text{R}1\;300{,}00").scale(1.0).shift(band_shift(8) + UP * 0.2)
        b8_l3 = MathTex(r"\text{Income: } 200 \times 10 = \text{R}2\;000; \; \text{profit R}700{,}00").scale(1.0).shift(band_shift(8) + DOWN * 0.7)
        b8_l4 = MathTex(r"\text{Only } 85\% \text{ sell: } 170 \times 10 = \text{R}1\;700{,}00").scale(1.0).shift(band_shift(8) + DOWN * 1.6)
        b8_l5 = MathTex(r"\text{Profit falls to } 1\;700 - 1\;300 = \text{R}400{,}00").scale(1.0).shift(band_shift(8) + DOWN * 2.5)
        self.play(Write(b8_l2))
        self.wait(2)
        self.play(Write(b8_l3))
        self.wait(2)
        self.play(Write(b8_l4))
        self.wait(2)
        self.play(Write(b8_l5))
        self.play(Create(SurroundingRectangle(b8_l5, color=GREEN)))
        self.wait(3)

        # --- Band 9 (subtopic_6): the Level 4 advice close
        self.next_band(9)
        b9_t = Tex("Advise with the number, not opinion").scale(1.15).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(1.5)
        b9_l1 = MathTex(r"\text{Target R}650: \; 400 \text{ falls R}250 \text{ short}").scale(1.05).shift(band_shift(9) + UP * 1.1)
        b9_l2 = MathTex(r"170p - 1\;300 = 650").scale(1.1).shift(band_shift(9) + UP * 0.1)
        b9_l3 = MathTex(r"p = 1\;950 \div 170 = 11{,}4706").scale(1.05).shift(band_shift(9) + DOWN * 0.9)
        b9_l4 = MathTex(r"\text{Round UP: R}11{,}48").scale(1.1).shift(band_shift(9) + DOWN * 1.9)
        self.play(Write(b9_l1))
        self.wait(2.5)
        self.play(Write(b9_l2))
        self.wait(2)
        self.play(Write(b9_l3))
        self.wait(2)
        self.play(Write(b9_l4))
        self.play(Create(SurroundingRectangle(b9_l4, color=GREEN)))
        self.wait(2)
        b9_l5 = Tex("R11,47 banks R1 949,90 — ten cents short").scale(1.0).shift(band_shift(9) + DOWN * 2.9)
        self.play(Write(b9_l5))
        self.wait(3)

        # --- Band 10 (subtopic_7): the five memo habits
        self.next_band(10)
        b10_t = Tex("Five memo habits that harvest marks").scale(1.15).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_t))
        self.wait(1.5)
        b10_l1 = Tex("1. Show substitution — structure banks the mark").scale(1.0).shift(band_shift(10) + UP * 1.2)
        b10_l2 = Tex("2. Consistent accuracy — finish every chain").scale(1.0).shift(band_shift(10) + UP * 0.4)
        b10_l3 = Tex("3. Units and form — R, two decimals, comma").scale(1.0).shift(band_shift(10) + DOWN * 0.4)
        b10_l4 = Tex("4. Round for the context, only at the end").scale(1.0).shift(band_shift(10) + DOWN * 1.2)
        b10_l5 = Tex("5. Answer the verb — advise needs a number").scale(1.0).shift(band_shift(10) + DOWN * 2.0)
        self.play(Write(b10_l1))
        self.wait(2.5)
        self.play(Write(b10_l2))
        self.wait(2.5)
        self.play(Write(b10_l3))
        self.wait(2.5)
        self.play(Write(b10_l4))
        self.wait(2.5)
        self.play(Write(b10_l5))
        self.wait(2)
        b10_l6 = Tex("The cheapest ten marks in the examination").scale(1.05).shift(band_shift(10) + DOWN * 2.9)
        self.play(Write(b10_l6))
        self.play(Create(SurroundingRectangle(b10_l6, color=GREEN)))
        self.wait(4)
