from manim import *

# Band-layout whiteboard scene for the CAPS Grade 10 Accounting session duo
# "Bookkeeping Cycle Essentials" (revision). Add-only lifecycle, one band per
# teaching beat, camera moves down between bands. Covers all seven subtopics:
# Part 1 Expert (subtopics 1-4), Part 2 Simplifier (subtopics 5-7) in fresh
# bands. subtopics.json durations 220/220/220/220/180/190/190 of 1440 s.
# The debtors control check is drawn as true T-account rails (Lines) with
# entries posted in script order and the balance boxed last.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class BookkeepingCycleSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): the equation and the compass
        title = Tex("The Bookkeeping Cycle").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = MathTex(r"\text{Assets} = \text{Owner's equity} + \text{Liabilities}").scale(1.1).shift(UP * 1.2)
        self.play(Write(b0_l1))
        self.play(Create(SurroundingRectangle(b0_l1, color=GREEN)))
        self.wait(2.5)
        b0_l2 = Tex("Every transaction: a debit and a credit, equal").scale(1.0).shift(UP * 0.2)
        self.play(Write(b0_l2))
        self.wait(2.5)
        b0_l3 = Tex("Debit side: assets, expenses, drawings increase").scale(0.95).shift(DOWN * 0.7)
        b0_l4 = Tex("Credit side: equity, liabilities, income increase").scale(0.95).shift(DOWN * 1.5)
        self.play(Write(b0_l3))
        self.play(Write(b0_l4))
        self.wait(2.5)
        b0_l5 = Tex("Capital deposit R10 000: debit Bank,").scale(0.95).shift(DOWN * 2.4)
        b0_l6 = Tex("credit Capital — the equation stays level").scale(0.95).shift(DOWN * 3.1)
        self.play(Write(b0_l5))
        self.play(Write(b0_l6))
        self.wait(3)

        # --- Band 1 (subtopic_2): six journals, six documents
        self.next_band(1)
        b1_title = Tex("Six journals, six doors").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(2)
        b1_l1 = Tex("Cash in — CRJ (receipts, till tapes)").scale(0.95).shift(band_shift(1) + UP * 1.2)
        self.play(Write(b1_l1))
        self.wait(2)
        b1_l2 = Tex("Cash out — CPJ (EFT records)").scale(0.95).shift(band_shift(1) + UP * 0.5)
        self.play(Write(b1_l2))
        self.wait(2)
        b1_l3 = Tex("Credit sales — DJ (duplicate invoices);").scale(0.95).shift(band_shift(1) + DOWN * 0.2)
        b1_l4 = Tex("returns in — DAJ (credit notes)").scale(0.95).shift(band_shift(1) + DOWN * 0.9)
        self.play(Write(b1_l3))
        self.play(Write(b1_l4))
        self.wait(2.5)
        b1_l5 = Tex("Credit purchases — CJ; returns out — CAJ").scale(0.95).shift(band_shift(1) + DOWN * 1.7)
        self.play(Write(b1_l5))
        self.wait(2)
        b1_l6 = Tex("Everything else — the General Journal").scale(0.95).shift(band_shift(1) + DOWN * 2.5)
        self.play(Write(b1_l6))
        self.wait(3)

        # --- Band 2 (subtopic_2): the month recorded, door by door
        self.next_band(2)
        b2_title = Tex("Thabo's month, recorded").scale(1.2).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(2)
        b2_l1 = MathTex(r"\text{CRJ: sales } 6\,900, \text{ cost } 4\,600 \; (4\,600 \times 1{,}5)").scale(0.95).shift(band_shift(2) + UP * 1.2)
        self.play(Write(b2_l1))
        self.wait(2.5)
        b2_l2 = Tex("DJ: Mrs Dube R2 400, cost R1 600").scale(0.95).shift(band_shift(2) + UP * 0.4)
        self.play(Write(b2_l2))
        self.wait(2)
        b2_l3 = Tex("CPJ: stock 5 000, rent 1 500, wages 800").scale(0.95).shift(band_shift(2) + DOWN * 0.4)
        self.play(Write(b2_l3))
        self.wait(2)
        b2_l4 = Tex("CJ: wholesaler R3 000").scale(0.95).shift(band_shift(2) + DOWN * 1.2)
        self.play(Write(b2_l4))
        self.wait(2)
        b2_l5 = Tex("DAJ: return R300 (cost R200); CRJ: paid R1 000;").scale(0.9).shift(band_shift(2) + DOWN * 2.0)
        b2_l6 = Tex("CPJ: wholesaler paid R2 000").scale(0.95).shift(band_shift(2) + DOWN * 2.8)
        self.play(Write(b2_l5))
        self.play(Write(b2_l6))
        self.wait(3)

        # --- Band 3 (subtopic_3): posting and balancing the ledger
        self.next_band(3)
        b3_title = Tex("Balancing the ledger").scale(1.2).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(2)
        b3_l1 = MathTex(r"\text{Bank: } 17\,900 - 9\,300 = 8\,600 \text{ Dr}").scale(1.0).shift(band_shift(3) + UP * 1.2)
        self.play(Write(b3_l1))
        self.wait(2.5)
        b3_l2 = MathTex(r"\text{Stock: } 8\,200 - 6\,200 = 2\,000 \text{ Dr}").scale(1.0).shift(band_shift(3) + UP * 0.4)
        self.play(Write(b3_l2))
        self.wait(2.5)
        b3_l3 = MathTex(r"\text{Debtors: } 2\,400 - 300 - 1\,000 = 1\,100 \text{ Dr}").scale(0.95).shift(band_shift(3) + DOWN * 0.4)
        self.play(Write(b3_l3))
        self.wait(2.5)
        b3_l4 = MathTex(r"\text{Creditors: } 3\,000 - 2\,000 = 1\,000 \text{ Cr}").scale(0.95).shift(band_shift(3) + DOWN * 1.2)
        self.play(Write(b3_l4))
        self.wait(2.5)
        b3_l5 = MathTex(r"\text{Sales } 9\,000 \text{ Cr}; \;\; \text{Cost of sales } 6\,000 \text{ Dr}").scale(0.95).shift(band_shift(3) + DOWN * 2.0)
        self.play(Write(b3_l5))
        self.wait(3)

        # --- Band 4 (subtopic_3): the trial balance and its blind spots
        self.next_band(4)
        b4_title = Tex("The trial balance — the month on a scale").scale(1.1).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(2)
        b4_l1 = Tex("Debits: 8 600 + 2 000 + 1 100").scale(0.95).shift(band_shift(4) + UP * 1.2)
        b4_l2 = Tex("+ 6 000 + 1 500 + 800 = R20 000").scale(0.95).shift(band_shift(4) + UP * 0.4)
        self.play(Write(b4_l1))
        self.play(Write(b4_l2))
        self.wait(2.5)
        b4_l3 = MathTex(r"\text{Credits: } 10\,000 + 9\,000 + 1\,000 = 20\,000").scale(0.95).shift(band_shift(4) + DOWN * 0.5)
        self.play(Write(b4_l3))
        self.play(Create(SurroundingRectangle(b4_l3, color=GREEN)))
        self.wait(2.5)
        b4_wrong = Tex("Level totals prove the books are fully correct").scale(0.95).shift(band_shift(4) + DOWN * 1.5)
        self.play(Write(b4_wrong))
        self.play(Create(strike(b4_wrong)))
        self.wait(2)
        b4_l4 = Tex("Blind to wrong-account postings and omissions —").scale(0.9).shift(band_shift(4) + DOWN * 2.4)
        b4_l5 = Tex("a strong test, not a perfect one").scale(0.95).shift(band_shift(4) + DOWN * 3.1)
        self.play(Write(b4_l4))
        self.play(Write(b4_l5))
        self.wait(3)

        # --- Band 5 (subtopic_4): the control account as a T-account
        self.next_band(5)
        b5_title = Tex("Debtors Control").scale(1.2).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(2)
        t_top = Line(LEFT * 4.0, RIGHT * 4.0).shift(band_shift(5) + UP * 1.5)
        t_stem = Line(UP * 1.5, DOWN * 1.4).shift(band_shift(5))
        self.play(Create(t_top), Create(t_stem))
        self.wait(1.5)
        b5_dr = Tex("Sales 2 400").scale(0.95).shift(band_shift(5) + UP * 0.7 + LEFT * 2.2)
        self.play(Write(b5_dr))
        self.wait(2)
        b5_cr1 = Tex("Allowances 300").scale(0.95).shift(band_shift(5) + UP * 0.7 + RIGHT * 2.2)
        b5_cr2 = Tex("Bank 1 000").scale(0.95).shift(band_shift(5) + DOWN * 0.1 + RIGHT * 2.2)
        self.play(Write(b5_cr1))
        self.wait(1.5)
        self.play(Write(b5_cr2))
        self.wait(2)
        b5_bal = MathTex(r"\text{Balance: } 2\,400 - 300 - 1\,000 = 1\,100").scale(1.0).shift(band_shift(5) + DOWN * 1.9)
        self.play(Write(b5_bal))
        self.play(Create(SurroundingRectangle(b5_bal, color=GREEN)))
        self.wait(2.5)
        b5_l1 = Tex("Mrs Dube's page says the same R1 100 — agreement").scale(0.9).shift(band_shift(5) + DOWN * 2.9)
        self.play(Write(b5_l1))
        self.wait(3)

        # --- Band 6 (subtopic_4): what the agreement catches
        self.next_band(6)
        b6_title = Tex("Two counts, facing each other").scale(1.2).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(2)
        b6_l1 = Tex("Control from journal TOTALS;").scale(1.0).shift(band_shift(6) + UP * 1.2)
        b6_l2 = Tex("the list from INDIVIDUAL postings").scale(1.0).shift(band_shift(6) + UP * 0.4)
        self.play(Write(b6_l1))
        self.play(Write(b6_l2))
        self.wait(2.5)
        b6_l3 = Tex("Wrong customer's page: list wrong, control right").scale(0.95).shift(band_shift(6) + DOWN * 0.5)
        self.play(Write(b6_l3))
        self.wait(2)
        b6_l4 = Tex("Journal total miscast: control wrong, list right").scale(0.95).shift(band_shift(6) + DOWN * 1.3)
        self.play(Write(b6_l4))
        self.wait(2)
        b6_l5 = Tex("Creditors mirror: 3 000 $-$ 2 000 = R1 000 both ways").scale(0.95).shift(band_shift(6) + DOWN * 2.2)
        self.play(Write(b6_l5))
        self.wait(2)
        b6_l6 = Tex("Internal control in miniature").scale(1.0).shift(band_shift(6) + DOWN * 3.0)
        self.play(Write(b6_l6))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 7 (subtopic_5): one slip, six boxes
        self.next_band(7)
        b7_title = Tex("One slip, six doors").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(2)
        b7_l1 = Tex("The shoebox: till tapes, invoices, credit notes").scale(0.95).shift(band_shift(7) + UP * 1.2)
        self.play(Write(b7_l1))
        self.wait(2.5)
        b7_l2 = Tex("Two questions sort every slip:").scale(1.0).shift(band_shift(7) + UP * 0.3)
        b7_l3 = Tex("cash or promise? which way did value travel?").scale(1.0).shift(band_shift(7) + DOWN * 0.5)
        self.play(Write(b7_l2))
        self.play(Write(b7_l3))
        self.play(Create(SurroundingRectangle(b7_l3, color=GREEN)))
        self.wait(2.5)
        b7_l4 = Tex("Till tape R6 900 — cash in. Dube's invoice").scale(0.95).shift(band_shift(7) + DOWN * 1.5)
        b7_l5 = Tex("R2 400 — promise, value out. Six tidy piles").scale(0.95).shift(band_shift(7) + DOWN * 2.3)
        self.play(Write(b7_l4))
        self.play(Write(b7_l5))
        self.wait(3)

        # --- Band 8 (subtopic_6): the month that adds up twice
        self.next_band(8)
        b8_title = Tex("The month that adds up twice").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = Tex("The ledger regroups by THING: bank page R8 600,").scale(0.95).shift(band_shift(8) + UP * 1.2)
        b8_l2 = Tex("stock R2 000, Mrs Dube R1 100").scale(0.95).shift(band_shift(8) + UP * 0.4)
        self.play(Write(b8_l1))
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = MathTex(r"\text{The weigh-in: } 20\,000 = 20\,000").scale(1.1).shift(band_shift(8) + DOWN * 0.6)
        self.play(Write(b8_l3))
        self.play(Create(SurroundingRectangle(b8_l3, color=GREEN)))
        self.wait(2.5)
        b8_l4 = Tex("The scale cannot smell wrong pages or a").scale(0.95).shift(band_shift(8) + DOWN * 1.6)
        b8_l5 = Tex("stolen slip — the first guard, not the only one").scale(0.95).shift(band_shift(8) + DOWN * 2.4)
        self.play(Write(b8_l4))
        self.play(Write(b8_l5))
        self.wait(3)

        # --- Band 9 (subtopic_7): counting the street twice
        self.next_band(9)
        b9_title = Tex("Counting the street twice").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex("Exercise book: a page per customer, slip by slip").scale(0.95).shift(band_shift(9) + UP * 1.2)
        self.play(Write(b9_l1))
        self.wait(2)
        b9_l2 = Tex("Main books: ONE total line, from journal totals").scale(0.95).shift(band_shift(9) + UP * 0.4)
        self.play(Write(b9_l2))
        self.wait(2.5)
        b9_l3 = Tex("Month-end: both counts say R1 100 — believable").scale(0.95).shift(band_shift(9) + DOWN * 0.5)
        self.play(Write(b9_l3))
        self.play(Create(SurroundingRectangle(b9_l3, color=GREEN)))
        self.wait(2.5)
        b9_l4 = Tex("Disagreement gives directions: the difference").scale(0.95).shift(band_shift(9) + DOWN * 1.5)
        b9_l5 = Tex("names the record that is wrong").scale(0.95).shift(band_shift(9) + DOWN * 2.3)
        self.play(Write(b9_l4))
        self.play(Write(b9_l5))
        self.wait(2.5)
        b9_l6 = Tex("Five habits, one machine — the whole year").scale(0.95).shift(band_shift(9) + DOWN * 3.1)
        self.play(Write(b9_l6))
        self.wait(4)
