from manim import *

# Band-layout whiteboard scene for the CAPS Grade 11 Term 2 duo
# "Financial Indicators and Interpretation" (partnership analysis).
# One band per teaching beat; camera moves down, nothing removed.
# Exporter-safe primitives only; every indicator is computed line by line
# with the script's exact figures. Subtopic shares:
# 220/240/230/230/190/200/195 of 1505 s.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class FinancialIndicatorsSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md audio plays.
        self.wait(15)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): gross margins against the policy ---
        title = Tex("Financial Indicators and Interpretation").scale(1.2).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = MathTex(r"\text{GP on sales: } \frac{820\,000}{2\,460\,000} = 33{,}3\%").scale(1.05).shift(UP * 0.9)
        self.play(Write(b0_l1))
        self.wait(2.5)
        b0_l2 = MathTex(r"\text{GP on cost: } \frac{820\,000}{1\,640\,000} = 50\%").scale(1.05).shift(DOWN * 0.4)
        self.play(Write(b0_l2))
        self.wait(2.5)
        b0_l3 = Tex(r"= the 50\% mark-up policy, exactly").scale(1.05).shift(DOWN * 1.5)
        self.play(Write(b0_l3))
        self.play(Create(SurroundingRectangle(b0_l3, color=GREEN)))
        self.wait(2)
        b0_l4 = Tex("No leaks, no hidden markdowns, no errors").scale(1.0).shift(DOWN * 2.4)
        self.play(Write(b0_l4))
        self.wait(3)

        # --- Band 1 (subtopic_1): the cascade, and the comparison rule ---
        self.next_band(1)
        b1_title = Tex("The cascade per rand of sales").scale(1.15).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l1 = Tex(r"Operating expenses: 441 000 / 2 460 000 = 17,9\%").scale(0.95).shift(band_shift(1) + UP * 1.1)
        self.play(Write(b1_l1))
        self.wait(2.5)
        b1_l2 = Tex(r"Operating profit: 439 000 / 2 460 000 = 17,8\%").scale(0.95).shift(band_shift(1) + UP * 0.3)
        self.play(Write(b1_l2))
        self.wait(2.5)
        b1_l3 = Tex(r"Net profit: 421 000 / 2 460 000 = 17,1\%").scale(0.95).shift(band_shift(1) + DOWN * 0.5)
        self.play(Write(b1_l3))
        self.play(Create(SurroundingRectangle(b1_l3, color=GREEN)))
        self.wait(2.5)
        b1_l4 = Tex("17,1 cents of every sales rand reaches").scale(1.0).shift(band_shift(1) + DOWN * 1.4)
        b1_l5 = Tex("the owners — but only comparison speaks:").scale(1.0).shift(band_shift(1) + DOWN * 2.1)
        b1_l6 = Tex("last year, budget, policy, rival").scale(1.0).shift(band_shift(1) + DOWN * 2.8)
        self.play(Write(b1_l4))
        self.play(Write(b1_l5))
        self.play(Write(b1_l6))
        self.wait(3)

        # --- Band 2 (subtopic_2): stock turnover and holding period ---
        self.next_band(2)
        b2_title = Tex("The operating cycle: the shelf").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(1.5)
        b2_l1 = MathTex(r"\text{Avg stock} = \frac{194\,800 + 185\,200}{2} = 190\,000").scale(1.0).shift(band_shift(2) + UP * 1.0)
        self.play(Write(b2_l1))
        self.wait(2.5)
        b2_l2 = MathTex(r"\text{Turnover: } \frac{1\,640\,000}{190\,000} = 8{,}6 \text{ times}").scale(1.0).shift(band_shift(2) + DOWN * 0.2)
        self.play(Write(b2_l2))
        self.wait(2.5)
        b2_l3 = Tex(r"Holding period: $\times$ 365 = 42,3 days").scale(1.05).shift(band_shift(2) + DOWN * 1.3)
        self.play(Write(b2_l3))
        self.play(Create(SurroundingRectangle(b2_l3, color=GREEN)))
        self.wait(2)
        b2_l4 = Tex("Same fact, two dialects: refills per year,").scale(0.95).shift(band_shift(2) + DOWN * 2.2)
        b2_l5 = Tex("or days per refill").scale(0.95).shift(band_shift(2) + DOWN * 2.9)
        self.play(Write(b2_l4))
        self.play(Write(b2_l5))
        self.wait(3)

        # --- Band 3 (subtopic_2): debtors, creditors, the cycle read together ---
        self.next_band(3)
        b3_title = Tex("Debtors, creditors, and the gap").scale(1.15).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(1.5)
        b3_l1 = Tex(r"Credit sales: 60\% $\times$ 2 460 000 = 1 476 000").scale(0.95).shift(band_shift(3) + UP * 1.2)
        self.play(Write(b3_l1))
        self.wait(2)
        b3_l2 = MathTex(r"\frac{54\,000}{1\,476\,000} \times 365 = 13{,}4 \text{ days}").scale(1.0).shift(band_shift(3) + UP * 0.3)
        self.play(Write(b3_l2))
        self.wait(2.5)
        b3_l3 = MathTex(r"\frac{83\,000}{1\,245\,000} \times 365 = 24{,}3 \text{ days}").scale(1.0).shift(band_shift(3) + DOWN * 0.9)
        self.play(Write(b3_l3))
        self.wait(2.5)
        b3_l4 = Tex("Money out 42 + 13 = 55 days; paid at 24").scale(1.0).shift(band_shift(3) + DOWN * 1.9)
        self.play(Write(b3_l4))
        self.play(Create(SurroundingRectangle(b3_l4, color=GREEN)))
        self.wait(2)
        b3_l5 = Tex("24 on 30-day terms: six free days given up").scale(0.95).shift(band_shift(3) + DOWN * 2.8)
        self.play(Write(b3_l5))
        self.wait(3)

        # --- Band 4 (subtopic_3): gearing, return, solvency ---
        self.next_band(4)
        b4_title = Tex("Risk and reward").scale(1.2).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(1.5)
        b4_l1 = Tex("Debt-equity: 138 000 : 765 800 = 0,2 : 1").scale(1.0).shift(band_shift(4) + UP * 1.2)
        self.play(Write(b4_l1))
        self.wait(2.5)
        b4_l2 = Tex(r"Low gearing — safe; but returns beat 12\%,").scale(0.95).shift(band_shift(4) + UP * 0.4)
        b4_l3 = Tex("so a case exists for gearing UP").scale(0.95).shift(band_shift(4) + DOWN * 0.3)
        self.play(Write(b4_l2))
        self.play(Write(b4_l3))
        self.wait(2.5)
        b4_l4 = MathTex(r"\text{ROE: } \frac{421\,000}{734\,300} = 57{,}3\%").scale(1.05).shift(band_shift(4) + DOWN * 1.3)
        self.play(Write(b4_l4))
        self.play(Create(SurroundingRectangle(b4_l4, color=GREEN)))
        self.wait(2.5)
        b4_l5 = Tex(r"vs 8-10\% risk-free — handsomely better,").scale(0.95).shift(band_shift(4) + DOWN * 2.3)
        b4_l6 = Tex("even pricing the partners' labour in").scale(0.95).shift(band_shift(4) + DOWN * 3.0)
        self.play(Write(b4_l5))
        self.play(Write(b4_l6))
        self.wait(3)

        # --- Band 5 (subtopic_4): liquidity, and over-liquidity ---
        self.next_band(5)
        b5_title = Tex("Liquidity: can the bills be paid?").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(1.5)
        b5_l1 = Tex("Current: 375 550 : 91 750 = 4,1 : 1").scale(1.05).shift(band_shift(5) + UP * 1.1)
        self.play(Write(b5_l1))
        self.wait(2.5)
        b5_l2 = Tex("Acid test: 190 350 : 91 750 = 2,1 : 1").scale(1.05).shift(band_shift(5) + UP * 0.2)
        self.play(Write(b5_l2))
        self.play(Create(SurroundingRectangle(b5_l2, color=GREEN)))
        self.wait(2.5)
        b5_l3 = Tex("Covered twice over without selling stock").scale(1.0).shift(band_shift(5) + DOWN * 0.7)
        self.play(Write(b5_l3))
        self.wait(2)
        b5_l4 = Tex("Arguably TOO healthy: R130 000 idle —").scale(1.0).shift(band_shift(5) + DOWN * 1.6)
        b5_l5 = Tex("expand, take discounts, or repay loan").scale(1.0).shift(band_shift(5) + DOWN * 2.3)
        self.play(Write(b5_l4))
        self.play(Write(b5_l5))
        self.wait(3)

        # --- Band 6 (subtopic_4): the four-part comment ---
        self.next_band(6)
        b6_title = Tex("The comment that earns full marks").scale(1.15).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(1.5)
        b6_l1 = Tex("1. FIGURE — quote it with its comparison").scale(1.0).shift(band_shift(6) + UP * 1.1)
        self.play(Write(b6_l1))
        self.wait(2)
        b6_l2 = Tex("2. TREND — improved, worsened, or beats").scale(1.0).shift(band_shift(6) + UP * 0.3)
        self.play(Write(b6_l2))
        self.wait(2)
        b6_l3 = Tex("3. CAUSE — a reason rooted in the business").scale(1.0).shift(band_shift(6) + DOWN * 0.5)
        self.play(Write(b6_l3))
        self.wait(2)
        b6_l4 = Tex("4. ADVICE — what the partners should do").scale(1.0).shift(band_shift(6) + DOWN * 1.3)
        self.play(Write(b6_l4))
        self.play(Create(SurroundingRectangle(b6_l4, color=GREEN)))
        self.wait(2)
        b6_wrong = Tex("A ratio quoted with no comparison?").scale(1.0).shift(band_shift(6) + DOWN * 2.2)
        self.play(Write(b6_wrong))
        self.play(Create(strike(b6_wrong)))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 7 (subtopic_5): reading the stats sheet ---
        self.next_band(7)
        b7_title = Tex("Reading the stats sheet").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(2)
        b7_l1 = Tex("Statements = the season;").scale(1.0).shift(band_shift(7) + UP * 1.1)
        b7_l2 = Tex("indicators = the stats sheet").scale(1.0).shift(band_shift(7) + UP * 0.4)
        self.play(Write(b7_l1))
        self.play(Write(b7_l2))
        self.wait(2.5)
        b7_l3 = Tex("Out of every R100 of sales, R33 stays").scale(1.0).shift(band_shift(7) + DOWN * 0.5)
        self.play(Write(b7_l3))
        self.wait(2.5)
        b7_l4 = Tex(r"Plan says 50\% on cost — the result matches").scale(1.0).shift(band_shift(7) + DOWN * 1.3)
        self.play(Write(b7_l4))
        self.wait(2.5)
        b7_l5 = Tex("Costs take 18; owners keep 17 of each 100").scale(1.0).shift(band_shift(7) + DOWN * 2.1)
        self.play(Write(b7_l5))
        self.wait(2)
        b7_l6 = Tex("A stat means nothing alone — find its NEXT TO").scale(0.95).shift(band_shift(7) + DOWN * 3.0)
        self.play(Write(b7_l6))
        self.play(Create(SurroundingRectangle(b7_l6, color=GREEN)))
        self.wait(3.5)

        # --- Band 8 (subtopic_6): the rhythm section ---
        self.next_band(8)
        b8_title = Tex("The rhythm section: one rand's lap").scale(1.15).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = Tex("Shelf: 8,6 refills a year — 42 days each").scale(1.0).shift(band_shift(8) + UP * 1.1)
        self.play(Write(b8_l1))
        self.wait(2.5)
        b8_l2 = Tex("Promises: debtors sprint home in 13,4 days").scale(1.0).shift(band_shift(8) + UP * 0.3)
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = Tex("Suppliers paid at 24,3 of 30 days —").scale(1.0).shift(band_shift(8) + DOWN * 0.5)
        b8_l4 = Tex("six days of free credit left unused").scale(1.0).shift(band_shift(8) + DOWN * 1.2)
        self.play(Write(b8_l3))
        self.play(Write(b8_l4))
        self.wait(3)
        b8_l5 = Tex("Out 42 + 13 = 55 days; funded from day 24").scale(1.0).shift(band_shift(8) + DOWN * 2.1)
        self.play(Write(b8_l5))
        self.play(Create(SurroundingRectangle(b8_l5, color=GREEN)))
        self.wait(2.5)
        b8_l6 = Tex("Tempo is judged against the trade's music").scale(0.95).shift(band_shift(8) + DOWN * 3.0)
        self.play(Write(b8_l6))
        self.wait(3.5)

        # --- Band 9 (subtopic_7): was it worth it? ---
        self.next_band(9)
        b9_title = Tex("Was it worth it?").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex("Survival: 4,1 cover; 2,1 without stock —").scale(1.0).shift(band_shift(9) + UP * 1.1)
        b9_l2 = Tex("safe, and slightly lazy (idle R130 000)").scale(1.0).shift(band_shift(9) + UP * 0.4)
        self.play(Write(b9_l1))
        self.play(Write(b9_l2))
        self.wait(3)
        b9_l3 = Tex(r"Risk: 0,2 : 1 — loan costs 12\%, business").scale(1.0).shift(band_shift(9) + DOWN * 0.5)
        b9_l4 = Tex("earns far more: a reason to borrow MORE").scale(1.0).shift(band_shift(9) + DOWN * 1.2)
        self.play(Write(b9_l3))
        self.play(Write(b9_l4))
        self.wait(3)
        b9_l5 = Tex(r"Reward: 57,3\% against the bank's 9\%").scale(1.05).shift(band_shift(9) + DOWN * 2.1)
        self.play(Write(b9_l5))
        self.play(Create(SurroundingRectangle(b9_l5, color=GREEN)))
        self.wait(2.5)
        b9_l6 = Tex("Four beats: figure, compared-to, cause, advice").scale(0.95).shift(band_shift(9) + DOWN * 3.0)
        self.play(Write(b9_l6))
        self.wait(4)
