from manim import *

# Band-layout whiteboard scene for the Perimeter and Area in Context session
# duo. One band per teaching beat, camera-only transitions, add-only
# lifecycle. Exporter-supported mobjects only: the plot is a Rectangle, the
# triangle is three Lines, the herb bed's flat side is a Line. Band time
# apportioned to subtopics.json (210/220/240/260/180/190/180 of 1480 s).

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class PerimeterAreaInContextSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): the plot — edge or inside? ---
        title = Tex("Perimeter and Area in Context").scale(1.25).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        plot = Rectangle(width=6.0, height=4.0).shift(LEFT * 3.2 + DOWN * 0.9)
        self.play(Create(plot))
        lab_l = Tex("12 m").scale(0.9).shift(LEFT * 3.2 + UP * 1.5)
        lab_w = Tex("8 m").scale(0.9).shift(LEFT * 6.6 + DOWN * 0.9)
        self.play(Write(lab_l), Write(lab_w))
        self.wait(2)
        b0_l1 = Tex("Edge or inside? Decide first").scale(1.0).shift(RIGHT * 3.4 + UP * 0.9)
        b0_l2 = MathTex(r"P = 2(12 + 8) = 40 \text{ m}").scale(1.0).shift(RIGHT * 3.4 + DOWN * 0.1)
        b0_l3 = MathTex(r"A = 12 \times 8 = 96 \text{ m}^2").scale(1.0).shift(RIGHT * 3.4 + DOWN * 1.1)
        self.play(Write(b0_l1))
        self.wait(2)
        self.play(Write(b0_l2))
        self.wait(2)
        self.play(Write(b0_l3))
        self.wait(3)

        # --- Band 1 (subtopic_1): the gate, and units as guards ---
        self.next_band(1)
        b1_t = Tex("Nobody fences a gateway").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_t))
        self.wait(1.5)
        b1_l1 = Tex("The gate is 1,5 m wide").scale(1.05).shift(band_shift(1) + UP * 1.1)
        b1_l2 = MathTex(r"\text{Fencing: } 40 - 1{,}5 = 38{,}5 \text{ m}").scale(1.1).shift(band_shift(1) + UP * 0.1)
        self.play(Write(b1_l1))
        self.wait(2)
        self.play(Write(b1_l2))
        self.play(Create(SurroundingRectangle(b1_l2, color=GREEN)))
        self.wait(2.5)
        b1_l3 = Tex("Perimeter answers in m; area in m$^2$").scale(1.05).shift(band_shift(1) + DOWN * 1.0)
        b1_l4 = Tex("Say the unit every time — it catches errors").scale(1.0).shift(band_shift(1) + DOWN * 1.9)
        self.play(Write(b1_l3))
        self.wait(2)
        self.play(Write(b1_l4))
        self.wait(3)

        # --- Band 2 (subtopic_2): the triangular seedling bed ---
        self.next_band(2)
        b2_t = Tex("Triangle: base 6 m, height 4 m").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(1.5)
        apex = band_shift(2) + LEFT * 2.9 + UP * 1.0
        bl = band_shift(2) + LEFT * 5.3 + DOWN * 1.6
        br = band_shift(2) + LEFT * 0.5 + DOWN * 1.6
        tri1 = Line(bl, br)
        tri2 = Line(bl, apex)
        tri3 = Line(br, apex)
        self.play(Create(tri1), Create(tri2), Create(tri3))
        hgt = DashedLine(apex, band_shift(2) + LEFT * 2.9 + DOWN * 1.6, color=YELLOW)
        self.play(Create(hgt))
        b2_lab = Tex("perpendicular height, not the slant").scale(0.85).shift(band_shift(2) + LEFT * 2.9 + DOWN * 2.3)
        self.play(Write(b2_lab))
        self.wait(2)
        b2_l1 = MathTex(r"A = \tfrac{1}{2} \times b \times h").scale(1.0).shift(band_shift(2) + RIGHT * 3.5 + UP * 0.6)
        b2_l2 = MathTex(r"= \tfrac{1}{2} \times 6 \times 4").scale(1.0).shift(band_shift(2) + RIGHT * 3.5 + DOWN * 0.3)
        b2_l3 = MathTex(r"= 12 \text{ m}^2").scale(1.05).shift(band_shift(2) + RIGHT * 3.5 + DOWN * 1.2)
        self.play(Write(b2_l1))
        self.wait(2)
        self.play(Write(b2_l2))
        self.wait(2)
        self.play(Write(b2_l3))
        self.play(Create(SurroundingRectangle(b2_l3, color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_2): the circle formulae, in order ---
        self.next_band(3)
        b3_t = Tex("The pond: radius 3,5 m, $\\pi = 3{,}142$").scale(1.1).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t))
        self.wait(1.5)
        b3_l0 = Tex("Diameter = 2 $\\times$ radius — halve it first!").scale(1.0).shift(band_shift(3) + UP * 1.2)
        self.play(Write(b3_l0))
        self.wait(2)
        b3_l1 = MathTex(r"C = 2 \times 3{,}142 \times 3{,}5 = 21{,}99 \text{ m}").scale(1.05).shift(band_shift(3) + UP * 0.2)
        self.play(Write(b3_l1))
        self.wait(2.5)
        b3_l2 = MathTex(r"A = 3{,}142 \times 3{,}5^2").scale(1.05).shift(band_shift(3) + DOWN * 0.7)
        b3_l3 = MathTex(r"= 3{,}142 \times 12{,}25 = 38{,}49 \text{ m}^2").scale(1.05).shift(band_shift(3) + DOWN * 1.6)
        self.play(Write(b3_l2))
        self.wait(2)
        self.play(Write(b3_l3))
        self.play(Create(SurroundingRectangle(b3_l3, color=GREEN)))
        self.wait(2)
        b3_rule = Tex("Square the radius BEFORE multiplying by $\\pi$").scale(1.0).shift(band_shift(3) + DOWN * 2.7)
        self.play(Write(b3_rule))
        self.wait(3)

        # --- Band 4 (subtopic_3): fractions of circles — area behaves ---
        self.next_band(4)
        b4_t = Tex("Herb bed, radius 2 m: area behaves").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(1.5)
        b4_l1 = MathTex(r"\text{Full circle: } 3{,}142 \times 2^2 = 12{,}568 \text{ m}^2").scale(1.0).shift(band_shift(4) + UP * 1.1)
        self.play(Write(b4_l1))
        self.wait(2.5)
        b4_l2 = MathTex(r"\text{Semicircle: } 12{,}568 \div 2 = 6{,}28 \text{ m}^2").scale(1.0).shift(band_shift(4) + UP * 0.2)
        b4_l3 = MathTex(r"\text{Quarter: } 3{,}142 \quad \text{Three-quarter: } 9{,}426").scale(1.0).shift(band_shift(4) + DOWN * 0.7)
        self.play(Write(b4_l2))
        self.wait(2.5)
        self.play(Write(b4_l3))
        self.wait(2)
        b4_rule = Tex("Area: take the fraction and stop").scale(1.05).shift(band_shift(4) + DOWN * 1.7)
        self.play(Write(b4_rule))
        self.play(Create(SurroundingRectangle(b4_rule, color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_3): the perimeter trap ---
        self.next_band(5)
        b5_t = Tex("Perimeter does NOT behave").scale(1.2).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_t))
        self.wait(1.5)
        b5_wrong = MathTex(r"\text{Semicircle edge} = 6{,}28 \text{ m only?}").scale(1.05).shift(band_shift(5) + UP * 1.1)
        self.play(Write(b5_wrong))
        self.play(Create(strike(b5_wrong)))
        self.wait(2)
        b5_l1 = MathTex(r"\text{Curved half: } 12{,}568 \div 2 = 6{,}284").scale(1.05).shift(band_shift(5) + UP * 0.1)
        b5_l2 = Tex("...but the walk ends where it began:").scale(1.0).shift(band_shift(5) + DOWN * 0.8)
        b5_l3 = MathTex(r"6{,}284 + 4 \text{ (diameter)} = 10{,}28 \text{ m}").scale(1.05).shift(band_shift(5) + DOWN * 1.7)
        self.play(Write(b5_l1))
        self.wait(2.5)
        self.play(Write(b5_l2))
        self.wait(2)
        self.play(Write(b5_l3))
        self.play(Create(SurroundingRectangle(b5_l3, color=GREEN)))
        self.wait(3)

        # --- Band 6 (subtopic_3): quarter and three-quarter walks ---
        self.next_band(6)
        b6_t = Tex("Quarter and three-quarter circles").scale(1.15).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_t))
        self.wait(1.5)
        b6_l1 = MathTex(r"\text{Quarter: } 3{,}142 + 2 + 2 = 7{,}14 \text{ m}").scale(1.05).shift(band_shift(6) + UP * 1.1)
        b6_l2 = Tex("(TWO straight edges — both radii)").scale(0.95).shift(band_shift(6) + UP * 0.2)
        self.play(Write(b6_l1))
        self.wait(2.5)
        self.play(Write(b6_l2))
        self.wait(2)
        b6_l3 = MathTex(r"\text{Three-quarter: } 9{,}426 + 4 = 13{,}43 \text{ m}").scale(1.05).shift(band_shift(6) + DOWN * 0.7)
        self.play(Write(b6_l3))
        self.wait(2.5)
        b6_rule = Tex("Fraction of the curve, then walk home").scale(1.0).shift(band_shift(6) + DOWN * 1.7)
        b6_rule2 = Tex("along the straight edges").scale(1.0).shift(band_shift(6) + DOWN * 2.4)
        self.play(Write(b6_rule))
        self.play(Write(b6_rule2))
        self.play(Create(SurroundingRectangle(b6_rule2, color=GREEN)))
        self.wait(3)

        # --- Band 7 (subtopic_4): pricing the fence ---
        self.next_band(7)
        b7_t = Tex("Price the fence: 10 m rolls at R350").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(1.5)
        b7_l1 = MathTex(r"38{,}5 \div 10 = 3{,}85 \text{ rolls}").scale(1.05).shift(band_shift(7) + UP * 1.1)
        self.play(Write(b7_l1))
        self.wait(2.5)
        b7_l2 = Tex("3 rolls = 30 m: an 8,5 m hole in the fence").scale(1.0).shift(band_shift(7) + UP * 0.2)
        self.play(Write(b7_l2))
        self.wait(2.5)
        b7_l3 = MathTex(r"\text{Round UP: } 4 \times \text{R}350 = \text{R}1\;400").scale(1.1).shift(band_shift(7) + DOWN * 0.8)
        self.play(Write(b7_l3))
        self.play(Create(SurroundingRectangle(b7_l3, color=GREEN)))
        self.wait(2)
        b7_l4 = Tex("Materials ALWAYS round up — 3,1 would also be 4").scale(0.95).shift(band_shift(7) + DOWN * 1.8)
        self.play(Write(b7_l4))
        self.wait(3)

        # --- Band 8 (subtopic_4): pricing the lawn, full method ---
        self.next_band(8)
        b8_t = Tex("Price the lawn seed").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_t))
        self.wait(1.5)
        b8_l1 = MathTex(r"96 - 12 - 6{,}28 = 77{,}72 \text{ m}^2").scale(1.05).shift(band_shift(8) + UP * 1.1)
        b8_l2 = MathTex(r"77{,}72 \div 20 = 3{,}886 \Rightarrow 4 \text{ bags}").scale(1.05).shift(band_shift(8) + UP * 0.2)
        b8_l3 = MathTex(r"4 \times \text{R}120 = \text{R}480").scale(1.05).shift(band_shift(8) + DOWN * 0.7)
        self.play(Write(b8_l1))
        self.wait(2.5)
        self.play(Write(b8_l2))
        self.wait(2.5)
        self.play(Write(b8_l3))
        self.wait(2)
        b8_l4 = MathTex(r"\text{Total: } 1\;400 + 480 = \text{R}1\;880").scale(1.1).shift(band_shift(8) + DOWN * 1.6)
        self.play(Write(b8_l4))
        self.play(Create(SurroundingRectangle(b8_l4, color=GREEN)))
        self.wait(2)
        b8_l5 = Tex("Shape, formula, metres, rolls, rand").scale(1.0).shift(band_shift(8) + DOWN * 2.6)
        self.play(Write(b8_l5))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 9 (subtopic_5): walk the edge, paint the floor ---
        self.next_band(9)
        b9_t = Tex("Walk the edge, paint the floor").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(2)
        b9_l1 = Tex("How far do you WALK around? Perimeter (m)").scale(1.0).shift(band_shift(9) + UP * 1.1)
        b9_l2 = Tex("How much would you PAINT inside? Area (m$^2$)").scale(1.0).shift(band_shift(9) + UP * 0.2)
        self.play(Write(b9_l1))
        self.wait(2.5)
        self.play(Write(b9_l2))
        self.wait(2.5)
        b9_l3 = MathTex(r"\text{Walk: } 12 + 8 + 12 + 8 = 40 \text{ m}").scale(1.0).shift(band_shift(9) + DOWN * 0.8)
        b9_l4 = Tex("Paint: 12 rows of 8 tiles = 96 m$^2$").scale(1.0).shift(band_shift(9) + DOWN * 1.7)
        self.play(Write(b9_l3))
        self.wait(2)
        self.play(Write(b9_l4))
        self.wait(2)
        b9_l5 = Tex("The gate hides in the words: 38,5 m, not 40").scale(1.0).shift(band_shift(9) + DOWN * 2.7)
        self.play(Write(b9_l5))
        self.play(Create(SurroundingRectangle(b9_l5, color=GREEN)))
        self.wait(3)

        # --- Band 10 (subtopic_6): half a pizza still has a straight side ---
        self.next_band(10)
        b10_t = Tex("Half a pizza still has a straight side").scale(1.15).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_t))
        self.wait(2)
        b10_l1 = Tex("Half the crust... plus the straight cut edge").scale(1.0).shift(band_shift(10) + UP * 1.1)
        self.play(Write(b10_l1))
        self.wait(2.5)
        b10_l2 = MathTex(r"6{,}284 + 4 = 10{,}28 \text{ m of edging}").scale(1.05).shift(band_shift(10) + UP * 0.1)
        self.play(Write(b10_l2))
        self.play(Create(SurroundingRectangle(b10_l2, color=GREEN)))
        self.wait(2.5)
        b10_l3 = MathTex(r"\text{Quarter: } 3{,}142 + 2 + 2 = 7{,}14 \text{ m}").scale(1.0).shift(band_shift(10) + DOWN * 0.9)
        b10_l4 = MathTex(r"\text{Three-quarter: } 9{,}426 + 4 = 13{,}43 \text{ m}").scale(1.0).shift(band_shift(10) + DOWN * 1.8)
        self.play(Write(b10_l3))
        self.wait(2)
        self.play(Write(b10_l4))
        self.wait(2)
        b10_l5 = Tex("The filling just takes the fraction — only").scale(0.95).shift(band_shift(10) + DOWN * 2.7)
        b10_l6 = Tex("the edge picks up cuts").scale(0.95).shift(band_shift(10) + DOWN * 3.3)
        self.play(Write(b10_l5))
        self.play(Write(b10_l6))
        self.wait(3)

        # --- Band 11 (subtopic_7): the shop sells rolls, not metres ---
        self.next_band(11)
        b11_t = Tex("The shop sells rolls, not metres").scale(1.2).shift(band_shift(11) + UP * 2.2)
        self.play(Write(b11_t))
        self.wait(2)
        b11_l1 = MathTex(r"38{,}5 \div 10 = 3{,}85 \Rightarrow 4 \text{ rolls} = \text{R}1\;400").scale(0.94).shift(band_shift(11) + UP * 1.1)
        self.play(Write(b11_l1))
        self.wait(2.5)
        b11_l2 = Tex("Even 3,1 becomes 4 — a 30 m fence has a hole").scale(1.0).shift(band_shift(11) + UP * 0.2)
        self.play(Write(b11_l2))
        self.wait(2.5)
        b11_l3 = MathTex(r"77{,}72 \div 20 = 3{,}886 \Rightarrow 4 \text{ bags} = \text{R}480").scale(0.94).shift(band_shift(11) + DOWN * 0.8)
        self.play(Write(b11_l3))
        self.wait(2.5)
        b11_ans = Tex("Measure, divide by pack, round UP, price").scale(1.05).shift(band_shift(11) + DOWN * 1.8)
        self.play(Write(b11_ans))
        self.play(Create(SurroundingRectangle(b11_ans, color=GREEN)))
        b11_l4 = Tex("Project: R1 880; add 2 days labour: R2 380").scale(0.95).shift(band_shift(11) + DOWN * 2.8)
        self.play(Write(b11_l4))
        self.wait(4)
