# Copyright (c) 2026 ROKCT INTELLIGENCE (PTY) LTD
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Royalty-free background music for the daily Reel, synthesised here.

Every note is generated by this file - no samples, no downloaded tracks -
so there is nothing to license and nothing for a rights-holder to claim.
A short upbeat loop: kick and hi-hat, a bass on the chord root, a soft pad
and a plucked arpeggio over a four-chord progression. Key, tempo and
progression rotate by date so consecutive days do not share one track.

Pure standard library (array + wave), 44.1 kHz mono 16-bit.
"""

import array
import math
import random
import wave
from pathlib import Path

RATE = 44100

# Semitone offsets from the key root, one chord per bar.
PROGRESSIONS = [
    [0, 7, 9, 5],   # I  V  vi IV
    [9, 5, 0, 7],   # vi IV I  V
    [0, 5, 9, 7],   # I  IV vi V
    [0, 9, 5, 7],   # I  vi IV V
]
KEYS = [48, 50, 52, 53, 55, 57]  # MIDI roots: C D E F G A (octave 3)
TEMPOS = [96, 100, 104, 108, 112]


def _hz(midi):
    return 440.0 * 2 ** ((midi - 69) / 12)


def _triad(root, offset):
    """Major triad on I/IV/V, minor on vi - diatonic to the key."""
    third = 3 if offset == 9 else 4
    base = root + offset
    return [base, base + third, base + 7]


def tempo_for(seed):
    """The day's tempo - motion.py times its on-beat hits to the same value."""
    return TEMPOS[(seed // 3) % len(TEMPOS)]


def render_music(seed, duration, out: Path):
    rng = random.Random(seed)
    key = KEYS[seed % len(KEYS)]
    bpm = tempo_for(seed)
    prog = PROGRESSIONS[(seed // 7) % len(PROGRESSIONS)]
    beat = 60.0 / bpm
    bar = beat * 4
    n = int(duration * RATE)
    buf = [0.0] * n

    def add(start, length, fn, gain):
        s0 = int(start * RATE)
        s1 = min(n, s0 + int(length * RATE))
        for i in range(s0, s1):
            t = (i - s0) / RATE
            buf[i] += gain * fn(t)

    t = 0.0
    step = 0
    while t < duration:
        chord = _triad(key, prog[int(t // bar) % len(prog)])

        # Kick on every beat: a pitch-dropping sine thump.
        if step % 2 == 0:
            add(t, 0.25, lambda x: math.sin(2 * math.pi * (50 + 90 * math.exp(-x * 30)) * x)
                * math.exp(-x * 14), 0.55)
        # Hi-hat on the off-beats: short decaying noise.
        else:
            hat = [rng.uniform(-1, 1) for _ in range(int(0.06 * RATE))]
            add(t, 0.06, lambda x, h=hat: h[min(len(h) - 1, int(x * RATE))] * math.exp(-x * 60), 0.10)

        # Bass on the chord root, one octave down, each beat.
        if step % 2 == 0:
            f = _hz(chord[0] - 12)
            add(t, beat * 0.9, lambda x, f=f: (math.sin(2 * math.pi * f * x)
                + 0.3 * math.sin(4 * math.pi * f * x)) * min(1, x * 40) * math.exp(-x * 2.5), 0.28)

        # Plucked arpeggio on eighths, walking the triad up an octave.
        note = chord[step % 3] + 12 * (1 + (step // 3) % 2)
        f = _hz(note)
        add(t, beat * 0.5, lambda x, f=f: (math.sin(2 * math.pi * f * x)
            + 0.25 * math.sin(6 * math.pi * f * x)) * math.exp(-x * 9), 0.12)

        # Pad: the whole triad, held for the bar, soft attack.
        if step % 8 == 0:
            freqs = [_hz(m + 12) for m in chord]
            add(t, bar, lambda x, fs=freqs: sum(
                math.sin(2 * math.pi * fq * x) + 0.2 * math.sin(4 * math.pi * fq * x * 1.003)
                for fq in fs) / 3 * min(1, x * 3) * min(1, (bar - x) * 6), 0.10)

        t += beat / 2
        step += 1

    # Fade in/out and normalise to -3 dBFS.
    fade = int(0.6 * RATE)
    for i in range(fade):
        buf[i] *= i / fade
        buf[n - 1 - i] *= i / fade
    peak = max(1e-9, max(abs(v) for v in buf))
    scale = 0.7 * 32767 / peak
    pcm = array.array("h", (int(v * scale) for v in buf))
    with wave.open(str(out), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(RATE)
        w.writeframes(pcm.tobytes())
    return out


ASSETS = Path(__file__).resolve().parent / "assets"
# Shared voice lines, rendered by the radio-ads factory from
# radio_ads/inbox/facebook_reel_brand_15.json, facebook_reel_open_15.json and
# facebook_reel_follow_15.json; tender Reels add radio_ads/reel_jobs/
# facebook_reel_tenderassist_15.json, rendered at build time by the Reel
# workflow (gated by REEL_SPONSOR_VOICE) and never committed.
VOICE_BRAND = ASSETS / "voice_brand.wav"
VOICE_OPEN = ASSETS / "voice_open.wav"
VOICE_CLOSE = ASSETS / "voice_close.wav"
VOICE_SPONSOR = ASSETS / "voice_tenderassist.wav"
SPONSOR_PAUSE = 0.3  # seconds between the sponsor line and the follow line
OPEN_PAUSE = 0.7  # seconds between "ROKCT" and the opening line


def _trimmed(vo: Path, tmp: Path):
    """The spoken line alone: leading and trailing silence cut away."""
    import subprocess

    subprocess.run(
        [
            "ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-i", str(vo),
            "-af",
            "silenceremove=start_periods=1:start_threshold=-45dB,areverse,"
            "silenceremove=start_periods=1:start_threshold=-45dB,areverse",
            "-ac", "1", "-ar", str(RATE), str(tmp),
        ],
        check=True,
    )
    with wave.open(str(tmp)) as w:
        return w.getnframes() / w.getframerate()


def _lay(music: Path, vo: Path, at_for):
    """Mix one voice line into the track at at_for(line_length) seconds,
    ducking the music under it. Returns when the line ends; a missing asset
    leaves the track as is and returns None."""
    import subprocess

    if not vo.exists():
        return None
    line = music.with_name("voice_line.wav")
    length = _trimmed(vo, line)
    at = at_for(length)
    mixed = music.with_name("music_vo.wav")
    subprocess.run(
        [
            "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
            "-i", str(music), "-i", str(line),
            "-filter_complex",
            f"[0:a]volume='if(between(t,{at - 0.25:.2f},{at + length + 0.1:.2f}),0.3,1)':eval=frame[m];"
            f"[1:a]adelay={int(at * 1000)}:all=1,volume=1.6[v];"
            "[m][v]amix=inputs=2:normalize=0:duration=first",
            "-ac", "1", "-ar", str(RATE), str(mixed),
        ],
        check=True,
    )
    line.unlink()
    mixed.replace(music)
    return at + length


def add_voiceover(music: Path, duration, opener=True, sponsor=False):
    """ROKCT (a man's voice) on the first beat, the opening line straight
    after it (unless opener is False), the follow line over the close. With
    sponsor, "Brought to you by TenderAssist" ends just before the follow
    line; until its asset is rendered it is skipped."""
    brand_end = _lay(music, VOICE_BRAND, lambda length: 0.15)
    if opener:
        _lay(music, VOICE_OPEN, lambda length: (brand_end or 0) + OPEN_PAUSE)
    close = {}

    def close_at(length):
        close["at"] = max(0.5, duration - length - 0.35)
        return close["at"]

    _lay(music, VOICE_CLOSE, close_at)
    if sponsor and "at" in close:
        _lay(music, VOICE_SPONSOR, lambda length: max(0.5, close["at"] - length - SPONSOR_PAUSE))
