from manim import *

# Band-layout whiteboard scene for the session duo "Evolution of Markets"
# (Part 1 — Expert subtopics 1-4, Part 2 — Simplifier subtopics 5-7).
# Exporter-safe vocabulary only: Tex/MathTex/Line/Arrow/Dot/Circle/Rectangle/
# SurroundingRectangle/VGroup. Add-only lifecycle — the camera moves down to a
# fresh band for each teaching step; nothing is transformed or removed.
# Subtopic durations (subtopics.json): 220/230/210/230/190/190/190 of 1460 s.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class EvolutionOfMarketsSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md audio plays.
        self.wait(14)

        # ===================== Part 1 — Expert =====================
        # --- Band 0 (subtopic_1): the whole story as one sequence ---
        title = Tex("The Evolution of Markets").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        s0a = Tex("Self-sufficiency").scale(1.0).shift(UP * 1.2 + LEFT * 4.4)
        s0b = Tex("Surplus").scale(1.0).shift(UP * 1.2 + LEFT * 0.6)
        s0c = Tex("Barter").scale(1.0).shift(UP * 1.2 + RIGHT * 2.4)
        s0d = Tex("Money").scale(1.0).shift(UP * 1.2 + RIGHT * 5.0)
        a0a = Arrow(s0a.get_right(), s0b.get_left(), buff=0.15)
        a0b = Arrow(s0b.get_right(), s0c.get_left(), buff=0.15)
        a0c = Arrow(s0c.get_right(), s0d.get_left(), buff=0.15)
        self.play(Write(s0a))
        self.play(Create(a0a), Write(s0b))
        self.play(Create(a0b), Write(s0c))
        self.play(Create(a0c), Write(s0d))
        self.wait(2)
        s0e = Tex("Markets").scale(1.0).shift(DOWN * 0.2 + LEFT * 3.6)
        s0f = Tex("The state").scale(1.0).shift(DOWN * 0.2)
        s0g = Tex("Industry").scale(1.0).shift(DOWN * 0.2 + RIGHT * 3.6)
        a0d = Arrow(s0e.get_right(), s0f.get_left(), buff=0.15)
        a0e = Arrow(s0f.get_right(), s0g.get_left(), buff=0.15)
        self.play(Write(s0e))
        self.play(Create(a0d), Write(s0f))
        self.play(Create(a0e), Write(s0g))
        self.wait(2)
        s0h = Tex("Each stage SOLVES the last stage's problem").scale(1.1).shift(DOWN * 1.6)
        self.play(Write(s0h))
        self.play(Create(SurroundingRectangle(s0h, color=GREEN)))
        self.wait(3)

        # --- Band 1 (subtopic_1): surplus is the hinge ---
        self.next_band(1)
        b1t = Tex("Surplus — the hinge of economic history").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1t))
        self.wait(2)
        b1a = Tex("Self-sufficiency: consume only what YOU make").scale(1.1).shift(band_shift(1) + UP * 1.1)
        self.play(Write(b1a))
        self.wait(2)
        b1b = Tex("Settled farming $\\Rightarrow$ SURPLUS (more than needed)").scale(1.1).shift(band_shift(1) + UP * 0.2)
        self.play(Write(b1b))
        self.wait(2)
        b1c = Tex("Surplus frees people to SPECIALISE").scale(1.1).shift(band_shift(1) + DOWN * 0.7)
        b1d = Tex("Specialists must EXCHANGE").scale(1.1).shift(band_shift(1) + DOWN * 1.6)
        self.play(Write(b1c))
        self.wait(2)
        self.play(Write(b1d))
        self.wait(2)
        b1e = Tex("Trade is surplus's child").scale(1.1).shift(band_shift(1) + DOWN * 2.6)
        self.play(Write(b1e))
        self.play(Create(SurroundingRectangle(b1e, color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_1): barter's four failures ---
        self.next_band(2)
        b2t = Tex("Barter: goods for goods — four failures").scale(1.2).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2t))
        self.wait(2)
        b2a = Tex("1. Double coincidence of wants").scale(1.1).shift(band_shift(2) + UP * 1.1)
        b2a2 = Tex("must find who HAS what you want, WANTS yours").scale(1.0).shift(band_shift(2) + UP * 0.4)
        self.play(Write(b2a))
        self.play(Write(b2a2))
        self.wait(2)
        b2b = Tex("2. Indivisibility — half a goat buys nothing").scale(1.1).shift(band_shift(2) + DOWN * 0.4)
        self.play(Write(b2b))
        self.wait(2)
        b2c = Tex("3. No common measure — a ratio per pair").scale(1.1).shift(band_shift(2) + DOWN * 1.2)
        self.play(Write(b2c))
        self.wait(2)
        b2d = Tex("4. No store of value — surplus rots").scale(1.1).shift(band_shift(2) + DOWN * 2.0)
        self.play(Write(b2d))
        self.wait(2)
        b2box = SurroundingRectangle(VGroup(b2a, b2b, b2c, b2d), color=GREEN)
        self.play(Create(b2box))
        self.wait(3)

        # --- Band 3 (subtopic_2): money answers barter point by point ---
        self.next_band(3)
        b3t = Tex("Money's functions answer barter's failures").scale(1.15).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3t))
        self.wait(2)
        b3l1 = Tex("Medium of exchange").scale(1.0).shift(band_shift(3) + UP * 1.1 + LEFT * 3.6)
        b3r1 = Tex("kills double coincidence").scale(1.0).shift(band_shift(3) + UP * 1.1 + RIGHT * 3.3)
        a31 = Arrow(b3l1.get_right(), b3r1.get_left(), buff=0.15)
        self.play(Write(b3l1))
        self.play(Create(a31), Write(b3r1))
        self.wait(2)
        b3l2 = Tex("Unit of account").scale(1.0).shift(band_shift(3) + UP * 0.2 + LEFT * 3.6)
        b3r2 = Tex("one measure — prices").scale(1.0).shift(band_shift(3) + UP * 0.2 + RIGHT * 3.3)
        a32 = Arrow(b3l2.get_right(), b3r2.get_left(), buff=0.15)
        self.play(Write(b3l2))
        self.play(Create(a32), Write(b3r2))
        self.wait(2)
        b3l3 = Tex("Store of value").scale(1.0).shift(band_shift(3) + DOWN * 0.7 + LEFT * 3.6)
        b3r3 = Tex("wealth can wait").scale(1.0).shift(band_shift(3) + DOWN * 0.7 + RIGHT * 3.3)
        a33 = Arrow(b3l3.get_right(), b3r3.get_left(), buff=0.15)
        self.play(Write(b3l3))
        self.play(Create(a33), Write(b3r3))
        self.wait(2)
        b3l4 = Tex("Divisibility").scale(1.0).shift(band_shift(3) + DOWN * 1.6 + LEFT * 3.6)
        b3r4 = Tex("change — any size works").scale(1.0).shift(band_shift(3) + DOWN * 1.6 + RIGHT * 3.3)
        a34 = Arrow(b3l4.get_right(), b3r4.get_left(), buff=0.15)
        self.play(Write(b3l4))
        self.play(Create(a34), Write(b3r4))
        self.wait(2)
        b3e = Tex("Cattle, salt, shells $\\rightarrow$ metal, paper, electronic").scale(1.0).shift(band_shift(3) + DOWN * 2.7)
        self.play(Write(b3e))
        self.wait(3)

        # --- Band 4 (subtopic_2): markets evolve along tracks ---
        self.next_band(4)
        b4t = Tex("How markets evolved — the tracks").scale(1.2).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4t))
        self.wait(2)
        b4a = Tex("Specialisation: division of labour").scale(1.1).shift(band_shift(4) + UP * 1.1)
        self.play(Write(b4a))
        self.wait(2)
        b4b = Tex("Trade + transport: roads, ships, rail").scale(1.1).shift(band_shift(4) + UP * 0.3)
        self.play(Write(b4b))
        self.wait(2)
        b4c = Tex("Mercantile law: contracts, weights, courts").scale(1.1).shift(band_shift(4) + DOWN * 0.5)
        self.play(Write(b4c))
        self.wait(2)
        b4d = Tex("Business forms: trader $\\rightarrow$ partnership $\\rightarrow$ company").scale(1.05).shift(band_shift(4) + DOWN * 1.3)
        self.play(Write(b4d))
        self.wait(2)
        b4e = Tex("Technological progress threads through all").scale(1.1).shift(band_shift(4) + DOWN * 2.3)
        self.play(Write(b4e))
        self.play(Create(SurroundingRectangle(b4e, color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_3): the state's three historic entries ---
        self.next_band(5)
        b5t = Tex("Governments enter the market — three entries").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5t))
        self.wait(2)
        r5a = Rectangle(width=4.0, height=1.0).shift(band_shift(5) + UP * 0.9 + LEFT * 4.2)
        t5a = Tex("1. Involvement in trade").scale(0.9).move_to(r5a.get_center())
        self.play(Create(r5a), Write(t5a))
        b5a = Tex("ports, routes, chartered companies — taxed trade").scale(1.0).shift(band_shift(5) + UP * 0.9 + RIGHT * 2.6)
        self.play(Write(b5a))
        self.wait(2)
        r5b = Rectangle(width=4.0, height=1.0).shift(band_shift(5) + DOWN * 0.4 + LEFT * 4.2)
        t5b = Tex("2. Taxation").scale(0.9).move_to(r5b.get_center())
        self.play(Create(r5b), Write(t5b))
        b5b = Tex("customs, levies — a claim on activity").scale(1.0).shift(band_shift(5) + DOWN * 0.4 + RIGHT * 2.6)
        self.play(Write(b5b))
        self.wait(2)
        r5c = Rectangle(width=4.0, height=1.0).shift(band_shift(5) + DOWN * 1.7 + LEFT * 4.2)
        t5c = Tex("3. Infrastructure").scale(0.9).move_to(r5c.get_center())
        self.play(Create(r5c), Write(t5c))
        b5c = Tex("roads, harbours, rail — public investment").scale(1.0).shift(band_shift(5) + DOWN * 1.7 + RIGHT * 2.6)
        self.play(Write(b5c))
        self.wait(3)

        # --- Band 6 (subtopic_3): the analytical thread ---
        self.next_band(6)
        b6t = Tex("Why the state? Market limitations").scale(1.2).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6t))
        self.wait(2)
        b6a = Tex("Unenforced contracts $\\rightarrow$ law and courts").scale(1.1).shift(band_shift(6) + UP * 1.0)
        self.play(Write(b6a))
        self.wait(2)
        b6b = Tex("Unfunded common goods $\\rightarrow$ public building").scale(1.1).shift(band_shift(6) + UP * 0.1)
        self.play(Write(b6b))
        self.wait(2)
        b6c = Tex("Larger economy $\\rightarrow$ larger tax revenue").scale(1.1).shift(band_shift(6) + DOWN * 0.8)
        self.play(Write(b6c))
        self.wait(2)
        b6d = Tex("Each entry answers a market limitation").scale(1.1).shift(band_shift(6) + DOWN * 1.9)
        self.play(Write(b6d))
        self.play(Create(SurroundingRectangle(b6d, color=GREEN)))
        self.wait(3)

        # --- Band 7 (subtopic_4): industrialisation's four components ---
        self.next_band(7)
        b7t = Tex("Industrial development — four components").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7t))
        self.wait(2)
        b7a = Tex("Manufacturing: factory scale, falling prices").scale(1.1).shift(band_shift(7) + UP * 1.1)
        self.play(Write(b7a))
        self.wait(2)
        b7b = Tex("Technological progress: machines embody knowledge").scale(1.05).shift(band_shift(7) + UP * 0.3)
        self.play(Write(b7b))
        self.wait(2)
        b7c = Tex("Mobilised energy: muscle $\\rightarrow$ steam $\\rightarrow$ electricity").scale(1.05).shift(band_shift(7) + DOWN * 0.5)
        self.play(Write(b7c))
        self.wait(2)
        b7d = Tex("Mechanisation: tractor, railway, assembly line").scale(1.05).shift(band_shift(7) + DOWN * 1.3)
        self.play(Write(b7d))
        self.wait(2)
        b7box = SurroundingRectangle(VGroup(b7a, b7b, b7c, b7d), color=GREEN)
        self.play(Create(b7box))
        self.wait(3)

        # --- Band 8 (subtopic_4): consequences, and SA's route through mining ---
        self.next_band(8)
        b8t = Tex("Consequences — gains and costs entangled").scale(1.15).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8t))
        self.wait(2)
        b8a = Tex("Productivity multiplied; urbanisation").scale(1.1).shift(band_shift(8) + UP * 1.1)
        self.play(Write(b8a))
        self.wait(2)
        b8b = Tex("New classes: employers vs workers").scale(1.1).shift(band_shift(8) + UP * 0.3)
        self.play(Write(b8b))
        self.wait(2)
        b8c = Tex("Costs: harsh conditions, child labour, pollution").scale(1.05).shift(band_shift(8) + DOWN * 0.5)
        self.play(Write(b8c))
        self.wait(2)
        b8d = Tex("SA route: diamonds and gold — MINING").scale(1.1).shift(band_shift(8) + DOWN * 1.4)
        self.play(Write(b8d))
        self.wait(2)
        b8e = Tex("Railways inland; migrant labour's social costs").scale(1.05).shift(band_shift(8) + DOWN * 2.3)
        self.play(Write(b8e))
        self.play(Create(SurroundingRectangle(b8d, color=GREEN)))
        self.wait(3)

        # ===================== Part 2 — Simplifier =====================
        # --- Band 9 (subtopic_5): the village that grew extra ---
        self.next_band(9)
        b9t = Tex("One village: extra changes everything").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9t))
        self.wait(2)
        b9a = Tex("Every family does everything — no extra, no trade").scale(1.05).shift(band_shift(9) + UP * 1.1)
        self.play(Write(b9a))
        self.wait(2)
        b9b = Tex("Farming mastered $\\Rightarrow$ EXTRA $\\Rightarrow$ specialists").scale(1.05).shift(band_shift(9) + UP * 0.2)
        self.play(Write(b9b))
        self.wait(2)
        b9c = Tex("Swapping's four miseries:").scale(1.1).shift(band_shift(9) + DOWN * 0.7)
        self.play(Write(b9c))
        b9d = Tex("the great hunt; no half-goat payments").scale(1.0).shift(band_shift(9) + DOWN * 1.5)
        b9e = Tex("every deal an argument; wealth rots or walks").scale(1.0).shift(band_shift(9) + DOWN * 2.3)
        self.play(Write(b9d))
        self.wait(2)
        self.play(Write(b9e))
        self.play(Create(SurroundingRectangle(VGroup(b9d, b9e), color=GREEN)))
        self.wait(3)

        # --- Band 10 (subtopic_6): the invention that fixed everything ---
        self.next_band(10)
        b10t = Tex("Iron pieces: four miseries die in one day").scale(1.15).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10t))
        self.wait(2)
        b10a = Tex("Sell to ANYONE, buy from ANYONE — hunt over").scale(1.05).shift(band_shift(10) + UP * 1.1)
        self.play(Write(b10a))
        self.wait(2)
        b10b = Tex("Iron splits — any size of purchase works").scale(1.05).shift(band_shift(10) + UP * 0.3)
        self.play(Write(b10b))
        self.wait(2)
        b10c = Tex("One measuring stick — arithmetic, not war").scale(1.05).shift(band_shift(10) + DOWN * 0.5)
        self.play(Write(b10c))
        self.wait(2)
        b10d = Tex("Wealth can WAIT — sell now, buy in winter").scale(1.05).shift(band_shift(10) + DOWN * 1.3)
        self.play(Write(b10d))
        self.wait(2)
        b10e = Tex("Then: roads, rules, shared ownership").scale(1.05).shift(band_shift(10) + DOWN * 2.3)
        self.play(Write(b10e))
        self.play(Create(SurroundingRectangle(b10e, color=GREEN)))
        self.wait(3)

        # --- Band 11 (subtopic_7): the chief, and then the machines ---
        self.next_band(11)
        b11t = Tex("The chief's three jobs — still in every budget").scale(1.15).shift(band_shift(11) + UP * 2.2)
        self.play(Write(b11t))
        self.wait(2)
        b11a = Tex("REGULATE routes $\\cdot$ TAX every deal $\\cdot$ BUILD the bridge").scale(1.0).shift(band_shift(11) + UP * 1.2)
        self.play(Write(b11a))
        self.play(Create(SurroundingRectangle(b11a, color=GREEN)))
        self.wait(2)
        b11b = Tex("Then machines: mill out-produces a lane of weavers").scale(1.0).shift(band_shift(11) + UP * 0.1)
        self.play(Write(b11b))
        self.wait(2)
        b11c = Tex("Goods cheap, cities big; owners face workers").scale(1.0).shift(band_shift(11) + DOWN * 0.8)
        self.play(Write(b11c))
        self.wait(2)
        b11d = Tex("SA's machine-day: diamonds, then gold").scale(1.05).shift(band_shift(11) + DOWN * 1.7)
        self.play(Write(b11d))
        self.wait(2)
        b11e = Tex("Extra $\\rightarrow$ specialists $\\rightarrow$ money $\\rightarrow$ market $\\rightarrow$ state $\\rightarrow$ machines").scale(0.95).shift(band_shift(11) + DOWN * 2.7)
        self.play(Write(b11e))
        self.play(Create(SurroundingRectangle(b11e, color=GREEN)))
        self.wait(4)
