from manim import *

# Band-layout whiteboard scene for the session duo "Chords and Angles at the
# Centre" (Part 1 — Expert: subtopics 1-4; Part 2 — Simplifier: subtopics
# 5-7). One band per teaching beat, add-only lifecycle, camera moves down.
# Only exporter-supported mobjects (Tex/MathTex/Line/Arrow/Dot/Circle/
# SurroundingRectangle); write-only reveals, diagrams built element by
# element. Band dwell times follow subtopics.json
# (235/255/220/250/190/195/195 of 1540 s); Level 6 rescales to real audio.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class ChordsAndAnglesAtCentreSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: player holds the topic full-screen while intro.md plays.
        self.wait(15)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): vocabulary of the circle
        title = Tex("Chords and Angles at the Centre").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(1.5)
        c0 = DOWN * 0.9 + LEFT * 3.4
        circ = Circle(radius=1.6, color=WHITE).shift(c0)
        oc = Dot(c0, color=YELLOW)
        o_lab = Tex("O").scale(0.9).shift(c0 + DOWN * 0.35)
        self.play(Create(circ))
        self.play(Create(oc), Write(o_lab))
        self.wait(1.5)
        radius = Line(c0, c0 + UP * 1.13 + RIGHT * 1.13, color=YELLOW)
        chord = Line(c0 + UP * 1.5 + LEFT * 0.55, c0 + DOWN * 0.4 + RIGHT * 1.55, color=BLUE)
        self.play(Create(radius))
        self.play(Create(chord))
        self.wait(1.5)
        v1 = Tex("Radius: centre to circle — all radii equal").scale(0.95).shift(UP * 0.4 + RIGHT * 2.9)
        v2 = Tex("Chord: joins two circle points").scale(0.95).shift(DOWN * 0.4 + RIGHT * 2.9)
        v3 = Tex("Diameter $= 2 \\times$ radius, through O").scale(0.95).shift(DOWN * 1.2 + RIGHT * 2.9)
        v4 = Tex("A chord cuts two segments").scale(0.95).shift(DOWN * 2.0 + RIGHT * 2.9)
        self.play(Write(v1))
        self.wait(2)
        self.play(Write(v2))
        self.wait(1.5)
        self.play(Write(v3))
        self.wait(1.5)
        self.play(Write(v4))
        self.wait(2.5)

        # --- Band 1 (subtopic_1): the chord theorem and its proof pattern
        self.next_band(1)
        b1_title = Tex("Perpendicular from centre bisects the chord").scale(1.1).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l1 = Tex(r"In $\triangle OMA$ and $\triangle OMB$:").scale(1.05).shift(band_shift(1) + UP * 1.2)
        b1_l2 = MathTex(r"OA = OB \;\text{(radii)}, \quad OM \text{ common}").scale(1.0).shift(band_shift(1) + UP * 0.4)
        b1_l3 = MathTex(r"\hat{M}_1 = \hat{M}_2 = 90^\circ").scale(1.0).shift(band_shift(1) + DOWN * 0.4)
        b1_l4 = MathTex(r"\triangle OMA \equiv \triangle OMB \Rightarrow AM = MB").scale(0.95).shift(band_shift(1) + DOWN * 1.2)
        self.play(Write(b1_l1))
        self.wait(2)
        self.play(Write(b1_l2))
        self.wait(2)
        self.play(Write(b1_l3))
        self.wait(2)
        self.play(Write(b1_l4))
        self.play(Create(SurroundingRectangle(b1_l4, color=GREEN)))
        self.wait(2.5)
        b1_l5 = Tex("Reverse: centre to midpoint $\\Rightarrow$ perpendicular").scale(0.95).shift(band_shift(1) + DOWN * 2.1)
        b1_l6 = Tex("And: perpendicular bisector of a chord passes through O").scale(0.9).shift(band_shift(1) + DOWN * 2.9)
        self.play(Write(b1_l5))
        self.wait(2)
        self.play(Write(b1_l6))
        self.wait(2.5)

        # --- Band 2 (subtopic_1): the half-chord triangle
        self.next_band(2)
        b2_title = Tex("Chord 16, radius 10 — distance to centre?").scale(1.1).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(1.5)
        b2_l1 = Tex("Perpendicular from O bisects: half-chord $= 8$").scale(1.05).shift(band_shift(2) + UP * 1.1)
        b2_l2 = MathTex(r"d^2 = 10^2 - 8^2 = 100 - 64 = 36").scale(1.1).shift(band_shift(2) + UP * 0.1)
        b2_l3 = MathTex(r"d = 6").scale(1.2).shift(band_shift(2) + DOWN * 0.9)
        self.play(Write(b2_l1))
        self.wait(2.5)
        self.play(Write(b2_l2))
        self.wait(2.5)
        self.play(Write(b2_l3))
        self.play(Create(SurroundingRectangle(b2_l3, color=GREEN)))
        self.wait(2)
        b2_rule = Tex("Every chord-distance sum: half chord, distance, radius").scale(0.95).shift(band_shift(2) + DOWN * 1.9)
        self.play(Write(b2_rule))
        self.wait(2.5)

        # --- Band 3 (subtopic_2): the centre theorem and its proof
        self.next_band(3)
        b3_title = Tex(r"$\hat{AOB} = 2 \times \hat{ACB}$ on the same arc").scale(1.15).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(2)
        b3_l1 = Tex(r"Proof: draw $CO$ extended to $D$").scale(1.0).shift(band_shift(3) + UP * 1.1)
        b3_l2 = MathTex(r"\triangle OAC \text{ isosceles (radii): base angles } x").scale(0.95).shift(band_shift(3) + UP * 0.2)
        b3_l3 = MathTex(r"\text{Exterior angle: } \hat{AOD} = 2x; \quad \hat{BOD} = 2y").scale(0.95).shift(band_shift(3) + DOWN * 0.7)
        b3_l4 = MathTex(r"\hat{AOB} = 2x + 2y, \quad \hat{ACB} = x + y").scale(1.0).shift(band_shift(3) + DOWN * 1.6)
        b3_l5 = MathTex(r"\hat{AOB} = 2\hat{ACB}").scale(1.1).shift(band_shift(3) + DOWN * 2.5)
        self.play(Write(b3_l1))
        self.wait(2)
        self.play(Write(b3_l2))
        self.wait(2.5)
        self.play(Write(b3_l3))
        self.wait(2.5)
        self.play(Write(b3_l4))
        self.wait(2)
        self.play(Write(b3_l5))
        self.play(Create(SurroundingRectangle(b3_l5, color=GREEN)))
        self.wait(2.5)

        # --- Band 4 (subtopic_2): using it, reflex arcs, semicircle
        self.next_band(4)
        b4_title = Tex("Halve the correct central angle").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(1.5)
        b4_l1 = MathTex(r"\hat{AOB} = 140^\circ \Rightarrow \hat{ACB} = 70^\circ").scale(1.05).shift(band_shift(4) + UP * 1.1)
        self.play(Write(b4_l1))
        self.wait(2)
        b4_l2 = MathTex(r"\text{Reflex } 220^\circ \Rightarrow \text{arc } 110^\circ").scale(1.0).shift(band_shift(4) + UP * 0.2)
        b4_l3 = Tex("Shade the arc the angles stand on before halving").scale(0.95).shift(band_shift(4) + DOWN * 0.7)
        self.play(Write(b4_l2))
        self.wait(2.5)
        self.play(Write(b4_l3))
        self.wait(2)
        b4_l4 = MathTex(r"\text{Diameter: } 180^\circ \div 2 = 90^\circ").scale(1.05).shift(band_shift(4) + DOWN * 1.6)
        b4_l5 = Tex("Angle in semicircle is a right angle — and in reverse").scale(0.95).shift(band_shift(4) + DOWN * 2.5)
        self.play(Write(b4_l4))
        self.play(Create(SurroundingRectangle(b4_l4, color=GREEN)))
        self.wait(2)
        self.play(Write(b4_l5))
        self.wait(2.5)

        # --- Band 5 (subtopic_3): angles in the same segment
        self.next_band(5)
        b5_title = Tex("Angles in the same segment are equal").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(1.5)
        b5_l1 = MathTex(r"\text{Chord } AB, \text{ same side: } \hat{ACB} = \hat{ADB}").scale(1.0).shift(band_shift(5) + UP * 1.1)
        self.play(Write(b5_l1))
        self.play(Create(SurroundingRectangle(b5_l1, color=GREEN)))
        self.wait(2.5)
        b5_l2 = MathTex(r"\text{Proof: each} = \tfrac{1}{2}\hat{AOB} \text{ on the same arc}").scale(1.0).shift(band_shift(5) + UP * 0.1)
        self.play(Write(b5_l2))
        self.wait(2.5)
        b5_l3 = Tex(r"Crossing chords at $P$: two equal pairs appear —").scale(0.95).shift(band_shift(5) + DOWN * 0.9)
        b5_l4 = MathTex(r"\hat{CAB} = \hat{CDB}, \; \hat{ABD} = \hat{ACD}").scale(0.9).shift(band_shift(5) + DOWN * 1.8)
        self.play(Write(b5_l3))
        self.wait(2)
        self.play(Write(b5_l4))
        self.wait(2)
        b5_l5 = Tex("Opposite sides of the chord: NOT equal — supplementary").scale(0.9).shift(band_shift(5) + DOWN * 2.8)
        self.play(Write(b5_l5))
        self.wait(2.5)

        # --- Band 6 (subtopic_3): the worked chain
        self.next_band(6)
        b6_title = Tex(r"Chord $AB$: $\hat{ACB} = 53^\circ$, $D$ on the same arc").scale(1.05).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(2)
        b6_l1 = MathTex(r"\hat{ADB} = 53^\circ \;\text{(angles in same segment)}").scale(1.05).shift(band_shift(6) + UP * 1.0)
        self.play(Write(b6_l1))
        self.play(Create(SurroundingRectangle(b6_l1, color=GREEN)))
        self.wait(2.5)
        b6_l2 = Tex(r"$AD$ crosses $BC$ at $P$: angles at $P$ vertically opposite").scale(0.95).shift(band_shift(6) + UP * 0.0)
        b6_l3 = Tex("Same-segment $+$ vertical pair $\\Rightarrow$ third equal").scale(0.9).shift(band_shift(6) + DOWN * 0.9)
        b6_l4 = Tex("Two triangles with matching angles, almost for free").scale(0.95).shift(band_shift(6) + DOWN * 1.8)
        self.play(Write(b6_l2))
        self.wait(2.5)
        self.play(Write(b6_l3))
        self.wait(2.5)
        self.play(Write(b6_l4))
        self.wait(2.5)

        # --- Band 7 (subtopic_4): rider strategy and reasons
        self.next_band(7)
        b7_title = Tex("Riders: claim $+$ reason, every line").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(1.5)
        b7_l1 = Tex("1. Mark every radius — isosceles angle factories").scale(1.0).shift(band_shift(7) + UP * 1.1)
        b7_l2 = Tex("2. Hunt the diameter — a free $90^\\circ$").scale(1.0).shift(band_shift(7) + UP * 0.2)
        b7_l3 = Tex("3. Shade the arc before halving or doubling").scale(1.0).shift(band_shift(7) + DOWN * 0.7)
        b7_l4 = Tex("4. Chase angles on the diagram before writing").scale(1.0).shift(band_shift(7) + DOWN * 1.6)
        self.play(Write(b7_l1))
        self.wait(2)
        self.play(Write(b7_l2))
        self.wait(2)
        self.play(Write(b7_l3))
        self.wait(2)
        self.play(Write(b7_l4))
        self.wait(2)
        b7_l5 = Tex("An unreasoned claim scores nothing, even when true").scale(0.95).shift(band_shift(7) + DOWN * 2.6)
        self.play(Write(b7_l5))
        self.wait(2.5)

        # --- Band 8 (subtopic_4): the full worked rider
        self.next_band(8)
        b8_title = Tex(r"Rider: $\hat{AOB} = 100^\circ$ on minor arc, $C$ opposite").scale(1.0).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = MathTex(r"\hat{ACB} = 50^\circ \text{ (centre } = 2 \times \text{circumf.)}").scale(0.95).shift(band_shift(8) + UP * 1.2)
        b8_l2 = MathTex(r"OA = OB \Rightarrow \triangle AOB \text{ isosceles}").scale(0.95).shift(band_shift(8) + UP * 0.3)
        b8_l3 = MathTex(r"\hat{A} = \hat{B} = \frac{180^\circ - 100^\circ}{2} = 40^\circ").scale(1.0).shift(band_shift(8) + DOWN * 0.7)
        self.play(Write(b8_l1))
        self.wait(2.5)
        self.play(Write(b8_l2))
        self.wait(2.5)
        self.play(Write(b8_l3))
        self.play(Create(SurroundingRectangle(b8_l3, color=GREEN)))
        self.wait(2.5)
        b8_l4 = MathTex(r"BC \text{ diameter} \Rightarrow \hat{BAC} = 90^\circ").scale(0.95).shift(band_shift(8) + DOWN * 1.7)
        b8_l5 = MathTex(r"\hat{ABC} = 180^\circ - 90^\circ - 50^\circ = 40^\circ").scale(1.0).shift(band_shift(8) + DOWN * 2.6)
        self.play(Write(b8_l4))
        self.wait(2.5)
        self.play(Write(b8_l5))
        self.play(Create(SurroundingRectangle(b8_l5, color=GREEN)))
        self.wait(2.5)

        # ============ Part 2 — Simplifier ============
        # --- Band 9 (subtopic_5): folding the circle
        self.next_band(9)
        b9_title = Tex("Folding the circle").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex("A fold that meets the chord's ends: halves it, at $90^\\circ$").scale(0.95).shift(band_shift(9) + UP * 1.1)
        b9_l2 = Tex("Every fold line passes through the centre — two folds find it").scale(0.9).shift(band_shift(9) + UP * 0.2)
        self.play(Write(b9_l1))
        self.wait(2.5)
        self.play(Write(b9_l2))
        self.wait(2.5)
        b9_wrong = MathTex(r"d^2 = 10^2 - 16^2 \;\text{(whole chord)}").scale(1.0).shift(band_shift(9) + DOWN * 0.8)
        self.play(Write(b9_wrong))
        self.play(Create(strike(b9_wrong)))
        self.wait(2)
        b9_l3 = MathTex(r"d^2 = 10^2 - 8^2 = 36 \;\Rightarrow\; d = 6").scale(1.05).shift(band_shift(9) + DOWN * 1.8)
        self.play(Write(b9_l3))
        self.play(Create(SurroundingRectangle(b9_l3, color=GREEN)))
        b9_rule = Tex("The triangle always uses HALF the chord").scale(1.0).shift(band_shift(9) + DOWN * 2.8)
        self.play(Write(b9_rule))
        self.wait(3)

        # --- Band 10 (subtopic_6): the whole stadium sees the same game
        self.next_band(10)
        b10_title = Tex("The whole stadium sees the same game").scale(1.15).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_title))
        self.wait(2)
        b10_l1 = Tex("Goal mouth $=$ chord; every seat on one curve —").scale(1.0).shift(band_shift(10) + UP * 1.1)
        b10_l2 = Tex("same viewing angle: angles in the same segment").scale(1.0).shift(band_shift(10) + UP * 0.3)
        self.play(Write(b10_l1))
        self.play(Write(b10_l2))
        self.wait(3)
        b10_l3 = MathTex(r"\text{Centre } 140^\circ \Rightarrow \text{seats } 70^\circ").scale(0.95).shift(band_shift(10) + DOWN * 0.7)
        self.play(Write(b10_l3))
        self.wait(2.5)
        b10_l4 = MathTex(r"\text{Goal through centre: } 180^\circ \div 2 = 90^\circ").scale(1.0).shift(band_shift(10) + DOWN * 1.7)
        self.play(Write(b10_l4))
        self.play(Create(SurroundingRectangle(b10_l4, color=GREEN)))
        self.wait(2)
        b10_l5 = Tex("See a diameter, expect a ninety — same arc, always").scale(0.95).shift(band_shift(10) + DOWN * 2.7)
        self.play(Write(b10_l5))
        self.wait(3)

        # --- Band 11 (subtopic_7): the case file
        self.next_band(11)
        b11_title = Tex("Solving a rider like a case file").scale(1.2).shift(band_shift(11) + UP * 2.2)
        self.play(Write(b11_title))
        self.wait(2)
        b11_l1 = Tex("Darken the radii, scan for a diameter, shade the arc").scale(0.95).shift(band_shift(11) + UP * 1.1)
        self.play(Write(b11_l1))
        self.wait(2.5)
        b11_l2 = MathTex(r"\text{Centre } 100^\circ \Rightarrow \text{seat } 50^\circ").scale(1.0).shift(band_shift(11) + UP * 0.2)
        b11_l3 = MathTex(r"\text{Isosceles: rest } 80^\circ \to 40^\circ + 40^\circ").scale(0.95).shift(band_shift(11) + DOWN * 0.8)
        self.play(Write(b11_l2))
        self.wait(2.5)
        self.play(Write(b11_l3))
        self.play(Create(SurroundingRectangle(b11_l3, color=GREEN)))
        self.wait(2.5)
        b11_l4 = Tex("Three certainties, each hanging on the one before").scale(0.95).shift(band_shift(11) + DOWN * 1.8)
        b11_l5 = Tex("Claim, reason, next link — no reason, no evidence, no marks").scale(0.9).shift(band_shift(11) + DOWN * 2.8)
        self.play(Write(b11_l4))
        self.wait(2.5)
        self.play(Write(b11_l5))
        self.wait(4)
