from manim import *

# Band-layout whiteboard scene for the session duo "Identities and Reduction
# Formulae" (Part 1 — Expert: subtopics 1-4; Part 2 — Simplifier: subtopics
# 5-7). One band per teaching beat, add-only lifecycle, camera moves down.
# Only exporter-supported mobjects (Tex/MathTex/Line/Arrow/Dot/Circle/
# SurroundingRectangle); write-only reveals, no sub-part transforms.
# Band dwell times follow subtopics.json (225/215/240/255/190/185/195 of
# 1505 s); Level 6 rescales to real audio, so proportion is what matters.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class IdentitiesAndReductionFormulaeSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: player holds the topic full-screen while intro.md plays.
        self.wait(15)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): the x, y, r definitions
        title = Tex("Identities and Reduction Formulae").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(1.5)
        d1 = Tex(r"Any angle: point $(x; y)$ on the arm, $r > 0$").scale(1.05).shift(UP * 1.0)
        self.play(Write(d1))
        self.wait(2)
        d2 = MathTex(r"\sin\theta = \frac{y}{r}, \quad \cos\theta = \frac{x}{r}").scale(1.1).shift(DOWN * 0.1)
        self.play(Write(d2))
        self.wait(2)
        d2b = MathTex(r"\tan\theta = \frac{y}{x}").scale(1.1).shift(DOWN * 1.1)
        self.play(Write(d2b))
        self.wait(2)
        d3 = Tex("No triangle needed — works past $90^\\circ$").scale(1.05).shift(DOWN * 2.1)
        self.play(Write(d3))
        self.wait(2.5)

        # --- Band 1 (subtopic_1): deriving the two identities
        self.next_band(1)
        b1_title = Tex("The two identities every proof leans on").scale(1.15).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l1a = MathTex(r"\frac{\sin\theta}{\cos\theta} = \frac{y}{r} \div \frac{x}{r}").scale(1.05).shift(band_shift(1) + UP * 1.25)
        self.play(Write(b1_l1a))
        self.wait(2)
        b1_l1b = MathTex(r"= \frac{y}{x} = \tan\theta").scale(1.05).shift(band_shift(1) + UP * 0.5)
        self.play(Write(b1_l1b))
        self.wait(2)
        b1_l2 = MathTex(r"x^2 + y^2 = r^2 \;\;\text{(Pythagoras)}").scale(1.1).shift(band_shift(1) + DOWN * 0.3)
        b1_l3 = MathTex(r"\div r^2: \quad \cos^2\theta + \sin^2\theta = 1").scale(1.1).shift(band_shift(1) + DOWN * 1.1)
        self.play(Write(b1_l2))
        self.wait(2)
        self.play(Write(b1_l3))
        self.play(Create(SurroundingRectangle(b1_l3, color=GREEN)))
        self.wait(2.5)
        b1_l4 = MathTex(r"\sin^2\theta = 1 - \cos^2\theta").scale(1.0).shift(band_shift(1) + DOWN * 2.0)
        b1_l4b = MathTex(r"\cos^2\theta = 1 - \sin^2\theta").scale(1.0).shift(band_shift(1) + DOWN * 2.75)
        self.play(Write(b1_l4))
        self.wait(1.5)
        self.play(Write(b1_l4b))
        self.wait(2)

        # --- Band 2 (subtopic_1): first use, and where tangent breaks
        self.next_band(2)
        b2_title = Tex(r"Simplify $(1 - \sin^2\theta)\tan\theta$").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(1.5)
        b2_l1 = MathTex(r"= \cos^2\theta \times \frac{\sin\theta}{\cos\theta}").scale(1.1).shift(band_shift(2) + UP * 1.0)
        b2_l2 = MathTex(r"= \sin\theta\cos\theta").scale(1.15).shift(band_shift(2))
        self.play(Write(b2_l1))
        self.wait(2.5)
        self.play(Write(b2_l2))
        self.play(Create(SurroundingRectangle(b2_l2, color=GREEN)))
        self.wait(2)
        b2_l3 = Tex(r"$\tan\theta$ does not exist where $\cos\theta = 0$").scale(1.05).shift(band_shift(2) + DOWN * 1.2)
        b2_l4 = MathTex(r"\theta \neq 90^\circ, \; 270^\circ \; (+ \text{ full turns})").scale(1.05).shift(band_shift(2) + DOWN * 2.2)
        self.play(Write(b2_l3))
        self.wait(2)
        self.play(Write(b2_l4))
        self.wait(2.5)

        # --- Band 3 (subtopic_2): the CAST rule, drawn on axes
        self.next_band(3)
        b3_title = Tex("Signs in the four quadrants — CAST").scale(1.15).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(1.5)
        ax_h = Arrow(LEFT * 3, RIGHT * 3, buff=0, stroke_width=4).shift(band_shift(3) + DOWN * 0.6)
        ax_v = Arrow(DOWN * 2.6, UP * 1.4, buff=0, stroke_width=4).shift(band_shift(3) + DOWN * 0.6)
        self.play(Create(ax_h), Create(ax_v))
        self.wait(1.5)
        q_a = Tex("A: all $+$").scale(1.0).shift(band_shift(3) + UP * 0.2 + RIGHT * 1.7)
        q_s = Tex("S: sine $+$").scale(1.0).shift(band_shift(3) + UP * 0.2 + LEFT * 1.7)
        q_t = Tex("T: tan $+$").scale(1.0).shift(band_shift(3) + DOWN * 1.6 + LEFT * 1.7)
        q_c = Tex("C: cos $+$").scale(1.0).shift(band_shift(3) + DOWN * 1.6 + RIGHT * 1.7)
        self.play(Write(q_a))
        self.wait(1.5)
        self.play(Write(q_s))
        self.wait(1.5)
        self.play(Write(q_t))
        self.wait(1.5)
        self.play(Write(q_c))
        self.wait(1.5)
        b3_rule = Tex("The letter names the only positive ratio there").scale(1.0).shift(band_shift(3) + DOWN * 2.9)
        self.play(Write(b3_rule))
        self.wait(2.5)

        # --- Band 4 (subtopic_2): the sketch method
        self.next_band(4)
        b4_title = Tex(r"$\sin\theta = \tfrac{3}{5}$, obtuse: $\cos\theta$? $\tan\theta$?").scale(1.05).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(2)
        b4_l1 = Tex("Obtuse $=$ second quadrant: mark it first").scale(1.05).shift(band_shift(4) + UP * 1.1)
        b4_l2 = MathTex(r"y = 3, \quad r = 5").scale(1.1).shift(band_shift(4) + UP * 0.2)
        b4_l3 = MathTex(r"x^2 = 25 - 9 = 16 \;\Rightarrow\; x = -4 \;\text{(west!)}").scale(1.05).shift(band_shift(4) + DOWN * 0.8)
        b4_l4 = MathTex(r"\cos\theta = -\tfrac{4}{5}, \quad \tan\theta = -\tfrac{3}{4}").scale(1.1).shift(band_shift(4) + DOWN * 1.8)
        self.play(Write(b4_l1))
        self.wait(2)
        self.play(Write(b4_l2))
        self.wait(2)
        self.play(Write(b4_l3))
        self.wait(2.5)
        self.play(Write(b4_l4))
        self.play(Create(SurroundingRectangle(b4_l4, color=GREEN)))
        b4_rule = Tex("The quadrant decides the sign — never guess it").scale(1.0).shift(band_shift(4) + DOWN * 2.8)
        self.play(Write(b4_rule))
        self.wait(2.5)

        # --- Band 5 (subtopic_3): the three reduction families
        self.next_band(5)
        b5_title = Tex("Reduction formulae — three families").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(1.5)
        b5_l1 = MathTex(r"180^\circ - \theta \text{ (Q2)}: \sin \to +, \; \cos, \tan \to -").scale(1.0).shift(band_shift(5) + UP * 1.1)
        b5_l2 = MathTex(r"180^\circ + \theta \text{ (Q3)}: \tan \to +, \; \sin, \cos \to -").scale(1.0).shift(band_shift(5) + UP * 0.2)
        b5_l3 = MathTex(r"360^\circ - \theta \text{ (Q4)}: \cos \to +, \; \sin, \tan \to -").scale(1.0).shift(band_shift(5) + DOWN * 0.7)
        self.play(Write(b5_l1))
        self.wait(2.5)
        self.play(Write(b5_l2))
        self.wait(2.5)
        self.play(Write(b5_l3))
        self.wait(2.5)
        b5_l4 = MathTex(r"\sin(-\theta) = -\sin\theta, \quad \cos(-\theta) = \cos\theta").scale(1.0).shift(band_shift(5) + DOWN * 1.7)
        b5_l5 = Tex("Size from the acute angle, sign from the quadrant").scale(1.0).shift(band_shift(5) + DOWN * 2.7)
        self.play(Write(b5_l4))
        self.wait(2)
        self.play(Write(b5_l5))
        self.wait(2.5)

        # --- Band 6 (subtopic_3): the machine applied
        self.next_band(6)
        b6_title = Tex("Reduce, then read the sign").scale(1.15).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(1.5)
        b6_l1a = MathTex(r"\cos 120^\circ = \cos(180^\circ - 60^\circ)").scale(1.0).shift(band_shift(6) + UP * 1.2)
        b6_l1b = MathTex(r"= -\cos 60^\circ = -\tfrac{1}{2}").scale(1.0).shift(band_shift(6) + UP * 0.45)
        b6_l2a = MathTex(r"\sin 210^\circ = \sin(180^\circ + 30^\circ)").scale(1.0).shift(band_shift(6) + DOWN * 0.35)
        b6_l2b = MathTex(r"= -\sin 30^\circ = -\tfrac{1}{2}").scale(1.0).shift(band_shift(6) + DOWN * 1.1)
        b6_l3a = MathTex(r"\tan 300^\circ = \tan(360^\circ - 60^\circ)").scale(1.0).shift(band_shift(6) + DOWN * 1.9)
        b6_l3b = MathTex(r"= -\tan 60^\circ = -\sqrt{3}").scale(1.0).shift(band_shift(6) + DOWN * 2.65)
        self.play(Write(b6_l1a))
        self.wait(1.5)
        self.play(Write(b6_l1b))
        self.wait(1.5)
        self.play(Write(b6_l2a))
        self.wait(1.5)
        self.play(Write(b6_l2b))
        self.wait(1.5)
        self.play(Write(b6_l3a))
        self.wait(1.5)
        self.play(Write(b6_l3b))
        self.wait(2)

        # --- Band 7 (subtopic_3): combined evaluation, no calculator
        self.next_band(7)
        b7_title = Tex(r"Evaluate $\sin 150^\circ \times \tan 225^\circ$").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(1.5)
        b7_l1a = MathTex(r"\sin 150^\circ = \sin(180^\circ - 30^\circ)").scale(1.0).shift(band_shift(7) + UP * 1.2)
        b7_l1b = MathTex(r"= \sin 30^\circ = \tfrac{1}{2}").scale(1.0).shift(band_shift(7) + UP * 0.45)
        b7_l2a = MathTex(r"\tan 225^\circ = \tan(180^\circ + 45^\circ)").scale(1.0).shift(band_shift(7) + DOWN * 0.35)
        b7_l2b = MathTex(r"= \tan 45^\circ = 1").scale(1.0).shift(band_shift(7) + DOWN * 1.1)
        b7_l3 = MathTex(r"\tfrac{1}{2} \times 1 = \tfrac{1}{2}").scale(1.15).shift(band_shift(7) + DOWN * 1.95)
        self.play(Write(b7_l1a))
        self.wait(1.5)
        self.play(Write(b7_l1b))
        self.wait(1.5)
        self.play(Write(b7_l2a))
        self.wait(1.5)
        self.play(Write(b7_l2b))
        self.wait(1.5)
        self.play(Write(b7_l3))
        self.play(Create(SurroundingRectangle(b7_l3, color=GREEN)))
        b7_rule = Tex("Quadrant first, sign second, acute angle last").scale(1.0).shift(band_shift(7) + DOWN * 2.85)
        self.play(Write(b7_rule))
        self.wait(2.5)

        # --- Band 8 (subtopic_4): co-functions — ninety swaps
        self.next_band(8)
        b8_title = Tex("Ninety degrees swaps the function").scale(1.15).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(1.5)
        b8_l1a = MathTex(r"\sin(90^\circ - \theta) = \cos\theta").scale(1.0).shift(band_shift(8) + UP * 1.2)
        b8_l1b = MathTex(r"\cos(90^\circ - \theta) = \sin\theta").scale(1.0).shift(band_shift(8) + UP * 0.45)
        b8_l2a = MathTex(r"\sin(90^\circ + \theta) = \cos\theta").scale(1.0).shift(band_shift(8) + DOWN * 0.3)
        b8_l2b = MathTex(r"\cos(90^\circ + \theta) = -\sin\theta").scale(1.0).shift(band_shift(8) + DOWN * 1.05)
        self.play(Write(b8_l1a))
        self.wait(1.5)
        self.play(Write(b8_l1b))
        self.wait(1.5)
        self.play(Write(b8_l2a))
        self.wait(1.5)
        self.play(Write(b8_l2b))
        self.wait(1.5)
        b8_l3 = Tex(r"$180^\circ$/$360^\circ$: keep the function, fix the sign").scale(1.0).shift(band_shift(8) + DOWN * 1.9)
        b8_l4 = Tex(r"$90^\circ$: swap sin and cos, the quadrant signs it").scale(1.0).shift(band_shift(8) + DOWN * 2.75)
        self.play(Write(b8_l3))
        self.wait(2)
        self.play(Write(b8_l4))
        self.wait(2.5)

        # --- Band 9 (subtopic_4): the full simplification chain
        self.next_band(9)
        b9_title = Tex("Simplify a reduction fraction").scale(1.15).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(1.5)
        b9_l0a = MathTex(r"\text{num} = \sin(180^\circ + x)\cos(360^\circ - x)\tan(-x)").scale(0.95).shift(band_shift(9) + UP * 1.35)
        b9_l0b = MathTex(r"\text{den} = \cos(90^\circ - x)\sin(90^\circ + x)").scale(0.95).shift(band_shift(9) + UP * 0.55)
        self.play(Write(b9_l0a))
        self.wait(2)
        self.play(Write(b9_l0b))
        self.wait(2)
        b9_l1 = MathTex(r"\text{num} = (-\sin x)(\cos x)(-\tan x)").scale(1.0).shift(band_shift(9) + DOWN * 0.25)
        b9_l2 = MathTex(r"= \sin x \cos x \times \frac{\sin x}{\cos x} = \sin^2 x").scale(1.0).shift(band_shift(9) + DOWN * 1.05)
        b9_l3 = MathTex(r"\text{den} = \sin x \cos x").scale(1.0).shift(band_shift(9) + DOWN * 1.85)
        b9_l4 = MathTex(r"\frac{\sin^2 x}{\sin x \cos x} = \frac{\sin x}{\cos x} = \tan x").scale(1.0).shift(band_shift(9) + DOWN * 2.7)
        self.play(Write(b9_l1))
        self.wait(2)
        self.play(Write(b9_l2))
        self.wait(2)
        self.play(Write(b9_l3))
        self.wait(2)
        self.play(Write(b9_l4))
        self.play(Create(SurroundingRectangle(b9_l4, color=GREEN)))
        self.wait(3)

        # --- Band 10 (subtopic_4): proving an identity, and where it holds
        self.next_band(10)
        b10_title = Tex("Prove:").scale(1.15).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_title))
        self.wait(1)
        b10_eq = MathTex(r"\frac{\sin x}{1+\cos x} + \frac{1+\cos x}{\sin x} = \frac{2}{\sin x}").scale(0.95).shift(band_shift(10) + UP * 1.35)
        self.play(Write(b10_eq))
        self.wait(2)
        b10_l1 = MathTex(r"\text{LHS} = \frac{\sin^2 x + (1+\cos x)^2}{\sin x(1+\cos x)}").scale(1.0).shift(band_shift(10) + UP * 0.4)
        b10_l2 = MathTex(r"\sin^2 x + \cos^2 x = 1: \; \text{top} = 2 + 2\cos x").scale(1.0).shift(band_shift(10) + DOWN * 0.5)
        b10_l3 = MathTex(r"= \frac{2(1+\cos x)}{\sin x(1+\cos x)} = \frac{2}{\sin x}").scale(1.0).shift(band_shift(10) + DOWN * 1.4)
        self.play(Write(b10_l1))
        self.wait(2.5)
        self.play(Write(b10_l2))
        self.wait(2.5)
        self.play(Write(b10_l3))
        self.play(Create(SurroundingRectangle(b10_l3, color=GREEN)))
        self.wait(2.5)
        b10_l4 = Tex(r"Valid where no denominator dies: $x \neq k \times 180^\circ$").scale(1.0).shift(band_shift(10) + DOWN * 2.6)
        self.play(Write(b10_l4))
        self.wait(2.5)

        # ============ Part 2 — Simplifier ============
        # --- Band 11 (subtopic_5): the spoke and the shadow
        self.next_band(11)
        b11_title = Tex("The spoke and the shadow").scale(1.2).shift(band_shift(11) + UP * 2.2)
        self.play(Write(b11_title))
        self.wait(2)
        wheel = Circle(radius=1.4, color=WHITE).shift(band_shift(11) + DOWN * 0.9 + LEFT * 3.2)
        spoke = Arrow(ORIGIN, UP * 0.9 + LEFT * 1.05, buff=0, color=RED, stroke_width=5).shift(band_shift(11) + DOWN * 0.9 + LEFT * 3.2)
        tip = Dot(band_shift(11) + DOWN * 0.9 + LEFT * 3.2 + UP * 0.9 + LEFT * 1.05, color=RED)
        self.play(Create(wheel))
        self.play(Create(spoke), Create(tip))
        self.wait(2)
        b11_l1 = Tex("Sine $=$ north-south share").scale(1.0).shift(band_shift(11) + UP * 0.4 + RIGHT * 2.6)
        b11_l2 = Tex("Cosine $=$ east-west share").scale(1.0).shift(band_shift(11) + DOWN * 0.5 + RIGHT * 2.6)
        b11_l3 = Tex("Spoke length $r$ never changes").scale(1.0).shift(band_shift(11) + DOWN * 1.4 + RIGHT * 2.6)
        self.play(Write(b11_l1))
        self.wait(2)
        self.play(Write(b11_l2))
        self.wait(2)
        self.play(Write(b11_l3))
        self.wait(2)
        b11_l4 = Tex(r"Pythagoras on the spoke: $\sin^2\theta + \cos^2\theta = 1$").scale(1.0).shift(band_shift(11) + DOWN * 2.6)
        self.play(Write(b11_l4))
        self.play(Create(SurroundingRectangle(b11_l4, color=GREEN)))
        self.wait(3)

        # --- Band 12 (subtopic_6): four neighbourhoods, one rule
        self.next_band(12)
        b12_title = Tex("Four neighbourhoods, one rule").scale(1.2).shift(band_shift(12) + UP * 2.2)
        self.play(Write(b12_title))
        self.wait(2)
        b12_l1 = Tex("C, A, S, T from the fourth quarter round").scale(1.0).shift(band_shift(12) + UP * 1.1)
        self.play(Write(b12_l1))
        self.wait(2.5)
        b12_l2 = Tex(r"$\sin\theta = \tfrac{3}{5}$, obtuse: tip 3 north on a spoke of 5").scale(1.0).shift(band_shift(12) + UP * 0.2)
        b12_l3 = MathTex(r"5^2 - 3^2 = 16 \;\Rightarrow\; 4 \text{ units west: } x = -4").scale(1.0).shift(band_shift(12) + DOWN * 0.8)
        b12_l4 = MathTex(r"\cos\theta = -\tfrac{4}{5}, \quad \tan\theta = -\tfrac{3}{4}").scale(1.05).shift(band_shift(12) + DOWN * 1.8)
        self.play(Write(b12_l2))
        self.wait(2.5)
        self.play(Write(b12_l3))
        self.wait(2.5)
        self.play(Write(b12_l4))
        self.play(Create(SurroundingRectangle(b12_l4, color=GREEN)))
        b12_rule = Tex("The sketch is the calculator").scale(1.0).shift(band_shift(12) + DOWN * 2.8)
        self.play(Write(b12_rule))
        self.wait(3)

        # --- Band 13 (subtopic_7): folding the angle back home
        self.next_band(13)
        b13_title = Tex("Folding the angle back home").scale(1.2).shift(band_shift(13) + UP * 2.2)
        self.play(Write(b13_title))
        self.wait(2)
        b13_l1 = Tex("Home angle, then quarter, then sign").scale(1.0).shift(band_shift(13) + UP * 1.1)
        self.play(Write(b13_l1))
        self.wait(2.5)
        b13_l2 = MathTex(r"\cos 120^\circ: 60^\circ, \text{Q2} \Rightarrow -\tfrac{1}{2}").scale(1.0).shift(band_shift(13) + UP * 0.2)
        b13_l3 = MathTex(r"\sin 210^\circ: 30^\circ, \text{Q3} \Rightarrow -\tfrac{1}{2}").scale(1.0).shift(band_shift(13) + DOWN * 0.7)
        b13_l4 = MathTex(r"\tan 225^\circ: 45^\circ, \text{Q3} \Rightarrow +1").scale(1.0).shift(band_shift(13) + DOWN * 1.6)
        self.play(Write(b13_l2))
        self.wait(2.5)
        self.play(Write(b13_l3))
        self.wait(2.5)
        self.play(Write(b13_l4))
        self.play(Create(SurroundingRectangle(b13_l4, color=GREEN)))
        self.wait(2.5)
        b13_l5 = Tex(r"Swap at $90^\circ$: $\sin(90^\circ - \theta) = \cos\theta$").scale(1.0).shift(band_shift(13) + DOWN * 2.7)
        self.play(Write(b13_l5))
        self.wait(4)
