from manim import *

# Band-layout whiteboard scene for the Probability: Games, Lotteries and Risk
# session duo. One band per teaching beat; the camera moves down to fresh
# space and earlier work stays on the canvas. Exporter-supported mobjects
# only (Tex/MathTex/Line/Arrow/Dot/Circle/Rectangle); every line of working
# is its own single-string Tex/MathTex revealed with Write — no sub-part
# transforms, no FadeOut.
#
# Subtopic time shares (subtopics.json, total 1470 s):
# 215/215/225/230/195/195/195 -> bands 0-1 / 2-3 / 4-5 / 6-8 / 9 / 10 / 11.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class ProbabilityGamesLotteriesRiskSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic full-screen while intro.md audio plays.
        self.wait(15)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): the language of chance + the 0-to-1 scale
        title = Tex("Probability: Games, Lotteries and Risk").scale(1.25).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        d1 = Tex("Sample space: ALL possible outcomes").scale(1.1).shift(UP * 1.3)
        d2 = Tex("Event: the outcomes you care about").scale(1.1).shift(UP * 0.5)
        self.play(Write(d1))
        self.wait(2)
        self.play(Write(d2))
        self.wait(2)
        scale_line = Line(LEFT * 4.2, RIGHT * 4.2).shift(DOWN * 0.8)
        dot0 = Dot(LEFT * 4.2 + DOWN * 0.8)
        dot_h = Dot(DOWN * 0.8)
        dot1 = Dot(RIGHT * 4.2 + DOWN * 0.8)
        self.play(Create(scale_line))
        self.play(FadeIn(dot0), FadeIn(dot_h), FadeIn(dot1))
        lab0 = Tex("0 impossible").scale(1.0).shift(LEFT * 4.2 + DOWN * 1.5)
        lab_h = Tex("0,5").scale(1.0).shift(DOWN * 1.5)
        lab1 = Tex("1 certain").scale(1.0).shift(RIGHT * 4.2 + DOWN * 1.5)
        self.play(Write(lab0))
        self.play(Write(lab_h))
        self.play(Write(lab1))
        self.wait(2)
        d3 = Tex("Fraction, decimal or percentage: same chance").scale(1.05).shift(DOWN * 2.5)
        self.play(Write(d3))
        self.wait(3)

        # --- Band 1 (subtopic_1): count and divide, plus the NOT rule
        self.next_band(1)
        b1_t = Tex("Equally likely outcomes: count and divide").scale(1.15).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_t))
        self.wait(1.5)
        b1_l1 = MathTex(r"P(\text{event}) = \frac{\text{favourable}}{\text{total}}").scale(1.15).shift(band_shift(1) + UP * 1.0)
        b1_l2 = MathTex(r"P(\text{six}) = \tfrac{1}{6} \approx 0{,}17").scale(1.1).shift(band_shift(1) + UP * 0.1)
        b1_l3 = MathTex(r"P(\text{even}) = \tfrac{3}{6} = 0{,}5").scale(1.1).shift(band_shift(1) + DOWN * 0.8)
        b1_l4 = MathTex(r"P(\text{red card}) = \tfrac{26}{52} = 0{,}5").scale(1.1).shift(band_shift(1) + DOWN * 1.7)
        b1_l5 = MathTex(r"P(\text{not six}) = 1 - \tfrac{1}{6} = \tfrac{5}{6}").scale(1.1).shift(band_shift(1) + DOWN * 2.7)
        self.play(Write(b1_l1))
        self.wait(2.5)
        self.play(Write(b1_l2))
        self.wait(2)
        self.play(Write(b1_l3))
        self.wait(2)
        self.play(Write(b1_l4))
        self.wait(2)
        self.play(Write(b1_l5))
        self.play(Create(SurroundingRectangle(b1_l5, color=GREEN)))
        self.wait(3)

        # --- Band 2 (subtopic_2): theoretical probability vs relative frequency
        self.next_band(2)
        b2_t = Tex("Two honest ways to measure chance").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(1.5)
        b2_l1 = Tex("Theoretical: reason BEFORE the experiment").scale(1.05).shift(band_shift(2) + UP * 1.2)
        b2_l2 = MathTex(r"P(\text{heads}) = \tfrac{1}{2} = 0{,}5").scale(1.1).shift(band_shift(2) + UP * 0.3)
        self.play(Write(b2_l1))
        self.wait(2)
        self.play(Write(b2_l2))
        self.wait(2)
        b2_l3 = Tex("Relative frequency: DO the experiment").scale(1.05).shift(band_shift(2) + DOWN * 0.6)
        b2_l4 = MathTex(r"RF = \frac{\text{times it occurred}}{\text{number of trials}}").scale(1.06).shift(band_shift(2) + DOWN * 1.6)
        b2_l5 = MathTex(r"\text{100 tosses, 58 heads: } \tfrac{58}{100} = 0{,}58").scale(1.05).shift(band_shift(2) + DOWN * 2.7)
        self.play(Write(b2_l3))
        self.wait(2)
        self.play(Write(b2_l4))
        self.wait(2.5)
        self.play(Write(b2_l5))
        self.wait(3)

        # --- Band 3 (subtopic_2): where theory cannot reach + fairness
        self.next_band(3)
        b3_t = Tex("No symmetry? Then observe").scale(1.15).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t))
        self.wait(1.5)
        b3_l1 = Tex("40 recorded taxi trips, 12 were late").scale(1.1).shift(band_shift(3) + UP * 1.1)
        b3_l2 = MathTex(r"P(\text{late}) = \tfrac{12}{40} = 0{,}3").scale(1.15).shift(band_shift(3) + UP * 0.1)
        self.play(Write(b3_l1))
        self.wait(2)
        self.play(Write(b3_l2))
        self.play(Create(SurroundingRectangle(b3_l2, color=GREEN)))
        self.wait(2.5)
        b3_l3 = Tex("More trials: frequency drifts to theory").scale(1.05).shift(band_shift(3) + DOWN * 0.9)
        b3_l4 = Tex("Fair game: equal chance for each player").scale(1.05).shift(band_shift(3) + DOWN * 1.8)
        b3_l5 = Tex("Six up 30 times in 60 rolls? Suspect the die").scale(1.05).shift(band_shift(3) + DOWN * 2.7)
        self.play(Write(b3_l3))
        self.wait(2)
        self.play(Write(b3_l4))
        self.wait(2)
        self.play(Write(b3_l5))
        self.wait(3)

        # --- Band 4 (subtopic_3): the lottery long shot
        self.next_band(4)
        b4_t = Tex("The lottery: six numbers from 52").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(1.5)
        b4_l1 = MathTex(r"P(\text{jackpot}) = \frac{1}{20\;358\;520}").scale(1.15).shift(band_shift(4) + UP * 1.0)
        self.play(Write(b4_l1))
        self.play(Create(SurroundingRectangle(b4_l1, color=GREEN)))
        self.wait(2.5)
        b4_l2 = Tex("One board a week: a win in 390 000 years").scale(1.05).shift(band_shift(4) + DOWN * 0.2)
        b4_l3 = Tex("Millions of boards sold, so SOMEONE wins").scale(1.05).shift(band_shift(4) + DOWN * 1.1)
        b4_l4 = Tex("Every game: price, prize, probability").scale(1.05).shift(band_shift(4) + DOWN * 2.0)
        b4_l5 = Tex("The long-run average favours the operator").scale(1.05).shift(band_shift(4) + DOWN * 2.9)
        self.play(Write(b4_l2))
        self.wait(2.5)
        self.play(Write(b4_l3))
        self.wait(2)
        self.play(Write(b4_l4))
        self.wait(2)
        self.play(Write(b4_l5))
        self.wait(3)

        # --- Band 5 (subtopic_3): insurance — the same maths reversed
        self.next_band(5)
        b5_t = Tex("Insurance: the same maths, reversed").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_t))
        self.wait(1.5)
        b5_l1 = Tex("Many small premiums pay a few large claims").scale(1.05).shift(band_shift(5) + UP * 1.1)
        b5_l2 = Tex("Premiums set by risk assessment: claim data").scale(1.05).shift(band_shift(5) + UP * 0.2)
        b5_l3 = Tex("Young drivers claim more: higher premium").scale(1.05).shift(band_shift(5) + DOWN * 0.7)
        b5_l4 = Tex("Gambler pays small to maybe WIN big").scale(1.05).shift(band_shift(5) + DOWN * 1.6)
        b5_l5 = Tex("Insured pays small to cancel LOSING big").scale(1.05).shift(band_shift(5) + DOWN * 2.5)
        self.play(Write(b5_l1))
        self.wait(2.5)
        self.play(Write(b5_l2))
        self.wait(2)
        self.play(Write(b5_l3))
        self.wait(2)
        self.play(Write(b5_l4))
        self.wait(2)
        self.play(Write(b5_l5))
        self.play(Create(SurroundingRectangle(b5_l5, color=GREEN)))
        self.wait(3)

        # --- Band 6 (subtopic_4): the tree diagram, drawn branch by branch
        self.next_band(6)
        b6_t = Tex("Tree diagram: rain, then the taxi").scale(1.15).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_t))
        self.wait(1.5)
        root = Dot(band_shift(6) + LEFT * 5.0 + DOWN * 0.5)
        n_rain = Dot(band_shift(6) + LEFT * 1.6 + UP * 0.7)
        n_dry = Dot(band_shift(6) + LEFT * 1.6 + DOWN * 1.7)
        self.play(FadeIn(root))
        br_rain = Line(root.get_center(), n_rain.get_center())
        br_dry = Line(root.get_center(), n_dry.get_center())
        lab_rain = Tex("rain 0,3").scale(1.0).shift(band_shift(6) + LEFT * 3.6 + UP * 0.8)
        lab_dry = Tex("dry 0,7").scale(1.0).shift(band_shift(6) + LEFT * 3.6 + DOWN * 1.8)
        self.play(Create(br_rain), FadeIn(n_rain))
        self.play(Write(lab_rain))
        self.play(Create(br_dry), FadeIn(n_dry))
        self.play(Write(lab_dry))
        self.wait(2)
        note1 = Tex("Branches from one fork add to 1").scale(1.0).shift(band_shift(6) + LEFT * 3.0 + DOWN * 2.9)
        self.play(Write(note1))
        self.wait(2)
        e1 = Dot(band_shift(6) + RIGHT * 1.8 + UP * 1.4)
        e2 = Dot(band_shift(6) + RIGHT * 1.8 + UP * 0.1)
        e3 = Dot(band_shift(6) + RIGHT * 1.8 + DOWN * 1.1)
        e4 = Dot(band_shift(6) + RIGHT * 1.8 + DOWN * 2.4)
        self.play(Create(Line(n_rain.get_center(), e1.get_center())), FadeIn(e1))
        self.play(Create(Line(n_rain.get_center(), e2.get_center())), FadeIn(e2))
        self.play(Create(Line(n_dry.get_center(), e3.get_center())), FadeIn(e3))
        self.play(Create(Line(n_dry.get_center(), e4.get_center())), FadeIn(e4))
        lab_e1 = Tex("late 0,6").scale(1.0).shift(band_shift(6) + RIGHT * 3.6 + UP * 1.4)
        lab_e2 = Tex("on time 0,4").scale(1.0).shift(band_shift(6) + RIGHT * 3.9 + UP * 0.1)
        lab_e3 = Tex("late 0,2").scale(1.0).shift(band_shift(6) + RIGHT * 3.6 + DOWN * 1.1)
        lab_e4 = Tex("on time 0,8").scale(1.0).shift(band_shift(6) + RIGHT * 3.9 + DOWN * 2.4)
        self.play(Write(lab_e1))
        self.play(Write(lab_e2))
        self.play(Write(lab_e3))
        self.play(Write(lab_e4))
        self.wait(3)

        # --- Band 7 (subtopic_4): multiply along, add across
        self.next_band(7)
        b7_t = Tex("Multiply along branches, add between paths").scale(1.1).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(1.5)
        b7_l1 = MathTex(r"P(\text{rain and late}) = 0{,}3 \times 0{,}6 = 0{,}18").scale(1.05).shift(band_shift(7) + UP * 1.1)
        b7_l2 = MathTex(r"P(\text{dry and late}) = 0{,}7 \times 0{,}2 = 0{,}14").scale(1.05).shift(band_shift(7) + UP * 0.2)
        b7_l3 = MathTex(r"P(\text{late}) = 0{,}18 + 0{,}14 = 0{,}32").scale(1.1).shift(band_shift(7) + DOWN * 0.8)
        self.play(Write(b7_l1))
        self.wait(2.5)
        self.play(Write(b7_l2))
        self.wait(2.5)
        self.play(Write(b7_l3))
        self.play(Create(SurroundingRectangle(b7_l3, color=GREEN)))
        self.wait(2.5)
        b7_l4 = Tex("Just under a one-in-three chance").scale(1.05).shift(band_shift(7) + DOWN * 1.8)
        b7_l5 = MathTex(r"\text{Check: } 0{,}18 + 0{,}12 + 0{,}14 + 0{,}56 = 1").scale(1.0).shift(band_shift(7) + DOWN * 2.8)
        self.play(Write(b7_l4))
        self.wait(2)
        self.play(Write(b7_l5))
        self.wait(3)

        # --- Band 8 (subtopic_4): two-way table and the shrinking pool
        self.next_band(8)
        b8_t = Tex("Two-way table: 100 tested vehicles").scale(1.15).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_t))
        self.wait(1.5)
        frame = Rectangle(width = 9.4, height = 3.0).shift(band_shift(8) + UP * 0.3)
        h1 = Line(LEFT * 4.7, RIGHT * 4.7).shift(band_shift(8) + UP * 1.05)
        h2 = Line(LEFT * 4.7, RIGHT * 4.7).shift(band_shift(8) + UP * 0.3)
        h3 = Line(LEFT * 4.7, RIGHT * 4.7).shift(band_shift(8) + DOWN * 0.45)
        v1 = Line(UP * 1.5, DOWN * 1.5).shift(band_shift(8) + UP * 0.3 + LEFT * 2.0)
        v2 = Line(UP * 1.5, DOWN * 1.5).shift(band_shift(8) + UP * 0.3 + RIGHT * 0.3)
        v3 = Line(UP * 1.5, DOWN * 1.5).shift(band_shift(8) + UP * 0.3 + RIGHT * 2.5)
        self.play(Create(frame))
        self.play(Create(h1), Create(h2), Create(h3))
        self.play(Create(v1), Create(v2), Create(v3))
        c_pass = Tex("Pass").scale(1.0).shift(band_shift(8) + UP * 1.42 + LEFT * 0.85)
        c_fail = Tex("Fail").scale(1.0).shift(band_shift(8) + UP * 1.42 + RIGHT * 1.4)
        c_tot = Tex("Total").scale(1.0).shift(band_shift(8) + UP * 1.42 + RIGHT * 3.5)
        self.play(Write(c_pass), Write(c_fail), Write(c_tot))
        r1 = Tex("Minibus").scale(1.0).shift(band_shift(8) + UP * 0.68 + LEFT * 3.3)
        r1a = Tex("24").scale(1.0).shift(band_shift(8) + UP * 0.68 + LEFT * 0.85)
        r1b = Tex("16").scale(1.0).shift(band_shift(8) + UP * 0.68 + RIGHT * 1.4)
        r1c = Tex("40").scale(1.0).shift(band_shift(8) + UP * 0.68 + RIGHT * 3.5)
        self.play(Write(r1), Write(r1a), Write(r1b), Write(r1c))
        r2 = Tex("Car").scale(1.0).shift(band_shift(8) + DOWN * 0.08 + LEFT * 3.3)
        r2a = Tex("48").scale(1.0).shift(band_shift(8) + DOWN * 0.08 + LEFT * 0.85)
        r2b = Tex("12").scale(1.0).shift(band_shift(8) + DOWN * 0.08 + RIGHT * 1.4)
        r2c = Tex("60").scale(1.0).shift(band_shift(8) + DOWN * 0.08 + RIGHT * 3.5)
        self.play(Write(r2), Write(r2a), Write(r2b), Write(r2c))
        r3 = Tex("Total").scale(1.0).shift(band_shift(8) + DOWN * 0.85 + LEFT * 3.3)
        r3a = Tex("72").scale(1.0).shift(band_shift(8) + DOWN * 0.85 + LEFT * 0.85)
        r3b = Tex("28").scale(1.0).shift(band_shift(8) + DOWN * 0.85 + RIGHT * 1.4)
        r3c = Tex("100").scale(1.0).shift(band_shift(8) + DOWN * 0.85 + RIGHT * 3.5)
        self.play(Write(r3), Write(r3a), Write(r3b), Write(r3c))
        self.wait(2.5)
        b8_l1 = MathTex(r"P(\text{fail}) = \tfrac{28}{100} = 0{,}28").scale(1.05).shift(band_shift(8) + DOWN * 1.9)
        b8_l2 = MathTex(r"\text{Of the minibuses: } \tfrac{16}{40} = 0{,}4").scale(1.05).shift(band_shift(8) + DOWN * 2.8)
        self.play(Write(b8_l1))
        self.wait(2.5)
        self.play(Write(b8_l2))
        self.play(Create(SurroundingRectangle(b8_l2, color=GREEN)))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 9 (subtopic_5): the ruler of chance + the NOT trick
        self.next_band(9)
        b9_t = Tex("Chance is a ruler from 0 to 1").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(1.5)
        r_line = Line(LEFT * 4.2, RIGHT * 4.2).shift(band_shift(9) + UP * 1.0)
        rd0 = Dot(band_shift(9) + LEFT * 4.2 + UP * 1.0)
        rdh = Dot(band_shift(9) + UP * 1.0)
        rd1 = Dot(band_shift(9) + RIGHT * 4.2 + UP * 1.0)
        self.play(Create(r_line), FadeIn(rd0), FadeIn(rdh), FadeIn(rd1))
        rl0 = Tex("0: a seven on a die").scale(1.0).shift(band_shift(9) + LEFT * 3.6 + UP * 0.3)
        rl1 = Tex("1: sunset tonight").scale(1.0).shift(band_shift(9) + RIGHT * 3.6 + UP * 0.3)
        rlh = Tex("0,5: the fair coin").scale(1.0).shift(band_shift(9) + UP * 1.7)
        self.play(Write(rl0))
        self.play(Write(rlh))
        self.play(Write(rl1))
        self.wait(2.5)
        b9_l1 = MathTex(r"P(\text{six}) = \tfrac{1}{6} \approx 0{,}17").scale(1.05).shift(band_shift(9) + DOWN * 0.7)
        b9_l2 = MathTex(r"\text{NOT trick: } P(\text{no six}) = 1 - \tfrac{1}{6} = \tfrac{5}{6}").scale(1.03).shift(band_shift(9) + DOWN * 1.7)
        b9_l3 = MathTex(r"\text{Rain } 0{,}3 \;\Rightarrow\; \text{dry } 1 - 0{,}3 = 0{,}7").scale(1.05).shift(band_shift(9) + DOWN * 2.7)
        self.play(Write(b9_l1))
        self.wait(2.5)
        self.play(Write(b9_l2))
        self.wait(2.5)
        self.play(Write(b9_l3))
        self.play(Create(SurroundingRectangle(b9_l3, color=GREEN)))
        self.wait(3)

        # --- Band 10 (subtopic_6): the lotto at street level
        self.next_band(10)
        b10_t = Tex("Why the lotto is not a retirement plan").scale(1.15).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_t))
        self.wait(1.5)
        b10_l1 = MathTex(r"\text{One board: } \frac{1}{20\;358\;520}").scale(1.1).shift(band_shift(10) + UP * 1.0)
        self.play(Write(b10_l1))
        self.wait(2.5)
        b10_l2 = Tex("220 full stadiums; one person wins").scale(1.05).shift(band_shift(10) + UP * 0.0)
        b10_l3 = Tex("Someone wins because MILLIONS play").scale(1.05).shift(band_shift(10) + DOWN * 0.9)
        b10_l4 = Tex("About half the stakes return as prizes").scale(1.05).shift(band_shift(10) + DOWN * 1.8)
        b10_l5 = Tex("An R5 ticket buys back under R2,50").scale(1.05).shift(band_shift(10) + DOWN * 2.7)
        self.play(Write(b10_l2))
        self.wait(2.5)
        self.play(Write(b10_l3))
        self.wait(2.5)
        self.play(Write(b10_l4))
        self.wait(2)
        self.play(Write(b10_l5))
        self.play(Create(SurroundingRectangle(b10_l5, color=GREEN)))
        self.wait(3)

        # --- Band 11 (subtopic_7): two steps of chance, compact re-work
        self.next_band(11)
        b11_t = Tex("Two steps: multiply along, add across").scale(1.15).shift(band_shift(11) + UP * 2.2)
        self.play(Write(b11_t))
        self.wait(1.5)
        b11_l1 = MathTex(r"\text{Rain and late: } 0{,}3 \times 0{,}6 = 0{,}18").scale(1.05).shift(band_shift(11) + UP * 1.1)
        b11_l2 = MathTex(r"\text{Dry and late: } 0{,}7 \times 0{,}2 = 0{,}14").scale(1.05).shift(band_shift(11) + UP * 0.2)
        b11_l3 = MathTex(r"\text{Late at all: } 0{,}18 + 0{,}14 = 0{,}32").scale(1.1).shift(band_shift(11) + DOWN * 0.8)
        self.play(Write(b11_l1))
        self.wait(2.5)
        self.play(Write(b11_l2))
        self.wait(2.5)
        self.play(Write(b11_l3))
        self.play(Create(SurroundingRectangle(b11_l3, color=GREEN)))
        self.wait(2.5)
        b11_l4 = MathTex(r"\text{Endpoints: } 0{,}18+0{,}12+0{,}14+0{,}56 = 1").scale(1.0).shift(band_shift(11) + DOWN * 1.8)
        b11_l5 = MathTex(r"\text{Of the 40 minibuses: } \tfrac{16}{40} = 0{,}4").scale(1.05).shift(band_shift(11) + DOWN * 2.8)
        self.play(Write(b11_l4))
        self.wait(2.5)
        self.play(Write(b11_l5))
        self.wait(4)
