# Copyright (c) 2026 ROKCT INTELLIGENCE (PTY) LTD
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from manim import *

# Band-layout whiteboard scene for "Paper 2 Chemistry Essentials" (Part 1 —
# Expert subtopics 1-4, Part 2 — Simplifier subtopics 5-7).
# Exporter-safe mobjects only, write-only reveals, camera moves between bands.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class Paper2ChemistryEssentialsSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): series and functional groups
        title = Tex("Paper 2 Chemistry Essentials").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex("Nine series, each stamped by its group:").scale(1.05).shift(UP * 1.3)
        self.play(Write(b0_l1))
        self.wait(2)
        b0_l2 = Tex("alkane, alkene, alkyne, haloalkane, alcohol,").scale(1.0).shift(UP * 0.5)
        b0_l3 = Tex("aldehyde, ketone, carboxylic acid, ester").scale(1.0).shift(DOWN * 0.2)
        self.play(Write(b0_l2))
        self.play(Write(b0_l3))
        self.wait(2.5)
        b0_l4 = Tex("Homologous series: one general formula,").scale(1.0).shift(DOWN * 1.2)
        b0_l5 = Tex("neighbours differ by CH$_2$").scale(1.05).shift(DOWN * 1.9)
        self.play(Write(b0_l4))
        self.play(Write(b0_l5))
        self.play(Create(SurroundingRectangle(b0_l5, color=GREEN)))
        self.wait(3)

        # --- Band 1 (subtopic_1): naming algorithm and isomers
        self.next_band(1)
        b1_title = Tex("The naming algorithm never changes").scale(1.15).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l1 = Tex("1. Longest chain WITH the functional group").scale(1.0).shift(band_shift(1) + UP * 1.3)
        b1_l2 = Tex("2. Lowest number to the group").scale(1.0).shift(band_shift(1) + UP * 0.6)
        b1_l3 = Tex("3. Substituents alphabetical, with positions").scale(1.0).shift(band_shift(1) + DOWN * 0.1)
        self.play(Write(b1_l1))
        self.wait(1.5)
        self.play(Write(b1_l2))
        self.wait(1.5)
        self.play(Write(b1_l3))
        self.wait(2)
        b1_l4 = Tex("2-methylbutan-1-ol").scale(1.2).shift(band_shift(1) + DOWN * 1.1)
        self.play(Write(b1_l4))
        self.play(Create(SurroundingRectangle(b1_l4, color=GREEN)))
        self.wait(2)
        b1_l5 = Tex("Isomers: chain (skeleton), positional (address),").scale(0.95).shift(band_shift(1) + DOWN * 2.1)
        b1_l6 = Tex("functional (group itself) — same formula, all three").scale(0.95).shift(band_shift(1) + DOWN * 2.8)
        self.play(Write(b1_l5))
        self.play(Write(b1_l6))
        self.wait(3)

        # --- Band 2 (subtopic_1): properties from forces
        self.next_band(2)
        b2_title = Tex("Boiling points argued from forces").scale(1.2).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(1.5)
        b2_l1 = Tex(r"Longer chain: stronger dispersion, bp $\uparrow$").scale(1.05).shift(band_shift(2) + UP * 1.2)
        self.play(Write(b2_l1))
        self.wait(2)
        b2_l2 = Tex(r"Branching: less contact, weaker forces, bp $\downarrow$").scale(1.0).shift(band_shift(2) + UP * 0.4)
        self.play(Write(b2_l2))
        self.wait(2)
        b2_l3 = Tex("H-bonding lifts alcohols and acids").scale(1.05).shift(band_shift(2) + DOWN * 0.5)
        b2_l4 = Tex("above alkanes of similar size").scale(1.05).shift(band_shift(2) + DOWN * 1.2)
        self.play(Write(b2_l3))
        self.play(Write(b2_l4))
        self.wait(2.5)
        b2_l5 = Tex("Stronger forces $=$ lower vapour pressure —").scale(1.0).shift(band_shift(2) + DOWN * 2.2)
        b2_l6 = Tex("the pair travel in opposite directions").scale(1.0).shift(band_shift(2) + DOWN * 2.9)
        self.play(Write(b2_l5))
        self.play(Write(b2_l6))
        self.wait(3)

        # --- Band 3 (subtopic_2): the reaction map
        self.next_band(3)
        b3_title = Tex("The reaction map: count the bonds first").scale(1.15).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(1.5)
        b3_l1 = Tex("Saturated $+$ something entering: SUBSTITUTION").scale(1.0).shift(band_shift(3) + UP * 1.2)
        self.play(Write(b3_l1))
        self.wait(2)
        b3_l2 = Tex("Double bond consumed: ADDITION").scale(1.0).shift(band_shift(3) + UP * 0.4)
        self.play(Write(b3_l2))
        self.wait(2)
        b3_l3 = Tex("Double bond created: ELIMINATION").scale(1.0).shift(band_shift(3) + DOWN * 0.4)
        self.play(Write(b3_l3))
        self.play(Create(SurroundingRectangle(VGroup(b3_l1, b3_l2, b3_l3), color=GREEN)))
        self.wait(2.5)
        b3_l4 = Tex("Bromine water: unsaturated decolourises it").scale(1.0).shift(band_shift(3) + DOWN * 1.5)
        b3_l5 = Tex("quickly (addition); saturated barely reacts").scale(1.0).shift(band_shift(3) + DOWN * 2.2)
        self.play(Write(b3_l4))
        self.play(Write(b3_l5))
        self.wait(3)

        # --- Band 4 (subtopic_2): major product and esterification
        self.next_band(4)
        b4_title = Tex("Major products and the ester ceremony").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(1.5)
        b4_l1 = Tex("H adds to the C already richer in H;").scale(1.0).shift(band_shift(4) + UP * 1.2)
        b4_l2 = Tex("halogen lands on the crowded carbon").scale(1.0).shift(band_shift(4) + UP * 0.5)
        self.play(Write(b4_l1))
        self.play(Write(b4_l2))
        self.wait(2.5)
        b4_l3 = Tex("Propene $+$ HBr: 2-bromopropane (major)").scale(1.0).shift(band_shift(4) + DOWN * 0.4)
        self.play(Write(b4_l3))
        self.play(Create(SurroundingRectangle(b4_l3, color=GREEN)))
        self.wait(2.5)
        b4_l4 = Tex("Ester: acid $+$ alcohol, conc. H$_2$SO$_4$, warm").scale(1.0).shift(band_shift(4) + DOWN * 1.4)
        b4_l5 = Tex("ethanoic acid $+$ ethanol $\\rightarrow$").scale(1.0).shift(band_shift(4) + DOWN * 2.2)
        b4_l6 = Tex("ethyl ethanoate $+$ water").scale(1.05).shift(band_shift(4) + DOWN * 2.9)
        self.play(Write(b4_l4))
        self.wait(2)
        self.play(Write(b4_l5))
        self.play(Write(b4_l6))
        self.wait(3)

        # --- Band 5 (subtopic_3): rates and collision theory
        self.next_band(5)
        b5_title = Tex("Rates: the collision currency").scale(1.2).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(1.5)
        b5_l1 = Tex("Five levers: nature, surface area,").scale(1.0).shift(band_shift(5) + UP * 1.2)
        b5_l2 = Tex("concentration/pressure, temperature, catalyst").scale(1.0).shift(band_shift(5) + UP * 0.5)
        self.play(Write(b5_l1))
        self.play(Write(b5_l2))
        self.wait(2.5)
        b5_l3 = Tex("Rate rises with the frequency of EFFECTIVE").scale(1.0).shift(band_shift(5) + DOWN * 0.4)
        b5_l4 = Tex(r"collisions ($\geq E_a$, correct orientation)").scale(1.0).shift(band_shift(5) + DOWN * 1.1)
        self.play(Write(b5_l3))
        self.play(Write(b5_l4))
        self.wait(2.5)
        b5_l5 = Tex("Catalyst: alternative path, lower $E_a$ —").scale(1.0).shift(band_shift(5) + DOWN * 2.1)
        b5_l6 = Tex("the curve stays; the finish line moves").scale(1.0).shift(band_shift(5) + DOWN * 2.8)
        self.play(Write(b5_l5))
        self.play(Write(b5_l6))
        self.wait(3)

        # --- Band 6 (subtopic_3): the Kc calculation
        self.next_band(6)
        b6_title = Tex(r"H$_2$ + I$_2 \rightleftharpoons$ 2HI: 1,0 mol each, 2 dm$^3$").scale(1.0).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(2)
        b6_l1 = Tex(r"0,2 mol H$_2$ left: 0,8 reacted, 1,6 HI formed").scale(1.0).shift(band_shift(6) + UP * 1.2)
        self.play(Write(b6_l1))
        self.wait(2.5)
        b6_l2 = MathTex(r"[H_2] = [I_2] = 0{,}1, \quad [HI] = 0{,}8").scale(1.05).shift(band_shift(6) + UP * 0.2)
        self.play(Write(b6_l2))
        self.wait(2.5)
        b6_l3 = MathTex(r"K_c = \frac{(0{,}8)^2}{0{,}1 \times 0{,}1} = \frac{0{,}64}{0{,}01}").scale(1.05).shift(band_shift(6) + DOWN * 1.0)
        self.play(Write(b6_l3))
        self.wait(2.5)
        b6_l4 = MathTex(r"K_c = 64").scale(1.2).shift(band_shift(6) + DOWN * 2.2)
        self.play(Write(b6_l4))
        self.play(Create(SurroundingRectangle(b6_l4, color=GREEN)))
        self.wait(2)
        b6_l5 = Tex("Large $K_c$: equilibrium far towards products").scale(1.0).shift(band_shift(6) + DOWN * 3.0)
        self.play(Write(b6_l5))
        self.wait(3)

        # --- Band 7 (subtopic_3): Le Chatelier in three sentences
        self.next_band(7)
        b7_title = Tex("Le Chatelier: oppose the disturbance").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(1.5)
        b7_l1 = Tex("Add reactant: forward favoured").scale(1.05).shift(band_shift(7) + UP * 1.2)
        self.play(Write(b7_l1))
        self.wait(2)
        b7_l2 = Tex("Raise pressure: fewer gas moles favoured").scale(1.05).shift(band_shift(7) + UP * 0.4)
        self.play(Write(b7_l2))
        self.wait(2)
        b7_l3 = Tex("Raise temperature: endothermic favoured —").scale(1.05).shift(band_shift(7) + DOWN * 0.4)
        b7_l4 = Tex(r"and only THIS one changes $K_c$").scale(1.05).shift(band_shift(7) + DOWN * 1.2)
        self.play(Write(b7_l3))
        self.play(Write(b7_l4))
        self.play(Create(SurroundingRectangle(b7_l4, color=GREEN)))
        self.wait(2.5)
        b7_l5 = Tex("Answer shape: disturbance, opposing reaction,").scale(1.0).shift(band_shift(7) + DOWN * 2.2)
        b7_l6 = Tex("shift and its visible result — three sentences").scale(1.0).shift(band_shift(7) + DOWN * 2.9)
        self.play(Write(b7_l5))
        self.play(Write(b7_l6))
        self.wait(3)

        # --- Band 8 (subtopic_4): acids, bases and pH
        self.next_band(8)
        b8_title = Tex("Acids and bases: donors and acceptors").scale(1.15).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(1.5)
        b8_l1 = Tex("Lowry-Bronsted: acid donates a proton,").scale(1.0).shift(band_shift(8) + UP * 1.3)
        b8_l2 = Tex("base accepts one; pairs differ by ONE proton").scale(1.0).shift(band_shift(8) + UP * 0.6)
        self.play(Write(b8_l1))
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = Tex("STRONG $=$ fraction ionised;").scale(1.0).shift(band_shift(8) + DOWN * 0.3)
        b8_l4 = Tex("CONCENTRATED $=$ amount dissolved").scale(1.0).shift(band_shift(8) + DOWN * 1.0)
        self.play(Write(b8_l3))
        self.play(Write(b8_l4))
        self.wait(2.5)
        b8_l5 = MathTex(r"0{,}01\ \text{M HCl: } pH = -\log 10^{-2} = 2").scale(1.0).shift(band_shift(8) + DOWN * 2.0)
        self.play(Write(b8_l5))
        self.wait(2)
        b8_l6 = MathTex(r"0{,}01\ \text{M NaOH: } [H_3O^+] = 10^{-12},\ pH = 12").scale(0.95).shift(band_shift(8) + DOWN * 2.9)
        self.play(Write(b8_l6))
        self.wait(3)

        # --- Band 9 (subtopic_4): titration and the two cells
        self.next_band(9)
        b9_title = Tex("Titration, then the two cells").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(1.5)
        b9_l1 = MathTex(r"n_{base} = 0{,}1 \times 0{,}020 = 0{,}002\ \text{mol}").scale(1.0).shift(band_shift(9) + UP * 1.2)
        b9_l2 = MathTex(r"c_{acid} = \frac{0{,}002}{0{,}025} = 0{,}08\ \text{mol}\cdot\text{dm}^{-3}").scale(0.95).shift(band_shift(9) + UP * 0.1)
        self.play(Write(b9_l1))
        self.wait(2)
        self.play(Write(b9_l2))
        self.play(Create(SurroundingRectangle(b9_l2, color=GREEN)))
        self.wait(2.5)
        b9_l3 = Tex("Galvanic: spontaneous, chemical $\\rightarrow$ electrical").scale(1.0).shift(band_shift(9) + DOWN * 1.0)
        self.play(Write(b9_l3))
        self.wait(2)
        b9_l4 = MathTex(r"E_{cell} = 0{,}34 - (-0{,}76) = 1{,}10\ \text{V}").scale(1.05).shift(band_shift(9) + DOWN * 1.9)
        self.play(Write(b9_l4))
        self.play(Create(SurroundingRectangle(b9_l4, color=GREEN)))
        self.wait(2)
        b9_l5 = Tex("Electrolytic: forced, electrical $\\rightarrow$ chemical").scale(1.0).shift(band_shift(9) + DOWN * 2.9)
        self.play(Write(b9_l5))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 10 (subtopic_5): carbon families and the compass
        self.next_band(10)
        b10_title = Tex("Carbon families and the reaction compass").scale(1.1).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_title))
        self.wait(2)
        b10_l1 = Tex("Surname $=$ chain (meth, eth, prop, but...);").scale(1.0).shift(band_shift(10) + UP * 1.2)
        b10_l2 = Tex("first name $=$ group (ane, ene, ol, oic acid)").scale(1.0).shift(band_shift(10) + UP * 0.5)
        self.play(Write(b10_l1))
        self.play(Write(b10_l2))
        self.wait(2.5)
        b10_l3 = Tex("Full bus: swap a passenger — substitution").scale(1.0).shift(band_shift(10) + DOWN * 0.4)
        b10_l4 = Tex("Folded seats unfold: addition").scale(1.0).shift(band_shift(10) + DOWN * 1.1)
        b10_l5 = Tex("Two leave, seat refolds: elimination").scale(1.0).shift(band_shift(10) + DOWN * 1.8)
        self.play(Write(b10_l3))
        self.wait(2)
        self.play(Write(b10_l4))
        self.wait(2)
        self.play(Write(b10_l5))
        self.play(Create(SurroundingRectangle(VGroup(b10_l3, b10_l4, b10_l5), color=GREEN)))
        self.wait(2.5)
        b10_l6 = Tex("OH group: hydrogen-bond superglue, boils high").scale(1.0).shift(band_shift(10) + DOWN * 2.9)
        self.play(Write(b10_l6))
        self.wait(3)

        # --- Band 11 (subtopic_6): the seesaw and the stubborn opponent
        self.next_band(11)
        b11_title = Tex("The seesaw and the stubborn opponent").scale(1.15).shift(band_shift(11) + UP * 2.2)
        self.play(Write(b11_title))
        self.wait(2)
        b11_l1 = Tex("At balance the RATES are equal —").scale(1.05).shift(band_shift(11) + UP * 1.2)
        b11_l2 = Tex("almost never the amounts").scale(1.05).shift(band_shift(11) + UP * 0.5)
        self.play(Write(b11_l1))
        self.play(Write(b11_l2))
        self.wait(2.5)
        b11_l3 = Tex("Whatever you do, the system leans back:").scale(1.0).shift(band_shift(11) + DOWN * 0.4)
        b11_l4 = Tex("it softens the blow, never cancels it").scale(1.0).shift(band_shift(11) + DOWN * 1.1)
        self.play(Write(b11_l3))
        self.play(Write(b11_l4))
        self.wait(2.5)
        b11_l5 = Tex(r"$K_c$ is the factory setting: only temperature").scale(1.0).shift(band_shift(11) + DOWN * 2.1)
        b11_l6 = Tex("reaches into the factory").scale(1.05).shift(band_shift(11) + DOWN * 2.8)
        self.play(Write(b11_l5))
        self.play(Write(b11_l6))
        self.play(Create(SurroundingRectangle(b11_l6, color=GREEN)))
        self.wait(3.5)

        # --- Band 12 (subtopic_7): two gears and the last audit
        self.next_band(12)
        b12_title = Tex("One machine, two gears — the last audit").scale(1.1).shift(band_shift(12) + UP * 2.2)
        self.play(Write(b12_title))
        self.wait(2)
        b12_l1 = Tex("Forward gear: galvanic, the chemistry wants to").scale(0.95).shift(band_shift(12) + UP * 1.3)
        b12_l2 = Tex("Reverse gear: electrolytic, you force it").scale(0.95).shift(band_shift(12) + UP * 0.6)
        self.play(Write(b12_l1))
        self.play(Write(b12_l2))
        self.wait(2.5)
        b12_l3 = Tex("An ox, red cat: oxidation at the anode,").scale(1.05).shift(band_shift(12) + DOWN * 0.3)
        b12_l4 = Tex("reduction at the cathode — in BOTH cells").scale(1.05).shift(band_shift(12) + DOWN * 1.0)
        self.play(Write(b12_l3))
        self.play(Write(b12_l4))
        self.play(Create(SurroundingRectangle(VGroup(b12_l3, b12_l4), color=GREEN)))
        self.wait(2.5)
        b12_t1 = Tex(r"Trap: strong $=$ concentrated").scale(1.0).shift(band_shift(12) + DOWN * 2.0)
        self.play(Write(b12_t1))
        self.play(Create(strike(b12_t1)))
        self.wait(2)
        b12_l5 = Tex("Electrons flow OUT of the anode, whatever the cell").scale(0.95).shift(band_shift(12) + DOWN * 2.9)
        self.play(Write(b12_l5))
        self.wait(4)
