from manim import *

# Band-layout whiteboard scene for "Humidity, condensation and rainfall
# types" (Part 1 Expert subtopics 1-4, Part 2 Simplifier subtopics 5-7).
# Relief-rainfall mountain, rising-parcel and cloud sketches are hand-built
# from Line/Arrow/Dot/Circle/Rectangle/Tex; worked RH and condensation-level
# calculations go line by line with the script's numbers.
# Subtopic durations (s): 215/240/240/250/180/185/190 of 1500.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class HumidityRainfallSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        self.wait(14)

        # ===== Part 1 — Expert =====
        # --- Band 0 (subtopic_1): humidity definitions ---
        title = Tex("Humidity, Condensation and Rainfall").scale(1.2).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        d1 = Tex(r"Evaporation + transpiration").scale(1.05).shift(UP * 1.3)
        d1b = Tex(r"= evapotranspiration").scale(1.05).shift(UP * 0.7)
        self.play(Write(d1))
        self.play(Write(d1b))
        self.wait(2)
        d2 = Tex(r"Absolute humidity: g/m$^3$ of vapour").scale(1.05).shift(DOWN * 0.2)
        d3 = Tex(r"Relative humidity: \% of the maximum").scale(1.05).shift(DOWN * 1.0)
        self.play(Write(d2))
        self.wait(2)
        self.play(Write(d3))
        self.wait(2)
        d4 = Tex(r"Warm air holds MORE water vapour").scale(1.1).shift(DOWN * 2.0)
        self.play(Write(d4))
        self.play(Create(SurroundingRectangle(d4, color=GREEN)))
        self.wait(3)

        # --- Band 1 (subtopic_1): the RH calculation and dew point ---
        self.next_band(1)
        b1t = Tex(r"Worked example: air at $20^\circ$C").scale(1.15).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1t))
        self.wait(1.5)
        c1 = MathTex(r"\text{max } 17 \text{ g}, \; \text{actual } 8{,}5 \text{ g}").scale(1.1).shift(band_shift(1) + UP * 1.1)
        c2 = MathTex(r"RH = \frac{8{,}5}{17} \times 100 = 50\%").scale(1.1).shift(band_shift(1) + UP * 0.0)
        self.play(Write(c1))
        self.wait(2)
        self.play(Write(c2))
        self.wait(2)
        c3 = MathTex(r"\text{Cool to } 10^\circ\text{C: max} = 8{,}5 \text{ g}").scale(1.05).shift(band_shift(1) + DOWN * 1.0)
        c4 = MathTex(r"\frac{8{,}5}{8{,}5} \times 100 = 100\% \text{ — saturated}").scale(1.05).shift(band_shift(1) + DOWN * 1.9)
        self.play(Write(c3))
        self.wait(2)
        self.play(Write(c4))
        self.play(Create(SurroundingRectangle(c4, color=GREEN)))
        c5 = Tex(r"Dew point: report the GAP, not one number").scale(0.95).shift(band_shift(1) + DOWN * 2.9)
        self.play(Write(c5))
        self.wait(3)

        # --- Band 2 (subtopic_2): dew, frost, mist, fog ---
        self.next_band(2)
        b2t = Tex("Condensation forms").scale(1.2).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2t))
        self.wait(1.5)
        f1 = Tex(r"Needs dew point + condensation nuclei").scale(1.0).shift(band_shift(2) + UP * 1.2)
        self.play(Write(f1))
        self.wait(2)
        f2 = Tex(r"Dew: clear still night, dew point $> 0$").scale(1.0).shift(band_shift(2) + UP * 0.4)
        f3 = Tex(r"Frost: dew point below $0^\circ$C — ice").scale(1.0).shift(band_shift(2) + DOWN * 0.4)
        f4 = Tex(r"Mist / fog: droplets suspended;").scale(1.0).shift(band_shift(2) + DOWN * 1.2)
        f4b = Tex(r"fog = visibility under 1 km").scale(1.0).shift(band_shift(2) + DOWN * 1.8)
        self.play(Write(f2))
        self.wait(2)
        self.play(Write(f3))
        self.wait(2)
        self.play(Write(f4))
        self.play(Write(f4b))
        self.wait(2)
        f5 = Tex(r"Advection fog: moist air over Benguela").scale(1.0).shift(band_shift(2) + DOWN * 2.7)
        self.play(Write(f5))
        self.wait(3)

        # --- Band 3 (subtopic_2): adiabatic cooling + condensation level ---
        self.next_band(3)
        b3t = Tex("The condensation level").scale(1.2).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3t))
        self.wait(1.5)
        g_line = Line(band_shift(3) + LEFT * 4.8 + DOWN * 2.6, band_shift(3) + LEFT * 0.8 + DOWN * 2.6, stroke_width=6)
        rise = Arrow(band_shift(3) + LEFT * 2.8 + DOWN * 2.5, band_shift(3) + LEFT * 2.8 + UP * 0.6, buff=0, color=YELLOW)
        base = Line(band_shift(3) + LEFT * 4.4 + UP * 0.7, band_shift(3) + LEFT * 1.2 + UP * 0.7, color=BLUE)
        base_l = Tex("cloud base").scale(0.8).shift(band_shift(3) + LEFT * 2.8 + UP * 1.1)
        self.play(Create(g_line))
        self.play(Create(rise))
        self.play(Create(base), Write(base_l))
        self.wait(2)
        a1 = Tex(r"Dry rate: $1^\circ$C per 100 m").scale(0.95).shift(band_shift(3) + RIGHT * 2.6 + UP * 1.3)
        a2 = Tex(r"Saturated: $0{,}5^\circ$C per 100 m").scale(0.95).shift(band_shift(3) + RIGHT * 2.7 + UP * 0.5)
        self.play(Write(a1))
        self.wait(1.5)
        self.play(Write(a2))
        self.wait(2)
        m1 = MathTex(r"25^\circ - 15^\circ = 10^\circ \text{ to cool}").scale(1.0).shift(band_shift(3) + RIGHT * 2.4 + DOWN * 0.6)
        m2 = MathTex(r"10 \times 100 \text{ m} = 1\,000 \text{ m}").scale(1.0).shift(band_shift(3) + RIGHT * 2.4 + DOWN * 1.5)
        self.play(Write(m1))
        self.wait(2)
        self.play(Write(m2))
        self.play(Create(SurroundingRectangle(m2, color=GREEN)))
        m3 = Tex(r"Flat cumulus bases: same height").scale(0.9).shift(band_shift(3) + RIGHT * 2.3 + DOWN * 2.5)
        self.play(Write(m3))
        self.wait(3)

        # --- Band 4 (subtopic_3): naming clouds ---
        self.next_band(4)
        b4t = Tex("Cloud names: four Latin words").scale(1.2).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4t))
        self.wait(1.5)
        n1 = Tex(r"cirro = high wispy \quad alto = middle").scale(1.0).shift(band_shift(4) + UP * 1.2)
        n2 = Tex(r"strato = layered \quad cumulo = heaped").scale(1.0).shift(band_shift(4) + UP * 0.5)
        n3 = Tex(r"nimbus = raining NOW").scale(1.05).shift(band_shift(4) + DOWN * 0.3)
        self.play(Write(n1))
        self.wait(2)
        self.play(Write(n2))
        self.wait(2)
        self.play(Write(n3))
        self.play(Create(SurroundingRectangle(n3, color=GREEN)))
        self.wait(2)
        n4 = Tex(r"High (ice, $>$ 6 000 m): cirrus warns").scale(0.95).shift(band_shift(4) + DOWN * 1.2)
        n4b = Tex(r"of a front; cirrostratus halo").scale(0.95).shift(band_shift(4) + DOWN * 1.8)
        self.play(Write(n4))
        self.play(Write(n4b))
        self.wait(3)

        # --- Band 5 (subtopic_3): middle, low, vertical clouds ---
        self.next_band(5)
        b5t = Tex("Middle, low and towering clouds").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5t))
        self.wait(1.5)
        q1 = Tex(r"Altostratus: frosted-glass sun,").scale(0.95).shift(band_shift(5) + UP * 1.2)
        q1b = Tex(r"thickens before steady rain").scale(0.95).shift(band_shift(5) + UP * 0.6)
        q2 = Tex(r"Stratus: grey blanket, drizzle").scale(0.95).shift(band_shift(5) + DOWN * 0.2)
        q3 = Tex(r"Nimbostratus: dark, steady all-day rain").scale(0.95).shift(band_shift(5) + DOWN * 0.9)
        self.play(Write(q1))
        self.play(Write(q1b))
        self.wait(2)
        self.play(Write(q2))
        self.wait(2)
        self.play(Write(q3))
        self.wait(2)
        # cumulonimbus tower with anvil
        tower = Rectangle(width=1.2, height=1.6).shift(band_shift(5) + LEFT * 3.6 + DOWN * 2.1)
        anvil = Line(band_shift(5) + LEFT * 4.8 + DOWN * 1.3, band_shift(5) + LEFT * 2.4 + DOWN * 1.3, stroke_width=6)
        cb_l = Tex(r"Cumulonimbus: anvil, thunder, hail").scale(0.95).shift(band_shift(5) + RIGHT * 1.6 + DOWN * 2.0)
        self.play(Create(tower))
        self.play(Create(anvil))
        self.play(Write(cb_l))
        self.wait(3)

        # --- Band 6 (subtopic_4): relief rainfall ---
        self.next_band(6)
        b6t = Tex("Relief (orographic) rainfall").scale(1.2).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6t))
        self.wait(1.5)
        gnd = Line(band_shift(6) + LEFT * 5.2 + DOWN * 2.4, band_shift(6) + RIGHT * 5.2 + DOWN * 2.4, stroke_width=6)
        up_sl = Line(band_shift(6) + LEFT * 2.6 + DOWN * 2.4, band_shift(6) + LEFT * 0.2 + UP * 0.8)
        dn_sl = Line(band_shift(6) + LEFT * 0.2 + UP * 0.8, band_shift(6) + RIGHT * 2.2 + DOWN * 2.4)
        self.play(Create(gnd))
        self.play(Create(up_sl), Create(dn_sl))
        self.wait(1.5)
        wind = Arrow(band_shift(6) + LEFT * 5.0 + DOWN * 1.6, band_shift(6) + LEFT * 3.0 + DOWN * 1.6, buff=0, color=BLUE)
        wind_l = Tex("moist sea air").scale(0.8).shift(band_shift(6) + LEFT * 4.0 + DOWN * 1.1)
        self.play(Create(wind), Write(wind_l))
        self.wait(1.5)
        ww = Tex(r"windward: rises, cools, rains").scale(0.85).shift(band_shift(6) + LEFT * 3.3 + UP * 0.6)
        self.play(Write(ww))
        self.wait(2)
        lw = Tex(r"leeward: sinks, warms — rain shadow").scale(0.85).shift(band_shift(6) + RIGHT * 3.3 + UP * 0.6)
        self.play(Write(lw))
        self.wait(2)
        ex = Tex(r"Drakensberg east wet; Little Karoo dry").scale(0.95).shift(band_shift(6) + DOWN * 3.0)
        self.play(Write(ex))
        self.play(Create(SurroundingRectangle(ex, color=GREEN)))
        self.wait(3)

        # --- Band 7 (subtopic_4): convectional and frontal ---
        self.next_band(7)
        b7t = Tex("Convectional and frontal rainfall").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7t))
        self.wait(1.5)
        v1 = Tex(r"Convectional: baked ground, thermals,").scale(0.95).shift(band_shift(7) + UP * 1.2)
        v1b = Tex(r"late-afternoon Highveld thunderstorm").scale(0.95).shift(band_shift(7) + UP * 0.6)
        self.play(Write(v1))
        self.play(Write(v1b))
        self.wait(2.5)
        v2 = Tex(r"Frontal: cold air wedges under warm").scale(0.95).shift(band_shift(7) + DOWN * 0.3)
        v2b = Tex(r"Cold front: steep lift, heavy showers").scale(0.95).shift(band_shift(7) + DOWN * 1.0)
        v2c = Tex(r"Western Cape winter rain, May–August").scale(0.95).shift(band_shift(7) + DOWN * 1.7)
        self.play(Write(v2))
        self.wait(2)
        self.play(Write(v2b))
        self.wait(2)
        self.play(Write(v2c))
        self.wait(2)
        trap = Tex(r"Identify the type by rain intensity").scale(0.95).shift(band_shift(7) + DOWN * 2.5)
        self.play(Write(trap))
        self.play(Create(strike(trap)))
        fix = Tex(r"Identify by the LIFTING MECHANISM").scale(0.95).shift(band_shift(7) + DOWN * 3.1)
        self.play(Write(fix))
        self.play(Create(SurroundingRectangle(fix, color=GREEN)))
        self.wait(3)

        # ===== Part 2 — Simplifier =====
        # --- Band 8 (subtopic_5): the shopping bag ---
        self.next_band(8)
        b8t = Tex("The bag that grows when it's warm").scale(1.15).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8t))
        self.wait(2)
        s1 = Tex(r"Warm air = big bag; cold air = small bag").scale(1.0).shift(band_shift(8) + UP * 1.2)
        self.play(Write(s1))
        self.wait(2)
        s2 = Tex(r"Cool the bag: it shrinks until full").scale(1.0).shift(band_shift(8) + UP * 0.4)
        s3 = Tex(r"Full = saturated; that temp = dew point").scale(1.0).shift(band_shift(8) + DOWN * 0.4)
        self.play(Write(s2))
        self.wait(2)
        self.play(Write(s3))
        self.play(Create(SurroundingRectangle(s3, color=GREEN)))
        self.wait(2)
        s4 = Tex(r"Cold Coke sweats: chilled air shrank").scale(1.0).shift(band_shift(8) + DOWN * 1.3)
        s5 = MathTex(r"\tfrac{8{,}5}{17} = 50\% \;\to\; \tfrac{8{,}5}{8{,}5} = 100\%").scale(1.05).shift(band_shift(8) + DOWN * 2.2)
        self.play(Write(s4))
        self.wait(2)
        self.play(Write(s5))
        s6 = Tex(r"Small temp–dew point gap = rain nearby").scale(0.95).shift(band_shift(8) + DOWN * 3.0)
        self.play(Write(s6))
        self.wait(3)

        # --- Band 9 (subtopic_6): the sky menu ---
        self.next_band(9)
        b9t = Tex("Reading the sky like a menu").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9t))
        self.wait(2)
        u1 = Tex(r"cirro high, alto middle, strato flat,").scale(1.0).shift(band_shift(9) + UP * 1.2)
        u1b = Tex(r"cumulo heaped, nimbus raining").scale(1.0).shift(band_shift(9) + UP * 0.6)
        self.play(Write(u1))
        self.play(Write(u1b))
        self.wait(2)
        u2 = Tex(r"Cirrus feathers: a front a day away").scale(0.95).shift(band_shift(9) + DOWN * 0.3)
        u3 = Tex(r"Stratus blanket: drizzle; fog is").scale(0.95).shift(band_shift(9) + DOWN * 1.1)
        u3b = Tex(r"stratus on the ground").scale(0.95).shift(band_shift(9) + DOWN * 1.7)
        u4 = Tex(r"Cumulus on its shelf $\to$ cumulonimbus").scale(0.95).shift(band_shift(9) + DOWN * 2.5)
        self.play(Write(u2))
        self.wait(2)
        self.play(Write(u3))
        self.play(Write(u3b))
        self.wait(2)
        self.play(Write(u4))
        self.wait(3)

        # --- Band 10 (subtopic_7): three ways to push air up ---
        self.next_band(10)
        b10t = Tex("Three ways to push air up a hill").scale(1.2).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10t))
        self.wait(2)
        w1 = Tex(r"1. Mountain: wet side / dry rain shadow").scale(0.95).shift(band_shift(10) + UP * 1.2)
        w2 = Tex(r"2. Hot ground: Highveld 4 pm storm").scale(0.95).shift(band_shift(10) + UP * 0.4)
        w3 = Tex(r"3. Cold bulldozer: Cape winter fronts").scale(0.95).shift(band_shift(10) + DOWN * 0.4)
        self.play(Write(w1))
        self.wait(2)
        self.play(Write(w2))
        self.wait(2)
        self.play(Write(w3))
        self.wait(2)
        w4 = Tex(r"Mountain, hot ground, bulldozer").scale(1.05).shift(band_shift(10) + DOWN * 1.4)
        self.play(Write(w4))
        self.play(Create(SurroundingRectangle(w4, color=GREEN)))
        self.wait(2)
        w5 = Tex(r"Decide by what did the pushing,").scale(0.95).shift(band_shift(10) + DOWN * 2.3)
        w5b = Tex(r"then name the region and season").scale(0.95).shift(band_shift(10) + DOWN * 2.9)
        self.play(Write(w5))
        self.play(Write(w5b))
        self.wait(4)
