from manim import *

# Band-layout whiteboard scene for the Universal Gravitation session duo.
# Part 1 — Expert: subtopics 1-4; Part 2 — Simplifier: subtopics 5-7.
# Band dwell proportional to subtopics.json (225/215/240/230/180/180/195
# of 1465 s). Exporter-safe mobjects only; add-only lifecycle; camera bands.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class UniversalGravitationSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic display while intro.md plays (~4-5% of scene).
        self.wait(14)

        # ===== Part 1 — Expert =====
        # --- Band 0 (subtopic_1): the law ---
        title = Tex("Newton's Law of Universal Gravitation").scale(1.15).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = MathTex(r"F = \frac{G m_1 m_2}{d^2}").scale(1.4).shift(UP * 1.0)
        self.play(Write(b0_l1))
        self.play(Create(SurroundingRectangle(b0_l1, color=BLUE)))
        self.wait(2.5)
        b0_l2 = MathTex(r"G = 6{,}67 \times 10^{-11}\ \text{N m}^2\text{kg}^{-2}").scale(1.0).shift(DOWN * 0.4)
        self.play(Write(b0_l2))
        self.wait(2.5)
        b0_l3 = Tex("Always attractive; a third-law pair").scale(0.95).shift(DOWN * 1.4)
        self.play(Write(b0_l3))
        self.wait(2)
        b0_l4 = Tex("$d$ is between the CENTRES").scale(0.95).shift(DOWN * 2.3)
        self.play(Write(b0_l4))
        self.wait(2.5)

        # --- Band 1 (subtopic_1): the scale of the force ---
        self.next_band(1)
        b1_title = Tex("Two learners, 60 kg and 80 kg, 1 m apart").scale(1.0).shift(band_shift(1) + UP * 2.3)
        self.play(Write(b1_title))
        self.wait(1.5)
        b1_l1 = MathTex(r"F = \frac{6{,}67 \times 10^{-11} \times 60 \times 80}{1^2}").scale(1.0).shift(band_shift(1) + UP * 1.2)
        self.play(Write(b1_l1))
        self.wait(2.5)
        b1_l2 = MathTex(r"F \approx 3{,}2 \times 10^{-7}\ \text{N}").scale(1.05).shift(band_shift(1) + UP * 0.1)
        self.play(Write(b1_l2))
        self.play(Create(SurroundingRectangle(b1_l2, color=GREEN)))
        self.wait(2)
        b1_l3 = Tex("Far too small to feel").scale(0.95).shift(band_shift(1) + DOWN * 0.8)
        self.play(Write(b1_l3))
        self.wait(2)
        b1_l4 = Tex(r"Earth ($5{,}98 \times 10^{24}$ kg) on 70 kg:").scale(0.95).shift(band_shift(1) + DOWN * 1.7)
        self.play(Write(b1_l4))
        self.wait(2)
        b1_l5 = MathTex(r"F = 686\ \text{N} = mg \; \text{— weight IS this force}").scale(0.95).shift(band_shift(1) + DOWN * 2.7)
        self.play(Write(b1_l5))
        self.wait(2.5)

        # --- Band 2 (subtopic_2): the ratio rules ---
        self.next_band(2)
        b2_title = Tex("Inverse-square reasoning").scale(1.15).shift(band_shift(2) + UP * 2.3)
        self.play(Write(b2_title))
        self.wait(1.5)
        b2_l1 = Tex(r"Double one mass $\Rightarrow$ force $\times$ 2").scale(1.0).shift(band_shift(2) + UP * 1.3)
        self.play(Write(b2_l1))
        self.wait(2)
        b2_l2 = Tex(r"Double both masses $\Rightarrow$ force $\times$ 4").scale(1.0).shift(band_shift(2) + UP * 0.4)
        self.play(Write(b2_l2))
        self.wait(2)
        b2_l3 = Tex(r"Double the distance $\Rightarrow$ force $\div$ 4").scale(1.0).shift(band_shift(2) + DOWN * 0.5)
        self.play(Write(b2_l3))
        self.wait(2)
        b2_l4 = Tex(r"Triple the distance $\Rightarrow$ force $\div$ 9").scale(1.0).shift(band_shift(2) + DOWN * 1.4)
        self.play(Write(b2_l4))
        self.wait(2)
        b2_trap = Tex(r"distance doubles, force halves").scale(1.0).shift(band_shift(2) + DOWN * 2.4)
        self.play(Write(b2_trap))
        self.play(Create(strike(b2_trap)))
        self.wait(1.5)
        b2_l5 = Tex("Distance changes are ALWAYS squared").scale(0.95).shift(band_shift(2) + DOWN * 3.2)
        self.play(Write(b2_l5))
        self.wait(2.5)

        # --- Band 3 (subtopic_2): combined ratio, worked ---
        self.next_band(3)
        b3_title = Tex("One mass tripled, distance halved").scale(1.1).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(1.5)
        b3_l1 = MathTex(r"\text{masses: } \times 3, \quad \text{distance: } \times 2^2 = 4").scale(1.0).shift(band_shift(3) + UP * 1.1)
        self.play(Write(b3_l1))
        self.wait(2.5)
        b3_l2 = MathTex(r"F_{new} = 3 \times 4 \times F = 12F").scale(1.1).shift(band_shift(3) + UP * 0.0)
        self.play(Write(b3_l2))
        self.play(Create(SurroundingRectangle(b3_l2, color=GREEN)))
        self.wait(2.5)
        b3_l3 = Tex(r"With numbers: $F = 3{,}6 \times 10^{-7}$ N, distance doubled").scale(0.9).shift(band_shift(3) + DOWN * 1.2)
        self.play(Write(b3_l3))
        self.wait(2)
        b3_l4 = MathTex(r"F_{new} = \frac{3{,}6 \times 10^{-7}}{4} = 9 \times 10^{-8}\ \text{N}").scale(1.0).shift(band_shift(3) + DOWN * 2.2)
        self.play(Write(b3_l4))
        self.play(Create(SurroundingRectangle(b3_l4, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): deriving g ---
        self.next_band(4)
        b4_title = Tex("Set the law equal to weight").scale(1.1).shift(band_shift(4) + UP * 2.3)
        self.play(Write(b4_title))
        self.wait(1.5)
        b4_l1 = MathTex(r"mg = \frac{G M m}{r^2}").scale(1.15).shift(band_shift(4) + UP * 1.2)
        self.play(Write(b4_l1))
        self.wait(2.5)
        b4_l2 = Tex("The small $m$ cancels:").scale(1.0).shift(band_shift(4) + UP * 0.2)
        self.play(Write(b4_l2))
        self.wait(1.5)
        b4_l3 = MathTex(r"g = \frac{G M}{r^2}").scale(1.3).shift(band_shift(4) + DOWN * 0.8)
        self.play(Write(b4_l3))
        self.play(Create(SurroundingRectangle(b4_l3, color=BLUE)))
        self.wait(2.5)
        b4_l4 = Tex("Every object at one place falls alike —").scale(0.95).shift(band_shift(4) + DOWN * 2.0)
        b4_l5 = Tex("brick and feather land together on the Moon").scale(0.95).shift(band_shift(4) + DOWN * 2.7)
        self.play(Write(b4_l4))
        self.play(Write(b4_l5))
        self.wait(2.5)

        # --- Band 5 (subtopic_3): Earth, Moon, altitude ---
        self.next_band(5)
        b5_l1 = MathTex(r"g_{Earth} = \frac{6{,}67 \times 10^{-11} \times 5{,}98 \times 10^{24}}{(6{,}38 \times 10^{6})^2}").scale(0.9).shift(band_shift(5) + UP * 2.1)
        self.play(Write(b5_l1))
        self.wait(2.5)
        b5_l2 = MathTex(r"g_{Earth} = 9{,}8\ \text{m/s}^2 \; \text{— derived!}").scale(1.05).shift(band_shift(5) + UP * 0.9)
        self.play(Write(b5_l2))
        self.play(Create(SurroundingRectangle(b5_l2, color=GREEN)))
        self.wait(2.5)
        b5_l3 = MathTex(r"g_{Moon} = 1{,}62\ \text{m/s}^2 \approx \tfrac{1}{6} g_{Earth}").scale(1.0).shift(band_shift(5) + DOWN * 0.3)
        self.play(Write(b5_l3))
        self.wait(2.5)
        b5_l4 = Tex(r"Satellite at 2 Earth radii from the centre:").scale(0.95).shift(band_shift(5) + DOWN * 1.4)
        b5_l5 = MathTex(r"g = \frac{9{,}8}{2^2} = 2{,}45\ \text{m/s}^2").scale(1.0).shift(band_shift(5) + DOWN * 2.4)
        self.play(Write(b5_l4))
        self.play(Write(b5_l5))
        self.wait(3)

        # --- Band 6 (subtopic_4): weight on other planets ---
        self.next_band(6)
        b6_title = Tex("Mass in kg, weight in N — never swap").scale(1.05).shift(band_shift(6) + UP * 2.3)
        self.play(Write(b6_title))
        self.wait(2)
        b6_l1 = MathTex(r"\text{Earth: } w = 70 \times 9{,}8 = 686\ \text{N}").scale(1.0).shift(band_shift(6) + UP * 1.3)
        self.play(Write(b6_l1))
        self.wait(2)
        b6_l2 = MathTex(r"\text{Moon: } w = 70 \times 1{,}62 = 113{,}4\ \text{N}").scale(1.0).shift(band_shift(6) + UP * 0.4)
        self.play(Write(b6_l2))
        self.wait(2)
        b6_l3 = MathTex(r"\text{Mars: } g = 3{,}7, \; w = 259\ \text{N}").scale(1.0).shift(band_shift(6) + DOWN * 0.5)
        self.play(Write(b6_l3))
        self.wait(2.5)
        b6_l4 = Tex("The mass never moved from 70 kg").scale(1.0).shift(band_shift(6) + DOWN * 1.6)
        self.play(Write(b6_l4))
        self.play(Create(SurroundingRectangle(b6_l4, color=GREEN)))
        self.wait(3)

        # --- Band 7 (subtopic_4): true weightlessness ---
        self.next_band(7)
        b7_title = Tex("Weightlessness, properly").scale(1.15).shift(band_shift(7) + UP * 2.3)
        self.play(Write(b7_title))
        self.wait(1.5)
        b7_l1 = MathTex(r"\text{At the ISS: } g \approx 9\ \text{m/s}^2 \; \text{— still there}").scale(0.95).shift(band_shift(7) + UP * 1.3)
        self.play(Write(b7_l1))
        self.wait(2.5)
        b7_l2 = Tex("The station is in continuous FREE FALL,").scale(0.95).shift(band_shift(7) + UP * 0.4)
        b7_l3 = Tex("moving sideways fast enough to keep missing").scale(0.95).shift(band_shift(7) + DOWN * 0.3)
        self.play(Write(b7_l2))
        self.play(Write(b7_l3))
        self.wait(2.5)
        b7_l4 = Tex("No support force $=$ the feeling of weightlessness").scale(0.95).shift(band_shift(7) + DOWN * 1.3)
        self.play(Write(b7_l4))
        self.wait(2.5)
        b7_l5 = Tex("Weightlessness is free fall, not no gravity").scale(0.95).shift(band_shift(7) + DOWN * 2.3)
        self.play(Write(b7_l5))
        self.play(Create(SurroundingRectangle(b7_l5, color=GREEN)))
        self.wait(3)

        # ===== Part 2 — Simplifier =====
        # --- Band 8 (subtopic_5): everything pulls on everything ---
        self.next_band(8)
        b8_title = Tex("Everything pulls on everything").scale(1.2).shift(band_shift(8) + UP * 2.3)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = Tex("You are pulling on your desk right now").scale(0.95).shift(band_shift(8) + UP * 1.3)
        self.play(Write(b8_l1))
        self.wait(2.5)
        b8_l2 = Tex(r"Two learners: $\approx$ a third of a millionth of a newton").scale(0.9).shift(band_shift(8) + UP * 0.4)
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = Tex("You only notice when a PLANET joins in").scale(0.95).shift(band_shift(8) + DOWN * 0.6)
        self.play(Write(b8_l3))
        self.wait(2.5)
        b8_l4 = Tex("Earth pulls you down 686 N;").scale(0.95).shift(band_shift(8) + DOWN * 1.6)
        b8_l5 = Tex("you pull the Earth UP 686 N").scale(0.95).shift(band_shift(8) + DOWN * 2.3)
        self.play(Write(b8_l4))
        self.play(Write(b8_l5))
        self.play(Create(SurroundingRectangle(b8_l5, color=GREEN)))
        self.wait(3)

        # --- Band 9 (subtopic_6): double the distance, quarter the pull ---
        self.next_band(9)
        b9_title = Tex("Double the distance, quarter the pull").scale(1.1).shift(band_shift(9) + UP * 2.3)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = Tex("Like torchlight on a wall: step back twice").scale(0.95).shift(band_shift(9) + UP * 1.3)
        b9_l2 = Tex("as far, each patch gets a quarter").scale(0.95).shift(band_shift(9) + UP * 0.6)
        self.play(Write(b9_l1))
        self.play(Write(b9_l2))
        self.wait(2.5)
        b9_l3 = Tex(r"Masses are simple: double $\Rightarrow$ double").scale(0.95).shift(band_shift(9) + DOWN * 0.4)
        self.play(Write(b9_l3))
        self.wait(2.5)
        b9_l4 = MathTex(r"\times 3 \text{ mass, } \times 2 \text{ distance: } \frac{3}{4}F").scale(1.0).shift(band_shift(9) + DOWN * 1.4)
        self.play(Write(b9_l4))
        self.play(Create(SurroundingRectangle(b9_l4, color=GREEN)))
        self.wait(2.5)
        b9_l5 = Tex("Distance always gets squared").scale(1.0).shift(band_shift(9) + DOWN * 2.5)
        self.play(Write(b9_l5))
        self.wait(3)

        # --- Band 10 (subtopic_7): same you, different weight ---
        self.next_band(10)
        b10_title = Tex("Same you, different weight").scale(1.2).shift(band_shift(10) + UP * 2.3)
        self.play(Write(b10_title))
        self.wait(2)
        b10_l1 = Tex("Mass: how much of you — same everywhere").scale(0.95).shift(band_shift(10) + UP * 1.3)
        self.play(Write(b10_l1))
        self.wait(2.5)
        b10_l2 = Tex("Weight: gravity's pull — depends on the planet").scale(0.95).shift(band_shift(10) + UP * 0.4)
        self.play(Write(b10_l2))
        self.wait(2.5)
        b10_l3 = MathTex(r"9{,}8 \to 1{,}62 \to 3{,}7\ \text{N per kg}").scale(1.0).shift(band_shift(10) + DOWN * 0.6)
        lab = Tex("Earth, Moon, Mars").scale(0.85).shift(band_shift(10) + DOWN * 1.3)
        self.play(Write(b10_l3))
        self.play(Write(lab))
        self.wait(2.5)
        b10_l4 = Tex("Astronauts float because they are FALLING,").scale(0.95).shift(band_shift(10) + DOWN * 2.2)
        b10_l5 = Tex("and their floor falls with them").scale(0.95).shift(band_shift(10) + DOWN * 2.9)
        self.play(Write(b10_l4))
        self.play(Write(b10_l5))
        self.play(Create(SurroundingRectangle(b10_l5, color=GREEN)))
        self.wait(4)
