from manim import *

# Band-layout whiteboard scene for the common acids and bases session duo.
# Covers all seven subtopics (Part 1 Expert: 1-4, Part 2 Simplifier: 5-7),
# band time proportional to subtopics.json (225/230/235/240/200/195/200 of
# 1525 s). Add-only lifecycle; exporter-safe mobjects only.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class CommonAcidsAndBasesSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        self.wait(14)

        # ===== Part 1 — Expert =====
        # --- Band 0 (subtopic_1): the four acids, first two ---
        title = Tex("The Four Acids You Must Know").scale(1.25).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex(r"1. Hydrochloric acid: $HCl$").scale(1.1).shift(UP * 1.1)
        b0_l2 = Tex("stomach acid, pool acid").scale(0.95).shift(UP * 0.4)
        self.play(Write(b0_l1))
        self.wait(1.5)
        self.play(Write(b0_l2))
        self.wait(2)
        b0_l3 = Tex(r"2. Nitric acid: $HNO_3$").scale(1.1).shift(DOWN * 0.5)
        b0_l4 = Tex("the acid of fertiliser manufacture").scale(0.95).shift(DOWN * 1.2)
        self.play(Write(b0_l3))
        self.wait(1.5)
        self.play(Write(b0_l4))
        self.wait(2)
        b0_l5 = Tex("One hydrogen ion each: MONOPROTIC").scale(1.05).shift(DOWN * 2.2)
        self.play(Write(b0_l5))
        self.wait(3)

        # --- Band 1 (subtopic_1): sulphuric and ethanoic ---
        self.next_band(1)
        b1_l1 = Tex(r"3. Sulphuric acid: $H_2SO_4$").scale(1.1).shift(band_shift(1) + UP * 2.2)
        b1_l2 = Tex("car batteries; TWO hydrogens: DIPROTIC").scale(1.0).shift(band_shift(1) + UP * 1.4)
        self.play(Write(b1_l1))
        self.wait(1.5)
        self.play(Write(b1_l2))
        self.wait(2)
        b1_l3 = Tex(r"4. Ethanoic acid: $CH_3COOH$ (vinegar)").scale(1.1).shift(band_shift(1) + UP * 0.4)
        self.play(Write(b1_l3))
        self.wait(2)
        b1_l4 = Tex("Four H in the formula, only ONE acidic —").scale(1.0).shift(band_shift(1) + DOWN * 0.5)
        b1_l5 = Tex("the one at the end, on the oxygen").scale(1.0).shift(band_shift(1) + DOWN * 1.3)
        self.play(Write(b1_l4))
        self.wait(2)
        self.play(Write(b1_l5))
        self.wait(2)
        b1_l6 = Tex("Weak acid: releases it reluctantly —").scale(1.0).shift(band_shift(1) + DOWN * 2.2)
        b1_l7 = Tex("which is why you can put it on chips").scale(1.0).shift(band_shift(1) + DOWN * 2.9)
        self.play(Write(b1_l6))
        self.wait(1.5)
        self.play(Write(b1_l7))
        self.wait(3)

        # --- Band 2 (subtopic_2): bases one to three ---
        self.next_band(2)
        b2_t = Tex("The Five Bases You Must Know").scale(1.2).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(2)
        b2_l1 = Tex(r"1. Sodium hydroxide: $NaOH$ (caustic soda)").scale(1.0).shift(band_shift(2) + UP * 1.1)
        b2_l2 = Tex(r"2. Potassium hydroxide: $KOH$ — its twin").scale(1.0).shift(band_shift(2) + UP * 0.2)
        self.play(Write(b2_l1))
        self.wait(2)
        self.play(Write(b2_l2))
        self.wait(2)
        b2_l3 = Tex(r"3. Ammonia: $NH_3$ — the odd one out:").scale(1.0).shift(band_shift(2) + DOWN * 0.8)
        b2_l4 = Tex("no hydroxide, no oxygen, no metal,").scale(1.0).shift(band_shift(2) + DOWN * 1.6)
        b2_l5 = Tex("yet a base — it accepts hydrogen ions").scale(1.0).shift(band_shift(2) + DOWN * 2.4)
        self.play(Write(b2_l3))
        self.wait(1.5)
        self.play(Write(b2_l4))
        self.wait(1.5)
        self.play(Write(b2_l5))
        self.wait(3)

        # --- Band 3 (subtopic_2): the carbonate pair ---
        self.next_band(3)
        b3_t = Tex("The classic confusion: the carbonate pair").scale(1.1).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t))
        self.wait(2)
        b3_l1 = Tex(r"4. Sodium carbonate: $Na_2CO_3$").scale(1.05).shift(band_shift(3) + UP * 1.1)
        b3_l2 = Tex("washing soda — TWO Na, no H").scale(1.0).shift(band_shift(3) + UP * 0.3)
        self.play(Write(b3_l1))
        self.wait(2)
        self.play(Write(b3_l2))
        self.wait(2)
        b3_l3 = Tex(r"5. Sodium hydrogen carbonate: $NaHCO_3$").scale(1.05).shift(band_shift(3) + DOWN * 0.7)
        b3_l4 = Tex("baking soda — ONE Na, one H").scale(1.0).shift(band_shift(3) + DOWN * 1.5)
        self.play(Write(b3_l3))
        self.wait(2)
        self.play(Write(b3_l4))
        self.wait(2)
        b3_l5 = MathTex(r"NaOH, \; KOH, \; NH_3, \; Na_2CO_3, \; NaHCO_3").scale(1.0).shift(band_shift(3) + DOWN * 2.5)
        self.play(Write(b3_l5))
        self.play(Create(SurroundingRectangle(b3_l5, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): the ions, and building the acids ---
        self.next_band(4)
        b4_t = Tex("Build formulae: charges total zero").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(2)
        b4_l1 = MathTex(r"+: \; H^+, \; Na^+, \; K^+").scale(1.05).shift(band_shift(4) + UP * 1.2)
        b4_l2 = MathTex(r"-: \; Cl^-, \; NO_3^-, \; OH^-, \; HCO_3^-").scale(1.0).shift(band_shift(4) + UP * 0.4)
        b4_l3 = MathTex(r"2-: \; SO_4^{2-}, \; CO_3^{2-}").scale(1.05).shift(band_shift(4) + DOWN * 0.4)
        self.play(Write(b4_l1))
        self.wait(1.5)
        self.play(Write(b4_l2))
        self.wait(1.5)
        self.play(Write(b4_l3))
        self.wait(2)
        b4_l4 = MathTex(r"H^+ + Cl^- \Rightarrow HCl").scale(1.0).shift(band_shift(4) + DOWN * 1.3 + LEFT * 3.0)
        b4_l4b = MathTex(r"H^+ + NO_3^- \Rightarrow HNO_3").scale(1.0).shift(band_shift(4) + DOWN * 1.3 + RIGHT * 3.0)
        self.play(Write(b4_l4))
        self.wait(1.5)
        self.play(Write(b4_l4b))
        self.wait(2)
        b4_l5 = MathTex(r"SO_4^{2-} \text{ needs TWO: } H_2SO_4").scale(1.05).shift(band_shift(4) + DOWN * 2.4)
        self.play(Write(b4_l5))
        self.play(Create(SurroundingRectangle(b4_l5, color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_3): building the bases, spotting fakes ---
        self.next_band(5)
        b5_l1 = MathTex(r"Na^+ + OH^- \Rightarrow NaOH").scale(1.05).shift(band_shift(5) + UP * 2.2)
        b5_l2 = MathTex(r"2Na^+ + CO_3^{2-} \Rightarrow Na_2CO_3").scale(1.05).shift(band_shift(5) + UP * 1.3)
        b5_l3 = MathTex(r"Na^+ + HCO_3^- \Rightarrow NaHCO_3").scale(1.05).shift(band_shift(5) + UP * 0.4)
        self.play(Write(b5_l1))
        self.wait(2)
        self.play(Write(b5_l2))
        self.wait(2)
        self.play(Write(b5_l3))
        self.wait(2)
        b5_w1 = MathTex(r"NaCO_3").scale(1.1).shift(band_shift(5) + DOWN * 0.7 + LEFT * 2.5)
        b5_w2 = MathTex(r"H_2NO_3").scale(1.1).shift(band_shift(5) + DOWN * 0.7 + RIGHT * 2.5)
        self.play(Write(b5_w1))
        self.play(Create(strike(b5_w1)))
        self.wait(1.5)
        self.play(Write(b5_w2))
        self.play(Create(strike(b5_w2)))
        self.wait(2)
        b5_n = Tex("Charges don't total zero — fakes").scale(1.05).shift(band_shift(5) + DOWN * 1.7)
        self.play(Write(b5_n))
        self.wait(2)
        b5_n2 = Tex("Audit every formula: do charges cancel?").scale(1.0).shift(band_shift(5) + DOWN * 2.6)
        self.play(Write(b5_n2))
        self.wait(3)

        # --- Band 6 (subtopic_4): salt takes the acid's surname ---
        self.next_band(6)
        b6_t = Tex("Acid + base = salt + water").scale(1.2).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_t))
        self.wait(2)
        b6_l1 = Tex("Positive ion from the BASE,").scale(1.0).shift(band_shift(6) + UP * 1.2)
        b6_l2 = Tex("negative ion from the ACID").scale(1.0).shift(band_shift(6) + UP * 0.5)
        self.play(Write(b6_l1))
        self.wait(1.5)
        self.play(Write(b6_l2))
        self.wait(2)
        b6_e1 = MathTex(r"NaOH + HCl \rightarrow NaCl + H_2O").scale(1.0).shift(band_shift(6) + DOWN * 0.5)
        b6_e2 = MathTex(r"KOH + HNO_3 \rightarrow KNO_3 + H_2O").scale(1.0).shift(band_shift(6) + DOWN * 1.4)
        b6_e3 = MathTex(r"2NaOH + H_2SO_4 \rightarrow Na_2SO_4 + 2H_2O").scale(0.95).shift(band_shift(6) + DOWN * 2.3)
        self.play(Write(b6_e1))
        self.wait(2)
        self.play(Write(b6_e2))
        self.wait(2)
        self.play(Write(b6_e3))
        self.wait(2)
        b6_n = Tex("Diprotic acid needs TWO hydroxides").scale(1.0).shift(band_shift(6) + DOWN * 3.2)
        self.play(Write(b6_n))
        self.wait(3)

        # --- Band 7 (subtopic_4): reading salts backwards ---
        self.next_band(7)
        b7_t = Tex("Backwards: read the salt apart").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(2)
        b7_l1 = Tex("chloride — hydrochloric; nitrate — nitric;").scale(1.0).shift(band_shift(7) + UP * 1.2)
        b7_l2 = Tex("sulphate — sulphuric; ethanoate — ethanoic").scale(1.0).shift(band_shift(7) + UP * 0.4)
        self.play(Write(b7_l1))
        self.wait(2)
        self.play(Write(b7_l2))
        self.wait(2)
        b7_l3 = Tex("Prepare potassium sulphate?").scale(1.05).shift(band_shift(7) + DOWN * 0.6)
        b7_l4 = MathTex(r"KOH + H_2SO_4").scale(1.1).shift(band_shift(7) + DOWN * 1.5)
        self.play(Write(b7_l3))
        self.wait(2)
        self.play(Write(b7_l4))
        self.play(Create(SurroundingRectangle(b7_l4, color=GREEN)))
        self.wait(2)
        b7_l5 = Tex("Sodium ethanoate? NaOH + ethanoic acid").scale(1.0).shift(band_shift(7) + DOWN * 2.5)
        self.play(Write(b7_l5))
        self.wait(3)

        # ===== Part 2 — Simplifier =====
        # --- Band 8 (subtopic_5): tour of the house ---
        self.next_band(8)
        b8_t = Tex("A tour of the house in nine chemicals").scale(1.15).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_t))
        self.wait(2)
        b8_l1 = Tex(r"Kitchen: vinegar $CH_3COOH$,").scale(1.0).shift(band_shift(8) + UP * 1.2)
        b8_l2 = Tex(r"baking soda $NaHCO_3$").scale(1.0).shift(band_shift(8) + UP * 0.5)
        self.play(Write(b8_l1))
        self.wait(1.5)
        self.play(Write(b8_l2))
        self.wait(2)
        b8_l3 = Tex(r"Laundry: washing soda $Na_2CO_3$;").scale(1.0).shift(band_shift(8) + DOWN * 0.4)
        b8_l4 = Tex(r"sink: drain cleaner $NaOH$; cleaner: $NH_3$").scale(0.95).shift(band_shift(8) + DOWN * 1.2)
        self.play(Write(b8_l3))
        self.wait(1.5)
        self.play(Write(b8_l4))
        self.wait(2)
        b8_l5 = Tex(r"Garage: pool acid $HCl$, battery $H_2SO_4$,").scale(0.95).shift(band_shift(8) + DOWN * 2.1)
        b8_l6 = Tex(r"fertiliser traces back to $HNO_3$").scale(1.0).shift(band_shift(8) + DOWN * 2.9)
        self.play(Write(b8_l5))
        self.wait(1.5)
        self.play(Write(b8_l6))
        self.wait(3)

        # --- Band 9 (subtopic_6): charges snap like magnets ---
        self.next_band(9)
        b9_t = Tex("Charges snap together like magnets").scale(1.15).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(2)
        b9_l1 = Tex("Single + meets single $-$: click, one-to-one").scale(1.0).shift(band_shift(9) + UP * 1.2)
        b9_l2 = MathTex(r"HCl, \; HNO_3, \; NaOH, \; KOH, \; NaHCO_3").scale(1.0).shift(band_shift(9) + UP * 0.3)
        self.play(Write(b9_l1))
        self.wait(2)
        self.play(Write(b9_l2))
        self.wait(2)
        b9_l3 = Tex("Double-strength minus needs TWO singles:").scale(1.0).shift(band_shift(9) + DOWN * 0.7)
        b9_l4 = MathTex(r"H_2SO_4 \qquad Na_2CO_3").scale(1.1).shift(band_shift(9) + DOWN * 1.6)
        self.play(Write(b9_l3))
        self.wait(2)
        self.play(Write(b9_l4))
        self.play(Create(SurroundingRectangle(b9_l4, color=GREEN)))
        self.wait(2)
        b9_l5 = Tex("The subscript 2 IS the second magnet").scale(1.0).shift(band_shift(9) + DOWN * 2.6)
        self.play(Write(b9_l5))
        self.wait(3)

        # --- Band 10 (subtopic_7): salts as compound words ---
        self.next_band(10)
        b10_t = Tex("Read a salt like a compound word").scale(1.15).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_t))
        self.wait(2)
        b10_l1 = Tex("First name from the base,").scale(1.05).shift(band_shift(10) + UP * 1.2)
        b10_l2 = Tex("surname from the acid").scale(1.05).shift(band_shift(10) + UP * 0.5)
        self.play(Write(b10_l1))
        self.wait(1.5)
        self.play(Write(b10_l2))
        self.wait(2)
        b10_l3 = Tex("Potassium nitrate: KOH and nitric acid").scale(1.0).shift(band_shift(10) + DOWN * 0.5)
        self.play(Write(b10_l3))
        self.wait(2)
        b10_l4 = MathTex(r"H^+ + OH^- \rightarrow H_2O").scale(1.1).shift(band_shift(10) + DOWN * 1.5)
        self.play(Write(b10_l4))
        self.play(Create(SurroundingRectangle(b10_l4, color=GREEN)))
        self.wait(2)
        b10_l5 = Tex("Salt AND water, every neutralisation —").scale(1.0).shift(band_shift(10) + DOWN * 2.5)
        b10_l6 = Tex("the fizz waits for the carbonate lessons").scale(1.0).shift(band_shift(10) + DOWN * 3.2)
        self.play(Write(b10_l5))
        self.wait(1.5)
        self.play(Write(b10_l6))
        self.wait(4)
