from manim import *

# Band-layout whiteboard scene: sequential vertical bands, one per teaching
# beat, camera moves down between bands, add-only lifecycle. Exporter-safe
# mobjects only; every working line is a single-string MathTex revealed with
# Write. Covers all seven subtopics of the duo (Part 1 — Expert: 1-4;
# Part 2 — Simplifier: 5-7); band time apportioned to subtopics.json
# (225/230/245/240/195/195/200 of 1530 s).

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class GrowthAndDecaySession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic display holds while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): the four formulae
        title = Tex("Growth and Decay: the Full Kit").scale(1.25).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        s0_l1 = MathTex(r"\text{Simple growth: } A = P(1 + in)").scale(1.1).shift(UP * 1.0)
        s0_l2 = MathTex(r"\text{Compound growth: } A = P(1 + i)^n").scale(1.1).shift(UP * 0.1)
        s0_l3 = MathTex(r"\text{Simple decay: } A = P(1 - in)").scale(1.1).shift(DOWN * 0.8)
        s0_l4 = MathTex(r"\text{Compound decay: } A = P(1 - i)^n").scale(1.1).shift(DOWN * 1.7)
        self.play(Write(s0_l1))
        self.wait(1.5)
        self.play(Write(s0_l2))
        self.wait(1.5)
        self.play(Write(s0_l3))
        self.wait(1.5)
        self.play(Write(s0_l4))
        self.wait(2)
        s0_l5 = Tex(r"Simple adds (arithmetic); compound multiplies (geometric)").scale(0.95).shift(DOWN * 2.8)
        self.play(Write(s0_l5))
        self.wait(3)

        # --- Band 1 (subtopic_1): worked drill + matching i and n
        self.next_band(1)
        b1_title = Tex(r"R15\,000 at 8\% p.a., compounded annually, 5 years").scale(1.0).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_title))
        self.wait(2)
        b1_l1 = MathTex(r"A = 15\,000 \times 1{,}08^5").scale(1.15).shift(band_shift(1) + UP * 1.1)
        b1_l2 = MathTex(r"1{,}08^5 = 1{,}469328").scale(1.1).shift(band_shift(1) + UP * 0.2)
        b1_l3 = MathTex(r"A = \text{R}22\,039{,}92").scale(1.15).shift(band_shift(1) + DOWN * 0.8)
        self.play(Write(b1_l1))
        self.wait(2)
        self.play(Write(b1_l2))
        self.wait(2)
        self.play(Write(b1_l3))
        self.play(Create(SurroundingRectangle(b1_l3, color=GREEN)))
        self.wait(2)
        b1_l4 = Tex(r"Match $i$ and $n$ to the compounding period:").scale(1.0).shift(band_shift(1) + DOWN * 1.9)
        b1_l5 = MathTex(r"i = \frac{0{,}09}{12} = 0{,}0075; \;\; 2 \text{ yr} = 24 \text{ mo}").scale(0.95).shift(band_shift(1) + DOWN * 2.8)
        self.play(Write(b1_l4))
        self.wait(2)
        self.play(Write(b1_l5))
        self.wait(3)

        # --- Band 2 (subtopic_2): solving for the rate — the bakkie
        self.next_band(2)
        b2_title = Tex(r"Bakkie: R250\,000 $\to$ R128\,000 in 3 years. Rate?").scale(1.0).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_title))
        self.wait(2)
        b2_l1 = MathTex(r"128\,000 = 250\,000\,(1 - i)^3").scale(1.1).shift(band_shift(2) + UP * 1.1)
        b2_l2 = MathTex(r"(1 - i)^3 = \frac{128\,000}{250\,000} = 0{,}512").scale(1.1).shift(band_shift(2) + UP * 0.1)
        b2_l3 = MathTex(r"1 - i = \sqrt[3]{0{,}512} = 0{,}8").scale(1.1).shift(band_shift(2) + DOWN * 1.0)
        b2_l4 = MathTex(r"i = 0{,}2 = 20\% \text{ per annum}").scale(1.1).shift(band_shift(2) + DOWN * 2.0)
        self.play(Write(b2_l1))
        self.wait(2.5)
        self.play(Write(b2_l2))
        self.wait(2.5)
        self.play(Write(b2_l3))
        self.wait(2)
        self.play(Write(b2_l4))
        self.play(Create(SurroundingRectangle(b2_l4, color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_2): the growth twin + disciplines
        self.next_band(3)
        b3_title = Tex(r"Growth twin: R10\,000 $\to$ R13\,604{,}89 in 4 years").scale(1.0).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_title))
        self.wait(2)
        b3_l1 = MathTex(r"(1 + i)^4 = 1{,}360489").scale(1.1).shift(band_shift(3) + UP * 1.1)
        b3_l2 = MathTex(r"1 + i = 1{,}360489^{0{,}25} = 1{,}08").scale(1.1).shift(band_shift(3) + UP * 0.1)
        b3_l3 = MathTex(r"i = 8\% \text{ per annum}").scale(1.1).shift(band_shift(3) + DOWN * 0.9)
        self.play(Write(b3_l1))
        self.wait(2.5)
        self.play(Write(b3_l2))
        self.wait(2.5)
        self.play(Write(b3_l3))
        self.play(Create(SurroundingRectangle(b3_l3, color=GREEN)))
        self.wait(2)
        b3_l4 = Tex(r"Divide BEFORE rooting: the root acts on $A/P$").scale(1.0).shift(band_shift(3) + DOWN * 2.0)
        b3_l5 = Tex(r"Decay root above 1? The fraction was inverted").scale(1.0).shift(band_shift(3) + DOWN * 2.9)
        self.play(Write(b3_l4))
        self.wait(2)
        self.play(Write(b3_l5))
        self.wait(3)

        # --- Band 4 (subtopic_3): solving for time — enter the logarithm
        self.next_band(4)
        b4_title = Tex(r"How long for R5\,000 to double at 9\% p.a.?").scale(1.1).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_title))
        self.wait(2)
        b4_l1 = MathTex(r"10\,000 = 5\,000 \times 1{,}09^n \;\Rightarrow\; 1{,}09^n = 2").scale(1.05).shift(band_shift(4) + UP * 1.1)
        self.play(Write(b4_l1))
        self.wait(2.5)
        b4_l2 = Tex(r"Unknown in the EXPONENT — no root reaches it").scale(1.0).shift(band_shift(4) + UP * 0.2)
        b4_l3 = MathTex(r"y = \log_b x \;\Leftrightarrow\; b^y = x").scale(1.1).shift(band_shift(4) + DOWN * 0.7)
        b4_l4 = MathTex(r"n = \log_{1{,}09} 2 = \frac{\log 2}{\log 1{,}09} = 8{,}04").scale(1.1).shift(band_shift(4) + DOWN * 1.8)
        self.play(Write(b4_l2))
        self.wait(2)
        self.play(Write(b4_l3))
        self.wait(2.5)
        self.play(Write(b4_l4))
        self.play(Create(SurroundingRectangle(b4_l4, color=GREEN)))
        self.wait(3)

        # --- Band 5 (subtopic_3): interpret against the crediting schedule
        self.next_band(5)
        b5_title = Tex("The decimal is not yet an answer").scale(1.15).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_title))
        self.wait(1.5)
        b5_l1 = MathTex(r"1{,}09^{8} \approx 1{,}9926 \;\; \text{(not yet doubled)}").scale(1.05).shift(band_shift(5) + UP * 1.1)
        b5_l2 = MathTex(r"1{,}09^{9} \approx 2{,}1719 \;\; \text{(past double)}").scale(1.05).shift(band_shift(5) + UP * 0.2)
        b5_l3 = Tex(r"Money first exceeds double at the END OF YEAR 9").scale(1.05).shift(band_shift(5) + DOWN * 0.8)
        self.play(Write(b5_l1))
        self.wait(2.5)
        self.play(Write(b5_l2))
        self.wait(2.5)
        self.play(Write(b5_l3))
        self.play(Create(SurroundingRectangle(b5_l3, color=GREEN)))
        self.wait(2.5)
        b5_l4 = MathTex(r"\text{Inflation } 6\%: \; \frac{\log 2}{\log 1{,}06} = 11{,}9 \text{ yr}").scale(0.95).shift(band_shift(5) + DOWN * 2.1)
        self.play(Write(b5_l4))
        self.wait(3)

        # --- Band 6 (subtopic_4): changing conditions — walk the timeline
        self.next_band(6)
        b6_title = Tex(r"R10\,000 at 8\%; +R5\,000 end yr 2; 9\% from yr 3").scale(0.95).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_title))
        self.wait(2)
        b6_l1 = MathTex(r"\text{Years 0–2: } 10\,000 \times 1{,}08^2 = 11\,664").scale(1.0).shift(band_shift(6) + UP * 1.1)
        b6_l2 = MathTex(r"\text{Add deposit: } 11\,664 + 5\,000 = 16\,664").scale(1.0).shift(band_shift(6) + UP * 0.2)
        b6_l3 = MathTex(r"\text{Year 2–3 at } 8\%: \; 16\,664 \times 1{,}08 = 17\,997{,}12").scale(1.0).shift(band_shift(6) + DOWN * 0.7)
        b6_l4 = MathTex(r"\text{Years 3–5 at } 9\%: \; 17\,997{,}12 \times 1{,}09^2").scale(1.0).shift(band_shift(6) + DOWN * 1.6)
        b6_l5 = MathTex(r"= \text{R}21\,382{,}38").scale(1.1).shift(band_shift(6) + DOWN * 2.6)
        self.play(Write(b6_l1))
        self.wait(2.5)
        self.play(Write(b6_l2))
        self.wait(2)
        self.play(Write(b6_l3))
        self.wait(2.5)
        self.play(Write(b6_l4))
        self.wait(2)
        self.play(Write(b6_l5))
        self.play(Create(SurroundingRectangle(b6_l5, color=GREEN)))
        self.wait(3)

        # --- Band 7 (subtopic_4): the rules that make timelines safe
        self.next_band(7)
        b7_title = Tex("Timeline rules").scale(1.2).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_title))
        self.wait(1.5)
        b7_l1 = Tex(r"Every amount travels through every period it is present").scale(1.0).shift(band_shift(7) + UP * 1.1)
        b7_l2 = Tex(r"Rate changes cut the line into regimes").scale(1.05).shift(band_shift(7) + UP * 0.2)
        b7_l3 = Tex(r"Withdrawals subtract at their date, then stop growing").scale(1.0).shift(band_shift(7) + DOWN * 0.7)
        b7_l4 = Tex(r"Alternative: grow each deposit separately, then add").scale(1.0).shift(band_shift(7) + DOWN * 1.6)
        b7_l5 = Tex(r"Draw the line first — bookkeeping, not acrobatics").scale(1.05).shift(band_shift(7) + DOWN * 2.6)
        self.play(Write(b7_l1))
        self.wait(2.5)
        self.play(Write(b7_l2))
        self.wait(2)
        self.play(Write(b7_l3))
        self.wait(2)
        self.play(Write(b7_l4))
        self.wait(2)
        self.play(Write(b7_l5))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 8 (subtopic_5): escalator up, escalator down
        self.next_band(8)
        b8_title = Tex("Escalator up, escalator down").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_title))
        self.wait(2)
        b8_l1 = MathTex(r"\text{Escalator: } \times 1{,}08 \text{ every year}").scale(1.0).shift(band_shift(8) + UP * 1.2)
        b8_l1b = MathTex(r"15\,000 \times 1{,}08^5 = 22\,039{,}92").scale(1.0).shift(band_shift(8) + UP * 0.4)
        b8_l2 = MathTex(r"\text{Stairs: } +1\,200 \text{ a year, on the original}").scale(0.95).shift(band_shift(8) + DOWN * 0.4)
        self.play(Write(b8_l1))
        self.wait(2)
        self.play(Write(b8_l1b))
        self.wait(2)
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = MathTex(r"\text{Decay: } \times 0{,}85 \text{ — never reaches zero}").scale(0.95).shift(band_shift(8) + DOWN * 1.2)
        self.play(Write(b8_l3))
        self.wait(2.5)
        b8_l4 = Tex(r"Two questions: up or down? stairs or escalator?").scale(1.0).shift(band_shift(8) + DOWN * 2.2)
        self.play(Write(b8_l4))
        self.play(Create(SurroundingRectangle(b8_l4, color=GREEN)))
        self.wait(3.5)

        # --- Band 9 (subtopic_6): the car lot detective
        self.next_band(9)
        b9_title = Tex("The car lot detective: un-multiply").scale(1.15).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_title))
        self.wait(2)
        b9_l1 = MathTex(r"\text{Kept: } \frac{128\,000}{250\,000} = 0{,}512").scale(1.05).shift(band_shift(9) + UP * 1.1)
        b9_l2 = MathTex(r"\sqrt[3]{0{,}512} = 0{,}8 \;\; (0{,}8 \times 0{,}8 \times 0{,}8 = 0{,}512)").scale(1.0).shift(band_shift(9) + UP * 0.1)
        b9_l3 = MathTex(r"\text{Each year kept } 80\%: \text{ shed } 20\% \text{ p.a.}").scale(1.05).shift(band_shift(9) + DOWN * 0.9)
        self.play(Write(b9_l1))
        self.wait(2.5)
        self.play(Write(b9_l2))
        self.wait(2.5)
        self.play(Write(b9_l3))
        self.play(Create(SurroundingRectangle(b9_l3, color=GREEN)))
        self.wait(2.5)
        b9_l4 = Tex(r"Divide end by start FIRST; decay factor sits below 1").scale(0.95).shift(band_shift(9) + DOWN * 2.0)
        self.play(Write(b9_l4))
        self.wait(3)

        # --- Band 10 (subtopic_7): how long until it doubles
        self.next_band(10)
        b10_title = Tex("How long until it doubles").scale(1.2).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_title))
        self.wait(2)
        b10_l1 = MathTex(r"1{,}09^n = 2 \;\; \text{— the unknown is upstairs}").scale(1.05).shift(band_shift(10) + UP * 1.1)
        b10_l2 = MathTex(r"n = \frac{\log 2}{\log 1{,}09} \approx 8{,}04").scale(1.1).shift(band_shift(10) + UP * 0.0)
        self.play(Write(b10_l1))
        self.wait(2.5)
        self.play(Write(b10_l2))
        self.wait(2.5)
        b10_l3 = Tex(r"Interest lands at year ends: end of year 9").scale(1.05).shift(band_shift(10) + DOWN * 1.1)
        self.play(Write(b10_l3))
        self.play(Create(SurroundingRectangle(b10_l3, color=GREEN)))
        self.wait(2.5)
        b10_l4 = MathTex(r"\text{Prices at } 6\%: \; 11{,}9 \text{ years to double}").scale(0.95).shift(band_shift(10) + DOWN * 2.2)
        self.play(Write(b10_l4))
        self.wait(4)
