from manim import *

# Band-layout whiteboard scene for "Analysis and Interpretation" (grade 12,
# term 1, companies). One band per teaching beat; the camera moves down and
# nothing is removed. Part 1 (Expert) = subtopics 1-4, Part 2 (Simplifier)
# = subtopics 5-7 in fresh bands. Exporter-safe primitives only; write-only
# reveals. Subtopic durations 235/245/240/230/200/210/210 of 1570 s guide
# the apportioning.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class AnalysisInterpretationSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md plays.
        self.wait(14)

        # ===== Part 1 — Expert =====
        # --- Band 0 (subtopic_1): liquidity on Khanya's figures ---
        title = Tex("Analysis and Interpretation").scale(1.25).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        b0_l1 = Tex("Khanya Ltd: current assets R840 000").scale(1.05).shift(UP * 1.2)
        b0_l2 = Tex("(stock 360, debtors 330, cash 150)").scale(0.95).shift(UP * 0.5)
        b0_l3 = Tex("Current liabilities R400 000").scale(1.05).shift(DOWN * 0.3)
        self.play(Write(b0_l1))
        self.play(Write(b0_l2))
        self.wait(2)
        self.play(Write(b0_l3))
        self.wait(2)
        b0_l4 = Tex("Current ratio: 840:400 $=$ 2,1:1").scale(1.05).shift(DOWN * 1.2)
        b0_l5 = Tex("Acid-test: 480:400 $=$ 1,2:1").scale(1.05).shift(DOWN * 2.1)
        self.play(Write(b0_l4))
        self.wait(2)
        self.play(Write(b0_l5))
        self.play(Create(SurroundingRectangle(b0_l5, color=GREEN)))
        b0_l6 = Tex("covered even without selling stock").scale(0.95).shift(DOWN * 3.0)
        self.play(Write(b0_l6))
        self.wait(3)

        # --- Band 1 (subtopic_1): the operating cycle, read together ---
        self.next_band(1)
        b1_t = Tex("The operating cycle, read together").scale(1.1).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_t))
        self.wait(2)
        b1_l1 = Tex("Stock turnover: 2 880 000 $\\div$ 360 000").scale(1.0).shift(band_shift(1) + UP * 1.2)
        b1_l2 = Tex("$=$ 8 times — about 45 days on the shelf").scale(1.0).shift(band_shift(1) + UP * 0.4)
        self.play(Write(b1_l1))
        self.play(Write(b1_l2))
        self.wait(2.5)
        b1_l3 = Tex("Debtors: 330/3 960 $\\times$ 365 $=$ 30,4 days").scale(1.0).shift(band_shift(1) + DOWN * 0.5)
        b1_l4 = Tex("Creditors: 400/2 920 $\\times$ 365 $=$ 50 days").scale(1.0).shift(band_shift(1) + DOWN * 1.3)
        self.play(Write(b1_l3))
        self.wait(2)
        self.play(Write(b1_l4))
        self.wait(2)
        b1_l5 = Tex("Collect in 30, pay in 50: suppliers").scale(1.0).shift(band_shift(1) + DOWN * 2.2)
        b1_l6 = Tex("finance the debtors' book — favourable").scale(1.0).shift(band_shift(1) + DOWN * 2.9)
        self.play(Write(b1_l5))
        self.play(Write(b1_l6))
        self.wait(2)
        b1_l7 = Tex("Solvency: 4 385:1 340 $=$ 3,3:1").scale(1.0).shift(band_shift(1) + DOWN * 3.6)
        self.play(Write(b1_l7))
        self.wait(3)

        # --- Band 2 (subtopic_2): ROSHE and ROTCE ---
        self.next_band(2)
        b2_t = Tex("What did the money earn?").scale(1.15).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(2)
        b2_l1 = Tex("ROSHE: profit after tax R450 000").scale(1.0).shift(band_shift(2) + UP * 1.2)
        b2_l2 = Tex("$\\div$ average equity R3 000 000 $=$ 15\\%").scale(1.0).shift(band_shift(2) + UP * 0.4)
        self.play(Write(b2_l1))
        self.wait(2)
        self.play(Write(b2_l2))
        self.play(Create(SurroundingRectangle(b2_l2, color=GREEN)))
        b2_l3 = Tex("vs a fixed deposit at 8\\%: risk rewarded").scale(0.95).shift(band_shift(2) + DOWN * 0.4)
        self.play(Write(b2_l3))
        self.wait(2.5)
        b2_l4 = Tex("ROTCE: before tax and interest —").scale(1.0).shift(band_shift(2) + DOWN * 1.3)
        b2_l5 = Tex("(620 000 $+$ 80 000) $\\div$ 4 000 000").scale(1.0).shift(band_shift(2) + DOWN * 2.1)
        b2_l6 = Tex("$=$ 17,5\\% — the engine before the split").scale(1.0).shift(band_shift(2) + DOWN * 2.9)
        self.play(Write(b2_l4))
        self.wait(2)
        self.play(Write(b2_l5))
        self.wait(2)
        self.play(Write(b2_l6))
        self.play(Create(SurroundingRectangle(b2_l6, color=GREEN)))
        self.wait(3)

        # --- Band 3 (subtopic_2): the per-share four ---
        self.next_band(3)
        b3_t = Tex("The per-share toolkit").scale(1.15).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t))
        self.wait(2)
        b3_l1 = Tex("EPS: R450 000 $\\div$ 1 000 000 $=$ 45 cents").scale(1.0).shift(band_shift(3) + UP * 1.2)
        self.play(Write(b3_l1))
        self.wait(2)
        b3_l2 = Tex("DPS: R360 000 $\\div$ 1 000 000 $=$ 36 cents").scale(1.0).shift(band_shift(3) + UP * 0.4)
        b3_l3 = Tex("(interim 15 $+$ final 21)").scale(0.95).shift(band_shift(3) + DOWN * 0.3)
        self.play(Write(b3_l2))
        self.play(Write(b3_l3))
        self.wait(2.5)
        b3_l4 = Tex("Pay-out rate: 36/45 $=$ 80\\% paid,").scale(1.0).shift(band_shift(3) + DOWN * 1.1)
        b3_l5 = Tex("one fifth retained — depends on the plans").scale(1.0).shift(band_shift(3) + DOWN * 1.9)
        self.play(Write(b3_l4))
        self.play(Write(b3_l5))
        self.wait(2.5)
        b3_l6 = Tex("NAV: R3 045 000 $\\div$ 1 000 000").scale(1.0).shift(band_shift(3) + DOWN * 2.7)
        b3_l7 = Tex("$=$ 304,5 cents per share, by the books").scale(1.0).shift(band_shift(3) + DOWN * 3.5)
        self.play(Write(b3_l6))
        self.wait(2)
        self.play(Write(b3_l7))
        self.play(Create(SurroundingRectangle(b3_l7, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): should Khanya borrow more? ---
        self.next_band(4)
        b4_t = Tex("Should Khanya borrow more?").scale(1.1).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(2)
        b4_l1 = Tex("Debt-equity: 940:3 045 $=$ 0,31:1 — light").scale(1.0).shift(band_shift(4) + UP * 1.2)
        self.play(Write(b4_l1))
        self.wait(2)
        b4_l2 = Tex("ROTCE 17,5\\% vs loan cost 8\\%:").scale(1.05).shift(band_shift(4) + UP * 0.3)
        b4_l3 = Tex("each borrowed rand earns 17,5c, costs 8c").scale(1.0).shift(band_shift(4) + DOWN * 0.5)
        self.play(Write(b4_l2))
        self.wait(2)
        self.play(Write(b4_l3))
        self.play(Create(SurroundingRectangle(b4_l3, color=GREEN)))
        self.wait(2)
        b4_l4 = Tex("POSITIVE gearing — room to gear up").scale(1.0).shift(band_shift(4) + DOWN * 1.4)
        self.play(Write(b4_l4))
        self.wait(2)
        b4_l5 = Tex("The risk: fixed interest is owed").scale(1.0).shift(band_shift(4) + DOWN * 2.3)
        b4_l6 = Tex("in the bad years too").scale(1.0).shift(band_shift(4) + DOWN * 3.0)
        self.play(Write(b4_l5))
        self.play(Write(b4_l6))
        self.wait(3)

        # --- Band 5 (subtopic_3): the share price and the scorecard ---
        self.next_band(5)
        b5_t = Tex("Is the share price sensible?").scale(1.1).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_t))
        self.wait(2)
        b5_l1 = Tex("Market price 380c vs NAV 304,5c:").scale(1.05).shift(band_shift(5) + UP * 1.2)
        b5_l2 = Tex("a premium of 75,5 cents per share").scale(1.05).shift(band_shift(5) + UP * 0.4)
        self.play(Write(b5_l1))
        self.wait(2)
        self.play(Write(b5_l2))
        self.wait(2)
        b5_l3 = Tex("The market prices what books cannot:").scale(1.0).shift(band_shift(5) + DOWN * 0.5)
        b5_l4 = Tex("future profits, brand, management").scale(1.0).shift(band_shift(5) + DOWN * 1.2)
        self.play(Write(b5_l3))
        self.play(Write(b5_l4))
        self.wait(2.5)
        b5_l5 = Tex("EPS 45c covers DPS 36c — genuine").scale(1.0).shift(band_shift(5) + DOWN * 2.1)
        self.play(Write(b5_l5))
        self.wait(2)
        b5_trap = Tex("EPS growth after a buy-back $=$ improvement?").scale(0.95).shift(band_shift(5) + DOWN * 2.9)
        self.play(Write(b5_trap))
        self.play(Create(strike(b5_trap)))
        b5_fix = Tex("fewer shares flatter the ratio").scale(0.95).shift(band_shift(5) + DOWN * 3.6)
        self.play(Write(b5_fix))
        self.wait(3)

        # --- Band 6 (subtopic_4): the published annual report ---
        self.next_band(6)
        b6_t = Tex("Reading a published annual report").scale(1.1).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_t))
        self.wait(2)
        b6_l1 = Tex("Directors' report: the players write").scale(1.0).shift(band_shift(6) + UP * 1.2)
        b6_l2 = Tex("the match report — read critically").scale(1.0).shift(band_shift(6) + UP * 0.5)
        self.play(Write(b6_l1))
        self.play(Write(b6_l2))
        self.wait(2.5)
        b6_l3 = Tex("Auditor's report: the referee — find").scale(1.0).shift(band_shift(6) + DOWN * 0.4)
        b6_l4 = Tex("the opinion paragraph FIRST").scale(1.0).shift(band_shift(6) + DOWN * 1.1)
        self.play(Write(b6_l3))
        self.play(Write(b6_l4))
        self.wait(2.5)
        b6_l5 = Tex("Abridged statements; governance and the").scale(0.95).shift(band_shift(6) + DOWN * 2.0)
        b6_l6 = Tex("King Code: responsibility, accountability,").scale(0.95).shift(band_shift(6) + DOWN * 2.7)
        b6_l7 = Tex("fairness, transparency").scale(0.95).shift(band_shift(6) + DOWN * 3.4)
        self.play(Write(b6_l5))
        self.play(Write(b6_l6))
        self.play(Write(b6_l7))
        self.wait(3)

        # --- Band 7 (subtopic_4): the discipline ---
        self.next_band(7)
        b7_t = Tex("The interpretation discipline").scale(1.1).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(2)
        b7_l1 = Tex("Audit opinion first: a qualified opinion").scale(1.0).shift(band_shift(7) + UP * 1.2)
        b7_l2 = Tex("on stock undermines the stock ratios").scale(1.0).shift(band_shift(7) + UP * 0.5)
        self.play(Write(b7_l1))
        self.play(Write(b7_l2))
        self.wait(2.5)
        b7_l3 = Tex("Directors' pay up while EPS falls:").scale(1.0).shift(band_shift(7) + DOWN * 0.4)
        b7_l4 = Tex("a question for the AGM; insider trading").scale(1.0).shift(band_shift(7) + DOWN * 1.1)
        b7_l5 = Tex("and price manipulation: illegal").scale(1.0).shift(band_shift(7) + DOWN * 1.8)
        self.play(Write(b7_l3))
        self.play(Write(b7_l4))
        self.play(Write(b7_l5))
        self.wait(2.5)
        b7_l6 = Tex("Figure. Comparison. Judgement.").scale(1.15).shift(band_shift(7) + DOWN * 2.8)
        self.play(Write(b7_l6))
        self.play(Create(SurroundingRectangle(b7_l6, color=GREEN)))
        self.wait(3)

        # ===== Part 2 — Simplifier =====
        # --- Band 8 (subtopic_5): the company's report card ---
        self.next_band(8)
        b8_t = Tex("Aunt Nomsa's report card").scale(1.15).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_t))
        self.wait(2)
        b8_l1 = Tex("Bills this month? R2 ready per R1 owed;").scale(1.0).shift(band_shift(8) + UP * 1.2)
        b8_l2 = Tex("R1,20 even if the stock refuses to sell").scale(1.0).shift(band_shift(8) + UP * 0.5)
        self.play(Write(b8_l1))
        self.play(Write(b8_l2))
        self.wait(2.5)
        b8_l3 = Tex("Speeds: stock turns 8 times; customers").scale(1.0).shift(band_shift(8) + DOWN * 0.4)
        b8_l4 = Tex("pay in 30 days; suppliers wait 50 —").scale(1.0).shift(band_shift(8) + DOWN * 1.1)
        b8_l5 = Tex("their patience finances the debtors").scale(1.0).shift(band_shift(8) + DOWN * 1.8)
        self.play(Write(b8_l3))
        self.play(Write(b8_l4))
        self.wait(2)
        self.play(Write(b8_l5))
        self.wait(2)
        b8_l6 = Tex("Bad year? Owns three times what it owes").scale(1.0).shift(band_shift(8) + DOWN * 2.7)
        self.play(Write(b8_l6))
        self.wait(2)
        b8_l7 = Tex("Never ``is profit big'' — big compared to WHAT?").scale(0.95).shift(band_shift(8) + DOWN * 3.5)
        self.play(Write(b8_l7))
        self.wait(3)

        # --- Band 9 (subtopic_6): whose money works harder? ---
        self.next_band(9)
        b9_t = Tex("Whose money works harder?").scale(1.15).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(2)
        b9_l1 = Tex("The engine: 17,5c on every rand in the pot").scale(1.0).shift(band_shift(9) + UP * 1.2)
        b9_l2 = Tex("The bank charges 8c and takes it EVERY year").scale(1.0).shift(band_shift(9) + UP * 0.4)
        self.play(Write(b9_l1))
        self.wait(2)
        self.play(Write(b9_l2))
        self.wait(2)
        b9_l3 = Tex("The family keeps the difference: 15\\%").scale(1.05).shift(band_shift(9) + DOWN * 0.5)
        self.play(Write(b9_l3))
        self.play(Create(SurroundingRectangle(b9_l3, color=GREEN)))
        self.wait(2)
        b9_l4 = Tex("Gearing is an amplifier: good years").scale(1.0).shift(band_shift(9) + DOWN * 1.4)
        b9_l5 = Tex("better, bad years worse").scale(1.0).shift(band_shift(9) + DOWN * 2.1)
        self.play(Write(b9_l4))
        self.play(Write(b9_l5))
        self.wait(2.5)
        b9_l6 = Tex("Fixed-deposit test: 15 vs 8 — seven").scale(1.0).shift(band_shift(9) + DOWN * 2.9)
        b9_l7 = Tex("extra cents is the price of courage").scale(1.0).shift(band_shift(9) + DOWN * 3.6)
        self.play(Write(b9_l6))
        self.play(Write(b9_l7))
        self.wait(3)

        # --- Band 10 (subtopic_7): the price and the value ---
        self.next_band(10)
        b10_t = Tex("The price on the board,").scale(1.1).shift(band_shift(10) + UP * 2.6)
        b10_t2 = Tex("the value in the books").scale(1.1).shift(band_shift(10) + UP * 1.9)
        self.play(Write(b10_t))
        self.play(Write(b10_t2))
        self.wait(2)
        b10_l1 = Tex("Books: 304,5c a slice; cousins pay 380c").scale(1.0).shift(band_shift(10) + UP * 1.1)
        b10_l2 = Tex("They buy the FUTURE, not the fridges").scale(1.0).shift(band_shift(10) + UP * 0.4)
        self.play(Write(b10_l1))
        self.wait(2)
        self.play(Write(b10_l2))
        self.wait(2.5)
        b10_l3 = Tex("Each slice earned 45c, was paid 36c;").scale(1.0).shift(band_shift(10) + DOWN * 0.4)
        b10_l4 = Tex("the 9c stayed in, growing every slice").scale(1.0).shift(band_shift(10) + DOWN * 1.1)
        self.play(Write(b10_l3))
        self.wait(2)
        self.play(Write(b10_l4))
        self.wait(2)
        b10_l5 = Tex("Pay-out 80\\%: grandmother loves it;").scale(1.0).shift(band_shift(10) + DOWN * 1.9)
        b10_l6 = Tex("the expansion cousin wants 40").scale(1.0).shift(band_shift(10) + DOWN * 2.6)
        self.play(Write(b10_l5))
        self.play(Write(b10_l6))
        self.wait(2.5)
        b10_l7 = Tex("Figure, comparison, judgement — always").scale(1.0).shift(band_shift(10) + DOWN * 3.4)
        self.play(Write(b10_l7))
        self.play(Create(SurroundingRectangle(b10_l7, color=GREEN)))
        self.wait(4)
