from manim import *

# Band-layout whiteboard scene for the session duo "Factors of Production and
# Their Remuneration" (Grade 11, Term 1). One band per teaching step; the
# camera moves down to fresh space and nothing is ever removed. Only
# exporter-safe mobjects are used (Tex/MathTex/Line/Arrow/Dot/Circle/
# Rectangle/SurroundingRectangle/VGroup); diagrams are hand-built from
# primitives. Band dwell time is apportioned to subtopics.json
# (200/230/250/250/170/190/180 of 1470 s).

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class FactorsOfProductionSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md audio plays.
        self.wait(14)

        # ============ Part 1 — Expert ============
        # --- Band 0 (subtopic_1): four factors, four rewards ---
        title = Tex("Factors of Production and Their Rewards").scale(1.25).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        p1 = Tex(r"Natural resources $\Rightarrow$ RENT").scale(1.15).shift(UP * 1.2)
        p2 = Tex(r"Labour $\Rightarrow$ WAGES and salaries").scale(1.15).shift(UP * 0.3)
        p3 = Tex(r"Capital $\Rightarrow$ INTEREST").scale(1.15).shift(DOWN * 0.6)
        p4 = Tex(r"Entrepreneurship $\Rightarrow$ PROFIT").scale(1.15).shift(DOWN * 1.5)
        for m in (p1, p2, p3, p4):
            self.play(Write(m))
            self.wait(1.5)
        rule = Tex("The pairing must be exact").scale(1.1).shift(DOWN * 2.6)
        self.play(Write(rule))
        self.play(Create(SurroundingRectangle(VGroup(p1, p2, p3, p4), color=GREEN)))
        self.wait(3)

        # --- Band 1 (subtopic_1): circular flow + the mismatched-pair trap ---
        self.next_band(1)
        b1_title = Tex("Factor market: households meet firms").scale(1.15).shift(band_shift(1) + UP * 2.4)
        self.play(Write(b1_title))
        self.wait(1.5)
        hh = Rectangle(width=3.4, height=1.2).shift(band_shift(1) + LEFT * 3.6 + UP * 0.8)
        hh_lab = Tex("Households (own factors)").scale(0.8).move_to(hh.get_center())
        fm = Rectangle(width=3.4, height=1.2).shift(band_shift(1) + RIGHT * 3.6 + UP * 0.8)
        fm_lab = Tex("Firms (buy factors)").scale(0.8).move_to(fm.get_center())
        self.play(Create(hh), Write(hh_lab))
        self.play(Create(fm), Write(fm_lab))
        self.wait(1.5)
        a_top = Arrow(hh.get_right() + UP * 0.25, fm.get_left() + UP * 0.25, buff=0.1)
        a_top_lab = Tex("factor services").scale(0.75).shift(band_shift(1) + UP * 1.75)
        a_bot = Arrow(fm.get_left() + DOWN * 0.25, hh.get_right() + DOWN * 0.25, buff=0.1)
        a_bot_lab = Tex("rent, wages, interest, profit").scale(0.75).shift(band_shift(1) + UP * 0.05)
        self.play(Create(a_top), Write(a_top_lab))
        self.wait(1.5)
        self.play(Create(a_bot), Write(a_bot_lab))
        self.wait(2)
        flow = Tex("National income $=$ national product").scale(1.05).shift(band_shift(1) + DOWN * 1.0)
        self.play(Write(flow))
        self.wait(2)
        trap1 = Tex("Interest rewards entrepreneurship").scale(1.0).shift(band_shift(1) + DOWN * 1.9)
        self.play(Write(trap1))
        self.play(Create(strike(trap1)))
        self.wait(1.5)
        trap2 = Tex("Dividends: distributed profit, not a factor reward").scale(1.0).shift(band_shift(1) + DOWN * 2.8)
        self.play(Write(trap2))
        self.wait(3)

        # --- Band 2 (subtopic_2): natural resources — fixed supply sets rent ---
        self.next_band(2)
        b2_title = Tex("Natural resources: supply is FIXED").scale(1.15).shift(band_shift(2) + UP * 2.4)
        self.play(Write(b2_title))
        self.wait(1.5)
        ch = Tex("Not produced; unevenly spread; immobile").scale(1.0).shift(band_shift(2) + UP * 1.5)
        self.play(Write(ch))
        self.wait(2)
        # Hand-built axes: vertical supply, downward demand, rent at the cross.
        origin = band_shift(2) + LEFT * 4.2 + DOWN * 2.4
        ax_y = Arrow(origin, origin + UP * 3.2, buff=0)
        ax_x = Arrow(origin, origin + RIGHT * 4.6, buff=0)
        ylab = Tex("Rent").scale(0.8).move_to(origin + UP * 3.2 + RIGHT * 0.7)
        xlab = Tex("Q").scale(0.8).move_to(origin + RIGHT * 4.6 + UP * 0.35)
        self.play(Create(ax_y), Create(ax_x), Write(ylab), Write(xlab))
        self.wait(1.5)
        s_line = Line(origin + RIGHT * 2.6, origin + RIGHT * 2.6 + UP * 2.9, stroke_width=5)
        s_lab = Tex("S (fixed)").scale(0.8).move_to(origin + RIGHT * 3.5 + UP * 2.8)
        self.play(Create(s_line), Write(s_lab))
        self.wait(1.5)
        d1 = Line(origin + UP * 2.6 + RIGHT * 0.3, origin + UP * 1.5 + RIGHT * 2.0, stroke_width=5)
        d2 = Line(origin + UP * 1.5 + RIGHT * 2.0, origin + UP * 0.5 + RIGHT * 3.9, stroke_width=5)
        d_lab = Tex("D").scale(0.8).move_to(origin + UP * 0.5 + RIGHT * 4.3)
        self.play(Create(d1), Create(d2), Write(d_lab))
        e_dot = Dot(origin + RIGHT * 2.6 + UP * 1.19)
        e_lab = Tex("rent set by demand").scale(0.75).move_to(origin + RIGHT * 2.7 + UP * 0.55 + RIGHT * 1.0)
        self.play(Create(e_dot), Write(e_lab))
        self.wait(2.5)
        mprda = Tex("MPRDA: mineral rights vest in the state").scale(0.95).shift(band_shift(2) + RIGHT * 3.1 + UP * 0.3)
        self.play(Write(mprda))
        self.wait(3)

        # --- Band 3 (subtopic_2): labour — characteristics and wages ---
        self.next_band(3)
        b3_title = Tex("Labour: the worker comes with it").scale(1.15).shift(band_shift(3) + UP * 2.4)
        self.play(Write(b3_title))
        self.wait(1.5)
        l1 = Tex("Inseparable; PERISHABLE; heterogeneous").scale(1.05).shift(band_shift(3) + UP * 1.4)
        l2 = Tex("A day not worked is lost permanently").scale(1.05).shift(band_shift(3) + UP * 0.5)
        self.play(Write(l1))
        self.wait(2)
        self.play(Write(l2))
        self.wait(2)
        l3 = Tex("Quantity $=$ labour force; Quality $=$ human capital").scale(1.0).shift(band_shift(3) + DOWN * 0.5)
        l4 = Tex("Quality raises productivity: output per worker-hour").scale(1.0).shift(band_shift(3) + DOWN * 1.4)
        self.play(Write(l3))
        self.wait(2)
        self.play(Write(l4))
        self.wait(2)
        l5 = Tex("SA puzzle: high unemployment $+$ skills MISMATCH").scale(1.0).shift(band_shift(3) + DOWN * 2.4)
        self.play(Write(l5))
        self.play(Create(SurroundingRectangle(l5, color=GREEN)))
        self.wait(3)

        # --- Band 4 (subtopic_3): capital and entrepreneurship ---
        self.next_band(4)
        b4_title = Tex("Capital saves today, produces tomorrow").scale(1.15).shift(band_shift(4) + UP * 2.4)
        self.play(Write(b4_title))
        self.wait(1.5)
        c1 = Tex("Fixed: buildings, machines. Working: stock, wage cash").scale(0.95).shift(band_shift(4) + UP * 1.4)
        self.play(Write(c1))
        self.wait(2)
        c2 = MathTex(r"\text{Net investment} = \text{gross} - \text{depreciation}").scale(1.05).shift(band_shift(4) + UP * 0.5)
        self.play(Write(c2))
        self.play(Create(SurroundingRectangle(c2, color=GREEN)))
        self.wait(2)
        c3 = Tex("Interest: price of funds (repo rate, risk, term)").scale(1.0).shift(band_shift(4) + DOWN * 0.6)
        self.play(Write(c3))
        self.wait(2)
        c4 = Tex("Entrepreneur: organises, innovates, bears risk").scale(1.0).shift(band_shift(4) + DOWN * 1.5)
        c5 = Tex("Profit is a RESIDUAL — it can be negative").scale(1.05).shift(band_shift(4) + DOWN * 2.5)
        self.play(Write(c4))
        self.wait(2)
        self.play(Write(c5))
        self.wait(3)

        # --- Band 5 (subtopic_3): value added, worked in full ---
        self.next_band(5)
        b5_title = Tex("Gqeberha metal-pressing firm, one year").scale(1.1).shift(band_shift(5) + UP * 2.4)
        self.play(Write(b5_title))
        self.wait(1.5)
        v1 = Tex(r"Sales (value of output): R4\,000\,000").scale(1.05).shift(band_shift(5) + UP * 1.4)
        v2 = Tex(r"Bought-in steel, electricity: R1\,500\,000").scale(1.05).shift(band_shift(5) + UP * 0.5)
        self.play(Write(v1))
        self.wait(2)
        self.play(Write(v2))
        self.wait(2)
        v3 = MathTex(r"4\,000\,000 - 1\,500\,000 = \text{R}2\,500\,000").scale(1.1).shift(band_shift(5) + DOWN * 0.5)
        self.play(Write(v3))
        self.wait(2)
        v4 = Tex(r"VALUE ADDED $=$ output $-$ intermediate purchases").scale(1.0).shift(band_shift(5) + DOWN * 1.5)
        self.play(Write(v4))
        self.play(Create(SurroundingRectangle(v3, color=GREEN)))
        self.wait(3)

        # --- Band 6 (subtopic_3): the share-out and the residual ---
        self.next_band(6)
        b6_title = Tex(r"Sharing the R2\,500\,000 pot").scale(1.1).shift(band_shift(6) + UP * 2.4)
        self.play(Write(b6_title))
        self.wait(1.5)
        s1 = Tex(r"Wages R1\,600\,000; rent R240\,000").scale(1.0).shift(band_shift(6) + UP * 1.4)
        s2 = Tex(r"Interest R160\,000; depreciation R200\,000").scale(1.0).shift(band_shift(6) + UP * 0.5)
        self.play(Write(s1))
        self.wait(2)
        self.play(Write(s2))
        self.wait(2)
        s3 = MathTex(r"\text{Total contractual} = \text{R}2\,200\,000").scale(1.05).shift(band_shift(6) + DOWN * 0.4)
        self.play(Write(s3))
        self.wait(2)
        s4 = MathTex(r"\text{Profit} = 2\,500\,000 - 2\,200\,000 = \text{R}300\,000").scale(1.05).shift(band_shift(6) + DOWN * 1.3)
        self.play(Write(s4))
        self.play(Create(SurroundingRectangle(s4, color=GREEN)))
        self.wait(2)
        s5 = Tex(r"Count the R1\,500\,000 of steel again").scale(1.0).shift(band_shift(6) + DOWN * 2.3)
        self.play(Write(s5))
        self.play(Create(strike(s5)))
        s6 = Tex("Intermediate goods already paid factors elsewhere").scale(0.95).shift(band_shift(6) + DOWN * 3.0)
        self.play(Write(s6))
        self.wait(3)

        # --- Band 7 (subtopic_4): local planning and access barriers ---
        self.next_band(7)
        b7_title = Tex("IDP: which factors does this town possess?").scale(1.1).shift(band_shift(7) + UP * 2.4)
        self.play(Write(b7_title))
        self.wait(1.5)
        i1 = Tex("Every municipality: Integrated Development Plan").scale(1.0).shift(band_shift(7) + UP * 1.4)
        self.play(Write(i1))
        self.wait(2)
        i2 = Tex(r"Barriers: land title $\Rightarrow$ no collateral $\Rightarrow$ no loan").scale(0.95).shift(band_shift(7) + UP * 0.5)
        i3 = Tex("Information, skills, transport, networks").scale(1.0).shift(band_shift(7) + DOWN * 0.4)
        self.play(Write(i2))
        self.wait(2)
        self.play(Write(i3))
        self.wait(2)
        i4 = Tex("Remedies: SEFA, NYDA, tenure reform, learnerships").scale(0.95).shift(band_shift(7) + DOWN * 1.3)
        self.play(Write(i4))
        self.wait(2)
        i5 = Tex("Participation: local knowledge lowers decision cost").scale(0.95).shift(band_shift(7) + DOWN * 2.2)
        self.play(Write(i5))
        self.wait(3)

        # --- Band 8 (subtopic_4): B-BBEE and preferential procurement ---
        self.next_band(8)
        b8_title = Tex("Empowerment procurement: demand with teeth").scale(1.1).shift(band_shift(8) + UP * 2.4)
        self.play(Write(b8_title))
        self.wait(1.5)
        e1 = Tex("B-BBEE scorecard: ownership, management,").scale(1.0).shift(band_shift(8) + UP * 1.4)
        e2 = Tex("skills, supplier development, socio-economic").scale(1.0).shift(band_shift(8) + UP * 0.6)
        self.play(Write(e1))
        self.play(Write(e2))
        self.wait(2.5)
        e3 = Tex(r"PPPFA tenders: 80/20 and 90/10 point splits").scale(1.05).shift(band_shift(8) + DOWN * 0.4)
        e4 = Tex("90/10 applies to larger contracts").scale(1.0).shift(band_shift(8) + DOWN * 1.3)
        self.play(Write(e3))
        self.wait(2)
        self.play(Write(e4))
        self.wait(2)
        e5 = Tex("State demand turns idle factors into incomes").scale(1.05).shift(band_shift(8) + DOWN * 2.3)
        self.play(Write(e5))
        self.play(Create(SurroundingRectangle(e5, color=GREEN)))
        self.wait(3)

        # ============ Part 2 — Simplifier ============
        # --- Band 9 (subtopic_5): the taxi rank at half past five ---
        self.next_band(9)
        b9_title = Tex("One taxi route holds all four factors").scale(1.15).shift(band_shift(9) + UP * 2.4)
        self.play(Write(b9_title))
        self.wait(2)
        t1 = Tex(r"Ground, diesel, stone in the tar $\Rightarrow$ RENT").scale(1.0).shift(band_shift(9) + UP * 1.4)
        t2 = Tex(r"Driver and marshal $\Rightarrow$ WAGES").scale(1.0).shift(band_shift(9) + UP * 0.5)
        t3 = Tex(r"Kombi, tyres, card machine $\Rightarrow$ INTEREST").scale(1.0).shift(band_shift(9) + DOWN * 0.4)
        t4 = Tex(r"The owner who saw the route $\Rightarrow$ PROFIT").scale(1.0).shift(band_shift(9) + DOWN * 1.3)
        for m in (t1, t2, t3, t4):
            self.play(Write(m))
            self.wait(1.5)
        t5 = Tex(r"The R400\,000 in the account is the capital").scale(1.0).shift(band_shift(9) + DOWN * 2.3)
        self.play(Write(t5))
        self.play(Create(strike(t5)))
        t6 = Tex("The kombi it buys is the capital").scale(1.0).shift(band_shift(9) + DOWN * 3.0)
        self.play(Write(t6))
        self.wait(3)

        # --- Band 10 (subtopic_6): splitting the day's takings ---
        self.next_band(10)
        b10_title = Tex("Splitting the month's takings").scale(1.15).shift(band_shift(10) + UP * 2.4)
        self.play(Write(b10_title))
        self.wait(2)
        m1 = MathTex(r"\text{Fares } 60\,000 - \text{diesel etc. } 22\,500 = \text{R}37\,500").scale(0.95).shift(band_shift(10) + UP * 1.4)
        self.play(Write(m1))
        self.wait(2.5)
        m2 = Tex(r"Wages R18\,000; rank fees R2\,500").scale(1.0).shift(band_shift(10) + UP * 0.5)
        m3 = Tex(r"Interest R4\,000; wear set aside R6\,000").scale(1.0).shift(band_shift(10) + DOWN * 0.4)
        self.play(Write(m2))
        self.wait(2)
        self.play(Write(m3))
        self.wait(2)
        m4 = MathTex(r"18\,000 + 2\,500 + 4\,000 + 6\,000 = 30\,500").scale(1.0).shift(band_shift(10) + DOWN * 1.3)
        self.play(Write(m4))
        self.wait(2)
        m5 = MathTex(r"\text{Owner: } 37\,500 - 30\,500 = \text{R}7\,000").scale(1.05).shift(band_shift(10) + DOWN * 2.2)
        self.play(Write(m5))
        self.play(Create(SurroundingRectangle(m5, color=GREEN)))
        self.wait(2)
        m6 = Tex("Everyone else first, owner last — that is why the owner decides").scale(0.85).shift(band_shift(10) + DOWN * 3.0)
        self.play(Write(m6))
        self.wait(3)

        # --- Band 11 (subtopic_7): plans, doors and tenders ---
        self.next_band(11)
        b11_title = Tex("Whose town is it?").scale(1.2).shift(band_shift(11) + UP * 2.4)
        self.play(Write(b11_title))
        self.wait(2)
        w1 = Tex("IDP: what have we GOT, how do we live off it?").scale(1.0).shift(band_shift(11) + UP * 1.4)
        w2 = Tex("Good soil, no packhouse: sauce is bought back").scale(1.0).shift(band_shift(11) + UP * 0.5)
        self.play(Write(w1))
        self.wait(2)
        self.play(Write(w2))
        self.wait(2)
        w3 = Tex("Three bakers, same idea: title deed, info, transport").scale(0.95).shift(band_shift(11) + DOWN * 0.4)
        w4 = Tex("None of the difference is the quality of the idea").scale(0.95).shift(band_shift(11) + DOWN * 1.3)
        self.play(Write(w3))
        self.wait(2)
        self.play(Write(w4))
        self.wait(2)
        w5 = Tex("State tenders: most points price, a set handful empowerment").scale(0.9).shift(band_shift(11) + DOWN * 2.2)
        self.play(Write(w5))
        self.wait(2)
        w6 = Tex("Demand pointed at people the old system pointed away from").scale(0.85).shift(band_shift(11) + DOWN * 3.0)
        self.play(Write(w6))
        self.play(Create(SurroundingRectangle(w6, color=GREEN)))
        self.wait(4)
