from manim import *

# Band-layout whiteboard scene for the catchment-and-river-management duo
# (drainage basins, human impact and catchment management). Exporter-safe
# primitives only (Tex/MathTex/Line/Arrow/Dot/Circle/Rectangle/VGroup);
# add-only lifecycle; camera moves down one frame-height per band.
# The superimposed/antecedent gorge diagrams are hand-built from Line
# chains and Arrows, assembled element by element in script order.
#
# Subtopic shares (subtopics.json, total 1635 s):
# 240/250/255/255 expert, 210/210/215 simplifier. Bands 0-7 = Part 1
# (two per expert subtopic), bands 8-10 = fresh Part 2 bands.

BAND = config.frame_height


def band_shift(k):
    return DOWN * BAND * k


def strike(m):
    return Line(m.get_corner(DL) + 0.08 * DL, m.get_corner(UR) + 0.08 * UR,
                color=RED, stroke_width=6)


class DrainageBasinsManagementSession(MovingCameraScene):
    def next_band(self, k):
        self.play(self.camera.frame.animate.move_to(band_shift(k)), run_time=0.8)

    def construct(self):
        # Intro beat: topic held full-screen while intro.md plays.
        self.wait(14)

        # ===== Part 1 — Expert =====
        # --- Band 0 (subtopic_1): superimposed drainage ---
        title = Tex("Rivers That Ignore the Rock").scale(1.3).to_edge(UP)
        self.play(Write(title))
        self.wait(2)
        s0 = Tex(r"Normal patterns: dendritic, trellis, radial —").scale(1.0).shift(UP * 1.3)
        s0b = Tex(r"a conversation between water and rock").scale(1.0).shift(UP * 0.6)
        self.play(Write(s0))
        self.play(Write(s0b))
        self.wait(2.5)
        # Superimposed: young flat cover over an old folded structure
        cover = Rectangle(width=7.0, height=0.8, color=GREY).shift(DOWN * 0.6)
        cover_lab = Tex(r"young flat cover").scale(0.85).shift(DOWN * 0.6 + RIGHT * 4.9)
        fold1 = Line(LEFT * 3.5 + DOWN * 2.6, LEFT * 1.8 + DOWN * 1.4, color=WHITE, stroke_width=4)
        fold2 = Line(LEFT * 1.8 + DOWN * 1.4, DOWN * 2.6, color=WHITE, stroke_width=4)
        fold3 = Line(DOWN * 2.6, RIGHT * 1.8 + DOWN * 1.4, color=WHITE, stroke_width=4)
        fold4 = Line(RIGHT * 1.8 + DOWN * 1.4, RIGHT * 3.5 + DOWN * 2.6, color=WHITE, stroke_width=4)
        fold_lab = Tex(r"buried folded structure").scale(0.85).shift(DOWN * 3.2)
        self.play(Create(cover), Write(cover_lab))
        self.play(Create(fold1), Create(fold2), Create(fold3), Create(fold4))
        self.play(Write(fold_lab))
        self.wait(2)
        river = Arrow(UP * 0.1, DOWN * 2.4, buff=0, color=BLUE)
        riv_lab = Tex(r"river cuts down, keeps its course").scale(0.85).shift(DOWN * 0.1 + LEFT * 4.2)
        self.play(Create(river), Write(riv_lab))
        self.wait(2)
        sup = Tex(r"SUPERIMPOSED: printed from above (Gouritz)").scale(0.95).shift(UP * 2.0)
        self.play(Write(sup))
        self.play(Create(SurroundingRectangle(sup, color=GREEN)))
        self.wait(3)

        # --- Band 1 (subtopic_1): antecedent + the one-line distinction ---
        self.next_band(1)
        b1_t = Tex("Antecedent: the river came first").scale(1.2).shift(band_shift(1) + UP * 2.2)
        self.play(Write(b1_t))
        self.wait(1.5)
        # Land rising into a downcutting river (bandsaw picture)
        riv2 = Arrow(band_shift(1) + LEFT * 4.6 + UP * 0.6, band_shift(1) + RIGHT * 4.6 + UP * 0.6,
                     buff=0, color=BLUE)
        riv2_lab = Tex(r"river, already flowing").scale(0.85).shift(band_shift(1) + UP * 1.2 + LEFT * 2.6)
        self.play(Create(riv2), Write(riv2_lab))
        self.wait(1.5)
        rise1 = Arrow(band_shift(1) + LEFT * 1.2 + DOWN * 2.2, band_shift(1) + LEFT * 1.2 + DOWN * 0.4,
                      buff=0, color=RED)
        rise2 = Arrow(band_shift(1) + RIGHT * 1.2 + DOWN * 2.2, band_shift(1) + RIGHT * 1.2 + DOWN * 0.4,
                      buff=0, color=RED)
        rise_lab = Tex(r"land rises; downcutting keeps pace").scale(0.85).shift(band_shift(1) + DOWN * 2.7)
        self.play(Create(rise1), Create(rise2))
        self.play(Write(rise_lab))
        self.wait(2)
        d1 = Tex(r"Superimposed: let down from a vanished cover").scale(0.95).shift(band_shift(1) + DOWN * 0.9)
        d2 = Tex(r"Antecedent: predates the rising structure").scale(0.95).shift(band_shift(1) + DOWN * 1.7)
        self.play(Write(d1))
        self.wait(2)
        self.play(Write(d2))
        self.play(Create(SurroundingRectangle(d2, color=GREEN)))
        self.wait(2)
        d3 = Tex(r"Both: gorges = dam sites, road corridors").scale(0.95).shift(band_shift(1) + DOWN * 3.3)
        self.play(Write(d3))
        self.wait(3)

        # --- Band 2 (subtopic_2): vocabulary + why catchments matter ---
        self.next_band(2)
        b2_t = Tex("Basin, catchment, watershed").scale(1.2).shift(band_shift(2) + UP * 2.2)
        self.play(Write(b2_t))
        self.wait(1.5)
        v1 = Tex(r"Basin: all land drained by river + tributaries").scale(0.95).shift(band_shift(2) + UP * 1.2)
        v2 = Tex(r"Catchment: the basin as a rain funnel").scale(0.95).shift(band_shift(2) + UP * 0.4)
        v3 = Tex(r"Watershed: the high rim between basins").scale(0.95).shift(band_shift(2) + DOWN * 0.4)
        self.play(Write(v1))
        self.wait(2)
        self.play(Write(v2))
        self.wait(2)
        self.play(Write(v3))
        self.wait(2)
        v4 = Tex(r"A river's health = its catchment's report card").scale(0.95).shift(band_shift(2) + DOWN * 1.3)
        self.play(Write(v4))
        self.play(Create(SurroundingRectangle(v4, color=GREEN)))
        self.wait(2)
        v5 = Tex(r"Matters: supply (Vaal, Lesotho), flood sponge,").scale(0.95).shift(band_shift(2) + DOWN * 2.2)
        v6 = Tex(r"ecology, economy — SA rain 465 vs 860 mm").scale(0.95).shift(band_shift(2) + DOWN * 3.0)
        self.play(Write(v5))
        self.wait(2)
        self.play(Write(v6))
        self.wait(3)

        # --- Band 3 (subtopic_2): why management fails ---
        self.next_band(3)
        b3_t = Tex("Why catchments are poorly managed").scale(1.15).shift(band_shift(3) + UP * 2.2)
        self.play(Write(b3_t))
        self.wait(1.5)
        m1 = Tex(r"1. Fragmented: nobody owns the whole funnel").scale(1.0).shift(band_shift(3) + UP * 1.2)
        m2 = Tex(r"2. Weak enforcement of a good Water Act").scale(1.0).shift(band_shift(3) + UP * 0.4)
        m3 = Tex(r"3. Broken sewage works (the Vaal crisis)").scale(1.0).shift(band_shift(3) + DOWN * 0.4)
        m4 = Tex(r"4. Competing users; ecological reserve last").scale(1.0).shift(band_shift(3) + DOWN * 1.2)
        m5 = Tex(r"5. Short-termism: wetlands drained, dumping").scale(1.0).shift(band_shift(3) + DOWN * 2.0)
        self.play(Write(m1))
        self.wait(2)
        self.play(Write(m2))
        self.wait(2)
        self.play(Write(m3))
        self.wait(2)
        self.play(Write(m4))
        self.wait(2)
        self.play(Write(m5))
        self.wait(3)

        # --- Band 4 (subtopic_3): the eutrophication chain ---
        self.next_band(4)
        b4_t = Tex("Impact 1 — eutrophication, in order").scale(1.15).shift(band_shift(4) + UP * 2.2)
        self.play(Write(b4_t))
        self.wait(1.5)
        e1 = Tex(r"1. Nitrates + phosphates wash in").scale(1.0).shift(band_shift(4) + UP * 1.2)
        e2 = Tex(r"2. Algal bloom (blue-green scum)").scale(1.0).shift(band_shift(4) + UP * 0.4)
        e3 = Tex(r"3. Light blocked, plants below die").scale(1.0).shift(band_shift(4) + DOWN * 0.4)
        e4 = Tex(r"4. Algae die; bacteria decompose them").scale(1.0).shift(band_shift(4) + DOWN * 1.2)
        e5 = Tex(r"5. Oxygen crashes; fish suffocate").scale(1.0).shift(band_shift(4) + DOWN * 2.0)
        self.play(Write(e1))
        self.wait(2)
        self.play(Write(e2))
        self.wait(2)
        self.play(Write(e3))
        self.wait(2)
        self.play(Write(e4))
        self.wait(2)
        self.play(Write(e5))
        self.play(Create(SurroundingRectangle(e5, color=GREEN)))
        self.wait(2)
        e6 = Tex(r"Example: Hartbeespoort Dam, pea-green").scale(0.95).shift(band_shift(4) + DOWN * 2.9)
        self.play(Write(e6))
        self.wait(3)

        # --- Band 5 (subtopic_3): the other three impacts ---
        self.next_band(5)
        b5_t = Tex("Impacts 2--4 on the catchment").scale(1.2).shift(band_shift(5) + UP * 2.2)
        self.play(Write(b5_t))
        self.wait(1.5)
        i1 = Tex(r"Overgrazing: bare crusted soil $\rightarrow$ runoff,").scale(0.95).shift(band_shift(5) + UP * 1.2)
        i1b = Tex(r"silted dams, dongas").scale(0.95).shift(band_shift(5) + UP * 0.4)
        self.play(Write(i1))
        self.play(Write(i1b))
        self.wait(2.5)
        i2 = Tex(r"Deforestation: roots gone, slopes shed fast;").scale(0.95).shift(band_shift(5) + DOWN * 0.4)
        i2b = Tex(r"alien wattles + gums STEAL streamflow").scale(0.95).shift(band_shift(5) + DOWN * 1.2)
        self.play(Write(i2))
        self.play(Write(i2b))
        self.wait(2.5)
        i3 = Tex(r"Settlement: sealed ground = flash floods,").scale(0.95).shift(band_shift(5) + DOWN * 2.1)
        i3b = Tex(r"shacks on floodplains, wetlands built over").scale(0.95).shift(band_shift(5) + DOWN * 2.9)
        self.play(Write(i3))
        self.play(Write(i3b))
        self.wait(3)

        # --- Band 6 (subtopic_4): strategies, rim to mouth ---
        self.next_band(6)
        b6_t = Tex("Strategies from rim to mouth").scale(1.2).shift(band_shift(6) + UP * 2.2)
        self.play(Write(b6_t))
        self.wait(1.5)
        g1 = Tex(r"Govern by basin: catchment agencies (NWA)").scale(0.95).shift(band_shift(6) + UP * 1.2)
        g2 = Tex(r"Guard water factories: Boland, Drakensberg").scale(0.95).shift(band_shift(6) + UP * 0.4)
        g3 = Tex(r"Repair wetlands (Working for Wetlands)").scale(0.95).shift(band_shift(6) + DOWN * 0.4)
        g4 = Tex(r"Fix sewage, treat mine acid, buffer strips").scale(0.95).shift(band_shift(6) + DOWN * 1.2)
        g5 = Tex(r"Farm gently: contours, stocking rates").scale(0.95).shift(band_shift(6) + DOWN * 2.0)
        g6 = Tex(r"Demand: fix leaks, recycle, ecological flow").scale(0.95).shift(band_shift(6) + DOWN * 2.8)
        self.play(Write(g1))
        self.wait(2)
        self.play(Write(g2))
        self.wait(2)
        self.play(Write(g3))
        self.wait(2)
        self.play(Write(g4))
        self.wait(2)
        self.play(Write(g5))
        self.wait(1.5)
        self.play(Write(g6))
        self.wait(3)

        # --- Band 7 (subtopic_4): Working for Water case study ---
        self.next_band(7)
        b7_t = Tex("Case study: Working for Water (1995--)").scale(1.15).shift(band_shift(7) + UP * 2.2)
        self.play(Write(b7_t))
        self.wait(1.5)
        w1 = Tex(r"Problem: alien wattle, gum, pine, hakea").scale(1.0).shift(band_shift(7) + UP * 1.2)
        w2 = Tex(r"guzzle streamflow, crowd fynbos, feed fires").scale(1.0).shift(band_shift(7) + UP * 0.4)
        self.play(Write(w1))
        self.play(Write(w2))
        self.wait(2.5)
        w3 = Tex(r"Method: cut, poison, burn — then follow up").scale(1.0).shift(band_shift(7) + DOWN * 0.5)
        self.play(Write(w3))
        self.wait(2.5)
        w4 = Tex(r"Dividend 1: measured streamflow returned").scale(1.0).shift(band_shift(7) + DOWN * 1.4)
        w5 = Tex(r"Dividend 2: tens of thousands employed").scale(1.0).shift(band_shift(7) + DOWN * 2.2)
        self.play(Write(w4))
        self.wait(2)
        self.play(Write(w5))
        self.wait(2)
        w6 = Tex(r"Water + jobs in one budget — a world first").scale(1.0).shift(band_shift(7) + DOWN * 3.1)
        self.play(Write(w6))
        self.play(Create(SurroundingRectangle(w6, color=GREEN)))
        self.wait(3)

        # ===== Part 2 — Simplifier =====
        # --- Band 8 (subtopic_5): the funnel everyone lives in ---
        self.next_band(8)
        b8_t = Tex("The funnel everyone lives in").scale(1.2).shift(band_shift(8) + UP * 2.2)
        self.play(Write(b8_t))
        self.wait(2)
        # Funnel: two slanted lines meeting at the river mouth
        fn_l = Line(band_shift(8) + LEFT * 3.6 + UP * 1.4, band_shift(8) + LEFT * 0.6 + DOWN * 0.6,
                    color=WHITE, stroke_width=5)
        fn_r = Line(band_shift(8) + RIGHT * 3.6 + UP * 1.4, band_shift(8) + RIGHT * 0.6 + DOWN * 0.6,
                    color=WHITE, stroke_width=5)
        fn_spout = Arrow(band_shift(8) + DOWN * 0.6, band_shift(8) + DOWN * 1.8, buff=0, color=BLUE)
        fn_lab = Tex(r"rim = watershed; spout = the river").scale(0.9).shift(band_shift(8) + UP * 1.9 + RIGHT * 0.2)
        self.play(Create(fn_l), Create(fn_r))
        self.play(Create(fn_spout))
        self.play(Write(fn_lab))
        self.wait(2)
        f1 = Tex(r"Whatever happens in the funnel ends in the river").scale(0.95).shift(band_shift(8) + DOWN * 2.3)
        self.play(Write(f1))
        self.play(Create(SurroundingRectangle(f1, color=GREEN)))
        self.wait(2.5)
        f2 = Tex(r"Dry country: Joburg drinks the Vaal's funnel").scale(0.95).shift(band_shift(8) + DOWN * 3.1)
        self.play(Write(f2))
        self.wait(2.5)
        f3 = Tex(r"Gorges: printed from above, or older than hills").scale(0.9).shift(band_shift(8) + UP * 2.9 + RIGHT * 0.1)
        self.play(Write(f3))
        self.wait(3)

        # --- Band 9 (subtopic_6): the fish tank that turned green ---
        self.next_band(9)
        b9_t = Tex("The fish tank that turned green").scale(1.2).shift(band_shift(9) + UP * 2.2)
        self.play(Write(b9_t))
        self.wait(2)
        t1 = Tex(r"Overfeed the tank $\rightarrow$ water goes rich").scale(1.0).shift(band_shift(9) + UP * 1.2)
        self.play(Write(t1))
        self.wait(2)
        t2 = Tex(r"Six beats: feed, bloom, dark, die, rot, suffocate").scale(0.95).shift(band_shift(9) + UP * 0.4)
        self.play(Write(t2))
        self.play(Create(SurroundingRectangle(t2, color=GREEN)))
        self.wait(2.5)
        t3 = Tex(r"= EUTROPHICATION (over-feeding); the green").scale(0.95).shift(band_shift(9) + DOWN * 0.5)
        t3b = Tex(r"tank is Hartbeespoort Dam").scale(0.95).shift(band_shift(9) + DOWN * 1.3)
        self.play(Write(t3))
        self.play(Write(t3b))
        self.wait(2.5)
        t4 = Tex(r"Also: factory poisons, acid mine water, plastic").scale(0.9).shift(band_shift(9) + DOWN * 2.0)
        self.play(Write(t4))
        self.wait(2)
        t5 = Tex(r"Bare veld seals; alien trees drink the river;").scale(0.9).shift(band_shift(9) + DOWN * 2.6)
        t5b = Tex(r"tar cannot drink, so storms turn to floods").scale(0.9).shift(band_shift(9) + DOWN * 3.2)
        self.play(Write(t5))
        self.play(Write(t5b))
        self.wait(3)

        # --- Band 10 (subtopic_7): saws, sponges and the water factories ---
        self.next_band(10)
        b10_t = Tex("Saws, sponges and the water factories").scale(1.15).shift(band_shift(10) + UP * 2.2)
        self.play(Write(b10_t))
        self.wait(2)
        x1 = Tex(r"Guard the mountain water factories").scale(1.0).shift(band_shift(10) + UP * 1.2)
        x2 = Tex(r"Rebuild the wetland sponges; police the pipes").scale(0.95).shift(band_shift(10) + UP * 0.4)
        x3 = Tex(r"Farm gently; use less; one team per funnel").scale(0.95).shift(band_shift(10) + DOWN * 0.4)
        self.play(Write(x1))
        self.wait(2)
        self.play(Write(x2))
        self.wait(2)
        self.play(Write(x3))
        self.wait(2)
        x4 = Tex(r"Working for Water, 1995: cut the thirsty aliens").scale(0.95).shift(band_shift(10) + DOWN * 1.3)
        self.play(Write(x4))
        self.wait(2)
        x5 = Tex(r"Pays twice: streamflow back + jobs for").scale(0.95).shift(band_shift(10) + DOWN * 2.1)
        x5b = Tex(r"tens of thousands — the model answer").scale(0.95).shift(band_shift(10) + DOWN * 2.9)
        self.play(Write(x5))
        self.play(Write(x5b))
        self.play(Create(SurroundingRectangle(x5b, color=GREEN)))
        self.wait(4)
